### ISSUE TITLE
[Feature]:  launch puppeteer on android

### ISSUE THREAD

**Issue by j67Sv89n** [puppeteer/puppeteer#10028]
### Feature description

I try launch puppeteer on android and want ask, it's possible didi with puppeteer or best way try selenium webdriver for that?

```
localhost:~/puppeteer-on-termux# node --trac
e-warnings index.js
/root/puppeteer-on-termux/node_modules/puppeteer-core/lib/cjs/puppeteer/common/assert.js:26
        throw new Error(message);
              ^

Error: Unsupported platform: android
    at exports.assert (/root/puppeteer-on-termux/node_modules/puppeteer-core/lib/cjs/puppeteer/common/assert.js:26:15)
    at BrowserFetcher.setPlatform (/root/puppeteer-on-termux/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserFetcher.js:175:25)
    at new BrowserFetcher (/root/puppeteer-on-termux/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserFetcher.js:159:14)
    at resolveExecutablePath (/root/puppeteer-on-termux/node_modules/puppeteer-core/lib/cjs/puppeteer/node/Launcher.js:442:28)
    at ChromeLauncher.launch (/root/puppeteer-on-termux/node_modules/puppeteer-core/lib/cjs/puppeteer/node/Launcher.js:77:53)
    at async file:///root/puppeteer-on-termux/index.js:4:19

Node.js v19.6.1
localhost:~/puppeteer-on-termux#
```

**Comment by OrKoN** [comment]
We don’t support launching without an executable path (I assume you do that) since we cannot download and install the browser on Android: see https://github.com/puppeteer/puppeteer/issues/9460#issuecomment-1370589669
