### ISSUE TITLE
[Bug]: ProtocolError: Network.getResponseBody timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.

### ISSUE THREAD

**Issue by vgoklani** [puppeteer/puppeteer#10091]
### Bug expectation

I expect this error to be managed by an exception handler, and not crash the app.

this is the full stack-trace:

```
ProtocolError: Network.getResponseBody timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
    at new Callback (/root/server/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:61:35)
    at CallbackRegistry.create (/root/server/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:106:26)
    at Connection._rawSend (/root/server/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:216:26)
    at CDPSessionImpl.send (/root/server/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:425:78)
    at next (/root/server/node_modules/puppeteer-extra-plugin-stealth/evasions/sourceurl/index.js:34:41)
    at CDPSessionImpl.send (/root/server/node_modules/puppeteer-extra-plugin-stealth/evasions/sourceurl/index.js:67:18)
    at /root/server/node_modules/puppeteer-core/lib/cjs/puppeteer/common/HTTPResponse.js:99:100
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async HTTPResponse.text (/root/server/node_modules/puppeteer-core/lib/cjs/puppeteer/api/HTTPResponse.js:98:25)
    at async HTTPResponse.json (/root/server/node_modules/puppeteer-core/lib/cjs/puppeteer/api/HTTPResponse.js:110:25)
```

### Bug behavior

- [X] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
cannot share the example :)
```

### Error string

ProtocolError: Network.getResponseBody timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.

### Puppeteer version

latest

### Node version

latest

### Package manager

npm

### Package manager version

latest

### Operating system

Linux

**Comment by OrKoN** [comment]
Please provide a reproducible example: Do you call `response.json()` in your code? do you wrap it in a try/catch?

**Comment by vgoklani** [comment]
I wrapped the response.json() in a try/catch, but the error is clearly happening upstream. I can't share the code unfortunately, and this error only occurs after running for several hours. Could you please explain what the error message is saying, it's not clear what it means or where it's occuring. More specifically, what does this mean:

    Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.

Full error: 

```bash
ProtocolError: Network.getResponseBody timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
    at new Callback (/root/server/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:61:35)
    at CallbackRegistry.create (/root/server/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:106:26)
    at Connection._rawSend (/root/server/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:216:26)
    at CDPSessionImpl.send (/root/server/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:425:78)
    at next (/root/server/node_modules/puppeteer-extra-plugin-stealth/evasions/sourceurl/index.js:34:41)
    at CDPSessionImpl.send (/root/server/node_modules/puppeteer-extra-plugin-stealth/evasions/sourceurl/index.js:67:18)
    at /root/server/node_modules/puppeteer-core/lib/cjs/puppeteer/common/HTTPResponse.js:99:100
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async HTTPResponse.text (/root/server/node_modules/puppeteer-core/lib/cjs/puppeteer/api/HTTPResponse.js:98:25)
    at async HTTPResponse.json (/root/server/node_modules/puppeteer-core/lib/cjs/puppeteer/api/HTTPResponse.js:110:25)
```

**Comment by OrKoN** [comment]
Can you create a sample script that reproduces this? Try/catch should help here. Are you using any puppeteer extensions that might be calling .json? The error means that the browser is not providing a response to a CDP call within 180 sec which is an indication of a bug (likely in the browser). You can change the timeout in the launch/connect options and increase it but it is unlikely to help as 180 sec should be more than enough for getting JSON for a respond.

**Comment by hobik** [comment]
HEllo did you find solution, I have same problem?

**Comment by hems** [comment]
same problem here, the log just goes to stdout even tough i have a try catch and clutter my logs whe it happens.

**Comment by lfreneda** [comment]
news?

**Comment by MouadBH** [comment]
any update?

**Comment by PiyushSuneja02** [comment]
Hi Guys,
Can anybody help me I am getting same issue

**Comment by kennMicepad** [comment]
+1

**Comment by cgtarmenta** [comment]
In my case this can be bypassed by setting headless: true instead of headless: 'new', but then I got a nasty warning.

This does not happen when the code runs locally,  only when it runs on docker using 
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

**Comment by PiyushSuneja02** [comment]
@cgtarmenta same is happening in my case. Please help if you get any solutions. Highly Appreciated

**Comment by cgtarmenta** [comment]
@PiyushSuneja02 

If you are using puppeteer < 22.x.x
try something like this:
```javascript
const browser = await puppeteer.launch({
      headless: true,
      args: ['--no-sandbox', '--disable-setuid-sandbox'],
      executablePath: process.env.NODE_ENV === 'production' ?
          process.env.PUPPETEER_EXECUTABLE_PATH :
          puppeteer.executablePath(),
});
```
or
```javascript
const browser = await puppeteer.launch({
      headless: 'old,
      args: ['--no-sandbox', '--disable-setuid-sandbox'],
      executablePath: process.env.NODE_ENV === 'production' ?
          process.env.PUPPETEER_EXECUTABLE_PATH :
          puppeteer.executablePath(),
});
````
if you are in v22 or above:

```javascript
const browser = await puppeteer.launch({
      headless: 'shell',
      args: ['--no-sandbox', '--disable-setuid-sandbox'],
      executablePath: process.env.NODE_ENV === 'production' ?
          process.env.PUPPETEER_EXECUTABLE_PATH :
          puppeteer.executablePath(),
});
```

As far as I understand from reading [here](https://developer.chrome.com/docs/chromium/new-headless/#use_headless_mode), is the new headless mode generates hidden platform windows, and that could be the source of the problem on docker stripped environments. Setting the headless mode to the old one doesn't try to build those platform windows, and that's why I think this works.

Hope this helps you. Cheers.
