### ISSUE TITLE
[Bug]: `Cannot extract value when objectId is given` when navigating to https://espn.com

### ISSUE THREAD

**Issue by adamraine** [puppeteer/puppeteer#10224]
### Bug expectation

I expected the script to run without error.

Instead the script throws the following error:

```
Error: Cannot extract value when objectId is given
    at assert (file:///Users/asraine/lighthouse/node_modules/puppeteer-core/lib/esm/puppeteer/util/assert.js:25:15)
    at valueFromRemoteObject (file:///Users/asraine/lighthouse/node_modules/puppeteer-core/lib/esm/puppeteer/common/util.js:212:5)
    at createClientError (file:///Users/asraine/lighthouse/node_modules/puppeteer-core/lib/esm/puppeteer/common/util.js:95:16)
    at CDPPage._CDPPage_handleException (file:///Users/asraine/lighthouse/node_modules/puppeteer-core/lib/esm/puppeteer/common/Page.js:890:62)
    at file:///Users/asraine/lighthouse/node_modules/puppeteer-core/lib/esm/puppeteer/common/Page.js:183:100
    at file:///Users/asraine/lighthouse/node_modules/puppeteer-core/lib/esm/third_party/mitt/index.js:1:248
    at Array.map (<anonymous>)
    at Object.emit (file:///Users/asraine/lighthouse/node_modules/puppeteer-core/lib/esm/third_party/mitt/index.js:1:232)
    at CDPSessionImpl.emit (file:///Users/asraine/lighthouse/node_modules/puppeteer-core/lib/esm/puppeteer/common/EventEmitter.js:81:22)
    at CDPSessionImpl._onMessage (file:///Users/asraine/lighthouse/node_modules/puppeteer-core/lib/esm/puppeteer/common/Connection.js:435:18)
```

I was only able to get this to work with `puppeteer-core` and the latest Chrome canary (115.0.5787.2)

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer-core';

const browser = await puppeteer.launch({
  headless: false,
  // Path to chrome canary
  executablePath: process.env.CHROME_PATH,
});
const page = await browser.newPage();
await page.goto('https://espn.com')
```

### Error string

Cannot extract value when objectId is given

### Puppeteer version

20.3.0

### Node version

16.20.0

### Package manager

yarn

### Package manager version

1.22.19

### Operating system

macOS

**Comment by fturmel** [comment]
I've had a similar issue today with Puppeteer 20.3.0 and Node 18.16.0, specifically with the domain https://marramstudios.com. I went through thousands of urls and this is the one domain that fails every time. 

Just tried with https://espn.com/ and I also got the same error but it's failing maybe 75% of the time.

```js
import puppeteer from 'puppeteer';

const browser = await puppeteer.launch({ headless: 'new' });
const page = await browser.newPage();
await page.goto('https://marramstudios.com');
await browser.close();

```

```
file:///Users/fturmel/Documents/projects/forks/thecodingtrain.com/node_modules/puppeteer-core/lib/esm/puppeteer/util/assert.js:25
        throw new Error(message);
              ^

Error: Cannot extract value when objectId is given
    at assert (file:///Users/fturmel/Documents/projects/forks/thecodingtrain.com/node_modules/puppeteer-core/lib/esm/puppeteer/util/assert.js:25:15)
    at valueFromRemoteObject (file:///Users/fturmel/Documents/projects/forks/thecodingtrain.com/node_modules/puppeteer-core/lib/esm/puppeteer/common/util.js:212:5)
    at createClientError (file:///Users/fturmel/Documents/projects/forks/thecodingtrain.com/node_modules/puppeteer-core/lib/esm/puppeteer/common/util.js:95:16)
    at CDPPage._CDPPage_handleException (file:///Users/fturmel/Documents/projects/forks/thecodingtrain.com/node_modules/puppeteer-core/lib/esm/puppeteer/common/Page.js:890:62)
    at file:///Users/fturmel/Documents/projects/forks/thecodingtrain.com/node_modules/puppeteer-core/lib/esm/puppeteer/common/Page.js:183:100
    at file:///Users/fturmel/Documents/projects/forks/thecodingtrain.com/node_modules/puppeteer-core/lib/esm/third_party/mitt/index.js:1:248
    at Array.map (<anonymous>)
    at Object.emit (file:///Users/fturmel/Documents/projects/forks/thecodingtrain.com/node_modules/puppeteer-core/lib/esm/third_party/mitt/index.js:1:232)
    at CDPSessionImpl.emit (file:///Users/fturmel/Documents/projects/forks/thecodingtrain.com/node_modules/puppeteer-core/lib/esm/puppeteer/common/EventEmitter.js:81:22)
    at CDPSessionImpl._onMessage (file:///Users/fturmel/Documents/projects/forks/thecodingtrain.com/node_modules/puppeteer-core/lib/esm/puppeteer/common/Connection.js:435:18)

Node.js v18.16.0
```

**Comment by Onyoursix** [comment]
I'm also getting this error with a specific page on a website.

`import puppeteer from 'puppeteer'

async function checkUrl(url) {
    const browser = await puppeteer.launch({ headless: true, args: ['--ignore-certificate-errors'] });
    const page = await browser.newPage();
    await page.goto(url, { waitUntil: "networkidle0" });
}
checkUrl('https://www.laytoncity.org/LC/PlanningZoning/PublicNotices');`

`
file:///home/six/Development/op_scraper/node_modules/puppeteer-core/lib/esm/puppeteer/util/assert.js:25
        throw new Error(message);
              ^

Error: Cannot extract value when objectId is given
    at assert (file:///home/six/Development/op_scraper/node_modules/puppeteer-core/lib/esm/puppeteer/util/assert.js:25:15)
    at valueFromRemoteObject (file:///home/six/Development/op_scraper/node_modules/puppeteer-core/lib/esm/puppeteer/common/util.js:212:5)
    at createClientError (file:///home/six/Development/op_scraper/node_modules/puppeteer-core/lib/esm/puppeteer/common/util.js:95:16)
    at CDPPage._CDPPage_handleException (file:///home/six/Development/op_scraper/node_modules/puppeteer-core/lib/esm/puppeteer/common/Page.js:890:62)
    at file:///home/six/Development/op_scraper/node_modules/puppeteer-core/lib/esm/puppeteer/common/Page.js:183:100
    at file:///home/six/Development/op_scraper/node_modules/puppeteer-core/lib/esm/third_party/mitt/index.js:1:248
    at Array.map (<anonymous>)
    at Object.emit (file:///home/six/Development/op_scraper/node_modules/puppeteer-core/lib/esm/third_party/mitt/index.js:1:232)
    at CDPSessionImpl.emit (file:///home/six/Development/op_scraper/node_modules/puppeteer-core/lib/esm/puppeteer/common/EventEmitter.js:81:22)
    at CDPSessionImpl._onMessage (file:///home/six/Development/op_scraper/node_modules/puppeteer-core/lib/esm/puppeteer/common/Connection.js:435:18)

Node.js v20.1.0

`

**Comment by grybykm** [comment]
It happens to me in the playwright as well. Maybe it's related to the chromium upgrade? Mine is Chromium `114.0.5735.26`.

**Comment by grybykm** [comment]
It stopped working for me after the update from `20.1.2`

**Comment by dotuan9x** [comment]
> 

Me too
