### ISSUE TITLE
Page crashed, no obvious errors

### ISSUE THREAD

**Issue by knownasilya** [puppeteer/puppeteer#1024]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.11
* Platform / OS version: GCP container engine/debian node 8.6-slim image
* URLs (if applicable): https://gloucesterma.beta.mapgeo.io/api/printablemap?url=https%3A%2F%2Fgloucesterma.beta.mapgeo.io%2Fproperties%2F92-34-2%3Flatlng%3D42.628666%252C-70.685595%26modal%3Dprint%26zoom%3D18&token=&title=&layout=standard&width=1380&height=884&scale=

**What steps will reproduce the problem?**

My screenshot code looks like so:

```js
  const pageUrl = 'https://gloucesterma.beta.mapgeo.io/properties/92-34-2?latlng=42.628666%2C-70.685595&modal=print&zoom=18';
  const browser = await puppeteer.launch({
    ignoreHTTPSErrors: true,
    args: ['--no-sandbox']
  });
  const page = await browser.newPage();

  page.on('console', (msg) => {
    console.log('screenshot browser console message: ', msg);
  });

  page.on('error', (error) => {
    console.log('screenshot browser error: ', error);
  });

  await page.setViewport({ width: 956, height: 891 });
  await page.goto(pageUrl, { waitUntil: 'networkidle' });
  await page.waitFor(15000);

  const imageBuffer = await page.screenshot();

  try {
    await browser.close();
  } catch(e) {
    console.log(e);
  }

  console.log(imageBuffer.toString('base64'));
```

**What is the expected result?**

I expect a pdf to be created with a screenshot of a map.

**What happens instead?**

I get no screenshot, and this shows up in the logs:

```
screenshot browser error:  Error: Page crashed!
2017-10-12T17:12:27.457689833Z     at Page._onTargetCrashed (/usr/src/mapgeo/node_modules/puppeteer/lib/Page.js:92:24)
2017-10-12T17:12:27.457693225Z     at Session.Page.client.on.event (/usr/src/mapgeo/node_modules/puppeteer/lib/Page.js:88:56)
2017-10-12T17:12:27.457695651Z     at emitOne (events.js:115:13)
2017-10-12T17:12:27.457698083Z     at Session.emit (events.js:210:7)
2017-10-12T17:12:27.457706544Z     at Session._onMessage (/usr/src/mapgeo/node_modules/puppeteer/lib/Connection.js:199:12)
2017-10-12T17:12:27.457709249Z     at Connection._onMessage (/usr/src/mapgeo/node_modules/puppeteer/lib/Connection.js:98:19)
2017-10-12T17:12:27.457711649Z     at emitOne (events.js:115:13)
2017-10-12T17:12:27.457713779Z     at WebSocket.emit (events.js:210:7)
2017-10-12T17:12:27.457718282Z     at Receiver._receiver.onmessage (/usr/src/mapgeo/node_modules/ws/lib/WebSocket.js:143:47)
2017-10-12T17:12:27.457720731Z     at Receiver.dataMessage (/usr/src/mapgeo/node_modules/ws/lib/Receiver.js:389:14)
2017-10-12T17:12:27.457722831Z     at Receiver.getData (/usr/src/mapgeo/node_modules/ws/lib/Receiver.js:330:12)
2017-10-12T17:12:27.457725005Z     at Receiver.startLoop (/usr/src/mapgeo/node_modules/ws/lib/Receiver.js:165:16)
2017-10-12T17:12:27.457727122Z     at Receiver.add (/usr/src/mapgeo/node_modules/ws/lib/Receiver.js:139:10)
2017-10-12T17:12:27.457729237Z     at Socket._ultron.on (/usr/src/mapgeo/node_modules/ws/lib/WebSocket.js:139:22)
2017-10-12T17:12:27.457731283Z     at emitOne (events.js:115:13)
2017-10-12T17:12:27.457733319Z     at Socket.emit (events.js:210:7)
2017-10-12T17:12:27.457735306Z     at addChunk (_stream_readable.js:266:12)
2017-10-12T17:12:27.45773785Z     at readableAddChunk (_stream_readable.js:253:11)
2017-10-12T17:12:27.457739903Z     at Socket.Readable.push (_stream_readable.js:211:10)
2017-10-12T17:12:27.45774204Z     at TCP.onread (net.js:587:20)
```

**Comment by vsemozhetbyt** [comment]
I get this if I try to open the URL in Chrome:

![1](https://user-images.githubusercontent.com/10393198/31509847-8ba45966-af8b-11e7-89b2-ec1addffbd22.png)

**Comment by knownasilya** [comment]
I use `ignoreHTTPSErrors` above, so that should be avoided, no? If not, shouldn't it just timeout or take a screenshot of that?

**Comment by knownasilya** [comment]
Console of the page returns the following:

```
2017-10-12T17:45:17.76299942Z screenshot browser console message:  cartodb.js 3.15.10
2017-10-12T17:45:18.504531146Z screenshot browser console message:  ServiceWorker Registration Error: 
2017-10-12T17:45:20.428029681Z screenshot browser console message:  property.related setup
```

The service worker registration error is caught and just logged. The setup message means that it entered the route of the app.

**Comment by knownasilya** [comment]
Sometimes it works, just not for all requests. Haven't found a working one that I can link to.

**Comment by aslushnikov** [comment]
@knownasilya There's a ton of undefined variables if I try to run your snippet as-is. Can you please update your snippet so that it's runnable? It will save me a lot of time.

**Comment by knownasilya** [comment]
@aslushnikov I've edited the code example above to make it more self-contained. Thanks for taking the time to look!

On a related note, has puppeteer been working better on App Engine instead of Container Engine?

**Comment by ebidel** [comment]
@knownasilya Puppeteer works fairly well in GAE for basic things. AFAICT, one of the main issues right now that's causing pages to crash is https://bugs.chromium.org/p/chromium/issues/detail?id=736452. Please star that one!

**Comment by knownasilya** [comment]
@ebidel seems like GAE would have similar issues since node.js runs in the flexible environment, which uses Docker under the hood, as far as I can tell.

**Comment by ebidel** [comment]
Indeed!

**Comment by tglines** [comment]
Setting the `docker run --shm-size 1G ...` param or something higher solved this issue for me, but I was lucky enough to be able to specify the size.  Starred the bug mentioned by @ebidel

**Comment by ebidel** [comment]
Let's close this in favor of the upstream chromium bug. Not much we can do from the Puppeteer side until that's fixed.

**Comment by dmush** [comment]
I got it working on GAE custom flexible environment with `VOLUME /dev/shm` in my Dockerfile. I'm not sure that this is a good idea. This slows things down but works in my case. So it might be considered as a temporary solution while waiting for fix for Chromium.

**Comment by endel** [comment]
I guess the `"Page crashed!"` errors can also be related to not enough swap memory. I've increased my swap memory to 1G and haven't seen these errors anymore.
