### ISSUE TITLE
[Bug]: Error: Failed to launch the browser process!

### ISSUE THREAD

**Issue by janaratolonbaeva** [puppeteer/puppeteer#10251]
### Bug expectation

I expected that build wouldn't fail when I upgraded puppeteer from v19 to v20, I use --headless:"new" in my config file. In locale build succeeded, but in production build it failed. We use AWS, AWS AppSync, Node 18, Gatsby 4, Jest 29, Apollo/client 3

**But error occur:** 
"Failed to launch the browser process! /root/.cache/puppeteer/chrome/linux-113.0.5672.63/chrome-linux64/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory"

### Bug behavior

- [X] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
It not important, I added only for example, because this field is required

/* Local dependencies */
import { getLabelFromTranslation, getLocale } from './helpers';

class GeneralHelper extends Helper {
  helpers: any;

  async openBrowserAndGoToLoginPage() {
    const I = this.helpers['Puppeteer'];

    await I.amOnPage('/');
    await I.wait(2);
    await I.click('.menu-user-icon');
    await I.wait(2);
    await I.amOnPage(`/login`);
  }
}
```

### Error string

"Failed to launch the browser process! /root/.cache/puppeteer/chrome/linux-113.0.5672.63/chrome-linux64/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory"

### Puppeteer configuration

```TypeScript
/* External dependencies */
require('ts-node/register');
const { setHeadlessWhen } = require('@codeceptjs/configure');

/* Local dependencies */
const { atomize } = require('./presettings.ts');

// turn on headless mode when running with HEADLESS=true environment variable
// HEADLESS=true npx codecept run
setHeadlessWhen(process.env.NODE_ENV);
process.setMaxListeners(Infinity);

exports.config = {
  tests: './integration-tests/tests/**_test.ts',
  output: './integration-tests/output',
  helpers: {
    Puppeteer: {
      url: `https://${process.env.GATSBY_SITE_DOMAIN}`,
      show: false,
      headless: process.env.STAGE === '',
      windowSize: '1420x768',
      chrome: {
        args: [
          '--start-maximized',
          '--lang=en-US,ru-RU,ky-KG',
          '--no-sandbox',
          '--disable-setuid-sandbox',
          '--disable-dev-shm-usage',
          '--headless=new'
        ],
      },
    },
    GeneralHelper: {
      require: './helpers/general.ts',
    },
    LocaleHelper: {
      require: './helpers/localeHelper.ts',
    },
    LoginHelper: {
      require: './helpers/login.ts',
    },
    TransactionsHelper: {
      require: './helpers/transactions.ts',
    },
    AdminHelper: {
      require: './helpers/admin.ts',
    },
    ManagerHelper: {
      require: './helpers/manager.ts',
    },
    AccountantHelper: {
      require: './helpers/accountant.ts',
    },
  },
  include: {
    I: './steps_file.ts',
  },
  name: 'integration-tests',
  atomize,
  plugins: {
    autoDelay: {
      enabled: true,
    },
    retryFailedStep: {
      enabled: true,
      minTimeout: 5000,
    },
    screenshotOnFail: {
      enabled: true,
    },
  },
  enablePreview: false,
  require: ['ts-node/register'],
};
```

### Puppeteer version

v20.2.1

### Node version

v18.12.1

### Package manager

npm

### Package manager version

v9.6.7

### Operating system

Linux

**Comment by OrKoN** [comment]
I believe dependencies might be missing. See https://pptr.dev/troubleshooting#chrome-doesnt-launch-on-linux for the list of dependencies that chrome requires.

**Comment by janaratolonbaeva** [comment]
@OrKoN sorry, but it didn't work for me. I added these commands in buildspec.yml

`version: 0.2
phases:
  install:
    commands:
      - npm install
      - ldd chrome | grep not
      - yum update nss -y
    runtime-versions:
      nodejs: 18
  build:
    commands:
      - npm run prepare-env
      - npm run build
      - npm test
  post_build:
    commands:
      - npm run deploy
      - npm run def-$STAGE --if-present
      - npm run codecept-$STAGE --if-present
cache:
  paths:
    - node_modules/**/*
reports:
  jest_reports:
    files:
      - jest-report.xml
    file-format: JUNITXML
    base-directory: coverage
`
Where these commands I have to add to?

In codepipeline it failed. 
**Error**: 
`[Container] 2023/05/26 08:07:48 Running command ldd chrome \| grep not 67 | ldd: ./chrome: No such file or directory
`
Please, look at this.

**Comment by janaratolonbaeva** [comment]
Alex, please, open the issue. The problem has not been solved yet.









*---С уважением, Толонбаева Жанара!skype:  janaratolonbaevatelegram:
 https://t.me/zhanara_zhanara <https://t.me/zhanara_zhanara>mobile phone:
 +996700123890*



*whatsapp:  +996700123890accommodation: Kyrgyzstan, Bishkek*

**Comment by aidanwolf** [comment]
Interestingly don't get this error when running locally but as soon as its on Heroku it happens:

```2023-06-10T06:25:57.737166+00:00 app[web.1]: /app/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241
2023-06-10T06:25:57.737180+00:00 app[web.1]:             reject(new Error([
2023-06-10T06:25:57.737186+00:00 app[web.1]:                    ^
2023-06-10T06:25:57.737187+00:00 app[web.1]: 
2023-06-10T06:25:57.737187+00:00 app[web.1]: Error: Failed to launch the browser process!
2023-06-10T06:25:57.737188+00:00 app[web.1]: /app/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory
2023-06-10T06:25:57.737188+00:00 app[web.1]: 
2023-06-10T06:25:57.737188+00:00 app[web.1]: 
2023-06-10T06:25:57.737188+00:00 app[web.1]: TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
2023-06-10T06:25:57.737189+00:00 app[web.1]: 
2023-06-10T06:25:57.737189+00:00 app[web.1]:     at onClose (/app/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241:20)
2023-06-10T06:25:57.737189+00:00 app[web.1]:     at Interface.<anonymous> (/app/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:231:68)
2023-06-10T06:25:57.737189+00:00 app[web.1]:     at Interface.emit (node:events:525:35)
2023-06-10T06:25:57.737190+00:00 app[web.1]:     at Interface.close (node:internal/readline/interface:533:10)
2023-06-10T06:25:57.737190+00:00 app[web.1]:     at Socket.onend (node:internal/readline/interface:259:10)
2023-06-10T06:25:57.737190+00:00 app[web.1]:     at Socket.emit (node:events:525:35)
2023-06-10T06:25:57.737190+00:00 app[web.1]:     at endReadableNT (node:internal/streams/readable:1359:12)
2023-06-10T06:25:57.737191+00:00 app[web.1]:     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
2023-06-10T06:25:57.737193+00:00 app[web.1]: 
2023-06-10T06:25:57.737194+00:00 app[web.1]: Node.js v18.16.0```

**Comment by OrKoN** [comment]
Take a look at https://pptr.dev/troubleshooting#chrome-doesnt-launch-on-linux `libatk1.0-0` is listed as a dependency there. Install it on your heroku server along with other dependencies and it should work.
