### ISSUE TITLE
[Bug]: Error message: failed loading configuration file

### ISSUE THREAD

**Issue by emadaldin-baybars** [puppeteer/puppeteer#10286]
### Bug expectation

Expectation : to work fine without errors 

What actually happened: 

I got this error 

```
[1] [19:02:44] E/configParser - Error code: 105
[1] [19:02:44] E/configParser - Error message: failed loading configuration file projects/examples-e2e/protractor-ci.conf.js
[1] [19:02:44] E/configParser - /opt/actions-runner/_work/portal/portal/packages/sugar-engine/node_modules/puppeteer-core/lib/cjs/puppeteer/common/util.js:403
[1]             callPuppeteer.args ??= new Map();
[1]                                ^^^
[1] 
[1] SyntaxError: Unexpected token '??='
[1]     at wrapSafe (internal/modules/cjs/loader.js:1029:16)
[1]     at Module._compile (internal/modules/cjs/loader.js:1078:[27](https://github.tools.sap/coresystemsFSM/portal/runs/8712421?check_suite_focus=true#step:8:28))
[1]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
[1]     at Module.load (internal/modules/cjs/loader.js:979:32)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:819:12)
[1]     at Module.require (internal/modules/cjs/loader.js:1003:19)
[1]     at require (internal/modules/cjs/helpers.js:107:18)
[1]     at Object.<anonymous> (/opt/actions-runner/_work/portal/portal/packages/sugar-engine/node_modules/puppeteer-core/lib/cjs/puppeteer/common/HTTPRequest.js:18:19)
[1]     at Module._compile (internal/modules/cjs/loader.js:1114:14)
[1]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
[1] protractor projects/examples-e2e/protractor-ci.conf.js exited with code 105
```

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
nothing to add
```

### Error string

[1] [19:02:44] E/configParser - Error message: failed loading configuration file projects/examples-e2e/protractor-ci.conf.js

### Puppeteer configuration

```TypeScript
// Protractor configuration file, see link for more information
// https://github.com/angular/protractor/blob/master/lib/config.ts

const { SpecReporter } = require('jasmine-spec-reporter');
const puppeteer = require('puppeteer');
const execSync = require('child_process').execSync;



exports.config = {
  allScriptsTimeout: 70000,
  specs: [
    './src/**/*.e2e-spec.ts'
  ],
  capabilities: {
    browserName: 'chrome',
    'goog:chromeOptions': {
      args: ["--no-sandbox", "--headless", "--disable-dev-shm-usage", "--disable-gpu", "--window-size=1280,960"],
      binary: puppeteer.executablePath(),
    }
  },
  directConnect: true,
  baseUrl: 'http://localhost:4200/index.html#/',
  framework: 'jasmine',
  jasmineNodeOpts: {
    showColors: true,
    defaultTimeoutInterval: 120000,
    print: function () { }
  },
  logLevel: 'INFO', // 'ERROR'|'WARN'|'INFO'|'DEBUG';
  beforeLaunch: () => {
    // ensure webdriver and chromium are in sync

    console.log('[INFO]' + '='.repeat(99));
    const binary = puppeteer.executablePath();
    console.log('[INFO] using binary ->', binary);

    // Out-commenting logic to update chrome because GHA has recently some issues with it
    // const chromeVersion = execSync(`${binary} --version`, { encoding: 'utf8' }).replace('Chromium ', '');
    // console.log('[INFO] Installed Chromium', chromeVersion);
    // console.log(`[INFO] Setting webdriver to ${chromeVersion}`);
    // console.log(execSync(`./node_modules/protractor/bin/webdriver-manager update --versions.chrome=${chromeVersion}`, { encoding: 'utf8' }));
    console.log('[DONE]' + '='.repeat(99));

  },
  onPrepare() {
    console.log('='.repeat(99));
    require('ts-node').register({
      project: require('path').join(__dirname, './tsconfig.e2e.json')
    });
    jasmine.getEnv().addReporter(new SpecReporter({ spec: { displayStacktrace: true } }));
  }
};
```

### Puppeteer version

20.5.0

### Node version

v18.16.0

### Package manager

npm

### Package manager version

9.5.1

### Operating system

macOS

**Comment by Gabo-Puck** [comment]
I'm getting the same error message. I think that there is something odd with the latest release, because I downgraded my puppeteer version and is working fine.

**Comment by OrKoN** [comment]
What is the node version you are using?

**Comment by OrKoN** [comment]
@emadaldin-baybars are you seeing the error on your machine or on CI?

**Comment by emadaldin-baybars** [comment]
@OrKoN I'm seeing it on CI

**Comment by OrKoN** [comment]
Yep, make sure the node version on CI is at least 16+. We don't support Node 14 anymore as it reached its end-of-life.

**Comment by Lightning00Blade** [comment]
This is coming from `selenium-webdriver` and not Puppeteer.
Puppeteer will update to Chrome 114 when #10298 lands with version `20.6.0, you can try updating then.

**Comment by emadaldin-baybars** [comment]
@Lightning00Blade So what do you suggest to resolve it ?

**Comment by mirekmirik** [comment]
> I'm getting the same error message. I think that there is something odd with the latest release, because I downgraded my puppeteer version and is working fine.

to which version u was downgraded?

**Comment by Lightning00Blade** [comment]
Puppeteer released `20.6.0` which uses Chrome `114.0.5735.90` you can try updating to see if that resolves your issue.

**Comment by gurhanPro** [comment]
"puppeteer": "20.0.0",

setting the version  in package.json to 20 and not '^20' worked for me

**Comment by lukaszdaniel2billennium** [comment]
hi, we have still the same problem with 20.7.4 version - it seems like a typo or something on puppeteer-core lib:
`  /app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/util.js:399
            callPuppeteer.args ??= new Map();
                               ^^^
SyntaxError: Unexpected token '??='
    at compileFunction (<anonymous>)
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/HTTPRequest.js:18:19)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/NetworkManager.js:34:26)` 

can you please take a look?

**Comment by OrKoN** [comment]
Node 14 is not supported.

**Comment by AssouaAlbert** [comment]
> Node 14 is not supported.

I have been trying to run my Express server which uses Puppeteer through a Cpanel account I have. I had to look into the log and found this problem. 

There are limited versions of Node versions; 6, 8, 9, 10, 11, 12, and 14. My question is: will any of these work (Except 14 as mentioned in your last answer)?

**Comment by OrKoN** [comment]
@AssouaAlbert no, none of those versions are supported anymore. See https://github.com/nodejs/release#release-schedule

**Comment by Eugene-Mokrushin** [comment]
> "puppeteer": "20.0.0",
> 
> setting the version in package.json to 20 and not '^20' worked for me

Downgrading from 20.9.0 to 20.0.0 solved the issues for me. Thanks

**Comment by louzanizineddine** [comment]
> 

Thanks it worked for me.

**Comment by HongYangHT** [comment]
thanks it worked

**Comment by C-onnor** [comment]
I had this error only after compiling app to Windows x64 using nexe library. After downgrading puppeteer to 19.0.4, then again compiling using nexe, the program works with no errors.

**Comment by digisidekickGit1** [comment]
/home/ourofppi/nodevenv/assuredensure.rankarts.in/14/lib/node_modules/puppeteer-core/lib/cjs/puppeteer/common/util.js:389
            callPuppeteer.args ??= new Map();
                               ^^^

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/ourofppi/nodevenv/assuredensure.rankarts.in/14/lib/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Browser.js:21:19)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
/home/ourofppi/nodevenv/assuredensure.rankarts.in/14/lib/node_modules/puppeteer-core/lib/cjs/puppeteer/common/util.js:389
            callPuppeteer.args ??= new Map();

my package.json file
    "axios": "^1.2.2",
    "compression": "^1.7.4",
    "convert-csv-to-json": "^1.4.0",
    "cookie-parser": "^1.4.6",
    "cors": "^2.8.5",
    "csv-parse": "^5.3.3",
    "csvtojson": "^2.0.10",
    "dotenv": "^16.0.3",
    "ejs": "^3.1.9",
    "exceljs": "^4.3.0",
    "express": "^4.18.2",
    "jsdom": "^22.1.0",
    "jsonwebtoken": "^8.5.1",
    "jspdf": "^2.5.1",
    "jspdf-autotable": "^3.6.0",
    "mongoose": "^6.7.2",
    "multer": "^1.4.5-lts.1",
    "nodemailer": "^6.9.0",
    "nodemon": "^2.0.20",
    "puppeteer": "^21.2.1",
    "react-pdf": "^7.3.3",
    "selenium-webdriver": "^4.11.1"
