### ISSUE TITLE
[Bug]: page.evaluate error message lost for asynchronous react error

### ISSUE THREAD

**Issue by mathbruyen** [puppeteer/puppeteer#10284]
### Bug expectation

A React component mounted in `page.evaluate` performs async work before failing. Puppeteer used to output the exact error message but since 20.2.0 started to give an empty error message. Reproduced in 20.3.0 20.4.0 and 20.0.5 but not in 20.1.0

This seems linked to https://github.com/puppeteer/puppeteer/pull/10114

While debugging a different case than the reproducer, exception details passed to `getErrorDetails` in `util.ts` has more call frames than exception stacktrace and `getErrorDetails` returns `{ message: '', name: 'Error' }`:

```
{
  exceptionId: 1,
  text: 'Uncaught (in promise) Error: Missing translation key obs.introduction.challenges.titlee',
  lineNumber: 15,
  columnNumber: 51,
  scriptId: '4',
  stackTrace: {
    callFrames: [
      [
        {
          functionName: 'onMissingKey',
          scriptId: '4',
          url: 'pptr:evaluate;defineRenderObsSlides%20(file%3A%2F%2F%2Fapp%2Ftest%2Futils%2Fobs-env.js%3A2%3A16)',
          lineNumber: 14,
          columnNumber: 50
        },
        {
          functionName: 'useI18n',
          scriptId: '19',
          url: 'http://localhost:64000/components/i18n/i18n.js',
          lineNumber: 112,
          columnNumber: 26
        },
        {
          functionName: 'useI18n',
          scriptId: '19',
          url: 'http://localhost:64000/components/i18n/i18n.js',
          lineNumber: 9,
          columnNumber: 19
        },
        {
          functionName: 'ChallengesSlide',
          scriptId: '33',
          url: 'http://localhost:64000/components/obs/introduction/challenges.js',
          lineNumber: 89,
          columnNumber: 14
        },
        {
          functionName: 'renderWithHooks',
          scriptId: '7',
          url: 'http://localhost:64000/libs/react-dom.js',
          lineNumber: 16314,
          columnNumber: 19
        },
        {
          functionName: 'mountIndeterminateComponent',
          scriptId: '7',
          url: 'http://localhost:64000/libs/react-dom.js',
          lineNumber: 20083,
          columnNumber: 14
        },
        {
          functionName: 'beginWork',
          scriptId: '7',
          url: 'http://localhost:64000/libs/react-dom.js',
          lineNumber: 21596,
          columnNumber: 17
        },
        {
          functionName: 'beginWork$1',
          scriptId: '7',
          url: 'http://localhost:64000/libs/react-dom.js',
          lineNumber: 27435,
          columnNumber: 15
        },
        {
          functionName: 'performUnitOfWork',
          scriptId: '7',
          url: 'http://localhost:64000/libs/react-dom.js',
          lineNumber: 26569,
          columnNumber: 13
        },
        {
          functionName: 'workLoopSync',
          scriptId: '7',
          url: 'http://localhost:64000/libs/react-dom.js',
          lineNumber: 26475,
          columnNumber: 6
        },
        {
          functionName: 'renderRootSync',
          scriptId: '7',
          url: 'http://localhost:64000/libs/react-dom.js',
          lineNumber: 26443,
          columnNumber: 8
        },
        {
          functionName: 'performConcurrentWorkOnRoot',
          scriptId: '7',
          url: 'http://localhost:64000/libs/react-dom.js',
          lineNumber: 25747,
          columnNumber: 75
        },
        {
          functionName: 'workLoop',
          scriptId: '6',
          url: 'http://localhost:64000/libs/react.js',
          lineNumber: 2652,
          columnNumber: 35
        },
        {
          functionName: 'flushWork',
          scriptId: '6',
          url: 'http://localhost:64000/libs/react.js',
          lineNumber: 2625,
          columnNumber: 15
        },
        {
          functionName: 'performWorkUntilDeadline',
          scriptId: '6',
          url: 'http://localhost:64000/libs/react.js',
          lineNumber: 2919,
          columnNumber: 22
        }
    ]
  },
  exception: {
    type: 'object',
    subtype: 'error',
    className: 'Error',
    description: 'Error: Missing translation key obs.introduction.challenges.titlee\n' +
      '    at Object.onMissingKey (pptr:evaluate;defineRenderObsSlides%20(file%3A%2F%2F%2Fapp%2Ftest%2Futils%2Fobs-env.js%3A2%3A16):15:51)\n' +
      '    at Object.useI18n [as buildTranslate] (http://localhost:64000/components/i18n/i18n.js:113:27)\n' +
      '    at useI18n (http://localhost:64000/components/i18n/i18n.js:10:20)\n' +
      '    at ChallengesSlide (http://localhost:64000/components/obs/introduction/challenges.js:90:15)\n' +
      '    at renderWithHooks (http://localhost:64000/libs/react-dom.js:16315:20)\n' +
      '    at mountIndeterminateComponent (http://localhost:64000/libs/react-dom.js:20084:15)\n' +
      '    at beginWork (http://localhost:64000/libs/react-dom.js:21597:18)\n' +
      '    at beginWork$1 (http://localhost:64000/libs/react-dom.js:27436:16)\n' +
      '    at performUnitOfWork (http://localhost:64000/libs/react-dom.js:26570:14)\n' +
      '    at workLoopSync (http://localhost:64000/libs/react-dom.js:26476:7)',
    objectId: '-7725925962384502251.3.1'
  }
}
```

[reproducer.zip](https://github.com/puppeteer/puppeteer/files/11616752/reproducer.zip)

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
const http = require('node:http');
const puppeteer = require('puppeteer');

(async function () {
  const server = http.createServer((req, res) => {
    res.end(`<html>
  <head>
    <script crossorigin src="https://unpkg.com/react@18/umd/react.development.js"></script>
    <script crossorigin src="https://unpkg.com/react-dom@18/umd/react-dom.development.js"></script>
  </head>
  <body>
    <div id="app"></div>
  </body>
</html>`);
  });
  try {
    server.listen(8000);
    const browser = await puppeteer.launch({
      args: [
        '--no-sandbox',
      ],
    });
    try {
      const context = await browser.createIncognitoBrowserContext();
      const page = await context.newPage();
      await page.goto('http://localhost:8000/');
      let gotError = false;
      try {
        await page.evaluate(async () => {
          return new Promise((resolve, reject) => {
            root = ReactDOM.createRoot(document.querySelector('#app'));
            root.render(React.createElement(function MyComponent() {
              React.useEffect(() => {
                reject(new Error('error message with details'));
              });
              return React.createElement('div');
            }));
          });
        });
      } catch (err) {
        gotError = true;
        if (!err.message.includes('error message with details')) {
          throw new Error('Expected message to contain details');
        }
      }
      if (!gotError) {
        throw new Error('Should have thrown');
      }
    } finally {
      await browser.close();
    }
  } finally {
    server.close();
  }
})();
```

### Error string

Expected message to contain details

### Puppeteer version

20.0.5

### Node version

20.2.0

### Package manager

npm

### Package manager version

9.6.6

### Operating system

Linux

**Comment by OrKoN** [comment]
Thanks for reporting @mathbruyen It looks like development builds of React (production builds seem to work as expected)  also do some transformations on stacktraces so the number of lines does not match what we expect (which is unfortunate). @jrandolf will take a look once he is back but I would say we should consider reverting the improvement or finding a more robust way to deal with this case. Do you know what does React do to stack traces?

**Comment by mathbruyen** [comment]
Didn't find what they are doing with stacktraces. Would ensuring at least one line in the stack is kept be more resilient?

```js
const size = Math.min(details.stackTrace?.callFrames.length ?? 0, lines.length - 1);
lines.splice(-size, size);
```

**Comment by jrandolf** [comment]
@mathbruyen I've taken a look. It indeed looks like React is modifying the stack trace. I think as a fallback, we can use manual parsing. I'll send out a PR for this.
