### ISSUE TITLE
[Feature]: Invalid header error should show what is the problem

### ISSUE THREAD

**Issue by Eccenux** [puppeteer/puppeteer#10356]
### Feature description

I try to serve a response from cache and I get:
```
Error: Protocol error (Fetch.fulfillRequest): Invalid header
    at new Callback (jsbot-auto\node_modules\puppeteer-core\lib\esm\puppeteer\common\Connection.js:58:35)
    at CallbackRegistry.create (jsbot-auto\node_modules\puppeteer-core\lib\esm\puppeteer\common\Connection.js:103:26)
    at Connection._rawSend (jsbot-auto\node_modules\puppeteer-core\lib\esm\puppeteer\common\Connection.js:215:26)
    at CDPSessionImpl.send (jsbot-auto\node_modules\puppeteer-core\lib\esm\puppeteer\common\Connection.js:422:78)
    at HTTPRequest._HTTPRequest_respond (jsbot-auto\node_modules\puppeteer-core\lib\esm\puppeteer\common\HTTPRequest.js:273:10)
    at HTTPRequest.respond (jsbot-auto\node_modules\puppeteer-core\lib\esm\puppeteer\common\HTTPRequest.js:184:100)
```
And cool, but which one? Which header is a problem? Is the header value invalid? Is the header name invalid? Is it a duplicate? Or what?...

**Comment by Eccenux** [comment]
Problematic header was set-cookie in this case.

Not sure why set-cookie was set on that request, probably a bug in Mediawiki. None the less would be helpful if Puppeteer would show the header name at least.

My ~pwa caching if that matters:
```
		page.on('request', async (request) => {
			const url = request.url();
			// const method = request.method();
			// if (cache[url] && cache[url].expires > Date.now()) {
			// if (method === 'GET' && cache[url]) {
			try {
				if (cache[url]) {
					this.stats.fromCache++;
					await request.respond(cache[url]);
					return;
				}
			} catch (error) {
				console.warn('[PageCache]', 'serving cache failed', url, error);
			}
			this.stats.direct++;
			request.continue();
		});
```
[PageCache] serving cache failed https://meta.wikimedia.org/w/index.php?title=MediaWiki:OSM.js&action=raw&ctype=text/javascript&smaxage=21601&maxage=86400 ProtocolError: Protocol error (Fetch.fulfillRequest): Invalid header

Possibly related:
 chore: propagate 'Invalid header' errors #7020

**Comment by Lightning00Blade** [comment]
This should be fixed with the latest version of Puppeteer.
