### ISSUE TITLE
[Bug]: SyntaxError: Unexpected token '??='

### ISSUE THREAD

**Issue by lukaszdaniel2billennium** [puppeteer/puppeteer#10486]
### Minimal, reproducible example

```TypeScript
installation by npm -i -D puppeteer generates the error:

  Browser download failed /app/node_modules/@puppeteer/browsers/lib/cjs/launch.js:48
    options.platform ??= (0, detectPlatform_js_1.detectBrowserPlatform)();
                     ^^^
SyntaxError: Unexpected token '??=' new Map();
                               ^^^
SyntaxError: Unexpected token '??='
    at compileFunction (<anonymous>)
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/HTTPRequest.js:18:19)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/NetworkManager.js:34:26)
```

### Error string

Browser download failed /app/node_modules/@puppeteer/browsers/lib/cjs/launch.js:48     options.platform ??= (0, detectPlatform_js_1.detectBrowserPlatform)();                      ^^^ SyntaxError: Unexpected token '??='

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Expectation

I cannot install lib by the `npm -i -D puppeteer`, can you please check the puppeteer component?

### Reality

the library cannot be installed

### Puppeteer version

20.7.4

### Node version

14.21.2

### Package manager

npm

### Package manager version

6.14.17

### Operating system

Linux

**Comment by OrKoN** [comment]
Node 14 is not a support version.
