### ISSUE TITLE
Can't take Screenshot

### ISSUE THREAD

**Issue by AliAryanTech** [puppeteer/puppeteer#10489]
I want take screenshot of invalid website like: https://domestic.some.app

But, I'm getting error like
```log
Error: net::ERR_NAME_NOT_RESOLVED at https://domestic.some.app
﻿at navigate (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:194:23)
﻿at runMicrotasks (<anonymous>)
﻿at processTicksAndRejections (node:internal/process/task_queues:96:5)
﻿at async FrameManager.navigateFrame (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:170:21)
﻿at async Frame.goto (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:589:16)
﻿at async Page.goto (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1089:16)
﻿at async /app/app.js:237:3
```

But I want response as 
![Image](https://github.com/puppeteer/puppeteer/assets/85696485/f3827460-c0ee-4ed9-ba79-207e134e6d68)

My code:
```js
app.get('/screenshot', async (req, res) => {
  if (!req.query.url) return void res.sendStatus(404)
  const { url } = req.query
  console.log(url)
  const browser = await puppeteer.launch({
    headless: true,
    args: ['--no-sandbox', '--incognito', '--single-process', '--no-zygote'],
    defaultViewport: null,
  })
  const page = await browser.newPage();
  await page.goto(url, { waitUntil: 'networkidle0', timeout: 60000 }).then(async () => {
     const image = await page.screenshot({ fullPage: true });
     await browser.close()
     res.status(200).setHeader('Content-Type', 'image/png').send(image).end()
    }).catch(async (error) => {
      console.error(error)
      res.sendStatus(404)
   })
})
```

**Comment by OrKoN** [comment]
Try using `try/catch` to catch the navigation exception? In any case, taking a screenshot of the internal error page is not something we explicitly support.

**Comment by AliAryanTech** [comment]
> Try using `try/catch` to catch the navigation exception? In any case, taking a screenshot of the internal error page is not something we explicitly support.

this happens:
```log
Error: net::ERR_NAME_NOT_RESOLVED at https://something.ub.app
﻿at navigate (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:194:23)
﻿at processTicksAndRejections (node:internal/process/task_queues:96:5)
﻿at async FrameManager.navigateFrame (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:170:21)
﻿at async Frame.goto (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:589:16)
﻿at async Page.goto (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1089:16)
﻿at async /app/app.js:238:5
```

Can't I take a screenshot like that which says **"This site can't be reached"**
