### ISSUE TITLE
[Bug]: Navigation failed because browser has disconnected!

### ISSUE THREAD

**Issue by hypo-thesis** [puppeteer/puppeteer#10491]
### Minimal, reproducible example

```TypeScript
const browser = await puppeteer.launch({
      args: ["--no-sandbox", "--disable-setuid-sandbox", "--headless=new" , "--single-process"],
      headless : false
    });
  const page = await browser.newPage();
  await page.goto('https://blog.risingstack.com', {waitUntil: 'networkidle0'});
  const pdf = await page.pdf({ format: 'A4' });
 
  await browser.close();
```

### Error string

Error: Navigation failed because browser has disconnected!

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I am trying to make a pdf out of a page. the moment I get to   `await page.goto('https://blog.risingstack.com', {waitUntil: 'networkidle0'});`

I get :

```
file:///www/wwwroot/v2.mydomain.com.tr/api/node_modules/puppeteer-core/lib/esm/puppeteer/common/LifecycleWatcher.js:80
            addEventListener(frameManager.client, CDPSessionEmittedEvents.Disconnected, __classPrivateFieldGet(this, _LifecycleWatcher_instances, "m", _LifecycleWatcher_terminate).bind(this, new Error('Navigation failed because browser has disconnected!'))),
                                                                                                                                                                                               ^

Error: Navigation failed because browser has disconnected!
    at new LifecycleWatcher (file:///www/wwwroot/v2.mydomain.com.tr/api/node_modules/puppeteer-core/lib/esm/puppeteer/common/LifecycleWatcher.js:80:192)
    at Frame.goto (file:///www/wwwroot/v2.mydomain.com.tr/api/node_modules/puppeteer-core/lib/esm/puppeteer/common/Frame.js:73:25)
    at CDPPage.goto (file:///www/wwwroot/v2.mydomain.com.tr/api/node_modules/puppeteer-core/lib/esm/puppeteer/common/Page.js:441:39)
    at file:///www/wwwroot/v2.mydomain.com.tr/api/routes.js:267:14
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.3.1
[nodemon] app crashed - waiting for file changes before starting...
```

### Expectation

I expect to not ge the error

### Reality

I in fact get the error.

### Puppeteer configuration

```TypeScript
const browser = await puppeteer.launch({
      args: ["--no-sandbox", "--disable-setuid-sandbox", "--headless=new" , "--single-process"],
      headless : false
    });
```

### Puppeteer version

"puppeteer": "20.7.4"

### Node version

20.3.1

### Package manager

npm

### Package manager version

9.2

### Operating system

Linux

**Comment by Lightning00Blade** [comment]
Unable to reproduce with the provided example, the PDF is correctly created (one `path` option is provided) and no error is observed. Tried 10 times to rule out some flakiness but scripts works all the time.

**Comment by Umoren** [comment]
i'm having this error all the time from using whatsapp-web.js

this is my config:

```js
puppeteer: {
            args: [
                '--no-sandbox',
                '--disable-setuid-sandbox',
                '--disable-dev-shm-usage',
                '--disable-accelerated-2d-canvas',
                '--no-first-run',
                '--no-zygote',
                '--single-process',
                '--disable-gpu'
            ],
        },
 ```
