### ISSUE TITLE
Passing empty array OR undefined object to `page.setCookie()` make puppeteer crash

### ISSUE THREAD

**Issue by GuilloOme** [puppeteer/puppeteer#1052]
a call on `page.setCookie([])` OR `page.setCookie(undefined)` make puppeteer crash.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.12.0
* Platform / OS version: https://try-puppeteer.appspot.com/ or linux ubuntu with nodejs v.8

**What steps will reproduce the problem?**

1. run : 
```javascript
const browser = await puppeteer.launch();
const page = await browser.newPage();

await page.setCookie([]);
// OR
await page.setCookie(undefined);

await browser.close();
```

**What is the expected result?**
No error, only a browser process starting and ending doing nothing

**What happens instead?**
Puppeteer crash with this error: 
```stack
 Error: Protocol error (Network.deleteCookies): Invalid parameters name: string value expected
    at Session._onMessage (./node_modules/puppeteer/lib/Connection.js:194:25)
    at Connection._onMessage (./node_modules/puppeteer/lib/Connection.js:98:19)
    at emitOne (events.js:115:13)
    at WebSocket.emit (events.js:210:7)
    at Receiver._receiver.onmessage (./node_modules/ws/lib/WebSocket.js:143:47)
    at Receiver.dataMessage (./node_modules/ws/lib/Receiver.js:389:14)
    at Receiver.getData (./node_modules/ws/lib/Receiver.js:330:12)
    at Receiver.startLoop (./node_modules/ws/lib/Receiver.js:165:16)
    at Receiver.add (./node_modules/ws/lib/Receiver.js:139:10)
    at Socket._ultron.on (./node_modules/ws/lib/WebSocket.js:139:22)

```

Edit: added case for `undefined`

**Comment by GuilloOme** [comment]
Forget it… it is my comprehension of params spreading which is bad…

Here's the right syntax: 
```javascript
const browser = await puppeteer.launch();
const page = await browser.newPage();

let cookies = [];

await page.setCookie(...cookies);

await browser.close();
```

Sorry…

**Comment by ebidel** [comment]
FWIW, try-puppeteer.appspot.com is still running 0.11.0, so if you'e using new APIs things migth not work. I'll update it to the latest version today.
