### ISSUE TITLE
[Bug]: single-process and headless=new crashes on Windows

### ISSUE THREAD

**Issue by rawfg** [puppeteer/puppeteer#10540]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer-core';

const browser = await puppeteer.launch({
	ignoreHTTPSErrors: true,
	args: ['--single-process'],
	headless: 'new', // switching to true on Windows fixes the issue
	channel: 'chrome',
	// executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', // works fine on MacOS
	// executablePath: 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe', // crashes on Windows
});

const pages = await browser.pages();
const page = pages && pages.length > 0 ? pages[0] : await browser.newPage();
await page.setViewport({width: 1920, height: 1080});
await page.goto('https://google.com', {waitUntil: 'load'});

console.log('Taking a screenshot of Google');
await page.screenshot({path: './google.png'});

await page.close();
await browser.close();
console.log('Exiting...');

process.exit();
```

### Error string

TargetCloseError: Protocol error (Emulation.setDeviceMetricsOverride): Session closed. Most likely the page has been closed.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I was trying to use the new `headless: 'new'` with `puppeteer-core` but it crashes on Windows when there is a Chrome browser argument (`args`) `--single-process`. When I switch to `headless: true` it works fine. I also tried to test it on MacOS and there is no problem.

I provide the entire repo with an example: https://github.com/rawfg/puppeteer-issue

### Expectation

I expect it would work on Windows as it works on MacOS.

### Reality

It crashes on Windows:

```
PS C:\Users\rawf\projects\puppeteer-issue> node .\index.mjs
file:///C:/Users/rawf/projects/puppeteer-issue/node_modules/puppeteer-core/lib/esm/puppeteer/common/Connection.js:422
            return Promise.reject(new TargetCloseError(`Protocol error (${method}): Session closed. Most likely the ${__classPrivateFieldGet(this, _CDPSessionImpl_targetType, "f")} has been closed.`));
                                  ^

TargetCloseError: Protocol error (Emulation.setDeviceMetricsOverride): Session closed. Most likely the page has been closed.
    at CDPSessionImpl.send (file:///C:/Users/rawf/projects/puppeteer-issue/node_modules/puppeteer-core/lib/esm/puppeteer/common/Connection.js:422:35)
    at EmulationManager.emulateViewport (file:///C:/Users/rawf/projects/puppeteer-issue/node_modules/puppeteer-core/lib/esm/puppeteer/common/EmulationManager.js:39:73)
    at CDPPage.setViewport (file:///C:/Users/rawf/projects/puppeteer-issue/node_modules/puppeteer-core/lib/esm/puppeteer/common/Page.js:541:96)
    at file:///C:/Users/rawf/projects/puppeteer-issue/index.mjs:14:12
```

### Puppeteer version

20.8.0

### Node version

18.16.0

### Package manager

npm

### Package manager version

9.5.1

### Operating system

Windows

**Comment by OrKoN** [comment]
Could you please report the issue to crbug.com as it does not directly depend on Puppeteer. Note that https://github.com/rawfg/puppeteer-issue you linked does not seem to be published? Also, `--single-process` might not work as expected as I am not sure how well Chromium supports it.
