### ISSUE TITLE
[Bug]: Browser crashes immediately when running with pm2 in cluster mode

### ISSUE THREAD

**Issue by ericman314** [puppeteer/puppeteer#10633]
### Minimal, reproducible example

```TypeScript
// Note: This script won't fail on its own. See https://github.com/ericman314/puppeteer-test

const express = require('express')
const http = require('http')
const puppeteer = require('puppeteer')

const app = express()
const server = new http.Server(app)
server.listen(3010, () => {
  console.log('Server listening')
})

app.get('/hello', (req, res) => {
  console.log('hello')
  res.send('<html><h1>Hello, world!</h1></html>')
})

app.get('/render.png', (req, res) => {
  console.log('render')
  doRender()
    .then(image => {
      res.setHeader('content-type', 'image/png');
      res.send(image)
    })
    .catch(err => {
      console.error(err)
    })
})

async function doRender() {
   const browser = await puppeteer.launch({ headless: 'new' })
   const page = await browser.newPage()
   await page.setViewport({ width: 600, height: 400 })
   const url = `http://localhost:3010/hello`
   await page.goto(url)
   await page.waitForNetworkIdle();
   let image = await page.screenshot()
   await browser.close()
   return image
}
```

### Error string

TargetCloseError: Protocol error (Target.setAutoAttach): Target closed

### Bug behavior

- [x] Flaky
- [ ] PDF

### Background

I have a server with two endpoints: one that serves a page, and a second that uses puppeteer to launch a headless browser, fetch that page, and take a screenshot. (Link to repo: https://github.com/ericman314/puppeteer-test) All of that works perfectly fine, _most of the time_.

Where things start breaking is when I run the server on a Ubuntu server, using pm2, in cluster mode. This is a tricky problem because I can't reproduce it on my local development machine (also ubuntu), and it only happens when running using pm2 in cluster mode. If pm2 runs in fork mode, it doesn't break.

#### Summary of when it breaks:
Running using pm2 in cluster mode on my local dev machine: Works
Running using pm2 in fork mode on my headless server: Works
Running using pm2 in cluster mode on my headless server: **Breaks**

To be honest, I don't know if the bug is with puppeteer, pm2, or chromium, or if it's a problem with the environment on my ubuntu server. I'm just hoping to get some information from the experts here as to what could possibly be going on. I can provide logs if requested.

### Expectation

Render and output this image:

![render](https://github.com/puppeteer/puppeteer/assets/6345617/f4ba9c5d-9c63-4061-b832-0de00e80f793)

### Reality

The browser appears to crash moments after starting:

```
9|image-server  | TargetCloseError: Protocol error (Target.setAutoAttach): Target closed
9|image-server  |     at CallbackRegistry.clear (/home/dev/puppeteer-test/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:138:36)
9|image-server  |     at Connection.#onClose (/home/dev/puppeteer-test/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:282:25)
9|image-server  |     at WebSocket.<anonymous> (/home/dev/puppeteer-test/node_modules/puppeteer-core/lib/cjs/puppeteer/common/NodeWebSocketTransport.js:57:30)
9|image-server  |     at callListener (/home/dev/puppeteer-test/node_modules/ws/lib/event-target.js:290:14)
9|image-server  |     at WebSocket.onClose (/home/dev/puppeteer-test/node_modules/ws/lib/event-target.js:220:9)
9|image-server  |     at WebSocket.emit (node:events:390:28)
9|image-server  |     at WebSocket.emitClose (/home/dev/puppeteer-test/node_modules/ws/lib/websocket.js:258:10)
9|image-server  |     at Socket.socketOnClose (/home/dev/puppeteer-test/node_modules/ws/lib/websocket.js:1264:15)
9|image-server  |     at Socket.emit (node:events:390:28)
9|image-server  |     at TCP.<anonymous> (node:net:687:12)
```

Also a huge `core` file is output:

![image](https://github.com/puppeteer/puppeteer/assets/6345617/859250c9-0a65-496a-96f0-b36b873657d0)

### Puppeteer version

20.9.0

### Node version

16.13.0

### Package manager

npm

### Package manager version

8.1.0

### Operating system

Linux

**Comment by ericman314** [comment]
I checked "flaky" above to satisfy the bot, but the bug definitely happens consistently. The bot probably won't be able to reproduce it.

**Comment by ericman314** [comment]
Thanks for the suggestion!
