### ISSUE TITLE
Error: Could not find Chrome (ver. 115.0.5790.170)

### ISSUE THREAD

**Issue by Sriinspire** [puppeteer/puppeteer#10724]
### Steps to reproduce

after finishing installation of puppeteer ,lighthouse, csv parser, while trying to run basic puppeteer scripts through Visual studio/command prompt

### Expected results

code should run successfully

### Actual results

file:///C:/Users/xxxxxx/puppeteer%20programs/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:274
                    throw new Error(`Could not find Chrome (ver. ${this.puppeteer.browserRevision}). This can occur if either\n` +
                          ^

Error: Could not find Chrome (ver. 115.0.5790.170). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npm install`) or
 2. your cache path is incorrectly configured (which is: C:\Users\xxxx\.cache\puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
    at ChromeLauncher.resolveExecutablePath (file:///C:/Users/XXXX/puppeteer%20programs/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:274:27)
    at ChromeLauncher.executablePath (file:///C:/Users/xxxx/puppeteer%20programs/node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js:174:25)
    at ChromeLauncher.computeLaunchArguments (file:///C:/User/xxxx/puppeteer%20programs/node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js:91:37)
    at async ChromeLauncher.launch (file:///C:/Users/xxxx/puppeteer%20programs/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:53:28)

**Comment by Sriinspire** [comment]
request you to help me solve this issue as i am trying to automate lighthouse reports using puppeteer, it ran fine  before i updated node and puppeteer...now the scripts are not running

**Comment by OrKoN** [comment]
is the chrome installed in the path defined by the error message? make sure you have it installed and re-install puppeteer or run `node node_modules/puppeteer/install.js` after you upgrade the puppeteer version.

**Comment by Pratham271** [comment]
Error: Browser was not found at the configured executablePath (/opt/render/.cache/puppeteer)
    at ChromeLauncher.launch (/opt/render/project/src/backend/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:72:19)
 getting this error while generating pdf of my page 
 I am uploading the project to render to host it
