### ISSUE TITLE
[Bug]: Cannot `npm install puppeteer` if parent directory contains a file named .config

### ISSUE THREAD

**Issue by jonhermansen** [puppeteer/puppeteer#10728]
### Minimal, reproducible example

```sh
user@localhost ~ $ cd $(mktemp -d)
user@localhost /tmp/tmp.FNStgxZUQh $ touch ../.config
user@localhost /tmp/tmp.FNStgxZUQh $ npm i puppeteer
npm ERR! code 1
npm ERR! path /tmp/tmp.FNStgxZUQh/node_modules/puppeteer
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! node:fs:600
npm ERR!   handleErrorFromBinding(ctx);
npm ERR!   ^
npm ERR! 
npm ERR! Error: ENOTDIR: not a directory, open '/tmp/.config/puppeteerrc'
npm ERR!     at Object.openSync (node:fs:600:3)
npm ERR!     at Object.readFileSync (node:fs:468:35)
npm ERR!     at readFileSync (/tmp/tmp.FNStgxZUQh/node_modules/cosmiconfig/dist/readFile.js:45:33)
npm ERR!     at ExplorerSync.loadSearchPlaceSync (/tmp/tmp.FNStgxZUQh/node_modules/cosmiconfig/dist/ExplorerSync.js:74:48)
npm ERR!     at ExplorerSync.searchDirectorySync (/tmp/tmp.FNStgxZUQh/node_modules/cosmiconfig/dist/ExplorerSync.js:60:32)
npm ERR!     at run (/tmp/tmp.FNStgxZUQh/node_modules/cosmiconfig/dist/ExplorerSync.js:41:27)
npm ERR!     at cacheWrapperSync (/tmp/tmp.FNStgxZUQh/node_modules/cosmiconfig/dist/cacheWrapper.js:28:18)
npm ERR!     at ExplorerSync.searchFromDirectorySync (/tmp/tmp.FNStgxZUQh/node_modules/cosmiconfig/dist/ExplorerSync.js:52:49)
npm ERR!     at run (/tmp/tmp.FNStgxZUQh/node_modules/cosmiconfig/dist/ExplorerSync.js:45:21)
npm ERR!     at cacheWrapperSync (/tmp/tmp.FNStgxZUQh/node_modules/cosmiconfig/dist/cacheWrapper.js:28:18) {
npm ERR!   errno: -20,
npm ERR!   syscall: 'open',
npm ERR!   code: 'ENOTDIR',
npm ERR!   path: '/tmp/.config/puppeteerrc'
npm ERR! }
npm ERR! 
npm ERR! Node.js v18.13.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2023-08-12T23_15_03_546Z-debug-0.log
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I wanted to try out puppeteer in a new npm project I'm creating. So I went to install it as a dependency of the project.

I found that this command fails if parent directory contains a file named .config -- in my case, it was a backup of a Linux kernel configuration file.

### Expectation

puppeteer installs normally in this case, or possibly uses a global directory relative to $HOME

### Reality

```
npm ERR! code 1
npm ERR! path /tmp/tmp.FNStgxZUQh/node_modules/puppeteer
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! node:fs:600
npm ERR!   handleErrorFromBinding(ctx);
npm ERR!   ^
npm ERR! 
npm ERR! Error: ENOTDIR: not a directory, open '/tmp/.config/puppeteerrc'
npm ERR!     at Object.openSync (node:fs:600:3)
npm ERR!     at Object.readFileSync (node:fs:468:35)
npm ERR!     at readFileSync (/tmp/tmp.FNStgxZUQh/node_modules/cosmiconfig/dist/readFile.js:45:33)
npm ERR!     at ExplorerSync.loadSearchPlaceSync (/tmp/tmp.FNStgxZUQh/node_modules/cosmiconfig/dist/ExplorerSync.js:74:48)
npm ERR!     at ExplorerSync.searchDirectorySync (/tmp/tmp.FNStgxZUQh/node_modules/cosmiconfig/dist/ExplorerSync.js:60:32)
npm ERR!     at run (/tmp/tmp.FNStgxZUQh/node_modules/cosmiconfig/dist/ExplorerSync.js:41:27)
npm ERR!     at cacheWrapperSync (/tmp/tmp.FNStgxZUQh/node_modules/cosmiconfig/dist/cacheWrapper.js:28:18)
npm ERR!     at ExplorerSync.searchFromDirectorySync (/tmp/tmp.FNStgxZUQh/node_modules/cosmiconfig/dist/ExplorerSync.js:52:49)
npm ERR!     at run (/tmp/tmp.FNStgxZUQh/node_modules/cosmiconfig/dist/ExplorerSync.js:45:21)
npm ERR!     at cacheWrapperSync (/tmp/tmp.FNStgxZUQh/node_modules/cosmiconfig/dist/cacheWrapper.js:28:18) {
npm ERR!   errno: -20,
npm ERR!   syscall: 'open',
npm ERR!   code: 'ENOTDIR',
npm ERR!   path: '/tmp/.config/puppeteerrc'
npm ERR! }
npm ERR! 
npm ERR! Node.js v18.13.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2023-08-12T23_15_03_546Z-debug-0.log
```

### Puppeteer configuration file (if used)

```TypeScript
// Not applicable, no config was used because can't install the library
```

### Puppeteer version

21.0.3

### Node version

18.13.0

### Package manager

npm

### Package manager version

9.2.0

### Operating system

Linux

**Comment by jonhermansen** [comment]
This is a packaging bug, not necessarily an issue with the puppeteer library. Even though the github-actions bot is reporting it as unverified, I think that is a bit dubious.

The three simple steps can be run in the shell to reproduce the issue.

I suppose it is somewhat of an edge case, but still thought it worth reporting here.

Thanks.

**Comment by jonhermansen** [comment]
no error

**Comment by Lightning00Blade** [comment]
This is not a Puppeteer issue if you see the stack traces, you can see the error is created from the module `cosmiconfig`, can you please open an issue against their repository. 
Give that this is a package Puppeteer uses I will be closing the PR about the fix and keeping this issue open till they have a fix and we have update to it.

**Comment by jonhermansen** [comment]
@Lightning00Blade Yes, the stack trace does reference cosmiconfig, but the error originates from within this project's [packages/puppeteer/install.js](https://github.com/puppeteer/puppeteer/blob/main/packages/puppeteer/install.js#L40) which is run as a package-specific postinstall script. For some reason that code does not show up in the stack trace...

I think if you look a bit more closely, maybe this is an issue with the way in which cosmiconfig is being used by puppeteer... is it really expected behavior that installing the package will walk up the directory tree looking for folders named `.config`? I don't see that many people would rely on this behavior. In my opinion, checking for puppeteerrc in $HOME/.config would be fine. But I understand that many users might have a differing opinion.

And lastly, this error does actually occur outside of /tmp and that is how I originally found it... please try for yourself.

```sh
user@localhost ~ $ pwd
/home/user
user@localhost ~ $ mkdir -p test/project/hierarchy
user@localhost ~ $ cd test/project/hierarchy 
user@localhost ~/test/project/hierarchy $ touch ../.config
user@localhost ~/test/project/hierarchy $ npm install puppeteer
npm ERR! code 1
npm ERR! path /home/user/test/project/hierarchy/node_modules/puppeteer
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! node:fs:600
npm ERR!   handleErrorFromBinding(ctx);
npm ERR!   ^
npm ERR! 
npm ERR! Error: ENOTDIR: not a directory, open '/home/user/test/project/.config/puppeteerrc'
npm ERR!     at Object.openSync (node:fs:600:3)
npm ERR!     at Object.readFileSync (node:fs:468:35)
npm ERR!     at readFileSync (/home/user/test/project/hierarchy/node_modules/cosmiconfig/dist/readFile.js:45:33)
npm ERR!     at ExplorerSync.loadSearchPlaceSync (/home/user/test/project/hierarchy/node_modules/cosmiconfig/dist/ExplorerSync.js:74:48)
npm ERR!     at ExplorerSync.searchDirectorySync (/home/user/test/project/hierarchy/node_modules/cosmiconfig/dist/ExplorerSync.js:60:32)
npm ERR!     at run (/home/user/test/project/hierarchy/node_modules/cosmiconfig/dist/ExplorerSync.js:41:27)
npm ERR!     at cacheWrapperSync (/home/user/test/project/hierarchy/node_modules/cosmiconfig/dist/cacheWrapper.js:28:18)
npm ERR!     at ExplorerSync.searchFromDirectorySync (/home/user/test/project/hierarchy/node_modules/cosmiconfig/dist/ExplorerSync.js:52:49)
npm ERR!     at run (/home/user/test/project/hierarchy/node_modules/cosmiconfig/dist/ExplorerSync.js:45:21)
npm ERR!     at cacheWrapperSync (/home/user/test/project/hierarchy/node_modules/cosmiconfig/dist/cacheWrapper.js:28:18) {
npm ERR!   errno: -20,
npm ERR!   syscall: 'open',
npm ERR!   code: 'ENOTDIR',
npm ERR!   path: '/home/user/test/project/.config/puppeteerrc'
npm ERR! }
npm ERR! 
npm ERR! Node.js v18.13.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2023-08-14T10_32_53_407Z-debug-0.log
```

**Comment by jonhermansen** [comment]
Related cosmiconfig issue discussion: https://github.com/cosmiconfig/cosmiconfig/issues/152#issue-338357556

They suggest passing `searchPlaces` which is essentially what I've done in my PR (but only as a fallback in case an ENOTDIR exception is thrown)

**Comment by Lightning00Blade** [comment]
Filed https://github.com/cosmiconfig/cosmiconfig/issues/313, will wait for their response before moving forward with any change on our side. 

Workaround at this time is to provide an empty `.puppeteerrc.js` file. ([Example](https://pptr.dev/guides/configuration#changing-the-default-cache-directory))
