### ISSUE TITLE
[Bug]: ProtocolError: Protocol error (Target.createTarget): Not supported

### ISSUE THREAD

**Issue by kingangelAOA** [puppeteer/puppeteer#10840]
### Steps to reproduce

`
  const config = await axios.get('http://127.0.0.1:1250/json/version')
  console.log(config)

  const browser = await puppeteer.connect({browserWSEndpoint: config.data.webSocketDebuggerUrl, ignoreHTTPSErrors: true})
  const page = await browser.newPage()`

ProtocolError: Protocol error (Target.createTarget): Not supported
    at Callback.<instance_members_initializer> (D:\csgoskins\node_modules\puppeteer-core\src\common\Connection.ts:67:12)     
    at new Callback (D:\csgoskins\node_modules\puppeteer-core\src\common\Connection.ts:72:3)
    at CallbackRegistry.create (D:\csgoskins\node_modules\puppeteer-core\src\common\Connection.ts:128:22)
    at Connection._rawSend (D:\csgoskins\node_modules\puppeteer-core\src\common\Connection.ts:279:22)
    at Connection.send (D:\csgoskins\node_modules\puppeteer-core\src\common\Connection.ts:267:17)
    at CDPBrowser._createPageInContext (D:\csgoskins\node_modules\puppeteer-core\src\common\Browser.ts:446:47)
    at CDPBrowserContext.newPage (D:\csgoskins\node_modules\puppeteer-core\src\common\Browser.ts:687:26)
    at CDPBrowser.newPage (D:\csgoskins\node_modules\puppeteer-core\src\common\Browser.ts:439:33)
    at D:/csgoskins/test.js:99:30
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

system: win10
chrome version: Version 116.0.5845.141 (Official Build) (64-bit)
puppeteer: "^21.1.1",

### Expected results

connect browser

### Actual results

error

**Comment by Lightning00Blade** [comment]
Closing this issue as it does not use the correct template.
Please open a new issue that uses the default template for the Puppeteer package.
