### ISSUE TITLE
[Bug]: puppeteer post install chromium install fails on node 18(npm 9) fails but succeeds on node 16

### ISSUE THREAD

**Issue by pmweeks98** [puppeteer/puppeteer#10900]
### Minimal, reproducible example

```TypeScript
unable to give one
```

### Error string

ERROR: Failed to set up Chromium r1108766! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

Trying to install puppeteer in a docker container on jenkins. It works on node 16 but when switching to node v18.17.1, the chromium install fails

puppeteer 19 issue
```
2633 verbose stack Error: command failed
2633 verbose stack     at ChildProcess.<anonymous> (/<>/.nvm/versions/node/v18.17.1/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
2633 verbose stack     at ChildProcess.emit (node:events:514:28)
2633 verbose stack     at maybeClose (node:internal/child_process:1091:16)
2633 verbose stack     at Socket.<anonymous> (node:internal/child_process:449:11)
2633 verbose stack     at Socket.emit (node:events:514:28)
2633 verbose stack     at Pipe.<anonymous> (node:net:323:12)
2634 verbose pkgid puppeteer@19.11.1
2635 verbose cwd /home/<>
2636 verbose Linux 3.10.0-1160.99.1.el7.x86_64
2637 verbose node v18.17.1
2638 verbose npm  v9.6.7
2639 error code 1
2640 error path /home/<>/node_modules/puppeteer
2641 error command failed
2642 error command sh -c node install.js
2643 error ERROR: Failed to set up Chromium r1108766! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
2643 error Error: connect ENETUNREACH 2607:f8b0:4004:c17::cf:443
2643 error     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16) {
2643 error   errno: -101,
2643 error   code: 'ENETUNREACH',
2643 error   syscall: 'connect',
2643 error   address: '2607:f8b0:4004:c17::cf',
2643 error   port: 443
2643 error }
2644 verbose exit 1
```

puppeteer 21 issue
```
2989 timing command:install Completed in 220352ms
2990 verbose stack Error: command failed
2990 verbose stack     at ChildProcess.<anonymous> (/home/<>/.nvm/versions/node/v18.17.1/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
2990 verbose stack     at ChildProcess.emit (node:events:514:28)
2990 verbose stack     at maybeClose (node:internal/child_process:1091:16)
2990 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
2991 verbose pkgid puppeteer@21.2.1
2992 verbose cwd /home/<>
2993 verbose Linux 3.10.0-1160.99.1.el7.x86_64
2994 verbose node v18.17.1
2995 verbose npm  v9.6.7
2996 error code 1
2997 error path /home/<>/node_modules/puppeteer
2998 error command failed
2999 error command sh -c node install.js
3000 error ERROR: Failed to set up Chrome r116.0.5845.96! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
3000 error Error: connect ENETUNREACH 2600:1900:4110:86f:::443
3000 error     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16) {
3000 error   errno: -101,
3000 error   code: 'ENETUNREACH',
3000 error   syscall: 'connect',
3000 error   address: '2600:1900:4110:86f::',
3000 error   port: 443
3000 error }
3001 verbose exit 1
```

I can set PUPPETEER_SKIP_DOWNLOAD and download succeeds but I need the chromium download as well
Setting npm versions using nvm

### Expectation

install puppeteer without issue

### Reality

install fails

### Puppeteer version

21.2.1

### Node version

18.17.1

### Package manager

npm

### Package manager version

9.6.7

### Operating system

Linux

**Comment by OrKoN** [comment]
ENETUNREACH indicates a network issue. I don't think there is anything Puppeteer can do here: https://stackoverflow.com/questions/49015634/error-connect-enetunreach Maybe your network does not support IPV6 which Node 18 uses by default? in that case https://stackoverflow.com/questions/72132898/how-to-fix-connect-enetunreach-on-npm-on-linux might be relevant.
