### ISSUE TITLE
[Bug]: Can't print to pdf using firefox on a local html file

### ISSUE THREAD

**Issue by mathisgauthey** [puppeteer/puppeteer#11165]
### Minimal, reproducible example

```TypeScript
const puppeteer = require("puppeteer");
const path = require("path");
const fs = require("fs");
const filePath = path.resolve(__dirname, "index.html");

(async () => {
  try {
    const puppeteerVersion = require('puppeteer/package.json').version;
    console.log(`Using Puppeteer version ${puppeteerVersion}`);
    console.log(`This is the path: ${filePath}`)
    
    const browser = await puppeteer.launch({
      product: 'firefox',
      headless: false, // Use true to run headless, not 'new'
      dumpio: true
    });
    const page = await browser.newPage();
    var contentHtml = fs.readFileSync(`${filePath}`, 'utf8');
    await page.setContent(contentHtml);
    // await page.goto(`file:${filePath}`);
    await page.pdf({
      path: "GAUTHEY_Mathis.pdf",
      format: "A4",
      displayHeaderFooter: false,
      margin: { top: 0, right: 0, bottom: 0, left: 0 },
      // preferCSSPageSize: true,
      // printBackground: false, // Change to true if you want to include background
    });
    await browser.close();
    console.log("✅ PDF built");
  } catch (error) {
    console.error("❌ Error building PDF:", error);
    process.exit(1);
  }
})();
```

HTML file : 

```
<!doctype html>
<html>
	<head>

	<meta charset='utf-8'>
	<meta name='viewport' content='width=device-width, user-scalable=no, minimal-ui'>

	<title>Mathis Gauthey</title>

	<style>
	body {
  background: #EEEEEE;
  font: 12px "Times New Roman", Times, sans-serif;
  line-height: 1.4;
  margin: 40px 0;
}
em {
  color: #999;
}
p {
  line-height: 1.4;
}
ul {
  margin-bottom: 0;
}
li {
  margin-bottom: 2px;
}
a {
  text-decoration: none;
}

#resume {
  margin: 0 auto;
  max-width: 600px;
  padding: 80px 100px;
  background: #fff;
  border: 1px solid #ccc;
  box-shadow: 2px 2px 4px #aaa;
  -webkit-box-shadow: 2px 2px 4px #aaa;
}

.coursesList {
  width: 28%;
  vertical-align: top;
  display: inline-block;
}

.largeFont {
  font-size: 20px;
}

.smallFont {
  font-size: 12px;
}

.sectionBlock {
  display: flex;
  width: 100%;
}

.sectionName {
  width: 18%;
  vertical-align: top;
  display: inline-block;
}

.sectionContent {
  width: 80%;
  vertical-align: top;
  display: inline-block;
}

.sectionContent ul {
  padding-left: 20px;
  margin-top: 6px;
  list-style-type: circle;
}

.sectionContent .title {
  font-weight: bold;
}

.sectionContent .date {
  float: right;
}

.sectionContent .separator {
  height: 14px;
}

.sectionLine {
  border-style: dashed;
  border-width: 1px;
  border-color: #CFCFCF;
  margin-top: 10px;
  margin-bottom: 10px;
}

.divider {
  font-weight: bold;
  margin-left: 5px;
  margin-right: 5px;
}

.summary {
  margin-top: 6px;
}

.skillBlock {
  margin-bottom: 4px;
}

.jobBlock {
  page-break-inside: avoid;
}

/* Media Queries */
@media only screen and (max-width: 40em) {
  body {
    margin: 0;
    font-size: 14px;
  }
  #resume {
    margin: 0 auto;
    max-width: 600px;
    padding: 0.5em 1em;
    border: none;
  }
  .sectionContent {
    width: 100%;
  }
  .sectionContent .date {
    padding-right: 2em;
  }
  .sectionName {
    width: auto;
  }
  .largeFont {
    font-size: 20px;
  }
  .smallFont {
    font-size: 14px;
  }
}

@media print {
  #resume {
    margin: 0 auto;
    max-width: 600px;
    padding: 0px 0px;
    border: 0px;
    background: #FFFFFF;
    box-shadow: none;
    -webkit-box-shadow: none;
  }

  a {
    color: black;
  }
}

	</style>

	</head>
	<body>

	<div id='resume'>
  <div id='nameBlock' class='largeFont'>
    <span class='name'>
      Mathis Gauthey,
    </span>
    <span class='label'>Ingénieur mécanique</span>
  </div>
  <div id='basicsBlock' class='smallFont'>
    <div class='contactBlock'>
      <span class='email'>mail@gmail.com</span>
      <span class='divider'>|</span>
      <span class='phone'>phone</span>
        <span class='divider'>|</span>
        <span class='address'>
          Adress
        </span>
    </div>
      <div id='profilesBlock'>
            <span class='url'>
              <a href=''></a>
            </span>
            <span class='divider'>|</span>
            <span class='url'>
              <a href=''></a>
            </span>
            <span class='divider'>|</span>
            <span class='url'>
              <a href=''></a>
            </span>
            <span class='divider'>|</span>
            <span class='url'>
              <a href=''></a>
            </span>
            <span class='divider'>|</span>
            <span class='url'>
              <a href=''></a>
            </span>
            <span class='divider'>|</span>
            <span class='url'>
              <a href=''></a>
            </span>

      </div>
  </div>
  <div class='sectionLine'></div>

  <div id='summaryBlock' class="sectionBlock">
    <div class='sectionName'>
      <span>RÉSUMÉ</span>
    </div>
    <div class='sectionContent'>
      <span>Recherche un poste d&#x27;ingénieur en développement à partir d&#x27;Octobre 2023.</span>
    </div>
  </div>
  <div class='sectionLine'></div>

  <div id='workBlock' class="sectionBlock">
    <div class='sectionName'>
      <span>EXPERIENCES</span>
    </div>
    <div class='sectionContent'>
			<div class="jobBlock">
	      <div class='blockHeader'>
	        <span class='title'>
	          🔬 Stagiaire ingénieur d&#x27;études -
	        </span>
	        <span class='date'>
	          févr. 2022 &mdash; juil. 2022 (5 mois)
	        </span>
	      </div>
	      <ul class='highlights'>
	        <li>Projet de recherche et innovation sur le comportement des structures soumises à un effet de surpression.</li>
	        <li>Rédaction en LaTeX d&#x27;un guide méthodologique complet d&#x27;analyse d&#x27;une structure soumise à une explosion </li>
	        <li>Développement de codes de calculs et de post-traitement sous Python</li>
	        <li>Réalisation d’une feuille Excel de calculs pour traiter les cas courants en élastique ou plastique</li>
	        <li>Développement de codes de calculs éléments finis sous Ansys APDL</li>
	      </ul>
	      <div class='separator'></div>
			</div>
			<div class="jobBlock">
	      <div class='blockHeader'>
	        <span class='title'>
	          🏭 Stagiaire ingénieur amélioration continue -
	        </span>
	        <span class='date'>
	          mars 2021 &mdash; août 2021 (5 mois)
	        </span>
	      </div>
	      <ul class='highlights'>
	        <li>Projet d&#x27;amélioration continu sur un îlot de production.</li>
	        <li>Collaboration et travail d&#x27;équipe avec les différents secteurs : Maintenance, R&amp;D, Qualité, Production</li>
	        <li>Analyse des causes de dé-cadencement et de perte de TRS</li>
	        <li>Mise en place d&#x27;un planning de maintenance préventive et de modes opératoires pour tout un îlot de production</li>
	        <li>Mise en place d&#x27;outils d&#x27;amélioration continue, de 5S, et formation des opérateurs</li>
	        <li>Résolutions de problèmes opérationnels</li>
	      </ul>

			</div>
    </div>
  </div>
  <div class='sectionLine'></div>



	<div id='education' class="sectionBlock">
    <div class='sectionName'>
      <span>FORMATIONS</span>
    </div>
    <div class='sectionContent'>
      <div class='educationBlock'>
        <span class='title'>
          🎓 Somewhere
        </span>
        <span class='date'>
          janv. 2019 &mdash; janv. 2022
        </span>
        <div class=''>
          Diplôme d&#x27;ingénieur mécanique  - Ingénierie
        </div>
      </div>
      <div class='separator'></div>
      <div class='educationBlock'>
        <span class='title'>
          👨‍🔬 Somewhere
        </span>
        <span class='date'>
          janv. 2017 &mdash; janv. 2019
        </span>
        <div class=''>
          Classes préparatoires  - Mathématiques
        </div>
      </div>

    </div>
	</div>
  <div class='sectionLine'></div>

	<div id='skills' class="sectionBlock">
    <div class='sectionName'>
      <span>COMPÉTENCES</span>
    </div>
    <div class='sectionContent'>
      <div class='skillBlock'>
        <span class='title'>⌨️ Développement <em>(Bonnes pratiques)</em>:</span>
          <span>C</span>,
          <span>C++</span>,
          <span>Python</span>,
          <span>Matlab</span>
      </div>
      <div class='skillBlock'>
        <span class='title'>📏 CAO <em>(Plusieurs projets)</em>:</span>
          <span>Creo</span>,
          <span>Catia V5</span>,
          <span>OnShape</span>
      </div>
      <div class='skillBlock'>
        <span class='title'>⏳ Simulation numérique <em>(PFE sur Adams, SFE sur Ansys APDL)</em>:</span>
          <span>Ansys APDL</span>,
          <span>Adams</span>,
          <span>Patran Nastran</span>,
          <span>Ansys Fluent</span>
      </div>
      <div class='skillBlock'>
        <span class='title'>💻 Informatique et bureautique <em>(Grande expérience personnelle)</em>:</span>
          <span>LaTeX</span>,
          <span>Microsoft Office</span>,
          <span>Bash</span>,
          <span>Batch</span>,
          <span>Powershell</span>
      </div>
      <div class='skillBlock'>
        <span class='title'>✅ Organisation <em>(Lecture sur la productivité)</em>:</span>
          <span>GTD (Getting Things Done)</span>,
          <span>P.A.R.A.</span>,
          <span>Atomic Habits</span>
      </div>
      <div class='skillBlock'>
        <span class='title'>👥 Travail d&#x27;équipes <em>(Nombreux projets réalisés en équipe)</em>:</span>
          <span>Agile</span>,
          <span>Kanban</span>,
          <span>Scrum</span>,
          <span>Git Workflow</span>,
          <span>Outils clouds</span>
      </div>
      <div class='skillBlock'>
        <span class='title'>🚗 Permis <em>(Validé)</em>:</span>
          <span>A (Moto)</span>,
          <span>B (Voiture)</span>
      </div>
    </div>
	</div>
  <div class='sectionLine'></div>

	<div id='languages' class="sectionBlock">
    <div class='sectionName'>
      <span>LANGUES</span>
    </div>
    <div class='sectionContent'>
      <span class='language'>🇫🇷 Français</span>
      <span class='fluency'><em>(Langue natale)</em></span>
      <span>,</span>
      <span class='language'>🇬🇧 English</span>
      <span class='fluency'><em>(Fluent : TOEIC C1 965/990)</em></span>
      <span>,</span>
      <span class='language'>🇪🇸 Español</span>
      <span class='fluency'><em>(A2-B1)</em></span>

    </div>
    <div class='sectionLine'></div>
	</div>

	<div id='interests' class="sectionBlock">
    <div class='sectionName'>
      <span>INTÉRÊTS</span>
    </div>
    <div class='sectionContent'>
      <span class='name'>🥾 Randonnée et course à pieds</span><!--
      --><span>, </span>
      <span class='name'>💪 Callisthénie</span><!--
      --><span>, </span>
      <span class='name'>🧳 Voyage</span><!--
      --><span>, </span>
      <span class='name'>💻 Informatique &amp; high-tech</span><!--
      --><span>, </span>
      <span class='name'>🎮 Gaming</span><!--
      --><span>, </span>
      <span class='name'>🍿 Séries &amp; films</span><!--
      --><span>, </span>
      <span class='name'>📕 Lecture</span><!--
      --><span>, </span>
      <span class='name'>🎵 Musique</span><!--
      --><span>, </span>
      <span class='name'>🎨 Art &amp; DIY</span><!--
      -->
    </div>
    <div class='sectionLine'></div>
	</div>

	</body>
</html>
```

### Error string

Using Puppeteer version 21.3.8 This is the path: /home/mat/documents/CV-pdf/index.html WebDriver BiDi listening on ws://127.0.0.1:41251 DevTools listening on ws://127.0.0.1:41251/devtools/browser/c9b772c5-1c2a-41e9-9031-8e4b30e9e7b3 1697445396428   RemoteAgent     INFO    Perform WebSocket upgrade for incoming connection from 127.0.0.1:53964 1697445424589   addons.xpi      ERROR   System addon update list error SyntaxError: XMLHttpRequest.open: 'http://%(server)s/dummy-system-addons.xml' is not a valid URL. ❌ Error building PDF: TimeoutError: Navigation timeout of 30000 ms exceeded     at Timeout.<anonymous> (/home/mat/documents/CV-pdf/node_modules/puppeteer-core/lib/cjs/puppeteer/util/Deferred.js:27:33)     at listOnTimeout (node:internal/timers:569:17)     at process.processTimers (node:internal/timers:512:7) [GFX1-]: glxtest: Could not connect to wayland display, WAYLAND_DISPLAY=wayland-0 WebDriver BiDi listening on ws://127.0.0.1:33177  (firefox-nightly:6782): dconf-CRITICAL **: 10:43:57.423: unable to create directory '/run/user/1000/dconf': Permission denied.  dconf will not work properly.

### Bug behavior

- [ ] Flaky
- [X] PDF

### Background

In a previous issue (#11120) I had troubles with chrome struggling with emoji printing. I'm using WSL2 Ubuntu latest version.

```
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
```

For using my exact setup : 

1. Install WSL by using `wsl --install` for having the last stable ubuntu version
2. Used `curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash` to install nvm
3. Used `nvm install --lts` to install npm
4. Installed resume-cli using `npm install -g resume-cli`
5. Cloning my resume repo using git
6. Installed puppeteer by using `PUPPETEER_PRODUCT=firefox npm install puppeteer`

I discovered that using firefox with puppeteer, there was an issue with `page.goto` if I used it on a **local html file**. The page would open and be visible using `headless: false` but the `console.log("Page opened")` wouldn't print in the command line.

```
const page = await browser.newPage(); // New page created ✅
await page.goto(`file:///${filePath}`) // ❌ Opens the file with the correct path but with an issue
console.log("Page opened")  // ❌ Does not appear in the command line, code stopped before
await page.pdf({
      path: "GAUTHEY_Mathis.pdf",
      format: "A4",
      displayHeaderFooter: false,
      margin: { top: 0, right: 0, bottom: 0, left: 0 },
      // preferCSSPageSize: true,
      // printBackground: false, // Change to true if you want to include background
    });
```

![image](https://github.com/puppeteer/puppeteer/assets/46576952/146aaae6-dc2d-445c-b209-6a1cfe0e0cad)

In my initial code, there was `await page.goto(`file:///${filePath}`);` but the complete path was `/home/mat/documents/CV-pdf/index.html`. So I tried removing one `/` or all of them, the page still opened but the code wasn't continuing its execution and timed out.

- `await page.goto(`file:${filePath}`);`
- `await page.goto(`file://${filePath}`);`

None worked.

What worked in the end was provided by [this post](https://stackoverflow.com/questions/47587352/opening-local-html-file-using-puppeteer/52789802#52789802) and was to add :

```
const fs = require("fs");

...

const page = await browser.newPage();
var contentHtml = fs.readFileSync(`${filePath}`, 'utf8');
await page.setContent(contentHtml);
// await page.goto(`file:${filePath}`); -> Stopped using `goto`
```

### Expectation

New page should open, open local file, and print.

### Reality

```
Using Puppeteer version 21.3.8
This is the path: /home/mat/documents/CV-pdf/index.html
WebDriver BiDi listening on ws://127.0.0.1:41251
DevTools listening on ws://127.0.0.1:41251/devtools/browser/c9b772c5-1c2a-41e9-9031-8e4b30e9e7b3
1697445396428   RemoteAgent     INFO    Perform WebSocket upgrade for incoming connection from 127.0.0.1:53964
1697445424589   addons.xpi      ERROR   System addon update list error SyntaxError: XMLHttpRequest.open: 'http://%(server)s/dummy-system-addons.xml' is not a valid URL.
❌ Error building PDF: TimeoutError: Navigation timeout of 30000 ms exceeded
    at Timeout.<anonymous> (/home/mat/documents/CV-pdf/node_modules/puppeteer-core/lib/cjs/puppeteer/util/Deferred.js:27:33)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
```

And if I was using the `dumpio: true` flag, I had the following error as well before the timeout : 

```
[GFX1-]: glxtest: Could not connect to wayland display, WAYLAND_DISPLAY=wayland-0
WebDriver BiDi listening on ws://127.0.0.1:33177

(firefox-nightly:6782): dconf-CRITICAL **: 10:43:57.423: unable to create directory '/run/user/1000/dconf': Permission denied.  dconf will not work properly.
```

But as of today I don't have it anymore. But the page still isn't printing.

### Puppeteer version

21.3.8

### Node version

18.18.2

### Package manager

npm

### Package manager version

9.8.1

### Operating system

Linux

**Comment by mathisgauthey** [comment]
It is the exact same one, I'll edit this issue and provide it here as well.

Seems to be yes, but I too don't have the capability to test it on a full Linux distro yet, unfortunately 👌

**Comment by OrKoN** [comment]
Does it still happen with the latest version? Could you also try with `protocol: 'webDriverBiDi'` in the launch options?

**Comment by mathisgauthey** [comment]
> Does it still happen with the latest version? Could you also try with `protocol: 'webDriverBiDi'` in the launch options?

Hey there, I'll try to give you an answer asap but I am pretty busy lately. Hoping to give it a try tomorrow.
