### ISSUE TITLE
[Bug]: UNABLE_TO_GET_ISSUER_CERT_LOCALLY when running `npm i`

### ISSUE THREAD

**Issue by PierrickLozach** [puppeteer/puppeteer#11417]
### Minimal, reproducible example

```TypeScript
Install puppeteer via npm
```

### Error string

UNABLE_TO_GET_ISSUER_CERT_LOCALLY

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Expectation

Install puppeteer via npm

### Reality

New install on MAC M1, running `npm i` with latest puppeteer version returns this:

```console
npm ERR! code 1
npm ERR! path /Users/pierrick.lozach/Documents/journey-automation-backend/docker-images/security-advisor-processor/node_modules/puppeteer
npm ERR! command failed
npm ERR! command sh -c -- node install.mjs
npm ERR! ERROR: Failed to set up Chrome r119.0.6045.105! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
npm ERR! Error: unable to get local issuer certificate
npm ERR!     at TLSSocket.onConnectSecure (node:_tls_wrap:1539:34)
npm ERR!     at TLSSocket.emit (node:events:513:28)
npm ERR!     at TLSSocket._finishInit (node:_tls_wrap:953:8)
npm ERR!     at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:734:12) {
npm ERR!   code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY'
npm ERR! }
```

Log shows as follows:

```
526 timing reify:rollback:createSparse Completed in 192ms
527 timing reify:rollback:retireShallow Completed in 0ms
528 timing command:i Completed in 5294ms
529 verbose stack Error: command failed
529 verbose stack     at ChildProcess.<anonymous> (/Users/pierrick.lozach/.nvm/versions/node/v16.20.2/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:63:27)
529 verbose stack     at ChildProcess.emit (node:events:513:28)
529 verbose stack     at maybeClose (node:internal/child_process:1100:16)
529 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
530 verbose pkgid puppeteer@21.5.2
531 verbose cwd /Users/pierrick.lozach/Documents/journey-automation-backend/docker-images/security-advisor-processor
532 verbose Darwin 22.6.0
533 verbose node v16.20.2
534 verbose npm  v8.19.4
535 error code 1
536 error path /Users/pierrick.lozach/Documents/journey-automation-backend/docker-images/security-advisor-processor/node_modules/puppeteer
537 error command failed
538 error command sh -c -- node install.mjs
539 error ERROR: Failed to set up Chrome r119.0.6045.105! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
539 error Error: unable to get local issuer certificate
539 error     at TLSSocket.onConnectSecure (node:_tls_wrap:1539:34)
539 error     at TLSSocket.emit (node:events:513:28)
539 error     at TLSSocket._finishInit (node:_tls_wrap:953:8)
539 error     at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:734:12) {
539 error   code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY'
539 error }
540 verbose exit 1
541 timing npm Completed in 5364ms
```New install on MAC M1, running `npm i` with latest puppeteer version returns this:

```console
npm ERR! code 1
npm ERR! path /Users/pierrick.lozach/Documents/journey-automation-backend/docker-images/security-advisor-processor/node_modules/puppeteer
npm ERR! command failed
npm ERR! command sh -c -- node install.mjs
npm ERR! ERROR: Failed to set up Chrome r119.0.6045.105! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
npm ERR! Error: unable to get local issuer certificate
npm ERR!     at TLSSocket.onConnectSecure (node:_tls_wrap:1539:34)
npm ERR!     at TLSSocket.emit (node:events:513:28)
npm ERR!     at TLSSocket._finishInit (node:_tls_wrap:953:8)
npm ERR!     at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:734:12) {
npm ERR!   code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY'
npm ERR! }
```

Log shows as follows:

```
526 timing reify:rollback:createSparse Completed in 192ms
527 timing reify:rollback:retireShallow Completed in 0ms
528 timing command:i Completed in 5294ms
529 verbose stack Error: command failed
529 verbose stack     at ChildProcess.<anonymous> (/Users/pierrick.lozach/.nvm/versions/node/v16.20.2/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:63:27)
529 verbose stack     at ChildProcess.emit (node:events:513:28)
529 verbose stack     at maybeClose (node:internal/child_process:1100:16)
529 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
530 verbose pkgid puppeteer@21.5.2
531 verbose cwd /Users/pierrick.lozach/Documents/journey-automation-backend/docker-images/security-advisor-processor
532 verbose Darwin 22.6.0
533 verbose node v16.20.2
534 verbose npm  v8.19.4
535 error code 1
536 error path /Users/pierrick.lozach/Documents/journey-automation-backend/docker-images/security-advisor-processor/node_modules/puppeteer
537 error command failed
538 error command sh -c -- node install.mjs
539 error ERROR: Failed to set up Chrome r119.0.6045.105! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
539 error Error: unable to get local issuer certificate
539 error     at TLSSocket.onConnectSecure (node:_tls_wrap:1539:34)
539 error     at TLSSocket.emit (node:events:513:28)
539 error     at TLSSocket._finishInit (node:_tls_wrap:953:8)
539 error     at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:734:12) {
539 error   code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY'
539 error }
540 verbose exit 1
541 timing npm Completed in 5364ms
```

### Puppeteer version

21.5.2

### Node version

16.20.2

### Package manager

npm

### Package manager version

8.19.4

### Operating system

macOS

**Comment by OrKoN** [comment]
I am unable to reproduce on my side (also M1 Mac). It does look like a Node TLS error, perhaps the system is missing certificates or cannot get them? Are you behind a corporate proxy/firewall that might be blocking it?

**Comment by OrKoN** [comment]
Possibly related https://superuser.com/a/1789421

**Comment by PierrickI3** [comment]
Thanks. I have tried that indeed (except for the CA as I am not sure how to check if I have a CA installed by my company).

The thing is that it runs when I install it locally on my machine. I forgot to specify that it fails when running `npm i` from a Dockerfile.

I tried using this in my Dockerfile before running `npm i` but it still fails:
```
RUN npm config set strict-ssl false
RUN export NODE_TLS_REJECT_UNAUTHORIZED=0
```

**Comment by PierrickI3** [comment]
Is there a command to check which site it's trying to download Chrome from?

**Comment by OrKoN** [comment]
It should be `https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/119.0.6045.105/mac-arm64/chrome-mac-arm64.zip` (see https://googlechromelabs.github.io/chrome-for-testing/)

**Comment by PierrickI3** [comment]
Thanks @OrKoN. I can get to this site fine and can download chrome too. 

I am lost. Not sure what to do at this point.

**Comment by OrKoN** [comment]
Also, we publish a docker image with installed Puppeteer here https://github.com/puppeteer/puppeteer/pkgs/container/puppeteer (https://github.com/puppeteer/puppeteer/blob/main/docker/Dockerfile). There must be something wrong with the docker or the docker image you are building (perhaps missing `sudo update-ca-certificates` if it is debian based?).

**Comment by PierrickI3** [comment]
Correct. Here is my Dockerfile:

```
FROM --platform=linux/amd64 ghcr.io/puppeteer/puppeteer:21.5.2

WORKDIR /app

RUN chown -Rh $user:$user /app
USER $user

COPY package*.json ./
RUN npm install --omit=dev

COPY . .

# Start service
CMD [ "npm", "run", "prod" ]
```

**Comment by PierrickI3** [comment]
Now that I look at it closer, our package.json also includes puppeteer@21.5.2 when we test locally.

Does it make sense to also install it from the package.json file when we already use the puppeteer image?

**Comment by OrKoN** [comment]
Puppeteer is already installed along with Chrome to the pptr user home folder so you could just use it

**Comment by OrKoN** [comment]
You can try to set PUPPETEER_SKIP_DOWNLOAD to true and see if it picks up the version that is already installed.

**Comment by OrKoN** [comment]
The dockerfile you posted builds without errors on my machine, btw.

**Comment by PierrickI3** [comment]
it works when setting PUPPETEER_SKIP_DOWNLOAD. Thanks a lot for your help!!
