### ISSUE TITLE
[Bug]: error with puppeteer

### ISSUE THREAD

**Issue by ORESoftware** [puppeteer/puppeteer#11435]
### Minimal, reproducible example

```TypeScript
yak shaving up the wazoo over here, forgive me, but I have errors within errors within errors here..so I am about to give up

code looks like this:


const puppeteer = require('puppeteer');

(async () => {
    // Launch Puppeteer with the extension
    const browser = await puppeteer.launch({
        headless: false,
        args: [
            `--disable-extensions-except=/path/to/your/extension/`,
            `--load-extension=/path/to/your/extension/`
        ]
    });

    console.log('starting puppeteer...');

    // const browser = await puppeteer.connect({
    //     browserURL: 'http://localhost:9222',
    //     defaultViewport: null,
    // });

    console.log('connected');

    // Open the intermediary page
    const page = await browser.newPage();
    await page.goto('file:///Users/alex.mills/codes/vibeirl/chrome-kill-tabs/main.html');

    // Use Puppeteer to control the page to send a message to the extension
    await page.evaluate(() => {
        sendMessageToExtension('Hello from Puppeteer!');
    });

    // Additional Puppeteer commands as needed...

    // Close the browser when done
    await browser.close();
})();

```

and here is the error:

```
alex chrome-kill-tabs % node /Users/alex.mills/codes/vibeirl/chrome-kill-tabs/puppeteer.js
/Users/alex.mills/codes/vibeirl/chrome-kill-tabs/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:286
                    throw new Error(`Could not find Chrome (ver. ${this.puppeteer.browserRevision}). This can occur if either\n` +
                          ^

Error: Could not find Chrome (ver. 119.0.6045.105). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npm install`) or
 2. your cache path is incorrectly configured (which is: /Users/alex.mills/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
    at ChromeLauncher.resolveExecutablePath (/Users/alex.mills/codes/vibeirl/chrome-kill-tabs/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:286:27)
    at ChromeLauncher.executablePath (/Users/alex.mills/codes/vibeirl/chrome-kill-tabs/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:203:25)
    at ChromeLauncher.computeLaunchArguments (/Users/alex.mills/codes/vibeirl/chrome-kill-tabs/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:97:37)
    at async ChromeLauncher.launch (/Users/alex.mills/codes/vibeirl/chrome-kill-tabs/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:79:28)
    at async /Users/alex.mills/codes/vibeirl/chrome-kill-tabs/puppeteer.js:5:21

Node.js v20.5.1
```
```


### Error string

Could not find Chrome

### Bug behavior

- [X] Flaky
- [ ] PDF

### Background

chrome is installed on a macos machine as usual, very very normal over here

### Expectation

no idea what's happening

### Reality

no idea

### Puppeteer configuration file (if used)

_No response_

### Puppeteer version

"^21.5.2"

### Node version

20

### Package manager

npm

### Package manager version

latest

### Operating system

macOS

**Comment by OrKoN** [comment]
The browser does not look it was installed. If you were upgrading Puppeteer, make sure npm runs the post install scripts (e.g., by re-installing Puppeteer) or run `node node_modules/puppeteer/install.mjs` to download the pinned binary.

**Comment by OrKoN** [comment]
Also check `/Users/alex.mills/.cache/puppeteer` to see what browsers you have. You should have 119.0.6045.105 under the chrome folder if it is downloaded.

**Comment by maicss** [comment]
<img width="821" alt="image" src="https://github.com/puppeteer/puppeteer/assets/9784767/b674176c-33ca-4df8-9214-f176ca17f044">

What should I do now? Thank you in advance. @OrKoN
