### ISSUE TITLE
[Bug]: Unable to execute Chrome Extension APIs that require opening Chrome Dev Tools on the Browser

### ISSUE THREAD

**Issue by shivani-mangaleswaran** [puppeteer/puppeteer#11462]
### Minimal, reproducible example

```TypeScript
Run this command  run nataletoscano/reproducible-puppeteer-bug:v1

Please note that you may have to run it multiple times since the issue is intermittent.

When the bug is not reproduced, you will see this message show up in the log: "EXTENSION IS ONLINE!"

When the bug is successfully reproduced, you will NOT see "EXTENSION IS ONLINE!" Instead, the stack trace will look like this:

[64:128:1129/222535.989995:VERBOSE1:tls_handshaker.cc(100)] TlsClient: Continuing handshake
[64:128:1129/222536.008805:VERBOSE1:tls_handshaker.cc(100)] TlsClient: Continuing handshake
[64:128:1129/222536.017256:VERBOSE1:tls_handshaker.cc(100)] TlsClient: Continuing handshake
[64:128:1129/222536.017359:VERBOSE1:tls_handshaker.cc(100)] TlsClient: Continuing handshake
[64:128:1129/222536.025163:VERBOSE1:tls_handshaker.cc(100)] TlsClient: Continuing handshake
[64:128:1129/222536.025247:VERBOSE1:tls_handshaker.cc(100)] TlsClient: Continuing handshake
[64:128:1129/222536.028006:VERBOSE1:tls_handshaker.cc(100)] TlsClient: Continuing handshake
[64:128:1129/222536.028491:VERBOSE1:tls_client_handshaker.cc(519)] Client: handshake finished


Repo: https://github.com/Vorelli/reproducible-puppeteer-bug
```

### Error string

no error

### Bug behavior

- [X] Flaky
- [ ] PDF

### Background

At my company's enterprise application, we use puppeteer to spin up Chrome browsers and have extensions that rely on dev-tools to gather necessary data.

E2E tests began failing intermittently on the latest version of puppeteer. We realized that this is might be due to the puppeteer browser not reliably opening dev-tools on our extensions. As a result, we are unable to execute this Chrome Extension API on our extension [chrome.devtools.network.getHAR ](https://developer.chrome.com/docs/extensions/reference/devtools_network/)

The last stable version of puppeteer when we did not face this issue is v21.3.8 and issues began from v21.4.0.

Perhaps the dependency update of @puppeteer/browsers from 1.7.1 to 1.8.0 introduced in v21.4.0 introduced the issue?

These tests run in a docker container with the following specifications:
Server Version: 20.10.17
API Version: 1.41
Operating System: Ubuntu 20.04.4 LTS

We use puppeteer in conjunction with these packages:
puppeteer-extra v3.3.6
puppeteer-extra-plugin-stealth v2.11.2

Log Trace on Successful Runs:
```

 37:57:1128/005843.804159:VERBOSE1:file_url_loader_factory.cc(453)] FileURLLoader::Start: file:///chrome-engine/extension/networking/devtools.html
notice: App:v1.0.5186 | chrome-engines|AuditClient | driver 2023-11-28T00:58:43.852Z: Chrome launched: version Chrome/119.0.6045.105 {"incoming_queue":"data"}
[37:73:1128/005844.186392:VERBOSE1:network_delegate.cc(35)] NetworkDelegate::NotifyBeforeURLRequest: http://localhost:7980/log
[37:73:1128/005844.186814:VERBOSE1:network_delegate.cc(35)] NetworkDelegate::NotifyBeforeURLRequest: http://localhost:7980/status
[37:73:1128/005844.192308:VERBOSE1:network_delegate.cc(35)] NetworkDelegate::NotifyBeforeURLRequest: http://localhost:7980/log
[37:73:1128/005844.192585:VERBOSE1:network_delegate.cc(35)] NetworkDelegate::NotifyBeforeURLRequest: http://localhost:7980/log
[360:360:1128/005844.334759:VERBOSE1:script_context.cc(144)] Created context:
  extension id:           dummy_data
  frame:                   dummy_data
  URL:                    
  context_type:           BLESSED_EXTENSION
  effective extension id:  dummy_data
  effective context type: BLESSED_EXTENSION
[360:360:1128/005844.335709:VERBOSE1:script_context.cc(144)] Created context:
  extension id:           (none)
  frame:                  (nil)
  URL:                    
  context_type:           UNSPECIFIED
  effective extension id: (none)
  effective context type: UNSPECIFIED
[360:360:1128/005844.337123:VERBOSE1:dispatcher.cc(456)] Num tracked contexts: 1
[37:57:1128/005844.349454:VERBOSE1:file_url_loader_factory.cc(453)] FileURLLoader::Start: file:///path-to-extension-file.js
[37:57:1128/005844.352787:VERBOSE1:file_url_loader_factory.cc(453)] FileURLLoader::Start: file:///path-to-extension-file.js
[37:57:1128/005844.354280:VERBOSE1:file_url_loader_factory.cc(453)] FileURLLoader::Start: file:///path-to-extension-file.js
[37:57:1128/005844.355747:VERBOSE1:file_url_loader_factory.cc(453)] FileURLLoader::Start: ffile:///path-to-extension-file.js
[37:57:1128/005844.356539:VERBOSE1:file_url_loader_factory.cc(453)] FileURLLoader::Start: ffile:///path-to-extension-file.js
[37:73:1128/005844.360969:VERBOSE1:network_delegate.cc(35)] NetworkDelegate::NotifyBeforeURLRequest: http://localhost:7980/log
```
Log stack trace on Failed Runs:
```

[37:57:1128/005701.934712:VERBOSE1:file_url_loader_factory.cc(453)] FileURLLoader::Start: file:///chrome-engine/extension/networking/devtools.html
notice: App:v1.0.5186 | chrome-engines|WebJourneyClient | driver 2023-11-28T00:57:02.225Z: Chrome launched: version Chrome/119.0.6045.105 {"data"}
**[37:73:1128/005702.457349:VERBOSE1:network_delegate.cc(35)] NetworkDelegate::NotifyBeforeURLRequest: http://localhost:7980/log**
[37:73:1128/005702.457552:VERBOSE1:network_delegate.cc(35)] NetworkDelegate::NotifyBeforeURLRequest: http://localhost:7980/status
[37:73:1128/005702.462358:VERBOSE1:network_delegate.cc(35)] NetworkDelegate::NotifyBeforeURLRequest: http://localhost:7980/log
[37:73:1128/005702.462486:VERBOSE1:network_delegate.cc(35)] NetworkDelegate::NotifyBeforeURLRequest: http://localhost:7980/log
[105:105:1128/005702.735057:VERBOSE1:script_context.cc(144)] Created context:
  extension id:           (none)
  frame:                  0x27a7001ee208
  URL:                    
  context_type:           UNSPECIFIED
  effective extension id: (none)
  effective context type: UNSPECIFIED
[105:105:1128/005702.735160:VERBOSE1:script_context.cc(144)] Created context:
  extension id:           (none)
  frame:                  (nil)
  URL:                    
  context_type:           UNSPECIFIED
  effective extension id: (none)
  effective context type: UNSPECIFIED
```
Notice how the extension files load in the successful scenario (v21.3.8), but did not load in the failed case (v21.5.2).

### Expectation

The Chrome browser should always open dev-tools reliably, without failing intermittently and we should be able to execute this Chrome Extension API [chrome.devtools.network.getHAR ](https://developer.chrome.com/docs/extensions/reference/devtools_network/) consistently in a puppeteer browser spun up by our extension.

The expectation is for this to work in puppeteer's "new" mode.

Docker specifications:
Server Version: 20.10.17
API Version: 1.41
Operating System: Ubuntu 20.04.4 LTS

### Reality

The dev-tools window may not always be consistently opening on the browser loaded by an extension as there is an inability to execute this Chrome Extension API [chrome.devtools.network.getHAR](https://developer.chrome.com/docs/extensions/reference/devtools_network/)

### Puppeteer version

21.5.2

### Node version

16.14.2

### Package manager

npm

### Package manager version

8.3.1

### Operating system

Linux

**Comment by OrKoN** [comment]
Can you reproduce it without a Docker (on a Linux host)? Note that Puppeteer does not open devtools by itself and `devtools: true` just sets the argument for the Chrome binary.

**Comment by OrKoN** [comment]
So looks like there is a race condition in Chrome between loading extensions and opening DevTools. What I noticed is that navigating to a new page makes the extension load for me.

**Comment by ShivaniMangal** [comment]
> Can you reproduce it without a Docker (on a Linux host)? 

It is indeed harder to reproduce without docker. It fails more often in the docker container, but it may be due to the large volume of tests we run in our containers. We've noticed that the same test will not always fail, but different tests will fail during different runs, and inevitably a subset of tests will always fail. (All tests use puppeteer and rely on extensions and dev tools)

**Comment by ShivaniMangal** [comment]
`So looks like there is a race condition in Chrome between loading extensions and opening DevTools. What I noticed is that navigating to a new page makes the extension load for me.`

Thanks for taking a look @OrKoN , that's a great observation!
For some context on the different scenarios we've tested so far to reproduce this bug:

1. We do not face this issue with Chrome version 117 and Puppeteer version 21.3.8. 
2. We began facing this issue on both Chrome 118 and Chrome 119, while using any version of Puppeteer v21.4.0 and above.
3. However, we were not able to reproduce the bug when using Chrome versions 118 or 119 with Puppeteer v21.3.8 (Which as you probably already know, officially only supports Chrome version 117)

We always keep our chrome and puppeteer versions in sync for stability, so sticking to the older version of v21.3.8 would not be an option for us. I'm thinking out loud here, but is it possible that puppeteer setting the devtools binary in Chrome is part of the race condition? Or maybe some other update that was introduced in v21.4.0 like the dependency update of @puppeteer/browsers from 1.7.1 to 1.8.0.  Appreciate your help with this!

**Comment by OrKoN** [comment]
> but is it possible that puppeteer setting the devtools binary in Chrome is part of the race condition?

https://github.com/puppeteer/puppeteer/blob/main/packages/puppeteer-core/src/node/ChromeLauncher.ts#L262 the devtools flag only sets the args when launching.

> Or maybe some other update that was introduced in v21.4.0 like the dependency update of @puppeteer/browsers from 1.7.1 to 1.8.0.

I don't see anything that would break this specifically. Need to investigate maybe the extension targets get blocked somehow.

**Comment by OrKoN** [comment]
@ShivaniMangal it would be really helpul if you could try the following: take all arguments that end up being generated by Puppeteer in your configuration (you can see them in `DEBUG=puppeteer:* node yourScript.js`) and in the reproducible example launch the browser using https://pptr.dev/browsers-api/browsers.launch Launch does not set up a CDP connection or anything that Puppeteer does and only launches the browser instance. I wonder if the extension fails to load in that case too.

**Comment by ShivaniMangal** [comment]
@OrKoN Of course! We do in fact use puppeteer launch. [Here](https://github.com/Vorelli/reproducible-puppeteer-bug/blob/7726601fcd6adbafa8c5d7308ce5099ecb800b75/src/index.ts#L57) it is in the reproducible code and here are the [launch options](https://github.com/Vorelli/reproducible-puppeteer-bug/blob/7726601fcd6adbafa8c5d7308ce5099ecb800b75/src/index.ts#L30)

I ran the puppeteer debug on the script as suggested and grabbed the arguments and added it to the launch options. I also commented the existing launch options to avoid repetition. It took  quite a few runs to reproduce the bug, (ie. to get the extension to not load), but once it began failing, it continued to fail consistently. Here's the stack trace:
```
> reproducepuppeteerbug@1.0.0 start
> node dist/index.js

[65:93:1202/025231.988943:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[65:124:1202/025232.376439:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[65:124:1202/025232.376524:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[65:93:1202/025232.382339:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[65:93:1202/025232.382456:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[65:93:1202/025232.382482:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[65:93:1202/025232.382502:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[65:93:1202/025232.434082:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[65:93:1202/025232.434199:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")

DevTools listening on ws://127.0.0.1:42773/devtools/browser/6e97834c-043a-409b-b9ce-f0bf8e435690
[65:93:1202/025232.531552:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[65:93:1202/025232.531625:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[133:133:1202/025232.761522:ERROR:viz_main_impl.cc(196)] Exiting GPU process due to errors during initialization
[65:266:1202/025232.766979:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[65:266:1202/025232.767134:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[65:266:1202/025232.767436:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[65:266:1202/025232.768095:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[65:266:1202/025232.769412:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[287:287:1202/025233.078330:ERROR:viz_main_impl.cc(196)] Exiting GPU process due to errors during initialization
[180:7:1202/025233.196880:ERROR:command_buffer_proxy_impl.cc(127)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[190:7:1202/025233.197633:ERROR:command_buffer_proxy_impl.cc(127)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
```

I also noticed this error `TargetCloseError: Protocol error (Target.setAutoAttach): Target closed ` when running the debug command. Here's a snippet of the failed log trace after running  `DEBUG=puppeteer:* ts-node --esm src/index.ts ` I'm attaching the full stack trace with verbose logging below, in case that helps.

```
puppeteer:error [
  puppeteer:error   TargetCloseError: Protocol error (Target.setAutoAttach): Target closed
  puppeteer:error       at CallbackRegistry.clear (/Users/shivanimangaleswaran/dev/minimal-pup-bug-reproduction/node_modules/puppeteer-core/src/common/CallbackRegistry.ts:103:30)
  puppeteer:error       at CdpCDPSession._onClosed (/Users/shivanimangaleswaran/dev/minimal-pup-bug-reproduction/node_modules/puppeteer-core/src/cdp/CDPSession.ts:158:21)
  puppeteer:error       at Connection.onMessage (/Users/shivanimangaleswaran/dev/minimal-pup-bug-reproduction/node_modules/puppeteer-core/src/cdp/Connection.ts:175:17)
  puppeteer:error       at runNextTicks (node:internal/process/task_queues:61:5)
  puppeteer:error       at listOnTimeout (node:internal/timers:528:9)
  puppeteer:error       at processTimers (node:internal/timers:502:7) {
  puppeteer:error     cause: ProtocolError
  puppeteer:error         at Callback.<instance_members_initializer> (/Users/shivanimangaleswaran/dev/minimal-pup-bug-reproduction/node_modules/puppeteer-core/src/common/CallbackRegistry.ts:114:12)
  puppeteer:error         at new Callback (/Users/shivanimangaleswaran/dev/minimal-pup-bug-reproduction/node_modules/puppeteer-core/src/common/CallbackRegistry.ts:119:3)
  puppeteer:error         at CallbackRegistry.create (/Users/shivanimangaleswaran/dev/minimal-pup-bug-reproduction/node_modules/puppeteer-core/src/common/CallbackRegistry.ts:37:22)
  puppeteer:error         at Connection._rawSend (/Users/shivanimangaleswaran/dev/minimal-pup-bug-reproduction/node_modules/puppeteer-core/src/cdp/Connection.ts:128:22)
  puppeteer:error         at CdpCDPSession.send (/Users/shivanimangaleswaran/dev/minimal-pup-bug-reproduction/node_modules/puppeteer-core/src/cdp/CDPSession.ts:105:29)
  puppeteer:error         at ChromeTargetManager.#onAttachedToTarget (/Users/shivanimangaleswaran/dev/minimal-pup-bug-reproduction/node_modules/puppeteer-core/src/cdp/ChromeTargetManager.ts:399:15)
  puppeteer:error         at listener (/Users/shivanimangaleswaran/dev/minimal-pup-bug-reproduction/node_modules/puppeteer-core/src/cdp/ChromeTargetManager.ts:187:36)
  puppeteer:error         at /Users/shivanimangaleswaran/dev/minimal-pup-bug-reproduction/node_modules/puppeteer-core/lib/cjs/third_party/mitt/mitt.js:1:732
  puppeteer:error         at Array.map (<anonymous>)
  puppeteer:error         at Object.emit (/Users/shivanimangaleswaran/dev/minimal-pup-bug-reproduction/node_modules/puppeteer-core/lib/cjs/third_party/mitt/mitt.js:1:716)
  puppeteer:error   }
  puppeteer:error ] +0ms
  ```
  
  
[failure_log.txt](https://github.com/puppeteer/puppeteer/files/13533262/failure_log.txt)

**Comment by OrKoN** [comment]
@ShivaniMangal I meant `@puppeeteer/browsers` launch not `puppeteer`'s launch.

**Comment by ShivaniMangal** [comment]
@OrKoN  My bad! I am able to install and launch a @puppeteer/browser easily using CLI. I've followed the docs and created a browser `Process` using `launch()`, but I could use your help understanding how to spin up an actual browser from the Process instance. Right now the script runs without errors, but fails to actually spin up a browser. 

The docs state: `The programmatic API allows installing and launching browsers from your code. See the test folder for examples on how to use the install, canInstall, launch, computeExecutablePath, computeSystemExecutablePath and other methods.` I can't seem to locate this test folder, if could point me in the direction of these examples that would be great!

**Comment by OrKoN** [comment]
I meant something like https://gist.github.com/OrKoN/03379638045d25d0147aa8ec11dd7043 I have tested that and unfortunately the problem seems to be related specifically to Puppeteer or perhaps delays caused by Puppeteer.

**Comment by OrKoN** [comment]
I have noticed that the error only seems to happen with the regular Chrome. And it seems to always work with the bundled Chrome for Testing version. Remove the env var PUPPETEER_SKIP_DOWNLOAD and do not provide the custom executable path. Perhaps it's related to some of the Chrome policies.

**Comment by ShivaniMangal** [comment]
@OrKoN Thanks again for looking into this! I tried the latest version of puppeteer v21.6.0 and I'm still seeing this issue. Do you have any idea about when we can expect a fix?

**Comment by OrKoN** [comment]
I seem to not be able to reproduce after removing the slowMo. I suspect since Puppeteer is now using tab targets it takes a bit longer to connect to targets so the extension loading times out on the DevTools side? I have not confirmed it yet but I see that the extension iframe is being attached and then removed by the browser.

**Comment by ShivaniMangal** [comment]
@OrKoN We use slowMo to give us enough time to download HAR files from the browser. You're right when we disabled slowMo, the issue was not reproducible. However, disabling slowMo is not an option for our use case. Tests related to HAR collection are inevitably failing after disabling slowMo.

**Comment by ShivaniMangal** [comment]
@OrKoN We updated our application to Node 20 and tried the latest version of puppeteer, but still have the issue of our extensions not being able to run reliably with puppeteer slowMo enabled. On disabling slowMo, we do not face this issue, however we do require slowMo to be enabled to give us enough time for HAR collection. Any idea if there is a plan to roll out a fix for this?

**Comment by OrKoN** [comment]
@ShivaniMangal how about you wait for N seconds to give time for HAR collection instead of using slowMo?
