### ISSUE TITLE
[Feature]: Is there way to validate margins for different page formats & custom page dimensions

### ISSUE THREAD

**Issue by satyajitnayk** [puppeteer/puppeteer#11539]
### Feature description

Puppeteer throws error `ProtocolError: Protocol error (Page.printToPDF): invalid print parameters: content area is empty ...` **_when we use invalid margins_, is there way to validate margins gracefully??** @OrKoN @jrandolf @Lightning00Blade 

**Error message:**
```cmd
ProtocolError: Protocol error (Page.printToPDF): invalid print parameters: content area is empty
    at <instance_members_initializer> (.../node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:92:14)
    at new Callback (.../node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:96:16)
    at CallbackRegistry.create (.../node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:29:26)
    at Connection._rawSend (.../node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:88:26)
    at CdpCDPSession.send (.../node_modules/puppeteer-core/lib/esm/puppeteer/cdp/CDPSession.js:75:33)
    at CdpPage.createPDFStream (.../node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Page.js:820:63)
    at CdpPage.pdf (.../node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Page.js:847:37)
    at .../t.js:20:14
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Example code:**
```js
 // const puppeteer = require('puppeteer');
import puppeteer from 'puppeteer';
puppeteer.PDFOptions;
try {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  const htmlContent = `<html><body><h1>Margin Test for a4</h1></body></html>`;
  await page.setContent(htmlContent);
  const pdfOptions = {
    margin: {
      top: '10in',
      right: '10in',
      bottom: '10in',
      left: '10in',
    },
    printBackground: true,
    format: 'a4',
  };

  await page.pdf(pdfOptions);
} catch (error) {
  console.log(error);
}
```

**Comment by jrandolf** [comment]
> is there way to validate margins gracefully?

Not at the moment. It would require use to get the computation from the PDF generator. `try-catching`ing `page.pdf` is actually more graceful than you'd expect since you can analyze the error message for _all_ problems related to generation.

After all, since the goal is to generate a PDF, wouldn't all errors need to be addressed anyway?
