### ISSUE TITLE
[Bug]: puppeteer.connect crashes Chromium when using --load-extension with uBlock

### ISSUE THREAD

**Issue by erikschul** [puppeteer/puppeteer#11572]
### Minimal, reproducible example

```TypeScript
How I reproduce it:

1. Start Chromium with user-data-dir, and install uBlock (1.54.0_0).
2. Copy directory in `Default/Extensions/...`
3. Start Puppeteer with puppeteer.launch({ ... --load-extension=..., --remote-debugging-port=9000 }), pointing to that directory.
4. Attach with separate script: puppeteer.connect({ browserWSEndpoint:  ... })
This causes Chromium to crash.
```

It doesn't crash when:
- using other extensions, e.g. AdBlockPlus (but is missing a filter that is available in uBlock)
- using a user-data-dir where the extension is preinstalled (and without using --load-extension)

### Error string

crash without error message

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I've tried various launch args, but nothing prevents a crash.

### Expectation

not crashing

### Reality

crashing

### Puppeteer version

21.6.1

### Node version

18.19.0

### Package manager

npm

### Package manager version

10.2.3

### Operating system

Linux

**Comment by erikschul** [comment]
It would be complicated to make this reproducible by the bot. Do you require that?

**Comment by OrKoN** [comment]
Where can I get the extension? Does the Chromium crash or Puppeteer? Does it work if you launch the Chromium with the same args without using Puppeteer?

**Comment by erikschul** [comment]
@OrKoN Thanks, I should have covered that in the initial report:

The problem is specifically the combination of `--load-extension` and `--remote-debugging-port`, and it only crashes when you connect to the debugging port.

This is the extension: https://chromewebstore.google.com/detail/cjpalhdlnbpafiamejdnhcphjbkeiagm

I have a "server" script which starts Chromium. The browser starts and can be interacted with manually. The extension is loaded and works correctly, and so on.

But when I connect Puppeteer via `puppeteer.connect` (over CDP), Chromium crashes, and puppeteer returns this error:

```
caught error:  TargetCloseError: Protocol error (Target.setDiscoverTargets): Target closed
    at CallbackRegistry.clear (/workspace/client/node_modules/.pnpm/puppeteer-core@21.5.2/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:85:36)
    at #onClose (/workspace/client/node_modules/.pnpm/puppeteer-core@21.5.2/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:166:25)
    at WebSocket.<anonymous> (/workspace/client/node_modules/.pnpm/puppeteer-core@21.5.2/node_modules/puppeteer-core/lib/cjs/puppeteer/node/NodeWebSocketTransport.js:57:30)
    at callListener (/workspace/client/node_modules/.pnpm/ws@8.14.2/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onClose (/workspace/client/node_modules/.pnpm/ws@8.14.2/node_modules/ws/lib/event-target.js:220:9)
    at WebSocket.emit (node:events:517:28)
    at WebSocket.emitClose (/workspace/client/node_modules/.pnpm/ws@8.14.2/node_modules/ws/lib/websocket.js:260:10)
    at Socket.socketOnClose (/workspace/client/node_modules/.pnpm/ws@8.14.2/node_modules/ws/lib/websocket.js:1272:15)
    at Socket.emit (node:events:517:28)
    at TCP.<anonymous> (node:net:350:12) {
  cause: ProtocolError
      at <instance_members_initializer> (/workspace/client/node_modules/.pnpm/puppeteer-core@21.5.2/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:96:14)
      at new Callback (/workspace/client/node_modules/.pnpm/puppeteer-core@21.5.2/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:100:16)
      at CallbackRegistry.create (/workspace/client/node_modules/.pnpm/puppeteer-core@21.5.2/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:32:26)
      at Connection._rawSend (/workspace/client/node_modules/.pnpm/puppeteer-core@21.5.2/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:91:26)
      at Connection.send (/workspace/client/node_modules/.pnpm/puppeteer-core@21.5.2/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:85:21)
      at ChromeTargetManager.initialize (/workspace/client/node_modules/.pnpm/puppeteer-core@21.5.2/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ChromeTargetManager.js:96:32)
      at CdpBrowser._attach (/workspace/client/node_modules/.pnpm/puppeteer-core@21.5.2/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Browser.js:80:35)
      at CdpBrowser._create (/workspace/client/node_modules/.pnpm/puppeteer-core@21.5.2/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Browser.js:33:23)
      at _connectToCdpBrowser (/workspace/client/node_modules/.pnpm/puppeteer-core@21.5.2/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/BrowserConnector.js:71:51)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
}
```

Maybe it's a Chromium/CDP/uBlock bug, rather than puppeteer, and puppeteer just happens to trigger it when connecting?

**Comment by OrKoN** [comment]
@erikschul can you try a Chrome build? You should see the crash in chrome://crashes then. It would be helpful if you could share the crash ID for the uploaded crash. It does look like Puppeteer is only a trigger.

**Comment by erikschul** [comment]
Server code:

```
const puppeteer = require("puppeteer-core")

function sleep(ms) {
	return new Promise((resolve) => setTimeout(resolve, ms))
}

;(async () => {
	let extension = "/workspace/ublock/1.54.0_0/"

	browser = await puppeteer.launch({
		args: [
			"--remote-debugging-port=4500",
			"--start-maximized",
			"--no-sandbox",
			`--load-extension=${extension}`,
		],
		headless: false,
		defaultViewport: null,
		executablePath: "/usr/bin/chromium",
		ignoreDefaultArgs: ["--enable-automation", "--disable-extensions"],
	})

	while (true) {
		await sleep(1_000)
	}
})()
```

Client code:
```
import puppeteer, { Browser, Page } from "puppeteer"

let browser = await puppeteer.connect({
  browserWSEndpoint: "ws://" + this.options.wsEndpoint.replace("ws://", ""),
  ignoreHTTPSErrors: true,
  defaultViewport: null,
})
```

**Comment by OrKoN** [comment]
What's the version of /usr/bin/chromium?

**Comment by erikschul** [comment]
@OrKoN Unfortunately there is no Chrome build for arm64 deployments. But maybe that's part of the problem as well, i.e. an architecture-specific bug. If I remember correctly, I'm using `/usr/bin/chromium` via apt-get, because it was the easiest way to get an arm64-supported build.

`chromium --version`
```
Chromium 120.0.6099.109 built on Debian 12.4, running on Debian 12.2
```

**Comment by erikschul** [comment]
For example, `npx @puppeteer/browsers install chrome@stable` installs the x64 version.
It doesn't seem that arm64 is supported?

`npx @puppeteer/browsers install --help`
```
...
  --platform  Platform that the binary needs to be compatible with.
                                [string] [choices: "linux", "mac", "mac_arm", "win32", "win64"] [default: Auto-detected]
```

**Comment by OrKoN** [comment]
Chrome/Chromium do not provide arm64 binaries. Only Mac ARM is supported. 

I can reproduce the crash in the latest Chrome Canary though (crash ID cb2e7d038f26b88c)

**Comment by erikschul** [comment]
I've opened an issue here: https://bugs.chromium.org/p/chromium/issues/detail?id=1514571

**Comment by erikschul** [comment]
@OrKoN Thanks for the help :)

**Comment by danielepolencic** [comment]
FWIW, I have the exact same issue (i.e. puppeteer disconnecting intermittently with `(Target.setDiscoverTargets): Target closed` when I use uBlock). Removing uBlock fixes the issue.
I tried to collect more logs and data around this (for quite some time now), but nothing stands out (i.e. chrome logs, CDP logs, xvfb logs). The only thing I noticed is that it does happen ~30% of the time — could it be a race condition?
However, I can add that the issue is appearing for me with the following setup:

- Chrome 119 + Xvfb (using [Chrome standalone](https://github.com/SeleniumHQ/docker-selenium))
- OS is Ubuntu on x86.
- uBlock pinned at 1.54.0
- puppeteer-core at 21.5.2

**Comment by erikschul** [comment]
@danielepolencic "disconnecting intermittently" sounds to me like a different issue (where Chrome keeps running, but puppeteer is disconnected/loses connection sometimes, such that retrying is partly resolves the problem).

This issue is about Chrome starting and running, but crashing only upon connecting to it via CDP. 
To clarify: Is this the exact symptom you're experiencing? But not 100% of the time?

**Comment by danielepolencic** [comment]
Apologies for the confusion: I use puppeteer-core, so every crash (e.g. V8 OOM) looks like a disconnect.

> where Chrome keeps running, but puppeteer is disconnected/loses connection sometimes, but where reconnecting is possible

Chrome is not running, and the process is terminated with the `SIGSEGV`.

> To clarify: Is this the exact symptom you're experiencing? But not 100% of the time?

I believe so. The thread resonated with me (and I was able to solve it by disabling ublock). It is not happening 100% of the time though (which makes it very hard to track down).

**Comment by OrKoN** [comment]
Does anyone have a chance to re-test using the latest versions?

**Comment by pkiv** [comment]
We're still seeing this on Puppeteer 22.10.0

**Comment by pkiv** [comment]
@OrKoN - any chance you've had a chance to take a look at this?
