### ISSUE TITLE
[Bug]: Unable run ng e2e in Angular 17.0.7, Puppeteer and Jest

### ISSUE THREAD

**Issue by doggy8088** [puppeteer/puppeteer#11590]
### Minimal, reproducible example

I was reported [an issue](https://github.com/angular/angular-cli/issues/26723) about Angular CLI's `ng e2e` command that supported by puppeteer.

Here are the minimal repo steps:

```sh
ng new demo1 --ssr=false --style=css
cd demo1
ng e2e
# I choose Puppeteer & Jest
ng e2e
```

### Error string

🛑 Test failed! 🛑

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Expectation

I expected to run `ng e2e` correctly.

### Reality

Error happened.

```txt
Building tests 🛠️ ...

 Spawning test server ⚙️ ...


Initial Chunk Files | Names         |  Raw Size
polyfills.js        | polyfills     |  82.71 kB |
main.js             | main          |  23.22 kB |
styles.css          | styles        |  95 bytes |

                    | Initial Total | 106.03 kB

Application bundle generation complete. [2.170 seconds]
  ➜  Local:   http://localhost:4200/

 Running tests 🧪 ...

No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
In G:\Projects\demo1\e2e
  6 files checked.
  testMatch: G:/Projects/demo1/e2e/build/**\?(*.)+(e2e).js?(x) - 0 matches
  testPathIgnorePatterns: \\node_modules\\ - 6 matches
  testRegex:  - 0 matches
Pattern:  - 0 matches

 🛑 Test failed! 🛑
✘ [ERROR] The build was canceled

✘ [ERROR] Terminating worker thread [plugin angular-vite-optimize-deps]

    node_modules/piscina/dist/src/index.js:676:26:
      676 │             taskInfo.done(new Error('Terminating worker thread'));
          ╵                           ^

    at ThreadPool.destroy (G:\Projects\demo1\node_modules\piscina\dist\src\index.js:676:27)
    at Piscina.destroy (G:\Projects\demo1\node_modules\piscina\dist\src\index.js:795:65)
    at JavaScriptTransformer.close (G:\Projects\demo1\node_modules\@angular-devkit\build-angular\src\tools\esbuild\javascript-transformer.js:111:40)
    at G:\Projects\demo1\node_modules\@angular-devkit\build-angular\src\builders\dev-server\vite-server.js:120:36
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)

  This error came from the "onLoad" callback registered here:

    node_modules/@angular-devkit/build-angular/src/builders/dev-server/vite-server.js:634:22:
      634 │                 build.onLoad({ filter: /\.[cm]?js$/ }, async (args) => {
          ╵                       ~~~~~~

    at setup (G:\Projects\demo1\node_modules\@angular-devkit\build-angular\src\builders\dev-server\vite-server.js:634:23)
    at handlePlugins (G:\Projects\demo1\node_modules\vite\node_modules\esbuild\lib\main.js:1292:21)
    at buildOrContextImpl (G:\Projects\demo1\node_modules\vite\node_modules\esbuild\lib\main.js:978:5)
    at Object.buildOrContext (G:\Projects\demo1\node_modules\vite\node_modules\esbuild\lib\main.js:786:5)
    at G:\Projects\demo1\node_modules\vite\node_modules\esbuild\lib\main.js:2186:68
    at new Promise (<anonymous>)
    at Object.context (G:\Projects\demo1\node_modules\vite\node_modules\esbuild\lib\main.js:2186:27)
    at Object.context (G:\Projects\demo1\node_modules\vite\node_modules\esbuild\lib\main.js:2026:58)
    at prepareEsbuildOptimizerRun (file:///G:/Projects/demo1/node_modules/vite/dist/node/chunks/dep-68d1a114.js:46041:35)

✘ [ERROR] Terminating worker thread [plugin angular-vite-optimize-deps]

    node_modules/piscina/dist/src/index.js:676:26:
      676 │             taskInfo.done(new Error('Terminating worker thread'));
          ╵                           ^

    at ThreadPool.destroy (G:\Projects\demo1\node_modules\piscina\dist\src\index.js:676:27)
    at Piscina.destroy (G:\Projects\demo1\node_modules\piscina\dist\src\index.js:795:65)
    at JavaScriptTransformer.close (G:\Projects\demo1\node_modules\@angular-devkit\build-angular\src\tools\esbuild\javascript-transformer.js:111:40)
    at G:\Projects\demo1\node_modules\@angular-devkit\build-angular\src\builders\dev-server\vite-server.js:120:36
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)

  This error came from the "onLoad" callback registered here:

    node_modules/@angular-devkit/build-angular/src/builders/dev-server/vite-server.js:634:22:
      634 │                 build.onLoad({ filter: /\.[cm]?js$/ }, async (args) => {
          ╵                       ~~~~~~

    at setup (G:\Projects\demo1\node_modules\@angular-devkit\build-angular\src\builders\dev-server\vite-server.js:634:23)
    at handlePlugins (G:\Projects\demo1\node_modules\vite\node_modules\esbuild\lib\main.js:1292:21)
    at buildOrContextImpl (G:\Projects\demo1\node_modules\vite\node_modules\esbuild\lib\main.js:978:5)
    at Object.buildOrContext (G:\Projects\demo1\node_modules\vite\node_modules\esbuild\lib\main.js:786:5)
    at G:\Projects\demo1\node_modules\vite\node_modules\esbuild\lib\main.js:2186:68
    at new Promise (<anonymous>)
    at Object.context (G:\Projects\demo1\node_modules\vite\node_modules\esbuild\lib\main.js:2186:27)
    at Object.context (G:\Projects\demo1\node_modules\vite\node_modules\esbuild\lib\main.js:2026:58)
    at prepareEsbuildOptimizerRun (file:///G:/Projects/demo1/node_modules/vite/dist/node/chunks/dep-68d1a114.js:46041:35)

✘ [ERROR] Terminating worker thread [plugin angular-vite-optimize-deps]

    node_modules/piscina/dist/src/index.js:676:26:
      676 │             taskInfo.done(new Error('Terminating worker thread'));
          ╵                           ^

    at ThreadPool.destroy (G:\Projects\demo1\node_modules\piscina\dist\src\index.js:676:27)
    at Piscina.destroy (G:\Projects\demo1\node_modules\piscina\dist\src\index.js:795:65)
    at JavaScriptTransformer.close (G:\Projects\demo1\node_modules\@angular-devkit\build-angular\src\tools\esbuild\javascript-transformer.js:111:40)
    at G:\Projects\demo1\node_modules\@angular-devkit\build-angular\src\builders\dev-server\vite-server.js:120:36
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)

  This error came from the "onLoad" callback registered here:

    node_modules/@angular-devkit/build-angular/src/builders/dev-server/vite-server.js:634:22:
      634 │                 build.onLoad({ filter: /\.[cm]?js$/ }, async (args) => {
          ╵                       ~~~~~~

    at setup (G:\Projects\demo1\node_modules\@angular-devkit\build-angular\src\builders\dev-server\vite-server.js:634:23)
    at handlePlugins (G:\Projects\demo1\node_modules\vite\node_modules\esbuild\lib\main.js:1292:21)
    at buildOrContextImpl (G:\Projects\demo1\node_modules\vite\node_modules\esbuild\lib\main.js:978:5)
    at Object.buildOrContext (G:\Projects\demo1\node_modules\vite\node_modules\esbuild\lib\main.js:786:5)
    at G:\Projects\demo1\node_modules\vite\node_modules\esbuild\lib\main.js:2186:68
    at new Promise (<anonymous>)
    at Object.context (G:\Projects\demo1\node_modules\vite\node_modules\esbuild\lib\main.js:2186:27)
    at Object.context (G:\Projects\demo1\node_modules\vite\node_modules\esbuild\lib\main.js:2026:58)
    at prepareEsbuildOptimizerRun (file:///G:/Projects/demo1/node_modules/vite/dist/node/chunks/dep-68d1a114.js:46041:35)

  The plugin "angular-vite-optimize-deps" was triggered by this import

    node_modules/@angular/platform-browser/fesm2022/platform-browser.mjs:11:40:
      11 │ import { ɵwithHttpTransferCache } from '@angular/common/http';
         ╵                                        ~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Terminating worker thread [plugin angular-vite-optimize-deps]

    node_modules/piscina/dist/src/index.js:246:29:
      246 │     ThreadTermination: () => new Error('Terminating worker thread'),
          ╵                              ^

    at Object.ThreadTermination (G:\Projects\demo1\node_modules\piscina\dist\src\index.js:246:30)
    at WorkerInfo.destroy (G:\Projects\demo1\node_modules\piscina\dist\src\index.js:268:34)
    at ThreadPool._removeWorker (G:\Projects\demo1\node_modules\piscina\dist\src\index.js:511:20)
    at ThreadPool.destroy (G:\Projects\demo1\node_modules\piscina\dist\src\index.js:682:18)
    at Piscina.destroy (G:\Projects\demo1\node_modules\piscina\dist\src\index.js:795:65)
    at JavaScriptTransformer.close (G:\Projects\demo1\node_modules\@angular-devkit\build-angular\src\tools\esbuild\javascript-transformer.js:111:40)
    at G:\Projects\demo1\node_modules\@angular-devkit\build-angular\src\builders\dev-server\vite-server.js:120:36
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)

  This error came from the "onLoad" callback registered here:

    node_modules/@angular-devkit/build-angular/src/builders/dev-server/vite-server.js:634:22:
      634 │                 build.onLoad({ filter: /\.[cm]?js$/ }, async (args) => {
          ╵                       ~~~~~~

    at setup (G:\Projects\demo1\node_modules\@angular-devkit\build-angular\src\builders\dev-server\vite-server.js:634:23)
    at handlePlugins (G:\Projects\demo1\node_modules\vite\node_modules\esbuild\lib\main.js:1292:21)
    at buildOrContextImpl (G:\Projects\demo1\node_modules\vite\node_modules\esbuild\lib\main.js:978:5)
    at Object.buildOrContext (G:\Projects\demo1\node_modules\vite\node_modules\esbuild\lib\main.js:786:5)
    at G:\Projects\demo1\node_modules\vite\node_modules\esbuild\lib\main.js:2186:68
    at new Promise (<anonymous>)
    at Object.context (G:\Projects\demo1\node_modules\vite\node_modules\esbuild\lib\main.js:2186:27)
    at Object.context (G:\Projects\demo1\node_modules\vite\node_modules\esbuild\lib\main.js:2026:58)
    at prepareEsbuildOptimizerRun (file:///G:/Projects/demo1/node_modules/vite/dist/node/chunks/dep-68d1a114.js:46041:35)

Please look at the output above to determine the issue!
```

### Puppeteer version

21.6.1

### Node version

v18.16.0

### Package manager

npm

### Package manager version

9.5.1

### Operating system

Windows

**Comment by OrKoN** [comment]
@Lightning00Blade PTAL

**Comment by OrKoN** [comment]
Unable to reproduce on Mac so might be a Windows-specific.

**Comment by Lightning00Blade** [comment]
It seems that the pattern that we use was having issue for Windows.
Please update it in the config to:
```js
testMatch: ['<rootDir>/build/**/*.e2e.js'],
```
The issue will fixed for future uses in `0.5.6`.

**Comment by doggy8088** [comment]
@Lightning00Blade When will you release next version?

**Comment by Lightning00Blade** [comment]
Just did - https://github.com/puppeteer/puppeteer/releases/tag/ng-schematics-v0.5.6,
so feature install should work out of the box thank you for reporting it.

**Comment by doggy8088** [comment]
Just confirmed. It works. Thank you.
