### ISSUE TITLE
TimeOutError

### ISSUE THREAD

**Issue by AnicetJonhia** [puppeteer/puppeteer#11762]
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');
const fs = require('fs');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();

  const postUrl = 'https://www.linkedin.com/feed/update/urn:li:activity:7156737855141113856/';
  await page.goto(postUrl);

  // Attendez que la page soit complètement chargée
  await page.waitForTimeout(5000);

  // Vérifiez si le bouton est déjà présent
  const likeButtonExists = await page.$('button[data-control-name="likes_count"]');
  if (likeButtonExists) {
    console.log('Le bouton "Voir les mentions J\'aime" a été trouvé.');

    // Sélecteur pour le bouton "Voir les mentions J'aime"
    const likeButtonSelector = 'button[data-control-name="likes_count"]';

    // Cliquez sur le bouton "Voir les mentions J'aime"
    await page.click(likeButtonSelector);

    // Attendez que la liste complète des personnes qui ont aimé soit chargée
    await page.waitForSelector('.social-details-reactors-tab-body-list-item');

    // Récupérez les informations de chaque personne ayant aimé le post
    const likedProfiles = await page.evaluate(() => {
      const profiles = [];
      const profileElements = document.querySelectorAll('.social-details-reactors-tab-body-list-item');

      profileElements.forEach((element) => {
        const name = element.querySelector('.artdeco-entity-lockup__title span').textContent.trim();
        const connectionDegree = element.querySelector('.artdeco-entity-lockup__badge .artdeco-entity-lockup__degree').textContent.trim();
        const profileLink = element.querySelector('a').href;
        const profileDescription = element.querySelector('.artdeco-entity-lockup__caption').textContent.trim();

        profiles.push({
          name,
          connectionDegree,
          profileLink,
          profileDescription,
        });
      });

      return profiles;
    });

    // Enregistrez les informations dans un fichier CSV
    const csvContent = 'Nom,Connection_Degree,Profil_Link,Profil_Description\n' +
      likedProfiles.map(profile => `${profile.name},${profile.connectionDegree},${profile.profileLink},"${profile.profileDescription}"`).join('\n');

    fs.writeFileSync('liked_profiles.csv', csvContent);

    // Affiche le message une fois que le CSV est créé
    console.log('Extraction des données terminée. Les informations ont été enregistrées dans liked_profiles.csv');
  } else {
    console.log('Le bouton "Voir les mentions J\'aime" n\'a pas été trouvé.');
  }

  // Fermeture du navigateur
  await browser.close();
})();
```

### Error string

Timeout error

### Bug behavior

- [X] Flaky
- [ ] PDF

### Background

to debug it

### Expectation

I expected it on chrome

### Reality

/home/anicetjonhia/Public/AJ/Esti_L2_IDEV/ListOfLikesToCSV/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:50
            this.#timeoutError = new Errors_js_1.TimeoutError(`Waiting failed: ${options.timeout}ms exceeded`);
                                 ^

TimeoutError: Waiting for selector `button[data-control-name="likes_count"]` failed: Waiting failed: 60000ms exceeded
    at new WaitTask (/home/anicetjonhia/Public/AJ/Esti_L2_IDEV/ListOfLikesToCSV/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:50:34)
    at IsolatedWorld.waitForFunction (/home/anicetjonhia/Public/AJ/Esti_L2_IDEV/ListOfLikesToCSV/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Realm.js:25:26)
    at PQueryHandler.waitFor (/home/anicetjonhia/Public/AJ/Esti_L2_IDEV/ListOfLikesToCSV/node_modules/puppeteer-core/lib/cjs/puppeteer/common/QueryHandler.js:170:95)
    at async CdpFrame.waitForSelector (/home/anicetjonhia/Public/AJ/Esti_L2_IDEV/ListOfLikesToCSV/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Frame.js:494:21)
    at async CdpPage.waitForSelector (/home/anicetjonhia/Public/AJ/Esti_L2_IDEV/ListOfLikesToCSV/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Page.js:1249:20)
    at async /home/anicetjonhia/Public/AJ/Esti_L2_IDEV/ListOfLikesToCSV/main.js:19:3

Node.js v21.5.0
[anicetjonhia@archlinux ListOfLikesToCSV]$ 

### Puppeteer configuration file (if used)

```TypeScript
const puppeteer = require('puppeteer');
const fs = require('fs');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();

  const postUrl = 'https://www.linkedin.com/feed/update/urn:li:activity:7156737855141113856/';
  await page.goto(postUrl);

  // Attendez que la page soit complètement chargée
  await page.waitForTimeout(5000);

  // Vérifiez si le bouton est déjà présent
  const likeButtonExists = await page.$('button[data-control-name="likes_count"]');
  if (likeButtonExists) {
    console.log('Le bouton "Voir les mentions J\'aime" a été trouvé.');

    // Sélecteur pour le bouton "Voir les mentions J'aime"
    const likeButtonSelector = 'button[data-control-name="likes_count"]';

    // Cliquez sur le bouton "Voir les mentions J'aime"
    await page.click(likeButtonSelector);

    // Attendez que la liste complète des personnes qui ont aimé soit chargée
    await page.waitForSelector('.social-details-reactors-tab-body-list-item');

    // Récupérez les informations de chaque personne ayant aimé le post
    const likedProfiles = await page.evaluate(() => {
      const profiles = [];
      const profileElements = document.querySelectorAll('.social-details-reactors-tab-body-list-item');

      profileElements.forEach((element) => {
        const name = element.querySelector('.artdeco-entity-lockup__title span').textContent.trim();
        const connectionDegree = element.querySelector('.artdeco-entity-lockup__badge .artdeco-entity-lockup__degree').textContent.trim();
        const profileLink = element.querySelector('a').href;
        const profileDescription = element.querySelector('.artdeco-entity-lockup__caption').textContent.trim();

        profiles.push({
          name,
          connectionDegree,
          profileLink,
          profileDescription,
        });
      });

      return profiles;
    });

    // Enregistrez les informations dans un fichier CSV
    const csvContent = 'Nom,Connection_Degree,Profil_Link,Profil_Description\n' +
      likedProfiles.map(profile => `${profile.name},${profile.connectionDegree},${profile.profileLink},"${profile.profileDescription}"`).join('\n');

    fs.writeFileSync('liked_profiles.csv', csvContent);

    // Affiche le message une fois que le CSV est créé
    console.log('Extraction des données terminée. Les informations ont été enregistrées dans liked_profiles.csv');
  } else {
    console.log('Le bouton "Voir les mentions J\'aime" n\'a pas été trouvé.');
  }

  // Fermeture du navigateur
  await browser.close();
})();
```

### Puppeteer version

20.8.1

### Node version

21.5.0

### Package manager

npm

### Package manager version

9.6.7

### Operating system

Linux

**Comment by Lightning00Blade** [comment]
@AnicetJonhia Could you verify that the `.social-details-reactors-tab-body-list-item` exists if you to the previous steps in headful (`await puppeteer.launch({ headless: false });`).
Sadly I am unable to reproduce due to not finding `const likeButtonExists = await page.$('button[data-control-name="likes_count"]');`. Do you need to be logged in to view?
