### ISSUE TITLE
[Bug]: Screen-cast Crashes from Time to Time

### ISSUE THREAD

**Issue by SudharakaP** [puppeteer/puppeteer#11767]
### Minimal, reproducible example

```TypeScript
try {
...
  // Start recording
  const recorder = await page.screencast({
    path: `recording-${process.env.PERSON}.webm`,
    speed: 0.5,
  });
...
} catch(error) {
    throw new Error(error)
} finally {
  await recorder.stop();
  await browser.close();
}
```

### Error string

```
ProtocolError: Page.screencastFrameAck timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
    at <instance_members_initializer> (file:///home/runner/work/AutoBooker/AutoBooker/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:82:14)
    at new Callback (file:///home/runner/work/AutoBooker/AutoBooker/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:86:16)
    at CallbackRegistry.create (file:///home/runner/work/AutoBooker/AutoBooker/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:19:[26](https://github.com/OpenArchitex/AutoBooker/actions/runs/7680258433/job/20932086669#step:5:27))
    at Connection._rawSend (file:///home/runner/work/AutoBooker/AutoBooker/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:77:26)
    at CdpCDPSession.send (file:///home/runner/work/AutoBooker/AutoBooker/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/CDPSession.js:63:33)
    at Object.next (file:///home/runner/work/AutoBooker/AutoBooker/node_modules/puppeteer-core/lib/esm/puppeteer/node/ScreenRecorder.js:141:[29](https://github.com/OpenArchitex/AutoBooker/actions/runs/7680258433/job/20932086669#step:5:30))
    at file:///home/runner/work/AutoBooker/AutoBooker/node_modules/puppeteer-core/lib/esm/third_party/rxjs/rxjs.js:3:22163
    at u._next (file:///home/runner/work/AutoBooker/AutoBooker/node_modules/puppeteer-core/lib/esm/third_party/rxjs/rxjs.js:3:6778)
    at e.next (file:///home/runner/work/AutoBooker/AutoBooker/node_modules/puppeteer-core/lib/esm/third_party/rxjs/rxjs.js:3:[31](https://github.com/OpenArchitex/AutoBooker/actions/runs/7680258433/job/20932086669#step:5:32)45)
    at u (file:///home/runner/work/AutoBooker/AutoBooker/node_modules/puppeteer-core/lib/esm/third_party/rxjs/rxjs.js:3:17473)
```
### Bug behavior

- [X] Flaky
- [ ] PDF

### Background

I don't know an exact way to reproduce this as this only happens once in a while totally at random. For a Puppeteer script, I use the screen-cast recorder to record the screen for debugging purposes. 

### Expectation

The screen-cast should not crash.

### Reality

Running this many times the screen-cast seems to give the above error. 

### Puppeteer version

21.9.0

### Node version

20.10.0

### Package manager

npm

### Package manager version

10.2.3

### Operating system

Linux

**Comment by SudharakaP** [comment]
Maybe this is not a bug as I can increase the `protocolTimeout` I guess and see how that helps. Closing for now. But if issue persists I'll re-open. 😄
