### ISSUE TITLE
[Bug]: Unsupported Frame Type

### ISSUE THREAD

**Issue by juliansyahrifqi** [puppeteer/puppeteer#11827]
### Minimal, reproducible example

```TypeScript
import puppeteer from "puppeteer"
(async () => {
  try {
    console.log("test")
    const browser = await puppeteer.launch({
      headless: false
    })
    

    const page = await browser.newPage()
  
    await page.goto("https://resilient-kelpie-af7af1.netlify.app/")

    const mainFrame = page
      .frames()
      .find((frame) => frame.name() === "mainframe");

    if (mainFrame) {
      const closeButtonSelector = ".close-popup";
      await mainFrame.waitForSelector(closeButtonSelector, { visible: true });
      await mainFrame.click(closeButtonSelector);
      console.log("Successfully clicked the close button in the main frame.");
    } else {
      console.log("Frame not found.");
    }
  }catch(error) {
    console.log(error)
  }
})();
```

### Error string

Error: Unsupported frame type

### Bug behavior

- [x] Flaky
- [ ] PDF

### Background

I want to click a button inside the `frameset`
I follow instruction from the documentation [https://pptr.dev/api/puppeteer.frame](https://pptr.dev/api/puppeteer.frame)

But after i tried that, it throw error `Error: Unsupported frame type`

Here's my HTML code
`index.html`
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <frameset rows="100%">
    <frame frameborder="0" />
    <frame src="test.html" frameborder="0" name="mainframe" />
  </frameset>
</html>
```

and here `test.html`
```
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <button id="button" class="close-popup">Click Me</button>
  </body>

  <script>
    const buttonClick = document
      .getElementById("button")
      .addEventListener("click", function (clicked) {
        alert("Test");
      });
  </script>
</html>
```

### Expectation

I'm expecting the button close popup is clicked and the popup is closed

### Reality

When it tried to click the close popup button, it throw error 
```
Error: Unsupported frame type
    at CdpElementHandle.#clickableBox (/home/rifqi/Projects/auto-puppeteer/node_modules/puppeteer-core/src/api/ElementHandle.ts:1088:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async CdpElementHandle.clickablePoint (/home/rifqi/Projects/auto-puppeteer/node_modules/puppeteer-core/src/api/ElementHandle.ts:707:17)
    at async CdpElementHandle.<anonymous> (/home/rifqi/Projects/auto-puppeteer/node_modules/puppeteer-core/src/api/ElementHandle.ts:164:16)
    at async CdpElementHandle.click (/home/rifqi/Projects/auto-puppeteer/node_modules/puppeteer-core/src/api/ElementHandle.ts:748:20)
    at async CdpElementHandle.<anonymous> (/home/rifqi/Projects/auto-puppeteer/node_modules/puppeteer-core/src/api/ElementHandle.ts:167:22)
    at async CdpFrame.click (/home/rifqi/Projects/auto-puppeteer/node_modules/puppeteer-core/src/api/Frame.ts:1053:5)
```

### Puppeteer version

21.9.0

### Node version

20.10.0

### Package manager

npm

### Package manager version

10.2.3

### Operating system

Linux

**Comment by OrKoN** [comment]
@jrandolf PTAL I think it's related to the clickableBox refactorings

**Comment by mgoku** [comment]
Got simmilar bug.

The latest version of Puppeteer that work fine is v.21.1.0

At v.21.1.1, Puppeteer failed to query the frame, but only produce timeout error.

At v.21.2.0, Puppeteer start to produce Unsupported frame type error.  Tried the latest v.2.2.0 and still got the same error.

**Comment by juliansyahrifqi** [comment]
Proved. I tried using v.21.1.0 and it works
