### ISSUE TITLE
[Bug]: Locator click outputs Timeout, when using a variable instead of a fixed

### ISSUE THREAD

**Issue by mikepziegler** [puppeteer/puppeteer#11893]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';

(async () => {

    const browser = await puppeteer.launch();
    const page = await browser.newPage();

    const searchURL = 'someUrlWith'
    const dynamicValue = 'searchingForValue'


    await page.goto(searchURL, { waitUntil: 'networkidle0' });

    await page.screenshot({ path: 'debug-screenshot-1.png', fullPage: true });

    await page.locator(' .searchedClass')
        .filter((div: { innerHTML: string | any[]; }) => div.innerHTML.includes(dynamicValue))
        .click();

    await page.waitForNavigation({waitUntil: "domcontentloaded"});

    await page.screenshot({ path: 'debug-screenshot-2.png', fullPage: true });
})
```

### Error string

TimeoutError: Timed out after waiting 30000ms

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I want to use filter in order to get a specific div with the class 'searchedClass', that has dynamicValue as a text within the html of the div. I also want to click on it in order to land to the next page

### Expectation

I would get to the next page and get the current url after the click

### Reality

I got this TimeoutError

```
TimeoutError: Timed out after waiting 30000ms
at path-to-project-root\node_modules\puppeteer-core\src\common\util.ts:311:17
at path-to-project-root\node_modules\puppeteer-core\lib\cjs\third_party\rxjs\rxjs.js:3:59978
at t.f._next (path-to-project-root\node_modules\puppeteer-core\lib\cjs\third_party\rxjs\rxjs.js:3:11821)
at t.next (path-to-project-root\node_modules\puppeteer-core\lib\cjs\third_party\rxjs\rxjs.js:3:6459)
at t.<anonymous> (path-to-project-root\node_modules\puppeteer-core\lib\cjs\third_party\rxjs\rxjs.js:3:71381)
at t._execute (path-to-project-root\node_modules\puppeteer-core\lib\cjs\third_party\rxjs\rxjs.js:3:28234)
at t.execute (path-to-project-root\node_modules\puppeteer-core\lib\cjs\third_party\rxjs\rxjs.js:3:28057)
at t.flush (path-to-project-root\node_modules\puppeteer-core\lib\cjs\third_party\rxjs\rxjs.js:3:32540)
at listOnTimeout (node:internal/timers:573:17)
at processTimers (node:internal/timers:514:7)
```

### Puppeteer version

22.0.0

### Node version

20.7.0

### Package manager

npm

### Package manager version

10.4.0

### Operating system

Windows

**Comment by OrKoN** [comment]
@mikepziegler the predicate is evaluated in the page context and dynamicValue is not defined there.

@jrandolf should we add support for arguments to the filter locator?

**Comment by OrKoN** [comment]
Yes, I believe you could use the text selector for this https://pptr.dev/guides/query-selectors#text-selectors--p-text (also, xpath, or using a custom query handler would work)

**Comment by OrKoN** [comment]
@mikepziegler could you clarify what you tried and why it didn't work? the text selector searches through all DOM elements and it should be possible to combine it with CSS selectors.

```
import puppeteer from 'puppeteer';

const browser = await puppeteer.launch();
const page = await browser.newPage();

await page.setContent(`
    <div>
      <button class="searchedClass" onclick="javascript: window.mylog.innerText = 'clicked';">some text</button>
      <div id="mylog">was not clicked</div>
    </div>`)

console.log(
  await page.evaluate(() => window.mylog.innerText)
)

await page.locator('.searchedClass::-p-text(some text)')
  .click();

console.log(
  await page.evaluate(() => window.mylog.innerText)
)
```

**Comment by alvinlys** [comment]
i got the same error stack too after upgrade 13.2.0 to 21.11.0. Any idea to know which line in my code caused the error?

**Comment by NarHakobyan** [comment]
Same for me

**Comment by ggorlen** [comment]
As an alternative to p-text, you can use string concatenation as shown [here](https://stackoverflow.com/a/79882931/6243352):

```js
const dynamicValue = 'searchingForValue';
await page.locator('.searchedClass')
  .filter(`div => div.innerHTML.includes(${JSON.stringify(dynamicValue)})`)
  .click();
```

This seems to be a common use case, so it'd be cool if `.filter()` took a second argument to pass into the browser context (I'd be into implementing this). In the meantime I've [added a documentation clarification proposal](https://github.com/puppeteer/puppeteer/pull/14671).
