### ISSUE TITLE
[Bug]: Reliable Browser Download Broken

### ISSUE THREAD

**Issue by worenga** [puppeteer/puppeteer#11925]
### Steps to reproduce

It seems the download path has changed? cc @mathiasbynens 

https://developer.chrome.com/blog/chrome-for-testing/

```
#Download the latest available Chrome for Testing binary corresponding to the Stable channel.
npx @puppeteer/browsers install chrome@stable
```

### Expected results

Browser downloads as expected.

### Actual results
```
Error: Download failed: server returned code 404. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6167.184/linux64/chrome-linux64.zip
    at /home/bewo/cf-repos/challenge-platform/node_modules/@puppeteer/browsers/lib/cjs/httpUtil.js:102:31
    at ClientRequest.requestCallback (/home/bewo/cf-repos/challenge-platform/node_modules/@puppeteer/browsers/lib/cjs/httpUtil.js:79:13)
```

**Comment by OrKoN** [comment]
The mitigation should be in place for now.

**Comment by msakrejda** [comment]
@OrKoN thanks, but can you clarify? I get the same error running `npx @puppeteer/browsers install chrome@stable`.

**Comment by renemadsen** [comment]
We have this error:
```
Error: Error: Download failed: server returned code 404. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6167.184/linux64/chromedriver-linux64.zip
    at file:///home/runner/work/eform-angular-frontend/eform-angular-frontend/eform-client/node_modules/@puppeteer/browsers/src/httpUtil.ts:98:23
    at ClientRequest.requestCallback (file:///home/runner/work/eform-angular-frontend/eform-angular-frontend/eform-client/node_modules/@puppeteer/browsers/src/httpUtil.ts:68:7)
    at Object.onceWrapper (node:events:632:26)
    at ClientRequest.emit (node:events:517:28)
    at ClientRequest.emit (node:domain:489:12)
    at HTTPParser.parserOnIncomingClient (node:_http_client:700:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:1[19](https://github.com/microting/eform-angular-frontend/actions/runs/7940143023/job/21682207080#step:16:20):17)
    at TLSSocket.socketOnData (node:_http_client:541:[22](https://github.com/microting/eform-angular-frontend/actions/runs/7940143023/job/21682207080#step:16:23))
    at TLSSocket.emit (node:events:517:28)
    at TLSSocket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:335:12)
    at readableAddChunk (node:internal/streams/readable:308:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:245:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:[23](https://github.com/microting/eform-angular-frontend/actions/runs/7940143023/job/21682207080#step:16:24))```

Why are the puppeteer trying to downloading from https://edgedl.me.gvt1.com when the url is https://storage.googleapis.com/chrome-for-testing-public/121.0.6167.184/linux64/chromedriver-linux64.zip according to https://googlechromelabs.github.io/chrome-for-testing/
