### ISSUE TITLE
[Bug]: Download failed: server returned code 500

### ISSUE THREAD

**Issue by tschaub** [puppeteer/puppeteer#11977]
### Minimal, reproducible example

```TypeScript
npx @puppeteer/browsers install chrome@stable
```

### Error string

Error: Download failed: server returned code 500

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I'm trying to install Chrome for Testing with Pupeteer.  The minimal, reproducible example comes from this page https://developer.chrome.com/blog/chrome-for-testing/#how_can_i_get_chrome_for_testing_binaries

I found #11969 and #11967.  I couldn't find a suggestion there that made `npx @puppeteer/browsers install chrome@stable` work.

### Expectation

I expected to be able to download Chrome for Testing with Pupeteer.

### Reality

```shell
Error: Download failed: server returned code 500. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/122.0.6261.57/mac-arm64/chrome-mac-arm64.zip
    at /path/to/node_modules/@puppeteer/browsers/lib/cjs/httpUtil.js:92:31
    at ClientRequest.requestCallback (/path/to/node_modules/@puppeteer/browsers/lib/cjs/httpUtil.js:69:13)
    at Object.onceWrapper (node:events:634:26)
    at ClientRequest.emit (node:events:519:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:693:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at TLSSocket.socketOnData (node:_http_client:535:22)
    at TLSSocket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
```

### Puppeteer version

@puppeteer/browsers@2.0.0

### Node version

21.5.0

### Package manager

npm

### Package manager version

10.2.4

### Operating system

macOS

**Comment by OrKoN** [comment]
Try using the latest @puppeteer/browsers: `npx @puppeteer/browsers@latest install chrome@stable`

**Comment by tschaub** [comment]
Thanks, @OrKoN.  I was able to get things working with the latest versions.

I just saw that I hadn't even included a title on the issue initially.  Apologies for the bad bug report.
