### ISSUE TITLE
[Bug]: Error: Could not find Chrome (ver. 124.0.6367.78).

### ISSUE THREAD

**Issue by bittorf** [puppeteer/puppeteer#12323]
### Minimal, reproducible example

```TypeScript
# i start with a fresh checkout on a recent debian trixie/sid
# and follow the howto in the examples folder:


git clone https://github.com/puppeteer/puppeteer.git
cd puppeteer 

# checkout from today:
bastian@ryzen:~/software/puppeteer$ git log -1
commit e35e783a7484ffd0d31ca23608e61a6cf54df8e2 (HEAD -> main, origin/main, origin/HEAD)
Author: Nikolay Vitkov <34244704+Lightning00Blade@users.noreply.github.com>
Date:   Wed Apr 24 15:13:09 2024 +0200

bastian@ryzen:~/software/puppeteer$ npm install

bastian@ryzen:~/software/puppeteer$ npm run build

bastian@ryzen:~/software/puppeteer$ npx puppeteer browsers install chrome
chrome@124.0.6367.60 /home/bastian/.cache/puppeteer/chrome/linux-124.0.6367.60/chrome-linux64/chrome

bastian@ryzen:~/software/puppeteer$ NODE_PATH=../ node examples/search.js

bastian@ryzen:~/software/puppeteer$ NODE_PATH=../ node examples/search.js
/home/bastian/software/puppeteer/packages/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:288
                    throw new Error(`Could not find Chrome (ver. ${this.puppeteer.browserRevision}). This can occur if either\n` +
                          ^

Error: Could not find Chrome (ver. 124.0.6367.78). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npx puppeteer browsers install chrome`) or
 2. your cache path is incorrectly configured (which is: /home/bastian/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
    at ChromeLauncher.resolveExecutablePath (/home/bastian/software/puppeteer/packages/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:288:27)
    at ChromeLauncher.executablePath (/home/bastian/software/puppeteer/packages/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:207:25)
    at ChromeLauncher.computeLaunchArguments (/home/bastian/software/puppeteer/packages/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:89:37)
    at async ChromeLauncher.launch (/home/bastian/software/puppeteer/packages/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:70:28)
    at async /home/bastian/software/puppeteer/examples/search.js:17:19

Node.js v18.19.1

bastian@ryzen:~/software/puppeteer$ command -v chrome
/home/bastian/.cache/puppeteer/chrome/linux-124.0.6367.60/chrome-linux64/chrome

bastian@ryzen:~/software/puppeteer$ ldd /home/bastian/.cache/puppeteer/chrome/linux-124.0.6367.60/chrome-linux64/chrome | grep not
<empty>

bastian@ryzen:~/software/puppeteer$ /home/bastian/.cache/puppeteer/chrome/linux-124.0.6367.60/chrome-linux64/chrome --version
Google Chrome for Testing 124.0.6367.60 

# all dependencies for debian listed at https://pptr.dev/troubleshooting
# Debian (e.g. Ubuntu) Dependencies
# are installed (already)
```
```


### Error string

Could not find Chrome (ver. 124.0.6367.78)

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

follow the mini howto in the examples folder

### Expectation

no error

### Reality

i seems that chrome is not found, but in fact installed.


### Puppeteer configuration file (if used)

```TypeScript
not used
```

### Puppeteer version

22.7.0

### Node version

18.19.1

### Package manager

npm

### Package manager version

10.5.0

### Operating system

Linux

**Comment by bittorf** [comment]
This needed step was missing:

```
npm install puppeteer-core
```

Maybe this should be mentioned in  
https://github.com/puppeteer/puppeteer/tree/main/examples
