### ISSUE TITLE
[Bug]: Install error

### ISSUE THREAD

**Issue by ne0c0de** [puppeteer/puppeteer#12362]
### Minimal, reproducible example

```TypeScript
npm i puppeteer
```

### Error string

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /mfa/mfa/node_modules/puppeteer/install.mjs

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Expectation

Install normally

### Reality

got this error:

```
> puppeteer@22.7.1 postinstall /mfa/mfa/node_modules/puppeteer
> node install.mjs

internal/modules/cjs/loader.js:819
  throw new ERR_REQUIRE_ESM(filename);
  ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /mfa/mfa/node_modules/puppeteer/install.mjs
    at Object.Module._extensions..mjs (internal/modules/cjs/loader.js:819:9)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11
npm WARN eslint-plugin-react@6.7.1 requires a peer of eslint@^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN twilio@3.59.0 requires a peer of @types/express@^4.17.7 but none is installed. You must install peer dependencies yourself.
npm WARN twilio@3.59.0 requires a peer of @types/qs@6.9.4 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.4.3 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.4.3 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN cosmiconfig@9.0.0 requires a peer of typescript@>=4.9.5 but none is installed. You must install peer dependencies yourself.
npm WARN ws@8.16.0 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@8.16.0 requires a peer of utf-8-validate@>=5.0.2 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@22.7.1 postinstall: `node install.mjs`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@22.7.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2024-04-29T10_25_07_778Z-debug.log
```

### Puppeteer version

22.7.1

### Node version

v12.4.0

### Package manager

npm

### Package manager version

6.9.0

### Operating system

Linux

**Comment by OrKoN** [comment]
Node 12 is not supported. Please try with Node v18 or newer.
