### ISSUE TITLE
Error: Passed function cannot be serialized! 

### ISSUE THREAD

**Issue by junehunter** [puppeteer/puppeteer#12392]
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.setContent(htmlString);
    await page.waitForSelector('body');
    const pdf = await page.pdf({
	    printBackground: true,
	    format: 'A4',
    });
// Error caused here
   const pageTitle = await page.evaluate(() => {
	return document.title;
   });
})();
```

### Error string

rror: Passed function cannot be serialized!     at stringifyFunction (C:\snapshot\xxx\node_modules\.pnpm\puppeteer-core@22.7.1\node_modules\puppeteer-core\lib\cjs\puppeteer\util\Function.js:47:19)[Bug]: 

### Bug behavior

- [ ] Flaky
- [X] PDF

### Expectation

pkg packaging runs new Function correctly

### Reality

Error: Passed function cannot be serialized!
    at stringifyFunction (C:\snapshot\xxx\node_modules\.pnpm\puppeteer-core@22.7.1\node_modules\puppeteer-core\lib\cjs\puppeteer\util\Function.js:47:19)
    at #evaluate (C:\snapshot\xxx\node_modules\.pnpm\puppeteer-core@22.7.1\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\ExecutionContext.js:196:73)
    at ExecutionContext.evaluate (C:\snapshot\xxx\node_modules\.pnpm\puppeteer-core@22.7.1\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\ExecutionContext.js:117:36)
    at IsolatedWorld.evaluate (C:\snapshot\xxx\node_modules\.pnpm\puppeteer-core@22.7.1\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\IsolatedWorld.js:124:30)
    at CdpFrame.evaluate (C:\snapshot\xxx\node_modules\.pnpm\puppeteer-core@22.7.1\node_modules\puppeteer-core\lib\cjs\puppeteer\api\Frame.js:342:43)
    at CdpFrame.<anonymous> (C:\snapshot\xxx\node_modules\.pnpm\puppeteer-core@22.7.1\node_modules\puppeteer-core\lib\cjs\puppeteer\util\decorators.js:98:27)
    at CdpPage.evaluate (C:\snapshot\xxx\node_modules\.pnpm\puppeteer-core@22.7.1\node_modules\puppeteer-core\lib\cjs\puppeteer\api\Page.js:823:43)

### Puppeteer version

22.7.1

### Node version

18.19.1

### Package manager

pnpm

### Package manager version

9.0.6

### Operating system

Windows

**Comment by OrKoN** [comment]
Not able to reproduce with

```
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.setContent('');
    await page.waitForSelector('body');
    const pdf = await page.pdf({
	    printBackground: true,
	    format: 'A4',
    });
// Error caused here
   const pageTitle = await page.evaluate(() => {
	return document.title;
   });

   await browser.close()
})();
```

Is it specific to pnpm and windows? do you see the issue with npm and other platforms?

**Comment by junehunter** [comment]
const pageTitle = await page.title(); That should do it

**Comment by OrKoN** [comment]
Not reproducible as well.

**Comment by OrKoN** [comment]
Not able to reproduce it on Windows as well. I suspect in your code you serialize some function that calls other functions or has local dependencies, please double check that.

**Comment by LWD8** [comment]
After packaging pkg, this problem will occur。puppeteer:23.3.0
