### ISSUE TITLE
Failed to launch the browser process! on WSL but working on local

### ISSUE THREAD

**Issue by jcbutil** [puppeteer/puppeteer#12409]
### Minimal, reproducible example

```TypeScript
I have been using aws-azure-login package which utilizes puppeteer for a while already but suddenly encountered this error yesterday after executing a stop command for AWSCLI. Cannot find any existing discussion that helped me with this issue. Hopefully someone could help me here. Thanks a lot!

$ ./aws-azure-acn-sso.sh --refresh
Logging in with profile 'default'...
Using AWS SAML endpoint https://signin.aws.amazon.com/saml
Error: Failed to launch the browser process!


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/johncarlobutil/.nvm/versions/node/v20.12.2/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241:20)
    at Interface.<anonymous> (/home/johncarlobutil/.nvm/versions/node/v20.12.2/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:231:68)
    at Interface.emit (node:events:530:35)
    at Interface.close (node:internal/readline/interface:527:10)
    at Socket.onend (node:internal/readline/interface:253:10)
    at Socket.emit (node:events:530:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
2024-05-07T22:25:36.245+08:00 aws-azure-acn-sso.sh      WARN    No AWS tokens expiration for 'default' profile
```

### Error string

Error: Failed to launch the browser process!

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Expectation

Browser popup to login credentials then successfully login.

### Reality

Browser popped up with login but error encounter on WSL.

### Puppeteer version

21.9.0

### Node version

20.12.2

### Package manager

npm

### Package manager version

10.5.0

### Operating system

Linux

**Comment by OrKoN** [comment]
Please try using the latest version and see potential solutions here https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-on-wsl-windows-subsystem-for-linux

**Comment by Linch1** [comment]
my issue is that chrome was already open, closing every chrome window and running my script made it work
