### ISSUE TITLE
[Bug]: Protocol error (Fetch.disable): 'Fetch.disable' wasn't found

### ISSUE THREAD

**Issue by Havunen** [puppeteer/puppeteer#12461]
### Minimal, reproducible example

Environment:
Chrome: Version 125.0.6422.41 (Official Build) Arch Linux (64-bit)
puppeteer: "22.9.0"
Linux linuxdesk 6.8.9-arch1-2 #1 SMP PREEMPT_DYNAMIC Tue, 07 May 2024 21:35:54 +0000 x86_64 GNU/Linux

I have a custom chrome extension which is loaded to puppeteer chromium using following script:

```js
  const browser = await puppeteer.launch({
    devtools: true,
    defaultViewport: {
      width: windowWidth,
      height: windowHeight,
    },
    headless: false,
    args: [
      `--window-size=${windowWidth},${windowHeight}`,
      `--disable-extensions-except=${buildFolder}`,
      `--load-extension=${buildFolder}`
    ]
  });
```

Whenever I try to debug the client side javascript in the started chromium instance it fails when I hover or try to console log the debug variables...

```
file:///home/sampo/git/mt-node-labeler/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:89
    #error = new ProtocolError();
             ^

ProtocolError: Protocol error (Fetch.disable): 'Fetch.disable' wasn't found
    at <instance_members_initializer> (file:///home/sampo/git/mt-node-labeler/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:89:14)
    at new Callback (file:///home/sampo/git/mt-node-labeler/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:93:16)
    at CallbackRegistry.create (file:///home/sampo/git/mt-node-labeler/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:19:26)
    at Connection._rawSend (file:///home/sampo/git/mt-node-labeler/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:85:26)
    at CdpCDPSession.send (file:///home/sampo/git/mt-node-labeler/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/CDPSession.js:63:33)
    at #applyProtocolRequestInterception (file:///home/sampo/git/mt-node-labeler/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/NetworkManager.js:194:24)
    at NetworkManager.addClient (file:///home/sampo/git/mt-node-labeler/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/NetworkManager.js:63:51)
    at FrameManager.initialize (file:///home/sampo/git/mt-node-labeler/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/FrameManager.js:164:38)
    at #initialize (file:///home/sampo/git/mt-node-labeler/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Page.js:311:36)
    at CdpPage._create (file:///home/sampo/git/mt-node-labeler/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Page.js:93:31)


```
```


### Error string

ProtocolError: Protocol error (Fetch.disable): 'Fetch.disable' wasn't found

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I have tried debugging the puppeteer as well but that didn't help

### Expectation

I expected the chromium debugger shows the variable contents as it should when its not started by puppeteer

### Reality

The puppeteer crashed and chromium instance was shutdown

### Puppeteer configuration file (if used)

_No response_

### Puppeteer version

22.9.0

### Node version

22.0.0

### Package manager

npm

### Package manager version

10.5.0

### Operating system

Linux

**Comment by OrKoN** [comment]
Could you please provide a test extensions? Extensions that we use for testing does not exhibit this behavior.

**Comment by Havunen** [comment]
I later changed the puppeteer options to include "pipe": true, and I am no longer able to reproduce this issue. I believe it was somehow related to some zombie chromium process, but not sure... I believe we can close this issue and re-open it it ever starts occurring again
