### ISSUE TITLE
SVG element causes DOM.getBoxModel error

### ISSUE THREAD

**Issue by Jamesernator** [puppeteer/puppeteer#1247]
I've been having issues trying to hover an svg element using `elementHandle.hover()`, now using `page.evaluate(element => element.getBoundingClientRect(), elementHandle)` works so I'm not sure why it throws an error for `.hover()`.

Here's a minimal example that causes it:

[puppeteer-svg-hover-test.zip](https://github.com/GoogleChrome/puppeteer/files/1436011/puppeteer-svg-hover-test.zip)

**Comment by Jamesernator** [comment]
I tried the latest version in the repository and now the error has changed to `Error: Node is not visible` which isn't the case either.

**Comment by aslushnikov** [comment]
Thanks @Jamesernator, this is a bug.

**Comment by lgrzybowski** [comment]
I have similar problem but related to click on button where page got reloaded because of some AJAX call. I think this can be related as both methods are calling  function `visibleCenter()` I get that stacktrace:
```
Error: Protocol error (DOM.getBoxModel): Could not compute box model. undefined
        at Session._onMessage (/Users/lukasz/Documents/work/github/brandwatch/analytics-ats/node_modules/puppeteer/lib/Connection.js:205:25)
        at Connection._onMessage (/Users/lukasz/Documents/work/github/brandwatch/analytics-ats/node_modules/puppeteer/lib/Connection.js:105:19)
        at emitOne (events.js:115:13)
        at WebSocket.emit (events.js:210:7)
        at Receiver._receiver.onmessage (/Users/lukasz/Documents/work/github/brandwatch/analytics-ats/node_modules/ws/lib/WebSocket.js:143:47)
        at Receiver.dataMessage (/Users/lukasz/Documents/work/github/brandwatch/analytics-ats/node_modules/ws/lib/Receiver.js:389:14)
        at Receiver.getData (/Users/lukasz/Documents/work/github/brandwatch/analytics-ats/node_modules/ws/lib/Receiver.js:330:12)
        at Receiver.startLoop (/Users/lukasz/Documents/work/github/brandwatch/analytics-ats/node_modules/ws/lib/Receiver.js:165:16)
        at Receiver.add (/Users/lukasz/Documents/work/github/brandwatch/analytics-ats/node_modules/ws/lib/Receiver.js:139:10)
        at Socket._ultron.on (/Users/lukasz/Documents/work/github/brandwatch/analytics-ats/node_modules/ws/lib/WebSocket.js:139:22)
        at emitOne (events.js:115:13)
```

**Comment by clujin** [comment]
I'm not sure if this helps but when I use the chrome-devtools protocol "DOM.getNodeForLocation" on a SVG element, it will return an error. So might this be related?

**Comment by tr1ckymast3r** [comment]
Same With Me , Try to click con <span /> but DOM.getBoxModel still return undefined, I just test on latest Chrome Browser and got the same result { width: auto, height: auto} . But it still rendered and visible

**Comment by aslushnikov** [comment]
Filed upstream [crbug.com/800636](https://bugs.chromium.org/p/chromium/issues/detail?id=800636)

**Comment by Muzietto** [comment]
I solved a problem that looks 99% the same as here in two ways:
- putting an `I.wait(3)` between the appearance of the item and the click on it
- using a `I.retry({ times:3, ...}).click(sel)` instead of an `I.click(...)`
