### ISSUE TITLE
[Bug]: Headless can't read LocalStorage written from Headful `DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.`

### ISSUE THREAD

**Issue by pirate** [puppeteer/puppeteer#12498]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';

(async () => {
	const browser = await puppeteer.launch({ignoreDefaultArgs: true});
	const page = await browser.newPage();
	await page.goto('http://www.sharonminsuk.com/code/storage-test.html', {waitUntil: 'networkidle2', timeout: 30_000})
	
    console.log(await page.evaluate(() => JSON.stringify(window.localStorage)))
    console.log(await page.evaluate(() => JSON.stringify(window.sessionStorage)))
})();
```

### Error string

DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.

### Bug Behavior

- [ ] Flaky
- [ ] PDF

### Background

I think it's the same underlying issue as https://github.com/puppeteer/puppeteer/issues/1268

I'm opening a new issue because there have been many puppeteer releases since then, but I'm still encountering it as of 2024-05 + I have more context provided in this issue. (also the older issue got closed by stalebot)

- [Allowing all 3rd party cookies](https://www.chromium.org/for-testers/bug-reporting-guidelines/uncaught-securityerror-failed-to-read-the-localstorage-property-from-window-access-is-denied-for-this-document/) in Chrome settings **does not** help
- adding `--no-sandbox` to launch args does not help
- adding `--disable-web-security` does not help
- adding `--disable-features=IsolateOrigins,site-per-process` does not help
- doing all of the above together does not work

*However, if you add `--headless=new`, then it works.*

### Expectation

Should be able to access `window.localStorage` and `window.sessionStorage`.

### Reality

An error is thrown on any access attempt from puppeteer.

```typescript
DOMException: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.
    at evaluate (evaluate at saveAuthStorage (file:///tmp/my-code.js:3405:37), <anonymous>:1:79)
    at #evaluate (/tmp/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:376:56)
    at async ExecutionContext.evaluate (/tmp/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:271:16)
    at async IsolatedWorld.evaluate (/tmp/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/IsolatedWorld.js:99:16)
    at async CdpFrame.evaluate (/tmp/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Frame.js:342:20)
    at async CdpPage.evaluate (/tmp/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Page.js:823:20)
    at async saveAuthStorage (file:///tmp/my-code.js:3405:26)
```

```typescript
DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at evaluate (evaluate at saveAuthStorage (file:///tmp/my-code.js:3405:37), <anonymous>:1:79)
    at #evaluate (/tmp/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:376:56)
    at async ExecutionContext.evaluate (/tmp/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:271:16)
    at async IsolatedWorld.evaluate (/tmp/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/IsolatedWorld.js:99:16)
    at async CdpFrame.evaluate (/tmp/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Frame.js:342:20)
    at async CdpPage.evaluate (/tmp/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Page.js:823:20)
    at async saveAuthStorage (file:///tmp/my-code.js:3405:26)
```

### Version Summary

- puppeteer: `22.10.0`
- chrome: `125.0.6422.78`
- node: `22.2.0`
- npm: `10.7.0`
- os: `macOS Sonoma 14.5 (arm64)`

### Puppeteer version
22.10.0

### Node version
22.2.0

### Package manager
npm

### Package manager version
10.7.0

### Operating system
macOS

**Comment by OrKoN** [comment]
I am not able to reproduce. 

```
import puppeteer from 'puppeteer';

(async () => {
	const browser = await puppeteer.launch({ignoreDefaultArgs: true});
	const page = await browser.newPage();
	await page.goto('http://www.sharonminsuk.com/code/storage-test.html', {waitUntil: 'networkidle2', timeout: 30_000})
	
    console.log(await page.evaluate(() => JSON.stringify(window.localStorage)))
    console.log(await page.evaluate(() => JSON.stringify(window.sessionStorage)))
})();
```


outputs

```
{}
{}
```

**Comment by pirate** [comment]
Woah that's strange, perhaps a puppeteer-extras extension I forgot to remove was toying with the chrome launch args in a way that broke it?

Do you have any idea off the top of your head if there are particular [chrome launch args](https://peter.sh/experiments/chromium-command-line-switches/) that would break access to localStorage from puppeteer? I'm curious which ones I should look out for in relation to this problem because I run dozens of different args setups on different projects.

**Comment by pirate** [comment]
It was the about:blank page! Good call. I had a race condition in another part of my app that was changing to `about:blank`. Thanks!
