### ISSUE TITLE
[Bug]: Puppeteer fails to launch browser process when running in a Nixpacks container

### ISSUE THREAD

**Issue by ngosky** [puppeteer/puppeteer#12583]
### Steps to reproduce

- Run a Node.js / Next.js project through [Coolify](https://coolify.io) using the Nixpacks Build Pack to containerize it. ([Coolify docs](https://coolify.io/docs/resources/applications/nextjs))
- Invoke `puppetter.launch({headless: "shell"})` on the server.

The code invoking puppeteer:
```
export async function htmlToPDF(html: string, options?: PDFOptions) {
  if (typeof html !== "string") throw new Error("Invalid HTML; expected string.");
  const browser = await puppeteer.launch({
    headless: "shell",
    args: ["--no-sandbox", "--disable-setuid-sandbox"],
  });
  const page = await browser.newPage();
  await page.setContent(html);
  const pdf = await page.pdf({
    printBackground: true,
    omitBackground: true,
    ...options,
  });
  await browser.close();
  return pdf.toString("base64");
}
```

### Expected results

- I expect puppeteer to launch the headless shell successfully.

### Actual results

Invoking the function on the server leads to the following error:
```
2024-06-13T20:28:53.089405665Z Error: Failed to launch the browser process!
2024-06-13T20:28:53.089450945Z /root/.cache/puppeteer/chrome-headless-shell/linux-125.0.6422.78/chrome-headless-shell-linux64/chrome-headless-shell: 1: �@�%: not found
2024-06-13T20:28:53.089458345Z /root/.cache/puppeteer/chrome-headless-shell/linux-125.0.6422.78/chrome-headless-shell-linux64/chrome-headless-shell: 2: @8@36@@@�����Є�Є�������: not found
2024-06-13T20:28:53.089465545Z /root/.cache/puppeteer/chrome-headless-shell/linux-125.0.6422.78/chrome-headless-shell-linux64/chrome-headless-shell: 1: K���: not found
2024-06-13T20:28:53.089470185Z /root/.cache/puppeteer/chrome-headless-shell/linux-125.0.6422.78/chrome-headless-shell-linux64/chrome-headless-shell: 1: ELF: not found
2024-06-13T20:28:53.089474505Z /root/.cache/puppeteer/chrome-headless-shell/linux-125.0.6422.78/chrome-headless-shell-linux64/chrome-headless-shell: 3: P: not found
2024-06-13T20:28:53.089478705Z /root/.cache/puppeteer/chrome-headless-shell/linux-125.0.6422.78/chrome-headless-shell-linux64/chrome-headless-shell: 4: P: not found
2024-06-13T20:28:53.089483465Z /root/.cache/puppeteer/chrome-headless-shell/linux-125.0.6422.78/chrome-headless-shell-linux64/chrome-headless-shell: 5: Syntax error: word unexpected (expecting ")")
2024-06-13T20:28:53.089487945Z 
2024-06-13T20:28:53.089491385Z 
2024-06-13T20:28:53.089494865Z TROUBLESHOOTING: https://pptr.dev/troubleshooting
2024-06-13T20:28:53.089498545Z 
2024-06-13T20:28:53.089502185Z     at Interface.onClose (/app/node_modules/@puppeteer/browsers/lib/cjs/launch.js:310:24)
2024-06-13T20:28:53.089506065Z     at Interface.emit (node:events:529:35)
2024-06-13T20:28:53.089510985Z     at Interface.close (node:internal/readline/interface:534:10)
2024-06-13T20:28:53.089514945Z     at Socket.onend (node:internal/readline/interface:260:10)
2024-06-13T20:28:53.089518665Z     at Socket.emit (node:events:529:35)
2024-06-13T20:28:53.089522545Z     at endReadableNT (node:internal/streams/readable:1400:12)
2024-06-13T20:28:53.089526585Z     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

Anyone have any ideas as to what could be contributing to the error?

Notes:
- Everything works fine locally on my Windows 10 PC.
- The Coolify instance runs on a `Linux 5.15.0-112-generic aarch64` server with `Ubuntu 22.04.4 LTS`, if that is of any importance.
- The build image Nixpacks chose to use is [ghcr.io/railwayapp/nixpacks:ubuntu-1716249803]('ghcr.io/railwayapp/nixpacks:ubuntu-1716249803').

**Comment by OrKoN** [comment]
aarch64 linux architecture is not supported since Chrome does not officially support this cpu architecture for Linux. See https://pptr.dev/guides/system-requirements and https://github.com/puppeteer/puppeteer/issues/7740

**Comment by OrKoN** [comment]
I think you should generally get an error when downloading but looks like the x64 binary is downloaded in this case.

**Comment by OrKoN** [comment]
So the issue is that we only check if the platform is Linux and download x64 binaries even if they are not compatible.

**Comment by ngosky** [comment]
Thanks for the quick responses.

As a workaround, I tried to switch browsers by using puppeteer with Firefox, but it seems to elicit the same errors, even though Firefox officially supports aarch64 linux. 

> So the issue is that we only check if the platform is Linux and download x64 binaries even if they are not compatible.

I'm guessing the same might be true for Firefox too:
```
2024-06-14T16:25:45.142181673Z Chrome DevTools Protocol (CDP) support for Firefox is deprecated in Puppeteer and it will be eventually removed. Use WebDriver BiDi instead (see https://pptr.dev/webdriver-bidi#get-started).
2024-06-14T16:25:45.162983670Z Error: Failed to launch the browser process!
2024-06-14T16:25:45.163025070Z /root/.cache/puppeteer/firefox/linux-nightly_129.0a1/firefox/firefox: 1: ELF: not found
2024-06-14T16:25:45.163031390Z /root/.cache/puppeteer/firefox/linux-nightly_129.0a1/firefox/firefox: 2: Syntax error: "(" unexpected
2024-06-14T16:25:45.163036150Z 
2024-06-14T16:25:45.163039790Z 
2024-06-14T16:25:45.163043150Z TROUBLESHOOTING: https://pptr.dev/troubleshooting
2024-06-14T16:25:45.163046870Z 
2024-06-14T16:25:45.163050270Z     at Interface.onClose (/app/node_modules/@puppeteer/browsers/lib/cjs/launch.js:310:24)
2024-06-14T16:25:45.163054150Z     at Interface.emit (node:events:529:35)
2024-06-14T16:25:45.163058030Z     at Interface.close (node:internal/readline/interface:534:10)
2024-06-14T16:25:45.163061790Z     at Socket.onend (node:internal/readline/interface:260:10)
2024-06-14T16:25:45.163065550Z     at Socket.emit (node:events:529:35)
2024-06-14T16:25:45.163069110Z     at endReadableNT (node:internal/streams/readable:1400:12)
2024-06-14T16:25:45.163072870Z     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

While the issue remains, I'll try installing Firefox seperately and pointing puppeteer to the corresponding executable to see if that would work.

**Comment by ngosky** [comment]
Ended up fixing my issue by installing an arm64 supported version of Chromium seperately and pointing puppeteer to its executable.

As for the above, I would highly urge you to account for arch Linux (at least [detecting](https://github.com/puppeteer/puppeteer/blob/38743007159beedcad8571c08c3320235eb93f76/packages/browsers/src/detectPlatform.ts#L14) it, and giving suitable feedback to the user). In the case of Firefox, the installation should definitely take into account the architecture of the OS (especially since Firefox has explicit support for arm64 Linux).

**Comment by OrKoN** [comment]
I filed https://github.com/puppeteer/puppeteer/issues/12595 but it looks like arm64 linux is only supported for nightly builds.

**Comment by zaini** [comment]
@ngosky can you share more info on how you resolved this issue?

Specifically I am running `"puppeteer": "^23.6.1"` in my Nextjs project and getting these errors:

```
/root/.cache/puppeteer/chrome/linux-130.0.6723.69/chrome-linux64/chrome: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.36' not found (required by /nix/store/g5dj80arfsy8lvkda22dgkcqmyqa126w-util-linux-minimal-2.39.4-lib/lib/libmount.so.1)
/root/.cache/puppeteer/chrome/linux-130.0.6723.69/chrome-linux64/chrome: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /nix/store/g5dj80arfsy8lvkda22dgkcqmyqa126w-util-linux-minimal-2.39.4-lib/lib/libmount.so.1)
/root/.cache/puppeteer/chrome/linux-130.0.6723.69/chrome-linux64/chrome: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /nix/store/g5dj80arfsy8lvkda22dgkcqmyqa126w-util-linux-minimal-2.39.4-lib/lib/libblkid.so.1)
/root/.cache/puppeteer/chrome/linux-130.0.6723.69/chrome-linux64/chrome: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /nix/store/g5dj80arfsy8lvkda22dgkcqmyqa126w-util-linux-minimal-2.39.4-lib/lib/libuuid.so.1)


TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at Interface.onClose (/app/node_modules/@puppeteer/browsers/lib/cjs/launch.js:312:24)
    at Interface.emit (node:events:529:35)
    at Interface.close (node:internal/readline/interface:534:10)
    at Socket.onend (node:internal/readline/interface:260:10)
    at Socket.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1400:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  digest: '1312161570'
}
```

**Comment by hugostanley** [comment]
Hi @zaini were you able to fix your issue? Im encountering the same thing.

**Comment by b33lz3bubTH** [comment]
```shell.nix
{ pkgs ? import <nixpkgs> {} }:

pkgs.mkShell {
  buildInputs = with pkgs; [
    nodejs_20
    yarn
    nodePackages.npm
    openssl
    pkg-config
    libuuid
    prisma-engines
    chromium
  ];

  # Set environment variables for Prisma
  PRISMA_SCHEMA_ENGINE_BINARY = "${pkgs.prisma-engines}/bin/schema-engine";
  PRISMA_QUERY_ENGINE_BINARY = "${pkgs.prisma-engines}/bin/query-engine";
  PRISMA_QUERY_ENGINE_LIBRARY = "${pkgs.prisma-engines}/lib/libquery_engine.so.node";
  PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING = "1";
  PUPPETEER_SKIP_DOWNLOAD = "1";

  PUPPETEER_EXECUTABLE_PATH = "${pkgs.chromium}/bin/chromium" ;
  # Ensure OpenSSL and other libraries are available
  shellHook = ''
    echo "Node.js and Prisma development environment"
    echo "Node.js version: $(node --version)"
    echo "npm version: $(npm --version)"
    echo "yarn version: $(yarn --version)"
    echo "OpenSSL version: $(openssl version)"
    echo "Prisma engines: ${pkgs.prisma-engines}/bin"
    export PATH=$PWD/node_modules/.bin:$PATH
    export LD_LIBRARY_PATH=${pkgs.lib.makeLibraryPath [
      pkgs.openssl
      pkgs.libuuid
      pkgs.zlib
    ]}:$LD_LIBRARY_PATH

    export PUPPETEER_EXECUTABLE_PATH=${pkgs.chromium}/bin/chromium

    # Create a directory for Prisma engines if needed
    mkdir -p .prisma/engines
    # Symlink Prisma engines to avoid download
    ln -sf ${pkgs.prisma-engines}/bin/query-engine .prisma/engines/query-engine
    ln -sf ${pkgs.prisma-engines}/bin/schema-engine .prisma/engines/schema-engine
    ln -sf ${pkgs.prisma-engines}/lib/libquery_engine.so.node .prisma/engines/libquery_engine.so.node
  '';
}
```

### This is working fine for me. i needed prisma so it has that as well. remove it if you dont want.

**Comment by Lightning00Blade** [comment]
Given the issue is related to ARM64 should be resolved once the linked issue is closed. If not open a new issue.
