### ISSUE TITLE
Page crashed after waiting for selector

### ISSUE THREAD

**Issue by ivanvandessel-wk** [puppeteer/puppeteer#12667]
waiting for a css selector like one here:  "[data-test-id='shell-document-tab-nav-item'][aria-selected='true']" 

After upgrading to 22.11.0 from 22.10 of puppeteer
I receive this failure:

Puppeteer page error Error: Page crashed!
    at #onTargetCrashed (/usr/local/lib/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Page.js:399:50)
    at /usr/local/lib/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/third_party/mitt/mitt.js:62:7
    at Array.map (<anonymous>)
    at Object.emit (/usr/local/lib/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/third_party/mitt/mitt.js:61:20)
    at CdpCDPSession.emit (/usr/local/lib/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:83:23)
    at CdpCDPSession._onMessage (/usr/local/lib/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/CDPSession.js:82:18)
    at Connection.onMessage (/usr/local/lib/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:142:25)
    at WebSocket.<anonymous> (/usr/local/lib/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/node/NodeWebSocketTransport.js:44:32)
    at callListener (/usr/local/lib/node_modules/puppeteer/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onMessage (/usr/local/lib/node_modules/puppeteer/node_modules/ws/lib/event-target.js:209:9)

_Originally posted by @ivanvandessel-wk in https://github.com/puppeteer/puppeteer/issues/7486#issuecomment-2192223083_

**Comment by OrKoN** [comment]
Please fill out the complete bug report form to provide the information necessary to reproduce the issue https://github.com/puppeteer/puppeteer/issues/new?assignees=&labels=bug&projects=&template=bug.yml&title=%5BBug%5D%3A+
