### ISSUE TITLE
Headless can't read LocalStorage written from Headful

### ISSUE THREAD

**Issue by aslushnikov** [puppeteer/puppeteer#1268]
1. Open headful chrome with a custom userDataDir
2. Write some localStorage:
```js
localStorage.key = 'hello';
```
3. Close headful chrome
4. run headless with the same userDataDir
5. try reading localStorage in headless chrome:
```js
await page.evaluate(() => localStorage.key);
```
Expected: "hello" to be returned in (5)
Actual: empty object is returned

This is similar to #921 and might be due to missing encryption for local storage in headless chrome.

**Comment by vsemozhetbyt** [comment]
Did you check IndexedDB?

**Comment by aslushnikov** [comment]
@vsemozhetbyt no, I didn't check anything but localStorage.

**Comment by vsemozhetbyt** [comment]
@aslushnikov `indexedDB` check: https://github.com/GoogleChrome/puppeteer/issues/1270
You can check a vice versa variant here too.

**Comment by HansLanger** [comment]
I have seem projects having the same issue.
Basically it does not pass the line "var page = await browser.newPage();"  when puppeteer is launched with headless option and it is using a custom userDataDir.
there is any intention to fix this?

**Comment by LucasPonzo** [comment]
Hey, is this feature developed? Or if there isn't a plan to develop, can you write some ideas on how to inject session local store and cookies? Another option is to persist the headless session in userDataDir and puppeteer load it in headless itself... I think it makes even more sense than to restore a headfull profile inside headless... It would be headless to headless userDataDir data persistence/loading.... 

Thanks

**Comment by riyadshauk** [comment]
I'm still running into an error where I launch chrome in debug mode with the userDataDir specified, I log in, etc, and connect to it via Pupeteer with the userDataDir specified. My script works. When I try using Puppeteer with headless and the userDataDir, it treats it like a new browser, and requires me to log in to the website I needed to automate on.

to run Chrome, I use this
```
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222 --no-first-run --no-default-browser-check --user-data-dir=~/chrome-remote_data_dir
```

To run headful, I reference the generated WS URL in my Puppeteer script.

**Comment by pirate** [comment]
This issue should be re-opened, I'm still unable to access `sessionStorage` in headful Chrome from puppeteer `v22.10.0` w/ Chrome `v125.0.6422.78`:

```logs
DOMException: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.
    at evaluate (evaluate at saveAuthStorage (file:///tmp/my-code.js:3405:37), <anonymous>:1:79)
    at #evaluate (/tmp/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:376:56)
    at async ExecutionContext.evaluate (/tmp/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:271:16)
    at async IsolatedWorld.evaluate (/tmp/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/IsolatedWorld.js:99:16)
    at async CdpFrame.evaluate (/tmp/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Frame.js:342:20)
    at async CdpPage.evaluate (/tmp/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Page.js:823:20)
    at async saveAuthStorage (file:///tmp/my-code.js:3405:26)
```

```logs
DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at evaluate (evaluate at saveAuthStorage (file:///tmp/my-code.js:3405:37), <anonymous>:1:79)
    at #evaluate (/tmp/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:376:56)
    at async ExecutionContext.evaluate (/tmp/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:271:16)
    at async IsolatedWorld.evaluate (/tmp/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/IsolatedWorld.js:99:16)
    at async CdpFrame.evaluate (/tmp/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Frame.js:342:20)
    at async CdpPage.evaluate (/tmp/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Page.js:823:20)
    at async saveAuthStorage (file:///tmp/my-code.js:3405:26)
```
