### ISSUE TITLE
'Page.setLifecycleEventsEnabled' wasn't found undefined

### ISSUE THREAD

**Issue by dustyhorizon** [puppeteer/puppeteer#1271]
Puppeteer version: master
Platform / OS version: ubuntu:17.04 (using google-chrome-unstable in a container)

Not sure what happened but kept getting the following

```
Error: Protocol error (Page.setLifecycleEventsEnabled): 'Page.setLifecycleEventsEnabled' wasn't found undefined
sierra_1             |     at Session._onMessage (/opt/app/node_modules/puppeteer/lib/Connection.js:194:25)
sierra_1             |     at Connection._onMessage (/opt/app/node_modules/puppeteer/lib/Connection.js:98:19)
sierra_1             |     at emitOne (events.js:115:13)
sierra_1             |     at WebSocket.emit (events.js:210:7)
sierra_1             |     at Receiver._receiver.onmessage (/opt/app/node_modules/ws/lib/WebSocket.js:143:47)
sierra_1             |     at Receiver.dataMessage (/opt/app/node_modules/ws/lib/Receiver.js:389:14)
sierra_1             |     at Receiver.getData (/opt/app/node_modules/ws/lib/Receiver.js:330:12)
sierra_1             |     at Receiver.startLoop (/opt/app/node_modules/ws/lib/Receiver.js:165:16)
sierra_1             |     at Receiver.add (/opt/app/node_modules/ws/lib/Receiver.js:139:10)
sierra_1             |     at Socket._ultron.on (/opt/app/node_modules/ws/lib/WebSocket.js:139:22)
sierra_1             |     at emitOne (events.js:115:13)
sierra_1             |     at Socket.emit (events.js:210:7)
sierra_1             |     at addChunk (_stream_readable.js:264:12)
sierra_1             |     at readableAddChunk (_stream_readable.js:251:11)
sierra_1             |     at Socket.Readable.push (_stream_readable.js:209:10)
sierra_1             |     at TCP.onread (net.js:587:20)
```

EDIT: tested and found commit ac55e69676dde4908e81c45f75cc84e0d3e850e9 was causing this. commit fede2643ac997be9899e67adcbd5f33170736647 had no issues.

**Comment by aslushnikov** [comment]
@dustyhorizon you somehow use new puppeteer with and old chrome that doesn't support `Page.setLifecycleEventsEnabled` method.

Make sure you run `npm install` in pptr folder to download a new chromium.
