### ISSUE TITLE
response.buffer() rejects for selected resources

### ISSUE THREAD

**Issue by ithinkihaveacat** [puppeteer/puppeteer#1274]
The promise returned by [response.buffer()](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#responsebuffer)  consistently rejects for certain resources. This makes it impossible to collect information about certain resources that can only be obtained from the buffer, such as the length of the resource.

The problem seems to particularly affect video/media files. (Perhaps because partial requests are involved?)

To reproduce:

```js
'use strict';

const URL = 'https://www.quirksmode.org/html5/tests/video.html';

const puppeteer = require('puppeteer');

(async() => {

const browser = await puppeteer.launch();
const page = await browser.newPage();
await page.on('response', response => {
  const url = response.url;
  if (!url.startsWith('data:') && response.ok) {
    response.buffer().then(
        b => {
          console.log(`${response.status} ${url} ${b.length} bytes`);
        },
        e => {
          console.error(`${response.status} ${url} failed: ${e}`);
        }
    );
  }
});

await page.goto(URL, { waitUntil: 'networkidle0' });

})();
```

Actual:

```
200 https://www.quirksmode.org/html5/tests/video.html 2905 bytes
200 https://www.quirksmode.org/quirksmode.css 16360 bytes
200 https://www.quirksmode.org/quirksmode.js 22540 bytes
200 https://www.quirksmode.org/pix/footer_bg.gif 312 bytes
206 https://www.quirksmode.org/html5/videos/big_buck_bunny.webm failed: Error: Protocol error (Network.getResponseBody): No data found for resource with given identifier undefined
206 https://www.quirksmode.org/html5/videos/big_buck_bunny.ogv failed: Error: Protocol error (Network.getResponseBody): No data found for resource with given identifier undefined
206 https://www.quirksmode.org/html5/videos/big_buck_bunny.webm 24804 bytes
206 https://www.quirksmode.org/html5/videos/big_buck_bunny.ogv 66642 bytes
```

Expected:

As above, but without the "Error: Protocol error (Network.getResponseBody): No data found for resource with given identifier undefined" messages.

The "broken" resources seem to be associated with 206 responses.

**Comment by ithinkihaveacat** [comment]
A workaround for finding the total amount of data downloaded is to listen to devtools' `Network.dataReceived` event via the page's private `_client` property, and track each chunk, something like:


```js
const resources = {};

page._client.on('Network.dataReceived', event => {
  const request = page._networkManager._requestIdToRequest.get(event.requestId);
  if (!request.url.startsWith('data:')) {
    // encodedDataLength is supposed to be the amount of data received
    // over the wire, but it's often 0, so just track uncompressed size for now...
    // https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-dataReceived
    // const length = event.encodedDataLength > 0 ? event.encodedDataLength : event.dataLength;
    const length = event.dataLength;
    if (request.url in resources)
      resources[request.url] += length;
    else
      resources[request.url] = length;
  }
});

const total = Object.values(resources).reduce((a, n) => a + n, 0);

console.log(resources);
console.log(`TOTAL = ${total} (uncompressed)`);
```

**Comment by ithinkihaveacat** [comment]
Update reproduce code for Puppeteer 1:

```js
'use strict';

const URL = 'https://www.quirksmode.org/html5/tests/video.html';

const puppeteer = require('puppeteer');

(async() => {

const browser = await puppeteer.launch();
const page = await browser.newPage();
await page.on('response', response => {
  const url = response.url();
  if (!url.startsWith('data:') && response.ok) {
    response.buffer().then(
        b => {
          console.log(`${response.status()} ${url} ${b.length} bytes`);
        },
        e => {
          console.error(`${response.status()} ${url} failed: ${e}`);
        }
    );
  }
});

await page.goto(URL);

})();
```

**Comment by lx1412** [comment]
Then how to get the buffer of the 206 response?

**Comment by codesorter2015** [comment]
I'm having the same issue, any update for this issue?

**Comment by nicoandmee** [comment]
Also experiencing this issue when intercepting a response whose `.buffer()` resolves to a pdf file.

**Comment by anaulin** [comment]
We're seeing this issue as well, and also with a video resource (`.mp4` in our case), but it happens even if we filter out `206` status codes. Here is a reproduce case that fails about 2/3s of the time on my machine:
```javascript
const puppeteer = require('puppeteer');

const URL = 'https://www.nash.io/company/careers';


(async() => {

const browser = await puppeteer.launch();
const page = await browser.newPage();
page.on('response', async (response) => {
  if ([200, 201, 304].includes(response.status())) {
    await response.buffer()
  }
});

console.log('waiting for url to load')
await page.goto(URL, { waitUntil: 'networkidle0' })

await browser.close()

})();
```

The specific exception I get is:
```
(node:54729) UnhandledPromiseRejectionWarning: Error: Protocol error (Network.getResponseBody): No data found for resource with given identifier
    at Promise (/Users/anaulin/src/github.com/percy/percy-agent/node_modules/puppeteer/lib/Connection.js:186:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/Users/anaulin/src/github.com/percy/percy-agent/node_modules/puppeteer/lib/Connection.js:185:12)
    at _contentPromise._bodyLoadedPromise.then (/Users/anaulin/src/github.com/percy/percy-agent/node_modules/puppeteer/lib/NetworkManager.js:591:45)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:54729) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:54729) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I'm using Puppeteer v 1.11.0 on Mac OS X.

**Comment by aslushnikov** [comment]
@anaulin the sporadic nature kinda suggests that you're hitting limits on resource buffering. As a workaround, can you please try:

```js
await page._client.send('Network.enable', {
  maxResourceBufferSize: 1024 * 1024 * 150, // 150Mb
  maxTotalBufferSize: 1024 * 1024 * 300, // 300mb
});
```

**Comment by anaulin** [comment]
@aslushnikov that doesn't really seem to fix the problem (maybe it now succeeds a little more frequently? but still seeing about 50% failures).

For the record, I tried with the following script:
```javascript
const puppeteer = require('puppeteer');

const URL = 'https://www.nash.io/company/careers';


(async() => {

const browser = await puppeteer.launch();
const page = await browser.newPage();

await page._client.send('Network.enable', {
      maxResourceBufferSize: 1024 * 1024 * 150, // 150Mb
      maxTotalBufferSize: 1024 * 1024 * 300, // 300mb
})

page.on('response', async (response) => {
  if ([200, 201, 304].includes(response.status())) {
    await response.buffer()
  }
});

console.log('waiting for url to load')
await page.goto(URL, { waitUntil: 'networkidle0' })

await browser.close()

})();
```

I ran it 10 times, 4 times it failed with `Protocol error (Network.getResponseBody): No data found for resource with given identifier`.

**Comment by aslushnikov** [comment]
@anaulin interesting, it worked 10 out of 10 for me.

Can you please log for which URLs it fails for you?

```js
const puppeteer = require('puppeteer');
const URL = 'https://www.nash.io/company/careers';

(async() => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();

  page.on('response', async (response) => {
    if (![200, 201, 304].includes(response.status()))
      return;
    try {
      await response.buffer()
    } catch (e) {
      console.log(`Failed for ${response.request().method()} ${response.request().url()}`);
    }
  });
  console.log('waiting for url to load')
  await page.goto(URL, { waitUntil: 'networkidle0' })
  await browser.close()
})();
```

**Comment by anaulin** [comment]
@aslushnikov it's always this mp4 URL: https://www.nash.io/static/careers-fe92d8a0bcbd10b63666cd11940a0f08.mp4

Script with buffer size + logging:
```javascript
const puppeteer = require('puppeteer');

const URL = 'https://www.nash.io/company/careers';


(async() => {

const browser = await puppeteer.launch();
const page = await browser.newPage();

await page._client.send('Network.enable', {
      maxResourceBufferSize: 1024 * 1024 * 150, // 150Mb
      maxTotalBufferSize: 1024 * 1024 * 300, // 300mb
})

page.on('response', async (response) => {
  if ([200, 201, 304].includes(response.status())) {
    await response.buffer().catch((e) => console.log(`${response.request().method()} ${response.url()} : ${e}`))
  }
});

console.log('waiting for url to load')
await page.goto(URL, { waitUntil: 'networkidle0' })

await browser.close()

})();
```

Output from running 10 times:
```
$ for n in {1..10}; do node repro.js; done
waiting for url to load
GET https://www.nash.io/static/careers-fe92d8a0bcbd10b63666cd11940a0f08.mp4 : Error: Protocol error (Network.getResponseBody): No data found for resource with given identifier
waiting for url to load
GET https://www.nash.io/static/careers-fe92d8a0bcbd10b63666cd11940a0f08.mp4 : Error: Protocol error (Network.getResponseBody): No data found for resource with given identifier
waiting for url to load
waiting for url to load
waiting for url to load
GET https://www.nash.io/static/careers-fe92d8a0bcbd10b63666cd11940a0f08.mp4 : Error: Protocol error (Network.getResponseBody): No data found for resource with given identifier
waiting for url to load
waiting for url to load
waiting for url to load
GET https://www.nash.io/static/careers-fe92d8a0bcbd10b63666cd11940a0f08.mp4 : Error: Protocol error (Network.getResponseBody): No data found for resource with given identifier
waiting for url to load
waiting for url to load
```

**Comment by aslushnikov** [comment]
@anaulin can you please try pptr v1.13.0?

I have no luck reproducing your script, but the [original bugreport](https://github.com/GoogleChrome/puppeteer/issues/1274#issuecomment-357672827) reproduces well for me. However, it relates to HTTP 206 which is clearly not your case.

**Comment by anaulin** [comment]
@aslushnikov i'm afraid see the same issue with pptr 1.13.0 and HeadlessChrome/74.0.3723.0

More specs of the system where I'm reproducing this:
```bash
$ node --version
v11.6.0
$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.14.3
BuildVersion:	18D109
```

Script with version and various logging bits:
```javascript
const puppeteer = require('puppeteer');

const URL = 'https://www.nash.io/company/careers';

(async() => {

console.log(`Puppeteer version: ${require('./node_modules/puppeteer/package.json').version}`)

const browser = await puppeteer.launch();

console.log(`Browser version: ${await browser.version()}`)

const page = await browser.newPage();

await page._client.send('Network.enable', {
      maxResourceBufferSize: 1024 * 1024 * 150, // 150Mb
      maxTotalBufferSize: 1024 * 1024 * 300, // 300mb
})

page.on('response', async (response) => {
  if ([200, 201, 304].includes(response.status())) {
    await response.buffer().catch((e) => console.log(`${response.request().method()} ${response.url()} : ${e}`))
  }
});

console.log('waiting for url to load')
await page.goto(URL, { waitUntil: 'networkidle0' })

await browser.close()

})();
```

Output from 10 runs:
```
$ for n in {1..10}; do node repro.js; done
Puppeteer version: 1.13.0
Browser version: HeadlessChrome/74.0.3723.0
waiting for url to load
Puppeteer version: 1.13.0
Browser version: HeadlessChrome/74.0.3723.0
waiting for url to load
Puppeteer version: 1.13.0
Browser version: HeadlessChrome/74.0.3723.0
waiting for url to load
Puppeteer version: 1.13.0
Browser version: HeadlessChrome/74.0.3723.0
waiting for url to load
GET https://www.nash.io/static/careers-fe92d8a0bcbd10b63666cd11940a0f08.mp4 : Error: Protocol error (Network.getResponseBody): No data found for resource with given identifier
Puppeteer version: 1.13.0
Browser version: HeadlessChrome/74.0.3723.0
waiting for url to load
GET https://www.nash.io/static/careers-fe92d8a0bcbd10b63666cd11940a0f08.mp4 : Error: Protocol error (Network.getResponseBody): No data found for resource with given identifier
Puppeteer version: 1.13.0
Browser version: HeadlessChrome/74.0.3723.0
waiting for url to load
Puppeteer version: 1.13.0
Browser version: HeadlessChrome/74.0.3723.0
waiting for url to load
GET https://www.nash.io/static/careers-fe92d8a0bcbd10b63666cd11940a0f08.mp4 : Error: Protocol error (Network.getResponseBody): No data found for resource with given identifier
Puppeteer version: 1.13.0
Browser version: HeadlessChrome/74.0.3723.0
waiting for url to load
Puppeteer version: 1.13.0
Browser version: HeadlessChrome/74.0.3723.0
waiting for url to load
Puppeteer version: 1.13.0
Browser version: HeadlessChrome/74.0.3723.0
waiting for url to load
```

**Comment by aslushnikov** [comment]
@anaulin ok I was able to repro this once in a while.

Looking into the page, it turns out there's some piece of JavaScript code that (allegedly) re-inserts the `<video>` tag. As a result, requests related to the video tag might be aborted before completion, and their body cannot be fetched.

The script that makes it work reliably for me fetches body for only successfully finished requests.
Another way to make it work for this particular website is to disable JavaScript.

Can you please check if this works for you?

```js
const puppeteer = require('puppeteer');

const URL = 'https://www.nash.io/company/careers';
const VIDEO_URL =  'https://www.nash.io/static/careers-fe92d8a0bcbd10b63666cd11940a0f08.mp4';

(async() => {
  for (let i = 0; i < 10; ++i) {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();

    // This makes it work 100%.
    //await page.setJavaScriptEnabled(false);

    page.on('requestfinished', async (request) => {
      if (request.url() !== VIDEO_URL)
        return;
      try {
        console.log('- fetching body of .mp4 file');
        await request.response().buffer();
        console.log(`-- .mp4: OK`);
      } catch (e) {
        console.log(`-- .mp4: FAIL - ${e.message}`);
      }
    });

    page.on('requestfailed', async (request) => {
      if (request.url() !== VIDEO_URL)
        return;
      console.log('- video loading failed!');
    });

    console.log(`=== ITERATION ${i+1} ===`);
    console.log('- loading URL');
    await page.goto(URL, { waitUntil: 'networkidle0' })
    console.log('- URL loaded.');
    await browser.close()
    console.log('- Browser closed.');
  }
})();
```

**Comment by anaulin** [comment]
@aslushnikov thanks for going deep into this (and I'm relieved you can repro too! 😹 )

I still get the same issue even if I disable JS in your script.

Here is what I get from running your script above (without disabling JS):
```
=== ITERATION 1 ===
- loading URL
- fetching body of .mp4 file
-- .mp4: OK
- URL loaded.
- Browser closed.
=== ITERATION 2 ===
- loading URL
- fetching body of .mp4 file
-- .mp4: OK
- video loading failed!
- URL loaded.
- Browser closed.
=== ITERATION 3 ===
- loading URL
- fetching body of .mp4 file
-- .mp4: OK
- URL loaded.
- Browser closed.
=== ITERATION 4 ===
- loading URL
- video loading failed!
- video loading failed!
- URL loaded.
- Browser closed.
=== ITERATION 5 ===
- loading URL
- video loading failed!
- video loading failed!
- URL loaded.
- Browser closed.
=== ITERATION 6 ===
- loading URL
- video loading failed!
- video loading failed!
- URL loaded.
- Browser closed.
=== ITERATION 7 ===
- loading URL
- video loading failed!
- video loading failed!
- URL loaded.
- Browser closed.
=== ITERATION 8 ===
- loading URL
- video loading failed!
- video loading failed!
- URL loaded.
- Browser closed.
=== ITERATION 9 ===
- loading URL
- fetching body of .mp4 file
-- .mp4: OK
- URL loaded.
- Browser closed.
=== ITERATION 10 ===
- loading URL
- video loading failed!
- video loading failed!
- URL loaded.
- Browser closed.
```
If I un-comment the line that disables JavaScript, things feel a little better, but still with failures:
```
=== ITERATION 1 ===
- loading URL
- fetching body of .mp4 file
-- .mp4: OK
- URL loaded.
- Browser closed.
=== ITERATION 2 ===
- loading URL
- video loading failed!
- URL loaded.
- Browser closed.
=== ITERATION 3 ===
- loading URL
- video loading failed!
- URL loaded.
- Browser closed.
=== ITERATION 4 ===
- loading URL
- video loading failed!
- URL loaded.
- Browser closed.
=== ITERATION 5 ===
- loading URL
- video loading failed!
- URL loaded.
- Browser closed.
=== ITERATION 6 ===
- loading URL
- fetching body of .mp4 file
-- .mp4: OK
- URL loaded.
- Browser closed.
=== ITERATION 7 ===
- loading URL
- video loading failed!
- URL loaded.
- Browser closed.
=== ITERATION 8 ===
- loading URL
- fetching body of .mp4 file
-- .mp4: OK
- URL loaded.
- Browser closed.
=== ITERATION 9 ===
- loading URL
- fetching body of .mp4 file
-- .mp4: OK
- URL loaded.
- Browser closed.
=== ITERATION 10 ===
- loading URL
- video loading failed!
- URL loaded.
- Browser closed.
```

**Comment by aslushnikov** [comment]
@anaulin that's surprising. Can you please also log out the [request.failure().errorText](https://pptr.dev/#?product=Puppeteer&version=v1.13.0&show=api-requestfailure) for failed requests? 

Maybe it'll shed some light on what's going on.

Also, if you just open the page in your browser - do you see the "video" element blinking once as it gets loaded?

**Comment by anaulin** [comment]
@aslushnikov you are absolutely right that i see the video blinking in again when i load that page -- that's a good catch, hadn't noticed that before.

I also added that extra log line, and the error text seems to always be `net::ERR_ABORTED`:
```
=== ITERATION 1 ===
- loading URL
- video loading failed!
- errorText: net::ERR_ABORTED
- URL loaded.
- Browser closed.
=== ITERATION 2 ===
- loading URL
- fetching body of .mp4 file
-- .mp4: OK
- URL loaded.
- Browser closed.
=== ITERATION 3 ===
- loading URL
- fetching body of .mp4 file
-- .mp4: OK
- URL loaded.
- Browser closed.
=== ITERATION 4 ===
- loading URL
- video loading failed!
- errorText: net::ERR_ABORTED
- URL loaded.
- Browser closed.
=== ITERATION 5 ===
- loading URL
- fetching body of .mp4 file
-- .mp4: OK
- URL loaded.
- Browser closed.
=== ITERATION 6 ===
- loading URL
- video loading failed!
- errorText: net::ERR_ABORTED
- URL loaded.
- Browser closed.
=== ITERATION 7 ===
- loading URL
- video loading failed!
- errorText: net::ERR_ABORTED
- URL loaded.
- Browser closed.
=== ITERATION 8 ===
- loading URL
- video loading failed!
- errorText: net::ERR_ABORTED
- URL loaded.
- Browser closed.
=== ITERATION 9 ===
- loading URL
- video loading failed!
- errorText: net::ERR_ABORTED
- URL loaded.
- Browser closed.
=== ITERATION 10 ===
- loading URL
- video loading failed!
- errorText: net::ERR_ABORTED
- URL loaded.
- Browser closed.
```

Full script (for future reference):
```javascript
const puppeteer = require('puppeteer');

const URL = 'https://www.nash.io/company/careers';
const VIDEO_URL =  'https://www.nash.io/static/careers-fe92d8a0bcbd10b63666cd11940a0f08.mp4';

(async() => {
  for (let i = 0; i < 10; ++i) {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();

    // This makes it work 100%.
    await page.setJavaScriptEnabled(false);

    page.on('requestfinished', async (request) => {
      if (request.url() !== VIDEO_URL)
        return;
      try {
        console.log('- fetching body of .mp4 file');
        await request.response().buffer();
        console.log(`-- .mp4: OK`);
      } catch (e) {
        console.log(`-- .mp4: FAIL - ${e.message}`);
      }
    });

    page.on('requestfailed', async (request) => {
      if (request.url() !== VIDEO_URL)
        return;
      console.log('- video loading failed!');
      console.log(`- errorText: ${request.failure().errorText}`);
    });

    console.log(`=== ITERATION ${i+1} ===`);
    console.log('- loading URL');
    await page.goto(URL, { waitUntil: 'networkidle0' })
    console.log('- URL loaded.');
    await browser.close()
    console.log('- Browser closed.');
  }
})();
```

**Comment by aslushnikov** [comment]
@anaulin I was able to reproduce this with disabled JavaScript. It looks like server sometimes aborts the request - the video element on the page is non-functional indeed when this happens:

![image](https://user-images.githubusercontent.com/746130/54468974-6c82a300-474f-11e9-84cf-2a5284a7b883.png)

**Comment by anaulin** [comment]
@aslushnikov thanks for getting to the bottom of that -- it is consistent with the `net::ERR_ABORTED` errors I was seeing. Looks like the issue for us is really this server breaking the connection, and not a Puppeteer issue after all.

**Comment by njlr** [comment]
In my case I was listening to the `'response'` event when I should have been listening to the `'requestfinished'` event.

**Comment by MikeColeGuru** [comment]
This might be a related issue: #4418 

I posted some test code relating to playing mp4s with 206 Partial Content
https://github.com/puppeteer/puppeteer/issues/4418#issuecomment-573277365

**Comment by adfnekc** [comment]
> In my case I was listening to the `'response'` event when I should have been listening to the `'requestfinished'` event.

it doesn`t works for me
