### ISSUE TITLE
Target / Browsing Context already closed when evaluating code in a pre-load script

### ISSUE THREAD

**Issue by whimboo** [puppeteer/puppeteer#12774]
The following script causes failures for both Chrome and Firefox. But these failures are different:

Chrome:
```
/Users/henrik/code/puppeteer/packages/puppeteer-core/lib/cjs/puppeteer/util/decorators.js:96
                throw new Error(message(this));
                      ^

Error: Browsing context already closed: User context already closed: Browser already closed.
    at WindowRealm.<anonymous> (/Users/henrik/code/puppeteer/packages/puppeteer-core/lib/cjs/puppeteer/util/decorators.js:96:23)
    at #evaluate (/Users/henrik/code/puppeteer/packages/puppeteer-core/lib/cjs/puppeteer/bidi/Realm.js:130:42)
    at async BidiFrameRealm.evaluate (/Users/henrik/code/puppeteer/packages/puppeteer-core/lib/cjs/puppeteer/bidi/Realm.js:100:16)
    at async BidiJSHandle.evaluate (/Users/henrik/code/puppeteer/packages/puppeteer-core/lib/cjs/puppeteer/api/JSHandle.js:142:20)
    at async BidiJSHandle.getProperties (/Users/henrik/code/puppeteer/packages/puppeteer-core/lib/cjs/puppeteer/api/JSHandle.js:179:35)
    at async #handleMessage (/Users/henrik/code/puppeteer/packages/puppeteer-core/lib/cjs/puppeteer/bidi/ExposedFunction.js:172:43)
```

Firefox:
```
/Users/henrik/code/puppeteer/packages/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:72
            this._reject(callback, new Errors_js_1.TargetCloseError('Target closed'));
                                   ^

TargetCloseError: Protocol error (script.callFunction): Target closed
    at CallbackRegistry.clear (/Users/henrik/code/puppeteer/packages/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:72:36)
    at BidiConnection.unbind (/Users/henrik/code/puppeteer/packages/puppeteer-core/lib/cjs/puppeteer/bidi/Connection.js:118:25)
    at WebSocket.<anonymous> (/Users/henrik/code/puppeteer/packages/puppeteer-core/lib/cjs/puppeteer/node/NodeWebSocketTransport.js:49:30)
    at callListener (/Users/henrik/code/puppeteer/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onClose (/Users/henrik/code/puppeteer/node_modules/ws/lib/event-target.js:220:9)
    at WebSocket.emit (node:events:520:28)
    at WebSocket.emitClose (/Users/henrik/code/puppeteer/node_modules/ws/lib/websocket.js:272:10)
    at Socket.socketOnClose (/Users/henrik/code/puppeteer/node_modules/ws/lib/websocket.js:1341:15)
    at Socket.emit (node:events:520:28)
    at TCP.<anonymous> (node:net:338:12) {
  cause: ProtocolError
      at <instance_members_initializer> (/Users/henrik/code/puppeteer/packages/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:93:14)
      at new Callback (/Users/henrik/code/puppeteer/packages/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:97:16)
      at CallbackRegistry.create (/Users/henrik/code/puppeteer/packages/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:22:26)
      at BidiConnection.send (/Users/henrik/code/puppeteer/packages/puppeteer-core/lib/cjs/puppeteer/bidi/Connection.js:54:32)
      at Session.send (/Users/henrik/code/puppeteer/packages/puppeteer-core/lib/cjs/puppeteer/bidi/core/Session.js:157:42)
      at Session.<anonymous> (/Users/henrik/code/puppeteer/packages/puppeteer-core/lib/cjs/puppeteer/util/decorators.js:98:27)
      at WindowRealm.callFunction (/Users/henrik/code/puppeteer/packages/puppeteer-core/lib/cjs/puppeteer/bidi/core/Realm.js:95:51)
      at WindowRealm.<anonymous> (/Users/henrik/code/puppeteer/packages/puppeteer-core/lib/cjs/puppeteer/util/decorators.js:98:27)
      at #evaluate (/Users/henrik/code/puppeteer/packages/puppeteer-core/lib/cjs/puppeteer/bidi/Realm.js:130:42)
      at async BidiFrameRealm.evaluateHandle (/Users/henrik/code/puppeteer/packages/puppeteer-core/lib/cjs/puppeteer/bidi/Realm.js:97:16)
```

Script:
```
'use strict';

const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
    product: 'chrome',
    // product: 'firefox',
    protocol: 'webDriverBiDi',
  });

  const page = await browser.newPage();

  await page.exposeFunction('logError', text => console.error(text));

  await page.evaluate(() => {
    window.logError('Failure from preload script');
  });

  await browser.close();
})();
```

@OrKoN can you please check? Thanks!

**Comment by OrKoN** [comment]
I am not sure if we need to suppress the error but if the browser.close needs to happen after the logError is done (and not while it is running), the code needs to be changed to 

```
  await page.evaluate(async () => {
    await window.logError('Failure from preload script');
  });
```

**Comment by whimboo** [comment]
Hm, but `logError` is not an async script so why would it require the usage of `await`?

**Comment by OrKoN** [comment]
all exposed functions are async since the call to the Node.js process and return the result from it.

**Comment by OrKoN** [comment]
maybe the documentation could have been clearer https://pptr.dev/api/puppeteer.page.exposefunction/ but the exposed function returns a promise.

**Comment by whimboo** [comment]
Thanks for the clarification. Using `await` clearly gets it to work.

**Comment by OrKoN** [comment]
I think we are not going to suppress the error because then it will silently not run the function (and might suppress other errors), I think the correct way is to await the exposed functions.
