### ISSUE TITLE
Node.JS Compilation error

### ISSUE THREAD

**Issue by TheStaticTurtle** [puppeteer/puppeteer#1282]
so I'm trying to compile my program that us coin-hive module witch uses puppeteer but pkg output me an error:

```
C:\Users\Samuel\Desktop\default>C:\Users\Samuel\AppData\Roaming\npm\pkg package.json
> pkg@4.2.6
> Targets not specified. Assuming:
  node8-linux-x64, node8-macos-x64, node8-win-x64
> Warning Cannot include directory %1 into executable.
  The directory must be distributed with executable as %2.
  ..\..\node_modules\puppeteer\.local-chromium
  path-to-executable/puppeteer
```
And there is the output when I strat Miner-win.exe:
```
C:\Users\Samuel\Desktop\default>Miner-win.exe
pkg/prelude/bootstrap.js:1155
      throw error;
      ^

Error: Cannot find module './lib/Puppeteer'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1252:46)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at Module.require (pkg/prelude/bootstrap.js:1136:31)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\snapshot\Samuel\node_modules\puppeteer\index.js:25:18)
    at Module._compile (pkg/prelude/bootstrap.js:1226:22)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)

C:\Users\Samuel\Desktop\default>
```
Here is my package.json
```
{
  "name": "Miner",
  "version": "1.0.0",
  "description": "CoinHive-JS_Miner",
  "main": "test.js",
  "bin": "test.js",
  "pkg": {
	"scripts": "C:\\Users\\Samuel\\AppData\\Roaming\\npm\\node_modules\\coin-hive\\src\\*.js"
  },
  "dependencies": { 
	"coin-hive" : "1.9.0",
	"puppeteer" : "any"
  },
  "author": "Samy",
  "license": "ISC"
}
```
And Here is my code:

```
const CoinHive = require('coin-hive');

(async () => {
 
  // Create miner
  const miner = await CoinHive('0vzRnGmDTHrSAwdJaKgDsdvSNoqaXIQO',username="test-nodejs"); // CoinHive's Site Key
 
  // Start miner
  await miner.start();
 
  // Listen on events
  miner.on('found', () => console.log('Found!'))
  miner.on('accepted', () => console.log('Accepted!'))
  miner.on('update', data => console.log(`Hashes per second: ${data.hashesPerSecond} Total hashes: ${data.totalHashes} Accepted hashes: ${data.acceptedHashes}`));
 
  // Stop miner
  setTimeout(async () => await miner.stop(), 60000);
})();
```

Thanks in advance!
PS: I have already started an issue on pkg: #https://github.com/zeit/pkg/issues/277

**Comment by bitcoinvsalts** [comment]
any updates on this one?

**Comment by aslushnikov** [comment]
Seems to be a dupe of #1281. This discussion would be more productive on PKG bugtracker. Please let us know if we can be helpful with this issue.
