### ISSUE TITLE
[Bug]: Puppeteer v22.14.0 requires --no-sandbox when running on Windows as SYSTEM

### ISSUE THREAD

**Issue by aarongoldenthal** [puppeteer/puppeteer#12857]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';

const browser = await puppeteer.launch(
// Works when adding the following args:
//    { args: ['--no-sandbox'] }
);
const page = await browser.newPage();

await page.goto('https://pptr.dev/');
await page.screenshot({ path: 'pptr.png' });

await browser.close();
```

### Background

After trying to upgrade a longstanding project from Puppeteer v22.13.1 to v22.14.0, Puppeteer now fails to navigate to a page when running on Windows under the build-in SYSTEM account. This was observed in GitLab CI, where the [typical Windows configuration for the GitLab Runner service](https://docs.gitlab.com/runner/install/windows.html#installation) is running under the SYSTEM account. While there was no error message indicating a sandbox-related issue, and this occurs with `page.goto()`, the only resolution identified so far is to launch Puppeteer with the `--no-sandbox` arg.

This has previously not been required in this Windows configuration (this has been run in GitLab CI for years). When logging in to the same Windows GitLab runners, the test with Puppeteer v22.14.0 runs nominally as the logged in user. It also runs nominally on Linux. But, it consistently fails in this Windows configuration with v22.14.0, but continues to run nominally when reverting to v22.13.1. All of this behavior is consistent on both Windows 11 and Windows Server 2022, and when opening local HTML files or remote URLs.

It's unclear if this is expected or not, but checking the Chrome 127 release notes and full changelog there was not an obvious change indicating this behavior.

### Expectation

The script above should run without `--no-sandbox`, as previous versions of Puppeteer did.

### Reality

Puppeteer, running in Windows as SYSTEM, fails to navigate to a page. This behavior can be seen in the example GitLab CI job logs below:

- Windows 11, Node 20.16.0, without `--no-sandbox`, [fails with `net::ERR_ABORTED`](https://gitlab.com/gitlab-ci-utils/pagean/-/jobs/7468114247)
- Windows 11, Node 20.16.0, with `--no-sandbox`, [executes nominally](https://gitlab.com/gitlab-ci-utils/pagean/-/jobs/7468116287)
- Windows 2022, Node 21.2.0, without `--no-sandbox`, [fails with `net::ERR_ABORTED`](https://gitlab.com/gitlab-ci-utils/pagean/-/jobs/7463255407)
- Windows 2022, Node 21.2.0, with `--no-sandbox`, [executes nominally](https://gitlab.com/gitlab-ci-utils/pagean/-/jobs/7463223287)

The minimal example above fails with `net::ERR_ABORTED`, although the original project has also timed out with `Navigation timeout of 60000 ms exceeded` when running Puppeteer directly, or with the test framework (vitest) timing out on a test.

### Puppeteer configuration file (if used)

```TypeScript
Not used.
```

### Puppeteer version

22.14.0

### Node version

20.16.0

### Package manager

npm

### Package manager version

10.8.1

### Operating system

Windows

**Comment by OrKoN** [comment]
I am not able to reproduce it on my Windows 10 or we do not reproduce it in our Windows CI on GitHub Actions. Chrome does require sandboxes on Windows now for PDF printing https://github.com/puppeteer/puppeteer/issues/12471 for which we now configure proper permissions https://github.com/puppeteer/puppeteer/pull/12430 I am not sure if the system account is affecting this behavior in some way but could you try permission configuration as specified here https://pptr.dev/troubleshooting#chrome-reports-sandbox-errors-on-windows?

**Comment by OrKoN** [comment]
Note that --no-sandbox is not recommended if you run any sort of untrusted context.

**Comment by OrKoN** [comment]
@aarongoldenthal can you start the regular Chrome browser under the system account on Windows?

**Comment by aarongoldenthal** [comment]
@OrKoN 

> I am not able to reproduce it on my Windows 10 (not a system account though) or we do not reproduce it in our Windows CI on GitHub Actions. Chrome does require sandboxes on Windows now for PDF printing #12471 for which we now configure proper permissions #12430 I am not sure if the system account is affecting this behavior in some way but could you try permission configuration as specified here https://pptr.dev/troubleshooting#chrome-reports-sandbox-errors-on-windows?

I tried this and had some issues. The chrome executable is dynamically loaded in the CI job, so I tried to add this (it's powershell, so with that env syntax):

```yaml
script:
  - npm ci
  - echo "$Env:USERPROFILE/.cache/puppeteer/chrome"
  - ls $Env:USERPROFILE/.cache/puppeteer/chrome
  - icacls $Env:USERPROFILE/.cache/puppeteer/chrome /grant *S-1-15-2-1:(OI)(CI)(RX)
  - node puppeteer.js
```

```powershell
$ echo "$Env:USERPROFILE/.cache/puppeteer/chrome"
C:\WINDOWS\system32\config\systemprofile/.cache/puppeteer/chrome
$ ls $Env:USERPROFILE/.cache/puppeteer/chrome
    Directory: C:\WINDOWS\system32\config\systemprofile\.cache\puppeteer\chrome
Mode                 LastWriteTime         Length Name                                                                 
----                 -------------         ------ ----                                                                 
d-----         6/21/2024   6:11 PM                win64-126.0.6478.63                                                  
d-----         7/31/2024   6:13 PM                win64-127.0.6533.88                                                  
$ icacls $Env:USERPROFILE/.cache/puppeteer/chrome /grant *S-1-15-2-1:(OI)(CI)(RX)
OI : The term 'OI' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the 
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:330 char:[69](https://gitlab.com/gitlab-ci-utils/pagean/-/jobs/7478138178#L69)
+ ... nv:USERPROFILE/.cache/puppeteer/chrome /grant *S-1-15-2-1:(OI)(CI)(RX ...
+                                                                ~~
    + CategoryInfo          : ObjectNotFound: (OI:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

I also tried logging in to the GitLab runner and tried the same command as admin and got the same error. Is it possible the `OI` has changed (I assume not, still in the docs), or maybe fails because it's SYSTEM?

> @aarongoldenthal can you start the regular Chrome browser under the system account on Windows?

I tried to run the regular Chrome browser (127.0.6533.88) , and it ran as the logged in user, but not as SYSTEM.

**Comment by OrKoN** [comment]
I have read up a bit on the system accounts and it looks like they exist for the purpose of Windows itself installing its components. So perhaps it is not a good idea to run a browser as a system user. Unfortunately, I do not know enough about Windows to tell why the icacls not working, it definitely works for regular users and it is what [Chromium uses ](https://source.chromium.org/chromium/chromium/src/+/main:testing/scripts/common.py;l=83;drc=b5c6726e7158b4ec140e07260ba62b2869a01a07)to test the browser.  

I would suggest adding `dumpio: true` to the launch options to see if there are indicators of what is exactly wrong with sandboxes under the system user.

**Comment by OrKoN** [comment]
Here is some additional documentation on sandbox architecture in Chromium https://chromium.googlesource.com/chromium/src/+/HEAD/docs/design/sandbox.md#Sandbox-Windows-architecture

**Comment by aarongoldenthal** [comment]
> I have read up a bit on the system accounts and it looks like they exist for the purpose of Windows itself installing its components. So perhaps it is not a good idea to run a browser as a system user. Unfortunately, I do not know enough about Windows to tell why the icacls not working, it definitely works for regular users and it is what [Chromium uses ](https://source.chromium.org/chromium/chromium/src/+/main:testing/scripts/common.py;l=83;drc=b5c6726e7158b4ec140e07260ba62b2869a01a07)to test the browser.
> 
> I would suggest adding `dumpio: true` to the launch options to see if there are indicators of what is exactly wrong with sandboxes under the system user.

It appears in PowerShell the permissions string needs to be quoted, so that run, but wasn't the fix. Using `dumpio` did give some errors, but trying to wrap my head around them (which were a little different after running a few times).

Runs 1 and 3 (with slightly different timing on the gpu process failure):

```powershell
$ icacls $Env:PUPPETEER_CACHE_DIR\chrome /grant "*S-1-15-2-1:(OI)(CI)(RX)"
processed file: C:\GitLab-Runner\builds\scdbxdWy\0\gitlab-ci-utils\pagean/node_modules/.cache/puppeteer\chrome
Successfully processed 1 files; Failed processing 0 files
$ node puppeteer.js
DevTools listening on ws://127.0.0.1:62051/devtools/browser/989db9ab-d792-4475-998b-78ccf32bf7f8
[3316:1360:0801/195734.416:ERROR:network_service_instance_impl.cc(600)] Network service crashed, restarting service.
[3316:1360:0801/195734.604:ERROR:network_service_instance_impl.cc(600)] Network service crashed, restarting service.
[3316:1360:0801/195734.760:ERROR:gpu_process_host.cc(1007)] GPU process exited unexpectedly: exit_code=34
[3316:1360:0801/195734.916:ERROR:network_service_instance_impl.cc(600)] Network service crashed, restarting service.
ERROR: The process with PID 57[72](https://gitlab.com/gitlab-ci-utils/pagean/-/jobs/7488565706#L72) (child process of PID 3316) could not be terminated.
file:///C:/GitLab-Runner/builds/scdbxdWy/0/gitlab-ci-utils/pagean/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Frame.js:183
                        ? new Error(`${response.errorText} at ${url}`)
                          ^
Error: net::ERR_ABORTED at https://pptr.dev/
    at navigate (file:///C:/GitLab-Runner/builds/scdbxdWy/0/gitlab-ci-utils/pagean/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Frame.js:183:27)
    at async Deferred.race (file:///C:/GitLab-Runner/builds/scdbxdWy/0/gitlab-ci-utils/pagean/node_modules/puppeteer-core/lib/esm/puppeteer/util/Deferred.js:33:20)
    at async CdpFrame.goto (file:///C:/GitLab-Runner/builds/scdbxdWy/0/gitlab-ci-utils/pagean/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Frame.js:149:25)
    at async CdpPage.goto (file:///C:/GitLab-Runner/builds/scdbxdWy/0/gitlab-ci-utils/pagean/node_modules/puppeteer-core/lib/esm/puppeteer/api/Page.js:561:20)
    at async file:///C:/GitLab-Runner/builds/scdbxdWy/0/gitlab-ci-utils/pagean/puppeteer.js:6:1
```

Run 2:

```powershell
$ node puppeteer.js
DevTools listening on ws://127.0.0.1:62064/devtools/browser/4aa5f64a-1860-4bdf-b013-b47452b2c351
[1140:10296:0801/200116.170:ERROR:network_service_instance_impl.cc(600)] Network service crashed, restarting service.
[1140:10296:0801/200116.342:ERROR:network_service_instance_impl.cc(600)] Network service crashed, restarting service.
[1140:10296:0801/200116.499:ERROR:network_service_instance_impl.cc(600)] Network service crashed, restarting service.
ERROR: The process with PID 52 (child process of PID 1140) could not be terminated.
file:///C:/GitLab-Runner/builds/scdbxdWy/0/gitlab-ci-utils/pagean/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Frame.js:183
                        ? new Error(`${response.errorText} at ${url}`)
                          ^
Error: net::ERR_ABORTED at https://pptr.dev/
    at navigate (file:///C:/GitLab-Runner/builds/scdbxdWy/0/gitlab-ci-utils/pagean/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Frame.js:1[83](https://gitlab.com/gitlab-ci-utils/pagean/-/jobs/7488576669#L83):27)
    at async Deferred.race (file:///C:/GitLab-Runner/builds/scdbxdWy/0/gitlab-ci-utils/pagean/node_modules/puppeteer-core/lib/esm/puppeteer/util/Deferred.js:33:20)
    at async CdpFrame.goto (file:///C:/GitLab-Runner/builds/scdbxdWy/0/gitlab-ci-utils/pagean/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Frame.js:149:25)
    at async CdpPage.goto (file:///C:/GitLab-Runner/builds/scdbxdWy/0/gitlab-ci-utils/pagean/node_modules/puppeteer-core/lib/esm/puppeteer/api/Page.js:561:20)
    at async file:///C:/GitLab-Runner/builds/scdbxdWy/0/gitlab-ci-utils/pagean/puppeteer.js:6:1
```

**Comment by OrKoN** [comment]
Interesting, so it is crashing inside the browser's network service. Unfortunately, I do not know further details. Does it also crash if you just run a headless screenshot command: `path\to\chrome.exe --headless=new --screenshot https://example.com`? If it does, could you please file a bug at crbug.com/new and post the link here?

**Comment by aarongoldenthal** [comment]
@OrKoN I did a little more troubleshooting directly running the chrome executable installed with Puppeteer. Similar results were seen when running under the SYSTEM account. What was surprising (to me, at least) was the results when running as the logged-in user. In that case both versions of Chrome successfully ran, but Chrome 126 (Puppeteer 22.13.1) showed a sandbox error, the network service crashed, but then recovered (versus no errors annunciated with Chrome 127).

Does that seem consistent with what you would expect given the sandbox changes? And is that executable covered by crbug.com/new, or is that unique to puppeteer?

Chrome 126.0.6478.182 (puppeteer@22.13.1), logged on user:

```ps
PS C:\>& "$PUPPETEER_CACHE_DIR\chrome\win64-126.0.6478.182\chrome-win64\chrome.exe" --headless=new --screenshot https://pptr.dev
[29264:10760:0805/110615.159:ERROR:sandbox_win.cc(913)] Sandbox cannot access executable. Check filesystem permissions are valid. See https://bit.ly/31yqMJR.: Access is denied. (0x5)
[29264:19452:0805/110615.182:ERROR:network_service_instance_impl.cc(600)] Network service crashed, restarting service.
287650 bytes written to file screenshot.png
```

Chrome 127.0.6533.88 (puppeteer@22.15.0), logged on user:

```ps
PS C:\>& "$PUPPETEER_CACHE_DIR\chrome\win64-127.0.6533.88\chrome-win64\chrome.exe" --headless=new --screenshot https://pptr.dev
281121 bytes written to file screenshot.png
```

Chrome 126.0.6478.182 (puppeteer@22.13.1), SYSTEM:

```ps
$ & "$PUPPETEER_CACHE_DIR\chrome\win64-126.0.6478.182\chrome-win64\chrome.exe" --headless=new --screenshot https://pptr.dev
[0805/145259.221:ERROR:registration_protocol_win.cc(136)] TransactNamedPipe: The pipe has been ended. (0x6D)
[1576:1216:0805/145315.053:ERROR:os_crypt_win.cc(70)] Failed to encrypt: Access is denied. (0x5)
[1576:4492:0805/145317.665:ERROR:sandbox_win.cc(913)] Sandbox cannot access executable. Check filesystem permissions are valid. See https://bit.ly/31yqMJR.: Access is denied. (0x5)
[1576:3884:0805/145317.962:ERROR:login_database_async_helper.cc(106)] Encryption is not available.
[1576:1948:0805/145318.260:ERROR:login_database_async_helper.cc(106)] Encryption is not available.
[1576:1216:0805/145318.682:ERROR:network_service_instance_impl.cc(600)] Network service crashed, restarting service.
67775 bytes written to file screenshot.png
```

Chrome 127.0.6533.88 (puppeteer@22.15.0), SYSTEM:

```ps
$ & "$PUPPETEER_CACHE_DIR\chrome\win64-127.0.6533.88\chrome-win64\chrome.exe" --headless=new --screenshot https://pptr.dev
[4144:1584:0805/145405.287:ERROR:os_crypt_win.cc(70)] Failed to encrypt: Access is denied. (0x5)
[4144:2084:0805/145405.711:ERROR:login_database_async_helper.cc(106)] Encryption is not available.
[4144:4708:0805/145406.055:ERROR:login_database_async_helper.cc(106)] Encryption is not available.
[4144:1584:0805/145406.461:ERROR:network_service_instance_impl.cc(600)] Network service crashed, restarting service.
[4144:1584:0805/145406.861:ERROR:network_service_instance_impl.cc(600)] Network service crashed, restarting service.
[4144:1584:0805/145407.313:ERROR:network_service_instance_impl.cc(600)] Network service crashed, restarting service.
[4144:1584:0805/145407.565:ERROR:network_service_instance_impl.cc(600)] Network service crashed, restarting service.
...network service crash continues until the process is killed
```

**Comment by OrKoN** [comment]
The command `path\to\chrome.exe --headless=new --screenshot https://example.com` does not use Puppeteer in any way and launching Chrome this way is somewhat similar to how Puppeteer itself launches Chrome. So it does look consistent with the sandbox issue although I expected it to only affect PDFs. At least that is what was affected in our CI setup. [In the latest versions we try to invoke `setup.exe`](https://github.com/puppeteer/puppeteer/releases/tag/browsers-v2.3.0) to configure permissions on the installation folder so these error is not present on binaries installed with puppeteer@22.15.0. It looks like there are some other errors in M127 under the system account. I'd recommend filing a crbug.com/new for those. If you can install a regular Chrome (Puppeteer downloads [Chrome for Testing](https://developer.chrome.com/blog/chrome-for-testing)) and try it in that environment with that command, it'd be helpful to include it into the bug report.

**Comment by OrKoN** [comment]
I find an older issue for "Failed to encrypt" https://issues.chromium.org/issues/40281493#comment23 Not sure if it could be applicable here?

**Comment by OrKoN** [comment]
Maybe adding the following args to chrome.exe invocations `--enable-logging --v=1` would provide more details.

**Comment by lostsource** [comment]
Adding `--enable-features=NetworkServiceInProcess2` seems to mitigate the Network Service crash

**Comment by aarongoldenthal** [comment]
Thanks @lostsource, the `--enable-features=NetworkServiceInProcess2` flag worked for me as well.

@OrKoN I did try testing regular Chrome - the latest of versions 124, 125, 126, and 127 - and all four failed with the following:

```ps
$ & "C:\Program Files\Google\Chrome\Application\chrome.exe" --headless=new --enable-logging --v=1 https://pptr.dev/
[0806/015543.481:ERROR:registration_protocol_win.cc(136)] TransactNamedPipe: The pipe has been ended. (0x6D)
[4356:4040:0806/015550.788:ERROR:os_crypt_win.cc(70)] Failed to encrypt: Access is denied. (0x5)
[4356:1948:0806/015551.413:ERROR:login_database_async_helper.cc(106)] Encryption is not available.
[4356:880:0806/015551.413:ERROR:login_database_async_helper.cc(106)] Encryption is not available.
[4356:2016:0806/015551.978:ERROR:app_bound_encryption_provider_win.cc(83)] Unable to encrypt key. Result: Error (0x13D) while retrieving error. (0x8004A005) GetLastError: 5
Created TensorFlow Lite XNNPACK delegate for CPU.
```

After that the process hangs until killed. So, it appears that working in this config was actually unique to Chrome for Testing. I haven't had a chance to file a bug with Chrome yet, but wonder if the bug is that this ever worked.

**Comment by OrKoN** [comment]
You need to include `--screenshot` to make sure a headless command is run to capture a screenshot. Otherwise, it is expected for the browser to just remain open. Errors might not necessarily mean it does not work.

**Comment by aarongoldenthal** [comment]
> You need to include `--screenshot` to make sure a headless command is run to capture a screenshot. Otherwise, it is expected for the browser to just remain open. Errors might not necessarily mean it does not work.

I reran the tests with `--screenshot` for the same versions of Chrome (124 - 127) and while most of the same errors occurred, the screenshot was successful for all.

``ps
$ & "C:\Program Files\Google\Chrome\Application\chrome.exe" --headless=new --enable-logging --v=1 --screenshot https://pptr.dev/
[0809/155526.705:ERROR:registration_protocol_win.cc(136)] TransactNamedPipe: The pipe has been ended. (0x6D)
[3128:4144:0809/155534.493:ERROR:os_crypt_win.cc(70)] Failed to encrypt: Access is denied. (0x5)
[3128:5004:0809/155535.041:ERROR:login_database_async_helper.cc(106)] Encryption is not available.
[3128:5004:0809/155535.386:ERROR:login_database_async_helper.cc(106)] Encryption is not available.
[3128:2312:0809/155536.578:ERROR:app_bound_encryption_provider_win.cc(83)] Unable to encrypt key. Result: Error (0x13D) while retrieving error. (0x8004A005) GetLastError: 5
68037 bytes written to file screenshot.png
```

**Comment by OrKoN** [comment]
then it looks like `--enable-features=NetworkServiceInProcess2` should make it work for you?

**Comment by aarongoldenthal** [comment]
> then it looks like `--enable-features=NetworkServiceInProcess2` should make it work for you?

It has. I've used it on the two projects that were having issues and both were resolved. Do you think it's still worth opening a Chrome issue? It feels more like a lower priority edge case as long as there's a fix, maybe just a PR to the troubleshooting docs?

**Comment by OrKoN** [comment]
I think it's worth filing it. NetworkServiceInProcess2 is not available on all platforms and AFAIK it is mostly only used for Android WebViews. I would say Chrome should probably run without it.

**Comment by aarongoldenthal** [comment]
Chrome issue opened at https://issues.chromium.org/issues/360642958

**Comment by dezza** [comment]
Issue is oddly very similar to what I am experiencing on opensuse tumbleweed (*linux*). I tested many different versions from `npx @puppeteer/browsers install chrome@...` happens to all

Getting a real `chromium` build from the official opensuse repos and setting `executablePath` also works.

The one that launches and seems to work best is still one of the later versions (linux-137.0.7151.55), I can even get a functional GUI, but it errors meanwhile with
```
[224406:224406:0609/045154.548253:ERROR:content/browser/network_service_instance_impl.cc:606] Network service crashed, restarting service.
[224406:224406:0609/045154.805542:ERROR:content/browser/network_service_instance_impl.cc:606] Network service crashed, restarting service.
[224406:224406:0609/045155.040044:ERROR:content/browser/network_service_instance_impl.cc:606] Network service crashed, restarting service.
```
(*repeated in eternity* with less than <100ms intervals), but GUI launch just requests not working. If I disable hardware acceleration in the browser via settings it locks up completely once restarted.

Another version 134-something fails with 
```
elf_dynamic_array_reader.h(64) tag not found
```

Which points to more general libc incompatability.

The solution is also
```js
const browser = await puppeteer.launch({
  args: ['--no-sandbox'],
})
```

I am commenting here, because I hope I can shed light that this is not only a Windows issue.

It could be the build args or the libc that Google builds against. I also tried `--disable-setuid-sandbox`, as well as changing permissions on the `chrome-sandbox` binary as said in this older post: https://forums.opensuse.org/t/latest-chromium-no-sandbox-error/71714

I find it quite peculiar that it would fail if hwaccel is disabled as well as have inconsistent launching of the GUI and errors pointing to libc compat issue of sorts or maybe google is packing, compressing or otherwise modifying the binaries in a unique way that makes it incompatible on many systems.

Since this is isolated issue to `Google for testing`, I think these builds have a very narrow compatibility and use-case.
