### ISSUE TITLE
[Bug]: ProtocolError: NS_BINDING_ABORTED on navigation in Firefox when navigating to https://x.com

### ISSUE THREAD

**Issue by OIRNOIR** [puppeteer/puppeteer#12929]
### Minimal, reproducible example

```TypeScript
import puppeteer from "puppeteer";

const browser = await puppeteer.launch({
	browser: "firefox"
});

const page = await browser.newPage();

await page.goto("https://x.com/"); // Crash!
```

### Background

I've been trying to access x.com with puppeteer through the Firefox browser. For some reason, the Firefox version of puppeteer cannot get past some step of the navigation process unique to x.com and crashes.

### Expectation

I expected the redirects to be followed properly and the page to load accordingly.

### Reality

This error occurs on page.goto:

```
file:///.../Puppeteer%20Firefox%20Testing/node_modules/.pnpm/puppeteer-core@23.0.2/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:89
    #error = new ProtocolError();
             ^

ProtocolError: Protocol error (browsingContext.navigate): unknown error Error: NS_BINDING_ABORTED #checkLoadingState@chrome://remote/content/shared/Navigate.sys.mjs:286:28
onStateChange@chrome://remote/content/shared/Navigate.sys.mjs:345:28
 at https://x.com/
    at <instance_members_initializer> (file:///.../Puppeteer%20Firefox%20Testing/node_modules/.pnpm/puppeteer-core@23.0.2/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:89:14)
    at new Callback (file:///.../Puppeteer%20Firefox%20Testing/node_modules/.pnpm/puppeteer-core@23.0.2/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:93:16)
    at CallbackRegistry.create (file:///.../Puppeteer%20Firefox%20Testing/node_modules/.pnpm/puppeteer-core@23.0.2/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:19:26)
    at BidiConnection.send (file:///.../Puppeteer%20Firefox%20Testing/node_modules/.pnpm/puppeteer-core@23.0.2/node_modules/puppeteer-core/lib/esm/puppeteer/bidi/Connection.js:51:32)
    at Session.send (file:///.../Puppeteer%20Firefox%20Testing/node_modules/.pnpm/puppeteer-core@23.0.2/node_modules/puppeteer-core/lib/esm/puppeteer/bidi/core/Session.js:134:42)
    at Session.<anonymous> (file:///.../Puppeteer%20Firefox%20Testing/node_modules/.pnpm/puppeteer-core@23.0.2/node_modules/puppeteer-core/lib/esm/puppeteer/util/decorators.js:94:27)
    at BrowsingContext.navigate (file:///.../Puppeteer%20Firefox%20Testing/node_modules/.pnpm/puppeteer-core@23.0.2/node_modules/puppeteer-core/lib/esm/puppeteer/bidi/core/BrowsingContext.js:303:33)
    at BrowsingContext.<anonymous> (file:///.../Puppeteer%20Firefox%20Testing/node_modules/.pnpm/puppeteer-core@23.0.2/node_modules/puppeteer-core/lib/esm/puppeteer/util/decorators.js:94:27)
    at BidiFrame.goto (file:///.../Puppeteer%20Firefox%20Testing/node_modules/.pnpm/puppeteer-core@23.0.2/node_modules/puppeteer-core/lib/esm/puppeteer/bidi/Frame.js:322:22)
    at BidiFrame.<anonymous> (file:///.../Puppeteer%20Firefox%20Testing/node_modules/.pnpm/puppeteer-core@23.0.2/node_modules/puppeteer-core/lib/esm/puppeteer/util/decorators.js:94:27)

Node.js v20.16.0
```

### Puppeteer version

23.0.2

### Node version

20.16.0

### Package manager

pnpm

### Package manager version

9.7.0

### Operating system

Linux

**Comment by OrKoN** [comment]
@whimboo could you please take a look?

**Comment by whimboo** [comment]
Thanks for the report. We will investigate via https://bugzilla.mozilla.org/show_bug.cgi?id=1908515.

**Comment by amanzrx4** [comment]
What's the update here

**Comment by whimboo** [comment]
For an up-to-date information about the state of the bug please check the bug as listed on https://github.com/puppeteer/puppeteer/issues/12929#issuecomment-2283775505.

**Comment by juliandescottes** [comment]
@OrKoN I was initially confused when testing with Puppeteer and Chrome trying to understand why we didn't get any error, but that's only the case when using CDP. When using Chrome + protocol WebDriver BiDi, Chrome has the exact same issue when navigating to x.com, mozilla.com etc... 

> ProtocolError: Protocol error (browsingContext.navigate): unknown error navigation canceled, as new navigation is requested by scriptInitiated Error
    at new UnknownErrorException (/Users/juliandescottes/Development/git/puppeteer-examples/node_modules/chromium-bidi/lib/cjs/protocol/ErrorResponse.js:122:39)
    at /Users/juliandescottes/Development/git/puppeteer-examples/node_modules/chromium-bidi/lib/cjs/bidiMapper/modules/context/BrowsingContextImpl.js:348:52
    at /Users/juliandescottes/Development/git/puppeteer-examples/node_modules/mitt/dist/mitt.js:1:255
    at Array.map (<anonymous>)
    at Object.emit (/Users/juliandescottes/Development/git/puppeteer-examples/node_modules/mitt/dist/mitt.js:1:239)
    at CDPClientAdapter.emit (/Users/juliandescottes/Development/git/puppeteer-examples/node_modules/chromium-bidi/lib/cjs/utils/EventEmitter.js:55:23)
    at #forwardMessage (/Users/juliandescottes/Development/git/puppeteer-examples/node_modules/puppeteer-core/lib/cjs/puppeteer/bidi/BidiOverCdp.js:124:14)
    at /Users/juliandescottes/Development/git/puppeteer-examples/node_modules/puppeteer-core/lib/cjs/third_party/mitt/mitt.js:64:7
    at Array.map (<anonymous>)
    at Object.emit (/Users/juliandescottes/Development/git/puppeteer-examples/node_modules/puppeteer-core/lib/cjs/third_party/mitt/mitt.js:63:39) at https://x.com/
    at <instance_members_initializer> (/Users/juliandescottes/Development/git/puppeteer-examples/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:94:14)
    at new Callback (/Users/juliandescottes/Development/git/puppeteer-examples/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:98:16)
    at CallbackRegistry.create (/Users/juliandescottes/Development/git/puppeteer-examples/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:23:26)
    at BidiConnection.send (/Users/juliandescottes/Development/git/puppeteer-examples/node_modules/puppeteer-core/lib/cjs/puppeteer/bidi/Connection.js:54:32)
    at Session.send (/Users/juliandescottes/Development/git/puppeteer-examples/node_modules/puppeteer-core/lib/cjs/puppeteer/bidi/core/Session.js:137:42)
    at Session.<anonymous> (/Users/juliandescottes/Development/git/puppeteer-examples/node_modules/puppeteer-core/lib/cjs/puppeteer/util/decorators.js:104:27)
    at BrowsingContext.navigate (/Users/juliandescottes/Development/git/puppeteer-examples/node_modules/puppeteer-core/lib/cjs/puppeteer/bidi/core/BrowsingContext.js:309:33)
    at BrowsingContext.<anonymous> (/Users/juliandescottes/Development/git/puppeteer-examples/node_modules/puppeteer-core/lib/cjs/puppeteer/util/decorators.js:104:27)
    at BidiFrame.goto (/Users/juliandescottes/Development/git/puppeteer-examples/node_modules/puppeteer-core/lib/cjs/puppeteer/bidi/Frame.js:339:22)
    at BidiFrame.<anonymous> (/Users/juliandescottes/Development/git/puppeteer-examples/node_modules/puppeteer-core/lib/cjs/puppeteer/util/decorators.js:104:27)

**Comment by OrKoN** [comment]
That's true, thanks for testing! I think we should add a test for this scenario.

**Comment by juliandescottes** [comment]
@OrKoN I'm about to land https://bugzilla.mozilla.org/show_bug.cgi?id=1914407 , after which we should get the following error message for the navigation issues mentioned in this report: 

> Navigation was aborted by another navigation

That will be available in Firefox 134. I imagine we should update https://github.com/puppeteer/puppeteer/blob/2747e7f2439484da5a74e1bb547a327f04599ebc/packages/puppeteer-core/src/bidi/Frame.ts#L332 based on this?

**Comment by OrKoN** [comment]
yes, or with a dedicated message if we can agree on what to do with aborted navigations in the spec.

**Comment by OrKoN** [comment]
@juliandescottes I seem to be still getting

```
ProtocolError: Protocol error (browsingContext.navigate): unknown error Error: NS_BINDING_ABORTED #checkLoadingState@chrome://remote/content/shared/Navigate.sys.mjs:327:28
onStateChange@chrome://remote/content/shared/Navigate.sys.mjs:422:28
 at http://localhost:58329/client-redirect.html
 ```
 
 in Firefox 134.

**Comment by juliandescottes** [comment]
> @juliandescottes I seem to be still getting
> 
> ```
> ProtocolError: Protocol error (browsingContext.navigate): unknown error Error: NS_BINDING_ABORTED #checkLoadingState@chrome://remote/content/shared/Navigate.sys.mjs:327:28
> onStateChange@chrome://remote/content/shared/Navigate.sys.mjs:422:28
>  at http://localhost:58329/client-redirect.html
> ```
> 
> in Firefox 134.

Yes sorry I forgot to update you here. The patch was backed out, it will require more refactoring to try to address this on our side apparently, starting with https://bugzilla.mozilla.org/show_bug.cgi?id=1930616

**Comment by OrKoN** [comment]
@juliandescottes @whimboo I checked the issues again and it looks like this scenario needs to report navigationAborted event with no error for the navigate call. I added a test here https://github.com/puppeteer/puppeteer/pull/13621

**Comment by juliandescottes** [comment]
For info we are landing https://bugzilla.mozilla.org/show_bug.cgi?id=1914407 which will make Firefox stop failing navigate calls in case NS_BINDING_ABORTED is received after the navigationCommitted event.

**Comment by hheexx** [comment]
@juliandescottes awesome! what train? 143?

**Comment by juliandescottes** [comment]
@hheexx the next one, 144.

**Comment by tapashi15-coder** [comment]
Hi team, (@OrKoN @juliandescottes @whimboo )

I'm running into what looks like the same issue reported in this thread but I'd like to confirm.

When navigating to a federated sign-in endpoint (a URL that immediately validates parameters and then redirects to a destination application), the browser consistently fails with:

```
ProtocolError: Protocol error (browsingContext.navigate): unknown error Error: NS_BINDING_ABORTED
#checkLoadingState@chrome://remote/content/shared/Navigate.sys.mjs:353:30
onStateChange@chrome://remote/content/shared/Navigate.sys.mjs:435:28
 at <initial redirecting URL>...
```

How these endpoints behave:

- The initial request is to a federation URL with parameters such as Action=login&Destination=<target>.
- It issues a redirect to the Destination.
- During this redirect, the navigation fails with the above error.

I also enabled firefox trace logs for it and it says 

```
- RemoteAgent	TRACE	[11] ProgressListener Loading state: isStart=false isStop=true status=0x804b0002, 
- RemoteAgent TRACE [11] ProgressListener Stop: has error=true url=****
- DEBUG	
{
    "message": "Page error:  [Error: ReferenceError: ReportingObserver is not defined]",
    "stepName": "Navigate-to-federated-url"
}
- RemoteAgent	TRACE	Received command browsingContext._applySessionData for destination ROOT
- RemoteAgent	TRACE	ParentWebProgressListener Loading state: flags: 983041, status: 0,  isStart: true, isStop: false, isNetwork: true, isBindingAborted: false, targetURI: ***
- RemoteAgent TRACE We're going to fail the navigation for url: ****, , since it was interrupted by a new navigation.
```

**Questions:**

- Is this the same underlying issue being tracked in Bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1914407 ?
- What kinds of URLs are affected? From my side, it seems tied to immediate redirect chains or script-triggered navigations.
- Has this already been fixed in a specific Firefox release? I saw references to 134 (landed, then backed out) and mentions of 144 as a possible fix. Which release train should we follow?
- Is there a recommended workaround until then?

This affects real login flows that rely on federation redirects, so knowing whether it’s expected, fixed upstream, or safe to work around would help a lot.

**Comment by juliandescottes** [comment]
@tapashi15-coder 

Hi! Sorry you're hitting this issue, some answers below.

> Is this the same underlying issue being tracked in Bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1914407 ?

This sounds like the same issue yes. 

> What kinds of URLs are affected? From my side, it seems tied to immediate redirect chains or script-triggered navigations.

Regular HTTP redirects should not have been affected by that. If you see an issue with regular redirects, can you file another issue? The main issue was around redirects initiated by a script while loading the page.

> Has this already been fixed in a specific Firefox release? I saw references to 134 (landed, then backed out) and mentions of 144 as a possible fix. Which release train should we follow?

The bug is marked as fixed in Firefox 144 which is currently in beta/dev-edition, could you give it a try?

> Is there a recommended workaround until then?

As a workaround I imagine you can temporarily try catch and swallow the exception if you get a NS_BINDING_ABORTED error.

> This affects real login flows that rely on federation redirects, so knowing whether it’s expected, fixed upstream, or safe to work around would help a lot.

One thing to note (and that should be the same with chrome), is that with this fix, the navigation "resolves" as soon as the script initiated redirect starts. So it might resolve "earlier" than you typically expect, unless Puppeteer has some logic to wait for additional navigation to complete (cc @OrKoN) ?

@tapashi15-coder overall, it would be really helpful if you could test with beta and report back.

**Comment by tapashi15-coder** [comment]
@whimboo @juliandescottes When will firefox 144 will be released?

**Comment by juliandescottes** [comment]
@tapashi15-coder you can refer to https://whattrainisitnow.com/ . Firefox 144 should be released on October 14.
