### ISSUE TITLE
puppeteer works locally but not on jenkins

### ISSUE THREAD

**Issue by yasserhussien** [puppeteer/puppeteer#12952]
The build failed on jenkins
```TypeScript
Error: EACCES: permission denied, open '/.config/puppeteerrc'
    at Object.openSync (node:fs:591:3)
    at Object.readFileSync (node:fs:459:35)
    at #readConfiguration (/var/tmp/vproj/pvid/node_modules/cosmiconfig/dist/ExplorerSync.js:76:39)
    at search (/var/tmp/vproj/pvid/node_modules/cosmiconfig/dist/ExplorerSync.js:44:63)
    at emplace (/var/tmp/vproj/pvid/node_modules/cosmiconfig/dist/util.js:12:20)
    at search (/var/tmp/vproj/pvid/node_modules/cosmiconfig/dist/ExplorerSync.js:64:50)
    at emplace (/var/tmp/vproj/pvid/node_modules/cosmiconfig/dist/util.js:12:20)
    at search (/var/tmp/vproj/pvid/node_modules/cosmiconfig/dist/ExplorerSync.js:64:50)
    at emplace (/var/tmp/vproj/pvid/node_modules/cosmiconfig/dist/util.js:12:20)
    at search (/var/tmp/vproj/pvid/node_modules/cosmiconfig/dist/ExplorerSync.js:64:50) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/.config/puppeteerrc'
}

### Puppeteer version

23.0.2

### Node version

20.15.0

### Package manager

npm

### Package manager version

10.8.2

**Comment by OrKoN** [comment]
cosmicconfigs tries to find the config in the parent directories up to the home folder of the current user. It looks like in this case there is no home folder and there are no permissions to read the config if it exists in /. Puppeteer uses a global search strategy as documented in https://github.com/cosmiconfig/cosmiconfig?tab=readme-ov-file#searchstrategy I would recommend either making sure there is a user and a home folder that the current user has permissions to access or define a config in an accessible place as described here https://pptr.dev/guides/configuration#changing-the-default-cache-directory

**Comment by yasserhussien** [comment]
@OrKoN as they mentioned here [https://pptr.dev/guides/configuration#changing-the-default-cache-directory](https://pptr.dev/guides/configuration#changing-the-default-cache-directory)
Notice this is only possible with CommonJS configuration files as information about the ambient environment is needed (in this case, __dirname).
so is there another way to work with es2020?

**Comment by yasserhussien** [comment]
@OrKoN  is it normal to have the previous error when I just add puppeteer to the file package.json without using it?

**Comment by yasserhussien** [comment]
Hi @OrKoN
actually the previous solution doesn't work with me
so it seems that we can only use the code [https://pptr.dev/guides/configuration#changing-the-default-cache-directory](https://pptr.dev/guides/configuration#changing-the-default-cache-directory)
is there another suggestion from your side to solve this issue?
