### ISSUE TITLE
[Bug]: Puppeteer fails to connect to WebDriver BiDi websocket from Firefox

### ISSUE THREAD

**Issue by JupiterSky11** [puppeteer/puppeteer#13057]
### Minimal, reproducible example

```TypeScript
import puppeteer, { ConnectOptions } from 'puppeteer';

async function main() {
    try {
        const cOps: ConnectOptions = {
            browserWSEndpoint: "ws://127.0.0.1:9221",
            protocol: "webDriverBiDi",
        }

        const browser = await puppeteer.connect(cOps);
        console.log("Connected!");

        await browser.disconnect();
        console.log("Disconnected!");
    } catch (e) {
        console.log("FAILURE!\n", e);
    }
}

main()
```

### Background

Firefox is launched via `firefox --remote-debugging-port 9221`, and responds with `WebDriver BiDi listening on ws://127.0.0.1:9221`.

Remote debugging is enabled in the settings for the browser.

### Expectation

As I understand it, this should connect to the browser, then disconnect.  It does not accomplish the first half.

### Reality

```
FAILURE!
ErrorEvent {
  [Symbol(kTarget)]: WebSocket {
    _events: [Object: null prototype] { open: [Function], error: [Function] },
    _eventsCount: 2,
    _maxListeners: undefined,
    _binaryType: 'nodebuffer',
    _closeCode: 1006,
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: <Buffer >,
    _closeTimer: null,
    _errorEmitted: true,
    _extensions: {},
    _paused: false,
    _protocol: '',
    _readyState: 3,
    _receiver: null,
    _sender: null,
    _socket: null,
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    _autoPong: true,
    _url: 'ws://127.0.0.1:9221/',
    _originalIpc: false,
    _originalSecure: false,
    _originalHostOrSocketPath: '127.0.0.1:9221',
    _req: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      _header: 'GET / HTTP/1.1\r\n' +
        'User-Agent: Puppeteer 23.3.0\r\n' +
        'Sec-WebSocket-Version: 13\r\n' +
        'Sec-WebSocket-Key: 2CYm/7loiVuLX0+OkTSw0Q==\r\n' +
        'Connection: Upgrade\r\n' +
        'Upgrade: websocket\r\n' +
        'Host: 127.0.0.1:9221\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: undefined,
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/',
      _ended: false,
      res: [IncomingMessage],
      aborted: true,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: [HTTPParser],
      maxHeadersCount: null,
      reusedSocket: false,
      host: '127.0.0.1',
      protocol: 'http:',
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kChunkedBuffer)]: [],
      [Symbol(kChunkedLength)]: 0,
      [Symbol(kSocket)]: [Socket],
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 65536,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null,
      [Symbol(kAborted)]: true,
      [Symbol(kError)]: undefined
    },
    [Symbol(shapeMode)]: false,
    [Symbol(kCapture)]: false
  },
  [Symbol(kType)]: 'error',
  [Symbol(kError)]: Error: Unexpected server response: 200
      at ClientRequest.<anonymous> (/home/jupitersky/Projects/Puppet/node_modules/ws/lib/websocket.js:913:7)
      at ClientRequest.emit (node:events:520:28)
      at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:704:27)
      at HTTPParser.parserOnHeadersComplete (node:_http_common:118:17)
      at Socket.socketOnData (node:_http_client:546:22)
      at Socket.emit (node:events:520:28)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
      at Readable.push (node:internal/streams/readable:390:5)
      at TCP.onStreamRead (node:internal/stream_base_commons:191:23),
  [Symbol(kMessage)]: 'Unexpected server response: 200'
}
```

### Puppeteer version

23.3.0

### Node version

22.8.0

### Package manager

npm

### Package manager version

10.8.3

### Operating system

Linux

**Comment by OrKoN** [comment]
The correct URL for Firefox seems to be "ws://127.0.0.1:9222/session".  @whimboo do you know if we should somehow indicate it in the Firefox output?

**Comment by whimboo** [comment]
Port `9222` is the default port for the WebSocket but the user above used `--remote-debugging-port 9221` to set a custom port. This should be fine.

@JupiterSky11 could you please add the following custom user preference for Firefox to enable trace output? This would help to better diagnose what's wrong. I also don't know what `Error: Unexpected server response: 200` should mean given that `200` is usually the code for [`OK`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/200).

**Comment by OrKoN** [comment]
I used port 9222 locally, what I meant it the URL needs to include `/session` in order to work, so `ws://127.0.0.1:9221/session` would work here.

**Comment by whimboo** [comment]
We start the WebSocket on that given host and port, and `/session` is just the path were we listen for new session requests in BiDi only mode. What if at some point we add other top-level paths for other features? Then our output would be incorrect and we cannot change it anymore without causing clients to break.

**Comment by JupiterSky11** [comment]
Connecting to `/session` does the trick.  Unfortunately, it still seems to have some issue.  I can't find any documentation mentioning this.

Still the same code, but line 6 has been changed to include `/session` at the end of the string.
# Error
```
FAILURE!
 ProtocolError: Protocol error (browsingContext.getTree): unknown error TypeError: context is null #getBrowsingContextInfo@chrome://remote/content/webdriver-bidi/modules/root/browsingContext.sys.mjs:1750:7
getTree/contextsInfo<@chrome://remote/content/webdriver-bidi/modules/root/browsingContext.sys.mjs:737:42
getTree@chrome://remote/content/webdriver-bidi/modules/root/browsingContext.sys.mjs:736:35
handleCommand@chrome://remote/content/shared/messagehandler/MessageHandler.sys.mjs:255:33
execute@chrome://remote/content/shared/webdriver/Session.sys.mjs:390:32
onPacket@chrome://remote/content/webdriver-bidi/WebDriverBiDiConnection.sys.mjs:214:37
onMessage@chrome://remote/content/server/WebSocketTransport.sys.mjs:127:18
handleEvent@chrome://remote/content/server/WebSocketTransport.sys.mjs:109:14

    at <instance_members_initializer> (/home/jupitersky/Puppet/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:93:14)
    at new Callback (/home/jupitersky/Puppet/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:97:16)
    at CallbackRegistry.create (/home/jupitersky/Puppet/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:22:26)
    at BidiConnection.send (/home/jupitersky/Puppet/node_modules/puppeteer-core/lib/cjs/puppeteer/bidi/Connection.js:54:32)
    at Session.send (/home/jupitersky/Puppet/node_modules/puppeteer-core/lib/cjs/puppeteer/bidi/core/Session.js:137:42)
    at Session.<anonymous> (/home/jupitersky/Puppet/node_modules/puppeteer-core/lib/cjs/puppeteer/util/decorators.js:98:27)
    at #syncBrowsingContexts (/home/jupitersky/Puppet/node_modules/puppeteer-core/lib/cjs/puppeteer/bidi/core/Browser.js:163:59)
    at #initialize (/home/jupitersky/Puppet/node_modules/puppeteer-core/lib/cjs/puppeteer/bidi/core/Browser.js:143:45)
    at async Browser.from (/home/jupitersky/Puppet/node_modules/puppeteer-core/lib/cjs/puppeteer/bidi/core/Browser.js:118:13)
    at async #initialize (/home/jupitersky/Puppet/node_modules/puppeteer-core/lib/cjs/puppeteer/bidi/core/Session.js:95:28)
```

I'm not sure what the issue is, but it is mentioning chrome as opposed to firefox.  I haven't found any documentation detailing how I can change this behaviour with regard to the `.connect()` function.  If that is the problem, perhaps the intended browser can be set in `ConnectOptions`?

**Comment by OrKoN** [comment]
@JupiterSky11 could you provide the code you use since the original code snippet worked for me? `chrome://` is a valid scheme in Firefox that has nothing to do with the browser Chrome. Also, Firefox only supports a single WebDriver BiDi session unlike Chrome.

**Comment by JupiterSky11** [comment]
The following is what I used in my previous comment:
```import puppeteer, { ConnectOptions } from 'puppeteer';

async function main() {
    try {
        const cOps: ConnectOptions = {
            browserWSEndpoint: "ws://127.0.0.1:9221/session",
            protocol: "webDriverBiDi",
        }

        const browser = await puppeteer.connect(cOps);
        console.log("Connected!");

        await browser.disconnect();
        console.log("Disconnected!");
    } catch (e) {
        console.log("FAILURE!\n", e);
    }
}

main()
```

**Comment by OrKoN** [comment]
Interesting, that works for me:

```
~/src/pptr-test
❯ node firefoxConnect.mjs
Connected!
Disconnected!

~/src/pptr-test
❯ node firefoxConnect.mjs
Connected!
Disconnected!
```

```
# installed via 'npx @puppeteer/browsers@latest install firefox@stable'
/Users/alexrudenko/src/pptr-test/firefox/mac_arm-stable_130.0/Firefox.app/Contents/MacOS/firefox --remote-debugging-port=9222
```

(although I am on Mac)

**Comment by whimboo** [comment]
@JupiterSky11 are you trying to connect to a Firefox instance that maybe has some unloaded tabs? Note that when Firefox is restarted only the currently selected tab and pinned tabs are restored. Those kind of tabs aren't supported at the moment and there is this bug to add support for it: https://bugzilla.mozilla.org/show_bug.cgi?id=1876240.

Workaround would be to click through all the tabs to let those get loaded.

I assume that when connected Puppeteer automatically tries to retrieve all the available navigables.

**Comment by JupiterSky11** [comment]
@whimboo that's exactly what it is.  Thank you both for helping and sharing your knowledge!

**Comment by whimboo** [comment]
That's good to hear! If you find other issues please let us know as well! Thanks in advance.

**Comment by saadchellah** [comment]
page.authenticate() seems no working in Firefox , the authenticate event isn't being triggered properly
