### ISSUE TITLE
Error: Protocol error (Network.enable): Target closed.

### ISSUE THREAD

**Issue by VinceG** [puppeteer/puppeteer#1310]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: puppeteer@0.12.0
* Platform / OS version:  CentOS Linux release 7.2.1511 (Core)

**What steps will reproduce the problem?**

This was written while working on a Mac then when we tried to run this on a server running CentOS the below exception is thrown. I've went ahead and read and tried numerous things including installing the suggested packages reading through the github issues i wasn't able to find a solution to this issue.

At first i got a different error message 

```
/var/www/xxx/node_modules/puppeteer/.local-chromium/linux-508693/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
```

that was fixed after i installed the recommended dependencies and packages but now it throws a new error shown below.

```
(async () => {
    logger.info('launching puppeteer');
    
    const browser = await puppeteer.launch({
        timeout: 240000,
        args: ['--no-sandbox','--disable-setuid-sandbox'],
        ignoreHTTPSErrors: true
    });

    ...
    ...
    ...

    await browser.close();
})();
```

**What is the expected result?**

successful launch 

**What happens instead?**

```
2017-11-07T19:34:32.172Z info: launching puppeteer
Error: Protocol error (Network.enable): Target closed.
    at Session._onClosed (/var/www/xxx/node_modules/puppeteer/lib/Connection.js:209:23)
    at Connection._onClose (/var/www/xxx/node_modules/puppeteer/lib/Connection.js:116:15)
    at emitTwo (events.js:125:13)
    at WebSocket.emit (events.js:213:7)
    at WebSocket.emitClose (/var/www/xxx/node_modules/puppeteer/node_modules/ws/lib/WebSocket.js:213:10)
    at _receiver.cleanup (/var/www/xxx/node_modules/puppeteer/node_modules/ws/lib/WebSocket.js:195:41)
    at Receiver.cleanup (/var/www/xxx/node_modules/puppeteer/node_modules/ws/lib/Receiver.js:520:15)
    at WebSocket.finalize (/var/www/xxx/node_modules/puppeteer/node_modules/ws/lib/WebSocket.js:195:22)
    at emitNone (events.js:110:20)
    at Socket.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by aslushnikov** [comment]
@VinceG this looks like a memory issue. Aren't you running in a docker?

**Comment by VinceG** [comment]
@aslushnikov  It's not a docker it's a Linode server running CentOS.

**Comment by zhangyy62** [comment]
I meet this same question in CentOS7....

**Comment by zhangyy62** [comment]
@VinceG  I solve this question. I updated nss newest.
![1](https://user-images.githubusercontent.com/4017852/32600865-ec4c20a4-c57b-11e7-9383-a081f0c33574.png)

**Comment by andy2046** [comment]
@VinceG can you run `df -Th /dev/shm` to check shm, i fixed `target closed` issue by adding more shm, https://github.com/c0b/chrome-in-docker/issues/1

**Comment by VinceG** [comment]
@sparkxxxxxx Thank You! that did it. we had NSS installed but not the latest version. once i upgraded Chrome worked just fine.


@andy2046 Thank you for the suggestion the /dev/shm returned this

```
Filesystem     Type   Size  Used Avail Use% Mounted on
tmpfs          tmpfs   24G     0   24G   0% /dev/shm
```

**Comment by VinceG** [comment]
@aslushnikov Might worth noting this somewhere was well. For CentOS. This issue is now resolved.
