### ISSUE TITLE
Error: Generator is already running

### ISSUE THREAD

**Issue by davidbeers** [puppeteer/puppeteer#1322]
As our app is currently running on node 6, I've converted one of puppeteer's node 8 async/await examples to use promises like this:

~~~~
function generateScreenshot() {
    let instances = {};
    return puppeteer.launch()
        .then(browser => {
            instances.browser = browser;
            return browser.newPage();
        })
        .then((page) => {
            instances.page = page;
            return page.goto('https://example.com');
        })
        .catch(err => {
            log.error("Error on goto: " + util.inspect(err));
        })
        .then(() => {
            return instances.page.screenshot({path: 'example.png'});
        })
        .catch(err => {
            log.error("Error on screenshot: " + util.inspect(err));
            return 'error';
        })
        .then((err) => {
            instances.browser.close();
            let status = !!err;
            return P.resolve({ success: status });
        });
}
~~~~
On the call to page.screenshot() I get the following error:
~~~~
2017-11-08T16:36:12.375Z - error: Error on screenshot: TypeError: Generator is already running
    at next (native)
    at step (/home/david/Development/link-live-4/worker/node_modules/puppeteer/node6/Page.js:1514:24)
    at Promise.resolve.then.value (/home/david/Development/link-live-4/worker/node_modules/puppeteer/node6/Page.js:1525:15)
    at wrapped (/home/david/Development/link-live-4/api/node_modules/newrelic/lib/transaction/tracer/index.js:184:28)
    at wrappedPromise.linkTransaction (/home/david/Development/link-live-4/api/node_modules/newrelic/lib/instrumentation/promise.js:295:65)
    at wrappedPromise.wrapped (/home/david/Development/link-live-4/api/node_modules/newrelic/lib/transaction/tracer/index.js:184:28)
    at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:135:7)
~~~~

I've also seen the same error on calls to page.goto().

If I catch every step in the promise chain and swallow the "Generator already running" errors, the chain can complete and I do get the expected screenshot, so the errors appear to be spurious. But having to swallow spurious errors means writing complicated code to handle real ones correctly. That's not really satisfactory.

I'm running puppeteer 0.12.0 in node 6.11.2 on Ubuntu 14.04 LTS.

**Comment by aslushnikov** [comment]
@davidbeers Do you have a script that we can run locally to reproduce this issue?

**Comment by mortiy** [comment]
I'm having the same issue with `puppeteer-1.3.2`:
```
TypeError: Generator is already running
    at next (native)
    at step (.../node_modules/puppeteer/node6/lib/Page.js:214:24)
    at Promise.resolve.then.value (.../node_modules/puppeteer/node6/lib/Page.js:225:15)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```
