### ISSUE TITLE
[Bug]: Target.setAutoAttach timed out.

### ISSUE THREAD

**Issue by beograde** [puppeteer/puppeteer#13234]
### Minimal, reproducible example

```TypeScript
const puppeteer = require("puppeteer");
const axios = require("axios");
const OCTO_REMOTE_API = axios.create({
  baseURL: "https://app.octobrowser.net/api/v2/automation/",
  timeout: 2000,
  headers: {
    "X-Octo-Api-Token": "API_TOKEN", //Put Token here
  },
});
const OCTO_LOCAL_API = axios.create({
  baseURL: "http://127.0.0.1:58888/api/profiles/",
  timeout: 100000,
});
async function createProfile() {
  return OCTO_REMOTE_API.post(`/profiles`, {
    title: "API Test profile",
    fingerprint: {
      os: "win",
    },
  })
    .then((response) => response.data)
    .catch((error) => (error.response ? error.response.data : null));
}
async function startProfile(uuid) {
  return OCTO_LOCAL_API.post("/start", {
    uuid: uuid,
    headless: true,
    debug_port: true,
  })
    .then((response) => response.data)
    .catch((error) => (error.response ? error.response.data : null));
}
(async () => {
  const response = await createProfile();
  console.log("response", response);
  const profile_uuid = response.data.uuid;
  const start_response = await startProfile(profile_uuid);
  const ws_endpoint = start_response.ws_endpoint;
  const browser = await puppeteer.connect({
    browserWSEndpoint: ws_endpoint,
    defaultViewport: null,
  });
  console.log("browser", browser.debugInfo);
  const page = await browser.newPage();
  await page.goto("https://google.com/");
})();
```

### Background

I've been trying to connect Puppeteer to OctoBrowser in Node.js for automation
https://documenter.getpostman.com/view/1801428/UVC6i6eA#36440a21-6ec4-4a02-a908-9e13e9562e31

### Expectation

I expected new browser is opened and going to google.

### Reality

Nothing happened. Even new browser wasn't opened. And I got following error via puppeteer dubugInfo.
`
Error: Target.setAutoAttach timed out. Trace: ProtocolError
        at <instance_members_initializer> (F:\NIKE\Projects\Guru\testing\node_modules\puppeteer-core\lib\cjs\puppeteer\common\CallbackRegistry.js:94:14)
        at new Callback (F:\NIKE\Projects\Guru\testing\node_modules\puppeteer-core\lib\cjs\puppeteer\common\CallbackRegistry.js:98:16)
        at CallbackRegistry.create (F:\NIKE\Projects\Guru\testing\node_modules\puppeteer-core\lib\cjs\puppeteer\common\CallbackRegistry.js:23:26)
        at Connection._rawSend (F:\NIKE\Projects\Guru\testing\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\Connection.js:90:26)
        at CdpCDPSession.send (F:\NIKE\Projects\Guru\testing\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\CDPSession.js:66:33)
        at #onAttachedToTarget (F:\NIKE\Projects\Guru\testing\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\ChromeTargetManager.js:280:21)
        at listener (F:\NIKE\Projects\Guru\testing\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\ChromeTargetManager.js:126:42)
        at F:\NIKE\Projects\Guru\testing\node_modules\puppeteer-core\lib\cjs\third_party\mitt\mitt.js:62:7
        at Array.map (<anonymous>)
        at Object.emit (F:\NIKE\Projects\Guru\testing\node_modules\puppeteer-core\lib\cjs\third_party\mitt\mitt.js:61:20)
        at CallbackRegistry.getPendingProtocolErrors (F:\NIKE\Projects\Guru\testing\node_modules\puppeteer-core\lib\cjs\puppeteer\common\CallbackRegistry.js:83:25)
        at CdpCDPSession.getPendingProtocolErrors (F:\NIKE\Projects\Guru\testing\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\CDPSession.js:115:32)
        at Connection.getPendingProtocolErrors (F:\NIKE\Projects\Guru\testing\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\Connection.js:214:36)
        at get debugInfo [as debugInfo] (F:\NIKE\Projects\Guru\testing\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\Browser.js:242:53)
        at F:\NIKE\Projects\Guru\testing\index.js:43:34
        ...
`

### Puppeteer version

^23.6.0

### Node version

v18.20.3

### Package manager

npm

### Package manager version

10.8.1

### Operating system

Windows

**Comment by OrKoN** [comment]
I suggest that you reach out to the Octobrowser support. Puppeteer requires https://chromedevtools.github.io/devtools-protocol/tot/Target/#method-setAutoAttach which is generally available for a long time in Chrome for Testing. I am not sure what browser is run by the Octobrowser.
