### ISSUE TITLE
[Bug]: Can't navigate to Youtube.com inside Docker

### ISSUE THREAD

**Issue by GDTNguyen** [puppeteer/puppeteer#13237]
### Minimal, reproducible example

```TypeScript
import puppeteer from "puppeteer";

export async function runPuppeteer() {
	try {
		const url = "https://www.youtube.com/watch?v=2OdYv8YKSaI";

		const browser = await puppeteer.launch({
			args: [
				"--no-sandbox", // Bypass OS security model
				"--disable-setuid-sandbox",
				"--disable-gpu", // Disable GPU hardware acceleration
				"--window-size=1920,1080", // Set the window size
				"--enable-features=NetworkService", // Optional: enhance network features
				"--start-maximized", // Start maximized (if you want to see it full-screen)
			],
			headless: false,
		});

		const page = await browser.newPage();
		await page.setUserAgent(
			"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
		);

		await page.setExtraHTTPHeaders({
			"Accept-Language": "en-US,en;q=0.9",
		});

		await page.goto(url, {
			waitUntil: "networkidle2",
			timeout: 60000,
		});

		await browser.close();

		console.log("done");
	} catch (error) {
		console.log(`Error in runPuppeteer`, error);
	}
}
```

### Background

I'm setting up a project to track/scrape the number of comments and views on a selected youtube videos/channels without using youtube quota.

### Expectation

I should be able to check out this YouTube link: https://www.youtube.com/watch?v=2OdYv8YKSaI, wait for the whole page to load, and then grab the views, comments, and likes. I can do it fine on my local machine, but it doesn't work in Docker.

### Reality

When I go to https://www.youtube.com/watch?v=2OdYv8YKSaI in headless mode, it times out. 

So I set up RealVNC to see what's going on in our Docker setup, and it basically visits the page but stops loading before hitting the timeout limit. I can check out the page using RealVNC, but it just stops loading after hitting the link.

Image of where it gets stuck is below:
![Screenshot 2024-10-26 at 15 03 53](https://github.com/user-attachments/assets/8d53a27b-873e-4457-a3bf-26604e85e340)

### Puppeteer configuration file (if used)

```TypeScript
# Stage 1: Build Next.js application
FROM node:20.17.0 AS builder

# Set working directory
WORKDIR /app

# Install dependencies
COPY package.json ./
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the Next.js application (creates the production build in the .next folder)
RUN npm run build



# Final lightweight production environment
FROM --platform=linux/amd64 node:20.17.0 AS runner

# Install Chrome with dependencies as root.
USER root

# Set working directory
WORKDIR /app

# Copy the production build from the builder stage, overwriting any matching files
COPY --from=builder /app /app/

# Install system dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    apt-utils locales \
    dbus \
    dbus-x11 \
    libnss3 \
    libnss3-tools \
    libxss1 \
    libatk-bridge2.0-0 \
    libgtk-3-0 \
    libgbm-dev \
    libasound2 \
    libx11-xcb1 \
    libxcomposite1 \
    libxcursor1 \
    libxi6 \
    libxrandr2 \
    libxshmfence1 \
    libvulkan1 \
    xdg-utils \
    ffmpeg \
    libavcodec-extra \
    xvfb \
    x11-utils \
    libjpeg62-turbo \
    libglib2.0-0 \
    libgdk-pixbuf2.0-0 \
    libgconf-2-4 \
    libatspi2.0-0 \
    libpangocairo-1.0-0 \
    libpango1.0-0 \
    libcups2 \
    libxrender1 \
    libxtst6 \
    iputils-ping \
    libgtk-3-dev \
    libnss3-dev \
    libnspr4 \
    libasound2-dev \
    libpulse0 \
    socat \
    x11vnc \
    fluxbox \
    xterm \
    xorg \
    gdm3 \
    openbox \
    libpipeline1 \
    xinit 

# for https
RUN apt-get update && \
    apt-get install -yyq ca-certificates

# install libraries
RUN apt-get update && \
    apt-get install -yyq \
    libappindicator1 \
    libasound2 \
    libatk1.0-0 \
    libc6 \
    libcairo2 \
    libcups2 \
    libdbus-1-3 \
    libexpat1 \
    libfontconfig1 \
    libgcc1 \
    libgconf-2-4 \
    libgdk-pixbuf2.0-0 \
    libglib2.0-0 \
    libgtk-3-0 \
    libnspr4 \
    libnss3 \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libstdc++6 \
    libx11-6 \
    libx11-xcb1 \
    libxcb1 \
    libxcomposite1 \
    libxcursor1 \
    libxdamage1 \
    libxext6 \
    libxfixes3 \
    libxi6 \
    libxrandr2 \
    libxrender1 \
    libxss1 \
    libxtst6

# tools
RUN apt-get update && \
    apt-get install -yyq gconf-service lsb-release wget xdg-utils

# Install latest chrome dev package and fonts to support major charsets (Chinese, Japanese, Arabic, Hebrew, Thai and a few others)
RUN apt-get update \
    && apt-get install -y wget gnupg \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*


# Configure default locale (important for chrome-headless-shell).
ENV LANG=en_US.UTF-8
ENV PUPPETEER_SKIP_DOWNLOAD=false
ENV DBUS_SESSION_BUS_ADDRESS=autolaunch:

# Install Puppeteer and other dependencies
RUN npm init -y && \
    npm install puppeteer puppeteer-cluster && \
    mkdir -p /root/Downloads && \
    chown -R root:root /app/node_modules && \
    chown -R root:root /app/package.json && \
    chown -R root:root /app/package-lock.json

# Install chromium
RUN npx puppeteer browsers install chrome --install-deps

# Generate THIRD_PARTY_NOTICES using chrome --credits.
RUN node -e "require('child_process').execSync(require('puppeteer').executablePath() + ' --credits', {stdio: 'inherit'})" > THIRD_PARTY_NOTICES

# Set the environment variable for display
ENV DISPLAY=:99

# Expose the port for Puppeteer (optional, if you're using a web proxy)
ENV PORT=9222
ENV PORT_INTERNAL=9992

###################################

EXPOSE 3001 8080 5900

# Command to start the Next.js application in production mode
CMD ["sh", "-c", "Xvfb :99 -screen 0 1920x1080x16 & \
                  x11vnc -ncache 1 -ncache_cr -display :99 -nopw -forever & \
                  fluxbox & \
                  npm run dev -- -p 3001"]
```

### Puppeteer version

23.6.0

### Node version

20.17.0

### Package manager

npm

### Package manager version

10.8.2

### Operating system

macOS

**Comment by OrKoN** [comment]
Could you provide the browser log (dumpio:true in launch), CDP logs https://pptr.dev/guides/debugging#log-devtools-protocol-traffic and see if there are any page errors by subscribing to the console, error and pageerror events on the page? Does your Docker image run locally or on the server?

**Comment by GDTNguyen** [comment]
Thanks for the response @OrKoN. Our docker image is running locally, once we get it working we want to deploy multiple images to a cluster.

We added debugging statements to puppeteer.

```
const browser = await puppeteer.launch({
        args: [
	        "--no-sandbox", // Bypass OS security model
	        "--disable-setuid-sandbox",
	        "--disable-gpu", // Disable GPU hardware acceleration
	        "--window-size=1920,1080", // Set the window size
	        "--enable-features=NetworkService", // Optional: enhance network features
	        "--start-maximized", // Start maximized (if you want to see it full-screen)
        ],
        dumpio: true,
        headless: false,
})

page.on("console", (msg) => console.log("PAGE LOG:", msg.text()));
page.on("error", (error) => console.error("ERROR:", error));
page.on("pageerror", (pageError) => console.error("PAGE ERROR:", pageError.message));
```

Below are the logs after adding debugging statements to puppeteer.

```

2024-10-27 00:21:34  ○ Compiling /api/smoketest ...
2024-10-27 00:21:34  ✓ Compiled /api/smoketest in 834ms (64 modules)
2024-10-27 00:21:36 
2024-10-27 00:21:36 DevTools listening on ws://127.0.0.1:40193/devtools/browser/c203faf7-f7d3-4cd9-af75-5f25bbd82f5f
2024-10-27 00:21:37 Error: unrecognized flag --enable-external-memory-accounted-in-global-limit
2024-10-27 00:21:37 Try --help for options
2024-10-27 00:21:37 Error: unrecognized flag --enable-external-memory-accounted-in-global-limit
2024-10-27 00:21:37 Try --help for options
2024-10-27 00:21:37 Error: unrecognized flag --enable-external-memory-accounted-in-global-limit
2024-10-27 00:21:37 Try --help for options
2024-10-27 00:21:38 Error: unrecognized flag --enable-external-memory-accounted-in-global-limit
2024-10-27 00:21:38 Try --help for options
2024-10-27 00:21:40 Error: unrecognized flag --enable-external-memory-accounted-in-global-limit
2024-10-27 00:21:40 Try --help for options
2024-10-27 00:21:40 PAGE LOG: LegacyDataMixin will be applied to all legacy elements.
2024-10-27 00:21:40 Set `_legacyUndefinedCheck: true` on element class to enable.
2024-10-27 00:21:40 PAGE LOG: Permissions policy violation: unload is not allowed in this document.
2024-10-27 00:22:37 Error in runPuppeteer TimeoutError: Navigation timeout of 60000 ms exceeded
2024-10-27 00:22:37     at new Deferred (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/util/Deferred.js:56:34)
2024-10-27 00:22:37     at Deferred.create (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/util/Deferred.js:18:16)
2024-10-27 00:22:37     at new LifecycleWatcher (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/LifecycleWatcher.js:66:46)
2024-10-27 00:22:37     at CdpFrame.goto (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Frame.js:146:29)
2024-10-27 00:22:37     at CdpFrame.<anonymous> (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/util/decorators.js:96:27)
2024-10-27 00:22:37     at CdpPage.goto (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/api/Page.js:565:43)
2024-10-27 00:22:37     at runPuppeteer (webpack-internal:///(api)/./pages/api/smoketest.js:38:20)
2024-10-27 00:22:37     at async handler (webpack-internal:///(api)/./pages/api/smoketest.js:50:9)
2024-10-27 00:22:37     at async K (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.dev.js:21:2871)
2024-10-27 00:22:37     at async U.render (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.dev.js:21:3955)
2024-10-27 00:22:37     at async DevServer.runApi (/app/node_modules/next/dist/server/next-server.js:598:9)
2024-10-27 00:22:37     at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/next/dist/server/next-server.js:269:37)
2024-10-27 00:22:37     at async DevServer.handleRequestImpl (/app/node_modules/next/dist/server/base-server.js:817:17)
2024-10-27 00:22:37     at async /app/node_modules/next/dist/server/dev/next-dev-server.js:339:20
2024-10-27 00:22:37     at async Span.traceAsyncFn (/app/node_modules/next/dist/trace/trace.js:154:20)
2024-10-27 00:22:37  GET /api/smoketest 200 in 64155ms


```


What could be happening?

**Comment by OrKoN** [comment]
It is possible that the site detects automation and blocks loading. So far I do not see any unexpected behavior from the puppeteer site, the page never finishes loading so the navigation times out. I am not sure why you enable NetworkService but perhaps you could try without it as this is not the feature Puppeteer enabled by default. If you have not included the CDP log and that might contain some hints.
