### ISSUE TITLE
DEP0018 DeprecationWarning, Trying the second example in the README.md puppeteer process starts but won't exit on Windows 10 x64

### ISSUE THREAD

**Issue by vl4dt** [puppeteer/puppeteer#1324]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: v0.12.0
* Platform / OS version: Windows 10 Pro 64-bit (10.0, Build 15063)
* URLs (if applicable): https://news.ycombinator.com
* Node version: v8.9.1 64-bit

**What steps will reproduce the problem?**
Copy and paste the second example at:
https://github.com/GoogleChrome/puppeteer

_Please include code that reproduces the issue._

```javascript
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://example.com');

  // Get the "viewport" of the page, as reported by the page.
  const dimensions = await page.evaluate(() => {
    return {
      width: document.documentElement.clientWidth,
      height: document.documentElement.clientHeight,
      deviceScaleFactor: window.devicePixelRatio
    };
  });

  console.log('Dimensions:', dimensions);

  await browser.close();
})();
```

**What is the expected result?**
Produce a PDF file

**What happens instead?**
The console prints the following message:
```bash
(node:26572) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): AssertionError [ERR_ASSERTION]: Unknown value for options.waitUntil: networkidle2
(node:26572) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by vsemozhetbyt** [comment]
Please, recheck your puppeteer version: there is no v1.3.2 yet. `networkidle2` is available from the v0.13.0-alpha. You can upgrade with `npm install https://github.com/GoogleChrome/puppeteer/`.

**Comment by vl4dt** [comment]
Indeed, my bad, copied it incorrect, the actual version is 0.12.0, installed it yesterday, updated the first comment with the correct one.

**Comment by ebidel** [comment]
@vl4dt this is likely what @vsemozhetbyt mentioned...but I don't see "networkidle2" in your code. Is that still an accurate snippet?

**Comment by ruslankonev** [comment]
Maybe same with this example code from [#getting-started](https://github.com/GoogleChrome/puppeteer#getting-started):

```
;(async () => {
  const browser = await puppeteer.launch()
  const page = await browser.newPage()
  await page.goto(path, { waitUntil: 'networkidle2' })
  await page.pdf({ format: 'A4', path: `${App.STORE_PATH}/${filename}` })

  await browser.close()
})()
```

I have the next stack trace: 

```
(node:83669) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): 
AssertionError [ERR_ASSERTION]: Unknown value for options.waitUntil: networkidle2
```

Detailed stack trace:

```
e { AssertionError [ERR_ASSERTION]: Unknown value for options.waitUntil: networkidle2
    at Console.assert (console.js:188:23)
    at new NavigatorWatcher (/Users/ruslankonev/projects/pdf-generator/node_modules/puppeteer/lib/NavigatorWatcher.js:32:13)
    at Page.goto (/Users/ruslankonev/projects/pdf-generator/node_modules/puppeteer/lib/Page.js:451:21)
    at /Users/ruslankonev/projects/pdf-generator/components/docs/route-handlers.js:410:22
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' } {"generatedMessage":false,"name":"AssertionError [ERR_ASSERTION]","code":"ERR_ASSERTION","actual":false,"expected":true,"operator":"=="}
```

And with other `waitUntil` options (`networkidle0`,`domcontentloaded`), I always have the same error. Why?:

```
e { AssertionError [ERR_ASSERTION]: Unknown value for options.waitUntil: networkidle0
    at Console.assert (console.js:188:23)
    at new NavigatorWatcher (/Users/ruslankonev/projects/pdf-generator/node_modules/puppeteer/lib/NavigatorWatcher.js:32:13)
    at Page.goto (/Users/ruslankonev/projects/pdf-generator/node_modules/puppeteer/lib/Page.js:451:21)
    at /Users/ruslankonev/projects/pdf-generator/components/docs/route-handlers.js:410:22
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' } {"generatedMessage":false,"name":"AssertionError [ERR_ASSERTION]","code":"ERR_ASSERTION","actual":false,"expected":true,"operator":"=="}
```
---
And the answer is next string in my use case (`lib/NavigatorWatcher.js:32:13`):
![image](https://user-images.githubusercontent.com/2588730/32652285-cf9f8812-c614-11e7-9c0c-9ab676a336ca.png)

Code will work only with `load` & `networkidle` values.

**Comment by vl4dt** [comment]
Update:
Updated today to puppeteer@0.13.0-alpha and it worked perfectly, no errors or warnings, very nice 👍
