### ISSUE TITLE
"[screenshot.spec] Screenshots ElementHandle.screenshot should run in parallel with page.close()" is flaky with Firefox

### ISSUE THREAD

**Issue by OrKoN** [puppeteer/puppeteer#13360]
See https://github.com/puppeteer/puppeteer/actions/runs/12157249591/job/33902654440#step:11:807

```
29) Screenshots
       ElementHandle.screenshot
         should run in parallel with page.close():
     ProtocolError: Protocol error (browsingContext.create): unknown error TypeError: webProgress.browsingContext.currentWindowGlobal is null _sendCommandToBrowsingContext@chrome://remote/content/shared/messagehandler/transports/RootTransport.sys.mjs:132:9

      at Callback.<instance_members_initializer> (packages\puppeteer-core\src\common\CallbackRegistry.ts:125:12)
      at new Callback (packages\puppeteer-core\src\common\CallbackRegistry.ts:130:3)
      at CallbackRegistry.create (packages\puppeteer-core\src\common\CallbackRegistry.ts:28:22)
      at BidiConnection.send (packages\puppeteer-core\src\bidi\Connection.ts:105:28)
      at Session.send (packages\puppeteer-core\src\bidi\core\Session.ts:111:34)
      at Session.<anonymous> (packages\puppeteer-core\src\util\decorators.ts:63:21)
      at UserContext.createBrowsingContext (packages\puppeteer-core\src\bidi\core\UserContext.ts:146:29)
      at UserContext.<anonymous> (packages\puppeteer-core\src\util\decorators.ts:63:21)
      at BidiBrowserContext.newPage (packages\puppeteer-core\src\bidi\BrowserContext.ts:189:44)
      at Context.<anonymous> (test\src\screenshot.spec.ts:441:21)
```

In Nightly, it is flaky in the same test but with a different error message:

```
ProtocolError: Protocol error (browsingContext.create): no such frame DiscardedBrowsingContextError: BrowsingContext does no longer exist RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
MessageHandlerError@chrome://remote/content/shared/messagehandler/Errors.sys.mjs:14:5
DiscardedBrowsingContextError@chrome://remote/content/shared/messagehandler/Errors.sys.mjs:76:5
waitForCurrentWindowGlobal@chrome://remote/content/shared/messagehandler/transports/BrowsingContextUtils.sys.mjs:132:11

      at Callback.<instance_members_initializer> (packages\puppeteer-core\src\common\CallbackRegistry.ts:125:12)
      at new Callback (packages\puppeteer-core\src\common\CallbackRegistry.ts:130:3)
      at CallbackRegistry.create (packages\puppeteer-core\src\common\CallbackRegistry.ts:28:22)
      at BidiConnection.send (packages\puppeteer-core\src\bidi\Connection.ts:105:28)
      at Session.send (packages\puppeteer-core\src\bidi\core\Session.ts:111:34)
      at Session.<anonymous> (packages\puppeteer-core\src\util\decorators.ts:63:21)
      at UserContext.createBrowsingContext (packages\puppeteer-core\src\bidi\core\UserContext.ts:146:29)
      at UserContext.<anonymous> (packages\puppeteer-core\src\util\decorators.ts:63:21)
      at BidiBrowserContext.newPage (packages\puppeteer-core\src\bidi\BrowserContext.ts:189:44)
      at Context.<anonymous> (test\src\screenshot.spec.ts:441:21)
```

**Comment by Lightning00Blade** [comment]
CC @whimboo

**Comment by whimboo** [comment]
There is now https://bugzilla.mozilla.org/show_bug.cgi?id=1935104 on file for it.
