### ISSUE TITLE
[Bug]: docker puppeteer:23.11.1

### ISSUE THREAD

**Issue by sysmat** [puppeteer/puppeteer#13432]
### Minimal, reproducible example

```TypeScript
- gitlab CI using `ghcr.io/puppeteer/puppeteer:23.11.1` image 
- in package.json I have `"puppeteer": "^23.11.1"`
- when installing `npm i` I have arror


npm error code EACCES
npm error syscall mkdir
npm error path /builds/portal-hub/angular-portal-libs/node_modules/vite/node_modules/@esbuild/aix-ppc64
npm error errno -13
npm error Error: EACCES: permission denied, mkdir '/builds/portal-hub/angular-portal-libs/node_modules/vite/node_modules/@esbuild/aix-ppc64'
npm error     at async mkdir (node:internal/fs/promises:857:10)
npm error     at async /usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:624:20
npm error     at async Promise.allSettled (index 0)
npm error     at async [reifyPackages] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:325:11)
npm error     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:142:5)
npm error     at async Install.exec (/usr/local/lib/node_modules/npm/lib/commands/install.js:150:5)
npm error     at async Npm.exec (/usr/local/lib/node_modules/npm/lib/npm.js:207:9)
npm error     at async module.exports (/usr/local/lib/node_modules/npm/lib/cli/entry.js:74:5) {
npm error   errno: -13,
npm error   code: 'EACCES',
npm error   syscall: 'mkdir',
npm error   path: '/builds/portal-hub/angular-portal-libs/node_modules/vite/node_modules/@esbuild/aix-ppc64'
npm error }
```

- the same error if I use `ghcr.io/puppeteer/puppeteer:latest`
```


### Background

_No response_

### Expectation

it was working with `ghcr.io/puppeteer/puppeteer:latest` and  puppeteer-v23.10.4

### Reality

npm could not install 

### Puppeteer configuration file (if used)

_No response_

### Puppeteer version

23.11.1

### Node version

22.12.0

### Package manager

npm

### Package manager version

10.9.0

### Operating system

Linux

**Comment by sysmat** [comment]
```
npm error path /builds/myprojcet/frontend/node_modules/puppeteer
npm error command failed
npm error command sh -c node install.mjs
```

**Comment by sysmat** [comment]
```
npm error path /builds/myprojcet/frontend/node_modules/chromium-bidi
npm error dest /builds/myprojcet/frontend/node_modules/.chromium-bidi-ZoohmUHZ
npm error errno -13
npm error Error: EACCES: permission denied, rename '/builds/myprojcet/frontend/node_modules/chromium-bidi' -> '/builds/myprojcet/frontend/node_modules/.chromium-bidi-ZoohmUHZ'
npm error     at async Object.rename (node:internal/fs/promises:783:10)
npm error     at async moveFile (/usr/local/lib/node_modules/npm/node_modules/@npmcli/fs/lib/move-file.js:30:5)
npm error     at async Promise.allSettled (index 0)
npm error     at async [reifyPackages] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:325:11)
npm error     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:[142]
npm error     at async Install.exec (/usr/local/lib/node_modules/npm/lib/commands/install.js:150:5)
npm error     at async Npm.exec (/usr/local/lib/node_modules/npm/lib/npm.js:207:9)
npm error     at async module.exports (/usr/local/lib/node_modules/npm/lib/cli/entry.js:74:5) {
npm error   errno: -13,
npm error   code: 'EACCES',
npm error   syscall: 'rename',
npm error   path: '/builds/myprojcet/frontend/node_modules/chromium-bidi',
npm error   dest: '/builds/myprojcet/frontend/node_modules/.chromium-bidi-ZoohmUHZ'
npm error }
npm error
```

**Comment by OrKoN** [comment]
That looks like a permission issue in your project. Please make sure you change the permissions or run everything as the pptruser https://github.com/puppeteer/puppeteer/blob/main/docker/Dockerfile#L38 The docker image test file passes for that version without any issues https://github.com/puppeteer/puppeteer/actions/runs/12410684039/job/34646832889

**Comment by sysmat** [comment]
- ok, I figure it out what is problem
- we have multi stage CI and we have CI cache for node modules
- first stage we build with official docker node which is running as root
- second stage we do test and we are using docker puppeteer(and for some reason tody stopped working with error from above)
