### ISSUE TITLE
Google OAuth Sign in w/ targetcreated

### ISSUE THREAD

**Issue by michaelryancaputo** [puppeteer/puppeteer#1374]
Previous issue: #1264

### Steps to reproduce
Running a test that needs to access context of modal window for Google OAuth login seems to try and enter email multiple times.

Here is my test file. I am using Jest to run the test.

```
let browser,
  page,
  count = 0;

beforeEach(async () => {
  browser = await puppeteer.launch({
    headless: false,
    args: ['--no-sandbox', '--disable-popup-blocking'],
  });
  page = await browser.newPage();
  await page.goto('http://localhost:8001');
});

afterEach(async () => {
  await page.close();
  console.log('🎉');
});

describe('/ (Home Page)', () => {
  it(
    'Should log in',
    async () => {
      console.log('log in');
      await page.click('#t-login_button');

      await browser.on('targetcreated', async () => {
        const pageList = await browser.pages();
        const newPage = await pageList[pageList.length - 1];
        const newPageTitle = await newPage.title();
        console.log(newPageTitle);
        if (newPageTitle === `Sign in - Google Accounts` && count === 0) {
          count = ++count;
          await newPage.waitForSelector(`#identifierId`);
          console.log(email_login);
          await newPage.type(`#identifierId`, email_login);
          await newPage.click('#identifierNext');

          await newPage.waitForSelector(`#password input[type="password"]`);
          await newPage.type(`#password input[type="password"]`, login_password);
          await newPage.click('#passwordNext');
        }
      });

      await page.goto(TESTING_BASE);
      await page.waitForSelector(`#t-login_button`);

      await page.waitForSelector(`#t-createStudy`);
    },
    10000,
  );
});
```

For some reason the console shows that the modal window is opened multiple times. You can see that i'm trying to debug the issue and limiting it to entering the login/password once. However if I do not have the check for the page title and counter, it will enter the email address more than one time (some times 3x in a row). Here is the console log from running this:

```
  console.log src/__test__/puppeteer.test.js:36
    log in

  console.log src/__test__/puppeteer.test.js:43
    Sign in - Google Accounts

  console.log src/__test__/puppeteer.test.js:47
    selenium_user@evidation.com

  console.log src/__test__/puppeteer.test.js:43
    Sign in - Google Accounts

  console.log src/__test__/puppeteer.test.js:43
    Sign in - Google Accounts

 FAIL  src/__test__/puppeteer.test.js (16.938s)
  / (Home Page)
    ✓ Title == Achievement Study Manager (2163ms)
    ✕ Should log in (13939ms)

  ● / (Home Page) › Should log in

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

      at node_modules/jest-config/node_modules/jest-jasmine2/build/queue_runner.js:64:21
      at ontimeout (timers.js:365:14)
      at tryOnTimeout (timers.js:237:5)
      at Timer.listOnTimeout (timers.js:207:5)
```

**Tell us about your environment:**

* Puppeteer version: 0.13.0
* Platform / OS version: Mac OS High Sierra
* URLs (if applicable): Can no provide

**What steps will reproduce the problem?**

described above.

**What is the expected result?**

I should be able to interact with the new page pop up and log my user in.

**What happens instead?**

I am unable to log the user in because for some reason the `targetcreated` is firing multiple times.

**Comment by MACSkeptic** [comment]
```
  await browser.on('targetcreated', async () => {
```

does browser.on actually return a promise?


i'm guessing your code opens the login popup multiple times because that is _not_ a promise and then it immediately runs

```
 await page.goto(TESTING_BASE);
      await page.waitForSelector(`#t-login_button`);
```

in parallel with the event handler, which clicks on login again (hence the even handler is called multiple times as well)

**Comment by niklasdorsch** [comment]
From API

> If the target is not of type "page", returns null.

```browser.on('targetcreated', async (target) => {
            const page = await target.page();
            if(page!==null) {
                 //do stuff
            }````
