### ISSUE TITLE
Object scoping problem in page.evaluate() function

### ISSUE THREAD

**Issue by lgrzybowski** [puppeteer/puppeteer#1393]
I think there is scope problem with `Evaluation failed: ReferenceError: selectors is not defined` when I pass selector object into `page.evaluate` function. 
I was try to find that same problem in already raised issues and in stackoverflow but without success. 

* Puppeteer version: 0.13.0
* Platform / OS version: MacOsx 10.12.3, Node 8.5.0, Jest 21.2.1 
* URLs (if applicable): I modified example search test https://github.com/GoogleChrome/puppeteer/blob/master/examples/search.js

**What steps will reproduce the problem?**
Run code.   

```
const puppeteer = require('puppeteer');

describe('Google Test', () => {
    let browser;
    jasmine.DEFAULT_TIMEOUT_INTERVAL = 100000;

    const selectors = {
      inputButton: 'input[name=q]',
      submitButton: 'input[type="submit"]',
      results: 'h3 a'
    };

    beforeEach(async () => {
        browser = await puppeteer.launch({
            headless: false,
            ignoreHTTPSErrors: true,
            args: ['--no-sandbox', '--disable-setuid-sandbox'],
        });
    });

    afterEach(async () => {
        await browser.close();
    });

    describe('I can use google', () => {
        test('to find puppeteer results', async () => {
            const page = await browser.newPage();
            await page.goto('https://google.com', {waitUntil: 'networkidle2'});
            await page.waitFor(selectors.inputButton);
            await page.type(selectors.inputButton, 'puppeteer');
            await page.click(selectors.submitButton);
            await page.waitForSelector(selectors.results);
            const links = await page.evaluate(() => {
                const anchors = Array.from(document.querySelectorAll(selectors.results));
                return anchors.map(anchor => anchor.textContent);
            });
            console.log(links.join('\n'));
        });
    });
});
```

**What is the expected result?**

I assume that function evaluate should not have problems with scoping. 

**What happens instead?**
When I try to pass object `selectors.results` as argument for line `const anchors = Array.from(document.querySelectorAll(selectors.results));` 
I get error:
```
coruscant:src lukasz$ jest tests/test.test.js 
 FAIL  tests/test.test.js
  ● Google Test › I can use google › to find puppeteer results

    Evaluation failed: ReferenceError: selectors is not defined
      
      at src/<anonymous>:2:70
      at ExecutionContext.evaluateHandle (node_modules/puppeteer/lib/ExecutionContext.js:66:13)
          at <anonymous>
      at process._tickCallback (src/internal/process/next_tick.js:188:7)

  Google Test
    I can use google
      ✕ to find puppeteer results (3183ms)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        4.048s, estimated 6s
```

Of course its working perfect when I use normal selector like in example `h3 a` but not pass object. I did not find that same problem for other puppeter functions jet like click, waitForSelector.

**Comment by vsemozhetbyt** [comment]
`page.evaluate()` executes its function in the browser context, so you need the variant with arguments:
```js
            const links = await page.evaluate((selector) => {
                const anchors = Array.from(document.querySelectorAll(selector));
                return anchors.map(anchor => anchor.textContent);
            }, selectors.results);
```

**Comment by lgrzybowski** [comment]
@vsemozhetbyt  Cheers !! Thx for very good explanation!
