### ISSUE TITLE
_form2 is not defined

### ISSUE THREAD

**Issue by H91011** [puppeteer/puppeteer#1407]
* Puppeteer version: 5.4.2
* Ubuntu 16.04

I try to puppeteer from docker images  My docker file is : 

```
FROM node:8-slim

RUN apt-get update && apt-get install -y apt-transport-https wget --no-install-recommends \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-unstable \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get purge --auto-remove -y curl \
    && rm -rf /src/*.deb

RUN groupadd -r pptruser && useradd -r -g pptruser -G audio,video pptruser \
    && mkdir -p /home/pptruser/Downloads \
    && chown -R pptruser:pptruser /home/pptruser

USER pptruser

WORKDIR /home/pptuser

VOLUME ["/home/pptuser"]

CMD ["./start"]`
```

I already install puppeter with package.json and when I start docker container It goes to my link click button on page but, it con not run evaulate functon give this error:

```
eksisozluk_1  | 0|eksisozk | last clickledim

eksisozluk_1  | 0|eksisozk | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:

eksisozluk_1  | 0|eksisozk | Error: Evaluation failed: ReferenceError: _from2 is not defined

eksisozluk_1  | 0|eksisozk |     at getentrydata (<anonymous>:3:14)

eksisozluk_1  | 0|eksisozk |     at ExecutionContext.evaluateHandle (/home/pptuser/node_modules/puppeteer/lib/ExecutionContext.js:66:13)

eksisozluk_1  | 0|eksisozk |     at <anonymous>

eksisozluk_1  | 0|eksisozk |     at process._tickDomainCallback (internal/process/next_tick.js:228:7)`
```

**Comment by ebidel** [comment]
Please provide the URL and code snippet that repros the issue. Also the version of Puppeteer you're using 5.4 2 does not exist.:)

**Comment by H91011** [comment]
Ooo sorry :) I think `npm puppeteer --version` is  give me right answer its a habit from bash :) I look `pupeteer > package.json  >  "version": "0.12.0"` 

My code is : 
```
 const browser = await puppeteer.launch({ executablePath: 'google-chrome-unstable', args:['--no-sandbox', '--disable-setuid-sandbox']});
  let page      = await browser.newPage();
  console.log(linkler[0]); // gidilen link
  await page.goto(linkler[0], {waitUntil: 'networkidle'});
  await page.waitFor(2000);
  await page.click('.last', {button: "left", delay: 400});
  console.log("last clickledim");

let pagecontent = await page.evaluate(()=>{

    let icerdekiarray = [];
    let cont          = Array.from(document.querySelectorAll('.content'));
    let time          = Array.from(document.querySelectorAll('.entry-date'));
    let user          = Array.from(document.querySelectorAll('.entry-author'));
    let i             = 0;
    cont.forEach((text) => {
      datastructure = {
        data: {
          content     : "",
          contentid   : "",
          contenttitle: document.querySelector('title').textContent,
          contentuser : "",
          conenturl   : "",
          contentdate : ""
        }
      };

      datastructure.data.content     = text.textContent;
      datastructure.data.contentid   = text.parentNode.getAttribute('data-id');
      datastructure.data.contentuser = user[i].textContent;
      datastructure.data.contentdate = time[i].textContent;
      datastructure.data.contenturl  = "https://eksisozluk.com/" + time[i].href;
      icerdekiarray.push(datastructure);
      i++;
    });
    return icerdekiarray;
  });

```

**Comment by ebidel** [comment]
What's `inkler[0]`?

**Comment by H91011** [comment]
linkler it means links. It is my url array. for example  you can use this  https://eksisozluk.com/internet--32088  it is same page with my links

**Comment by ebidel** [comment]
Ok thanks. An actual url was what I was after.

Using 0.13.0, I can't repro the issue on MacOS with the following script.  The important additions are that  I'm waiting for the `.last` anchor to be defined on the page before clicking it and then using `page.waitForNavigation` to wait for the new page to load before evaluating code in it.

```js
const puppeteer = require('puppeteer');

(async() => {
const browser = await puppeteer.launch();

const page = await browser.newPage();

  await page.goto('https://eksisozluk.com/internet--32088', {waitUntil: 'networkidle2'});
  await page.waitForSelector('.last');
  await page.click('.last', {button: "left", delay: 400});
  console.log("last clickledim");

  await page.waitForNavigation({waitUntil: 'networkidle2'});

let pagecontent = await page.evaluate(()=>{

    let icerdekiarray = [];
    let cont          = Array.from(document.querySelectorAll('.content'));
    let time          = Array.from(document.querySelectorAll('.entry-date'));
    let user          = Array.from(document.querySelectorAll('.entry-author'));
    let i             = 0;
    cont.forEach((text) => {
      datastructure = {
        data: {
          content     : "",
          contentid   : "",
          contenttitle: document.querySelector('title').textContent,
          contentuser : "",
          conenturl   : "",
          contentdate : ""
        }
      };

      datastructure.data.content     = text.textContent;
      datastructure.data.contentid   = text.parentNode.getAttribute('data-id');
      datastructure.data.contentuser = user[i].textContent;
      datastructure.data.contentdate = time[i].textContent;
      datastructure.data.contenturl  = "https://eksisozluk.com/" + time[i].href;
      icerdekiarray.push(datastructure);
      i++;
    });
    return icerdekiarray;
  });

console.log(pagecontent);

await browser.close();
})();
```

**Comment by ebidel** [comment]
Please reopen if you still see weirdness.

**Comment by H91011** [comment]
Hi, I upgrade version 0.13.0 and it gives https error I resolve it with` ignoreHTTPSErrors: true` and  add your code `await page.waitForSelector('.last'); ` and  ` await page.waitForNavigation({waitUntil: 'networkidle2'});` then it gives `Error: Navigation Timeout Exceeded: 30000ms exceeded`  it can not navigate url. I can not reopen the issue. @ebidel  can you help me ?

**Comment by aslushnikov** [comment]
@H91011 looks like a new issue to me! Can you please file another one, pasting the script that yields the error for you?
