### ISSUE TITLE
slowMo + userDataDir = Error: Protocol error (Browser.close): Target closed.

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#1429]
**Tell us about your environment:**

* Puppeteer version: 0.13.0
* Platform / OS version: macOS 10.13.1
* URLs (if applicable): https://www.google.com/ (any URLs)

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. use options `slowMo` and `userDataDir` together
2. `browser.close()`

the code:

```js
const path = require('path')
const puppeteer = require('puppeteer')

const run = async () => {
  const browser = await puppeteer.launch({
    headless: false,
    slowMo: 250,
    userDataDir: path.join(process.cwd(), 'state'),
  })
  const page = await browser.newPage()
  await page.goto('https://www.google.com/')
  await browser.close()
}

run()
```

**What is the expected result?**

close the browser with no exception

**What happens instead?**

throw UnhandledPromiseRejectionWarning:

1. `Error: Protocol error (Browser.close): Target closed.`
2. `AssertionError [ERR_ASSERTION]: false == true`

![2017-11-20 20 28 29](https://user-images.githubusercontent.com/30150098/33018531-c75d9fa2-ce31-11e7-9ce8-94228b6d62bc.png)

**Comment by mxrlkn** [comment]
I get the same error with just:

```
const browser = await puppeteer.launch({
  headless: false,
  slowMo: 250
})
```

Without `userDataDir`.

**Comment by aslushnikov** [comment]
@chanjsq @marktheis I can't reproduce this on tip-of-tree. Can you please run your script with `trace-warnings` flag so that there's a stacktrace for the error?

```
$ node --trace-warnings script.js
```

**Comment by ghost** [comment]
@aslushnikov Sure.

The same code run with `--trace-warnings` flag got these outputs when the browser closed.

```shell
(node:34671) Error: Protocol error (Browser.close): Target closed.
    at Connection._onClose (/Users/chanjsq/Repos/puppeteer-test/node_modules/_puppeteer@0.13.0@puppeteer/lib/Connection.js:124:23)
    at emitTwo (events.js:126:13)
    at WebSocket.emit (events.js:214:7)
    at WebSocket.emitClose (/Users/chanjsq/Repos/puppeteer-test/node_modules/_ws@3.3.1@ws/lib/WebSocket.js:213:10)
    at _receiver.cleanup (/Users/chanjsq/Repos/puppeteer-test/node_modules/_ws@3.3.1@ws/lib/WebSocket.js:195:41)
    at Receiver.cleanup (/Users/chanjsq/Repos/puppeteer-test/node_modules/_ws@3.3.1@ws/lib/Receiver.js:520:15)
    at WebSocket.finalize (/Users/chanjsq/Repos/puppeteer-test/node_modules/_ws@3.3.1@ws/lib/WebSocket.js:195:22)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
(node:34671) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitWarning (internal/process/promises.js:78:15)
    at emitPendingUnhandledRejections (internal/process/promises.js:95:11)
    at runMicrotasksCallback (internal/process/next_tick.js:124:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:34671) AssertionError [ERR_ASSERTION]: false == true
    at Console.assert (console.js:188:23)
    at Connection._onMessage (/Users/chanjsq/Repos/puppeteer-test/node_modules/_puppeteer@0.13.0@puppeteer/lib/Connection.js:101:15)
    at <anonymous>
```

**Comment by ghost** [comment]
Use Puppeteer master branch got the same:

```shell
(node:34803) Error: Protocol error (Browser.close): Target closed.
    at Connection._onClose (/Users/chanjsq/Repos/puppeteer-test/node_modules/_puppeteer@1.0.0-rc@puppeteer/lib/Connection.js:124:23)
    at emitTwo (events.js:126:13)
    at WebSocket.emit (events.js:214:7)
    at WebSocket.emitClose (/Users/chanjsq/Repos/puppeteer-test/node_modules/_ws@3.3.1@ws/lib/WebSocket.js:213:10)
    at _receiver.cleanup (/Users/chanjsq/Repos/puppeteer-test/node_modules/_ws@3.3.1@ws/lib/WebSocket.js:195:41)
    at Receiver.cleanup (/Users/chanjsq/Repos/puppeteer-test/node_modules/_ws@3.3.1@ws/lib/Receiver.js:520:15)
    at WebSocket.finalize (/Users/chanjsq/Repos/puppeteer-test/node_modules/_ws@3.3.1@ws/lib/WebSocket.js:195:22)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
(node:34803) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitWarning (internal/process/promises.js:78:15)
    at emitPendingUnhandledRejections (internal/process/promises.js:95:11)
    at runMicrotasksCallback (internal/process/next_tick.js:124:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:34803) AssertionError [ERR_ASSERTION]: false == true
    at Console.assert (console.js:188:23)
    at Connection._onMessage (/Users/chanjsq/Repos/puppeteer-test/node_modules/_puppeteer@1.0.0-rc@puppeteer/lib/Connection.js:101:15)
    at <anonymous>
```

**Comment by aslushnikov** [comment]
@chanjsq interesting! Someone's shutting the websocket. 

The two possibilities are:
- anti-virus
- chrome's crashing

To get a more details, can you also pass `dumpio: true` to the `puppeteer.launch` and show us the stdout output?

**Comment by ghost** [comment]
@aslushnikov interesting!

```shell
DevTools listening on ws://127.0.0.1:57228/devtools/browser/1aed9167-a851-469a-a8f1-ef06e3b428af
2017-11-21 08:52:16.486 Chromium[36031:1656630] *** Owner supplied to -[NSTrackingArea initWithRect:options:owner:userInfo:] referenced a deallocating object. Tracking area behavior is undefined. Break on NSTrackingAreaDeallocatingOwnerError to debug.
[36031:47875:1121/085219.947681:ERROR:service_manager.cc(158)] Connection InterfaceProviderSpec prevented service: content_renderer from binding interface: blink::mojom::ReportingServiceProxy exposed by: content_browser
[36031:47875:1121/085219.947842:ERROR:service_manager.cc(158)] Connection InterfaceProviderSpec prevented service: content_renderer from binding interface: blink::mojom::ReportingServiceProxy exposed by: content_browser
[36031:47875:1121/085219.948030:ERROR:service_manager.cc(158)] Connection InterfaceProviderSpec prevented service: content_renderer from binding interface: blink::mojom::ReportingServiceProxy exposed by: content_browser
(node:36030) Error: Protocol error (Browser.close): Target closed.
    at Connection._onClose (/Users/chanjsq/Repos/puppeteer-test/node_modules/_puppeteer@1.0.0-rc@puppeteer/lib/Connection.js:124:23)
    at emitTwo (events.js:126:13)
    at WebSocket.emit (events.js:214:7)
    at WebSocket.emitClose (/Users/chanjsq/Repos/puppeteer-test/node_modules/_ws@3.3.1@ws/lib/WebSocket.js:213:10)
    at _receiver.cleanup (/Users/chanjsq/Repos/puppeteer-test/node_modules/_ws@3.3.1@ws/lib/WebSocket.js:195:41)
    at Receiver.cleanup (/Users/chanjsq/Repos/puppeteer-test/node_modules/_ws@3.3.1@ws/lib/Receiver.js:520:15)
    at WebSocket.finalize (/Users/chanjsq/Repos/puppeteer-test/node_modules/_ws@3.3.1@ws/lib/WebSocket.js:195:22)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
(node:36030) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitWarning (internal/process/promises.js:78:15)
    at emitPendingUnhandledRejections (internal/process/promises.js:95:11)
    at runMicrotasksCallback (internal/process/next_tick.js:124:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:36030) AssertionError [ERR_ASSERTION]: false == true
    at Console.assert (console.js:188:23)
    at Connection._onMessage (/Users/chanjsq/Repos/puppeteer-test/node_modules/_puppeteer@1.0.0-rc@puppeteer/lib/Connection.js:101:15)
    at <anonymous>
```

**Comment by ghost** [comment]
@aslushnikov Can you find something useful? I didn't install anti-virus software yet.

**Comment by aslushnikov** [comment]
@chanjsq hmm no, doesn't look like chrome's crashing. So you run straight on OS X, without any docker or vm?

**Comment by ghost** [comment]
@aslushnikov Yes, I am. Any other actions I can do to figure out the problem?

**Comment by ghost** [comment]
@marktheis I will test it in Windows later.

**Comment by aslushnikov** [comment]
> Any other actions I can do to figure out the problem?

@chanjsq can you please try launching chromium manually from the `puppeteer/.local-chromium` folder and see if the binary is fully-functional for you?

**Comment by mxrlkn** [comment]
@aslushnikov I got the same error as @chanjsq did with `dumpio: true`. Running it straight on MacOS 10.13.1.

chromium in `puppeteer/.local-chromium` works just fine for me. hitting google, facebook, etc.

I don't have antivirus installed.

**Comment by ghost** [comment]
@aslushnikov I have also tested with Windows 7, same issue. While `puppeteer/.local-chromium` binary worked ok for me.

**Comment by peterschrott** [comment]
Are there any updates on this?
I am forcing the same issue on OSX wit the following configuration:
```
{
   slowMo: 50,
   userDataDir: `/tmp/data-session-${sessionId}`
}
```

Setting `headless` to `true` /  `false` results in a different error tho.
On `headless: false`, I get an OSX error windows showing: "Chromium quit unexpectedly - Click Reopen to open the application again. Click Report to see more detailed information and send a report to Apple."

Plus, when providing a `userDataDir` the user data are not written correctly on a browser crash. Either chromium complains about corrupt profile data or no profile data are stored at all. I assume that due to the crash the user data are not correctly flushed to disk.

The following cases lead to different errors:
```
| headless | slowMo | userDir | error
+----------+--------+---------+---------------------------
| false    | no     | yes     | OSX error window
| true     | yes    | yes     | console error
| false    | yes    | yes     | console error + OSX error window
```

![screen shot 2018-04-06 at 09 51 14](https://user-images.githubusercontent.com/3984741/38409028-1460405c-3980-11e8-9c9e-26807af7937f.png)

**Comment by aslushnikov** [comment]
There are good chances this will be fixed as the upstream patch lands: https://chromium-review.googlesource.com/c/chromium/src/+/1000730

**Comment by aslushnikov** [comment]
@chanjsq we've rolled chromium in https://github.com/GoogleChrome/puppeteer/pull/2327. can you please try installing `puppeteer@next` (this is a tip-of-tree build published to npm) and see if the issue is fixed?

**Comment by adelalsaggaf1** [comment]
في السبت، ٧ ابريل، ٢٠١٨ ٣:٥٢ ص Andrey Lushnikov <notifications@github.com>
كتب:

**Comment by ghost** [comment]
@aslushnikov I will try it ❤️

**Comment by ghost** [comment]
@aslushnikov Still happens, with the following output:

```shell
(node:11731) UnhandledPromiseRejectionWarning: Error: Protocol error (Browser.close): Target closed.
    at Promise (/Users/huachen/Projects/labs/puppeteer-player/node_modules/_puppeteer@1.2.0-next.1523149483176@puppeteer/lib/Connection.js:86:56)
    at new Promise (<anonymous>)
    at Connection.send (/Users/huachen/Projects/labs/puppeteer-player/node_modules/_puppeteer@1.2.0-next.1523149483176@puppeteer/lib/Connection.js:85:12)
    at killChrome (/Users/huachen/Projects/labs/puppeteer-player/node_modules/_puppeteer@1.2.0-next.1523149483176@puppeteer/lib/Launcher.js:176:20)
    at Browser.close (/Users/huachen/Projects/labs/puppeteer-player/node_modules/_puppeteer@1.2.0-next.1523149483176@puppeteer/lib/Browser.js:154:31)
    at run (/Users/huachen/Projects/labs/puppeteer-player/index.js:12:17)
    at <anonymous>
(node:11731) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11731) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
