### ISSUE TITLE
headless: true with timeout on Launch causes Kill

### ISSUE THREAD

**Issue by jungalwala** [puppeteer/puppeteer#1442]
* Puppeteer version: 0.13.0
* Platform / OS version: Mac OSx 10.13.2
* URLs (if applicable): (Local URL)

When I launch puppeteer with `headless: false` and `timeout=3000000`, everything works great.  When I switch to `headless: true` I get the following error:

` Error: kill EPERM
  at exports._errnoException (util.js:1050:11)
  at process.kill (internal/process.js:188:13)
  at forceKillChrome (/Users/jfj/Library/Mobile Documents/com~apple~CloudDocs/Workspace/squad-leader/node_modules/puppeteer/lib/Launcher.js:162:19)
  at killChrome (/Users/jfj/Library/Mobile Documents/com~apple~CloudDocs/Workspace/squad-leader/node_modules/puppeteer/lib/Launcher.js:147:9)
  at Function.launch (/Users/jfj/Library/Mobile Documents/com~apple~CloudDocs/Workspace/squad-leader/node_modules/puppeteer/lib/Launcher.js:137:7)
  at process._tickCallback (internal/process/next_tick.js:109:7)
 code: 'EPERM', errno: 'EPERM', syscall: 'kill' }`

Note I am using coffeescript, but here is how I launch Puppeteer:

`puppeteer.launch({headless: true, args: ["--timeout=300000"]}).then (browser) =>`

Also note, if I remove the timeout and keep `headless:true` it works fine.

**Comment by jimut** [comment]
Would have been a help if you had shared the solution.

**Comment by jungalwala** [comment]
To be honest, I don't remember what I did to fix it. Sorry.
