### ISSUE TITLE
Properly handle target crashes

### ISSUE THREAD

**Issue by aslushnikov** [puppeteer/puppeteer#1454]
Crashed targets should be handled gracefully:
1. All pending commands should be rejected. This includes protocol messages and watchdogs, such as NavigatorWatcher / WaitTask
2. All subsequent commands to the crashed target should reject right away

Neither (1) or (2) happen with Puppeteer v0.13.0.

**Comment by schelkun** [comment]
Why page is crashing? Some Chromium bug?

**Comment by aslushnikov** [comment]
@schelkun might be many reasons: chromium bug, OOM, memory corruption etc.

**Comment by bahattincinic** [comment]
@aslushnikov When will you fix this issue?

We got the same problem. Zombie chrome processes have been growing increasingly.  We can't kill them. AWS Lambda has a maximum process limit. (max 1024 process) That's why we reach the lambda limits

**For example;**
```
483 1 3.3 1.6 1226196 65408 ? Ssl 22:07 0:05 /var/lang/bin/node --max-old-space-size=870 --max-semi-space-size=54 --max-executable-size=109 --expose-gc /var/runtime/node_modules/awslambda/index.js
483 22 0.0 0.0 0 0 ? Z 22:07 0:00 [headless-chromi] <defunct>
483 73 0.0 0.0 0 0 ? Z 22:07 0:00 [headless-chromi] <defunct>
483 119 0.0 0.0 0 0 ? Z 22:07 0:00 [headless-chromi] <defunct>
483 166 0.0 0.0 0 0 ? Z 22:07 0:00 [headless-chromi] <defunct>
483 214 0.0 0.0 0 0 ? Z 22:07 0:00 [headless-chromi] <defunct>
483 262 0.0 0.0 0 0 ? Z 22:07 0:00 [headless-chromi] <defunct>
483 307 0.0 0.0 0 0 ? Z 22:07 0:00 [headless-chromi] <defunct>
483 353 0.0 0.0 0 0 ? Z 22:07 0:00 [headless-chromi] <defunct>
483 398 0.0 0.0 0 0 ? Z 22:07 0:00 [headless-chromi] <defunct>
483 446 0.0 0.0 0 0 ? Z 22:07 0:00 [headless-chromi] <defunct>
483 493 0.0 0.0 0 0 ? Z 22:07 0:00 [headless-chromi] <defunct>
483 538 0.0 0.0 0 0 ? Z 22:07 0:00 [headless-chromi] <defunct>
483 585 0.0 0.0 0 0 ? Z 22:07 0:00 [headless-chromi] <defunct>
483 630 0.0 0.0 0 0 ? Z 22:07 0:00 [headless-chromi] <defunct>
483 680 0.0 0.0 0 0 ? Z 22:07 0:00 [headless-chromi] <defunct>
483 730 0.0 0.0 0 0 ? Z 22:07 0:00 [headless-chromi] <defunct>
483 777 0.0 0.0 0 0 ? Z 22:08 0:00 [headless-chromi] <defunct>
483 829 0.0 0.0 0 0 ? Z 22:08 0:00 [headless-chromi] <defunct>
483 874 0.0 0.0 0 0 ? Z 22:08 0:00 [headless-chromi] <defunct>
483 922 0.0 0.0 0 0 ? Z 22:08 0:00 [headless-chromi] <defunct>
483 969 0.0 0.0 0 0 ? Z 22:08 0:00 [headless-chromi] <defunct>
483 1915 0.0 0.0 0 0 ? Z 22:09 0:00 [sh] <defunct>
```

We tried to use `dumb-init` on lambda. it didn't work.

**Comment by aslushnikov** [comment]
@bahattincinic I don't think this has something to do with the issue. Would you mind filing a new issue with some details, e.g. your pptr version and chrome version?

**Comment by bahattincinic** [comment]
Okay, I will create a new issue.

- Puppeteer Version: 1.0.
- Chrome Version: 64.0.3282.71 (https://github.com/adieuadieu/serverless-chrome/releases/tag/v1.0.0-34)

**Comment by bahattincinic** [comment]
@aslushnikov issue: https://github.com/GoogleChrome/puppeteer/issues/1825

**Comment by brandonros** [comment]
I don't understand why if the functions calling the puppeteer API are wrapped in try/catch why the 

```
error:  error=Error: Page crashed!
    at Page._onTargetCrashed (/home/brandon/shippingtroll/node_modules/puppeteer/lib/Page.js:115:24)
    at CDPSession.Page.client.on.event (/home/brandon/shippingtroll/node_modules/puppeteer/lib/Page.js:103:56)
```

error bubbles up?

**Comment by brandonros** [comment]
I don't understand why if the functions calling the puppeteer API are wrapped in try/catch why the 

```
error:  error=Error: Page crashed!
    at Page._onTargetCrashed (/home/brandon/f/node_modules/puppeteer/lib/Page.js:115:24)
    at CDPSession.Page.client.on.event (/home/brandon/f/node_modules/puppeteer/lib/Page.js:103:56)
```

error bubbles up?

Edit:

https://github.com/GoogleChrome/puppeteer/issues/1401#issuecomment-346521638

Nevermind...

**Comment by drmrbrewer** [comment]
@aslushnikov I don't understand what the current status of this is.  Exactly as per @brandonros's comment just above, I have all puppeteer API function calls wrapped within a try/catch.  I have also assigned a function to the `page.on('error'...)` event handler.  Despite that, I am still getting `UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 28): Error: Page crashed!`.

Is this issue unresolved?  How do I get rid of these errors... so far as I can tell, I am handling all promise rejections, but maybe I'm not.  Is there an example somewhere of how `Page crashed` errors should be handled?

**Comment by brandonros** [comment]
@drmrbrewer Try this:

```
page.on('error', function(err) {
    throw err;
  });
```

I believe that fixed it for me.

**Comment by drmrbrewer** [comment]
@brandonros apart from a bit of logging, that is *exactly* what I'm using for the `error` handler.  Despite that, I'm still getting the occasional `UnhandledPromiseRejectionWarning` :-/

**Comment by drmrbrewer** [comment]
@brandonros @aslushnikov I'm finding that the error does reach the `page.on('error'..)` handler, but doesn't propagate upward, despite the `throw err` in the handler.  In other words, I have a bunch of stuff that does things with the `page`, and all of that is wrapped in a `try/catch`.  So I had assumed that an error thrown by the `page.on('error'..)` handler would be caught in the `catch` block.  But it never appears there.  I can't help thinking that I've misunderstood something fundamental about error handling with `async/await`, at least where an error handler like this is involved?

EDIT... yes... trying an approach more along the lines of [this example](https://github.com/GoogleChrome/puppeteer/issues/1862#issue-290193270) seems to work better, i.e. wrapping everything in a Promise with `resolve/reject` functions to call... and in particular this allows you to call the `reject` function in the `page.on('error'..)` handler.  It's all a bit messy, but I think I have it working a bit better now, without the pesky `UnhandledPromiseRejectionWarning` occurrences.

**Comment by mahnunchik** [comment]
Any news?

I've faced with:

```bash
(node:1) UnhandledPromiseRejectionWarning: Error: Page crashed!
at Page._onTargetCrashed (/usr/src/app/node_modules/puppeteer/lib/Page.js:176:24)
at CDPSession.Page.client.on.event (/usr/src/app/node_modules/puppeteer/lib/Page.js:138:56)
at emitOne (events.js:116:13)
at CDPSession.emit (events.js:211:7)
at CDPSession._onMessage (/usr/src/app/node_modules/puppeteer/lib/Connection.js:216:12)
at <anonymous>
at Connection._onMessage (/usr/src/app/node_modules/puppeteer/lib/Connection.js:99:19)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

* puppeteer version: 1.11.0
* chromium from package on ubuntu linux

**Comment by gsouf** [comment]
A tiny concern..is someone aware of a realistic way to reproduce "page crashed!" in order to include it to our projects' test suits?

**Comment by sdeprez** [comment]
@gsouf we have a unit-test similar to that in our codebase. 

```
const browser = await puppeteer.launch()
const page = await browser.newPage()

const client = await page.target().createCDPSession()
let hasPageCrashed = false

page.on('error', (e: Error) => {
  hasPageCrashed = /Page crashed/.test(error.toString())
  void newBrowser.close() // otherwise `send('Page.crash')` hangs.
})

try {
  await client.send('Page.crash')
} catch (e) {}

expect(hasPageCrashed).toBeTruthy()
```

**Comment by epexa** [comment]
#6277

**Comment by epexa** [comment]
#3709

**Comment by epexa** [comment]
> @gsouf we have a unit-test similar to that in our codebase.
> 
> ```
> const browser = await puppeteer.launch()
> const page = await browser.newPage()
> 
> const client = await page.target().createCDPSession()
> let hasPageCrashed = false
> 
> page.on('error', (e: Error) => {
>   hasPageCrashed = /Page crashed/.test(error.toString())
>   void newBrowser.close() // otherwise `send('Page.crash')` hangs.
> })
> 
> try {
>   await client.send('Page.crash')
> } catch (e) {}
> 
> expect(hasPageCrashed).toBeTruthy()
> ```

@sdeprez thanks!

Another working example:
```js
const makeScreenshot = async () => {
  try {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();

    page.on('error', async () => {
      // throw err; // catch don't work (issue: 6330, 5928, 1454, 6277, 3709)
      await browser.close();
    });

    await page.goto(url);

    const result = await page.screenshot();

    await browser.close();

    return result;
  } catch (err) {
    console.error('makeScreenshot error', err);

    return false;
  }
};
```

**Comment by bryghtlabs-richard** [comment]
If you can send signals, sending SIGKILL to chrome's renderer process will generate "Aw, Snap!" in that renderer's tab. But I'm not sure how to locate the renderer PID.
