### ISSUE TITLE
brower.newPage() return a null

### ISSUE THREAD

**Issue by IWSR** [puppeteer/puppeteer#1745]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:  ^0.13.0
* Platform / OS version: Debian
* Node.js version: v9.3.0
* Chrome version: 62.0.3202.62

**What steps will reproduce the problem?**

I just run the code by node app.js,and there is my code in app.js

```
const puppeteer = require('puppeteer');

(async () => {
  const brower = await puppeteer.launch({
    headless: false,
    executablePath: '/opt/google/chrome/chrome',
  });
  const page = await brower.newPage();
  console.log(page, 'page'); // page is null
  await page.goto('https://github.com');
  const dimensions = await page.evaluate(() => {
    return {
      width: document.documentElement.clientWidth,
      height: document.documentElement.clientHeight,
      deviceScaleFactor: window.devicePixelRatio
    }
  });

  console.log('Dimensions:', dimensions);

  await brower.close();
})()
```

**What is the expected result?**
My code is exactly the same as the demo code.It should have run the code successfully,but there is something wrong,the page is null.

**What happens instead?**
```
[AsyncFunction: newPage]
null 'page'
(node:15517) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'goto' of null
    at __dirname (/home/iwsr/myCode/nodejs/Spider_Intermediaries_Killer/app.js:11:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:15517) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15517) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ebidel** [comment]
That version of chrome is much older than the one puppeteer requires in
0.13.0. That version bundles m64.

**Comment by aslushnikov** [comment]
@IWSR please, either use older pptr (e.g. 0.9.0) or newer chrome.

**Comment by IWSR** [comment]
@ebidel I install puppeteer with yarn again,and this time I open my vpn and I installed all devDependencies, moreover,i installed the chromium which is required ,then I change my code. 
```
const puppeteer = require('puppeteer');

(async () => {
  const brower = await puppeteer.launch({
    headless: false,
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
  });
  const page = await brower.newPage();
  try {
    console.log('success');
  }catch (e) {
    console.log(e);
    process.exit(1);
  }
  console.log(1);
  await page.goto('https://github.com');
  console.log(2);
  const dimensions = await page.evaluate(() => {
    return {
      width: document.documentElement.clientWidth,
      height: document.documentElement.clientHeight,
      deviceScaleFactor: window.devicePixelRatio
    }
  });

  console.log('Dimensions:', dimensions);

  await brower.close();
})()
```
But the terminal did not output either success or error message,I guess the code stop at the first await.I do not know why.
Sorry for my poor English.

**Comment by IWSR** [comment]
@ebidel @aslushnikov Thank you all,I can run the puppeteer now.

**Comment by lcjnil** [comment]
@aslushnikov Maybe you should mention that in README

**Comment by IWSR** [comment]
@lcjnil I find the Version requirements about chromium in README, but there is no information about chrome.
