### ISSUE TITLE
puppeteer doesn't work with istanbul

### ISSUE THREAD

**Issue by yujiosaka** [puppeteer/puppeteer#1855]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.0.0
* Platform / OS version: any
* URLs (if applicable): any
* Node.js version: any

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Install puppeteer and [istanbul](https://istanbul.js.org) in the project
2. Measure coverage of tests which calls `page.evaluate()` functions
3. JavaScript evaluation is broken

**What is the expected result?**

It works as usual.

**What happens instead?**

It fails silently. If you look into Chrome's console, it shows the following message:
```
Error: Evaluation failed: ReferenceError: __cov_wd8fYQ0_DRsaAufZbmXyDQ is not defined
    at <anonymous>:1:741
    at ExecutionContext.evaluateHandle (/Users/yujiosaka/work/headless-chrome-crawler/node_modules/puppeteer/lib/ExecutionContext.js:70:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Why it happens?**

[istanbul](https://istanbul.js.org) overrides `Function.toString` and modifies the string like this:

*before*
```js
function fn(){console.log('hoge');}
```

*after*
```js
function fn(){__cov_wd8fYQ0_DRsaAufZbmXyDQ.f['7']++;__cov_wd8fYQ0_DRsaAufZbmXyDQ.s['20']++;console.log('hoge');}
```

puppeteer's  `page.evaluate()` relies on `Function.toString`, so it's broken.

It's istanbul's issue, and it's discussed in [here](https://github.com/gotwarlost/istanbul/issues/310).

I posted this issue because I think it's useful for people to be able to search here when they face the same problem.

**Comment by yujiosaka** [comment]
Sorry, it was a dupe to https://github.com/GoogleChrome/puppeteer/issues/1054 which I failed to notice.
