### ISSUE TITLE
Troubleshooting solution doesn't work for Node 8

### ISSUE THREAD

**Issue by fetis** [puppeteer/puppeteer#2030]
Hello everyone,

 I'm trying to make docker image with Node.js and Puppeteer to be able run  unit tests in CI environment.

I tried to used solution from https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker

But it still has problem with sandbox (you _still_ have to specify it for correct work)

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.0.0
* Platform / OS version: `Linux 1de6989fc88d 4.9.49-moby #1 SMP Wed Sep 27 23:17:17 UTC 2017 x86_64 GNU/Linux`
* Node.js version: 8.9.4

**What steps will reproduce the problem?**
1. Create new docker image with Docker file provied in [Troubleshooting](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker)
2. Create this test file 
```js
const puppeteer = require('puppeteer');
(async() => {
  const browser = await puppeteer.launch();
const page = await browser.newPage();
await page.goto('https://example.com');
await page.screenshot({path: 'example.png'});
browser.close();
})();
```
3. Try to run it inside the container
```
node test.js
```

**What is the expected result?**
I expect normal execution

**What happens instead?**
```
pptruser@1de6989fc88d:/home$ node test.js
(node:83) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Failed to launch chrome!
[0214/155025.511300:FATAL:zygote_host_impl_linux.cc(126)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
#0 0x55e84d0ef2ec base::debug::StackTrace::StackTrace()
#1 0x55e84d10673c logging::LogMessage::~LogMessage()
#2 0x55e84c18b0d1 content::ZygoteHostImpl::Init()
#3 0x55e84be05045 content::BrowserMainLoop::EarlyInitialization()
#4 0x55e84be0b222 content::BrowserMainRunnerImpl::Initialize()
#5 0x55e850fd7059 headless::HeadlessContentMainDelegate::RunProcess()
#6 0x55e84ce2bf60 content::RunNamedProcessTypeMain()
#7 0x55e84ce2c975 content::ContentMainRunnerImpl::Run()
#8 0x55e84ce35c5f service_manager::Main()
#9 0x55e84ce2b481 content::ContentMain()
#10 0x55e850fd61fa headless::(anonymous namespace)::RunContentMain()
#11 0x55e850fd626e headless::HeadlessBrowserMain()
#12 0x55e84ce32a6a headless::HeadlessShellMain()
#13 0x55e84b6b81c5 ChromeMain
#14 0x7f09eca1bb45 __libc_start_main
#15 0x55e84b6b802a _start

Received signal 6
#0 0x55e84d0ef2ec base::debug::StackTrace::StackTrace()
#1 0x55e84d0eee51 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#2 0x7f09f2896890 <unknown>
#3 0x7f09eca2f067 gsignal
#4 0x7f09eca30448 abort
#5 0x55e84d0edaa5 base::debug::BreakDebugger()
#6 0x55e84d106b3f logging::LogMessage::~LogMessage()
#7 0x55e84c18b0d1 content::ZygoteHostImpl::Init()
#8 0x55e84be05045 content::BrowserMainLoop::EarlyInitialization()
#9 0x55e84be0b222 content::BrowserMainRunnerImpl::Initialize()
#10 0x55e850fd7059 headless::HeadlessContentMainDelegate::RunProcess()
#11 0x55e84ce2bf60 content::RunNamedProcessTypeMain()
#12 0x55e84ce2c975 content::ContentMainRunnerImpl::Run()
#13 0x55e84ce35c5f service_manager::Main()
#14 0x55e84ce2b481 content::ContentMain()
#15 0x55e850fd61fa headless::(anonymous namespace)::RunContentMain()
#16 0x55e850fd626e headless::HeadlessBrowserMain()
#17 0x55e84ce32a6a headless::HeadlessShellMain()
#18 0x55e84b6b81c5 ChromeMain
#19 0x7f09eca1bb45 __libc_start_main
#20 0x55e84b6b802a _start
  r8: ffffbf109f742440  r9: ffffbf109f742430 r10: 0000000000000008 r11: 0000000000000202
 r12: 00007ffd536b1838 r13: 00007ffd536b1828 r14: 00007ffd536b1830 r15: 00007ffd536b13e0
  di: 000000000000005d  si: 000000000000005d  bp: 00007ffd536b1370  bx: 00007ffd536b13e0
  dx: 0000000000000006  ax: 0000000000000000  cx: 00007f09eca2f067  sp: 00007ffd536b1238
  ip: 00007f09eca2f067 efl: 0000000000000202 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
```

**Comment by ebidel** [comment]
Is `Linux 1de6989fc88d 4.9.49-moby` is a version you've built yourself? Try running with the `puppeteer.launch({args: ['--no-sandbox']})` flag to see if that helps.

**Comment by fetis** [comment]
@ebidel No, it's version of node:8 docker image which is base for this image.
`--no-sandbox` obviously helps, but I would like to have normal startup process. As far I understood, this options is not recommended.

**Comment by ebidel** [comment]
FWIW, I recently had to add this myself: https://github.com/ebidel/try-puppeteer/commit/aacadb54abf861a807e9a71ee54d03abbf21d193. Haven't found the reason, but it's possible Unbuntu has rolled it's Chromium package recently, and therefore change the dependencies required by Chromium.

**Comment by milanchheda** [comment]
I am also getting exactly the same error. :( 

```
(node:13692) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
/var/www/html/development/screenshot/node_modules/puppeteer/.local-chromium/linux-536395/chrome-linux/chrome: /usr/lib/x86_64-linux-gnu/libnss3.so: version `NSS_3.22' not found (required by /var/www/html/development/screenshot/node_modules/puppeteer/.local-chromium/linux-536395/chrome-linux/chrome)


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/var/www/html/development/screenshot/node_modules/puppeteer/lib/Launcher.js:235:14)
    at Interface.helper.addEventListener (/var/www/html/development/screenshot/node_modules/puppeteer/lib/Launcher.js:224:50)
    at Interface.emit (events.js:165:20)
    at Interface.close (readline.js:381:8)
    at Socket.onend (readline.js:154:10)
    at Socket.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
(node:13692) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13692) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Node version: v9.4.0
Puppeteer version: 1.1.0
Ubuntu: 16.04

And following is the code:
```
const puppeteer = require('puppeteer');
(async() => {
  const browser = await puppeteer.launch();
const page = await browser.newPage();
await page.goto('https://example.com');
await page.screenshot({path: 'example.png'});
browser.close();
})();
```

**Comment by milanchheda** [comment]
Ok. I got it fixed by installing libnss3
```
sudo apt-get install libnss3
```

**Comment by ebidel** [comment]
@fetis also make sure you have user namespaces turned on for the kernel. If you don't, you'll need `--no-sandbox`.

**Comment by fetis** [comment]
@ebidel how can I specify it?

@milanchheda I think you had the different problem than me.

**Comment by enthusiasmus** [comment]
same problem here as @fetis! 
Installing libnss3 doesn't fix it, I have namespaces turned on and the --no-sandbox flag is no solution. it is a workaround. please reopen issue, till this bug is fixed

**Comment by juancarlosfarah** [comment]
I'm encountering the same issue. @enthusiasmus, how did you enable user namespaces?
