### ISSUE TITLE
Launching Error with Heroku

### ISSUE THREAD

**Issue by Nicolas-vrcc** [puppeteer/puppeteer#2031]
Hello,

I installed the buildpack (https://github.com/heroku/heroku-buildpack-google-chrome) and everything as said in the docs to run with Heroku.

And I ended up with this error : 

```
    at onClose (/app/node_modules/puppeteer/lib/Launcher.js:226:14)
    at Interface.helper.addEventListener (/app/node_modules/puppeteer/lib/Launcher.js:215:50)
    at emitNone (events.js:111:20)
    at Interface.emit (events.js:208:7)
    at Interface.close (readline.js:370:8)
    at Socket.onend (readline.js:149:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
```
(node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'newPage' of undefined
(node:4) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a
 non-zero exit code.`
```

What's wrong ?

**Comment by aslushnikov** [comment]
Checkout our troubleshooting guide for running on Heroku: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-on-heroku

**Comment by Timibadass** [comment]
Hi @aslushnikov , i have the buildpack on my heroku yet I still get this error , can you help?
`Error: Failed to launch chrome!
       /tmp/build_912afc3a01c84171324e56872de578ca/node_modules/puppeteer/.local-chromium/linux-624492/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory`

**Comment by swang2019** [comment]
same to #4098
