### ISSUE TITLE
Improve error message for timeouts

### ISSUE THREAD

**Issue by felixfbecker** [puppeteer/puppeteer#2037]
When a `page.waitFor()` times out, this is all error context a dev gets:
```
     Error: waiting failed: timeout 30000ms exceeded
      at Timeout.WaitTask._timeoutTimer.setTimeout (node_modules/puppeteer/lib/FrameManager.js:695:58)
```

No stack trace and no indication _what_ operation timed out.

An easy change to an error message like
```
     Error: waiting for selector ".my-selector" failed: timeout 30000ms exceeded
      at Timeout.WaitTask._timeoutTimer.setTimeout (node_modules/puppeteer/lib/FrameManager.js:695:58)
```

would make a huge difference in knowing where to look.

**Comment by aslushnikov** [comment]
I'll be happy to review a PR.

**Comment by felixfbecker** [comment]
I was also able to get long stack traces by patching global Promise with bluebird (which still has the most robust long stack traces implementation I've seen):
```js
const Bluebird = require('bluebird')
Bluebird.config({ longStackTraces: true })
global.Promise = Bluebird
```
```
  Error: waiting failed: timeout 30000ms exceeded
      at Timeout.WaitTask._timeoutTimer.setTimeout [as _onTimeout] (node_modules/puppeteer/lib/FrameManager.js:789:58)
  From previous event:
      at new WaitTask (node_modules/puppeteer/lib/FrameManager.js:783:20)
      at Frame.waitForFunction (node_modules/puppeteer/lib/FrameManager.js:675:12)
      at Frame._waitForSelectorOrXPath (node_modules/puppeteer/lib/FrameManager.js:695:17)
      at Frame.waitForSelector (node_modules/puppeteer/lib/FrameManager.js:655:17)
      at Page.waitForSelector (node_modules/puppeteer/lib/Page.js:874:29)
      at Context.it (src/e2e/index.test.e2e.tsx:122:24)
      at <anonymous>
```

There currently is no native way to maintain stack traces with `setTimeout` in Node.

**Comment by Saturate** [comment]
Including bluebird just for this seems rather excessive. Is this on the Node roadmap?

**Comment by felixfbecker** [comment]
I don't think so. Async call stacks when using `setTimeout` for the debugger [have been fixed in Node 9.6.1](https://github.com/nodejs/node/issues/11370) but async error stack traces was never supported by Node.

**Comment by felixfbecker** [comment]
Also personally don't really have a problem with a 194KB devDependency if I get long stack traces in return. The benefit it huge, what's the cost? I don't use any Bluebird API, the application sees no difference.

**Comment by ianldgs** [comment]
Suggestion:
instantiate an `Error` before `setTimeout`. If it timesout, throw the instantiated `Error`
