### ISSUE TITLE
Sandbox fails on system with Linux 4.15

### ISSUE THREAD

**Issue by bobajeff** [puppeteer/puppeteer#2161]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: puppeteer@1.1.1
* Platform / OS version: Manjaro Linux 17.1.6 with Linux 4.15
* Node.js version: v9.7.1

**What steps will reproduce the problem?**

This fails on the `example.js` from the Getting Started section:
```javascript

const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://example.com');
  await page.screenshot({path: 'example.png'});

  await browser.close();
})();
```

1. run node example.js

**What is the expected result?**
I believe it should use the namespace sandbox since my kernel is well above 3.8.

**What happens instead?**
Here's the console output:
```
(node:2685) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
[0308/081346.497090:FATAL:zygote_host_impl_linux.cc(124)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
#0 0x556d8e77a8ec base::debug::StackTrace::StackTrace()
#1 0x556d8e792770 logging::LogMessage::~LogMessage()
#2 0x556d8d84cf61 content::ZygoteHostImpl::Init()
#3 0x556d8d4c73b5 content::BrowserMainLoop::EarlyInitialization()
#4 0x556d8d4cd30a content::BrowserMainRunnerImpl::Initialize()
#5 0x556d927348f8 headless::HeadlessContentMainDelegate::RunProcess()
#6 0x556d8e4b4160 content::RunNamedProcessTypeMain()
#7 0x556d8e4b4ab6 content::ContentMainRunnerImpl::Run()
#8 0x556d8e4bdd59 service_manager::Main()
#9 0x556d8e4b3661 content::ContentMain()
#10 0x556d927339f8 headless::(anonymous namespace)::RunContentMain()
#11 0x556d92733a6e headless::HeadlessBrowserMain()
#12 0x556d8e4bac49 headless::HeadlessShellMain()
#13 0x556d8cd6a1c4 ChromeMain
#14 0x7f8b55554f4a __libc_start_main
#15 0x556d8cd6a02a _start

Received signal 6
#0 0x556d8e77a8ec base::debug::StackTrace::StackTrace()
#1 0x556d8e77a451 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#2 0x7f8b5b50fdd0 <unknown>
#3 0x7f8b55568860 __GI_raise
#4 0x7f8b55569ec9 __GI_abort
#5 0x556d8e778ee5 base::debug::BreakDebugger()
#6 0x556d8e792bbb logging::LogMessage::~LogMessage()
#7 0x556d8d84cf61 content::ZygoteHostImpl::Init()
#8 0x556d8d4c73b5 content::BrowserMainLoop::EarlyInitialization()
#9 0x556d8d4cd30a content::BrowserMainRunnerImpl::Initialize()
#10 0x556d927348f8 headless::HeadlessContentMainDelegate::RunProcess()
#11 0x556d8e4b4160 content::RunNamedProcessTypeMain()
#12 0x556d8e4b4ab6 content::ContentMainRunnerImpl::Run()
#13 0x556d8e4bdd59 service_manager::Main()
#14 0x556d8e4b3661 content::ContentMain()
#15 0x556d927339f8 headless::(anonymous namespace)::RunContentMain()
#16 0x556d92733a6e headless::HeadlessBrowserMain()
#17 0x556d8e4bac49 headless::HeadlessShellMain()
#18 0x556d8cd6a1c4 ChromeMain
#19 0x7f8b55554f4a __libc_start_main
#20 0x556d8cd6a02a _start
  r8: 0000000000000000  r9: 00007ffdf09a60b0 r10: 0000000000000008 r11: 0000000000000246
 r12: 00007ffdf09a67b8 r13: 0000000000000161 r14: 00007ffdf09a67c0 r15: 00007ffdf09a6359
  di: 0000000000000002  si: 00007ffdf09a60b0  bp: 00007ffdf09a6300  bx: 0000000000000006
  dx: 0000000000000000  ax: 0000000000000000  cx: 00007f8b55568860  sp: 00007ffdf09a60b0
  ip: 00007f8b55568860 efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/home/megadyne/myapp/fixpuppeteer/node_modules/puppeteer/lib/Launcher.js:239:14)
    at Interface.helper.addEventListener (/home/megadyne/myapp/fixpuppeteer/node_modules/puppeteer/lib/Launcher.js:228:50)
    at Interface.emit (events.js:132:15)
    at Interface.close (readline.js:379:8)
    at Socket.onend (readline.js:152:10)
    at Socket.emit (events.js:132:15)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:114:19)
(node:2685) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2685) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by oleksiivo** [comment]
the same

**Comment by aslushnikov** [comment]
This is a chromium issue. We don't deal with internals of chromium sandboxing and won't be able to help, please file upstream to the https://crbug.com/new.

**Comment by Niceplace** [comment]
@bobajeff Getting the same thing too, have you found a workaround ?

Distro : Antergos (Arch)
Kernel: 4.16.13-2-ARCH

However, in the config If I manually specify the executable to use /usr/bin/chromium it works.

**Comment by banyomarci** [comment]
@bobajeff  Maybe you should try enabling user namespace cloning
```sh 
sudo sysctl -w kernel.unprivileged_userns_clone=1
```
