### ISSUE TITLE
Add URL to invalid address

### ISSUE THREAD

**Issue by gauntface** [puppeteer/puppeteer#2165]
Just got this error message:

```
/node_modules/puppeteer/lib/Page.js:520
  Rejected promise returned by test. Reason:
  Error {
    message: 'net::ERR_ADDRESS_INVALID',
  }
```

Would be helpful if Puppeteer added the problematic address to this error.

**Comment by Cardoso222** [comment]
You mean like a default 404 page ?

**Comment by jvelezpo** [comment]
Hello @gauntface can you please provide a little snipped 
i have tried to get an output like your but i havent got it
al i have got from a small test i added is this
```
Failures:
1) Page sebas should say sebas (test.js:3934:5)
  Message:
    net::ERR_INVALID_RESPONSE
  Stack:
    Error: net::ERR_INVALID_RESPONSE
        at navigate (/Users/sebastian/Desktop/TEMP/puppeteer/lib/Page.js:520:37)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by jvelezpo** [comment]
maybe you want something like this?
```
Failures:
1) Page sebas should say sebas (test.js:3934:5)
  Message:
    net::ERR_INVALID_RESPONSE at this url: http://ak.or.download.microsoft.com/download/F/2/2/
  Stack:
    Error: net::ERR_INVALID_RESPONSE at this url: http://ak.or.download.microsoft.com/download/F/2/2/
        at navigate (/Users/sebastian/Desktop/TEMP/puppeteer/lib/Page.js:525:37)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)
```
