### ISSUE TITLE
Cannot find context with specified id undefined

### ISSUE THREAD

**Issue by MildSYang** [puppeteer/puppeteer#2222]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.0
* Platform / OS version: window10
* URLs (if applicable): 
* Node.js version: 8.9.0

**What steps will reproduce the problem?**

  In my web page, the input box change will cause the refresh.
If there is no try catch, the project will crash. And print the error;
If I add a try catch, the project will be executed correctly and the crawl content is correct, but it still throws an exception.

_Please include code that reproduces the issue._

      { Error: Protocol error (Runtime.callFunctionOn): Cannot find context with specified id undefined
    at Promise (E:\work\blog\node_modules\_puppeteer@1.2.0@puppeteer\lib\Connection.js:198:56)
    at new Promise (<anonymous>)
    at CDPSession.send (E:\work\blog\node_modules\_puppeteer@1.2.0@puppeteer\lib\Connection.js:197:12)
    at JSHandle.jsonValue (E:\work\blog\node_modules\_puppeteer@1.2.0@puppeteer\lib\ExecutionContext.js:184:43)
    at ExecutionContext.evaluate (E:\work\blog\node_modules\_puppeteer@1.2.0@puppeteer\lib\ExecutionContext.js:47:33)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  message: 'Protocol error (Runtime.callFunctionOn): Cannot find context with specified id undefined' }

        // 循环获取每页内容
            for (let i of length) {
                let links = ''
                if (i !== 1) {
                    try {
                        await page.waitForSelector('.mh_headpager .mh_select')
                        await page.select('.mh_headpager .mh_select', i)
                    } catch (e) {
                        console.warn(e)
                    }
                }
                try {
                    await page.waitForSelector('.mh_comicpic img')
                    links = await page.$eval('.mh_comicpic img', e => e.src)
                } catch (e) {
                    console.warn(e)
                }

                this.pngList.push({
                    title: currentSection.title,
                    page: i,
                    links: links,
                })

            }

**What is the expected result?**
Do not use  try-catch
Do throws exception

**What happens instead?**
use  try-catch
throws exception

**Comment by dbuarque** [comment]
Hey @MildSYang, did you figure out how to solve this issue?

**Comment by MildSYang** [comment]
@dbuarque have no clue

**Comment by TotusSomnium** [comment]
getting this a lot after updating to 1.2.0. Does not happen if i downgrade back to 1.1.0

**Comment by KevinGrandon** [comment]
Probably the same issue as #1325

**Comment by sean-hill** [comment]
I get this all the stinking time

```sh
[ 08:20:51:179 ] Error: Protocol error (Runtime.callFunctionOn): Cannot find context with specified id undefined
    at Promise (/var/task/node_modules/puppeteer/lib/Connection.js:200:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/var/task/node_modules/puppeteer/lib/Connection.js:199:12)
    at ExecutionContext.evaluateHandle (/var/task/node_modules/puppeteer/lib/ExecutionContext.js:73:75)
    at ElementHandle.$ (/var/task/node_modules/puppeteer/lib/ElementHandle.js:252:50)
    at Frame.$ (/var/task/node_modules/puppeteer/lib/FrameManager.js:335:34)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7) +672ms
```

Typically when the page thinks it's done navigating, and I'm trying to access data from the page.

**Comment by aslushnikov** [comment]
Dupe of #1325. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
