### ISSUE TITLE
How to use complete Chrome？

### ISSUE THREAD

**Issue by yxs** [puppeteer/puppeteer#2228]
* Puppeteer version: 1.2.0 
* Platform / OS version: CentOS 7.4.1708
* Node.js version: 8.10.0

The sample code I used:
```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({args: ['--no-sandbox', '--disable-setuid-sandbox']});
  const page = await browser.newPage();
  await page.goto('https://www.baidu.com');
  await page.screenshot({path: 'example.png'});

  await browser.close();
})();
```
**problem**
After installing Centos dependencies and adding `{args: ['--no-sandbox', '--disable-setuid-sandbox']}` , I can run pupeteter in headless mode.

But when I added parameter `headless: false`.

`const browser = await puppeteer.launch({args: ['--no-sandbox', '--disable-setuid-sandbox'], headless: false});`

An error occurred:

```
(node:26244) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!

(chrome:26254): Gtk-WARNING **: cannot open display: 
[0319/160809.263548:ERROR:nacl_helper_linux.cc(310)] NaCl helper process running without a sandbox!
Most likely you need to configure your SUID sandbox correctly


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/root/node_modules/puppeteer/lib/Launcher.js:246:14)
    at Interface.helper.addEventListener (/root/node_modules/puppeteer/lib/Launcher.js:235:50)
    at emitNone (events.js:111:20)
    at Interface.emit (events.js:208:7)
    at Interface.close (readline.js:370:8)
    at Socket.onend (readline.js:149:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
(node:26244) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:26244) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
How can i fix it?

By the way, here are some additional error messages:
![image](https://user-images.githubusercontent.com/25861775/37586188-8449ee06-2b96-11e8-9601-9c712189eedb.png)

**Comment by yxs** [comment]
`ldd /usr/bin/Xorg`

This error has been solved

![image](https://user-images.githubusercontent.com/25861775/37632216-1ce832f8-2c28-11e8-8d9d-0328fb541878.png)
