### ISSUE TITLE
Network.getResponseBody fails for some pages (No resource with given identifier found undefined)

### ISSUE THREAD

**Issue by npetr** [puppeteer/puppeteer#2258]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.2.0
* Platform / OS version: Windows 10
* Node.js version: v9.9.0

**What steps will reproduce the problem?**
```javascript
const puppeteer = require('puppeteer');

// Event types to catch
const events = [
  'Page.loadEventFired',
  'Page.domContentEventFired',
  'Page.frameStartedLoading',
  'Page.frameAttached',
  'Network.requestWillBeSent',
  'Network.requestServedFromCache',
  'Network.dataReceived',
  'Network.responseReceived',
  'Network.resourceChangedPriority',
  'Network.loadingFinished',
  'Network.loadingFailed',
];

async function run() {
  // Create headless session
  const browser = await puppeteer.launch();
  const page = await browser.newPage();

  // Enable events listeners
  const client = await page.target().createCDPSession();
  await client.send('Page.enable');
  await client.send('Network.enable');

  // Log network traffic and page domain notifications
  events.forEach(eventName => {
      client.on(eventName, async listenerFunc => {
          console.log(eventName, listenerFunc, '\n');
          if (eventName == 'Network.loadingFinished') {
              const { body, base64Encoded } = await client.send('Network.getResponseBody', { "requestId": listenerFunc.requestId });
              console.log(`RESPONSE [${listenerFunc.requestId}] BASE64 [${base64Encoded}] BODY >>>${body}<<< \n`);
          }
      });
  });

  // Do not work for "www.forbes.com", but works well for "www.kernel.org"!
  await page.goto('https://www.forbes.com', { waitUntil: ['networkidle2', 'load', 'domcontentloaded'], timeout: 10000 });
  await page.screenshot({ path: 'forbes.png' });

  //console.log('DIE'); process.exit();
  await browser.close();  
}

run();
```

**What is the expected result?**
Passed without errors as for "www.kernel.org" (instead of "www.forbes.com").

**What happens instead?**
Errors occured for "www.forbes.com":
```
C:\Users\npetr\AppData\Roaming\npm>node forbes.js > forbes.log
(node:125168) UnhandledPromiseRejectionWarning: Error: Protocol error (Network.getResponseBody): No resource with given identifier found undefined
    at Promise (C:\Users\npetr\AppData\Roaming\npm\node_modules\puppeteer\lib\Connection.js:198:56)
    at new Promise (<anonymous>)
    at CDPSession.send (C:\Users\npetr\AppData\Roaming\npm\node_modules\puppeteer\lib\Connection.js:197:12)
    at CDPSession.client.on (C:\Users\npetr\AppData\Roaming\npm\forbes.js:33:60)
    at CDPSession.emit (events.js:180:13)
    at CDPSession._onMessage (C:\Users\npetr\AppData\Roaming\npm\node_modules\puppeteer\lib\Connection.js:217:12)
    at Connection._onMessage (C:\Users\npetr\AppData\Roaming\npm\node_modules\puppeteer\lib\Connection.js:117:19)
    at WebSocket.emit (events.js:180:13)
    at Receiver._receiver.onmessage (C:\Users\npetr\AppData\Roaming\npm\node_modules\ws\lib\WebSocket.js:141:47)
    at Receiver.dataMessage (C:\Users\npetr\AppData\Roaming\npm\node_modules\ws\lib\Receiver.js:389:14)
(node:125168) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:125168) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:125168) UnhandledPromiseRejectionWarning: Error: Protocol error (Network.getResponseBody): No resource with given identifier found undefined
    at Promise (C:\Users\npetr\AppData\Roaming\npm\node_modules\puppeteer\lib\Connection.js:198:56)
    at new Promise (<anonymous>)
    at CDPSession.send (C:\Users\npetr\AppData\Roaming\npm\node_modules\puppeteer\lib\Connection.js:197:12)
    at CDPSession.client.on (C:\Users\npetr\AppData\Roaming\npm\forbes.js:33:60)
    at CDPSession.emit (events.js:180:13)
    at CDPSession._onMessage (C:\Users\npetr\AppData\Roaming\npm\node_modules\puppeteer\lib\Connection.js:217:12)
    at Connection._onMessage (C:\Users\npetr\AppData\Roaming\npm\node_modules\puppeteer\lib\Connection.js:117:19)
    at WebSocket.emit (events.js:180:13)
    at Receiver._receiver.onmessage (C:\Users\npetr\AppData\Roaming\npm\node_modules\ws\lib\WebSocket.js:141:47)
    at Receiver.dataMessage (C:\Users\npetr\AppData\Roaming\npm\node_modules\ws\lib\Receiver.js:389:14)
(node:125168) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:125168) UnhandledPromiseRejectionWarning: Error: Protocol error (Network.getResponseBody): No resource with given identifier found undefined
    at Promise (C:\Users\npetr\AppData\Roaming\npm\node_modules\puppeteer\lib\Connection.js:198:56)
    at new Promise (<anonymous>)
    at CDPSession.send (C:\Users\npetr\AppData\Roaming\npm\node_modules\puppeteer\lib\Connection.js:197:12)
    at CDPSession.client.on (C:\Users\npetr\AppData\Roaming\npm\forbes.js:33:60)
    at CDPSession.emit (events.js:180:13)
    at CDPSession._onMessage (C:\Users\npetr\AppData\Roaming\npm\node_modules\puppeteer\lib\Connection.js:217:12)
    at Connection._onMessage (C:\Users\npetr\AppData\Roaming\npm\node_modules\puppeteer\lib\Connection.js:117:19)
    at WebSocket.emit (events.js:180:13)
    at Receiver._receiver.onmessage (C:\Users\npetr\AppData\Roaming\npm\node_modules\ws\lib\WebSocket.js:141:47)
    at Receiver.dataMessage (C:\Users\npetr\AppData\Roaming\npm\node_modules\ws\lib\Receiver.js:389:14)
(node:125168) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

**Comment by aslushnikov** [comment]
@npetr resources get dumped after page commits navigation. This can be easily reproduced with the following pptr script:

```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const [page] = await browser.pages();
  const response = await page.goto('https://example.com');
  // commit another navigation to kill all the resources from the previous navigation
  await page.reload();
  // throws the same protocol error
  console.log(await response.text());
  await browser.close();
})();
```

I'd recommend handling this error gracefully.

**Comment by mattzeunert** [comment]
Is there some way to stall navigation until reading the response buffer is complete?

**Comment by aslushnikov** [comment]
@mattzeunert you can intercept [navigation requests](https://pptr.dev/#?product=Puppeteer&version=v1.6.1&show=api-requestisnavigationrequest) and hold on responding however long you want.

**Comment by mattzeunert** [comment]
@aslushnikov Thanks, I'm doing that at the moment. The one downside I'm running into is that I can no longer access the encoded/gzipped content size.

**Comment by mattzeunert** [comment]
@aslushnikov Thanks, that does work. Right now I'm using `getResponseBodyForInterception` to get the response body.

My only issue is that `page.setRequestInterception(true);` means I lose access to the actual encoded download size, so `encodedDataLength` is always 0.

**Comment by mattzeunert** [comment]
@aslushnikov Do you happen to know where in the Chrome code I'd need to look if I wanted to disable dumping resources on navigation?

**Comment by aslushnikov** [comment]
@mattzeunert nah, unfortunately I'm not very familiar with chrome's network subsystem

**Comment by ghost** [comment]
> @mattzeunert you can intercept [navigation requests](https://pptr.dev/#?product=Puppeteer&version=v1.6.1&show=api-requestisnavigationrequest) and hold on responding however long you want.

That link is dead, how do I hold navigation requests? Wouldn't page.on('request') be async and not hold?

**Comment by gazeciarz** [comment]
Got the same problem as @dave-dm , any idea how to hold on the request intercept response when its navigation request? May I ask for any example code or any clue?

**Comment by gazeciarz** [comment]
If anyone will come with the same issue there is a nice article around that: https://medium.com/@jsoverson/using-chrome-devtools-protocol-with-puppeteer-737a1300bac0, with some modifications You can intercept responses using dev tools protocol directly.

**Comment by ggorlen** [comment]
In more recent versions of Puppeteer (tested on ^21.2.1), this now manifests as

```none
ProtocolError: Could not load body for this request. This might happen if the request is a preflight request.
```

which is reproduced by [this code](https://github.com/puppeteer/puppeteer/issues/2258#issuecomment-380647459).

**Comment by extension434** [comment]
@mattzeunert https://javascripter.space/questions/the-function-chromecookiesget-is-returning-undefined-or-causing-an-error-to-be-thrown
