### ISSUE TITLE
Windows 10 Error, debug.log

### ISSUE THREAD

**Issue by krll-k** [puppeteer/puppeteer#2273]
![image](https://user-images.githubusercontent.com/2174805/38001415-4f7404a0-3235-11e8-9044-b0c777fce073.png)

```904 warn domrrrrrru@1.0.0 No description
905 warn domrrrrrru@1.0.0 No repository field.
906 verbose stack Error: puppeteer@1.2.0 install: `node install.js`
906 verbose stack Exit status 1
906 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
906 verbose stack     at EventEmitter.emit (events.js:180:13)
906 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
906 verbose stack     at ChildProcess.emit (events.js:180:13)
906 verbose stack     at maybeClose (internal/child_process.js:936:16)
906 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
907 verbose pkgid puppeteer@1.2.0
908 verbose cwd C:\Users\Kirill\Desktop\domrrrrrru
909 verbose Windows_NT 10.0.16299
910 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "--save" "puppeteer"
911 verbose node v9.9.0
912 verbose npm  v5.6.0
913 error code ELIFECYCLE
914 error errno 1
915 error puppeteer@1.2.0 install: `node install.js`
915 error Exit status 1
916 error Failed at the puppeteer@1.2.0 install script.
916 error This is probably not a problem with npm. There is likely additional logging output above.
917 verbose exit [ 1, true ]```

**Comment by krll-k** [comment]
Solved a problem. I just closed Chrome

**Comment by JoelEinbinder** [comment]
Looks like you ran out of disk space. Puppeteer needs ~100mb free to download Chromium.
