### ISSUE TITLE
Need several same addScriptTag() before calling external own functions

### ISSUE THREAD

**Issue by sputnick-dev** [puppeteer/puppeteer#2282]
* Puppeteer version: 1.2.0
* Platform / OS version: archlinux x86_64
* Node.js version: 9.9.0

If I keep only the first `addScriptTag()` : 

```javascript
const puppeteer = require('puppeteer');

(async () => {
    let events = [];

    // need no sandbox and disable setuid to avoid fatal error FATAL:zygote_host_impl_linux.cc(126)
    const browser = await puppeteer.launch({headless: true, args: ['--no-sandbox', '--disable-setuid-sandbox']});
    const page = await browser.newPage();
    await page.setUserAgent('Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0')

    await page.goto('https://www.eurosport.fr/moto/championnat-du-monde-2/calendar-result.shtml', { waitUntil: 'networkidle2' });

    let xpath_selector = '//*[@id="col-left"]//a[@class="table-generic__row"'
        + ' and not(./div/div[@class="table-generic__item table-generic__item--check-green"])]';

    await page.addScriptTag({ path: './helperFunctions.js' });
    const urls = await page.evaluate((sel) => {
        return getElementsByXPath(sel)
            .map((elt) => 'https://www.eurosport.fr' + elt.getAttribute('href') );
    }, xpath_selector);

    for (let h = 0; h < urls.length; h++) {
        let url = urls[h];

        await page.goto(url);
        await page.waitForSelector('#col-left div.table-generic__item.table-generic__item--text-team');

        let date = await page.evaluate(() => {
            return document.querySelector('div:last-of-type > div[class="table-generic__header-cell table-generic__header-cell--100"]')
                .innerText;
        });

        let xpath1 = '//div[@class="table-generic__item table-generic__item--text-team" and text()="Course"]';
        let xpath2 = '../../div[@class="table-generic__cell table-generic__cell--50 table-generic__cell--align-right"]/div';

        // await page.addScriptTag({ path: './helperFunctions.js' });
        const hours_arr = await page.evaluate((sel1, sel2) => {
            return getElementsByXPath(sel1)
                .map((node) =>
                    getElementByXPath(sel2, node).innerText
                )
        }, xpath1, xpath2);

    }

    await browser.close();

    console.log(date);
    console.log(JSON.stringify(hours_arr, null, 4));

})();
```

helperFunctions.js (based on `casperjs.__utils__`) :
```javascript
window.getElementByXPath = (expression, scope) => {
    scope = scope || document;
    var a = document.evaluate(expression, scope, null, XPathResult.ORDERED_NODE_SNAPSHOT_TYPE, null);
    if (a.snapshotLength > 0) {
        return a.snapshotItem(0);
    }
};

window.getElementsByXPath = (expression, scope) => {
    scope = scope || document;
    var nodes = [];
    var a = document.evaluate(expression, scope, null, XPathResult.ORDERED_NODE_SNAPSHOT_TYPE, null);
    for (var i = 0; i < a.snapshotLength; i++) {
        nodes.push(a.snapshotItem(i));
    }
    return nodes;
};
```

## Error : 
```
(node:32575) UnhandledPromiseRejectionWarning: Error: Evaluation failed: ReferenceError: getElementsByXPath is not defined
    at <anonymous>:2:13
    at ExecutionContext.evaluateHandle (/home/sputnick/node_modules/puppeteer/lib/ExecutionContext.js:70:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
(node:32575) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:32575) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

If instead I uncomment the second `addScriptTag()`from the script above, I get the expected object output and no error

**Comment by marijanlekic** [comment]
After await page.goto(url) first added script is not available...

Not sure whats happening in puppeteer with page if url is just a route in some js framework, will it reload a page...

**Comment by sputnick-dev** [comment]
Can't the lib add scripts to each new page automatically ? 

IIRC, it's the behavior of casperjs

**Comment by tomgallagher** [comment]
Need to find an event to hook onto where you can add the script tags on each new page load.

**Comment by aslushnikov** [comment]
@sputnick-dev  Looks like sudden page reload kills the added script.

Instead of using `page.addScriptTag`, you can use [`page.evaluateOnNewDocument`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageevaluateonnewdocumentpagefunction-args) to inject your helper functions. This way they will survive page navigations:

```js
await page.evaluateOnNewDocument(fs.readFileSync('./helperFunctions.js', 'utf8'));
```

**Comment by tomgallagher** [comment]
Except page.evaluateOnNewDocument runs when every frame in the page loads. Chome Extensions offer the option of single injection and run at document_start, as does Phantom JS and Casper JS. This kind of functionality is useful and quite commonplace.

**Comment by tomgallagher** [comment]
The closest I've got to a workable solution is this:

```
page.on('framenavigated', async frame => {
        if (frame !== page.mainFrame()) { return; } 
        else {
            await page.addScriptTag({path: './lib/browser_extensions/some.js'});
            await page.addScriptTag({path: './lib/browser_extensions/more.js'});
            
        }
});
```
But it still does not inject the JS fast enough to use, say, mutation observers to catch all changes to the HTML.

**Comment by aslushnikov** [comment]
> Except page.evaluateOnNewDocument runs when every frame in the page loads.

@tomgallagher it runs as frame's document instance gets created. It's the earliest you get to run javascript.

**Comment by 5t4rdu5t** [comment]
Thanks all (sputnick-dev on another account)

**Comment by Mementoerwin** [comment]
I think this https://pythoner.space/questions/returning-from-a-callback-in-an-external-javascript-script-a-guide could streamline your process
