### ISSUE TITLE
Page.click(selector) or Handle.click throws error with target closed

### ISSUE THREAD

**Issue by evenstensberg** [puppeteer/puppeteer#2309]
**Tell us about your environment:**

* Puppeteer version: 1.2
* Platform / OS version: Macbook Pro 2017 10.13.3 / Darwin
* URLs (if applicable): uit.no/canvas
* Node.js version: 9.6.1

**What steps will reproduce the problem?**
1.
Run this file:

```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  const response = await page.goto('https://uit.no/canvas')
  const listHandle =
      await page.$('div.selectize-input.items.not-full.has-options')
  const hndle = listHandle.asElement()
  page.click('div.selectize-input.items.not-full.has-options')
  await browser.close();
})();
```

**What is the expected result?**
Puppeteer doesn't throw on clicked element.

**What happens instead?**
```js
(node:77224) UnhandledPromiseRejectionWarning: Error: Protocol error (Runtime.callFunctionOn): Target closed.
    at Promise (/Users/ev1stensberg/Documents/GitHub/canvas-to-gh/node_modules/puppeteer/lib/Connection.js:198:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/Users/ev1stensberg/Documents/GitHub/canvas-to-gh/node_modules/puppeteer/lib/Connection.js:197:12)
    at ExecutionContext.evaluateHandle (/Users/ev1stensberg/Documents/GitHub/canvas-to-gh/node_modules/puppeteer/lib/ExecutionContext.js:71:75)
    at ElementHandle.$ (/Users/ev1stensberg/Documents/GitHub/canvas-to-gh/node_modules/puppeteer/lib/ElementHandle.js:212:50)
    at Frame.$ (/Users/ev1stensberg/Documents/GitHub/canvas-to-gh/node_modules/puppeteer/lib/FrameManager.js:308:34)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:77224) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:77224) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

> This method scrolls element into view if needed, and then uses page.mouse to click in the center of the element. If the element is detached from DOM, the method throws an error.

But doing the same thing ( queryselect on element ) inside chrome devtools doesn't throw. Why's that? The DOM node is not in shadow DOM

**Comment by vsemozhetbyt** [comment]
You need one more `await`;
```js
  await page.click('div.selectize-input.items.not-full.has-options')
```

**Comment by evenstensberg** [comment]
Okay, I'll try it out, thanks!

**Comment by KhyatiShah007** [comment]
@evenstensberg did this work for you?
