### ISSUE TITLE
`npm install puppeteer` dosen't work

### ISSUE THREAD

**Issue by danhab99** [puppeteer/puppeteer#2389]
### Steps to reproduce

`sudo npm install puppeteer`

Returns:

```
npm WARN package.json blockiumbot@1.0.0 No description
npm WARN package.json blockiumbot@1.0.0 No repository field.
npm WARN package.json blockiumbot@1.0.0 No README data
npm WARN engine puppeteer@1.3.0: wanted: {"node":">=6.4.0"} (current: {"node":"4.8.2","npm":"1.4.21"})
/
> puppeteer@1.3.0 install /home/pi/Documents/blockiumBot/node_modules/puppeteer
> node install.js

/home/pi/Documents/blockiumBot/node_modules/puppeteer/install.js:80
let progressBar = null;
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! puppeteer@1.3.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@1.3.0 install script.
npm ERR! This is most likely a problem with the puppeteer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls puppeteer
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.9.80+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "puppeteer"
npm ERR! cwd /home/pi/Documents/blockiumBot
npm ERR! node -v v4.8.2
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/Documents/blockiumBot/npm-debug.log
npm ERR! not ok code 0
```

**Tell us about your environment:**

* Puppeteer version: [UNINSTALLABLE, so latest]
* Platform / OS version: Node / Raspbian GNU/Linux 9 (stretch)
* URLs (if applicable): [Proprietary]
* Node.js version: v9.10.1

**What steps will reproduce the problem?**

`sudo npm install puppeteer`

**What is the expected result?**

For puppeteer to be installed and working like on windows

**What happens instead?**

It doesn't work

**Comment by vsemozhetbyt** [comment]
See:
```
npm WARN engine puppeteer@1.3.0: wanted: {"node":">=6.4.0"} (current: {"node":"4.8.2","npm":"1.4.21"})
```

https://github.com/GoogleChrome/puppeteer#usage :

> Caution: Puppeteer requires at least Node v6.4.0...
