### ISSUE TITLE
 Error: Timed out after 30000 ms while trying to connect to Chrome! 

### ISSUE THREAD

**Issue by Swiffers** [puppeteer/puppeteer#2399]
(node:20081) UnhandledPromiseRejectionWarning: Error: Timed out after 30000 ms while trying to connect to Chrome! The only Chrome revision guaranteed to work is r549031
    at Timeout.onTimeout (/home/ubuntu/affiliate/node_modules/puppeteer/lib/Launcher.js:266:14)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)

**Comment by Swiffers** [comment]
The error was on ubuntu, 

The [message of alex88](https://github.com/GoogleChrome/puppeteer/issues/404) helped me to fix the issue.
