### ISSUE TITLE
(node:20233) UnhandledPromiseRejectionWarning: Error: socket hang up

### ISSUE THREAD

**Issue by hyahm** [puppeteer/puppeteer#2430]
### os
[root@hyahm node]# cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core

### version : 
[root@hyahm node]# node -v
v8.11.1
[root@hyahm node]# npm -v
5.6.0

### install   puppeteer
```
[root@hyahm node]# cnpm i puppeteer
✔ Installed 1 packages
✔ Linked 39 latest versions
Downloading Chromium r549031 - 97 Mb [====================] 100% 0.0s
Chromium downloaded to /opt/node/node_modules/_puppeteer@1.3.0@puppeteer/.local-chromium/linux-549031
✔ Run 1 scripts
✔ All packages installed (41 packages installed from npm registry, used 14s, speed 37.52kB/s, json 40(518.66kB), tarball 0B)
```
### test.js:
```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({args: ['--no-sandbox']});
  const page = await browser.newPage();
  await page.goto('https://www.baidu.com');
  await page.screenshot({path: 'example.png'});
  await browser.close();
})();
```

### run it error 
```
[root@hyahm node]# node test.js
(node:20233) UnhandledPromiseRejectionWarning: Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at Socket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:20233) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20233) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
in mac ,run it ok

**Comment by yrshaikh** [comment]
https://github.com/GoogleChrome/puppeteer/issues/391 might be related.

**Comment by hyahm** [comment]
need depend
```
yum install pango.x86_64 libXcomposite.x86_64 libXcursor.x86_64 libXdamage.x86_64 libXext.x86_64 libXi.x86_64 libXtst.x86_64 cups-libs.x86_64 libXScrnSaver.x86_64 libXrandr.x86_64 GConf2.x86_64 alsa-lib.x86_64 atk.x86_64 gtk3.x86_64 -y
```
