### ISSUE TITLE
Cannot find module 'puppeteer/utils/ChromiumDownloader'

### ISSUE THREAD

**Issue by CoreyCole** [puppeteer/puppeteer#2680]
**Tell us about your environment:**

* Puppeteer version: 1.4.0
* Platform / OS version: Mac OSX 10.13.4
* Node.js version: 8.11.1

**What steps will reproduce the problem?**
1. In an angular cli project, I modified my `karma.conf.js` file (following guidance from @ebidel's post [here](https://developers.google.com/web/updates/2017/06/headless-karma-mocha-chai) except that I'm using `jasmine` and `@angular-devkit/build-angular`, not `mocha` and `chai`):
```javascript
const Downloader = require('puppeteer/utils/ChromiumDownloader');
const { chromium_revision } = require('puppeteer/package.json').puppeteer;
const info = Downloader.revisionInfo(Downloader.currentPlatform(), chromium_revision);
console.log(info);

process.env.CHROME_BIN = info.executablePath();

module.exports = function (config) {
    config.set({
        basePath: '',
        frameworks: ['jasmine', '@angular-devkit/build-angular'],
        plugins: [
            require('karma-jasmine'),
            require('karma-jasmine-html-reporter'),
            require('karma-coverage-istanbul-reporter'),
            require('@angular-devkit/build-angular/plugins/karma')
        ],
        client: {
            clearContext: false // leave Jasmine Spec Runner output visible in browser
        },
        coverageIstanbulReporter: {
            dir: require('path').join(__dirname, '../coverage'),
            reports: ['html', 'lcovonly'],
            fixWebpackSourcePaths: true
        },
        reporters: ['progress', 'kjhtml'],
        port: 9876,
        colors: true,
        logLevel: config.LOG_INFO,
        autoWatch: false,
        browsers: ['Chrome', 'ChromeHeadless', 'MyHeadlessChrome'],
        customLaunchers: {
            MyHeadlessChrome: {
                base: 'ChromeHeadless',
                flags: [
                    '--headless',
                    '--disable-gpu',
                    '--no-sandbox',
                    '--remote-debugging-port=9222',
                ]
            }
        },

        // Continuous Integration mode if true, Karma captures browsers, runs the tests and exits
        singleRun: true
    });
};
```
2. Modified `npm run test` command:
```
ng test --browsers MyHeadlessChrome
```
3. And I get error:
```
05 06 2018 18:02:17.510:ERROR [config]: Invalid config file!
  Error: Cannot find module 'puppeteer/utils/ChromiumDownloader'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/src/karma.conf.js:4:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.parseConfig (<snip>/node_modules/karma/lib/config.js:363:22)
    at new Server (<snip>/node_modules/karma/lib/server.js:56:20)
    at Observable.rxjs_1.Observable.obs [as _subscribe] (<snip>/node_modules/@angular-devkit/build-angular/src/karma/packages/angular_devkit/build_angular/src/karma/index.ts:92:29)
    at Observable.subscribe (<snip>/node_modules/rxjs/src/internal/Observable.ts:197:63)
```

Here is my devDependencies in package.json- I have puppeteer and karma-chrome-launcher
```json
"devDependencies": {
    "@angular-devkit/build-angular": "~0.6.5",
    "@angular/cli": "~6.0.7",
    "@angular/compiler-cli": "^6.0.3",
    "@angular/language-service": "^6.0.3",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "^2.2.0",
    "karma-coverage-istanbul-reporter": "~1.4.2",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-phantomjs-launcher": "^1.0.4",
    "protractor": "~5.3.0",
    "puppeteer": "^1.4.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "~2.7.2"
}
```

When I do a fresh npm install
```
rm -rf node_modules && rm package-lock.json && npm i
```

I see
```
Downloading Chromium r555668 - 76.4 Mb [====================] 100% 0.0s
Chromium downloaded to <snip>/node_modules/puppeteer/.local-chromium/mac-555668
```

So I know it's getting downloaded.

Is `puppeteer/utils/ChromiumDownloader` deprecated?
```
require('puppeteer/utils/ChromiumDownloader');
```

Or am I doing something wrong / have a corrupt installation on my local computer

**Comment by CoreyCole** [comment]
Looking in commit history I found that ChromiumDownload moved from util to lib?
https://github.com/GoogleChrome/puppeteer/commit/9a5086847c3a9e489da30c9fcd80ca86938440a4#diff-2b3583e6e17721c54496bd04e57a0c15

So, I tried changing to `BrowserFetcher`
```javascript
const BrowserFetcher = require('puppeteer/lib/BrowserFetcher');
const { chromium_revision } = require('puppeteer/package.json').puppeteer;
const info = BrowserFetcher.revisionInfo(chromium_revision);
```

And got
```
06 06 2018 12:28:00.999:ERROR [config]: Invalid config file!
  TypeError: BrowserFetcher.revisionInfo is not a function
```

But I see `revisionInfo()` in `BrowserFetcher.js` (in my local `node_modules`)
```javascript
  /**
   * @param {string} revision
   * @return {!BrowserFetcher.RevisionInfo}
   */
  revisionInfo(revision) {
    const folderPath = this._getFolderPath(revision);
    let executablePath = '';
    if (this._platform === 'mac')
      executablePath = path.join(folderPath, 'chrome-mac', 'Chromium.app', 'Contents', 'MacOS', 'Chromium');
    else if (this._platform === 'linux')
      executablePath = path.join(folderPath, 'chrome-linux', 'chrome');
    else if (this._platform === 'win32' || this._platform === 'win64')
      executablePath = path.join(folderPath, 'chrome-win32', 'chrome.exe');
    else
      throw 'Unsupported platform: ' + this._platform;
    let url = downloadURLs[this._platform];
    url = util.format(url, this._downloadHost, revision);
    const local = fs.existsSync(folderPath);
    return {revision, executablePath, folderPath, local, url};
  }
```

Also, in the API docs
https://github.com/GoogleChrome/puppeteer/blob/v1.4.0/docs/api.md#browserfetcherrevisioninforevision

**Comment by CoreyCole** [comment]
Closing this because my problem is not related to `Cannot find module 'puppeteer/utils/ChromiumDownloader'` anymore

**Comment by CoreyCole** [comment]
Btw, for anyone else arriving here from google:
```
process.env.CHROME_BIN = require('puppeteer').executablePath();
```
I think is the correct way to get the `executablePath` now

**Comment by prasadmadv** [comment]
ERROR in ./node_modules/puppeteer/node6/lib/FrameManager.js
Module not found: Error: Can't resolve 'fs' in 'D:\xampp\htdocs\repos\easyshopify\node_modules\puppeteer\node6\lib'
 @ ./node_modules/puppeteer/node6/lib/FrameManager.js 17:11-24
 @ ./node_modules/puppeteer/node6/lib/Page.js
 @ ./node_modules/puppeteer/node6/lib/Target.js
 @ ./node_modules/puppeteer/node6/lib/Browser.js
 @ ./node_modules/puppeteer/node6/lib/Launcher.js
 @ ./node_modules/puppeteer/node6/lib/Puppeteer.js
 @ ./node_modules/puppeteer/index.js
 @ ./resources/assets/js/components/Example.js
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss


Cant resolve 'fs' where fs module is already installed.
