### ISSUE TITLE
 JSON.stringify() not work in evaluate

### ISSUE THREAD

**Issue by amourfrei** [puppeteer/puppeteer#2682]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:1.4.0
* Platform / OS version:macOS X 10.12.6
* URLs (if applicable):
* Node.js version:9.8.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```javascript
                let performance = JSON.parse(await page.evaluate(() => {
                   let total = window.performance
                   let entries = total.getEntries()
                   return JSON.stringify({ total, entries })
                }))
                console.log(performance, 'performance-timing')
```

**What is the expected result?**
return performance Object.

**What happens instead?**
Got error:
```
UnhandledPromiseRejectionWarning: Error: Evaluation failed: ReferenceError: _stringify2 is not defined
    at <anonymous>:4:57
    at ExecutionContext.evaluateHandle (/Users/amour/privately/web-performance-monitoring-system/node_modules/_puppeteer@1.4.0@puppeteer/lib/ExecutionContext.js:88:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
```

**Comment by vsemozhetbyt** [comment]
Cannot reproduce on Windows 7 x64 with puppeteer 1.4.0-post (Chromium r564778) and this code:
```js
const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch();
    const [page] = await browser.pages();

    await page.goto('https://example.org/');

    let performance = JSON.parse(await page.evaluate(() => {
      let total = window.performance
      let entries = total.getEntries()
      return JSON.stringify({ total, entries })
    }));
    console.log(performance, 'performance-timing');

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```

**Comment by meetDeveloper** [comment]
It happened with me too.

**Comment by jkryanchou** [comment]
Me too

**Comment by chenzezhang** [comment]
const timing = await page.evaluate(() => (window.performance.timing.toJSON()));
