### ISSUE TITLE
Integration with Lighthouse breaks only on localhost

### ISSUE THREAD

**Issue by 29rayb** [puppeteer/puppeteer#2731]
```
Error:
11:47:38 [Temp Tests] Unhandled Rejection at: Promise Promise {
11:47:38 [Temp Tests]   <rejected> Error: You probably have multiple tabs open to the same origin.
11:47:38 [Temp Tests]     at versions.forEach.ver (/home/jenkins/workspace/or_Pipeline_ray9656_jenkins-K4TELRXZ2GGXTCMJMLMVULSDKD4IGNTMJLVG7MI2QWX3S5ZZL4BQ/builder/node_modules/lighthouse/lighthouse-core/gather/driver.js:354:21)
11:47:38 [Temp Tests]     at Array.forEach (<anonymous>)
11:47:38 [Temp Tests]     at registrations.filter.forEach.reg (/home/jenkins/workspace/or_Pipeline_ray9656_jenkins-K4TELRXZ2GGXTCMJMLMVULSDKD4IGNTMJLVG7MI2QWX3S5ZZL4BQ/builder/node_modules/lighthouse/lighthouse-core/gather/driver.js:346:20)
11:47:38 [Temp Tests]     at Array.forEach (<anonymous>)
11:47:38 [Temp Tests]     at getServiceWorkerRegistrations.then.then.then.then._ (/home/jenkins/workspace/or_Pipeline_ray9656_jenkins-K4TELRXZ2GGXTCMJMLMVULSDKD4IGNTMJLVG7MI2QWX3S5ZZL4BQ/builder/node_modules/lighthouse/lighthouse-core/gather/driver.js:345:10)
11:47:38 [Temp Tests]     at <anonymous>
11:47:38 [Temp Tests]     at process._tickCallback (internal/process/next_tick.js:188:7) } reason:  Error: You probably have multiple tabs open to the same origin.
11:47:38 [Temp Tests]     at versions.forEach.ver (/home/jenkins/workspace/or_Pipeline_ray9656_jenkins-K4TELRXZ2GGXTCMJMLMVULSDKD4IGNTMJLVG7MI2QWX3S5ZZL4BQ/builder/node_modules/lighthouse/lighthouse-core/gather/driver.js:354:21)
11:47:38 [Temp Tests]     at Array.forEach (<anonymous>)
11:47:38 [Temp Tests]     at registrations.filter.forEach.reg (/home/jenkins/workspace/or_Pipeline_ray9656_jenkins-K4TELRXZ2GGXTCMJMLMVULSDKD4IGNTMJLVG7MI2QWX3S5ZZL4BQ/builder/node_modules/lighthouse/lighthouse-core/gather/driver.js:346:20)
11:47:38 [Temp Tests]     at Array.forEach (<anonymous>)
11:47:38 [Temp Tests]     at getServiceWorkerRegistrations.then.then.then.then._ (/home/jenkins/workspace/or_Pipeline_ray9656_jenkins-K4TELRXZ2GGXTCMJMLMVULSDKD4IGNTMJLVG7MI2QWX3S5ZZL4BQ/builder/node_modules/lighthouse/lighthouse-core/gather/driver.js:345:10)
11:47:38 [Temp Tests]     at <anonymous>
11:47:38 [Temp Tests]     at process._tickCallback (internal/process/next_tick.js:188:7)
11:47:38 [Temp Tests] events.js:183
11:47:38 [Temp Tests]       throw er; // Unhandled 'error' event
11:47:38 [Temp Tests]       ^
11:47:38 [Temp Tests] 
11:47:38 [Temp Tests] Error: connect ECONNREFUSED 127.0.0.1:37142
11:47:38 [Temp Tests]     at Object._errnoException (util.js:992:11)
11:47:38 [Temp Tests]     at _exceptionWithHostPort (util.js:1014:20)
11:47:38 [Temp Tests]     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
11:47:38 [Temp Tests] npm ERR! code ELIFECYCLE
11:47:38 [Temp Tests] npm ERR! errno 1
11:47:38 [Temp Tests] npm ERR! builder@0.1.0 lighthouse-jenkins-test: `node puplighthouse.js`
11:47:38 [Temp Tests] npm ERR! Exit status 1
11:47:38 [Temp Tests] npm ERR! 
11:47:38 [Temp Tests] npm ERR! Failed at the builder@0.1.0 lighthouse-jenkins-test script.
11:47:38 [Temp Tests] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
11:47:39 [Temp Tests] 
11:47:39 [Temp Tests] npm ERR! A complete log of this run can be found in:
11:47:39 [Temp Tests] npm ERR!     /var/lib/jenkins/.npm/_logs/2018-06-19T18_47_38_974Z-debug.log
11:47:39 [Temp Tests] 
11:47:39 [Temp Tests] INFO: Gracefully shutting down. Please wait...
11:47:39 [Temp Tests] { Error: Command failed: npm run lighthouse-jenkins-test
11:47:39 [Temp Tests]     at makeError (/home/jenkins/workspace/or_Pipeline_ray9656_jenkins-K4TELRXZ2GGXTCMJMLMVULSDKD4IGNTMJLVG7MI2QWX3S5ZZL4BQ/builder/node_modules/start-server-and-test/node_modules/execa/index.js:172:9)
11:47:39 [Temp Tests]     at Promise.all.then.arr (/home/jenkins/workspace/or_Pipeline_ray9656_jenkins-K4TELRXZ2GGXTCMJMLMVULSDKD4IGNTMJLVG7MI2QWX3S5ZZL4BQ/builder/node_modules/start-server-and-test/node_modules/execa/index.js:277:16)
11:47:39 [Temp Tests]     at <anonymous>
11:47:39 [Temp Tests]     at process._tickCallback (internal/process/next_tick.js:188:7)
11:47:39 [Temp Tests]   code: 1,
11:47:39 [Temp Tests]   stdout: null,
11:47:39 [Temp Tests]   stderr: null,
11:47:39 [Temp Tests]   failed: true,
11:47:39 [Temp Tests]   signal: null,
11:47:39 [Temp Tests]   cmd: 'npm run lighthouse-jenkins-test',
11:47:39 [Temp Tests]   timedOut: false,
11:47:39 [Temp Tests]   killed: false }
11:47:39 [Temp Tests] error Command failed with exit code 1.
```

```
const puppeteer = require('puppeteer');
const lighthouse = require('lighthouse');
const {URL} = require('url');
const ReportGenerator = require('lighthouse/lighthouse-core/report/report-generator');
const fs = require('fs');

const HOME_PAGE = 'http://localhost:9000/';

const opts = {
  chromeFlags: ['--headless', '--no-sandbox', '--disable-gpu', '--disable-setuid-sandbox', '--disable-dev-shm-usage'],
}

async function createNewBrowser() {
  const browser = await puppeteer.launch({
    args: opts.chromeFlags
  })
  return browser;
}

async function createNewPage(browser) {
  const page = await browser.newPage();
  return page;
}


async function run() {
  const browser = await createNewBrowser();
  const page = await createNewPage(browser);

  process.on("unhandledRejection", async (reason, p) => {
    console.error("Unhandled Rejection at: Promise", p, "reason: ", reason);
    browser.close();
  });

  await page.goto(HOME_PAGE);

  await home_lighthouse(browser) 
  browser.close();
}

function generateReport(lhr){
  const htmlReportAssets = require('lighthouse/lighthouse-core/report/html/html-report-assets');

  const sanitizedJson = JSON.stringify(lhr)
    .replace(/</g, '\\u003c') // replaces opening script tags
    .replace(/\u2028/g, '\\u2028') // replaces line separators ()
    .replace(/\u2029/g, '\\u2029'); // replaces paragraph separators
  const sanitizedJavascript = htmlReportAssets.REPORT_JAVASCRIPT.replace(/<\//g, '\\u003c/');

  return ReportGenerator.replaceStrings(htmlReportAssets.REPORT_TEMPLATE, [
    {search: '%%LIGHTHOUSE_JSON%%', replacement: sanitizedJson},
    {search: '%%LIGHTHOUSE_JAVASCRIPT%%', replacement: sanitizedJavascript},
    {search: '/*%%LIGHTHOUSE_CSS%%*/', replacement: htmlReportAssets.REPORT_CSS},
    {search: '%%LIGHTHOUSE_TEMPLATES%%', replacement: htmlReportAssets.REPORT_TEMPLATES},
  ]);
}

async function home_lighthouse(browser) {
  // BREAKS HERE
  const {lhr} = await lighthouse(HOME_PAGE, {
    port: (new URL(browser.wsEndpoint())).port,
    output: 'json',
    logLevel: 'info'
  });

  const lighthouse_results = generateReport(lhr);

  fs.writeFile('lighthouse-reports/lighthouse-home-report.html', lighthouse_results, 'utf8', function(err){
    if (err) return console.log(err);
    console.log('home-lighthouse file was saved');
  });
}

run();
```

```
lighthouse: 3.0.0-alpha.2
"puppeteer": "^1.5.0",
```

So in the jenkins I run the lp:ci command:

    "lp:ci": "start-server-and-test l:start http://localhost:3000 lighthouse-jenkins-test",
    "l:start": "serve -s -l 3000 build",
    "lighthouse-jenkins-test": "node puplighthouse.js",
Then I launch Puppeteer and when it tries to generate the first Lighthouse Report on localhost:9000 (with the code above), it breaks with the above error.

It's able to generate the lighthouse reports on public URLs like example.com twitter.com it works flawlessly.

But what I don't get is why it won't work on the PC for localhost (I've tried changing the port to like 7000, and it still doesn't work while it works on the VM with the same specs and locally on my Mac).
I've also made sure that port 3000 isn't in use prior to me starting the server.

**What is the expected result?**
Expect to generate a lighthouse report successfully for page opened by Puppeteer on localhost:9000

**What happens instead?**
Does not work on PC (RHLS 7.4) while it works on VM (RHLS 7.4) and locally on MacOS

I have read: [link](https://github.com/GoogleChrome/puppeteer/issues/1390) but it doesn't seem to take care of the error...

I'm out of ideas as I have nearly tried everything I could think of..

**Comment by aslushnikov** [comment]
Weird. It throws some `'Error: You probably have multiple tabs open to the same origin.'` - it has nothing to do with puppeteer.

I'd try asking lighthouse folks, they might have an idea of what's going on here.
