### ISSUE TITLE
`browser.newPage ` Error: socket hang up

### ISSUE THREAD

**Issue by zhilidali** [puppeteer/puppeteer#2734]
**environment:**

* Puppeteer version: 1.4.0
* Platform / OS version:  ubuntu 16.04 LTS
* Node.js version: 6.11.3
* running as root

**code**
```js
 const browser = await puppeteer.launch({
      timeout: 20000,
      args: ['--no-sandbox', '--disable-setuid-sandbox']
    });

    const page  = await browser.newPage();
    console.log('get page'); // cannot print
   // code...
```

**error**
```js
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
    at createHangUpError (_http_client.js:254:15)
    at Socket.socketOnEnd (_http_client.js:346:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

pls help，how to fix this ?

**Comment by zhilidali** [comment]
`$ ./node_modules/puppeteer/.local-chromium/linux-564778/chrome-linux/chrome --no-sandbox
`
output: 
```sh
[0614/081525.917606:FATAL:thread_helpers.cc(44)] Check failed: 3UL <= task_stat.st_nlink (3 vs. 2)
#0 0x7fffff214f9c <unknown>
#1 0x7fffff1ebc70 <unknown>
#2 0x7fffff22aa89 <unknown>
#3 0x7fffff16e588 <unknown>
#4 0x7fffff16c364 <unknown>
#5 0x7ffffd020830 <unknown>
#6 0x7fffff16c02a <unknown>

[96244:96244:0614/081525.956607:ERROR:nacl_fork_delegate_linux.cc(314)] Bad NaCl helper startup ack (-1 bytes)
[96244:96244:0614/081525.957458:FATAL:thread_helpers.cc(44)] Check failed: 3UL <= task_stat.st_nlink (3 vs. 2)
#0 0x7ffffab67bac <unknown>
#1 0x7ffffaaf5a30 <unknown>
#2 0x7ffffbdf0049 <unknown>
#3 0x7ffffbdf0097 <unknown>
#4 0x7ffffbe49654 <unknown>
#5 0x7ffffa81d482 <unknown>
#6 0x7ffffa81ec26 <unknown>
#7 0x7ffffa827c32 <unknown>
#8 0x7ffffa81ccc4 <unknown>
#9 0x7ffff8db21b3 <unknown>
#10 0x7fffec620830 <unknown>
#11 0x7ffff8db202a <unknown>

Received signal 6
#0 0x7ffffab67bac <unknown>
#1 0x7ffffab67711 <unknown>
#2 0x7ffff5c11390 <unknown>
#3 0x7fffec635428 <unknown>
#4 0x7fffec63702a <unknown>
#5 0x7ffffab66565 <unknown>
#6 0x7ffffaaf5e99 <unknown>
#7 0x7ffffbdf0049 <unknown>
#8 0x7ffffbdf0097 <unknown>
#9 0x7ffffbe49654 <unknown>
#10 0x7ffffa81d482 <unknown>
#11 0x7ffffa81ec26 <unknown>
#12 0x7ffffa827c32 <unknown>
#13 0x7ffffa81ccc4 <unknown>
#14 0x7ffff8db21b3 <unknown>
#15 0x7fffec620830 <unknown>
#16 0x7ffff8db202a <unknown>
  r8: 00007fffec9c5770  r9: 00007ffff6260a80 r10: 0000000000000008 r11: 0000000000000246
 r12: 00007fffffefe788 r13: 000000000000006e r14: 00007fffffefe790 r15: 00007fffffefe798
  di: 00000000000177f4  si: 00000000000177f4  bp: 00007fffffefe240  bx: 00007fffffefe2b0
  dx: 0000000000000006  ax: 0000000000000000  cx: 0000000000000008  sp: 00007fffffefe108
  ip: 00007fffec635428 efl: 0000000000000202 cgf: 004b000000000053 erf: 0000000000000007
 trp: 000000000000000e msk: 00007fffffefddd0 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.

```

**Comment by zhilidali** [comment]
`ldd  ./node_modules/puppeteer/.local-chromium/linux-564778/chrome-linux/chrome | more`
output:

```sh
linux-vdso.so.1 =>  (0x00007fffff45c000)
libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ffff6000000)
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ffff5c00000)
librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007ffff5800000)
libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007ffff5400000)
libX11-xcb.so.1 => /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007ffff5000000)
libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007ffff4c00000)
libXcomposite.so.1 => /usr/lib/x86_64-linux-gnu/libXcomposite.so.1 (0x00007ffff4800000)
libXcursor.so.1 => /usr/lib/x86_64-linux-gnu/libXcursor.so.1 (0x00007ffff4400000)
libXdamage.so.1 => /usr/lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007ffff4000000)
libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007ffff3c00000)
libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007ffff3800000)
libXi.so.6 => /usr/lib/x86_64-linux-gnu/libXi.so.6 (0x00007ffff3400000)
libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007ffff3000000)
libXtst.so.6 => /usr/lib/x86_64-linux-gnu/libXtst.so.6 (0x00007ffff2c00000)
libgobject-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007ffff2800000)
libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007ffff2400000)
libnss3.so => /usr/lib/x86_64-linux-gnu/libnss3.so (0x00007ffff2000000)
libnssutil3.so => /usr/lib/x86_64-linux-gnu/libnssutil3.so (0x00007ffff1c00000)
libsmime3.so => /usr/lib/x86_64-linux-gnu/libsmime3.so (0x00007ffff1800000)
libnspr4.so => /usr/lib/x86_64-linux-gnu/libnspr4.so (0x00007ffff1400000)
libcups.so.2 => /usr/lib/x86_64-linux-gnu/libcups.so.2 (0x00007ffff1000000)
libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007ffff0c00000)
libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007ffff0800000)
libXss.so.1 => /usr/lib/x86_64-linux-gnu/libXss.so.1 (0x00007ffff0400000)
libXrandr.so.2 => /usr/lib/x86_64-linux-gnu/libXrandr.so.2 (0x00007ffff0000000)
libgio-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0 (0x00007fffefc00000)
libasound.so.2 => /usr/lib/x86_64-linux-gnu/libasound.so.2 (0x00007fffef800000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fffef400000)
libpangocairo-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0 (0x00007fffef000000)
libpango-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0 (0x00007fffeec00000)
libcairo.so.2 => /usr/lib/x86_64-linux-gnu/libcairo.so.2 (0x00007fffee800000)
libatk-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libatk-1.0.so.0 (0x00007fffee400000)
libatk-bridge-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0 (0x00007fffee000000)
libgtk-3.so.0 => /usr/lib/x86_64-linux-gnu/libgtk-3.so.0 (0x00007fffed600000)
libgdk-3.so.0 => /usr/lib/x86_64-linux-gnu/libgdk-3.so.0 (0x00007fffed200000)
libgdk_pixbuf-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0 (0x00007fffece00000)
libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fffeca00000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fffec600000)
/lib64/ld-linux-x86-64.so.2 (0x00007fffff200000)
libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007fffec200000)
libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fffebe00000)
libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007fffeba00000)
libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fffeb600000)
libplc4.so => /usr/lib/x86_64-linux-gnu/libplc4.so (0x00007fffeb200000)
libplds4.so => /usr/lib/x86_64-linux-gnu/libplds4.so (0x00007fffeae00000)
libgssapi_krb5.so.2 => /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007fffeaa00000)
libgnutls.so.30 => /usr/lib/x86_64-linux-gnu/libgnutls.so.30 (0x00007fffea600000)
libavahi-common.so.3 => /usr/lib/x86_64-linux-gnu/libavahi-common.so.3 (0x00007fffea200000)
libavahi-client.so.3 => /usr/lib/x86_64-linux-gnu/libavahi-client.so.3 (0x00007fffe9e00000)
libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fffe9a00000)
libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007ffff637a000)
libgmodule-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007fffe9600000)
libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007fffe9200000)
libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fffe8e00000)
libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007fffe8a00000)
libpangoft2-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0 (0x00007fffe8600000)
libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007fffe8200000)
libthai.so.0 => /usr/lib/x86_64-linux-gnu/libthai.so.0 (0x00007fffe7e00000)
libpixman-1.so.0 => /usr/lib/x86_64-linux-gnu/libpixman-1.so.0 (0x00007fffe7a00000)
libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007fffe7600000)
libxcb-shm.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007fffe7200000)
libxcb-render.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-render.so.0 (0x00007fffe6e00000)
libatspi.so.0 => /usr/lib/x86_64-linux-gnu/libatspi.so.0 (0x00007fffe6a00000)
libcairo-gobject.so.2 => /usr/lib/x86_64-linux-gnu/libcairo-gobject.so.2 (0x00007fffe6600000)
libepoxy.so.0 => /usr/lib/x86_64-linux-gnu/libepoxy.so.0 (0x00007fffe6200000)
libXinerama.so.1 => /usr/lib/x86_64-linux-gnu/libXinerama.so.1 (0x00007fffe5e00000)
libxkbcommon.so.0 => /usr/lib/x86_64-linux-gnu/libxkbcommon.so.0 (0x00007fffe5a00000)
libwayland-cursor.so.0 => /usr/lib/x86_64-linux-gnu/libwayland-cursor.so.0 (0x00007fffe5600000)
libwayland-egl.so.1 => /usr/lib/x86_64-linux-gnu/libwayland-egl.so.1 (0x00007fffe5200000)
libwayland-client.so.0 => /usr/lib/x86_64-linux-gnu/libwayland-client.so.0 (0x00007fffe4e00000)
libmirclient.so.9 => /usr/lib/x86_64-linux-gnu/libmirclient.so.9 (0x00007fffe4a00000)
libkrb5.so.3 => /usr/lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007fffe4600000)
libk5crypto.so.3 => /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007fffe4200000)
libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007fffe3e00000)
libkrb5support.so.0 => /usr/lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007fffe3a00000)
libp11-kit.so.0 => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007fffe3600000)
libidn.so.11 => /usr/lib/x86_64-linux-gnu/libidn.so.11 (0x00007fffe3200000)
libtasn1.so.6 => /usr/lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007fffe2e00000)
libnettle.so.6 => /usr/lib/x86_64-linux-gnu/libnettle.so.6 (0x00007fffe2a00000)
libhogweed.so.4 => /usr/lib/x86_64-linux-gnu/libhogweed.so.4 (0x00007fffe2600000)
libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007fffe2200000)
liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fffe1e00000)
libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007fffe1a00000)
libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007fffe1600000)
libdatrie.so.1 => /usr/lib/x86_64-linux-gnu/libdatrie.so.1 (0x00007fffe1200000)
libmircommon.so.7 => /usr/lib/x86_64-linux-gnu/libmircommon.so.7 (0x00007fffe0e00000)
libmirprotobuf.so.3 => /usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3 (0x00007fffe0a00000)
libcapnp-0.5.3.so => /usr/lib/x86_64-linux-gnu/libcapnp-0.5.3.so (0x00007fffe0600000)
libmircore.so.1 => /usr/lib/x86_64-linux-gnu/libmircore.so.1 (0x00007fffe0200000)
libboost_system.so.1.58.0 => /usr/lib/x86_64-linux-gnu/libboost_system.so.1.58.0 (0x00007fffdfe00000)
libprotobuf-lite.so.9 => /usr/lib/x86_64-linux-gnu/libprotobuf-lite.so.9 (0x00007fffdfa00000)
libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fffdf600000)
libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007fffdf200000)
libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007fffdee00000)
libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007fffdea00000)
libboost_filesystem.so.1.58.0 => /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.58.0 (0x00007fffde600000)
libkj-0.5.3.so => /usr/lib/x86_64-linux-gnu/libkj-0.5.3.so (0x00007fffde200000)
```

**Comment by aslushnikov** [comment]
@zhilidali this looks like an issue with your environment; try running puppeteer v1.5.0 and a newer node; maybe it will help. Other then that, I don't think there's anything else we can help here with.

**Comment by blankzust** [comment]
The same
