### ISSUE TITLE
Installing Chrome trough dockerfile - error:  WebDriverError: unknown error: DevToolsActivePort file doesn't exist

### ISSUE THREAD

**Issue by cemol** [puppeteer/puppeteer#2897]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:
* Platform / OS version: dockerfile (linux/ubuntu)
* URLs (if applicable):
* Node.js version: npm: 5.6.0, node: v8.11.3

**What steps will reproduce the problem?**
I first got the error: WebDriverError: unknown error: cannot find Chrome binary
But then I realised that I had to install chrome browser. So I tried to install chrome browser through the dockerfile like this:

1.
```
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 
RUN sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
RUN sudo apt update
RUN sudo apt install -y google-chrome-stable
```

2. The CMD 
`CMD ["selenium-side-runner", "-c", "chromeOptions.args=[headless]", "/tests/project.side"]`

3. But I got this error:
```
WebDriverError: unknown error: DevToolsActivePort file doesn't exist
      (Driver info: chromedriver=2.40.565383 (76257d1ab79276b2d53ee976b2c3e3b9f335cde7),platform=Linux 4.9.93-linuxkit-aufs x86_64)

      at Object.checkLegacyResponse (../usr/local/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/error.js:546:15)
      at parseHttpResponse (../usr/local/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/http.js:509:13)
      at doSend.then.response (../usr/local/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/http.js:441:30)
      From: Task: WebDriver.createSession()
      at Function.createSession (../usr/local/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
      at Function.createSession (../usr/local/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/chrome.js:761:15)
      at createDriver (../usr/local/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/index.js:170:33)
      at Builder.build (../usr/local/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/index.js:642:16)
      at buildDriver (../usr/local/lib/node_modules/selenium-side-runner/node_modules/jest-environment-selenium/dist/index.js:52:17)
      at WebdriverEnvironment.setup (../usr/local/lib/node_modules/selenium-side-runner/node_modules/jest-environment-selenium/dist/index.js:32:32)

```

**What is the expected result?**
I expect the project.side test file to run headless with chrome.

**What happens instead?**
I got the error: WebDriverError: unknown error: DevToolsActivePort file doesn't exist

**Comment by aslushnikov** [comment]
puppeteer has no relation to WebDriver; please file a bug on `https://crbug.com/new`.
