### ISSUE TITLE
The page.setContent() function does not render html source.

### ISSUE THREAD

**Issue by kbbmanse** [puppeteer/puppeteer#2913]
* Puppeteer version:1.5.0
* Platform / OS version:mac/sierra 10.12.6
* URLs (if applicable):
* Node.js version:8.9.0

**I'm going to use the puppeteer to replace phantomjs.**

The functions that were used in the past are as follows.
1. Download the html before rendering
2. Read the html file downloaded on phantomjs, and call page.setContent ()
3. Get the results of the final rendered content using page.content

**on the command line**
```
curl 'https://www.pikicast.com' > src.html
```
**load_test_phantomjs.js that used on phantomjs**
```
var fs = require('fs'), webPage = require('webpage');

var page = webPage.create();
var htmlUrl = 'https://www.pikicast.com';
var htmlContent = fs.read('./src.html');
console.log("---------Before rendering---------");
console.log(htmlContent);
page.setContent(htmlContent, htmlUrl);

var timer = setTimeout(function() {
    console.log("---------After rendering---------");
    console.log(page.content);
}, 3000);
```

**What is the expected result?**
When I used the 'load_test_phantomjs.js' code on **phantomjs** above, I got rendered results.
I want to get a rendered html using the below puppeteer code.

**load_test_puppeteer.js that used on puppeteer**
```
const fs = require('fs');
const puppeteer = require('puppeteer');

const htmlContent = fs.readFileSync('./src.html', {encoding:'utf-8'});
puppeteer.launch({headless:false, dumpio:true}).then(async browser=> {
    const page = await browser.newPage();
    console.log("---------Before rendering---------");
    console.log(htmlContent);
    await page.setContent(htmlContent);
    setTimeout(async () => {
        console.log("---------After rendering---------");
        console.log(await page.content());
    }, 3000);
});
```
**What happens instead?**
I got a non-rendered html.

**Comment by vsemozhetbyt** [comment]
I cannot reproduce with 1.5.0-post on Windows 7 x64 using this code:
```js
'use strict';

const puppeteer = require('puppeteer');

const htmlContent = `
  <!doctype html>
  <html>
    <head><meta charset='UTF-8'><title>Test</title></head>
    <body>Test</body>
  </html>
`;

puppeteer.launch({ headless: false }).then(async (browser) => {
  const page = await browser.newPage();
  await page.setContent(htmlContent);
  setTimeout(async () => {
    console.log(await page.content());
  }, 3000);
});

```

 Output and browser screenshot:

![s](https://user-images.githubusercontent.com/10393198/42949405-5da8b7de-8b7a-11e8-9dac-bce2d2828a1b.png)

**Comment by vsemozhetbyt** [comment]
BTW, when I open the result of the `curl 'https://www.pikicast.com' > src.html` in the browser, I get a blank page with some errors in the browser console.

**Comment by kbbmanse** [comment]
**This is the result of phantomjs.**
**The output before and after calling the page.setContent() function is different.**
**The results were too long to capture only a fraction.**
![phantomjs_result](https://user-images.githubusercontent.com/41423303/42977569-d108e11c-8c02-11e8-888b-e1c699be774e.png)


**This is the result of puppeteer.**
**The output before and after calling the page.setContent() function is the same.**
![puppeteer_result](https://user-images.githubusercontent.com/41423303/42977681-8e880bdc-8c03-11e8-96fa-0b2adea65101.png)

**Comment by vsemozhetbyt** [comment]
The difference may be from the `htmlUrl` you provide for the phantomjs and do not provide for the puppeteer: `src.html` contains some relative URLs, so phantomjs can resolve them against the `htmlUrl` while puppeteer cannot resolve them.

**Comment by vsemozhetbyt** [comment]
@aslushnikov Is there a way to provide a base URL for `page.setContent(html)` to resolve relative URLs?

**Comment by aslushnikov** [comment]
> @aslushnikov Is there a way to provide a base URL for page.setContent(html) to resolve relative URLs?

The only thing I can think of is injecting `<base>` tag into html.

**Comment by vsemozhetbyt** [comment]
@aslushnikov Unfortunately, this approach is unavailable due to CSP (`page.setBypassCSP(true)` does not help with blank page).
```js
'use strict';

const fs = require('fs');
const puppeteer = require('puppeteer');

const baseURL = 'https://www.pikicast.com/';
const htmlContent = fs.readFileSync('./src.html', {encoding:'utf-8'})
                    .replace(/<head>/i, `<head><base href='${baseURL}'>`);

puppeteer.launch({headless:false, dumpio:true}).then(async browser=> {
    const page = await browser.newPage();
    await page.setBypassCSP(true);
    console.log("---------Before rendering---------");
    console.log(htmlContent);
    await page.setContent(htmlContent);
    setTimeout(async () => {
        console.log("---------After rendering---------");
        console.log(await page.content());
    }, 3000);
});
```

<details>
<summary>Errors in the browser console:</summary>

```
VM19:3 A parser-blocking, cross site (i.e. different eTLD+1) script, https://www.pikicast.com/js/lib/require.js, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.html @ VM19:3
VM19:3 A parser-blocking, cross site (i.e. different eTLD+1) script, https://www.pikicast.com/js/lib/require.js, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.html @ VM19:3
about:blank:1 Uncaught DOMException: Failed to set the 'domain' property on 'Document': 'pikicast.com' is not a suffix of ''.
    at about:blank:1:17
(anonymous) @ about:blank:1
app.v3.js?cb=v3.1524100716370:1 Uncaught DOMException: Failed to read the 'cookie' property from 'Document': Access is denied for this document.
    at t.i.get_storage (https://www.pikicast.com/js/app.v3.js?cb=v3.1524100716370:1:12282)
    at t.i.reinit (https://www.pikicast.com/js/app.v3.js?cb=v3.1524100716370:1:9638)
    at t.i.reinit (https://www.pikicast.com/js/app.v3.js?cb=v3.1524100716370:1:9609)
    at https://www.pikicast.com/js/app.v3.js?cb=v3.1524100716370:1:6865
    at Object.execCb (https://www.pikicast.com/js/lib/require.js:1:11575)
    at E.check (https://www.pikicast.com/js/lib/require.js:1:6025)
    at E.<anonymous> (https://www.pikicast.com/js/lib/require.js:1:8198)
    at https://www.pikicast.com/js/lib/require.js:1:642
    at https://www.pikicast.com/js/lib/require.js:1:8630
    at v (https://www.pikicast.com/js/lib/require.js:1:202)
i.get_storage @ app.v3.js?cb=v3.1524100716370:1
i.reinit @ app.v3.js?cb=v3.1524100716370:1
i.reinit @ app.v3.js?cb=v3.1524100716370:1
(anonymous) @ app.v3.js?cb=v3.1524100716370:1
execCb @ require.js:1
check @ require.js:1
(anonymous) @ require.js:1
(anonymous) @ require.js:1
(anonymous) @ require.js:1
v @ require.js:1
emit @ require.js:1
check @ require.js:1
(anonymous) @ require.js:1
(anonymous) @ require.js:1
(anonymous) @ require.js:1
v @ require.js:1
emit @ require.js:1
check @ require.js:1
enable @ require.js:1
init @ require.js:1
x @ require.js:1
completeLoad @ require.js:1
onScriptLoad @ require.js:1
```

</details><br>

**Comment by aslushnikov** [comment]
Don't know how we can help here - closing.

**Comment by semoal** [comment]
@vsemozhetbyt did you fixed it? I have the same problem.
The scripts are getting intercepted, because the html is written via `document.write`

**Comment by vsemozhetbyt** [comment]
@semoal No, I did not, sorry.

**Comment by semoal** [comment]
Fixed it with args: ```[      '--disable-web-security']```, @vsemozhetbyt 

Give it a try!!
