### ISSUE TITLE
Error: Protocol error (Runtime.addBinding): 'Runtime.addBinding' wasn't found

### ISSUE THREAD

**Issue by tech-a-go-go** [puppeteer/puppeteer#2972]
### Steps to reproduce

**Tell us about your environment:**

Running on Docker node:10.7.0

* Puppeteer version: 1.6.1
* Platform / OS version: node10.7.0-alpine on Docker on CentOS7
* URLs (if applicable):
* Node.js version: 10.7.0
* Chrome version: HeadlessChrome/64.0.3282.168  (by browser.version())

Here is my Dockerfile.
```
FROM node:10.7.0-alpine

# Installs latest Chromium (64) package.
RUN apk update && apk upgrade && \
    echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories && \
    echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories && \
    apk add --no-cache \
      git \
      chromium@edge \
      nss@edge \
      ttf-freefont

RUN mkdir /server
VOLUME /server
RUN mkdir /noto

ADD https://noto-website.storage.googleapis.com/pkgs/NotoSansCJKjp-hinted.zip /noto

WORKDIR /noto

RUN unzip NotoSansCJKjp-hinted.zip && \
    mkdir -p /usr/share/fonts/noto && \
    cp *.otf /usr/share/fonts/noto && \
    chmod 655 -R /usr/share/fonts/noto/ && \
    fc-cache -fv

RUN rm -rf /noto

# Tell Puppeteer to skip installing Chrome. We'll be using the installed package.
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true

# Puppeteer v0.13.0 works with Chromium 64.
RUN yarn add puppeteer@0.13.0

USER node

ENV TERM xterm
ENV HOME /home/node
ENV LANG C.UTF-8

WORKDIR /server
CMD ["/bin/ash"]
```
This is my package.json.
```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "test.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "puppeteer": "^1.6.1"
  }
}
```

**What steps will reproduce the problem?**

just calling exposeFunction.
```
const browser = await puppeteer.launch({
  headless: true,
  executablePath: '/usr/bin/chromium-browser',
  args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage']
});

const page = await browser.newPage();

await page.exposeFunction('onChangeEvent', (e) => {  // This line throws the error.
  console.log('onChangeEvent', JSON.stringify(e,null,2));
});
await page.evaluate(() => {
  window.api.signalR.changes.subscribe((e) => {
    window.onChangeEvent(e);
  });
});
```
**What is the expected result?**

exposeFunction without the protocol error "'Runtime.addBinding' wasn't found".

**What happens instead?**
```
(node:2745) UnhandledPromiseRejectionWarning: Error: Protocol error (Runtime.addBinding): 'Runtime.addBinding' wasn't found
    at Promise (/server/node_modules/puppeteer/lib/Connection.js:202:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/server/node_modules/puppeteer/lib/Connection.js:201:12)
    at Page.exposeFunction (/server/node_modules/puppeteer/lib/Page.js:391:24)
    at /var/tmp/test.js:29:14
(node:2745) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2745) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by aslushnikov** [comment]
You're using way too old chromium version; please use the bundled version of Chromium or older version of puppeteer.

Also see our FAQ entry: [Q: Why doesn’t Puppeteer v.XXX work with Chromium v.YYY?](https://github.com/GoogleChrome/puppeteer/#q-why-doesnt-puppeteer-vxxx-work-with-chromium-vyyy)

**Comment by tech-a-go-go** [comment]
Hi, @aslushnikov 

Thank you for your reply !

Some blogs say installing Chromium using apt in Dockerfile is fine, some say installing one using npm (package.json) is right way so I'm confused which one I should follow...

I guess installing one using apt is wrong because both versions of Chromium and Puppeteer don't match according to the link you provided. I must have installed the version of Chromium specified in package.json.
I hope this is correct.

Cheers
