### ISSUE TITLE
Target closed when trying to read large json file in evaluate

### ISSUE THREAD

**Issue by ronalb** [puppeteer/puppeteer#2998]
### Steps to reproduce
**Tell us about your environment:**

Puppeteer version:1.6.1
Platform: windows 10
Node.js version: v10.6.0

**file size = ~80mb see fileName3 in the code**

### code to reproduce:
```
const puppeteer = require('puppeteer');
const sizeof = require('object-sizeof');
const fs = require('fs');

let fileName1 = "D:/shared/render_small/request.txt";
let fileName2 = "D:/shared/render_addresses2/request.txt";
let fileName3 = "D:/shared/render_add3/data.json"; //80mb json file
let jsonObj1 = JSON.parse(fs.readFileSync(fileName1, "utf8"));
let jsonObj2 = JSON.parse(fs.readFileSync(fileName2, "utf8"));
let jsonObj3 = JSON.parse(fs.readFileSync(fileName3, "utf8"));

console.log(sizeof(jsonObj1));
console.log(sizeof(jsonObj2));
console.log(sizeof(jsonObj3));

(async () => {

    const browser = await puppeteer.launch();    
    const page = await browser.newPage();
    page.on('console', msg => console.log(msg.text()));

    await page.exposeFunction('readfile', async filePath => {
        return new Promise((resolve, reject) => {
            fs.readFile(filePath, 'utf8', (err, text) => {
                if (err)
                    reject(err);
                else
                    resolve(text);
            });
        });
    });

    await page.exposeFunction('sizeof', async obj => {
        return new Promise((resolve, reject) => {
            sizeof(obj, (err, text) => {
                if (err)
                    reject(err);
                else
                    resolve(text);
            });
        });
    });

    console.log("before");
    let evaluateResult = await page.evaluate(async (fileName3) => {

        console.log("before read file");
        const content = await window.readfile(fileName3);
        console.log("after read file"); // never reach this line
        //prints : Protocol error (Runtime.callFunctionOn): Target closed.

        contentParsed = JSON.parse(content);
        console.log("after JSON parse");
        console.log(contentParsed.tabId);
        document.title = "new title";
    }, fileName3);
    const title = await page.title()
    console.log(title);
    await browser.close()
})().catch(err => {
    console.log(err.message);
});
```

**What is the expected result?**
file loaded successfully

**What happens instead?**

> Protocol error (Runtime.callFunctionOn): Target closed.

Error: Protocol error (Runtime.callFunctionOn): Target closed.
    at Promise (F:\Test\testLargeData\node_modules\puppeteer\lib\Connection.js:202:56)
    at new Promise (<anonymous>)
    at CDPSession.send (F:\Test\testLargeData\node_modules\puppeteer\lib\Connection.js:201:12)
    at ExecutionContext.evaluateHandle (F:\Test\testLargeData\node_modules\puppeteer\lib\ExecutionContext.js:88:75)
    at ExecutionContext.evaluate (F:\Test\testLargeData\node_modules\puppeteer\lib\ExecutionContext.js:49:31)
    at Frame.evaluate (F:\Test\testLargeData\node_modules\puppeteer\lib\FrameManager.js:325:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by ronalb** [comment]
### package.json file:
```
{
  "name": "testlargedata",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "object-sizeof": "^1.2.0",
    "puppeteer": "^1.6.1"
  }
}

```

**Comment by sheikalthaf** [comment]
@OrKoN we are still facing this issue. Any update on this?

**Comment by OrKoN** [comment]
@sheikalthaf could you please file a new ticket with the repro script and using the latest versions of Chromium/Puppeteer?

This issue went stale and we don't longer support the Node version and the Puppeteer version mentioned in the ticket.
