### ISSUE TITLE
Page crashes, timeouts and strange behaviors using puppeteer

### ISSUE THREAD

**Issue by jprivillaso** [puppeteer/puppeteer#3126]
Hi,

I am trying to deploy an application at AWS EC2 using a cluster.
I am using puppeteer to crawl a URL, get its contents and convert them to pdf. The application works locally, in my Mcbook pro, however it does not work on the AWS end.

I have been trying to do that for days. I have seen that there are multiple threads about it but unfortunately, none of the options have worked for me. 

It has worked for pages like: 
- https://example.com/

An other websites that are very lightweight.

Currently I am testing with this URL `https://stackoverflow.com/users/2599811/jprivillaso`

The issues that I have faced are:
- Page Crash
- Timeout connecting to chrome when launching puppeteer
- Timeout when calling the PDF method
- Cannot find context with id X

This is my function

```js
const processInBackground = async () => {

  try {

    const browser = await puppeteer.launch({
      args: [
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-dev-shm-usage',
        '--disable-web-security',
        "--proxy-server='direct://'", 
        '--proxy-bypass-list=*'
      ],
    });

    const page = await browser.newPage();
    page.on('error', e => {
      console.error(e);
    });

    const tracker = new InflightRequests(page);
    await page.goto(process.env.PAGE_TO_CRAWL, {
      waitUntil: 'load'
    }).catch(e => {

      const inflight = tracker.inflightRequests();
      const fail = tracker.failedRequests();
      console.log('>>> Inflight Errors', e);

    });
    tracker.dispose();

    await page.content();
    const bodyHandle = await page.$('body');
    await page.evaluate(body => body.innerHTML, bodyHandle);
    await bodyHandle.dispose();

    await page.emulateMedia('screen');
    await page.pdf({
      path: path.join(__dirname, 'example1.pdf'),
      format: 'A4',
      printBackground: true
    });
    await browser.close();
    
  } catch (error) {
    console.error('Error processing PDF in background mode', error);
  }

};
```

*Note*: I removed some console.log statements from the snippet, for a better understanding of what am I doing with puppeteer

**Tell us about your environment:**

- Docker 
- AWS ECS Cluster with EC2 Instances
- Nodejs 10
- Puppeteer version: 1.7.0-next.1534528770278
- AWS AMI: amzn-ami-2017.09.i-amazon-ecs-optimized
- OS: Linux

**What is the expected result?**
The expected result is to be able to go to a page, get its contents and the convert them to PDF

**What happens instead?**
Page crashes, timeouts, and strange errors.

This is my Docker configuration.

```docker
FROM node:8-slim

# # Manually install missing shared libs for Chromium.
RUN apt-get update && \
  apt-get install -yq gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 \
  libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 \
  libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 \
  libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libgconf2-4 libxrender1 libxss1 libxtst6 \
  ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget

COPY . /app/
WORKDIR app
RUN mkdir /app/tmp

# Install deps for server.
RUN npm install -g

# Install puppeteer so it can be required by user code that gets run in
# server.js. Cache bust so we always get the latest version of puppeteer when
# building the image.
ARG CACHEBUST=1
RUN npm install puppeteer@next

# Add pptr user.
RUN groupadd -r pptruser && useradd -r -g pptruser -G audio,video pptruser \
    && mkdir -p /home/pptruser/Downloads \
    && chown -R pptruser:pptruser /home/pptruser \
    && chown -R pptruser:pptruser /app

# Run user as non privileged.
USER pptruser

EXPOSE 3001

CMD ["npm", "start"]
```

This is some part of my logs: 

```

15:05:52
> invoice-generator-service@1.0.0 start /app
15:05:52
> node index.js
15:06:06
Started invoice generator worker
15:06:06
Worker requesting jobs every 60000ms. The next job will be triggered in 60000ms.
15:06:06
Created server listening at port 80 for healthcheck
15:06:06
Processing PDF in background mode ...
15:06:26
Version 1.7.0@next Puppeteer before launch ...
15:06:26
HeadlessChrome/70.0.3524.0
15:06:50
After new page ...
15:06:50
https://stackoverflow.com/users/2599811/jprivillaso
15:07:23
>>> Inflight Errors { TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
15:07:23
at Promise.then (/app/node_modules/puppeteer/lib/NavigatorWatcher.js:74:21)
15:07:23
at <anonymous> name: 'TimeoutError' }
15:07:23
After go to
15:07:38
Error processing PDF in background mode Error: Evaluation failed: TypeError: Cannot read property 'innerHTML' of null
15:07:38
at body (__puppeteer_evaluation_script__:1:15)
15:07:38
at ExecutionContext.evaluateHandle (/app/node_modules/puppeteer/lib/ExecutionContext.js:106:13)
15:07:38
at <anonymous>
15:07:38
at process._tickDomainCallback (internal/process/next_tick.js:228:7)
15:07:38
waiting till next batch process
15:08:40
Processing PDF in background mode ...
15:09:19
Error processing PDF in background mode { TimeoutError: Timed out after 30000 ms while trying to connect to Chrome! The only Chrome revision guaranteed to work is r583214
15:09:19
at Timeout.onTimeout (/app/node_modules/puppeteer/lib/Launcher.js:310:14)
15:09:19
at ontimeout (timers.js:498:11)
15:09:19
at tryOnTimeout (timers.js:323:5)
15:09:19
at Timer.listOnTimeout (timers.js:290:5) name: 'TimeoutError' }
15:09:19
waiting till next batch process
15:10:21
Processing PDF in background mode ...
15:10:55
Error processing PDF in background mode { TimeoutError: Timed out after 30000 ms while trying to connect to Chrome! The only Chrome revision guaranteed to work is r583214
15:10:55
at Timeout.onTimeout (/app/node_modules/puppeteer/lib/Launcher.js:310:14)
15:10:55
at ontimeout (timers.js:498:11)
15:10:55
at tryOnTimeout (timers.js:323:5)
15:10:55
at Timer.listOnTimeout (timers.js:290:5) name: 'TimeoutError' }
15:10:55
waiting till next batch process
```

I just want to be sure that the puppeteer part is wrong or see if anyone can suggest me what can I do.
I have create an issue at stackoverflow too, and I had no answers.
Thanks and hope anyone can help

**Comment by jprivillaso** [comment]
The issue wasn't related to puppeteer, sorry for the inconvenience

**Comment by a-eid** [comment]
@jprivillaso  what was it related to ?

**Comment by Laribobibo** [comment]
Im also wondering, i get the same errors, it seems like my script is working when im singed in but now when i exit out and the computer locks
