### ISSUE TITLE
Navigation Timeout Exceeded

### ISSUE THREAD

**Issue by TheScree** [puppeteer/puppeteer#3242]
Puppeteer version: 1.8.0
Platform / OS: CentOS 7
Node.js version: 8.11.3
URLs: included in description

I've included the core function that I keep getting "Navigation Timeout Exceeded" errors on. I've verified that the server can get a 200 response on the URL via a quick Axios call (I had begun to believe I was being blacklisted). The URL, for reference, is "https://community.crowfall.com/topic/22528-571-live-feedback-and-bug-reports-for-91318/?do=findComment&comment=404954". 

This code was recently updated with page.on catchers, as I was starting to see a ton of restarts in pm2 as the process failed. Previously it had been working without issue. You can see an example of the final working result of this app here; https://twitter.com/ProjectMalekai/status/1039972945483976705

The function being used is in its entirety is below:
```
async function devpostToImage(url) {
  if (url) {
    const postID = url.slice(url.search('comment=') + 8);
    try {
      const browser = await puppeteer.launch({
        args: ['--no-sandbox', '--disable-setuid-sandbox']
      });
      const page = await browser.newPage();
      await page.setRequestInterception(true);
      await page.setViewport({
        width: 900,
        height: 15000
      });
      await page.goto(url, {
          waitUntil: 'domcontentloaded'
        }).then(result => {
          console.log(result);
        })
        .catch(err => console.log(`Issue with GoTo Execution:`, err));
      await page.waitFor(`#elComment_${postID}`, {
          timeout: 30000
        })
        .catch(err => console.log(`ID did not show up while waiting:`, err));
      const devpost = await page.$(`#elComment_${postID}`);
      if (devpost) {
        const screenshot = await devpost.screenshot({
            path: `/var/www/malekai.network/devposts/${postID}.png`,
          }).then(result => {
            console.log(`Captured Screenshot of: ${url}`)
          })
          .catch(err => console.log(`Capturing Screenshot Failed:`, err));
      } else {
        console.log(`Post ID was not found/loaded correctly.`);
      }
      page.on('requestfailed', err => {
        console.log('URL Request Failed:', err.failure().errorText);
      });
      page.on('error', err => {
        console.error('Retrying after Chromium error:', err.failure().errorText)
      });
      page.on('pageerror', err => {
        console.error('Retrying after Chromium page error:', err.failure().errorText)
      });
      page.on('response', response => {
        console.log(`Response: response.status, response.url, response.headers`)
      })
      await browser.close()
    } catch (err) {
      console.error(err);
    }
  }
};
```
**What is the expected result?**
I get something other than a timeout error.

**What happens instead?**
```
Issue with GoTo Execution: { TimeoutError: Navigation Timeout Exceeded: 120000ms exceeded
at Promise.then (/home/malekai/malekaiDevtracker/node_modules/puppeteer/lib/NavigatorWatcher.js:94:21)
at <anonymous> name: 'TimeoutError' }
```
and

```
ID did not show up while waiting: { TimeoutError: waiting for selector "#elComment_404968" failed: timeout 30000ms exceeded
at new WaitTask (/home/malekai/malekaiDevtracker/node_modules/puppeteer/lib/FrameManager.js:862:28)
at Frame._waitForSelectorOrXPath (/home/malekai/malekaiDevtracker/node_modules/puppeteer/lib/FrameManager.js:753:12)
at Frame.waitForSelector (/home/malekai/malekaiDevtracker/node_modules/puppeteer/lib/FrameManager.js:711:17)
at Frame.waitFor (/home/malekai/malekaiDevtracker/node_modules/puppeteer/lib/FrameManager.js:696:19)
at Page.waitFor (/home/malekai/malekaiDevtracker/node_modules/puppeteer/lib/Page.js:1034:29)
at devpostToImage (/home/malekai/malekaiDevtracker/malekaiDevtracker.js:67:18)
at <anonymous> name: 'TimeoutError' }
```

I am aware that the page.waitFor() code is redundant but wanted to make sure I was giving ample time for the dom to finish loading (just in case the previous entry wasn't working correctly).

**Comment by TheScree** [comment]
Turning await page.setRequestInterception(false) to false, solved this issue.

<shrug>

**Comment by aslushnikov** [comment]
@TheScree make sure to react to every intercepted request, if you enable request interception:

```js
page.on('request', request => request.continue());
```

**Comment by TheScree** [comment]
@aslushnikov Just a quick followup; Do you have any ideas why I'm getting 403 responses from a URL when using Puppeteer, but getting 200 responses using the same URL but with Axios?

**Comment by aslushnikov** [comment]
@TheScree the easiest explanation is server-side user agent detection
