### ISSUE TITLE
Browser closing before browser.close() call

### ISSUE THREAD

**Issue by jimut** [puppeteer/puppeteer#3251]
### Steps to reproduce

**My environment:**

* Puppeteer version: 0.11.0
* Platform / OS version: macOS v10.13.6
* Node.js version: 10.10.0

**Steps thst will reproduce the problem**

```js
const puppeteer = require('puppeteer');

(async function launchNexitTest() {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();

  process.on('SIGINT', async () => {
    await page.close();
    await browser.close();
  });
})();
```

**What is the expected result?**

I want to close the browser once I press CTRL+C. 

**What happens instead?**

Instead, I am getting the following error.

```
^C(node:60744) UnhandledPromiseRejectionWarning: Error: Protocol error (Target.closeTarget): Target closed.
    at Connection._onClose (/Users/jimutdhali/Projects/random/pupp-test/node_modules/puppeteer/lib/Connection.js:113:23)
    at WebSocket.emit (events.js:182:13)
    at WebSocket.emitClose (/Users/jimutdhali/Projects/random/pupp-test/node_modules/ws/lib/WebSocket.js:211:10)
    at _receiver.cleanup (/Users/jimutdhali/Projects/random/pupp-test/node_modules/ws/lib/WebSocket.js:199:39)
    at Receiver.cleanup (/Users/jimutdhali/Projects/random/pupp-test/node_modules/ws/lib/Receiver.js:520:15)
    at WebSocket.finalize (/Users/jimutdhali/Projects/random/pupp-test/node_modules/ws/lib/WebSocket.js:199:20)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:60744) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:60744) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by aslushnikov** [comment]
@jimut Puppeteer has a default SIGINT handler to close the browser. If you want to do this on your own, you should pass `handleSIGINT: false` to the `puppeteer.launch`: 

```js
const browser = await puppeteer.launch({
  handleSIGINT: false
});
```

Hope this helps.

**Comment by jimut** [comment]
That solved my issue. Thank you so much for the prompt response.
