### ISSUE TITLE
page.authenticate https proxy not work

### ISSUE THREAD

**Issue by liyongios** [puppeteer/puppeteer#3253]
Puppeteer version: 1.8
Platform / OS version:MacOS 10.13.6
Node.js version:v10.9.0

```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
        headless:false,
        ignoreHTTPSErrors:true,
        devtools:true,
        timeout:3000,
        args: ['--no-sandbox','--proxy-server=xxx:xxx']
  });
  const user='xxx';
  const password='xxx';
  const page = await browser.newPage();
  // await page.setExtraHTTPHeaders({
  //   'Proxy-Authorization': 'Basic ' + Buffer.from(`${user}:${password}`).toString('base64'),
  // });
  await page.authenticate({username:user, password:password});
  await page.goto('https://www.apple.com/');
  let title = await page.title();
  console.log("title:" + title);
  await browser.close();
})();
```

got error:
```
(node:5858) UnhandledPromiseRejectionWarning: Error: net::ERR_TUNNEL_CONNECTION_FAILED at https://www.apple.com/
    at navigate (/xxx/node_modules/_puppeteer@1.8.0@puppeteer/lib/Page.js:622:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:5858) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

**Comment by liyongios** [comment]
http proxy is work

**Comment by rozumem** [comment]
Facing same issue.

**Comment by antifa-ev** [comment]
+1

**Comment by RuslanTT** [comment]
i have same issue, u can use 'proxy-chain' https://github.com/apifytech/proxy-chain when you need to use proxy and auth at the same time.

**Comment by rozumem** [comment]
@RuslanTT works like a charm. thanks.

**Comment by phrfpeixoto** [comment]
I'm getting the same error.
Using puppeteer v1.19.0
Chromium Version 77.0.3844.0 (Developer Build) (64-bit)
Node v11.14.0

Also, when using the traditional Proxy-Authorization header, I get this:
```
(node:92796) UnhandledPromiseRejectionWarning: Error: net::ERR_INVALID_ARGUMENT at https://www.example.com
    at navigate (/Users/ppeixoto/shub/pupperteer-latest/node_modules/puppeteer/lib/FrameManager.js:121:37)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
  -- ASYNC --
    at Frame.<anonymous> (/Users/ppeixoto/shub/pupperteer-latest/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.goto (/Users/ppeixoto/shub/pupperteer-latest/node_modules/puppeteer/lib/Page.js:674:49)
    at Page.<anonymous> (/Users/ppeixoto/shub/pupperteer-latest/node_modules/puppeteer/lib/helper.js:112:23)
    at /Users/ppeixoto/shub/pupperteer-latest/index.js:43:27
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:92796) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:92796) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
@liyongios Did you manage to work around this?

**Comment by gajus** [comment]
You can use https://github.com/gajus/puppeteer-proxy to proxy authenticated HTTP/ HTTPS requests. Unlike other implementations, puppeteer-proxy actually makes the request from Node.js and hands over the response to the browser. It uses https://github.com/sindresorhus/got behind the scenes to make HTTP requests.

**Comment by Cuadrix** [comment]
I made a module that does this. It's called [**puppeteer-page-proxy**](https://github.com/Cuadrix/puppeteer-page-proxy).
It supports setting a proxy for an entire page, or if you like, it can set a different proxy for each request.

First install it:
```
npm i puppeteer-page-proxy
```
Then require it:
```js
const useProxy = require('puppeteer-page-proxy');
```
**Using it is easy;**
Set proxy for an entire page:
```js
await useProxy(page, 'http://127.0.0.1:8000');
```

If you want a different proxy for each request,then you can simply do this:
```js
await page.setRequestInterception(true);
page.on('request', req => {
    useProxy(req, 'socks5://127.0.0.1:9000');
});
```
Then if you want to be sure that your page's IP has changed, you can look it up;
```js
const data = await useProxy.lookup(page);
console.log(data.ip);
```
It supports **http**, **https**, **socks4** and **socks5** proxies, and it also supports authentication if that is needed:
```js
const proxy = 'http://login:pass@127.0.0.1:8000'
```

Repository:
https://github.com/Cuadrix/puppeteer-page-proxy

**Comment by leoplct** [comment]
@Cuadrix It's great. How can I pass the username/password for authentication for each page?
