### ISSUE TITLE
Puppeteer won't work in Manjaro Linux!

### ISSUE THREAD

**Issue by mihirkumar** [puppeteer/puppeteer#3267]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.8.0
* Platform / OS version: Manjaro 17.1.12 (Deepin)
* Node.js version: 8.11.4

_Please include code that reproduces the issue._

```
'use strict';
const puppeteer = require('puppeteer');
(async () => {
    var browser = await puppeteer.launch();
    await browser.close();
})();
```

**What is the expected result?** I would expect no output but successful execution.

**What happens instead?** Gives me an error saying that Chrome can't be opened. Here's the error:
```
(node:1788) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
[0918/005133.383085:FATAL:zygote_host_impl_linux.cc(116)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
#0 0x5585440c68ec base::debug::StackTrace::StackTrace()
#1 0x558544042200 logging::LogMessage::~LogMessage()
#2 0x5585455354f0 service_manager::ZygoteHostImpl::Init()
#3 0x558543d0954e content::ContentMainRunnerImpl::Initialize()
#4 0x558543d3ceb8 service_manager::Main()
#5 0x558543d07d91 content::ContentMain()
#6 0x55854820f97d headless::(anonymous namespace)::RunContentMain()
#7 0x55854820fa08 headless::HeadlessBrowserMain()
#8 0x558543d3a4ab headless::HeadlessShellMain()
#9 0x5585420ff1ac ChromeMain
#10 0x7fac2f3e4223 __libc_start_main
#11 0x5585420ff02a _start

Received signal 6
#0 0x5585440c68ec base::debug::StackTrace::StackTrace()
#1 0x5585440c6451 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#2 0x7fac32ff93c0 <unknown>
#3 0x7fac2f3f7d7f __GI_raise
#4 0x7fac2f3e2672 __GI_abort
#5 0x5585440c5275 base::debug::BreakDebugger()
#6 0x558544042669 logging::LogMessage::~LogMessage()
#7 0x5585455354f0 service_manager::ZygoteHostImpl::Init()
#8 0x558543d0954e content::ContentMainRunnerImpl::Initialize()
#9 0x558543d3ceb8 service_manager::Main()
#10 0x558543d07d91 content::ContentMain()
#11 0x55854820f97d headless::(anonymous namespace)::RunContentMain()
#12 0x55854820fa08 headless::HeadlessBrowserMain()
#13 0x558543d3a4ab headless::HeadlessShellMain()
#14 0x5585420ff1ac ChromeMain
#15 0x7fac2f3e4223 __libc_start_main
#16 0x5585420ff02a _start
  r8: 0000000000000000  r9: 00007ffe02a02cd0 r10: 0000000000000008 r11: 0000000000000246
 r12: 00007ffe02a034f8 r13: 0000000000000161 r14: 00007ffe02a03500 r15: 00007ffe02a03508
  di: 0000000000000002  si: 00007ffe02a02cd0  bp: 00007ffe02a02f20  bx: 0000000000000006
  dx: 0000000000000000  ax: 0000000000000000  cx: 00007fac2f3f7d7f  sp: 00007ffe02a02cd0
  ip: 00007fac2f3f7d7f efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/home/ares/fae-util-2/node_modules/puppeteer/lib/Launcher.js:333:14)
    at Interface.helper.addEventListener (/home/ares/fae-util-2/node_modules/puppeteer/lib/Launcher.js:322:50)
    at emitNone (events.js:111:20)
    at Interface.emit (events.js:208:7)
    at Interface.close (readline.js:368:8)
    at Socket.onend (readline.js:147:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
(node:1788) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1788) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mihirkumar** [comment]
Correcting the code

**Comment by aslushnikov** [comment]
@mihirkumar this should help: [Chrome Headless fails due to sandbox issues - Puppeteer Troubleshooting](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-fails-due-to-sandbox-issues)

**Comment by mihirkumar** [comment]
The only thing that ended up working was disabling the sandbox :(
Thanks for the reply though.
