### ISSUE TITLE
Unhandled rejection caused by puppeteer: We either navigate top level or have old version of the navigated frame.

### ISSUE THREAD

**Issue by SergeyFromHell** [puppeteer/puppeteer#3309]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.8.0-next.1537588058879
* Platform / OS version: x86-64 / CentOS Linux release 7.5.1804 (Core)
* URLs (if applicable):
* Node.js version: 10.10.0

**What steps will reproduce the problem?**
I have web scrapping project with pool of  puppeteer instances (big code base, cannot paste here). The scenario is like that:
1. Pool created with multiple (50-60) instances of puppeteer browsers.
2. In each browser one permanent page is created and reused.
3. Incoming queries are distributed to that instances.
4. Query processing at one instance does not reload page (until some limits), scrapped sites use ajax to return result (so one page after being loaded can process hundreds of requests before closed or reloaded)
5. Puppeteer is used to control pages (send queries, wait for result, extract, sometimes detect and process captchas etc.)

**What is the expected result?**
No unhandled rejections should occur from puppeteer.

**What happens instead?**
There are occasional unhandled rejections of the kind:
Unhandled Rejection at: Promise Promise {                                                                                                                                      
  <rejected> Error: We either navigate top level or have old version of the navigated frame                                                                                                                        
      at assert (/***/node_modules/puppeteer/lib/helper.js:259:11)                                                                                                                 
      at FrameManager._onFrameNavigated (/***/node_modules/puppeteer/lib/FrameManager.js:214:5)                                                                                    
      at CDPSession.FrameManager._client.on.event (/***/node_modules/puppeteer/lib/FrameManager.js:46:58)                                                                          
      at CDPSession.emit (events.js:182:13)                                                                                                                                                                        
      at CDPSession._onMessage (/***/node_modules/puppeteer/lib/Connection.js:216:12)                                                                                              
      at Connection._onMessage (/***/node_modules/puppeteer/lib/Connection.js:99:19)                                                                                               
      at WebSocketTransport._ws.addEventListener.event (/***/node_modules/puppeteer/lib/WebSocketTransport.js:41:24)                                                               
      at WebSocket.onMessage (/***/node_modules/ws/lib/event-target.js:120:16)                                                                                                     
      at WebSocket.emit (events.js:182:13)                                                                                                                                                                         
      at Receiver.receiverOnMessage (/***/node_modules/ws/lib/websocket.js:720:20)                                                                                                 
      at Receiver.emit (events.js:182:13)                                                                                                                                                                          
      at Receiver.dataMessage (/***/node_modules/ws/lib/receiver.js:414:14)                                                                                                        
      at Receiver.getData (/***/node_modules/ws/lib/receiver.js:346:17)                                                                                                            
      at Receiver.startLoop (/***/node_modules/ws/lib/receiver.js:133:22)                                                                                                          
      at Receiver._write (/***/node_modules/ws/lib/receiver.js:69:10)                                                                                                              
      at doWrite (_stream_writable.js:410:12)                                                                                                                                                                      
      at writeOrBuffer (_stream_writable.js:394:5)                                                                                                                                                                 
      at Receiver.Writable.write (_stream_writable.js:294:11)                                                                                                                                                      
      at Socket.socketOnData (/***/node_modules/ws/lib/websocket.js:795:35)                                                                                                        
      at Socket.emit (events.js:182:13)                                                                                                                                                                            
      at addChunk (_stream_readable.js:283:12)                                                                                                                                                                     
      at readableAddChunk (_stream_readable.js:264:11)                                                                                                                                                             
      at Socket.Readable.push (_stream_readable.js:219:10)                                                                                                                                                         
      at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17) }

I think, the source of unhandled rejections is the function in lib/Connection.js:
Line 80: async _onMessage(message) {...}
It is used as event callback:
Line 36: this._transport.onmessage = this._onMessage.bind(this);
But it has no enclosing try/catch inside, so exceptions propagate to the event caller, but there is no await/.then, so no one process this error.=> unhandled rejection.

I dont mind some strange errors from time to time, but they all should be handled through standard mechanics (like 'error' events or exceptions/rejections from direct puppeteer methods calls).

Unhandled rejections/exceptions must never occur from library code!

**Comment by aslushnikov** [comment]
@SergeyFromHell This is clearly a bug, most likely in DevTools protocol.

Any chance you have at a URL of the page that causes this? If not, we can update the error message to dump the URL. This way we'll have at least some pointers to debug it.

**Comment by SergeyFromHell** [comment]
Well, initially it is yandex.ru/search, but there are human behaviour emulation that includes random search results links clicks etc, so it can be any link from search result.
Actually, my concern is not the error itself, but the fact that it is from unhandled promise rejection somewhere from puppeteer code, so I  have to use process.on('unhandledRejection',...) to make process not die.

**Comment by nammaianh** [comment]
I have been getting this error for a few days.
Do you know what cause the error?

**Comment by AshDee** [comment]
I get the same error for the following URL- https://www.roblox.com. I have been using Debugger.scriptParsed method.

**Comment by aslushnikov** [comment]
@SergeyFromHell @nammaianh @AshDee this issue doesn't seem to be actionable without a good repro.

If you folks have a reliable script that reproduces this issue on latest Puppeteer, please file another issue - we'd be happy to look into it.
