### ISSUE TITLE
page.type fails on Japanese character

### ISSUE THREAD

**Issue by edwardhct** [puppeteer/puppeteer#3396]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:1.4.0
* chrome: 69.0.3497.81（Official Build)(64Bit)
* Platform / OS version: El Capitan 10.11.6
* URLs (if applicable): N/A
* Node.js version: 8.11.2
* npm: 5.6.0

**What steps will reproduce the problem?**
Error occurs when typing Japanese character(s)

```
    await page.waitFor('input.selector');
    await page.focus('input.selector');
    await page.type('input.selector', 'あいうえお'); <<<<<< 
```

**What is the expected result?**
Expected to type Japanese character(s)

**What happens instead?**
Failed to type Japanese character(s)

stack trace
------------------
```
(node:8365) UnhandledPromiseRejectionWarning: Error: Protocol error (Input.insertText): 'Input.insertText' wasn't found
    at Promise (/Users/uu091430/project/jbg-ga/app/node_modules/puppeteer/lib/Connection.js:203:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/Users/uu091430/project/jbg-ga/app/node_modules/puppeteer/lib/Connection.js:202:12)
    at Keyboard.sendCharacter (/Users/uu091430/project/jbg-ga/app/node_modules/puppeteer/lib/Input.js:151:24)
    at Keyboard.type (/Users/uu091430/project/jbg-ga/app/node_modules/puppeteer/lib/Input.js:166:20)
    at ElementHandle.type (/Users/uu091430/project/jbg-ga/app/node_modules/puppeteer/lib/ExecutionContext.js:413:31)
    at <anonymous>
  writeOut
  output
  process.on
  emitOne
  emit
  (anonymous function)
  _combinedTickCallback
  _tickCallback
(node:8365) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
  writeOut
  output
  process.on
  emitOne
  emit
  (anonymous function)
  _combinedTickCallback
  _tickCallback
(node:8365) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
  writeOut
  output
  process.on
  emitOne
  emit
  (anonymous function)
  _combinedTickCallback
  _tickCallback
```

**Comment by JoelEinbinder** [comment]
Puppeteer only supports the Chromium version it is bundled with. Older versions won't work.
