### ISSUE TITLE
Flacky timeout

### ISSUE THREAD

**Issue by vsemozhetbyt** [puppeteer/puppeteer#3434]
* Puppeteer version: 1.9.0-post (chromium_revision 599821)
* Platform / OS version: Windows 7 x64
* URLs (if applicable): https://www.hackterms.com/
* Node.js version: 10.12.0 or last 11.0.0 [v8-canary](https://github.com/nodejs/node-v8/tree/canary)

Is there a cause that the same code with the same puppeteer on the same OS works right on two different machines in headful mode, while in headless mode on one machine is constantly OK and on the second machine constantly produces timeout?

```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch({ headless: false });
    const [page] = await browser.pages();

    await page.goto('https://www.hackterms.com/');

    console.log(await page.evaluate(() => document.title));

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```
Otput on both machines:
```
Hackterms: a dictionary of programming terms
```

```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch();
    const [page] = await browser.pages();

    await page.goto('https://www.hackterms.com/');

    console.log(await page.evaluate(() => document.title));

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```
The same output on one machine, the error on the second machine:
```
{ TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (puppeteer\lib\FrameManager.js:1230:21)
  -- ASYNC --
    at Frame.<anonymous> (puppeteer\lib\helper.js:144:27)
    at Page.goto (puppeteer\lib\Page.js:579:49)
    at Page.<anonymous> (puppeteer\lib\helper.js:145:23)
    at main (test.js:10:16)
    at process.internalTickCallback (internal/process/next_tick.js:77:7) name: 'TimeoutError' }
```

**Comment by sradu** [comment]
There are a number of tickets open about issues with redirects. Don't know if related.

**Comment by aslushnikov** [comment]
@sradu All redirect issues are related to the request interception bugs we have in CDP; this doesn't seem related.

@vsemozhetbyt can you run your script with 'DEBUG=*session' and post the protocol traffic for the machine that hangs?

**Comment by sradu** [comment]
Got it @aslushnikov! Sorry to butt in.

**Comment by vsemozhetbyt** [comment]
@aslushnikov [The output](https://gist.github.com/vsemozhetbyt/10dcbfd64675257a3ae8f3fc8fae50aa) (after the hanging, the output continued, so I've aborted after some seconds).

**Comment by jasonswearingen** [comment]
usually when I see this kind of timeout error it's because the load event hasn't fired.   That could be if the page has a timed out resource.

For example, I've seen sites that load fine on one computer but timeout on another because some dumb twitter social script load timed out.   

so with the given information honestly I would not be surprised if this is not a bug with chrome, but rather a bug with the page/CDN

With Puppeteer, Is there a simple way to see why a page timesout?

**Comment by vsemozhetbyt** [comment]
FWIW, these two machines are in one home local network.

**Comment by aslushnikov** [comment]
@vsemozhetbyt from the log you've attached, I see that a lot of network requests take forever to load. Check out timing for various `Network.responseReceived` events: in the very end of the line there's a delta time after previous log line, and many of them are in *seconds* rather than milliseconds.

I'd speculate that this has something to do with the network on the machine; it's hard to say anything else though.

**Comment by vsemozhetbyt** [comment]
Can there be a cause that this network issue happens only in headless mode?

**Comment by jasonswearingen** [comment]
fyi, I run a Browser automation SaaS that uses puppeteer headless (on ubuntu x64)  I can load your example page no problem.

Here's my SaaS's JSON output summarizing all the network requests from your hackerterms page:

```json
"resources":[
                "{elapsed:363,detail:'complete:200:OK',start:'180(initialRequest)',ended:'543(initialRequest)',frame:'main(nav)',type:'document',url:''https://www.hackterms.com/''}",
                "{elapsed:160,detail:'complete:200:',start:'579(pageNavigated)',ended:'739(pageNavigated)',frame:'main',type:'stylesheet',url:''https://fonts.googleapis.com/css?family=Zilla+Slab:300,400,500,600''}",
                "{elapsed:161,detail:'complete:200:',start:'579(pageNavigated)',ended:'740(pageNavigated)',frame:'main',type:'script',url:''https://apis.google.com/js/platform.js''}",
                "{elapsed:182,detail:'complete:200:',start:'579(pageNavigated)',ended:'761(pageNavigated)',frame:'main',type:'script',url:''https://apis.google.com/js/platform.js?onload=init''}",
                "{elapsed:183,detail:'complete:200:',start:'579(pageNavigated)',ended:'762(pageNavigated)',frame:'main',type:'script',url:''https://www.googletagmanager.com/gtag/js?id=UA-113877652-1''}",
                "{elapsed:184,detail:'complete:200:OK',start:'579(pageNavigated)',ended:'763(pageNavigated)',frame:'main',type:'stylesheet',url:''https://www.hackterms.com/assets/style.css''}",
                "{elapsed:160,detail:'complete:200:',start:'579(pageNavigated)',ended:'739(pageNavigated)',frame:'main',type:'stylesheet',url:''https://fonts.googleapis.com/css?family=Muli:200,300,400,600''}",
                "{elapsed:2435,detail:'complete:200:',start:'579(pageNavigated)',ended:'3014(pageNavigated)',frame:'main',type:'stylesheet',url:''https://use.fontawesome.com/releases/v5.0.6/css/all.css''}",
                "{elapsed:2436,detail:'complete:200:OK',start:'579(pageNavigated)',ended:'3015(pageNavigated)',frame:'main',type:'script',url:''https://www.hackterms.com/assets/script.js''}",
                "{elapsed:2437,detail:'complete:200:OK',start:'579(pageNavigated)',ended:'3016(pageNavigated)',frame:'main',type:'script',url:''https://code.jquery.com/jquery-2.2.4.min.js''}",
                "{elapsed:2438,detail:'complete:200:',start:'579(pageNavigated)',ended:'3017(pageNavigated)',frame:'main',type:'script',url:''https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.0.10/handlebars.min.js''}",
                "{elapsed:2434,detail:'complete:200:OK',start:'579(pageNavigated)',ended:'3013(pageNavigated)',frame:'main',type:'script',url:''https://www.hackterms.com/assets/utilities.js''}",
                "{elapsed:354,detail:'complete:200:',start:'3160(pageNavigated)',ended:'3514(pageNavigated)',frame:'main',type:'font',url:''https://fonts.gstatic.com/s/zillaslab/v3/dFa6ZfeM_74wlPZtksIFajo6-w.woff''}",
                "{elapsed:352,detail:'complete:200:',start:'3161(pageNavigated)',ended:'3513(pageNavigated)',frame:'main',type:'font',url:''https://fonts.gstatic.com/s/muli/v12/7Auwp_0qiz-afTLGKw.woff''}",
                "{elapsed:354,detail:'complete:200:',start:'3161(pageNavigated)',ended:'3515(pageNavigated)',frame:'main',type:'font',url:''https://fonts.gstatic.com/s/muli/v12/7Au_p_0qiz-ade3iOCX2yQ.woff''}",
                "{elapsed:354,detail:'complete:200:',start:'3161(pageNavigated)',ended:'3515(pageNavigated)',frame:'main',type:'font',url:''https://fonts.gstatic.com/s/muli/v12/7Au_p_0qiz-adZnkOCX2yQ.woff''}",
                "{elapsed:355,detail:'complete:200:',start:'3161(pageNavigated)',ended:'3516(pageNavigated)',frame:'main',type:'script',url:''https://www.google-analytics.com/analytics.js''}",
                "{elapsed:350,detail:'complete:200:',start:'3161(pageNavigated)',ended:'3511(pageNavigated)',frame:'main',type:'script',url:''https://apis.google.com/_/scs/apps-static/_/js/...TcCPdzfaDsFYsZF5Fx6dxuyMdlAHKvg/cb=gapi.loaded_0''}",
                "{elapsed:137,detail:'complete:200:',start:'3590(pageNavigated)',ended:'3727(domReady)',frame:'main',type:'font',url:''https://use.fontawesome.com/releases/v5.0.6/webfonts/fa-solid-900.woff2''}",
                "{elapsed:138,detail:'complete:200:',start:'3590(pageNavigated)',ended:'3728(domReady)',frame:'main',type:'font',url:''https://use.fontawesome.com/releases/v5.0.6/webfonts/fa-regular-400.woff2''}",
                "{elapsed:669,detail:'complete:200:OK',start:'3621(pageNavigated)',ended:'4290(load)',frame:'main',type:'xhr',url:''https://www.hackterms.com/top-terms''}",
                "{elapsed:1131,detail:'complete:200:OK',start:'3621(pageNavigated)',ended:'4752(load)',frame:'main',type:'xhr',url:''https://www.hackterms.com/get-definitions''}",
                "{elapsed:290,detail:'complete:200:OK',start:'3621(pageNavigated)',ended:'3911(domReady)',frame:'main',type:'xhr',url:''https://www.hackterms.com/all-terms''}",
                "{elapsed:118,detail:'complete:302:',start:'3704(domReady)',ended:'3822(domReady)',frame:'main',type:'image',url:''https://www.google-analytics.com/r/collect?v=1&...830637433.1541091443&_r=1&gtm=2ouas3&z=889650107''}",
                "{elapsed:14,detail:'complete:200:',start:'3898(domReady)',ended:'3912(domReady)',frame:'main',type:'image',url:''https://stats.g.doubleclick.net/r/collect?v=1&a...33.1541091443&gjid=1471667200&_v=j71&z=889650107''}",
                "{elapsed:15,detail:'complete:200:',start:'3898(domReady)',ended:'3913(domReady)',frame:'58E8(nav)',type:'document',url:''https://accounts.google.com/o/oauth2/iframe''}",
                "{elapsed:352,detail:'complete:200:',start:'3925(domReady)',ended:'4277(domReady)',frame:'58E8',type:'stylesheet',url:''https://ssl.gstatic.com/accounts/o/749446591-idpiframe_css_ltr.css''}",
                "{elapsed:363,detail:'complete:200:',start:'3925(domReady)',ended:'4288(domReady)',frame:'58E8',type:'script',url:''https://ssl.gstatic.com/accounts/o/3021236038-v2-idpiframe.js''}",
                "{elapsed:59,detail:'complete:200:',start:'4324(load)',ended:'4383(load)',frame:'58E8',type:'xhr',url:''https://accounts.google.com/o/oauth2/iframerpc?...utrvbcd2omt5r3rktmh6v.apps.googleusercontent.com''}"
]
```

that ```resources``` array is sorted by start time.

based on that output, I would suggest that, on your problematic computer, you check what resources are still pending when the ```.goto()``` times out.  My bet would be one of your fonts.    Are you using a persistent userDataDir with puppeteer?  if so, try clearing it out?

**Comment by vsemozhetbyt** [comment]
@jasonswearingen Thank you. If I understand correctly, the mentioned scripts use a new temp user data dir in the temp directory every time, by default.

**Comment by aslushnikov** [comment]
> Can there be a cause that this network issue happens only in headless mode?

@vsemozhetbyt I can't really think of anything that would cause this kind of behavior. Since the same script is running just fine in the same network on a different machine, looks like something's going on with the environment. Maybe there's an anti-virus or something else?

Also, can you try running with `--enable-features=NetworkService` and see if the problem persists?

**Comment by vsemozhetbyt** [comment]
@aslushnikov Unfortunately, `--enable-features=NetworkService` does not this issue. And I've tested with no anti-virus or firewall on.

I will close for now due to an undetectable cause.

Thank you all for the efforts to help!
