### ISSUE TITLE
report action is not work.

### ISSUE THREAD

**Issue by xiongzeng** [puppeteer/puppeteer#3438]
report action:execute:run 'horseman' report:Failed to load url: Error: Failed to load url
    at checkStatus (/home/luozhengxin/elk6.3.0/kibana-6.3.0-linux-x86_64/plugins/sentinl/node_modules/node-horseman/lib/index.js:292:16)
    at tryCatcher (/home/luozhengxin/elk6.3.0/kibana-6.3.0-linux-x86_64/plugins/sentinl/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/home/luozhengxin/elk6.3.0/kibana-6.3.0-linux-x86_64/plugins/sentinl/node_modules/bluebird/js/release/method.js:39:29)
    at Object.loadFinishedSetup [as onLoadFinished] (/home/luozhengxin/elk6.3.0/kibana-6.3.0-linux-x86_64/plugins/sentinl/node_modules/node-horseman/lib/index.js:290:43)
    at /home/luozhengxin/elk6.3.0/kibana-6.3.0-linux-x86_64/plugins/sentinl/node_modules/node-phantom-simple/node-phantom-simple.js:636:30
    at Array.forEach (<anonymous>)
    at IncomingMessage.<anonymous> (/home/luozhengxin/elk6.3.0/kibana-6.3.0-linux-x86_64/plugins/sentinl/node_modules/node-phantom-simple/node-phantom-simple.js:617:17)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

**Comment by entrptaher** [comment]
Issue should be closed. 

- Horseman is no longer maintained. It is not related to puppeteer. Its strictly related to PhantomJS.
- You should consider using puppeteer, nightmareJS or something similar as alternative.
