### ISSUE TITLE
Consecutive launch with  `headless: false` and userDataDir fails

### ISSUE THREAD

**Issue by vsemozhetbyt** [puppeteer/puppeteer#3452]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.9.0-post (chromium_revision 599821)
* Platform / OS version: Windows 7 x64
* URLs (if applicable): https://twitter.com/
* Node.js version: 11.0.0 (or 12.0.0-v8-canary)

**What steps will reproduce the problem?**

1. Run this code, log in the Twitter account, close the browser.
```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch({
      headless: false,
      userDataDir: 'test-profile-dir',
    });
    const [page] = await browser.pages();
    await page.goto('https://twitter.com/');
    console.log(await page.evaluate(() => document.title));
  } catch (err) {
    console.error(err);
  }
})();
```
2. Run the same script the second time, See the error:
```
Error: Execution context was destroyed, most likely because of a navigation.
    at rewriteError (C:\Users\vmb\AppData\Roaming\npm\node_modules\puppeteer\lib\ExecutionContext.js:144:15)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (C:\Users\vmb\AppData\Roaming\npm\node_modules\puppeteer\lib\helper.js:144:27)
    at ExecutionContext.evaluate (C:\Users\vmb\AppData\Roaming\npm\node_modules\puppeteer\lib\ExecutionContext.js:58:31)
    at ExecutionContext.<anonymous> (C:\Users\vmb\AppData\Roaming\npm\node_modules\puppeteer\lib\helper.js:145:23)
    at Frame.evaluate (C:\Users\vmb\AppData\Roaming\npm\node_modules\puppeteer\lib\FrameManager.js:439:20)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
  -- ASYNC --
    at Frame.<anonymous> (C:\Users\vmb\AppData\Roaming\npm\node_modules\puppeteer\lib\helper.js:144:27)
    at Page.evaluate (C:\Users\vmb\AppData\Roaming\npm\node_modules\puppeteer\lib\Page.js:728:43)
    at Page.<anonymous> (C:\Users\vmb\AppData\Roaming\npm\node_modules\puppeteer\lib\helper.js:145:23)
    at main (e:\DOC\prg\js\node\-test\test.js:17:28)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

**Comment by vsemozhetbyt** [comment]
Currently can reproduce only with Twitter. Google is OK.

**Comment by JoelEinbinder** [comment]
Looks like this isn't a headless/userDataDir issue. Everything authenticates correctly. Twitter is just doing a second navigation after the first resolves, which you are failing to await.

**Comment by vsemozhetbyt** [comment]
How should I secure against this?

**Comment by JoelEinbinder** [comment]
If you are confident there will be a second navigation:
`await page.waitForNavigation()` immediately after the first `goto`.

**Comment by vsemozhetbyt** [comment]
And if I am not confident, I can only fix the code post-factum, after this error emerges?

**Comment by JoelEinbinder** [comment]
you could try to use waitForSelector or waitForFunction to make sure the page is in a state you expect. If you wait a foolproof way of knowing when an arbitratary page is done navigating, that’s unfortunately unsolvable.

**Comment by vsemozhetbyt** [comment]
Thank you.

**Comment by vsemozhetbyt** [comment]
BTW, `waitUntil: 'networkidle0'` in the `page.goto()` options fixes this issue.
