### ISSUE TITLE
Chrome crash on puppeteer usage

### ISSUE THREAD

**Issue by brauliobo** [puppeteer/puppeteer#3478]
```
~/P/o/reports-daemon ❯❯❯ node headless/puppeteer.js 'http://localhost:4000/templates/reputation-lab/?token=x&company_id=38&start_date=2018-01-01&end_date=2018
-01-31'                                                    
(node:28503) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!                                                                                                               
[1101/123400.360222:FATAL:zygote_host_impl_linux.cc(116)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_develo
pment.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.                        
#0 0x555559ca1cac base::debug::StackTrace::StackTrace()                                                            
#1 0x555559c1b670 logging::LogMessage::~LogMessage()                                                      
#2 0x55555b11f050 service_manager::ZygoteHostImpl::Init()
#3 0x5555598e4d7e content::ContentMainRunnerImpl::Initialize()                          
#4 0x5555599183e8 service_manager::Main()                                               
#5 0x5555598e35c1 content::ContentMain()                                                
#6 0x55555ddbcae8 headless::(anonymous namespace)::RunContentMain()                                                                                                                         
#7 0x55555ddbcb78 headless::HeadlessBrowserMain()                                       
#8 0x5555599159db headless::HeadlessShellMain()                   
#9 0x555557c231ac ChromeMain                                         
#10 0x7ffff52c7223 __libc_start_main                                                                                                                  
#11 0x555557c2302a _start                     
                                                                         
Received signal 6                                                                                    
#0 0x555559ca1cac base::debug::StackTrace::StackTrace()                 
#1 0x555559ca1821 base::debug::(anonymous namespace)::StackDumpSignalHandler()                            
#2 0x7ffff7f603c0 <unknown>                                                                                                         
#3 0x7ffff52dad7f __GI_raise                            
#4 0x7ffff52c5672 __GI_abort              
#5 0x555559ca0645 base::debug::BreakDebugger()                                                       
#6 0x555559c1bae8 logging::LogMessage::~LogMessage()
#7 0x55555b11f050 service_manager::ZygoteHostImpl::Init()          
#8 0x5555598e4d7e content::ContentMainRunnerImpl::Initialize()           
#9 0x5555599183e8 service_manager::Main()                                                                                                                                                    
#10 0x5555598e35c1 content::ContentMain()                  
#11 0x55555ddbcae8 headless::(anonymous namespace)::RunContentMain()                                                                                                                         
#12 0x55555ddbcb78 headless::HeadlessBrowserMain()                
#13 0x5555599159db headless::HeadlessShellMain()                                                                                                                                            
#14 0x555557c231ac ChromeMain                                                                                                                                                               
#15 0x7ffff52c7223 __libc_start_main
#16 0x555557c2302a _start
  r8: 0000000000000000  r9: 00007fffffffa410 r10: 0000000000000008 r11: 0000000000000246
 r12: 00007fffffffac38 r13: 0000000000000161 r14: 00007fffffffac40 r15: 00007fffffffac48
  di: 0000000000000002  si: 00007fffffffa410  bp: 00007fffffffa660  bx: 0000000000000006
  dx: 0000000000000000  ax: 0000000000000000  cx: 00007ffff52dad7f  sp: 00007fffffffa410
  ip: 00007ffff52dad7f efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/home/braulio/Projects/olery/reports-daemon/node_modules/puppeteer/lib/Launcher.js:339:14)
    at Interface.helper.addEventListener (/home/braulio/Projects/olery/reports-daemon/node_modules/puppeteer/lib/Launcher.js:328:50)
    at Interface.emit (events.js:187:15)
    at Interface.close (readline.js:379:8)
    at Socket.onend (readline.js:157:10)
    at Socket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
(node:28503) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a pro
mise which was not handled with .catch(). (rejection id: 1)
(node:28503) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-
zero exit code.
```

**Tell us about your environment:**

* Puppeteer version: 1.9.0
* Platform / OS version: ArchLinux

**Comment by jasonswearingen** [comment]
@brauliobo please see the sandbox section of this page:  https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

**Comment by brauliobo** [comment]
Why wasnt `build/update-linux-sandbox.sh` run in the installation? It seems to be a requirement.

**Comment by aslushnikov** [comment]
@brauliobo i think this is a requirement for the developer workflow; the sandbox binary is prebuilt and ships with executable.
