### ISSUE TITLE
Evaluate seems not to have context to an object

### ISSUE THREAD

**Issue by nei** [puppeteer/puppeteer#3499]
I'm using the latest version 1.10.0 and I am trying to execute a function using evaluate and I am getting an error. Interesting that if I open the console and type the function it does work.

Maybe the issue is due to the command exist just on the new window that my puppeter code execute.

If I open the console from the new window and type the js code I want it does execute properly.
```
$obj.addWidget('history');
```

But my evaluate code does not work. what I am missing here?

```
document.querySelector('#button').click();// this open my new window
await page.evaluate(() => {
          $obj.addWidget('history');
        });
```
**Tell us about your environment:**

* Puppeteer version: 1.10.0
* Platform / OS version: macOS 10.13.06
* Node.js version: v10.8.0

Details of the error:
```
(node:89165) UnhandledPromiseRejectionWarning: Error: Evaluation failed: ReferenceError: $obj is not defined
    at __puppeteer_evaluation_script__:3:11
    at ExecutionContext.evaluateHandle (node_modules/puppeteer/lib/ExecutionContext.js:124:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (node_modules/puppeteer/lib/helper.js:144:27)
    at ExecutionContext.evaluate (node_modules/puppeteer/lib/ExecutionContext.js:58:31)
    at ExecutionContext.<anonymous> (node_modules/puppeteer/lib/helper.js:145:23)
    at Frame.evaluate (node_modules/puppeteer/lib/FrameManager.js:439:20)
  -- ASYNC --
    at Frame.<anonymous> (node_modules/puppeteer/lib/helper.js:144:27)
    at Page.evaluate (node_modules/puppeteer/lib/Page.js:736:43)
    at Page.<anonymous> (node_modules/puppeteer/lib/helper.js:145:23)
```

**Comment by vsemozhetbyt** [comment]
Can you try `window.$obj.addWidget('history');`?

**Comment by nei** [comment]
After quite some hours I found I needed to evaluate from the new page.

```
let getNewPageWhenLoaded = function() {
            return new Promise((x) => browser.once('targetcreated', async (target) => {
                const newPage = await target.page();
                const newPagePromise = new Promise(() => newPage.once('domcontentloaded', () => x(newPage)));
                const isPageLoaded = await newPage.evaluate(() => document.readyState);
                return isPageLoaded.match('complete|interactive') ? x(newPage) : newPagePromise;
            }));
        };

        const newPagePromise = getNewPageWhenLoaded();
        await page.evaluate(() => {
          document.querySelector('#buttonForNewPage').click();
        });
        const newPage = await newPagePromise;
        const MenuItem = await newPage.$x('//*[@id="menu"]/li/div/div[1]/div[17]/img');
        if (MenuItem.length > 0) {
            await MenuItem[0].click();
        }
```
I've tried this but did not work.
```
await newPage.evaluate(() => {
            console.log($obj.addWidget('history'));
        });
```
So I solved my clicking where the funcion is executed.
