### ISSUE TITLE
Error: ENOENT: no such file or directory, open './images/123.png'

### ISSUE THREAD

**Issue by brandondurham** [puppeteer/puppeteer#3529]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.10.0
* Platform / OS version: macOS High Sierra 10.13.6
* URLs (if applicable): n/a
* Node.js version: 8.12.0

**What steps will reproduce the problem?**

I’m developing locally currently. My front-end is being served at `http://local.website.com:3002/` and the back-end (Node/Express) is running at `http://local.website.com:5000/`. In between sits a small proxy that looks like this:

```js
const proxy = require('http-proxy-middleware')
const port = process.env.PORT || 5000
module.exports = function(app) {
	app.use(proxy('/chore', { target: `http://local.website.com:${port}/`, changeOrigin: true }))
}
```

The front-end sends a request for a screenshot to `/chore/${id}?height=${height}&width=${width}` which is then picked up vy Express:

```js
app.get('/chore/:id', async (req, res) => {
	const { id } = req.params

	const height = parseInt(req.query.height)
	const width = parseInt(req.query.width)

	await puppeteer.launch({
		headless: true,
	}).then(async browser => {
		const page = await browser.newPage()
		page.setViewport({
			deviceScaleFactor: 2,
			height: height + 110,
			width: width,
		})

		await page.goto(
			`http://local.website.com:3002/screenshot?height=${height + 110}&width=${width}`,
			{ waitUntil: 'networkidle0' }
		)

		try {
			await page.screenshot({
				path: `./images/${id}.png`,
			})
		} catch (err) {
			console.log('Error generating screenshot', err)
		}

		await browser.close()

		res.send({
			status: 'complete',
			image: {
				name: id,
				path: `images/${id}.png`,
				size: {
					height,
					width,
				},
			},
		})
	})
})
```

As soon as the script hits `page.screenshot()` I get the following error:

```bash
Error generating screenshot { Error: ENOENT: no such file or directory, open './images/123.png'
  -- ASYNC --
    at Page.<anonymous> (/Users/me/work/editor/node_modules/puppeteer/lib/helper.js:144:27)
    at puppeteer.launch.then (/Users/me/work/editor/src/server/index.js:41:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './images/123.png' }
```

**What is the expected result?**
The screenshot would be generated and output to `images/${id}.png`.

**What happens instead?**
`page.screenshot()` throws the above error and no image is created.

This exact setup on my home machine with the same environment details works perfectly.

**Comment by brandondurham** [comment]
I’m a fool. It was trying to find the image directory from the root of the project. This simple update solved the problem:

```diff
await page.screenshot({
-	path: '../static/images/${id}.png'
+	path: path.join(__dirname, `../static/images/${id}.png`)
});
```
