### ISSUE TITLE
Why socket hang up Error

### ISSUE THREAD

**Issue by HassyMasa** [puppeteer/puppeteer#3605]
Error: socket hang up
   at createHangUpError (_http_client.js:330:15)
   at Socket.socketOnEnd (_http_client.js:433:23)
   at Socket.emit (events.js:187:15)
   at endReadableNT (_stream_readable.js:1098:12)
   at process.internalTickCallback (internal/process/next_tick.js:72:19) code: 'ECONNRESET'

CENTOS7

$ node -v
v11.3.0
$ npm -v
6.4.1
$ yarn -v
1.12.3

puppeteer v1.10.0

$ yum install pango.x86_64 libXcomposite.x86_64 libXcursor.x86_64 libXdamage.x86_64 libXext.x86_64 libXi.x86_64 libXtst.x86_64 cups-libs.x86_64 libXScrnSaver.x86_64 libXrandr.x86_64 GConf2.x86_64 alsa-lib.x86_64 atk.x86_64 gtk3.x86_64 -y

const BROWSEROPT = [
        '--no-sandbox',
        '--disable-setuid-sandbox',
      ];
const browser = await puppeteer.launch({ ignoreHTTPSErrors: true, args : BROWSEROPT });
↓
const browser = await puppeteer.launch({ **dumpio: true,** ignoreHTTPSErrors: true, args : BROWSEROPT });

console output is
```
Fontconfig warning: "/etc/fonts/fonts.conf", line 86: unknown element "blank"
[1207/115433.319699:ERROR:gpu_process_transport_factory.cc(967)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:43297/devtools/browser/cba00b12-562f-43e1-88a8-738abbff30ec
[1207/115433.329449:FATAL:platform_font_linux.cc(83)] Check failed: InitDefaultFont(). Could not find the default font
#0 0x7f68d82877df base::debug::StackTrace::StackTrace()
#1 0x7f68d8200f70 logging::LogMessage::~LogMessage()
#2 0x7f68d87b7044 gfx::PlatformFontLinux::PlatformFontLinux()
#3 0x7f68d87b806b gfx::PlatformFont::CreateDefault()
#4 0x7f68d87afb4e gfx::Font::Font()
#5 0x7f68d6d79312 content::RenderViewHostImpl::CreateRenderView()
#6 0x7f68d6e8764f content::WebContentsImpl::CreateRenderViewForRenderManager()
#7 0x7f68d6c1139e content::RenderFrameHostManager::ReinitializeRenderFrame()
#8 0x7f68d6c10d57 content::RenderFrameHostManager::GetFrameHostForNavigation()
#9 0x7f68d6c108f2 content::RenderFrameHostManager::DidCreateNavigationRequest()
#10 0x7f68d6bc9369 content::FrameTreeNode::CreatedNavigationRequest()
#11 0x7f68d6be9f83 content::NavigatorImpl::Navigate()
#12 0x7f68d6bd07de content::NavigationControllerImpl::NavigateWithoutEntry()
#13 0x7f68d6bd0268 content::NavigationControllerImpl::LoadURLWithParams()
#14 0x7f68dc21d92f headless::HeadlessWebContentsImpl::Create()
#15 0x7f68dc221159 headless::HeadlessBrowserContextImpl::CreateWebContents()
#16 0x7f68d7e907b7 headless::HeadlessShell::OnGotURLs()
#17 0x7f68d69a57af base::internal::ReplyAdapter<>()
#18 0x7f68d6275837 _ZN4base8internal7InvokerINS0_9BindStateIPFvNS_12OnceCallbackIFvbEEEPNSt3__110unique_ptrIbNS6_14default_deleteIbEEEEEJS5_NS0_12OwnedWrapperISA_EEEEEFvvEE7RunOnceEPNS0_13BindStateBaseE
#19 0x7f68d6b3d95e _ZN4base8internal7InvokerINS0_9BindStateIZN7content8protocol12_GLOBAL__N_114SetCookiesOnIOEPN3net23URLRequestContextGetterENSt3__16vectorINS9_10unique_ptrINS6_15CanonicalCookieENS9_14default_deleteISC_EEEENS9_9allocatorISF_EEEENS_12OnceCallbackIFvvEEEE3$_4JNS_17RepeatingCallbackISK_EEEEEFvbEE7RunOnceEPNS0_13BindStateBaseEb
#20 0x7f68d825d49a _ZN4base8internal7InvokerINS0_9BindStateIPFvNS_12_GLOBAL__N_121PostTaskAndReplyRelayEEJS4_EEEFvvEE7RunOnceEPNS0_13BindStateBaseE
#21 0x7f68d8206511 base::debug::TaskAnnotator::RunTask()
#22 0x7f68d820576f base::MessageLoop::RunTask()
#23 0x7f68d8205af2 base::MessageLoop::DoWork()
#24 0x7f68d82086cf base::(anonymous namespace)::WorkSourceDispatch()
#25 0x7f68d1394969 g_main_context_dispatch
#26 0x7f68d1394cc8 <unknown>
#27 0x7f68d1394d7c g_main_context_iteration
#28 0x7f68d8208582 base::MessagePumpGlib::Run()
#29 0x7f68d82243c5 base::RunLoop::Run()
#30 0x7f68d6aacbc4 content::BrowserMainLoop::MainMessageLoopRun()
#31 0x7f68d6aac983 content::BrowserMainLoop::RunMainMessageLoopParts()
#32 0x7f68d6aaf492 content::BrowserMainRunnerImpl::Run()
#33 0x7f68dc2235ef headless::HeadlessContentMainDelegate::RunProcess()
#34 0x7f68d7e64e46 content::ContentMainRunnerImpl::Run()
#35 0x7f68d7e9642b service_manager::Main()
#36 0x7f68d7e63111 content::ContentMain()
#37 0x7f68dc222488 headless::(anonymous namespace)::RunContentMain()
#38 0x7f68dc222515 headless::HeadlessBrowserMain()
#39 0x7f68d7e948b2 headless::HeadlessShellMain()
#40 0x7f68d5fab1ac ChromeMain
#41 0x7f68cd118c05 __libc_start_main
#42 0x7f68d5fab02a _start

Received signal 6
#0 0x7f68d82877df base::debug::StackTrace::StackTrace()
#1 0x7f68d8287351 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#2 0x7f68d32725e0 <unknown>
#3 0x7f68cd12c1f7 __GI_raise
#4 0x7f68cd12d8e8 __GI_abort
#5 0x7f68d8286185 base::debug::BreakDebugger()
#6 0x7f68d82013e2 logging::LogMessage::~LogMessage()
#7 0x7f68d87b7044 gfx::PlatformFontLinux::PlatformFontLinux()
#8 0x7f68d87b806b gfx::PlatformFont::CreateDefault()
#9 0x7f68d87afb4e gfx::Font::Font()
#10 0x7f68d6d79312 content::RenderViewHostImpl::CreateRenderView()
#11 0x7f68d6e8764f content::WebContentsImpl::CreateRenderViewForRenderManager()
#12 0x7f68d6c1139e content::RenderFrameHostManager::ReinitializeRenderFrame()
#13 0x7f68d6c10d57 content::RenderFrameHostManager::GetFrameHostForNavigation()
#14 0x7f68d6c108f2 content::RenderFrameHostManager::DidCreateNavigationRequest()
#15 0x7f68d6bc9369 content::FrameTreeNode::CreatedNavigationRequest()
#16 0x7f68d6be9f83 content::NavigatorImpl::Navigate()
#17 0x7f68d6bd07de content::NavigationControllerImpl::NavigateWithoutEntry()
#18 0x7f68d6bd0268 content::NavigationControllerImpl::LoadURLWithParams()
#19 0x7f68dc21d92f headless::HeadlessWebContentsImpl::Create()
#20 0x7f68dc221159 headless::HeadlessBrowserContextImpl::CreateWebContents()
#21 0x7f68d7e907b7 headless::HeadlessShell::OnGotURLs()
#22 0x7f68d69a57af base::internal::ReplyAdapter<>()
#23 0x7f68d6275837 _ZN4base8internal7InvokerINS0_9BindStateIPFvNS_12OnceCallbackIFvbEEEPNSt3__110unique_ptrIbNS6_14default_deleteIbEEEEEJS5_NS0_12OwnedWrapperISA_EEEEEFvvEE7RunOnceEPNS0_13BindStateBaseE
#24 0x7f68d6b3d95e _ZN4base8internal7InvokerINS0_9BindStateIZN7content8protocol12_GLOBAL__N_114SetCookiesOnIOEPN3net23URLRequestContextGetterENSt3__16vectorINS9_10unique_ptrINS6_15CanonicalCookieENS9_14default_deleteISC_EEEENS9_9allocatorISF_EEEENS_12OnceCallbackIFvvEEEE3$_4JNS_17RepeatingCallbackISK_EEEEEFvbEE7RunOnceEPNS0_13BindStateBaseEb
#25 0x7f68d825d49a _ZN4base8internal7InvokerINS0_9BindStateIPFvNS_12_GLOBAL__N_121PostTaskAndReplyRelayEEJS4_EEEFvvEE7RunOnceEPNS0_13BindStateBaseE
#26 0x7f68d8206511 base::debug::TaskAnnotator::RunTask()
#27 0x7f68d820576f base::MessageLoop::RunTask()
#28 0x7f68d8205af2 base::MessageLoop::DoWork()
#29 0x7f68d82086cf base::(anonymous namespace)::WorkSourceDispatch()
#30 0x7f68d1394969 g_main_context_dispatch
#31 0x7f68d1394cc8 <unknown>
#32 0x7f68d1394d7c g_main_context_iteration
#33 0x7f68d8208582 base::MessagePumpGlib::Run()
#34 0x7f68d82243c5 base::RunLoop::Run()
#35 0x7f68d6aacbc4 content::BrowserMainLoop::MainMessageLoopRun()
#36 0x7f68d6aac983 content::BrowserMainLoop::RunMainMessageLoopParts()
#37 0x7f68d6aaf492 content::BrowserMainRunnerImpl::Run()
#38 0x7f68dc2235ef headless::HeadlessContentMainDelegate::RunProcess()
#39 0x7f68d7e64e46 content::ContentMainRunnerImpl::Run()
#40 0x7f68d7e9642b service_manager::Main()
#41 0x7f68d7e63111 content::ContentMain()
#42 0x7f68dc222488 headless::(anonymous namespace)::RunContentMain()
#43 0x7f68dc222515 headless::HeadlessBrowserMain()
#44 0x7f68d7e948b2 headless::HeadlessShellMain()
#45 0x7f68d5fab1ac ChromeMain
#46 0x7f68cd118c05 __libc_start_main
#47 0x7f68d5fab02a _start
  r8: 00007f68d3842ac0  r9: 00002c031aa24400 r10: 0000000000000008 r11: 0000000000000202
 r12: 00007ffc6fa54c38 r13: 0000000000000076 r14: 00007ffc6fa54c40 r15: 00007ffc6fa54c48
  di: 0000000000005afe  si: 0000000000005afe  bp: 00007ffc6fa54290  bx: 00007ffc6fa542f0
  dx: 0000000000000006  ax: 0000000000000000  cx: ffffffffffffffff  sp: 00007ffc6fa54158
  ip: 00007f68cd12c1f7 efl: 0000000000000202 cgf: 0000000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
ErrorEvent {
  target:
   WebSocket {
     _events:
      [Object: null prototype] {
        open: { [Function: onOpen] _listener: [Function] },
        error: { [Function: onError] _listener: [Function] } },
     _eventsCount: 2,
     _maxListeners: undefined,
     readyState: 3,
     protocol: '',
     _binaryType: 'nodebuffer',
     _closeFrameReceived: false,
     _closeFrameSent: false,
     _closeMessage: '',
     _closeTimer: null,
     _closeCode: 1006,
     _extensions: {},
     _isServer: false,
     _receiver: null,
     _sender: null,
     _socket: null,
     url:
      'ws://127.0.0.1:43297/devtools/browser/cba00b12-562f-43e1-88a8-738abbff30ec',
     _req: null },
  type: 'error',
  message: 'socket hang up',
  error:
   { Error: socket hang up
       at createHangUpError (_http_client.js:330:15)
       at Socket.socketOnEnd (_http_client.js:433:23)
       at Socket.emit (events.js:187:15)
       at endReadableNT (_stream_readable.js:1098:12)
       at process.internalTickCallback (internal/process/next_tick.js:72:19) code: 'ECONNRESET' } }

```
```
$ ldd ./node_modules/puppeteer/.local-chromium/linux-599821/chrome-linux/chrome

	linux-vdso.so.1 =>  (0x00007ffd8756d000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007ff101b96000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ff10197a000)
	librt.so.1 => /lib64/librt.so.1 (0x00007ff101771000)
	libX11.so.6 => /lib64/libX11.so.6 (0x00007ff101433000)
	libX11-xcb.so.1 => /lib64/libX11-xcb.so.1 (0x00007ff101231000)
	libxcb.so.1 => /lib64/libxcb.so.1 (0x00007ff10100e000)
	libXcomposite.so.1 => /lib64/libXcomposite.so.1 (0x00007ff100e0b000)
	libXcursor.so.1 => /lib64/libXcursor.so.1 (0x00007ff100c00000)
	libXdamage.so.1 => /lib64/libXdamage.so.1 (0x00007ff1009fc000)
	libXext.so.6 => /lib64/libXext.so.6 (0x00007ff1007ea000)
	libXfixes.so.3 => /lib64/libXfixes.so.3 (0x00007ff1005e4000)
	libXi.so.6 => /lib64/libXi.so.6 (0x00007ff1003d3000)
	libXrender.so.1 => /lib64/libXrender.so.1 (0x00007ff1001c8000)
	libXtst.so.6 => /lib64/libXtst.so.6 (0x00007ff0fffc2000)
	libgobject-2.0.so.0 => /lib64/libgobject-2.0.so.0 (0x00007ff0ffd70000)
	libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007ff0ffa5c000)
	libnss3.so => /lib64/libnss3.so (0x00007ff0ff732000)
	libnssutil3.so => /lib64/libnssutil3.so (0x00007ff0ff504000)
	libsmime3.so => /lib64/libsmime3.so (0x00007ff0ff2dd000)
	libnspr4.so => /lib64/libnspr4.so (0x00007ff0ff09f000)
	libcups.so.2 => /lib64/libcups.so.2 (0x00007ff0fee35000)
	libexpat.so.1 => /lib64/libexpat.so.1 (0x00007ff0fec0b000)
	libdbus-1.so.3 => /lib64/libdbus-1.so.3 (0x00007ff0fe9bb000)
	libXss.so.1 => /lib64/libXss.so.1 (0x00007ff0fe7b6000)
	libuuid.so.1 => /lib64/libuuid.so.1 (0x00007ff0fe5b1000)
	libXrandr.so.2 => /lib64/libXrandr.so.2 (0x00007ff0fe3a6000)
	libgio-2.0.so.0 => /lib64/libgio-2.0.so.0 (0x00007ff0fe00a000)
	libm.so.6 => /lib64/libm.so.6 (0x00007ff0fdd08000)
	libasound.so.2 => /lib64/libasound.so.2 (0x00007ff0fda0a000)
	libpangocairo-1.0.so.0 => /lib64/libpangocairo-1.0.so.0 (0x00007ff0fd7fc000)
	libpango-1.0.so.0 => /lib64/libpango-1.0.so.0 (0x00007ff0fd5b1000)
	libcairo.so.2 => /lib64/libcairo.so.2 (0x00007ff0fd289000)
	libatk-1.0.so.0 => /lib64/libatk-1.0.so.0 (0x00007ff0fd062000)
	libatk-bridge-2.0.so.0 => /lib64/libatk-bridge-2.0.so.0 (0x00007ff0fce33000)
	libatspi.so.0 => /lib64/libatspi.so.0 (0x00007ff0fcc03000)
	libgtk-3.so.0 => /lib64/libgtk-3.so.0 (0x00007ff0fc2ef000)
	libgdk-3.so.0 => /lib64/libgdk-3.so.0 (0x00007ff0fc003000)
	libgdk_pixbuf-2.0.so.0 => /lib64/libgdk_pixbuf-2.0.so.0 (0x00007ff0fbddb000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007ff0fbbc4000)
	libc.so.6 => /lib64/libc.so.6 (0x00007ff0fb801000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ff10aea3000)
	libXau.so.6 => /lib64/libXau.so.6 (0x00007ff0fb5fd000)
	libpcre.so.1 => /lib64/libpcre.so.1 (0x00007ff0fb39a000)
	libffi.so.6 => /lib64/libffi.so.6 (0x00007ff0fb192000)
	libplc4.so => /lib64/libplc4.so (0x00007ff0faf8c000)
	libplds4.so => /lib64/libplds4.so (0x00007ff0fad88000)
	libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007ff0fab3a000)
	libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007ff0fa852000)
	libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007ff0fa61f000)
	libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007ff0fa41a000)
	libssl.so.10 => /lib64/libssl.so.10 (0x00007ff0fa1a8000)
	libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007ff0f9d47000)
	libavahi-common.so.3 => /lib64/libavahi-common.so.3 (0x00007ff0f9b39000)
	libavahi-client.so.3 => /lib64/libavahi-client.so.3 (0x00007ff0f9928000)
	libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007ff0f96f1000)
	libz.so.1 => /lib64/libz.so.1 (0x00007ff0f94da000)
	libsystemd.so.0 => /lib64/libsystemd.so.0 (0x00007ff0f94b2000)
	libgmodule-2.0.so.0 => /lib64/libgmodule-2.0.so.0 (0x00007ff0f92ad000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007ff0f9086000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007ff0f8e6c000)
	libmount.so.1 => /lib64/libmount.so.1 (0x00007ff0f8c2b000)
	libpangoft2-1.0.so.0 => /lib64/libpangoft2-1.0.so.0 (0x00007ff0f8a15000)
	libthai.so.0 => /lib64/libthai.so.0 (0x00007ff0f8809000)
	libgthread-2.0.so.0 => /lib64/libgthread-2.0.so.0 (0x00007ff0f8606000)
	libharfbuzz.so.0 => /lib64/libharfbuzz.so.0 (0x00007ff0f83a3000)
	libfontconfig.so.1 => /lib64/libfontconfig.so.1 (0x00007ff0f8166000)
	libfreetype.so.6 => /lib64/libfreetype.so.6 (0x00007ff0f7ebf000)
	libpixman-1.so.0 => /lib64/libpixman-1.so.0 (0x00007ff0f7c16000)
	libEGL.so.1 => /lib64/libEGL.so.1 (0x00007ff0f79e0000)
	libpng15.so.15 => /lib64/libpng15.so.15 (0x00007ff0f77b4000)
	libxcb-shm.so.0 => /lib64/libxcb-shm.so.0 (0x00007ff0f75b0000)
	libxcb-render.so.0 => /lib64/libxcb-render.so.0 (0x00007ff0f73a6000)
	libGL.so.1 => /lib64/libGL.so.1 (0x00007ff0f7133000)
	libcairo-gobject.so.2 => /lib64/libcairo-gobject.so.2 (0x00007ff0f6f2a000)
	libepoxy.so.0 => /lib64/libepoxy.so.0 (0x00007ff0f6c34000)
	libXinerama.so.1 => /lib64/libXinerama.so.1 (0x00007ff0f6a31000)
	libxkbcommon.so.0 => /lib64/libxkbcommon.so.0 (0x00007ff0f67f1000)
	libwayland-cursor.so.0 => /lib64/libwayland-cursor.so.0 (0x00007ff0f65e8000)
	libwayland-egl.so.1 => /lib64/libwayland-egl.so.1 (0x00007ff0f63e6000)
	libwayland-client.so.0 => /lib64/libwayland-client.so.0 (0x00007ff0f61d7000)
	libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007ff0f5fc8000)
	libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007ff0f5dc4000)
	libfreebl3.so => /lib64/libfreebl3.so (0x00007ff0f5bc0000)
	libcap.so.2 => /lib64/libcap.so.2 (0x00007ff0f59bb000)
	liblzma.so.5 => /lib64/liblzma.so.5 (0x00007ff0f5795000)
	libgcrypt.so.11 => /lib64/libgcrypt.so.11 (0x00007ff0f5513000)
	libgpg-error.so.0 => /lib64/libgpg-error.so.0 (0x00007ff0f530e000)
	libdw.so.1 => /lib64/libdw.so.1 (0x00007ff0f50c6000)
	libblkid.so.1 => /lib64/libblkid.so.1 (0x00007ff0f4e87000)
	libgraphite2.so.3 => /lib64/libgraphite2.so.3 (0x00007ff0f4c59000)
	libxcb-dri2.so.0 => /lib64/libxcb-dri2.so.0 (0x00007ff0f4a53000)
	libxcb-dri3.so.0 => /lib64/libxcb-dri3.so.0 (0x00007ff0f4850000)
	libxcb-xfixes.so.0 => /lib64/libxcb-xfixes.so.0 (0x00007ff0f4648000)
	libxcb-present.so.0 => /lib64/libxcb-present.so.0 (0x00007ff0f4444000)
	libxcb-sync.so.1 => /lib64/libxcb-sync.so.1 (0x00007ff0f423d000)
	libxshmfence.so.1 => /lib64/libxshmfence.so.1 (0x00007ff0f403a000)
	libgbm.so.1 => /lib64/libgbm.so.1 (0x00007ff0f3e2b000)
	libwayland-server.so.0 => /lib64/libwayland-server.so.0 (0x00007ff0f3c18000)
	libdrm.so.2 => /lib64/libdrm.so.2 (0x00007ff0f3a07000)
	libglapi.so.0 => /lib64/libglapi.so.0 (0x00007ff0f37d6000)
	libxcb-glx.so.0 => /lib64/libxcb-glx.so.0 (0x00007ff0f35bc000)
	libXxf86vm.so.1 => /lib64/libXxf86vm.so.1 (0x00007ff0f33b6000)
	libattr.so.1 => /lib64/libattr.so.1 (0x00007ff0f31b0000)
	libelf.so.1 => /lib64/libelf.so.1 (0x00007ff0f2f97000)
	libbz2.so.1 => /lib64/libbz2.so.1 (0x00007ff0f2d87000)
```

**Comment by nicoandmee** [comment]
are you running puppeteer at scale? i have encountered this when executing multiple puppeteer workflows (and other web-scraping stuff at the same time).

**Comment by HassyMasa** [comment]
`$ yum install ipa-gothic-fonts ipa-mincho-fonts ipa-pgothic-fonts ipa-pmincho-fonts`
Solved!! :-)

**Comment by Kikobeats** [comment]
@HassyMasa not sure how fonts are related with the original issue 🤔 did you fix your problem? did you take any other consideration?

**Comment by ecolss** [comment]
I'm having the same issue,

**Comment by StephanMeijer** [comment]
Weirdly enough installing such fonts seemed to fix the issue on my side also. I don't know why
