### ISSUE TITLE
How to use page.tracing.start ?? - UnhandledPromiseRejectionWarning: Error: Protocol error (Tracing.start): Tracing is already started

### ISSUE THREAD

**Issue by kimsangsoo** [puppeteer/puppeteer#3639]
```
Error 
(node:15488) UnhandledPromiseRejectionWarning: Error: Protocol error (Tracing.start): Tracing is already started
    at Promise (/Users/user/git/src/main/puppeteer/node_modules/puppeteer/lib/Connection.js:186:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/Users/user/git/src/main/puppeteer/node_modules/puppeteer/lib/Connection.js:185:12)
    at Tracing.start (/Users/user/git/src/main/puppeteer/node_modules/puppeteer/lib/Tracing.js:56:24)
    at Tracing.<anonymous> (/Users/user/git/src/main/puppeteer/node_modules/puppeteer/lib/helper.js:145:23)
    at EVENTS.map (/Users/user/git/src/main/puppeteer/measure.js:125:24)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

```js
async function collectCoverage() {
  const browser = await puppeteer.launch({ headless: true });
  
  const collectPromises = EVENTS.map(async event => {
    const page = await browser.newPage();
    const har = new PuppeteerHar(page);
    await page.emulate(iPhone);
    await har.start({ path: "results.har" }); // Har file
    await page.tracing.start({ screenshots: true, path: "trace.json" }); <----------- Error

    page.on("response", async response => {
    });

    await Promise.all([
      page.coverage.startJSCoverage(),
      page.coverage.startCSSCoverage()
    ]);

    await page.goto(URL, { waitUntil: event });
    
    await har.stop();
    await page.tracing.stop();

    const [jsCoverage, cssCoverage] = await Promise.all([
      page.coverage.stopJSCoverage(),
      page.coverage.stopCSSCoverage()
    ]);

    addUsage(cssCoverage, "css", event);
    addUsage(jsCoverage, "js", event);

    await page.close();
  });

  await Promise.all(collectPromises);

  return browser.close();
}
```

**Comment by aslushnikov** [comment]
@kimsangsoo tracing could be started only once per browser. Our API is currently misleading; we'll need to make the API much more self-explanatory in 2.0 release.

So in your case, please make sure to call `page.tracing.start` only once per the lifetime of browser.

**Comment by Mifrill** [comment]
Hi @aslushnikov, could you please provide more details to help understand the reasons for it:
> tracing could be started only once per browser
