### ISSUE TITLE
Error: spawn EPERM .. lib\Launcher.js:122:40 on Windows

### ISSUE THREAD

**Issue by dsheiko** [puppeteer/puppeteer#3645]
Window 10 v1803, build 17134.407
puppeteer 1.11.0
node v10.13.0 (the same with v 11.4.)
both as Admin and regular user

I'm running 
```js
'use strict';
const puppeteer = require('puppeteer');

puppeteer.launch().then(async browser => {
  const page = await browser.newPage();
  await page.goto('https://www.google.com');  
  await browser.close();
}).catch( err => console.log( err ) );
```
and getting 
```
{ Error: spawn EPERM                                                                                           
    at ChildProcess.spawn (internal/child_process.js:358:11)                                                   
    at Object.spawn (child_process.js:533:9)                                                                   
    at Launcher.launch (D:\UPLOAD\TEST_P\node_modules\puppeteer\lib\Launcher.js:122:40) errno: 'EPERM', code: '
EPERM', syscall: 'spawn' }                                                                                     
```
Setting `DEBUG="puppeteer:*"` changes nothing in the output here.
This issue is probably related to the closed on https://github.com/GoogleChrome/puppeteer/issues/298

**Comment by dsheiko** [comment]
Sorry, I got it. Our corporate antivirus Sophos since recently automatically puts downloaded by NPM Chromium in quarantine. Curious, I've been happily using Puppeteer on Windows for a long time and didn't have problems until now. I do not know where the rules for Sophos quarantine are managed, built-in or our IT decided to update them. Pity we are not allowed to remove or configure Sophos ourselves, so requesting IT
