### ISSUE TITLE
Different behavior desktop vs puppeteer (ERR_EMPTY_RESPONSE)

### ISSUE THREAD

**Issue by dinigo** [puppeteer/puppeteer#3656]
### Steps to reproduce

* Puppeteer version: 1.10.0
* Platform / OS version: macOS High Sierra 10.13.6
* URLs (if applicable): https://www.vueling.com/es
* Node.js version: 10.13

1. Run the code trying to print the responses
```javascript
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  page.on('response', response => {console.log(response.request().url())});
  page.on('error', error => {console.error(error.message)});
  await page.goto('https://www.vueling.com/es');
  await browser.close();
})();
```

**What is the expected result?**
I expect this script to print ~135 urls in about 5~7". Just like Chrome and Chromium desktop does.

**What happens instead?**
I get the following error:
```
UnhandledPromiseRejectionWarning: Error: net::ERR_EMPTY_RESPONSE
```

https://try-puppeteer.appspot.com/ Gives a different error though. I suppose because they manage the error within a try-catch.
```
Error running your code. TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
```

The whole stack-trace I got on my machine here:
```
(node:3224) UnhandledPromiseRejectionWarning: Error: net::ERR_EMPTY_RESPONSE
 at https://www.vueling.com/es
    at navigate (/Users/dinigo/Workspace/myproject/node_modules/puppeteer/lib/FrameManager.js:103:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (/Users/dinigo/Workspace/myproject/node_modules/puppeteer/lib/helper.js:144:27)
    at Page.goto (/Users/dinigo/Workspace/myproject/node_modules/puppeteer/lib/Page.js:587:49)
    at Page.<anonymous> (/Users/dinigo/Workspace/myproject/node_modules/puppeteer/lib/helper.js:145:23)
    at /Users/dinigo/Workspace/myproject/src/navigate.js:8:14
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:3224) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3224) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by dinigo** [comment]
I'm [cross-posting this to stackoverflow](https://stackoverflow.com/q/22312671/621058), just in case you (maintainers) consider this doesn't belong here

**Comment by aslushnikov** [comment]
@dinigo looks like the website detects headless and refuses to serve content to it. That's usually a defensive measure to avoid scraping.

Avoiding detections falls outside of the scope of the project; I can't help much here.
