### ISSUE TITLE
Puppeteer evaluation doesn't work with defined functions

### ISSUE THREAD

**Issue by ibudisteanu** [puppeteer/puppeteer#3671]
hi. I am using Puppeteer on Linux Ubuntu, I did install chromium and followed the troubleshooting documentation, but I encounter a strange behavior on Linux on the .evaluate function. I believe it can help you guys to fix an issue that other users may encounter it too. 

If I run the evaluate it fails running using specific defined functions
```
await page.evaluate( ()=> return "it rocks!" );
```

I tried also with simple functions as well 

```
await page.evaluate( function () { return "it rocks!" } );
```

Moreover, I also tried the demo presented on the first page.

```
await page.exposeFunction('md5', text =>
    crypto.createHash('md5').update(text).digest('hex')
  );
  await page.evaluate(async () => {
    // use window.md5 to compute hashes
    const myString = 'PUPPETEER';
    const myHash = await window.md5(myString);
    console.log(`md5 of ${myString} is ${myHash}`);
  });
```

always it returns the following error: 

```
Error: The following is not a function: undefined
    at ExecutionContext.evaluateHandle (/home/alex/project/node_modules/puppeteer/lib/ExecutionContext.js:95:13)
    at ExecutionContext.<anonymous> (/home/alex/project/node_modules/puppeteer/lib/helper.js:145:23)
    at ExecutionContext.evaluate (/home/alex/project/node_modules/puppeteer/lib/ExecutionContext.js:58:31)
    at ExecutionContext.<anonymous> (/home/alex/project/node_modules/puppeteer/lib/helper.js:145:23)
    at Frame.evaluate (/home/alex/project/node_modules/puppeteer/lib/FrameManager.js:447:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (/home/alex/project/node_modules/puppeteer/lib/helper.js:144:27)
    at Page.evaluate (/home/alex/project/node_modules/puppeteer/lib/Page.js:777:43)
    at Page.<anonymous> (/home/alex/project/node_modules/puppeteer/lib/helper.js:145:23)
```

The following code works
```
                console.log(await page.evaluate('1 + 2')); // prints "3"
                await page.evaluate( console.log("awesome"));
```

Thanks

For me it is not an issue, because I use http/s requests

**Comment by ibudisteanu** [comment]
never mind, after a fresh install of the package, it started to work

**Comment by cosminpopescu14** [comment]
don't use it for attacking blogs ;)
