### ISSUE TITLE
Puppeteer fails to connect to Chromium on Windows 10

### ISSUE THREAD

**Issue by phistuck** [puppeteer/puppeteer#3681]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.11.0
* Platform / OS version: Windows 10 1709
* URLs (if applicable):
* Node.js version: 10.x.x as well as 11.4.0

**What steps will reproduce the problem?**
```js
const puppeteer = require("puppeteer");
puppeteer.launch();
```

**What is the expected result?**
A headless browser launching in the background and no console error.

**What happens instead?**
chrome.exe is run without any command line switch, opening a non-headless window and eventually the tab also crashes, until it is killed by Puppeteer.
```
(node:27296) UnhandledPromiseRejectionWarning: TimeoutError: Timed out after 30000 ms while trying to connect to Chrome! The only Chrome revision guaranteed to work is r609904
    at Timeout.onTimeout (C:\Projects\foo\node_modules\puppeteer\lib\Launcher.js:353:14)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
(node:27296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:27296) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I added `console.log(chromeArguments)` in Launcher.js just before it `spawn`s the Chromium process -
```js
[ '--disable-background-networking',
  '--disable-background-timer-throttling',
  '--disable-backgrounding-occluded-windows',
  '--disable-breakpad',
  '--disable-client-side-phishing-detection',
  '--disable-default-apps',
  '--disable-dev-shm-usage',
  '--disable-extensions',
  '--disable-features=site-per-process',
  '--disable-hang-monitor',
  '--disable-ipc-flooding-protection',
  '--disable-popup-blocking',
  '--disable-prompt-on-repost',
  '--disable-renderer-backgrounding',
  '--disable-sync',
  '--disable-translate',
  '--metrics-recording-only',
  '--no-first-run',
  '--safebrowsing-disable-auto-update',
  '--enable-automation',
  '--password-store=basic',
  '--use-mock-keychain',
  '--headless',
  '--hide-scrollbars',
  '--mute-audio',
  '--disable-gpu',
  'about:blank',
  '--remote-debugging-port=0',
  '--user-data-dir=C:\\Users\\foobaz\\AppData\\Local\\Temp\\puppeteer_dev_profile-tW27Rg' ]
```

Something makes Node.js ignore the arguments. There is no existing chrome.exe (of Chromium) active, only chrome.exe of Chrome.

**Comment by phistuck** [comment]
Environmental variables -
```
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\foobaz\AppData\Roaming
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=foobaz00
ComSpec=C:\WINDOWS\system32\cmd.exe
HOMEDRIVE=C:
HOMEPATH=\Users\foobaz
HTTPS_PROXY=http://CRAP:8080
LOCALAPPDATA=C:\Users\foobaz\AppData\Local
LOGONSERVER=\\RAADC1
NO_PROXY=UUU1111,UUU1234
NUMBER_OF_PROCESSORS=4
OneDrive=C:\Users\foobaz\OneDrive
OS=Windows_NT
Path=C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files (x86)\UUU Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\nodejs\;C:\Program Files\UUA\;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\foobaz\AppData\Local\Programs\Fiddler;C:\Program Files\Microsoft VS Code\bin;C:\Users\foobaz\AppData\Roaming\npm;C:\Users\foobaz\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\foobaz\AppData\Local\Microsoft\WindowsApps;
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=8e09
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files (x86)\Microsoft Azure Information Protection\Powershell
PUBLIC=C:\Users\Public
UUU_PROJECT_HOME=C:\Program Files (x86)\UUU\UUU\UUUU
SESSIONNAME=Console
SystemDrive=C:
SystemRoot=C:\WINDOWS
TEMP=C:\Users\foobaz\AppData\Local\Temp
TMP=C:\Users\foobaz\AppData\Local\Temp
UUUDATA=C:\WINDOWS\CCM\UATData\FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFF
USERDNSDOMAIN=CORP.UUU.COM
USERDOMAIN=CRAPNET
USERDOMAIN_ROAMINGPROFILE=CRAPNET
USERNAME=foobaz
USERPROFILE=C:\Users\foobaz
UUU_CLIENT_HOME=C:\Program Files (x86)\UUU\UUU
windir=C:\WINDOWS
```

**Comment by jaan1025** [comment]
same problem

**Comment by phistuck** [comment]
I tried -
`puppeteer.launch({executablePath: 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe'});`
Same result.
I tried -
`puppeteer.launch({executablePath: 'C:\\WINDOWS\\system32\\cmd.exe'});`
It actually started `cmd.exe` with the expected arguments, so Chrome and Chromium are "excluding" those command line arguments somehow. Could it be group policy related (though headless does not implement group policy)?
Probably not, because only the following policies are configured -
![image](https://user-images.githubusercontent.com/184400/50081492-46547200-01f7-11e9-8325-1422b9a1785d.png)

**Comment by phistuck** [comment]
I found the culprit. `--disable-extensions` is forbidden in my corporate environment. That was stupid (the extensions it mandates are not security sensitive or protective or enforcing anything).
`puppeteer.launch({ignoreDefaultArgs: ['--disable-extensions']})` fixes it, until the next error...

**Comment by herve-coder** [comment]
Hi everyone,
I'm facing the same issue. The solution provided by Phistuck doesn't work for me.

**Comment by titusfx** [comment]
I have the same issue, and the solution of @phistuck  works. *BUT* I need to use an extension,

my script is:

```
    const browser = await puppeteer.launch({
        headless: false, // extension are allowed only in head-full mode
        args: [
            `--disable-extensions-except=${extensionPath}`, // Full path only
            `--load-extension=${extensionPath}`,
            // '--disable-extensions',
            '--no-sandbox',
            '--disable-setuid-sandbox',
            "--disable-gpu",
            "--disable-dev-shm-usage",
        ],
        // timeout: 0
    });
```

In order to puppeteer load an extension (from my experience), it needs the full path, in my case the new full path was on the container. I didn't realize that. So, I changed the path to the local container, and it worked.
So, my problem was the extension but was the location of the extension the problem.

So, please make the path to the extension relative


By the way, this is my Dockerfile, I use xvfb-run because I need to use chrome headless but headless is not compatible with extensions, so xvfb-run is a virtual framebuffer.

```

# First, we need to make sure all dependencies are there. If you are using docker, then the important dependencies are already present on most node images. 
FROM node:16.1.0
# FROM node:8

# To run Headful mode, you will need to have a display, which is not present in a server. 
# To avoid this, we will use Xvfb, and create a fake display, so the chrome will think there is a display and run properly. 
# So we just need to install Xvfb and Puppeteer related dependencies.
RUN apt-get update && apt-get install -yq gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget x11vnc x11-xkb-utils xfonts-100dpi xfonts-75dpi xfonts-scalable xfonts-cyrillic x11-apps xvfb

RUN whereis chromium
# I am going to ignore dumb-init or such for now since it will add complexities to understand what is actually needed here. 

# Assuming we are working on /app folder, cd into /app
WORKDIR /app

# Copy package.json into app folder
COPY package.json /app

# Install dependencies
RUN npm install 

COPY . /app

# Start server on port 3000
EXPOSE 3000

# I'll also assume you are going to use root user, 
# and your script has `--no-sandbox` and `--disable-setuid-sandbox` arguments.
# We run a fake display and run our script.
# Start script on Xvfb
# CMD npm run serve
CMD xvfb-run -a --server-args="-screen 0 1024x768x24" npm run serve
```

**Comment by VexA3** [comment]
Don't recall whee I saw it but doing `cd /node_modules/puppeteer` then running `npm install` forces it to download Chromium

![image](https://user-images.githubusercontent.com/47019848/210015130-583f72e6-1090-40db-a045-07c40ed3df5a.png)
