### ISSUE TITLE
Error: Protocol error (Runtime.callFunctionOn): Target closed.

### ISSUE THREAD

**Issue by gdeivasigamani** [puppeteer/puppeteer#3683]
**Environment:**
* Puppeteer version: 1.11.0
* Platform / OS version: Mac OS High Sierra
* Node.js version: 11.3.0

**What steps will reproduce the problem?**
I followed a youtube tutorial to generate PDF tables using puppeteer.
I have a simple js file with a template from handlebars and I used puppeteer to create a invoice pdf
I am able to stress test it for a data of around 100000 but I when I try 200000 I get

`Error: Protocol error (Runtime.callFunctionOn): Target closed.
`
With the below code, run `node App.js`
JS Code: App.js

```
const puppeteer = require('puppeteer');
const fs = require('fs-extra');
const hbs = require('handlebars');
const path = require('path');
const data = require('./stressData2.json');

const compile = async function(templateName, data){
    const filePath = await path.join(process.cwd(), 'templates', `${templateName}.hbs`);
    const html = await fs.readFile(filePath, 'utf-8');
    return await hbs.compile(html)(data);
};

(async function(){
    try{
        const browser = await puppeteer.launch({
            args: ['--shm-size=1gb']
          });
        const page = await browser.newPage();
        const content = await compile('statementStressTemplate', data);

        await page.setContent(content);
       // let bodyHTML = await page.evaluate(() => document.body.innerHTML);
        //console.log(bodyHTML);
        await page.pdf({
            path: 'pdfs/mypdf.pdf',
            format: 'A4',
            printBackground: true
        });

        console.log('done');

        await browser.close();
        await process.exit();
    } catch(e){
        console.log('Our Error', e);
    }
})();
```
statementStressTemplate.hbs
```
<html>
    <body>
        <h1>Statement</h1>
         <div>
        <table>
            <tbody>
            <tr>
                <th>Name</th>
                <th>Age</th>
                <th>Sex</th>
                <th>Salary</th>
                <th>DOB</th>
                <th>Address</th>
                <th>City</th>
                <th>State</th>
                <th>Country</th>
                <th>Zipcode</th>

                <th>Invoice</th>
                <th>Balance</th>
                <th>Purchase Date</th>
                <th>Item</th>
                <th>Description</th>
                <th>Price</th>
                <th>Validity</th>
                <th>Owner</th>
                <th>User</th>
                <th>Renew</th>
            </tr>
            {{#each statements as |statement|}}
            <tr>
                <td>{{statement.name}}</td>
                <td>{{statement.age}}</td>
                <td>{{statement.sex}}</td>
                <td>{{statement.salary}}</td>
                <td>{{statement.dob}}</td>
                <td>{{statement.address}}</td>
                <td>{{statement.city}}</td>
                <td>{{statement.state}}</td>
                <td>{{statement.country}}</td>
                <td>{{statement.zipcode}}</td>
                <td>{{statement.invoice}}</td>
                <td>{{statement.balance}}</td>
                <td>{{statement.purchaseDate}}</td>
                <td>{{statement.item}}</td>
                <td>{{statement.description}}</td>
                <td>{{statement.price}}</td>
                <td>{{statement.validity}}</td>
                <td>{{statement.owner}}</td>
                <td>{{statement.user}}</td>
                <td>{{statement.renew}}</td>    
            </tr>
            {{/each}}
            </tbody>
        </table>
       </div>
    </body>
</html>
```

FYI, if people want to work on my code I have attach a simple JSON struct with one item, can do a loop to make this n-numbers
stressData2.json
`{"statements":[{"name":"Cater","age":30,"sex":"Male","salary":5000,"dob":"1989-09-05","address":"address","city":"Dallas","state":"Texas","country":"USA","zipcode":75201,"invoice":"3435455","balance":90000,"purchaseDate":"2015-05-09","item":67789,"description":"customers","price":5000,"validity":"2020-05-17","owner":"xyz","user":"ghh","renew":"2025-07-15"}]}`

**What is the expected result?**
Expected result is a nicely formatted table inside pdf.

**What happens instead?**

```
{ Error: Protocol error (Runtime.callFunctionOn): Target closed.
    at Promise (/Users/gdeivasigamani/node_modules/puppeteer/lib/Connection.js:186:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/Users/gdeivasigamani/node_modules/puppeteer/lib/Connection.js:185:12)
    at ExecutionContext.evaluateHandle (/Users/gdeivasigamani/node_modules/puppeteer/lib/ExecutionContext.js:115:75)
    at ExecutionContext.<anonymous> (/Users/gdeivasigamani/node_modules/puppeteer/lib/helper.js:145:23)
    at ExecutionContext.evaluate (/Users/gdeivasigamani/node_modules/puppeteer/lib/ExecutionContext.js:58:31)
    at ExecutionContext.<anonymous> (/Users/gdeivasigamani/node_modules/puppeteer/lib/helper.js:145:23)
    at Frame.evaluate (/Users/gdeivasigamani/node_modules/puppeteer/lib/FrameManager.js:447:20)
  -- ASYNC --
    at Frame.<anonymous> (/Users/gdeivasigamani/node_modules/puppeteer/lib/helper.js:144:27)
    at Frame.setContent (/Users/gdeivasigamani/node_modules/puppeteer/lib/FrameManager.js:541:16)
    at Frame.<anonymous> (/Users/gdeivasigamani/node_modules/puppeteer/lib/helper.js:145:23)
    at Page.setContent (/Users/gdeivasigamani/node_modules/puppeteer/lib/Page.js:615:42)
    at Page.<anonymous> (/Users/gdeivasigamani/node_modules/puppeteer/lib/helper.js:145:23)
    at /Users/gdeivasigamani/git/NodeJsServer/serverPdfGenerator.js:21:20
  message: 'Protocol error (Runtime.callFunctionOn): Target closed.' 
}

```

I tried the solutions suggested in other related issues raised in this repo https://github.com/GoogleChrome/puppeteer/issues/1175
. But it didnt help me resolve the above

Stackoverflow post for the same: https://stackoverflow.com/questions/53801543/puppeteer-protocol-error-runtime-callfunctionon-target-closed

**Comment by gdeivasigamani** [comment]
It happens on the below line
`await page.setContent(content);
`
 I think the above error is thrown when the content size is large, is there any way to increase the Page or browse memory or anyother trick to overcome this error?

**Comment by thamerla** [comment]
@gdeivasigamani chromium flags maybe?

**Comment by gdeivasigamani** [comment]
@nonyy Do you know what flags i should set and how to send them in puppeteer.
Since I checked the flags and I couldnt get any useful information

**Comment by aslushnikov** [comment]
@gdeivasigamani this has been discussed before: https://groups.google.com/a/chromium.org/forum/#!topic/chromium-dev/qsffxWuaNeQ

I'd try suggested options; if none work, please ask on chromium-dev.

**Comment by maximedupre** [comment]
@aslushnikov Are you sure the link you posted is about the same bug? 

The same problem occurs to me when I try to pass in a large string (length of 126947296) to an exposed function, however the tab does not crash like described in your link, which makes me think they are somewhat unrelated.

**Comment by maximedupre** [comment]
Just in case anyone else has the same problem, you can send your string in chunks to avoid the error.

**Comment by luyizhao** [comment]
Fyi, I think this may be related to https://github.com/GoogleChrome/puppeteer/issues/4543
