### ISSUE TITLE
Feature: Simpler way to handle pages created on clicking a[target="_blank"]; wait for loading and include timeouts

### ISSUE THREAD

**Issue by dheerajbhaskar** [puppeteer/puppeteer#3718]
# Overview
I'm looking for a simpler way to handle clicking on links which open new pages (like target="_blank" anchor tags). 

Here handle means:
- get the new page object
- wait for the new tab to load (with timeout)

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: ^1.11.0
* Platform / OS version:  64-bit, win 10 pro
* URLs (if applicable): none
* Node.js version: v10.15.0

I've looked at related issues:
#386 
#3535 
#978
and more

**What steps will reproduce the problem?**
_I've included the code snippet below_

I'm trying to:
1. Get the object for the new page when clicking on a link opens a new tab. (The links are dynamically generated, capturing href might not be the most elegant way)
2. Wait till the new page loads (with timeout). I'd like it if you can use page.waitForNavigation for consistency
3. close the tab and return the earlier tab to continue further operations

_Please include code that reproduces the issue._
```
// as referenced here on #386 : https://github.com/GoogleChrome/puppeteer/issues/386#issuecomment-425109457
    const getNewPageWhenLoaded =  async () => {
        return new Promise(x =>
            global.browser.on('targetcreated', async target => {
                if (target.type() === 'page') {
                    const newPage = await target.page();
                    const newPagePromise = new Promise(y =>
                        newPage.once('domcontentloaded', () => y(newPage))
                    );
                    const isPageLoaded = await newPage.evaluate(
                        () => document.readyState
                    );
                    return isPageLoaded.match('complete|interactive')
                        ? x(newPage)
                        : x(newPagePromise);
                }
            })
        );
    };


const newPagePromise = getNewPageWhenLoaded();
await page.click('my-link'); // or just do await page.evaluate(() => window.open('https://www.example.com/'));
const newPage = await newPagePromise;
```

**What is the expected result?**
An easier and consistent way to handle new tabs

**What happens instead?**
The developer has to write what looks like plumbing (internal/ low level) commands.
Usage of waitForTarget might simplify this, but I've not been able to get the predicate to return the right types. Here's my non-functional code

```
private async getNewPageWhenLoaded() {
        const newTarget = await this._browser.waitForTarget(async (target) => {
            const newPage = await target.page();
            await newPage.waitForNavigation(this._optionsNavigation);
            // const newPagePromise = new Promise(() => newPage.once('load', () => x(newPage)));
            return await newPage.evaluate("true");
        });
        return await newTarget.page();
    }

// elsewhere in the code
            const newPagePromise = this.getNewPageWhenLoaded();
            await resultItem.element.click();
            const newPage = <Page>await newPagePromise;

//I get the following error
DevTools listening on ws://127.0.0.1:31984/devtools/browser/bf86648d-d52d-42d8-a392-629bf96211d4
(node:5564) UnhandledPromiseRejectionWarning: Error: Navigation failed because browser has disconnected!
    at CDPSession.LifecycleWatcher._eventListeners.helper.addEventListener (<path-to-my-project>\node_modules\puppeteer\lib\FrameManager.js:1181:107)
    at CDPSession.emit (events.js:182:13)
    at CDPSession._onClosed (<path-to-my-project>\node_modules\puppeteer\lib\Connection.js:231:10)
    at Connection._onMessage (<path-to-my-project>\node_modules\puppeteer\lib\Connection.js:103:19)
    at WebSocketTransport._ws.addEventListener.event (<path-to-my-project>\node_modules\puppeteer\lib\WebSocketTransport.js:41:24)
    at WebSocket.onMessage (<path-to-my-project>\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (events.js:182:13)
    at Receiver.receiverOnMessage (<path-to-my-project>\node_modules\ws\lib\websocket.js:741:20)
    at Receiver.emit (events.js:182:13)
    at Receiver.dataMessage (<path-to-my-project>\node_modules\ws\lib\receiver.js:417:14)
  -- ASYNC --
    at Frame.<anonymous> (<path-to-my-project>\node_modules\puppeteer\lib\helper.js:144:27)
    at Page.waitForNavigation (<path-to-my-project>\node_modules\puppeteer\lib\Page.js:644:49)
    at Page.<anonymous> (<path-to-my-project>\node_modules\puppeteer\lib\helper.js:145:23)
    at newTarget._browser.waitForTarget (<path-to-my-project>\pageObjects\MyPage.js:104:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:5564) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5564) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:5564) UnhandledPromiseRejectionWarning: TimeoutError: Navigation Timeout Exceeded: 300000ms exceeded
    at Promise.then (<path-to-my-project>\node_modules\puppeteer\lib\FrameManager.js:1276:21)
  -- ASYNC --
    at Frame.<anonymous> (<path-to-my-project>\node_modules\puppeteer\lib\helper.js:144:27)
    at Page.waitForNavigation (<path-to-my-project>\node_modules\puppeteer\lib\Page.js:644:49)
    at Page.<anonymous> (<path-to-my-project>\node_modules\puppeteer\lib\helper.js:145:23)
    at newTarget._browser.waitForTarget (<path-to-my-project>\pageObjects\MyPage.js:104:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:5564) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**Comment by dheerajbhaskar** [comment]
I'm not sure if things like page.waitforTarget make this simpler, so I've created a stackoverflow question as well: https://stackoverflow.com/questions/54002607/puppeteer-simpler-way-to-handle-pages-created-on-clicking-atarget-blank-w

Let me know if you need anything else from me here

**Comment by dheerajbhaskar** [comment]
Is this the most simple way to handle this? (credits: https://github.com/GoogleChrome/puppeteer/issues/2912#issuecomment-446395521)

```
const link = await page.$('selector')
await link.click()    // at this time, a new page was successful opened in a new tab in chromium
//waits until the target is available [see browser.targests]
const newPage = await browser.waitForTarget(target => target.ur() === link.textContent());

// get all pages
pages = await browser.pages()
for (const page of pages) {
    console.log(page.url())   // new page now appear!
}
```

Edit: This doesn't wait for page content to be loaded, so doesn't work as a valid solution

**Comment by dheerajbhaskar** [comment]
This is the simplest I've gotten it to be

```
const pageTarget = this._page.target(); //save this to know that this was the opener
await resultItem.element.click(); //click on a link
const newTarget = await this._browser.waitForTarget(target => target.opener() === pageTarget); //check that you opened this page, rather than just checking the url
const newPage = await newTarget.page(); //get the page object
// await newPage.once("load",()=>{}); //this doesn't work; wait till page is loaded
await newPage.waitForSelector("body"); //wait for page to be loaded
```

**Comment by aslushnikov** [comment]
@dheerajbhaskar so there are two jobs in one:

> get the new page object

Tip-of-tree puppeteer has a new [`'popup'`](https://pptr.dev/#?product=Puppeteer&version=master&show=api-event-popup) event specifically to address this. 

> wait for the new tab to load (with timeout)

For this we're experimenting with a new `page.ensureNavigation` API that will make sure the current navigation reached the desired state. It's not landed yet, but there are promising results.

**Comment by jeroenvisser101** [comment]
> For this we're experimenting with a new `page.ensureNavigation` API that will make sure the current navigation reached the desired state. It's not landed yet, but there are promising results.

@aslushnikov is this tracked somewhere? I couldn't find this on the chrome bug tracker

**Comment by ignacioainol** [comment]
run the click function first of all and within the promise remove the global keyword like this

```
const browser = await puppeteer.launch();
await page.click('my-link'); 

const getNewPageWhenLoaded =  async () => {
        return new Promise(x =>
            browser.on('targetcreated', async target => {
                if (target.type() === 'page') {
                    const newPage = await target.page();
                    const newPagePromise = new Promise(y =>
                        newPage.once('domcontentloaded', () => y(newPage))
                    );
                    const isPageLoaded = await newPage.evaluate(
                        () => document.readyState
                    );
                    return isPageLoaded.match('complete|interactive')
                        ? x(newPage)
                        : x(newPagePromise);
                }
            })
        );
    };


const newPagePromise = getNewPageWhenLoaded();
const newPage = await newPagePromise;
```

**Comment by sadortun** [comment]
@ignacioainol 

Example working almost perfectly, except i get hundreds of event handlers attatched 😆 

Should ` browser.on(...)`   be ` browser.once(...)`  ?

**Comment by adailsonm** [comment]
@sadortun 
I'm having the same problem, independent of using once or on
```Error: Request is already handled!```

**Comment by fernandojmartin** [comment]
> run the click function first of all and within the promise remove the global keyword like this
> 
> ```
> const browser = await puppeteer.launch();
> await page.click('my-link'); 
> 
> const getNewPageWhenLoaded =  async () => {
>         return new Promise(x =>
>             browser.on('targetcreated', async target => {
>                 if (target.type() === 'page') {
>                     const newPage = await target.page();
>                     const newPagePromise = new Promise(y =>
>                         newPage.once('domcontentloaded', () => y(newPage))
>                     );
>                     const isPageLoaded = await newPage.evaluate(
>                         () => document.readyState
>                     );
>                     return isPageLoaded.match('complete|interactive')
>                         ? x(newPage)
>                         : x(newPagePromise);
>                 }
>             })
>         );
>     };
> 
> 
> const newPagePromise = getNewPageWhenLoaded();
> const newPage = await newPagePromise;
> ```

For me, it worked like a charm.
Copy and paste, and from there on, everything is done against `newPage` instead of `page`.

```javascript
...
await page.click('div[title="rcel"]');

const newPagePromise = getNewPageWhenLoaded();
const newPage = await newPagePromise;

await newPage.click('input[value="blah"]');
await newPage.waitForSelector('a#btn_gen_cmp', {visible: true});
...
```

Thank you @ignacioainol !

**Comment by maly-logi** [comment]
I would rather prefer this : 

    const [popup] = await Promise.all([
      new Promise((resolve) => page.once('popup', async p => {
        await p.waitForNavigation({ waitUntil: 'networkidle0' });
        resolve(p);
      })),
      page.click(confirmEmailButton),
    ]);

 After that you can run this code to make use of the newly opened page: 
` await popup.screenshot({ fullPage: true, path: 'screenshot11.png' });`

**Comment by minipunch** [comment]
> "This is the simplest I've gotten it to be"

So this worked for me, but now I have to figure out how to ignore HTTPS errors for this new popup page (SAML login)...

**Comment by PredokMiF** [comment]
[The solution](https://github.com/puppeteer/puppeteer/issues/3718#issuecomment-606385531) works but it is bad. The main problem of this code is that it should not be used more than once because there is no event unsubscribing.

 I improved it a little:
```JS
async function getNewBrowserTab(browser) {
    let resultPromise

    async function onTargetcreatedHandler(target) {
        if (target.type() === 'page') {
            const newPage = await target.page()
            const newPagePromise = new Promise(y =>
                newPage.once('domcontentloaded', () => y(newPage))
            )

            const isPageLoaded = await newPage.evaluate(
                () => document.readyState
            )

            browser.off('targetcreated', onTargetcreatedHandler) // unsubscribing

            return isPageLoaded.match('complete|interactive')
                ? resultPromise(newPage)
                : resultPromise(newPagePromise)
        }
    }

    return new Promise(resolve => {
        resultPromise = resolve
        browser.on('targetcreated', onTargetcreatedHandler)
    })
}

// Using
const browser = await puppeteer.launch({ headless: false })
const page = await browser.newPage()

await page.goto('https://www.google.com/')

// Click on link with middle button to open in new browser tab
await page.click('a[href]', { button : 'middle' })

// Wait for new tab and return a page instance
const newPage = await getNewBrowserTab(browser)

// Switch to new tab
await newPage.bringToFront()

// Wait a bit to see the page
await new Promise(resolve => setTimeout(resolve, 1000))

await newPage.close()
await page.close()
await browser.close()
```

**Comment by jamesrusso** [comment]
```typescript
const getNewBrowserTab = (browser: Browser) => {
  let resultPromise: (page: Page | Promise<Page>) => void;

  async function onTargetcreatedHandler(target: Target) {
    if (target.type() === 'page') {
      const newPage = await target.page();

      if (newPage === null) throw Error('newPage was null?');

      const newPagePromise = new Promise<Page>((resolve) =>
        newPage.once('domcontentloaded', () => {
          resolve(newPage);
        })
      );

      const isPageLoaded = await newPage.evaluate(() => document.readyState);

      browser.off('targetcreated', onTargetcreatedHandler); // unsubscribing

      return isPageLoaded.match('complete|interactive') ? resultPromise(newPage) : resultPromise(newPagePromise);
    }
  }

  return new Promise<Page | Promise<Page>>((resolve) => {
    resultPromise = resolve;
    browser.on('targetcreated', onTargetcreatedHandler);
  });
};
``` 

Here is a typescript adaptation from @PredokMiF's version in case anyone else needs it.
