### ISSUE TITLE
`Evaluation failed: ReferenceError: sender is not defined` when using evaluate

### ISSUE THREAD

**Issue by ZendyLim** [puppeteer/puppeteer#3731]
**Tell us about your environment:**
I am using Puppeteer in my vue-electron project. Because of problem launching packaged chromium from bundled from Puppeteer, I used `chrome-launcher` and connect the Chrome instance to Puppeteer with `puppeteer-core`

* Puppeteer version: 1.11.0
* Platform / OS version: Win10 Pro
* URLs (if applicable):
* Node.js version: 10.14.2

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```
await mainPage.goto('https://www.smartpv.jp/', {timeout: 0, waitUntil: 'networkidle0'});
await mainPage.type('input[name=userCode]', '1234');
await mainPage.type('input[name=userPwd]', 'password');
await Promise.all([
  mainPage.waitForNavigation({timeout: 0, waitUntil: 'networkidle2'}),
    await mainPage.click('button[name=loginsub]')
  ]);
await mainPage.goto('https://www.smartpv.jp/perReportDownloads.html', {timeout: 0, waitUntil: 'networkidle0'});
await mainPage.click('div#reportType > div > a.dropdown-toggle');
await mainPage.click('div#reportType > div > ul > li > a[selvalue=\'2\']');

const options = await mainPage.$$('div#psDrop4 > div > ul > li > a[selvalue]');

const trigger = await mainPage.$('div#psDrop4 > div > a.dropdown-toggle');
const countButton = await mainPage.$('button#Calculation');
const clearButton = await mainPage.$('button#clCalculation');
const valueElement = await mainPage.$('#sumPac');

await mainPage.evaluate((valueElement) => {
        valueElement.innerHTML = '';
      }, valueElement);
```

I ran this code on button click from Vue.

**What is the expected result?**
The innerHTML should be empty.

**What happens instead?**
I got an error when trying to use `mainPage.evaluate()`

```
asyncToGenerator.js?3b8d:8 Uncaught (in promise) Error: Evaluation failed: ReferenceError: sender is not defined
    at __puppeteer_evaluation_script__:2:11
    at __puppeteer_evaluation_script__:2:11
    at ExecutionContext.evaluateHandle (webpack:///./node_modules/puppeteer-core/lib/ExecutionContext.js?:124:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at ExecutionContext.eval (webpack:///./node_modules/puppeteer-core/lib/helper.js?:144:27)
    at ExecutionContext.evaluate (webpack:///./node_modules/puppeteer-core/lib/ExecutionContext.js?:58:31)
    at ExecutionContext.eval (webpack:///./node_modules/puppeteer-core/lib/helper.js?:145:23)
    at Frame.evaluate (webpack:///./node_modules/puppeteer-core/lib/FrameManager.js?:447:20)
  -- ASYNC --
    at Frame.eval (webpack:///./node_modules/puppeteer-core/lib/helper.js?:144:27)
    at Page.evaluate (webpack:///./node_modules/puppeteer-core/lib/Page.js?:777:43)
    at Page.eval (webpack:///./node_modules/puppeteer-core/lib/helper.js?:145:23)
    at callFunction (D:\Projects\Work\Solaris\node_modules\electron\dist\resources\electron.asar\browser\rpc-server.js:251:24)
    at D:\Projects\Work\Solaris\node_modules\electron\dist\resources\electron.asar\browser\rpc-server.js:377:10
    at EventEmitter.ipcMain.on.args (D:\Projects\Work\Solaris\node_modules\electron\dist\resources\electron.asar\browser\rpc-server.js:274:21)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (D:\Projects\Work\Solaris\node_modules\electron\dist\resources\electron.asar\browser\api\web-contents.js:356:21)
    at WebContents.emit (events.js:182:13)
```

**Comment by aslushnikov** [comment]
@ZendyLim I see there are some webpack URLs. Are you transpiling Puppeteer? If this is the case, then check out our [transpilation troubleshooting](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#code-transpilation-issues).

**Comment by rohitsg** [comment]
> @ZendyLim I see there are some webpack URLs. Are you transpiling Puppeteer? If this is the case, then check out our [transpilation troubleshooting](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#code-transpilation-issues).

your given -` transpiler link` is showing 404 message. Modifiying compilerOptions in tsConfig.json solved the issue - https://github.com/puppeteer/puppeteer/issues/1665#issuecomment-429356629
