### ISSUE TITLE
Always getting errors when running my instagram monitor

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#3760]
Unhandled Rejection at: Promise Promise {
  <rejected> Error: Evaluation failed: SyntaxError: Unexpected token I in JSON at position 0
      at JSON.parse (<anonymous>)
      at __puppeteer_evaluation_script__:3:24
      at ExecutionContext.evaluateHandle (C:\Users\Administrator\Desktop\Kunden\numb#0001\Instagram Monitor\node_modules\puppeteer\lib\ExecutionContext.js:124:13)
      at process._tickCallback (internal/process/next_tick.js:68:7)
    -- ASYNC --
      at ExecutionContext.<anonymous> (C:\Users\Administrator\Desktop\Kunden\numb#0001\Instagram Monitor\node_modules\puppeteer\lib\helper.js:144:27)
      at ExecutionContext.evaluate (C:\Users\Administrator\Desktop\Kunden\numb#0001\Instagram Monitor\node_modules\puppeteer\lib\ExecutionContext.js:58:31)
      at ExecutionContext.<anonymous> (C:\Users\Administrator\Desktop\Kunden\numb#0001\Instagram Monitor\node_modules\puppeteer\lib\helper.js:145:23)
      at Frame.evaluate (C:\Users\Administrator\Desktop\Kunden\numb#0001\Instagram Monitor\node_modules\puppeteer\lib\FrameManager.js:447:20)
      at process._tickCallback (internal/process/next_tick.js:68:7)
    -- ASYNC --
      at Frame.<anonymous> (C:\Users\Administrator\Desktop\Kunden\numb#0001\Instagram Monitor\node_modules\puppeteer\lib\helper.js:144:27)
      at Page.evaluate (C:\Users\Administrator\Desktop\Kunden\numb#0001\Instagram Monitor\node_modules\puppeteer\lib\Page.js:777:43)
      at Page.<anonymous> (C:\Users\Administrator\Desktop\Kunden\numb#0001\Instagram Monitor\node_modules\puppeteer\lib\helper.js:145:23)
      at C:\Users\Administrator\Desktop\Kunden\numb#0001\Instagram Monitor\bot.js:39:30
      at process._tickCallback (internal/process/next_tick.js:68:7) } reason: Error: Evaluation failed: SyntaxError: Unexpected token I in JSON at position 0
    at JSON.parse (<anonymous>)
    at __puppeteer_evaluation_script__:3:24
    at ExecutionContext.evaluateHandle (C:\Users\Administrator\Desktop\Kunden\numb#0001\Instagram Monitor\node_modules\puppeteer\lib\ExecutionContext.js:124:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (C:\Users\Administrator\Desktop\Kunden\numb#0001\Instagram Monitor\node_modules\puppeteer\lib\helper.js:144:27)
    at ExecutionContext.evaluate (C:\Users\Administrator\Desktop\Kunden\numb#0001\Instagram Monitor\node_modules\puppeteer\lib\ExecutionContext.js:58:31)
    at ExecutionContext.<anonymous> (C:\Users\Administrator\Desktop\Kunden\numb#0001\Instagram Monitor\node_modules\puppeteer\lib\helper.js:145:23)
    at Frame.evaluate (C:\Users\Administrator\Desktop\Kunden\numb#0001\Instagram Monitor\node_modules\puppeteer\lib\FrameManager.js:447:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (C:\Users\Administrator\Desktop\Kunden\numb#0001\Instagram Monitor\node_modules\puppeteer\lib\helper.js:144:27)
    at Page.evaluate (C:\Users\Administrator\Desktop\Kunden\numb#0001\Instagram Monitor\node_modules\puppeteer\lib\Page.js:777:43)
    at Page.<anonymous> (C:\Users\Administrator\Desktop\Kunden\numb#0001\Instagram Monitor\node_modules\puppeteer\lib\helper.js:145:23)
    at C:\Users\Administrator\Desktop\Kunden\numb#0001\Instagram Monitor\bot.js:39:30
    at process._tickCallback (internal/process/next_tick.js:68:7)

Hopefully someone can help me..

**Comment by aslushnikov** [comment]
@saschawlt123 this is not actionable unless you can share a script with us so that we can repro it.. Feel free to refile with more information we can work with.
