### ISSUE TITLE
Site JavaScript blocking Puppeteer

### ISSUE THREAD

**Issue by tksa** [puppeteer/puppeteer#3795]
**Puppeteer version:** 1.11.0
**Node.js version:** 8.11.3

Using puppeteer on page (http://www.hansgrohe.hr/) throws the following error; 

```
(node:10512)` UnhandledPromiseRejectionWarning: TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (C:\Users\tester1\node_modules\puppeteer\lib\FrameManager.js:1276:21)
    at <anonymous>
  -- ASYNC --
    at Frame.<anonymous> (C:\Users\tester1\node_modules\puppeteer\lib\helper.js:144:27)
    at Page.goto (C:\Users\tester1\node_modules\puppeteer\lib\Page.js:624:49)
    at Page.<anonymous> (C:\Users\tester1\node_modules\puppeteer\lib\helper.js:145:23)
    at C:\Users\tester1\puppet\example.js:8:12
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:10512) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10512) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I expect a screenshot as works on every other site I try but this site has puzzled me, the only way I can get it to work is by disabling JavaScript. I have tried changing user-agent as well to no avail.  

Any suggestions much appreciated. 

**Code as follows;** 

```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();

await page.goto('http://www.hansgrohe.hr/'); 
await page.screenshot({path: 'example.png'});
await browser.close();

})();

**Comment by mboeser** [comment]
I noticed that url is loading the New Relic script within the head. loading it in Chrome throws some warnings in the console: _Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience._

perhaps that script is somehow impacting chromium or puppeteers...

**Comment by tksa** [comment]
In case anyone is interested, I fixed the issue but have not figured out the problem; 

Basically, something inside "measureDesktop.js" caused puppeteer to crap itself; I added intercept for this and works perfectly, I am curious how many other sites use something similar. 

measureDesktop.js (the script blocking puppeteer) 

```
function measureDevice(mobileHref, domain, value, text, repeated) { //( string mobileHref, string domain, int widthValue)
	//mobileHref - URL kommt aus Iolet
	//domain - ganz wichtig: domain muss gesetzt werden, damit das Cookie Ã¼bergreifend gilt!
	var useragent = navigator.userAgent.toLowerCase();
	
	//do not redirect, if user is linked from mobile site
	if( location.search.indexOf('m=1') >= 0 ) {
		document.cookie = 'mobileRedirect=false; domain=' + domain + '; path=/';
		return false;
	}
	
	//redirect if cookie is already set
	if( mobileHref != '' && document.cookie.indexOf('mobileRedirect=true') >= 0 ) {
		location.href = mobileHref;
		return;
	}
	
	//first call
	if( mobileHref != '' && document.cookie.indexOf('mobileRedirect=false') == -1 ) {
		var width = screen.width,
			height = screen.height,
			check;		
		
		/*
		 * Nur auf IE Mobile, da sonst der IE sonst im Desktop Modus auch auf die mobile Version geschickt wird
		 */
		if( useragent.indexOf('iemobile') > -1 ) { //extra values for IE Mobile
			width = document.documentElement.offsetWidth;
			height = document.documentElement.offsetHeight;
		}
		
		//Problem with android internal browser
		if( useragent.indexOf('android') > -1 && useragent.indexOf('mobile safari') > -1 ) {
			width = window.innerWidth;
			height = window.innerHeight;
		}

		if( width > height ) { //take smallest value
			if( height < value ) {
				check = confirm(text);
			}
		} else {
			if( width < value ) {
				check = confirm(text);
			}
		}
		
		if( check ) { //set cookie "true" on change
			document.cookie = 'mobileRedirect=true; domain=' + domain + '; path=/';
			location.href = mobileHref;
		}
		else { //set cookie "false" if user refuses to change
			document.cookie = 'mobileRedirect=false; domain=' + domain + '; path=/';
		}
	}
}

```

Working example; 

```
const puppeteer = require('puppeteer');

puppeteer.launch().then(async browser => {
  const page = await browser.newPage();
  await page.setRequestInterception(true);
  page.on('request', interceptedRequest => {
    if (interceptedRequest.url().endsWith('measureDesktop.js'))
      interceptedRequest.abort();
    else
      interceptedRequest.continue();
  });
await page.goto('http://www.url.com/'); 
await page.screenshot({path: 'example.png'});
  await browser.close();
});
```
