### ISSUE TITLE
Parse Error - HPE_INVALID_CONSTANT - When connecting to browserWSEndpoint.

### ISSUE THREAD

**Issue by GautierT** [puppeteer/puppeteer#3804]
Hi.
When i try to connect to a distant Chrome instance spawn with https://github.com/joelgriffith/browserless It's working for a few request then i have this error :

```
ErrorEvent {
  target:
   WebSocket {
     domain: null,
     _events: { open: [Function], error: [Function] },
     _eventsCount: 2,
     _maxListeners: undefined,
     readyState: 3,
     protocol: '',
     _binaryType: 'nodebuffer',
     _closeFrameReceived: false,
     _closeFrameSent: false,
     _closeMessage: '',
     _closeTimer: null,
     _closeCode: 1006,
     _extensions: {},
     _isServer: false,
     _receiver: null,
     _sender: null,
     _socket: null,
     url: 'ws://URL_OF_THE_BROWSERLESS_INSTANCE:3000',
     _req: null },
  type: 'error',
  message: 'Parse Error',
  error:
   { Error: Parse Error
       at Socket.socketOnData (_http_client.js:441:20)
       at Socket.emit (events.js:182:13)
       at Socket.EventEmitter.emit (domain.js:442:20)
       at addChunk (_stream_readable.js:283:12)
       at readableAddChunk (_stream_readable.js:264:11)
       at Socket.Readable.push (_stream_readable.js:219:10)
       at TCP.onStreamRead (internal/stream_base_commons.js:94:17) bytesParsed: 0, code: 'HPE_INVALID_CONSTANT' } }
```

The browserless instance is behind a NGINX proxy with this config 
```
server {
        listen                  3000 default_server;

        client_max_body_size    250m;
        # redirect on errors
        error_page              500 502 504 /50x.html;

        # handle error redirect
        location = /50x.html {
            proxy_pass http://placeholders.cloud66.com/nginx/50x.html;
        }

        server_name             _;

        location / {
            # Next three lines implement websocket support
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header        Host $http_host;
            proxy_redirect          off;
            proxy_pass              http://browserless;
            break;
        }
    }
```

I'm using this code to connect, load HTML and convert to PDF : 
```
    const browser = await puppeteer.connect({ browserWSEndpoint: process.env.BROWSER_WS_ENDPOINT })

    const page = await browser.newPage()

    await page.goto(`data:text/html,${html}`, { waitUntil: 'networkidle0' })

    const pdf_buffer = await page.pdf(options)

    await page.close()
    await browser.close()
```
The error is triggered when i'm doing `const browser = await puppeteer.connect({ browserWSEndpoint: process.env.BROWSER_WS_ENDPOINT })`

From what i found on internet it seems to be related to HTTP. 

Any idea what's happening ? Thanks a lot.

**Comment by aslushnikov** [comment]
Hey @GautierT, seems like this has something to do with its infrastructure rather then with pptr itself.
Can you please file this over to browserless?

**Comment by GautierT** [comment]
Indeed. Sorry for this.
