### ISSUE TITLE
Reload page error in response.text()

### ISSUE THREAD

**Issue by mnesrine** [puppeteer/puppeteer#3806]
### Steps to reproduce

**Tell us about your environment:**
    - Puppeteer version: "1.4.0"
    - Platform / OS version: Ubuntu 18.04.1 LTS
    - URLs (if applicable): https://twitter.com/nytimes

**What steps will reproduce the problem?**

```
const puppeteer = require('puppeteer');
(async () => {
  const browser = await puppeteer.launch();
  const [page] = await browser.pages();
  const response = await page.goto('https://twitter.com/nytimes');
  await page.reload();
  console.log(await response.text());
  await browser.close();
})();
```
```
$node test.js 
(node:21519) UnhandledPromiseRejectionWarning: Error: Protocol error (Network.getResponseBody): No resource with given identifier found
    at Promise (/home/nesrine/test/node_modules/puppeteer/lib/Connection.js:186:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/home/nesrine/test/node_modules/puppeteer/lib/Connection.js:185:12)
    at _contentPromise._bodyLoadedPromise.then (/home/nesrine/test/node_modules/puppeteer/lib/NetworkManager.js:591:45)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Response.<anonymous> (/home/nesrine/test/node_modules/puppeteer/lib/helper.js:144:27)
    at /home/nesrine/testtest.js:11:30
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:21519) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21519) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.'
```

How can I resolve this issue.
Thanks

**Comment by vsemozhetbyt** [comment]
I am not sure if the first `response` is available for processing after the reload. If you need the text of the first response, you can try to save it before the reload. If you need the text of the reload response, you may need something like this:
```js
const response2 = await page.reload();
console.log(await response2.text());
```

**Comment by mnesrine** [comment]
@vsemozhetbyt Thanks, but that does not work.
I got the same error in another example when :
 1- Load a page
 2- Click a button
3- wait for Naviguation

Any idea about this issue ?

Thanks,

**Comment by vsemozhetbyt** [comment]
Can you provide a small script that reproduces the error?
