### ISSUE TITLE
executionContextId is 0 when using multiples connections

### ISSUE THREAD

**Issue by kblok** [puppeteer/puppeteer#3865]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: Master branch
* Platform / OS version: MacOS 10.14.2
* Node.js version: v8.10

**What steps will reproduce the problem?**

```js
(async() => {
    var options =  { headless : true, };
    var browser = await puppeteer.launch(options);
    var browserWSEndpoint = browser.wsEndpoint();

    var browser2 = await puppeteer.connect({ browserWSEndpoint });
    var page = (await browser2.pages())[0];
    await page.evaluateOnNewDocument(() => {console.log('Loading js helper1');});
    await page.goto("https://www.google.com");
    browser2.disconnect();

    var browser3 = await puppeteer.connect({ browserWSEndpoint });
    var page2 = (await browser3.pages())[0];
    await page2.goto("https://www.google.com");
    await page2.evaluateOnNewDocument(() => {console.log('Loading js helper1');});

    browser3.disconnect();
    browser.close();
})();
```

**What is the expected result?**
It shouldn't fail.

**What happens instead?**
I'm getting a 
````
(node:28860) UnhandledPromiseRejectionWarning: Error: INTERNAL ERROR: missing context with id = 0
warning.js:18
    at assert (/Users/neo/Documents/Coding/Open Source/puppeteer/lib/helper.js:278:11)
    at FrameManager.executionContextById (/Users/neo/Documents/Coding/Open Source/puppeteer/lib/FrameManager.js:308:5)
    at Page._onConsoleAPI (/Users/neo/Documents/Coding/Open Source/puppeteer/lib/Page.js:504:40)
    at CDPSession.Page.client.on.event (/Users/neo/Documents/Coding/Open Source/puppeteer/lib/Page.js:133:57)
    at emitOne (events.js:116:13)
    at CDPSession.emit (events.js:211:7)
    at CDPSession._onMessage (/Users/neo/Documents/Coding/Open Source/puppeteer/lib/Connection.js:216:12)
    at Connection._onMessage (/Users/neo/Documents/Coding/Open Source/puppeteer/lib/Connection.js:99:19)
    at WebSocketTransport._ws.addEventListener.event (/Users/neo/Documents/Coding/Open Source/puppeteer/lib/WebSocketTransport.js:41:24)
    at WebSocket.onMessage (/Users/neo/Documents/Coding/Open Source/puppeteer/node_modules/ws/lib/event-target.js:120:16)
(node:28860) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
warning.js:18
```

This was reported on Puppeteer-Sharp https://github.com/kblok/puppeteer-sharp/issues/856

**Comment by aslushnikov** [comment]
@kblok Weird, I can't reproduce this on OSX or Linux. Maybe there's something else special with your setup? Could it be you have `PUPPETEER_EXECUTABLE_PATH` defined that points to a custom chromium?

**Comment by kblok** [comment]
I'm using the one in `.local-chromium. But it's true, it doesn't happen every time. Let me try to get a more solid test.

**Comment by kblok** [comment]
@aslushnikov  I know it sounds stupid. But, could you try running it a few times?

**Comment by aslushnikov** [comment]
@kblok I have the following: 

```js
const puppeteer = require('.');

(async() => {
    const theBrowser = await puppeteer.launch({headless: true});
    const browserWSEndpoint = theBrowser.wsEndpoint();

    for (let i = 0; i < 100; ++i) {
      console.log('Iteration #' + i);
      const  browser = await puppeteer.connect({ browserWSEndpoint });
      const page = (await browser.pages())[0];
      await page.evaluateOnNewDocument(() => {console.log('Loading js helper1');});
      await page.goto("https://www.google.com");
      browser.disconnect();
    }
    theBrowser.close();
})();
```

works flawlessly for me. Can you please confirm this script fails for you?

**Comment by kblok** [comment]
@aslushnikov could you try that script with `https://www.facebook.com`?
```
Darios-MBP:puppeteer neo$ node test/playground.js
Iteration #0
Iteration #1
(node:34022) UnhandledPromiseRejectionWarning: Error: INTERNAL ERROR: missing context with id = 0
    at assert (/Users/neo/Documents/Coding/Open Source/puppeteer/lib/helper.js:229:11)
    at FrameManager.executionContextById (/Users/neo/Documents/Coding/Open Source/puppeteer/lib/FrameManager.js:333:5)
    at Page._onConsoleAPI (/Users/neo/Documents/Coding/Open Source/puppeteer/lib/Page.js:520:40)
    at CDPSession.Page.client.on.event (/Users/neo/Documents/Coding/Open Source/puppeteer/lib/Page.js:135:57)
    at emitOne (events.js:116:13)
    at CDPSession.emit (events.js:211:7)
    at CDPSession._onMessage (/Users/neo/Documents/Coding/Open Source/puppeteer/lib/Connection.js:200:12)
    at Connection._onMessage (/Users/neo/Documents/Coding/Open Source/puppeteer/lib/Connection.js:112:17)
    at WebSocketTransport._ws.addEventListener.event (/Users/neo/Documents/Coding/Open Source/puppeteer/lib/WebSocketTransport.js:41:24)
    at WebSocket.onMessage (/Users/neo/Documents/Coding/Open Source/puppeteer/node_modules/ws/lib/event-target.js:120:16)
(node:34022) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handledwith .catch(). (rejection id: 1)
(node:34022) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Iteration #2
(node:34022) UnhandledPromiseRejectionWarning: Error: INTERNAL ERROR: missing context with id = 0
    at assert (/Users/neo/Documents/Coding/Open Source/puppeteer/lib/helper.js:229:11)
    at FrameManager.executionContextById (/Users/neo/Documents/Coding/Open Source/puppeteer/lib/FrameManager.js:333:5)
    at Page._onConsoleAPI (/Users/neo/Documents/Coding/Open Source/puppeteer/lib/Page.js:520:40)
    at CDPSession.Page.client.on.event (/Users/neo/Documents/Coding/Open Source/puppeteer/lib/Page.js:135:57)
    at emitOne (events.js:116:13)
    at CDPSession.emit (events.js:211:7)
    at CDPSession._onMessage (/Users/neo/Documents/Coding/Open Source/puppeteer/lib/Connection.js:200:12)
    at Connection._onMessage (/Users/neo/Documents/Coding/Open Source/puppeteer/lib/Connection.js:112:17)
    at WebSocketTransport._ws.addEventListener.event (/Users/neo/Documents/Coding/Open Source/puppeteer/lib/WebSocketTransport.js:41:24)
    at WebSocket.onMessage (/Users/neo/Documents/Coding/Open Source/puppeteer/node_modules/ws/lib/event-target.js:120:16)
(node:34022) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handledwith .catch(). (rejection id: 2)
Iteration #3
(node:34022) UnhandledPromiseRejectionWarning: Error: INTERNAL ERROR: missing context with id = 0
    at assert (/Users/neo/Documents/Coding/Open Source/puppeteer/lib/helper.js:229:11)
    at FrameManager.executionContextById (/Users/neo/Documents/Coding/Open Source/puppeteer/lib/FrameManager.js:333:5)
    at Page._onConsoleAPI (/Users/neo/Documents/Coding/Open Source/puppeteer/lib/Page.js:520:40)
    at CDPSession.Page.client.on.event (/Users/neo/Documents/Coding/Open Source/puppeteer/lib/Page.js:135:57)
    at emitOne (events.js:116:13)
    at CDPSession.emit (events.js:211:7)
    at CDPSession._onMessage (/Users/neo/Documents/Coding/Open Source/puppeteer/lib/Connection.js:200:12)
    at Connection._onMessage (/Users/neo/Documents/Coding/Open Source/puppeteer/lib/Connection.js:112:17)
    at WebSocketTransport._ws.addEventListener.event (/Users/neo/Documents/Coding/Open Source/puppeteer/lib/WebSocketTransport.js:41:24)
    at WebSocket.onMessage (/Users/neo/Documents/Coding/Open Source/puppeteer/node_modules/ws/lib/event-target.js:120:16)
(node:34022) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handledwith .catch(). (rejection id: 3)
Iteration #4
```

**Comment by aslushnikov** [comment]
@kblok yep manager to reproduce it!
