### ISSUE TITLE
Navigation failed because browser has disconnected error on AWS Lambda

### ISSUE THREAD

**Issue by AndreaAdvanon** [puppeteer/puppeteer#3927]
I'm using `puppeteer-core` on AWS Lambda with chromium builds taken [here](https://github.com/adieuadieu/serverless-chrome/releases/).

I create a new browser instance per lambda invocation, like this:
```javascript
    const browser = await puppeteer.launch({
        args: [
            '--disable-gpu',
            '--disable-dev-shm-usage',
            '--disable-setuid-sandbox',
            '--no-first-run',
            '--no-sandbox',
            '--no-zygote',
            '--single-process',
        ],
        executablePath: './bin/headless-chromium',
        userDataDir: '/tmp/puppeteer_data'
    });
```

Everything works fine except when I have many, many invocations of this lambda. It's hard to tell how many but I'd say ~ 500 invocations near the same time.

```
error: Error: Navigation failed because browser has disconnected!
    at CDPSession.LifecycleWatcher._eventListeners.helper.addEventListener (/var/task/node_modules/puppeteer-core/lib/FrameManager.js:1181:107)
    at emitNone (events.js:106:13)
    at CDPSession.emit (events.js:208:7)
    at CDPSession._onClosed (/var/task/node_modules/puppeteer-core/lib/Connection.js:231:10)
    at Connection._onClose (/var/task/node_modules/puppeteer-core/lib/Connection.js:121:15)
    at WebSocketTransport._ws.addEventListener.event (/var/task/node_modules/puppeteer-core/lib/WebSocketTransport.js:45:22)
    at WebSocket.onClose (/var/task/node_modules/puppeteer-core/node_modules/ws/lib/event-target.js:124:16)
    at emitTwo (events.js:126:13)
    at WebSocket.emit (events.js:214:7)
    at WebSocket.emitClose (/var/task/node_modules/puppeteer-core/node_modules/ws/lib/websocket.js:180:10)
    -- ASYNC --
    at Frame.<anonymous> (/var/task/node_modules/puppeteer-core/lib/helper.js:144:27)
    at Page.goto (/var/task/node_modules/puppeteer-core/lib/Page.js:624:49)
    at Page.<anonymous> (/var/task/node_modules/puppeteer-core/lib/helper.js:145:23)
    at getHTML (/var/task/src/details/details.js:100:16)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```
This error keeps going on for each event that triggers the lambda, until the lambda container is gone.

* Puppeteer version: 1.11.0
* Platform / OS version: AWS Lambda
* URLs (if applicable):
* Node.js version: 8.10

**Comment by AndreaAdvanon** [comment]
Not sure if I should, but I tried to `try {} catch {}` this error to always close the browser, and when I try to close it I get:
```
error: Error: WebSocket is not open: readyState 3 (CLOSED)
    at WebSocket.send (/var/task/node_modules/puppeteer-core/node_modules/ws/lib/websocket.js:322:19)
    at WebSocketTransport.send (/var/task/node_modules/puppeteer-core/lib/WebSocketTransport.js:57:14)
    at Connection.send (/var/task/node_modules/puppeteer-core/lib/Connection.js:71:21)
    at gracefullyCloseChrome (/var/task/node_modules/puppeteer-core/lib/Launcher.js:209:20)
    at Browser.close (/var/task/node_modules/puppeteer-core/lib/Browser.js:255:31)
    at Browser.<anonymous> (/var/task/node_modules/puppeteer-core/lib/helper.js:145:23)
    at getHTML (/var/task/src/details/details.js:108:23)
    at <anonymous>
```

**Comment by PCS-Ismail** [comment]
I do have the same issue, we are using a node.js app that uses puppeteer to generate pdfs. 
This happens mostly on the standard environment, on app engine.
With a small stressing test, it usually crashes with this error similar to yours but happens on the goto function:

```
Error: Navigation failed because browser has disconnected! 
at CDPSession.LifecycleWatcher._eventListeners.helper.addEventListener (/srv/node_modules/puppeteer/lib/FrameManager.js:1181:107) 
at emitNone (events.js:106:13) 
at CDPSession.emit (events.js:208:7) 
at CDPSession._onClosed (/srv/node_modules/puppeteer/lib/Connection.js:231:10) 
at Connection._onClose (/srv/node_modules/puppeteer/lib/Connection.js:121:15) 
at WebSocketTransport._ws.addEventListener.event (/srv/node_modules/puppeteer/lib/WebSocketTransport.js:45:22) 
at WebSocket.onClose (/srv/node_modules/ws/lib/event-target.js:124:16) 
at emitTwo (events.js:126:13) 
at WebSocket.emit (events.js:214:7) 
at WebSocket.emitClose (/srv/node_modules/ws/lib/websocket.js:180:10) 
at Socket.socketOnClose (/srv/node_modules/ws/lib/websocket.js:802:15) 
at emitOne (events.js:116:13) 
at Socket.emit (events.js:211:7) 
at TCP._handle.close [as _onclose] (net.js:561:12)
-- ASYNC -- 
at Frame.<anonymous> (/srv/node_modules/puppeteer/lib/helper.js:144:27) 
at Page.goto (/srv/node_modules/puppeteer/lib/Page.js:624:49) 
at Page.<anonymous> (/srv/node_modules/puppeteer/lib/helper.js:145:23) 
at generateReport (/srv/reportapp.js:653:26) 
at <anonymous> 
at process._tickCallback (internal/process/next_tick.js:189:7) 
```

**Comment by AndreaAdvanon** [comment]
I find that clearing the `/tmp` directory before and after launching chrome the number of invocations goes up to ~ 2000 before it stops working again. I think chrome leaves too much files behind that fill the `/tmp` directory of a lambda container.

**Comment by azavisha-snap** [comment]
Do you guys know if there is a way to force termination of the broken lambda execution context so it doesn't get reused anymore? I don't know if this is possible, but it would help a bit.

**Comment by govindrai** [comment]
I am having this same issue:
```js
{
    "errorMessage": "Navigation failed because browser has disconnected!",
    "errorType": "Error",
    "stackTrace": [
        "CDPSession.LifecycleWatcher._eventListeners.helper.addEventListener (/var/task/node_modules/puppeteer/lib/LifecycleWatcher.js:47:107)",
        "emitNone (events.js:106:13)",
        "CDPSession.emit (events.js:208:7)",
        "CDPSession._onClosed (/var/task/node_modules/puppeteer/lib/Connection.js:215:10)",
        "Connection._onClose (/var/task/node_modules/puppeteer/lib/Connection.js:138:15)",
        "WebSocketTransport._ws.addEventListener.event (/var/task/node_modules/puppeteer/lib/WebSocketTransport.js:45:22)",
        "WebSocket.onClose (/var/task/node_modules/ws/lib/event-target.js:124:16)",
        "emitTwo (events.js:126:13)",
        "WebSocket.emit (events.js:214:7)",
        "WebSocket.emitClose (/var/task/node_modules/ws/lib/websocket.js:180:10)",
        "  -- ASYNC --",
        "Frame.<anonymous> (/var/task/node_modules/puppeteer/lib/helper.js:108:27)",
        "Page.goto (/var/task/node_modules/puppeteer/lib/Page.js:662:49)",
        "Page.<anonymous> (/var/task/node_modules/puppeteer/lib/helper.js:109:23)",
        "handler (/var/task/pdf.js:19:14)",
        "<anonymous>",
        "process._tickDomainCallback (internal/process/next_tick.js:228:7)"
    ]
}
```

**Comment by govindrai** [comment]
This is happening to me as well. It happens for certain URLs. Please try http://proteus.com. That url causes this issue whereas http://www.google.com does not. I am not able to identify why this would be the case, but it seems like a chromium/puppeteer issue.

**Comment by dattto** [comment]
Had this issue with both 1.11 and 1.12 (chrome 72 and 73). I can confirm that one of flags at:
https://github.com/alixaxel/chrome-aws-lambda/blob/master/source/index.js
solved this issue for me. I've used them all so haven't isolated which one.

**Comment by aslushnikov** [comment]
Looks like a dupe of #2463

**Comment by Noahbambi1** [comment]
> Had this issue with both 1.11 and 1.12 (chrome 72 and 73). I can confirm that one of flags at:
> https://github.com/alixaxel/chrome-aws-lambda/blob/master/source/index.js
> solved this issue for me. I've used them all so haven't isolated which one.

This seems to have worked for me too. Thank you @dattto

**Comment by tooleks** [comment]
> Had this issue with both 1.11 and 1.12 (chrome 72 and 73). I can confirm that one of flags at:
https://github.com/alixaxel/chrome-aws-lambda/blob/master/source/index.js
solved this issue for me. I've used them all so haven't isolated which one.

`--single-process` flag solved the issue for me.

**Comment by AndreaAdvanon** [comment]
`--single-process` did not fix the problem for me, I was using it from the start

**Comment by MichaelHirn** [comment]
any updates on this? Having the same problems both with `v1.12` and the latest `v1.15`

Tried with `--single-process`, the args from here (https://github.com/alixaxel/chrome-aws-lambda/blob/master/source/index.js), and various combinations and didn't get it to work. Works fine locally, though. So maybe it is related to hard drive space limitations on AWS?

Edit: submitted too early and added the second paragraph.

**UPDATE**: was an application bug where another object handled the same `page`

**Comment by diy10264** [comment]
Got the same problem, on AWS lambda. 

Each invocation on instance at first time works well. But AWS reuse the same instance will throw out the same error. 

I think its related to `browser.close()`. seems zombie browser still exists.

**Comment by oza75** [comment]
Got the same problem with version : ^2.0.0
I think it come with the page `goto` call 
`--single-process` dit not fix it
If I try to hide with  `try {} catch{}` I get Websocket error 
```bash
error: Error: WebSocket is not open: readyState 3 (CLOSED)
    at WebSocket.send (/var/task/node_modules/puppeteer-core/node_modules/ws/lib/websocket.js:322:19)
    at WebSocketTransport.send (/var/task/node_modules/puppeteer-core/lib/WebSocketTransport.js:57:14)
    at Connection.send (/var/task/node_modules/puppeteer-core/lib/Connection.js:71:21)
    at gracefullyCloseChrome (/var/task/node_modules/puppeteer-core/lib/Launcher.js:209:20)
    at Browser.close (/var/task/node_modules/puppeteer-core/lib/Browser.js:255:31)
    at Browser.<anonymous> (/var/task/node_modules/puppeteer-core/lib/helper.js:145:23)
    at getHTML (/var/task/src/details/details.js:108:23)
    at <anonymous>
 ```

**Comment by Meekohi** [comment]
When people say the "flags from ... solved the problem", could someone specifically show which flags they are including here that solved the problem? Are you talking about `--memory-pressure-off`?

**Comment by Meekohi** [comment]
Curious if someone could test whether it's `--no-zygote` that solves the issue https://codereview.chromium.org/2384163002

**Comment by neekey** [comment]
i'm having the same issue when using puppeteer in aws lamda, but my case only happens for certain websites, for example: https://www.dailymotion.com/ (I will be very appreciated if someone can try this for me), it will fail with this error everytime, but other websites work fine for me.

it also works fine in my local btw

**Comment by jared-w-smith** [comment]
I'm also getting this error, though not using Lambda. After around 10,000 or so pages are opened via Puppeteer (each a unique process) on an EC2 instance, this error starts to sporadically and randomly appear, then increases in frequency until nearly every process returns this error. There are no stray processes running and no disk or memory constraints.

**Comment by neekey** [comment]
@jared-w-smith not sure if it will help but I solved my problem by changing the version of Chromium back to 79, which based on what module you are using, if you are just using Puppeteer, you can downgrade to `2.0.x`

My solution with `chrome-aws-lamda` is [here](https://github.com/alixaxel/chrome-aws-lambda/issues/104) just a reference for anyone experiencing the same problem.

**Comment by el0911** [comment]
> --single-process

Single process
Finally, for the purposes of comparison, Chromium supports a single process model that can be enabled using the --single-process command-line switch. In this model, both the browser and rendering engine are run within a single OS process.

The single process model provides a baseline for measuring any overhead that the multi-process architectures impose. It is not a safe or robust architecture, as any renderer crash will cause the loss of the entire browser process. It is designed for testing and development purposes, and it may contain bugs that are not present in the other architectures.

**Comment by salvadornava01** [comment]
Hello friends! I've solved the problem wrapping all the puppeteer logic inside a try - catch - finally like the following:

`  let browser = null;
  try {...
  browser = await chromium.puppeteer.launch({ ...
  ...
  } catch (error) {
    console.log(error);
  } finally {
    if (browser !== null) {
      await browser.close();
    }
  }
  `

Before I missed the "finally" block and after 2 or 3 lambda executions I fall on the issue, so I've added the "finally" block and when I execute lambda, no matter how many times, the issue is gone.

Hope all you guys find this helpful!

Best regards!

**Comment by josfh2005** [comment]
Had the same problem and the cause was some images with incorrect content type (application/oct-stream)

**Comment by fabiel-leon** [comment]
this worked for me 
https://github.com/alixaxel/chrome-aws-lambda/issues/104#issuecomment-625999698

**Comment by cloudhuang** [comment]
remove the `await close()` method resolve the problem for me.

**Comment by kalintro** [comment]
Hi there! I have the same issue, and it seems like everytime I have an image with https in my html, the error occures. Anyone have any suggestion on how to fix this?

**Comment by userme99x** [comment]
> Hi there! I have the same issue, and it seems like everytime I have an image with https in my html, the error occures. Anyone have any suggestion on how to fix this?

Hi @kalintro , Facing same issue. Have you found any solution?

**Comment by kalintro** [comment]
@userme99x Hi there! Yes, I just found a set that works!  "@sparticuz/chromium": "123.0.1" and "puppeteer-core": "22.7.1" works as a charm in my env!
