### ISSUE TITLE
Can't goto() a font file

### ISSUE THREAD

**Issue by groundclutter** [puppeteer/puppeteer#3953]
Trying to goto() any kind of font file (WOFF, WOFF2, TTF) never returns and generates the following warning: 

```
(node:70787) UnhandledPromiseRejectionWarning: Error: net::ERR_ABORTED at https://fonts.gstatic.com/s/opensans/v15/mem8YaGs126MiZpBA-UFVZ0e.ttf
    at navigate (/home/me/src/node/node_modules/puppeteer/lib/FrameManager.js:101:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (/home/me/src/node/node_modules/puppeteer/lib/helper.js:108:27)
    at Page.goto (/home/me/src/node/node_modules/puppeteer/lib/Page.js:662:49)
    at Page.<anonymous> (/home/me/src/node/node_modules/puppeteer/lib/helper.js:109:23)
    at /home/me/bug.js:6:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:70787) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:70787) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Steps to reproduce

```
const puppeteer = require('puppeteer');
(async () => {
    const browser = await puppeteer.launch({args: ['--no-sandbox','--disable-setuid-sandbox']});
    const page = await browser.newPage();
    await page.goto('https://fonts.gstatic.com/s/opensans/v15/mem8YaGs126MiZpBA-UFVZ0e.ttf');
    await browser.close();
})();

```

**Tell us about your environment:**

* Puppeteer version: 1.12.2
* Platform / OS version: CENTOS7
* Node.js version: 10.15.0

I'm able to reproduce this with any font file on seemingly any host - including my own where I'm 100% sure there is nothing intentionally blocking the requests.  Requesting html, css, images from the same hosts work fine.

**Comment by aslushnikov** [comment]
Navigation to font files yields a download instead of a navigation. As a result, navigation per se gets aborted - this is expected.

We don't have a nice download support yet - see #299

**Comment by pankhiprasher** [comment]
hey @aslushnikov  do we have a solution to this now? Trying to download font file with puppeteer.
