### ISSUE TITLE
Evaluate. Limitations on the amount of data returned?

### ISSUE THREAD

**Issue by UltraDosaaf** [puppeteer/puppeteer#3955]
I'm facing some wiered issue:

```javascript
{ Error: Protocol error (Runtime.callFunctionOn): Target closed.
    at Promise (C:\Users\me\Desktop\test-app\node_modules\puppeteer\lib\Connection.js:183:56)
    at new Promise (<anonymous>)
    at CDPSession.send (C:\Users\me\Desktop\test-app\node_modules\puppeteer\lib\Connection.js:182:12)
    at JSHandle.jsonValue (C:\Users\me\Desktop\test-app\node_modules\puppeteer\lib\JSHandle.js:87:43)
    at JSHandle.<anonymous> (C:\Users\me\Desktop\test-app\node_modules\puppeteer\lib\helper.js:109:23)
    at ExecutionContext.evaluate (C:\Users\me\Desktop\test-app\node_modules\puppeteer\lib\ExecutionContext.js:49:33)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (C:\Users\me\Desktop\test-app\node_modules\puppeteer\lib\helper.js:108:27)
    at DOMWorld.evaluate (C:\Users\me\Desktop\test-app\node_modules\puppeteer\lib\DOMWorld.js:105:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  -- ASYNC --
    at Frame.<anonymous> (C:\Users\me\Desktop\test-app\node_modules\puppeteer\lib\helper.js:108:27)
    at Page.evaluate (C:\Users\me\Desktop\test-app\node_modules\puppeteer\lib\Page.js:815:43)
    at Page.<anonymous> (C:\Users\me\Desktop\test-app\node_modules\puppeteer\lib\helper.js:109:23)
    at CanvasRecorder (C:\Users\me\Desktop\test-app\app.js:118:28)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  message: 'Protocol error (Runtime.callFunctionOn): Target closed.' }
```

So, I spent some time to find out what actually causes this issue, and... it looks like it was this code: 
```javascript
let data = await page.evaluate((timeout) => {
   return new Promise((resolve, reject) => {
      resolve({ huge_base64_string }); <-------------------
   })
}, timeout);
```

I'm sending ~115MB of data from the browser level back to main process and it crashes the pptr. Maybe there is some limitations for size of sending data?

**Comment by vsemozhetbyt** [comment]
As per test on Windows 7 x64, the safe string length to be transferred is `104857493` (~ 100 MB  one-byte encoded).
```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch();
    const [page] = await browser.pages();

    await page.goto('https://example.org/');

    const safeLength = 104857493;

    const str1 = await page.evaluate((length) => {
      return '-'.repeat(length);
    }, safeLength);
    console.log(str1.length === safeLength);

    const str2 = await page.evaluate((length) => {
      return '-'.repeat(length);
    }, safeLength + 1);
    console.log(str2.length === safeLength + 1);

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```

```
true
{ Error: Protocol error (Runtime.callFunctionOn): Target closed.
    at Promise (puppeteer\lib\Connection.js:183:56)
    at new Promise (<anonymous>)
    at CDPSession.send (puppeteer\lib\Connection.js:182:12)
    at ExecutionContext.evaluateHandle (puppeteer\lib\ExecutionContext.js:106:44)
    at ExecutionContext.<anonymous> (puppeteer\lib\helper.js:109:23)
    at ExecutionContext.evaluate (puppeteer\lib\ExecutionContext.js:48:31)
    at ExecutionContext.<anonymous> (puppeteer\lib\helper.js:109:23)
    at DOMWorld.evaluate (puppeteer\lib\DOMWorld.js:105:20)
    at process.internalTickCallback (internal/process/next_tick.js:74:5)
  -- ASYNC --
    at Frame.<anonymous> (puppeteer\lib\helper.js:108:27)
    at Page.evaluate (puppeteer\lib\Page.js:815:43)
    at Page.<anonymous> (puppeteer\lib\helper.js:109:23)
    at main (test.js:19:29)
    at process.internalTickCallback (internal/process/next_tick.js:74:5)
  message: 'Protocol error (Runtime.callFunctionOn): Target closed.' }
```
Should this be documented if this is expected?

**Comment by UltraDosaaf** [comment]
Is it unavoidable limitation?

**Comment by tpkn** [comment]
`page.exposeFunction` should work.

```javascript
let huge_base64_string;

await page.exposeFunction('forwardMyHugeString', (data) => {
   huge_base64_string = data;
});

let data = await page.evaluate((timeout) => {
   return new Promise((resolve, reject) => {
      window.forwardMyHugeString('huge_base64_string');
      resolve();
   })
}, timeout);

console.log(huge_base64_string);
```
