### ISSUE TITLE
"Protocol error (Runtime.callFunctionOn): Target closed." inside Docker container.

### ISSUE THREAD

**Issue by GuanHaoSu** [puppeteer/puppeteer#3991]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:1.9.0
* Platform / OS version: docker image -  node:8.11.3
* URLs (if applicable):
* Node.js version:8.11.3

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.Build docker image with following:
```
FROM node:8.11.3

RUN apt-get update && \
    apt-get -y install xvfb gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 \
      libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 \
      libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 \
      libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 \
      libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget && \
rm -rf /var/lib/apt/lists/*

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY package.json /usr/src/app/
RUN npm install --unsafe-perm=true --allow-root

COPY . /usr/src/app
CMD [ "npm", "test", "example2.test.js"]
```
2. My example2.test.js to test puppeteer in container:

```const puppeteer = require('puppeteer')

let browser
let page

test('Test', async() => {
  browser = await puppeteer.launch({
    args: [
      // Required for Docker version of Puppeteer
      '--no-sandbox',
      '--disable-setuid-sandbox',
      // This will write shared memory files into /tmp instead of /dev/shm,
      // because Docker’s default for /dev/shm is 64MB
      '--disable-dev-shm-usage'
    ]
  })

  const browserVersion = await browser.version()
  console.log(`Started ${browserVersion}`)
  
  page = await browser.newPage()
  const response = await page.goto('http://google.com/')
  let searchform = await page.waitForSelector('#searchform');

  await searchform.click();
  await page.screenshot({path: './screenshot.png', fullPage: true});
  
  await page.close()
  await browser.close()
    
})
```
3. Run the container and the test failed when click a element:
```
> puppet@1.0.0 test /usr/src/app
> jest "example2.test.js"

  console.log example2.test.js:20
    Started HeadlessChrome/73.0.3679.0

FAIL ./example2.test.js (8.664s)
  ✕ Test (7844ms)

  ● Test

    Protocol error (Runtime.callFunctionOn): Target closed.

      24 |   let searchform = await page.waitForSelector('#searchform');
      25 |
    > 26 |   await searchform.click();
         |                    ^
      27 |   await page.screenshot({path: './screenshot.png', fullPage: true});
      28 |
      29 |   await page.close()

      at Promise (node_modules/puppeteer/lib/Connection.js:183:56)
      at CDPSession.send (node_modules/puppeteer/lib/Connection.js:182:12)
      at ExecutionContext.evaluateHandle (node_modules/puppeteer/lib/ExecutionContext.js:106:44)
      at ExecutionContext.<anonymous> (node_modules/puppeteer/lib/helper.js:109:23)
      at ExecutionContext.evaluate (node_modules/puppeteer/lib/ExecutionContext.js:48:31)
      at ExecutionContext.<anonymous> (node_modules/puppeteer/lib/helper.js:109:23)
      at ElementHandle._scrollIntoViewIfNeeded (node_modules/puppeteer/lib/JSHandle.js:163:49)
      at ElementHandle.click (node_modules/puppeteer/lib/JSHandle.js:247:16)
      at ElementHandle.<anonymous> (node_modules/puppeteer/lib/helper.js:109:23)
      at Object.click (example2.test.js:26:20)

```

**What is the expected result?**
The test should pass. 
The same code run in Ubuntu 16 outside the container without any problem.

**What happens instead?**
Exception thorws:  Protocol error (Runtime.callFunctionOn): Target closed.

**Comment by patheard** [comment]
It may be related to this [answer on SO](https://stackoverflow.com/a/54837726/152963).  I was having a similar problem and downgrading my version of Chrome to **Chromium 72.0.3582.0** fixed the issue.

Here's the behaviour I was seeing:

- Test with `page.click` ran fine locally.
- Test with `page.click` ran fine locally in a docker container.
- Test [failed on CircleCI](https://circleci.com/gh/patheard/cucumber-puppeteer/190) in same docker container with the following error:

```
    Protocol error (Runtime.callFunctionOn): Target closed.

      30 |     
      31 |     await page.waitForSelector('.nav');
    > 32 |     await page.click('.nav');
         |                ^
      33 |     await browser.close();
      34 |   });
      35 | 

      at Promise (node_modules/puppeteer/lib/Connection.js:183:56)
      at CDPSession.send (node_modules/puppeteer/lib/Connection.js:182:12)
      at ExecutionContext.evaluateHandle (node_modules/puppeteer/lib/ExecutionContext.js:106:44)
      at ExecutionContext.<anonymous> (node_modules/puppeteer/lib/helper.js:109:23)
      at ExecutionContext.evaluate (node_modules/puppeteer/lib/ExecutionContext.js:48:31)
      at ExecutionContext.<anonymous> (node_modules/puppeteer/lib/helper.js:109:23)
      at ElementHandle._scrollIntoViewIfNeeded (node_modules/puppeteer/lib/JSHandle.js:163:49)
      at ElementHandle.click (node_modules/puppeteer/lib/JSHandle.js:247:16)
      at ElementHandle.<anonymous> (node_modules/puppeteer/lib/helper.js:109:23)
      at DOMWorld.click (node_modules/puppeteer/lib/DOMWorld.js:360:18)
        -- ASYNC --
      at Frame.<anonymous> (node_modules/puppeteer/lib/helper.js:108:27)
      at Page.click (node_modules/puppeteer/lib/Page.js:1021:29)
      at Object.click (test/action/clickElement.test.js:32:16)
```

**Comment by mustafah15** [comment]
I have the same issue! 
any idea what cause this ?!

**Comment by GuanHaoSu** [comment]
I changed my docker storage driver to overlay2 then the problem fixed.

**Comment by mustafah15** [comment]
@GuanHaoSu is that possible on CircleCi ?

**Comment by haikyuu** [comment]
@mustafah15 it works using `puppeteer@1.11.0`

**Comment by haikyuu** [comment]
We should reopen this issue

**Comment by aslushnikov** [comment]
A common reason for "page closed" error in docker is related to a bad sandbox.
So I'd suggest a few things here:
- try [setting up a proper sandbox](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#setting-up-chrome-linux-sandbox)
- try [using our docker image](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker) - we exercise it daily to run Puppeteer tests, so it's valid.

**Comment by haikyuu** [comment]
Thank you @aslushnikov 👍
