### ISSUE TITLE
'npm i puppeteer' fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by PorkCharsui79** [puppeteer/puppeteer#4010]
**Tell us about your environment:**

* Puppeteer version: v1.12.2
* Platform / OS version: Ubuntu 16.04 Xenial / kernel 4.15.0-15-generic
* Node.js version: v11.9.0
* NPM: v6.5.0
* [2019-02-14T10_22_39_643Z-debug.log](https://github.com/GoogleChrome/puppeteer/files/2864569/2019-02-14T10_22_39_643Z-debug.log)

**What steps will reproduce the problem?**
1. npm i puppeteer

**What is the expected result?**
It installs puppeteer.

**What happens instead?**
> puppeteer@1.12.2 install /root/node_modules/puppeteer
> node install.js

internal/modules/cjs/loader.js:611
    throw err;
    ^

Error: Cannot find module '/root/node_modules/puppeteer/install.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:609:15)
    at Function.Module._load (internal/modules/cjs/loader.js:535:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:797:12)
    at executeUserCode (internal/bootstrap/node.js:526:15)
    at startMainThreadExecution (internal/bootstrap/node.js:439:3)
npm WARN root No description
npm WARN root No repository field.
npm WARN root No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.12.2 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@1.12.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-02-14T10_40_47_518Z-debug.log

**Comment by PorkCharsui79** [comment]
Don't try installing as root.
