### ISSUE TITLE
cannot be invoked without 'new'

### ISSUE THREAD

**Issue by tcurdt** [puppeteer/puppeteer#405]
Just following the instructions the following `test.js`

```
const puppeteer = require('puppeteer')
(async () => {
  const browser = await puppeteer.launch({headless: false})
  const page = await browser.newPage()
  await page.goto('https://example.com', {waitUntil: 'networkidle'})
  browser.close()
})()
```

gives `node test.js`

```
(async () => {
^
TypeError: Class constructor Puppeteer cannot be invoked without 'new'
    at Object.<anonymous> (/foo/test.js:3:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```
> Puppeteer requires Node version 7.10 or greater

```
$ node -v
v8.2.1
```

**Comment by tcurdt** [comment]
Seems like
```
const puppeteer = require('puppeteer')

puppeteer.launch({headless: false}).then(async browser => {
  let page = await browser.newPage()
  await page.goto('https://google.com')
  await page.waitForNavigation({waitUntil: 'networkidle'})
  browser.close()
})
```
is doing the right thing.

**Comment by ebidel** [comment]
`;` are your friend :) This runs fine for me:

```js
const puppeteer = require('puppeteer');
(async () => {
  const browser = await puppeteer.launch({headless: false});
  const page = await browser.newPage();
  await page.goto('https://example.com', {waitUntil: 'networkidle'});
  browser.close();
})();
```

**Comment by tcurdt** [comment]
no, `;` are definitely not my friends ;)

Seems like only one is required - for whatever reason.
This works, too:

```
const puppeteer = require('puppeteer');
(async () => {
  const browser = await puppeteer.launch({headless: false})
  const page = await browser.newPage()
  await page.goto('https://example.com', {waitUntil: 'networkidle'})
  browser.close();
})()
```

**Comment by positlabs** [comment]
It's something to do with the immediate async function. 

No `;` required if you assign the function to a variable, then call it.


```
const puppeteer = require('puppeteer')
const run = async () => {
    const browser = await puppeteer.launch({headless: false})
    const page = await browser.newPage()
    await page.goto('https://news.ycombinator.com', {waitUntil: 'networkidle'})
    browser.close()
}
run()
```

**Comment by millette** [comment]
I know this issue is closed (just encountered it too) but I go with

> Never start a line with (, [, or `. This is the only gotcha with omitting semicolons

from [standardjs](https://standardjs.com/rules.html#semicolons).

**Comment by jrainlau** [comment]
The key of this problem is that you forgot adding `;` in front of `(async () => {})()`.

```
const puppeteer = require('puppeteer')

;(async () => {
  const browser = await puppeteer.launch()
  const page = await browser.newPage()
  await page.goto('https://jrainlau.github.io')
  await page.screenshot({path: './example.png'})

  await browser.close()
})()

```
code above would solve the problem :)

**Comment by chriswininger** [comment]
Not sure what this says about the trend away from semicolons in JavaScript :-(
