### ISSUE TITLE
Cannot read property 'children' of null on page.evaluate()

### ISSUE THREAD

**Issue by ratkorle** [puppeteer/puppeteer#4073]
* Puppeteer version: "^1.12.2"
* Node.js version: v9.8.0

I am trying to produce a **good quality query string**, which I get it from **X, Y coordinates**.

This is my code:

```
let chosenElement = await page.evaluate((payload) => {
            return document.elementsFromPoint(payload.data.x, payload.data.y)
                .map((o) => {
                    let sibArr = Array.from(o.parentElement.children);
                    if (sibArr.length > 0) {
                        let oIndex = Array.from(o.parentElement.children).indexOf(o);
                        return `${o.tagName}:nth-child(${oIndex + 1})`;
                    } else if (o.id) {
                        return o.id;
                    } else if (o.className) {
                        if (o.className.includes(' ')) {
                            return o.tagName.toLowerCase() + '.' + o.className.split(' ').join('.');
                        } else {
                            return o.tagName.toLowerCase() + '.' + o.className;
                        }
                    } else {
                        return o.tagName.toLowerCase();
                    }
                }).reverse().join(' > ');
        }, payload);
```
**What is the expected result?**
`'html > body > #mainContainer > div:nth-child(3) > p.price'`

**What happens instead?**

```
Error: Evaluation failed: TypeError: Cannot read property 'children' of null
    at __puppeteer_evaluation_script__:4:61
    at Array.map (<anonymous>)
    at __puppeteer_evaluation_script__:3:18
    at ExecutionContext.evaluateHandle (/Users/xcode_projects/node_modules/puppeteer/lib/ExecutionContext.js:121:13)
    at <anonymous>
  -- ASYNC --
    at ExecutionContext.<anonymous> (/Users/todornikolov/xcode_projects/mobilesubscription/scraper-surveilance/socket-server/node_modules/puppeteer/lib/helper.js:108:27)
    at ExecutionContext.evaluate (/Users/node_modules/puppeteer/lib/ExecutionContext.js:48:31)
    at ExecutionContext.<anonymous> (/Users/xcode_projects/node_modules/puppeteer/lib/helper.js:109:23)
    at DOMWorld.evaluate (/Users/xcode_projects/node_modules/puppeteer/lib/DOMWorld.js:105:20)
```

**Comment by ratkorle** [comment]
This fixed it:

```
 let chosenElement = await page.evaluate((payload) => {
            return document.elementsFromPoint(payload.data.x, payload.data.y)
                .map((o) => {
                    let sibArr = Array.from(o.parentNode.children).filter(i => i.tagName === o.tagName);
                    if (sibArr.indexOf(o) > 0) {
                        let oIndex = sibArr.indexOf(o);
                        return `${o.tagName.toLowerCase()}:nth-child(${oIndex + 1})`;
                    } else if (o.id) {
                        return '#' + o.id;
                    } else if (o.className) {
                        return `${o.tagName.toLowerCase()}.${Array.from(o.classList).join('.')}`
                    } else {
                        return o.tagName.toLowerCase();
                    }
                }).reverse().filter(e => !e.includes('html')).join(' > ');
        }, payload);
```

This creates good query string for further usage.

I hope this will help some other guys
