### ISSUE TITLE
Don't work with png, but work with pdf

### ISSUE THREAD

**Issue by Inkognitoo** [puppeteer/puppeteer#4085]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.12.2
* Platform / OS version: Ubuntu 16.04.3
* URLs (if applicable):
* Node.js version: 11.10.0

**What steps will reproduce the problem?**

Run code:
```
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({
        headless: true,
        args: ['--no-sandbox', '--disable-dev-shm-usage']
    });
    const page = await browser.newPage();
    await page.goto('https://www.google.com');
    await page.screenshot({path: 'example.png'});

    await browser.close();
})();
```

**What is the expected result?**
Image

**What happens instead?**
Error:
```
(node:6179) UnhandledPromiseRejectionWarning: Error: Protocol error (Page.captureScreenshot): Target closed.
    at Promise (/var/www/node_modules/puppeteer/lib/Connection.js:183:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/var/www/node_modules/puppeteer/lib/Connection.js:182:12)
    at Page._screenshotTask (/var/www/node_modules/puppeteer/lib/Page.js:903:39)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
  -- ASYNC --
    at Page.<anonymous> (/var/www/node_modules/puppeteer/lib/helper.js:108:27)
    at /var/www/index.js:10:16
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:6179) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6179) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

But strange thing, it's work if I create pdf file:
```
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({
        headless: true,
        args: ['--no-sandbox', '--disable-dev-shm-usage']
    });
    const page = await browser.newPage();
    await page.goto('https://www.google.com');
    await page.pdf({path: 'hn.pdf', format: 'A4'});

    await browser.close();
})();
```

What is wrong?

**Comment by aslushnikov** [comment]
Nothing seems to be wrong with your code; this looks purely as a host problem. The "target closed" error you're getting is due to the page crashing; this usually has something to do with the host environment you're running in.

I'd try:
- running bundled chromium manually and see if you can take screenshots via DevTools
- use Stable Chrome instead of chromium and see if it works
- if it doesn't work, than run stable chrome, make the page crash while taking the screenshot, and then goto chrome://crashes and file a bug to Chromium project with the latest crash.

Hope this helps
