### ISSUE TITLE
Puppeteer-firefox fails postinstall download, storage.googleapis.com says User project billing account not in good standing

### ISSUE THREAD

**Issue by asmundg** [puppeteer/puppeteer#4118]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: puppeteer-firefox 0.5.0
* Platform / OS version: Ubuntu 18.04.2 LTS
* URLs (if applicable):
* Node.js version: v11.1.0

**What steps will reproduce the problem?**

1. `yarn add puppeteer-firefox@0.5.0`

**What is the expected result?**

Puppeteer-firefox installs

**What happens instead?**

```
yarn add v1.13.0
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/2] ⠠ puppeteer
error /home/asgramme/src/tmp/node_modules/puppeteer-firefox: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /home/asgramme/src/tmp/node_modules/puppeteer-firefox
Output:
ERROR: Failed to download Firefox r2f959d575a3d61f5dda12e4e2dca1f46a92ab569!
Error: Download failed: server returned code 403. URL: https://storage.googleapis.com/juggler-builds/2f959d575a3d61f5dda12e4e2dca1f46a92ab569/firefox-linux.zip
    at response (/home/asgramme/src/tmp/node_modules/puppeteer-firefox/lib/BrowserFetcher.js:263:21)
    at ClientRequest.requestCallback (/home/asgramme/src/tmp/node_modules/puppeteer-firefox/lib/BrowserFetcher.js:319:7)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:562:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:449:20)
    at TLSSocket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
  -- ASYNC --
    at BrowserFetcher.<anonymous> (/home/asgramme/src/tmp/node_modules/puppeteer-firefox/lib/helper.js:31:27)
    at Object.<anonymous> (/home/asgramme/src/tmp/node_modules/puppeteer-firefox/install.js:47:16)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:760:12)
    at startup (internal/bootstrap/node.js:308:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:878:3)
```

Loading the URL in a browser returns

```
<Error><Code>UserProjectAccountProblem</Code><Message>User project billing account not in good standing.</Message><Details>The billing account for project 1092466364837 is disabled in state closed</Details></Error>
```

**Comment by aslushnikov** [comment]
Thanks @asmundg, we're working on it.

**Comment by aslushnikov** [comment]
This is fixed now 🎉Credits go to @PaulKinlan 🔥

**Comment by michaelsalexander83** [comment]
I have the same problem it is failing the download.
Is there a fix for this please?

Can I manually download the correct firefox browser from somewhere?

**Comment by gullerya** [comment]
I have seemingly the same issue, namely error "firefox-win64.zip" not found during installation.

Any news on this or any settings that I may tune up locally to make it through?
