### ISSUE TITLE
response.buffer() Error After 'requestfinished' Event

### ISSUE THREAD

**Issue by lidancheng** [puppeteer/puppeteer#4174]
I use puppeteer to download video from one site. 
on the page `requestfinished` event, all the video has download, so I call `var buffer = await response.buffer();` to get the video data. 
```
Downloader.prototype.onResponse = async function(response) {
  let url = response.url();
  let [path, quote] = url.split('?');
  if(path.endsWith('.flv')) {
    let buffer = await response.buffer();
    await this.saveFlv(path, buffer);
  }
}
```
that works ok, but it occur error occasionally.

``` Promise Promise {
  <rejected> { Error: Protocol error (Network.getResponseBody): Target closed.
    at Promise (/Users/kim/code/node_modules/puppeteer/lib/Connection.js:184:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/Users/kim/code/node_modules/puppeteer/lib/Connection.js:183:12)
    at _contentPromise._bodyLoadedPromise.then (/Users/kim/code/node_modules/puppeteer/lib/NetworkManager.js:597:45)
    at <anonymous>
  message: 'Protocol error (Network.getResponseBody): Target closed.' } }  reason: { Error: Protocol error (Network.getResponseBody): Target closed.
    at Promise (/Users/kim/code/node_modules/puppeteer/lib/Connection.js:184:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/Users/kim/code/node_modules/puppeteer/lib/Connection.js:183:12)
    at _contentPromise._bodyLoadedPromise.then (/Users/kim/code/node_modules/puppeteer/lib/NetworkManager.js:597:45)
    at <anonymous>
  message: 'Protocol error (Network.getResponseBody): Target closed.' }
```

I think it is because the devtools session closed before the requestfinished event. please give me some suggestion. thanks.
the version is  puppeteer@1.13.0, node v8.11.4 on mac.

**Comment by aslushnikov** [comment]
@lidancheng you seem to be closing your page before awaiting the `response.buffer()` method to return. 

You should make sure to wait for the `response.buffer` to complete.

**Comment by lidancheng** [comment]
@aslushnikov thanks for your response.
I add some debug log in the `WebSocketTransport.js`:
```
    this._ws.addEventListener('close', event => {
      if (this.onclose) {
        console.log("ws close >:", event);
        this.onclose.call(null);
      }
    });
```
run the code, finally I got the output:
```
protocol: '',
     _binaryType: 'nodebuffer',
     _closeFrameReceived: false,
     _closeFrameSent: false,
     _closeMessage: '',
     _closeTimer: null,
     _closeCode: 1009,
     _receiver: 
      Receiver {
        ...
        _maxPayload: 104857600,
        _bufferedBytes: 65526,
        _buffers: [Array],
        _compressed: false,
        _payloadLength: 107789193,
        ...
         },
```
the code 1009 means `CLOSE_TOO_LARGE`, so I change the WebSocket constructor in `WebSocketTransport`  like this:
```
 const ws = new WebSocket(url, [], { perMessageDeflate: false , maxPayload:300 * 1024 * 1024});
```
then I never see the error.

**Comment by aslushnikov** [comment]
> the code 1009 means CLOSE_TOO_LARGE, so I change the WebSocket constructor in WebSocketTransport like this:

@lidancheng Thank you for the investigation! It looks like we should do this by default (and add a test).
