### ISSUE TITLE
How to get this to run on CentOS 7?

### ISSUE THREAD

**Issue by majestique** [puppeteer/puppeteer#4189]
I saw the really long troubleshoot thread but I couldn't find a solution from it.
So google-chrome runs fine when I'm logged in as the super user with X11 enabled.

However when I execute `node test.js` I'm getting the error (below).

I'm sure others are experiencing the same problems, does anyone have a thread I may have overlooked? (There are so many).

**The code:**
```
const puppeteer = require('puppeteer');

(async() => {

const browser = await puppeteer.launch();
const page = await browser.newPage();
await page.goto('https://example.com');
await page.screenshot({path: 'example.png'});

browser.close();
})();

```

**Error:**
```
bash-4.2$ node test.js
(node:18501) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
[0321/011509.330167:FATAL:zygote_host_impl_linux.cc(116)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
#0 0x5638d5e20f29 base::debug::CollectStackTrace()
#1 0x5638d5d86593 base::debug::StackTrace::StackTrace()
#2 0x5638d5d9ad1e logging::LogMessage::~LogMessage()
#3 0x5638d740390e service_manager::ZygoteHostImpl::Init()
#4 0x5638d59dc1b7 content::ContentMainRunnerImpl::Initialize()
#5 0x5638d5a0efca service_manager::Main()
#6 0x5638d59da791 content::ContentMain()
#7 0x5638da076178 headless::(anonymous namespace)::RunContentMain()
#8 0x5638da076205 headless::HeadlessBrowserMain()
#9 0x5638d5a0dca3 headless::HeadlessShellMain()
#10 0x5638d39451ac ChromeMain
#11 0x7f9f5ffd03d5 __libc_start_main
#12 0x5638d394502a _start

Received signal 6
#0 0x5638d5e20f29 base::debug::CollectStackTrace()
#1 0x5638d5d86593 base::debug::StackTrace::StackTrace()
#2 0x5638d5e20ab1 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#3 0x7f9f661585d0 <unknown>
#4 0x7f9f5ffe4207 __GI_raise
#5 0x7f9f5ffe58f8 __GI_abort
#6 0x5638d5e1f8e5 base::debug::BreakDebugger()
#7 0x5638d5d9af61 logging::LogMessage::~LogMessage()
#8 0x5638d740390e service_manager::ZygoteHostImpl::Init()
#9 0x5638d59dc1b7 content::ContentMainRunnerImpl::Initialize()
#10 0x5638d5a0efca service_manager::Main()
#11 0x5638d59da791 content::ContentMain()
#12 0x5638da076178 headless::(anonymous namespace)::RunContentMain()
#13 0x5638da076205 headless::HeadlessBrowserMain()
#14 0x5638d5a0dca3 headless::HeadlessShellMain()
#15 0x5638d39451ac ChromeMain
#16 0x7f9f5ffd03d5 __libc_start_main
#17 0x5638d394502a _start
  r8: 0000000000000000  r9: 0000000000000030 r10: 0000000000000008 r11: 0000000000000206
 r12: 00007ffeb719ed38 r13: 0000000000000161 r14: 00007ffeb719f6a0 r15: 00007ffeb719f698
  di: 0000000000004850  si: 0000000000004850  bp: 00007ffeb719ece0  bx: 0000335795f21000
  dx: 0000000000000006  ax: 0000000000000000  cx: ffffffffffffffff  sp: 00007ffeb719eba8
  ip: 00007f9f5ffe4207 efl: 0000000000000206 cgf: 0000000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/home/node_modules/puppeteer/lib/Launcher.js:342:14)
    at Interface.helper.addEventListener (/home/node_modules/puppeteer/lib/Launcher.js:331:50)
    at Interface.emit (events.js:194:15)
    at Interface.close (readline.js:379:8)
    at Socket.onend (readline.js:157:10)
    at Socket.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:18501) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18501) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Tell us about your environment:**

* Puppeteer version: latest
* Platform / OS version: Centos7
* URLs (if applicable):
* Node.js version: 10.15.1

**Comment by majestique** [comment]
All of a sudden it works now.. not sure what i did but when I logged in as a non-root user, then go back into root, and it worked.
