### ISSUE TITLE
Error: Cannot find module 'puppeteer'

### ISSUE THREAD

**Issue by QACodeDev** [puppeteer/puppeteer#4243]
* Puppeteer version:1.14
* Platform / OS version:window 10
* URLs (if applicable):
* Node.js version:10.15.3 (includes npm 6.4.1)

**Issue** : i am running below example.js file

```js
const puppeteer = require('puppeteer');
console.log("Hello World");
(async () => **{**
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://example.com');
})();
```
 and getting the error:

```
C:\NewLearning\Nodejs>node TestScript.js
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'puppeteer'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\NewLearning\Nodejs\TestScript.js:1:81)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
```

**Comment by vsemozhetbyt** [comment]
How did you install puppeteer? Where is it located?

**Comment by aslushnikov** [comment]
@nazimdevs you should install Puppeteer before using it.

```bash
$ mkdir my-project
$ cd my-project
$ npm i puppeteer
```

After that, the `my-project` folder will have a `node_modules/` subfolder with puppeteer folder in it. 
If you put your script in the `my-project` folder, it should see Puppeteer module just fine.

Hope this helps.

**Comment by ernestp** [comment]
I have same error while running examples using recommended method

cd ~/puppeteer-master

$ npm i

$ NODE_PATH=../ node examples/search.js
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'puppeteer'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (~/puppeteer-master/examples/search.js:24:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

$ npm i puppeteer

npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "puppeteer" under a package
npm ERR! also called "puppeteer". Did you name your project the same
npm ERR! as the dependency you're installing?

**Comment by Jaymmyin** [comment]
I use windows 10 and got the same problem.  Previously, I install through 'npm i puppeteer'

Then, I install it through 'npm install puppeteer'. And, it is solved.

**Comment by telanxrays** [comment]
@Jaymmyin os is win7x64, same problem and same solution. thanks guy

**Comment by mmbd-mkulas** [comment]
Ubuntu 24.04 The command "PATH=$PATH:/usr/local/bin:/opt/homebrew/bin NODE_PATH=`npm root -g` node '/var/www/vhosts/mmbd.eu/skladovka.mmbd.eu/vendor/spatie/browsershot/src/../bin/browser.cjs' '{"url":"file:\/\/\/tmp\/1899450890-0701601001724751401\/index.html","action":"pdf","options":{"args":[],"viewport":{"width":800,"height":600},"displayHeaderFooter":false,"printBackground":true}}'" failed. Exit Code: 1(General error) Working directory: /var/www/vhosts/mmbd.eu/skladovka.mmbd.eu/public Output: ================ Error Output: ================ Error: Could not find Chrome (ver. 127.0.6533.88). This can occur if either 1. you did not perform an installation before running the script (e.g. `npx puppeteer browsers install chrome`) or 2. your cache path is incorrectly configured (which is: /var/www/vhosts/mmbd.eu/.cache/puppeteer). For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration. at ChromeLauncher.resolveExecutablePath (/var/www/vhosts/mmbd.eu/skladovka.mmbd.eu/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:291:27) at ChromeLauncher.executablePath (/var/www/vhosts/mmbd.eu/skladovka.mmbd.eu/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:209:25) at ChromeLauncher.computeLaunchArguments (/var/www/vhosts/mmbd.eu/skladovka.mmbd.eu/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:89:37) at async ChromeLauncher.launch (/var/www/vhosts/mmbd.eu/skladovka.mmbd.eu/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:70:28) at async callChrome (/var/www/vhosts/mmbd.eu/skladovka.mmbd.eu/vendor/spatie/browsershot/bin/browser.cjs:94:23)
