### ISSUE TITLE
page.evaluate generates error randomly

### ISSUE THREAD

**Issue by dreamergo** [puppeteer/puppeteer#4245]
**Tell us about your environment:**

* Puppeteer version: 1.14.0
* Platform / OS version: Windows server 2016 64bit
* URLs (if applicable):
* Node.js version: 10.15.0

Everything has worked fine for quite long time, but one day suddenly the errors began to happen.
It's strange that the same codes sometimes work without error, and then generate the error before long.
In brief, I think the codes generate error randomly. 

When the codes generate the rror, I enter the codes (without await page.evaluate..) in chromium developer tool and it always works fine.

1) in fone.js:149:27
```js
var imgNum = await page.evaluate(() => document.getElementsByClassName(`thumbnail-list`)[0].children.length);
```
imgNum gets the number of the thumbnails.
The above causes below error;
```
(node:3696) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'children' of undefined
    at __puppeteer_evaluation_script__:1:60
    at ExecutionContext.evaluateHandle (c:\Program Files\nodejs\node_modules\puppeteer\lib\ExecutionContext.js:121:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (c:\Program Files\nodejs\node_modules\puppeteer\lib\helper.js:110:27)
    at ExecutionContext.evaluate (c:\Program Files\nodejs\node_modules\puppeteer\lib\ExecutionContext.js:48:31)
    at ExecutionContext.<anonymous> (c:\Program Files\nodejs\node_modules\puppeteer\lib\helper.js:111:23)
    at DOMWorld.evaluate (c:\Program Files\nodejs\node_modules\puppeteer\lib\DOMWorld.js:105:20)
  -- ASYNC --
    at Frame.<anonymous> (c:\Program Files\nodejs\node_modules\puppeteer\lib\helper.js:110:27)
    at Page.evaluate (c:\Program Files\nodejs\node_modules\puppeteer\lib\Page.js:809:43)
    at Page.<anonymous> (c:\Program Files\nodejs\node_modules\puppeteer\lib\helper.js:111:23)
    at runC (c:\Program Files\nodejs\works\fone.js:149:27)
(node:3696) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3696) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

2) in ftwo.js:61:25
```js
const nn = await page.evaluate(() => document.getElementsByClassName("col-md-3 info")[0].children.length);
```
The above causes below error;
```
(node:2868) UnhandledPromiseRejectionWarning: Error: Execution context was destroyed, most likely because of a navigation.
    at rewriteError (c:\Program Files\nodejs\node_modules\puppeteer\lib\ExecutionContext.js:161:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (c:\Program Files\nodejs\node_modules\puppeteer\lib\helper.js:110:27)
    at ExecutionContext.evaluate (c:\Program Files\nodejs\node_modules\puppeteer\lib\ExecutionContext.js:48:31)
    at ExecutionContext.<anonymous> (c:\Program Files\nodejs\node_modules\puppeteer\lib\helper.js:111:23)
    at DOMWorld.evaluate (c:\Program Files\nodejs\node_modules\puppeteer\lib\DOMWorld.js:105:20)
  -- ASYNC --
    at Frame.<anonymous> (c:\Program Files\nodejs\node_modules\puppeteer\lib\helper.js:110:27)
    at Page.evaluate (c:\Program Files\nodejs\node_modules\puppeteer\lib\Page.js:809:43)
    at Page.<anonymous> (c:\Program Files\nodejs\node_modules\puppeteer\lib\helper.js:111:23)
    at runC (c:\Program Files\nodejs\works\ftwo.js:61:25)
(node:2868) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2868) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I am stuck for days.

**Comment by aslushnikov** [comment]
> Everything has worked fine for quite long time, but one day suddenly the errors began to happen.

@dreamergo it looks like the website logic has changed.

> in fone.js:149:27

The first error happens due to page's DOM being different to what you expect. It might be because server sometimes responds with something different, e.g. due to A/B testing. 

> in ftwo.js:61:25

This looks like a navigation/reload is happening in some random time, killing your pending evaluations. This is not Puppeteer's fault - Puppeteer can't complete evaluation if the page navigates away.

These all seem to be issues related to handling a particular website rather than troubles with Puppeteer per se. I'll close this since there's nothing we can do on the PPTR side.
