### ISSUE TITLE
Attaching a file to a file input on WSL bash Windows 10 will cause a page crash

### ISSUE THREAD

**Issue by karl-roberts** [puppeteer/puppeteer#4280]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.14.0
* Platform / OS version: Windows 10 Pro 1803 with WSL 
* URLs (if applicable):
* Node.js version: 11.2.0

**What steps will reproduce the problem?**
Getting a handle to a file input through the WSL will cause the page to crash immediately, no form submits required

_Please include code that reproduces the issue._

    const fileControl = await page.page.$('input[type=file][name="discrep_factor_evidence[]"]')
    const testFilePath = FileHelper.appRoot('/test/functional/biscuit.png')
    console.log('test file path: ', testFilePath)
    await fileControl.uploadFile(testFilePath)
    // crash

**What is the expected result?**
   That the file will attach and the functional test will carry on as intended and submit a form

**What happens instead?**
   The test errors and exits with the following being rendered in the console:

warning:
  WARNING: Adonis has detected an unhandled promise rejection, which may
  cause undesired behavior in production.
  To stop this warning, use catch() on promises or wrap await
  calls inside try/catch.

Error: Page crashed!
    at Page._onTargetCrashed (/mnt/c/Users/kroberts/code/service-claims-processing/node_modules/puppeteer/lib/Page.js:185:24)
    at CDPSession.Page.client.on.event (/mnt/c/Users/kroberts/code/service-claims-processing/node_modules/puppeteer/lib/Page.js:140:56)
    at CDPSession.emit (events.js:182:13)
    at CDPSession.EventEmitter.emit (domain.js:441:20)
    at CDPSession._onMessage (/mnt/c/Users/kroberts/code/service-claims-processing/node_modules/puppeteer/lib/Connection.js:200:12)
    at Connection._onMessage (/mnt/c/Users/kroberts/code/service-claims-processing/node_modules/puppeteer/lib/Connection.js:112:17)
    at WebSocketTransport._ws.addEventListener.event (/mnt/c/Users/kroberts/code/service-claims-processing/node_modules/puppeteer/lib/WebSocketTransport.js:41:24)
    at WebSocket.onMessage (/mnt/c/Users/kroberts/code/service-claims-processing/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:182:13)
    at WebSocket.EventEmitter.emit (domain.js:441:20)
    at Receiver.receiverOnMessage (/mnt/c/Users/kroberts/code/service-claims-processing/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:182:13)
    at Receiver.EventEmitter.emit (domain.js:441:20)
    at Receiver.dataMessage (/mnt/c/Users/kroberts/code/service-claims-processing/node_modules/ws/lib/receiver.js:422:14)
    at Receiver.getData (/mnt/c/Users/kroberts/code/service-claims-processing/node_modules/ws/lib/receiver.js:352:17)
    at Receiver.startLoop (/mnt/c/Users/kroberts/code/service-claims-processing/node_modules/ws/lib/receiver.js:138:22)
    at Receiver._write (/mnt/c/Users/kroberts/code/service-claims-processing/node_modules/ws/lib/receiver.js:74:10)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Receiver.Writable.write (_stream_writable.js:299:11)
    at Socket.socketOnData (/mnt/c/Users/kroberts/code/service-claims-processing/node_modules/ws/lib/websocket.js:864:35)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:287:12)
    at readableAddChunk (_stream_readable.js:268:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:122:17)
form submit exception:  Error: Navigation failed because browser has disconnected!
    at CDPSession.LifecycleWatcher._eventListeners.helper.addEventListener (/mnt/c/Users/kroberts/code/service-claims-processing/node_modules/puppeteer/lib/LifecycleWatcher.js:47:107)
    at CDPSession.emit (events.js:182:13)
    at CDPSession.EventEmitter.emit (domain.js:441:20)
    at CDPSession._onClosed (/mnt/c/Users/kroberts/code/service-claims-processing/node_modules/puppeteer/lib/Connection.js:215:10)
    at Connection._onMessage (/mnt/c/Users/kroberts/code/service-claims-processing/node_modules/puppeteer/lib/Connection.js:105:17)
    at WebSocketTransport._ws.addEventListener.event (/mnt/c/Users/kroberts/code/service-claims-processing/node_modules/puppeteer/lib/WebSocketTransport.js:41:24)
    at WebSocket.onMessage (/mnt/c/Users/kroberts/code/service-claims-processing/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:182:13)
    at WebSocket.EventEmitter.emit (domain.js:441:20)
    at Receiver.receiverOnMessage (/mnt/c/Users/kroberts/code/service-claims-processing/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:182:13)
    at Receiver.EventEmitter.emit (domain.js:441:20)
    at Receiver.dataMessage (/mnt/c/Users/kroberts/code/service-claims-processing/node_modules/ws/lib/receiver.js:422:14)
    at Receiver.getData (/mnt/c/Users/kroberts/code/service-claims-processing/node_modules/ws/lib/receiver.js:352:17)
    at Receiver.startLoop (/mnt/c/Users/kroberts/code/service-claims-processing/node_modules/ws/lib/receiver.js:138:22)
    at Receiver._write (/mnt/c/Users/kroberts/code/service-claims-processing/node_modules/ws/lib/receiver.js:74:10)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Receiver.Writable.write (_stream_writable.js:299:11)
    at Socket.socketOnData (/mnt/c/Users/kroberts/code/service-claims-processing/node_modules/ws/lib/websocket.js:864:35)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:287:12)
    at readableAddChunk (_stream_readable.js:268:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:122:17)
  -- ASYNC --
    at Frame.<anonymous> (/mnt/c/Users/kroberts/code/service-claims-processing/node_modules/puppeteer/lib/helper.js:110:27)
    at Page.waitForNavigation (/mnt/c/Users/kroberts/code/service-claims-processing/node_modules/puppeteer/lib/Page.js:676:49)
    at Page.<anonymous> (/mnt/c/Users/kroberts/code/service-claims-processing/node_modules/puppeteer/lib/helper.js:111:23)
    at _actions.(anonymous function) (/mnt/c/Users/kroberts/code/service-claims-processing/node_modules/@adonisjs/vow-browser/src/Browser/ActionsChain.js:295:70)

**Comment by aslushnikov** [comment]
@karl-roberts this looks like a Chromium or WSL issue to me. 

Can you run chromium on WSL and select a file using the file dialog? Does it work?

**Comment by karl-roberts** [comment]
@aslushnikov I've launched chrome.exe through bash on WSL and been able to submit a form with a populated file input. Do you have any further suggestions?

![image](https://user-images.githubusercontent.com/6085782/68044167-b44e3e80-fcce-11e9-8deb-fd476b72f06c.png)
