### ISSUE TITLE
Cant install on ubuntu 16.04.5 

### ISSUE THREAD

**Issue by pcbimon** [puppeteer/puppeteer#4332]
In my project first time to install on ubuntu server and use  [svg-to-img](https://www.npmjs.com/package/svg-to-img) A node.js library to convert SVGs to images built with Puppeteer.
Try it run 
`npm i --save`

Result
```
> puppeteer@1.1.1 install /home/mussp/mu-ssp/mu-ssp-server/node_modules/puppeteer
> node install.js

ERROR: Failed to download Chromium r536395! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: Client network socket disconnected before secure TLS connection was established
    at TLSSocket.onConnectEnd (_tls_wrap.js:1088:19)
    at Object.onceWrapper (events.js:277:13)
    at TLSSocket.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  code: 'ECONNRESET',
  path: undefined,
  host: 'my-proxy.domain',
  port: 8080,
  localAddress: undefined }
npm WARN mu-ssp-server@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.1.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@1.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

Sorry for Bad in English. Please help.

**Comment by pcbimon** [comment]
I had set http_proxy,https_proxy already.

I can install all package except this package.

**Comment by pcbimon** [comment]
Solved. My proxy blocked [this web](https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2F536395%2Fchrome-linux.zip?generation=1518543028548075&alt=media ) . I downloaded this file and unzip in `node_modules/puppeteer/.local-chromium/linux-536395` and set config in NPM by this command
`npm config set puppeteer_skip_chromium_download true -g`
