### ISSUE TITLE
How to change element attribute with variable

### ISSUE THREAD

**Issue by backtracker** [puppeteer/puppeteer#4376]
Use the following code,I can change element data-page arrribute to 100。
`await page.$eval(' div.panel-footer > div > div > ul > li:nth-child(3) > a ',e => e.setAttribute("data-page","100"));`

But if I change 100 to a variable, like this ,it will report a error

`var currentPageNo = "100"
await page.$eval(' div.panel-footer > div > div > ul > li:nth-child(3) > a ',e => e.setAttribute("data-page",currentPageNo ));
`

`node:4780) UnhandledPromiseRejectionWarning: Error: Evaluation failed: ReferenceError: currentPageNo is not defined
    at __puppeteer_evaluation_script__:1:20
    at ExecutionContext.evaluateHandle (\node_modules\puppeteer\lib\ExecutionContext.js:121:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (\node_modules\puppeteer\lib\helper.js:108:27)
    at ExecutionContext.evaluate (\node_modules\puppeteer\lib\ExecutionContext.js:48:31)
    at ExecutionContext.<anonymous> (\node_modules\puppeteer\lib\helper.js:109:23)
    at ElementHandle.$eval (\node_modules\puppeteer\lib\JSHandle.js:419:50)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at ElementHandle.<anonymous> (\node_modules\puppeteer\lib\helper.js:108:27)
    at DOMWorld.$eval (\node_modules\puppeteer\lib\DOMWorld.js:149:21)
  -- ASYNC --
    at Frame.<anonymous> (\node_modules\puppeteer\lib\helper.js:108:27)
    at Page.$eval (\node_modules\puppeteer\lib\Page.js:329:29)
    at Page.<anonymous> (\node_modules\puppeteer\lib\helper.js:109:23)
    at Object.switchToCurrentPageByClick (\functions\sh_common.js:43:23)
(node:4780) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4780) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by vsemozhetbyt** [comment]
Variables from Node.js context are not available in the browser context, you need to transfer them via arguments:
```js
var currentPageNo = "100"
await page.$eval(
  'div.panel-footer > div > div > ul > li:nth-child(3) > a',
  (e, no) => e.setAttribute("data-page", no),
  currentPageNo
);
```
