### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1):

### ISSUE THREAD

**Issue by MikinjMistry** [puppeteer/puppeteer#4399]
Getting below error when I used **await response.json();** in code

(node:7636) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: Unexpected end of JSON input
(node:7636) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are
not handled will terminate the Node.js process with a non-zero exit code.
(node:7636) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): SyntaxError: Unexpected end of JSON input

```
page.on('response', async (response) => {
	   if (response['_url'].indexOf('api-gtm.grubhub.com/restaurants/' + resId) !== -1) {
		const data = await response.json();
		await browser.close();
		const DbRes = await RestaurantHelpers.create(convertJson(data));
		res.json(DbRes);
	}
});
```

**Comment by MikinjMistry** [comment]
I have changed the code like this.
```
page.on('response', async (response) => {
                    if (response['_url'].indexOf('api-gtm.grubhub.com/restaurants/' + resId) !== -1) {
                        try {
                            const data = await response.json();
                            await browser.close();
                            const DbRes = await RestaurantHelpers.create(convertJson(data));
                            res.json(DbRes);
                        } catch (e) {
                            console.log(e);
                        }
                    }
                });
```

After change code, I am getting below error in the catch block

```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Response.json (F:\Upwork Client\Ayush\webapp\node_modules\puppeteer\lib\NetworkManager.js:639:17)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  -- ASYNC --
    at Response.<anonymous> (F:\Upwork Client\Ayush\webapp\node_modules\puppeteer\lib\helper.js:110:27)
    at Object.<anonymous> (F:\Upwork Client\Ayush\webapp\server\lib\routes\admin\restaurant\routes.js:268:79)
    at step (F:\Upwork Client\Ayush\webapp\server\lib\routes\admin\restaurant\routes.js:32:23)
    at Object.next (F:\Upwork Client\Ayush\webapp\server\lib\routes\admin\restaurant\routes.js:13:53)
    at F:\Upwork Client\Ayush\webapp\server\lib\routes\admin\restaurant\routes.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (F:\Upwork Client\Ayush\webapp\server\lib\routes\admin\restaurant\routes.js:3:12)
    at Page.<anonymous> (F:\Upwork Client\Ayush\webapp\server\lib\routes\admin\restaurant\routes.js:259:82)
    at emitOne (events.js:116:13)
    at Page.emit (events.js:211:7)
    at NetworkManager.Page.networkManager.on.event (F:\Upwork Client\Ayush\webapp\node_modules\puppeteer\lib\Page.js:115:69)
    at emitOne (events.js:116:13)
    at NetworkManager.emit (events.js:211:7)
    at NetworkManager._onResponseReceived (F:\Upwork Client\Ayush\webapp\node_modules\puppeteer\lib\NetworkManager.js:278:10)
    at emitOne (events.js:116:13)
    at CDPSession.emit (events.js:211:7)
```

Any suggesion to solve this issue
