### ISSUE TITLE
Can't use getDisplayMedia (and then start recording) in headless mode

### ISSUE THREAD

**Issue by tskirby** [puppeteer/puppeteer#4404]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.15.0
* Platform / OS version: Ubuntu 16.04
* URLs (if applicable):
* Node.js version: v10.15.3

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Run the following code, set headless to `true` or `false` and see the difference.
```
const puppeteer = require('puppeteer')

;(async () => {
  const url = 'https://www.google.com'
  const browser = await puppeteer.launch({
    headless: false,
    args: [
      `--window-size=1920,1080`,
      '--enable-experimental-web-platform-features',
      '--disable-infobars',
      '--enable-usermedia-screen-capturing',
      '--allow-http-screen-capture',
      '--auto-select-desktop-capture-source=webclip',
      '--ignore-certificate-errors', 
       '--unsafely-treat-insecure-origin-as-secure=' + url
    ]
  });
  const page = await browser.newPage()
  await page.setViewport({
    width: 1920,
    height: 1080,
  })
  await page.goto(url)
  page.evaluate(async () => {
    document.title = 'webclip'
    const stream = await navigator.mediaDevices.getDisplayMedia({ video: true })
    const recorder = new window.MediaRecorder(stream, { mimeType: 'video/webm' })
    recorder.start(10)
    const chunks = []
    recorder.addEventListener('dataavailable', event => {
      if (event.data && event.data.size) {
        chunks.push(event.data)
      }
    })
  })
})()
```
**What is the expected result?**
Maybe it should start recording (I don't know whether this behavior is intended and I haven't found percisely related information).

**What happens instead?**
Throw exceptions.

**Comment by jericizon** [comment]
+1

**Comment by tomardern** [comment]
I've just tried this now and get this error:
```
(node:87845) UnhandledPromiseRejectionWarning: Error: Evaluation failed: DOMException: Not supported
    at ExecutionContext._evaluateInternal (node_modules/puppeteer/lib/ExecutionContext.js:122:13)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async ExecutionContext.evaluate (node_modules/puppeteer/lib/ExecutionContext.js:48:12)
    at async index.js:24:3
  -- ASYNC --
    at ExecutionContext.<anonymous> (node_modules/puppeteer/lib/helper.js:111:15)
    at DOMWorld.evaluate (node_modules/puppeteer/lib/DOMWorld.js:112:20)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
  -- ASYNC --
    at Frame.<anonymous> (node_modules/puppeteer/lib/helper.js:111:15)
    at Page.evaluate (node_modules/puppeteer/lib/Page.js:860:43)
    at Page.<anonymous> (node_modules/puppeteer/lib/helper.js:112:23)
    at index.js:24:14
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

**Comment by Kashuab** [comment]
Need this in order to record sessions for failed tests in my CI pipeline.

**Comment by jkbpvsc** [comment]
Any updates on this?

**Comment by crisdosaygo** [comment]
Blanket silence on these issues related to WebRTC getDisplayMedia in headless, and zero answers on the web. Maybe the chrome team is working on something here in secret and they have "nothing to announce at this stage"?🤣

**Comment by crisdosaygo** [comment]
Go star the CRBUG 

https://bugs.chromium.org/p/chromium/issues/detail?id=1195881&q=Headless%20%20getDisplayMedia&can=2

**Comment by ldenoue** [comment]
any update on this? getDisplayMedia generates much better streams that using Page.startScreencast for me (higher FPS too). Can it work headless now?

**Comment by crisdosaygo** [comment]
@ldenoue no. pretty much likely that it can't. The bug I linked above is now assigned to caseq@chromium.org

Go star the issue and spread the world to show it's important. That contributes to the Chrome team's decisions about what to work on next.

**Comment by guest271314** [comment]
On Linux the error appears to be at https://source.chromium.org/chromium/chromium/src/+/main:third_party/webrtc/modules/desktop_capture/linux/x_server_pixel_buffer.cc;drc=cec4343fb42ddfea6063aa5b88968c4ff2bedcf8;l=202

`[0911/102515.901344:WARNING:x_server_pixel_buffer.cc(202)] Failed to get icc profile`

```
bool XServerPixelBuffer::Init(XAtomCache* cache, Window window) {
  Release();
  display_ = cache->display();

  XWindowAttributes attributes;
  if (!GetWindowRect(display_, window, &window_rect_, &attributes)) {
    return false;
  }

  if (cache->IccProfile() != None) {
    // `window` is the root window when doing screen capture.
    XWindowProperty<uint8_t> icc_profile_property(cache->display(), window,
                                                  cache->IccProfile());
    if (icc_profile_property.is_valid() && icc_profile_property.size() > 0) {
      icc_profile_ = std::vector<uint8_t>(
          icc_profile_property.data(),
          icc_profile_property.data() + icc_profile_property.size());
    } else {
      RTC_LOG(LS_WARNING) << "Failed to get icc profile";
    }
  }

  window_ = window;
  InitShm(attributes);

  return true;
}
```

**Comment by thegiantbeast** [comment]
Just in case someone might miss this, the new CRBUG is: https://bugs.chromium.org/p/chromium/issues/detail?id=1268342

This should be fixed because having to run the full chrome instance because of `getDisplayMedia` isn't the kind of behaviour I would expect from the headless mode 🤔

**Comment by guest271314** [comment]
@thegiantbeast Chromium developers banned me from their group and deleted my comment on that issue.

Of course users expect for `getDisplayMedia()` to work in headless mode. FWIW this plays audio in headless mode using an extension to launch headless https://github.com/guest271314/sw-extension-audio. 

Given `getDisplayMedia()` emits `mute` events when no user activity occurs on the document for "Tab" capture https://github.com/w3c/mediacapture-screen-share/issues/141 I would suggest using shell scripts or other means to capture the display surface for the specific requirement, insteado f waiting around for Chromium authors to see the use cases as you do.

**Comment by y-yagi** [comment]
I've confirmed this issue still exists.
