### ISSUE TITLE
Interception timeout when responding empty body

### ISSUE THREAD

**Issue by jinjor** [puppeteer/puppeteer#4408]
Simply responding empty body (`""`) causes the timeout error. It seems to require at least one character (e.g. `" "`).

### Steps to reproduce

* Puppeteer version: 1.15.0
* Platform / OS version: macOS 10.14.4
* Node.js version: v10.15.3

**What steps will reproduce the problem?**

```javascript
const puppeteer = require("puppeteer");

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.setRequestInterception(true);
  page.on("request", async request => {
    await request.respond({
      status: 200,
      contentType: "text/plain",
      body: "" // <------
    });
  });
  await page.goto("https://example.com");
  await browser.close();
})();
```

**What is the expected result?**

Done with no error.

**What happens instead?**

Raises TimeoutError.
```
(node:35254) UnhandledPromiseRejectionWarning: TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (/Users/jinjor/Projects/actcast/webui/node_modules/puppeteer/lib/LifecycleWatcher.js:142:21)
  -- ASYNC --
    at Frame.<anonymous> (/Users/jinjor/Projects/actcast/webui/node_modules/puppeteer/lib/helper.js:110:27)
    at Page.goto (/Users/jinjor/Projects/actcast/webui/node_modules/puppeteer/lib/Page.js:629:49)
    at Page.<anonymous> (/Users/jinjor/Projects/actcast/webui/node_modules/puppeteer/lib/helper.js:111:23)
    at /Users/jinjor/Projects/actcast/webui/tests/ts/sscce.js:14:14
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:35254) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:35254) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by lukaszfiszer** [comment]
A workaround for this issue it to pass a Buffer instead of string:

```
  page.on("request", async request => {
    await request.respond({
      status: 200,
      contentType: "text/plain",
      body: Buffer.from("") // <------
    });
  });
```
