### ISSUE TITLE
Problem installing on Linux Mint

### ISSUE THREAD

**Issue by NL66278** [puppeteer/puppeteer#4412]
I try to install mermaid. clli on Linux mint, this fails because puppeteer install fails due apparently to an error in install.js (line 78):
```
> puppeteer@1.15.0 install /usr/local/lib/node_modules/mermaid.cli/node_modules/puppeteer
> node install.js

/usr/local/lib/node_modules/mermaid.cli/node_modules/puppeteer/install.js:78
  return Promise.all([...cleanupOldVersions, generateProtocolTypesIfNecessary(true /* updated */)]);
                      ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
/usr/local/lib
└── (empty)

npm ERR! Linux 4.15.0-47-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "mermaid.cli"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! puppeteer@1.15.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@1.15.0 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the puppeteer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs puppeteer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls puppeteer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/openeyedev/npm-debug.log
npm ERR! code 1
```

**Comment by Yokutto** [comment]
In your NPM log I see this:
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! node v4.2.6
> npm ERR! npm  v3.5.2

Puppeteer requires at least Node v6.4.0.
Please run this code to upgrade your NPM & NodeJS packages:
```bash 
sudo apt-get update && sudo apt-get install -y nodejs npm && nodejs -v && npm -v
```

Best;

**Comment by NL66278** [comment]
@Yokutto Thanks for your reply! I was finally able to get everything working after updating as you suggested the packages. 

I had to use this command first to get a newer version then in my default OS packages:
```curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -```

**Comment by chawk** [comment]
Updating the node source via the above worked when nothing else did.   I'm on Ubuntu 16.04.
