### ISSUE TITLE
Fails to install on Windows with Node 8.3.0

### ISSUE THREAD

**Issue by NigelThorne** [puppeteer/puppeteer#442]
```
npm install -g node

> node@8.3.0 preinstall C:\Users\Nigel\AppData\Roaming\npm\node_modules\node
> node installArchSpecificPackage

npm WARN invalid config loglevel="notice"
npm WARN node@8.3.0 No repository field.

+ node-win-x64@8.3.0
added 1 package in 30.144s
C:\Users\Nigel\AppData\Roaming\npm\node -> C:\Users\Nigel\AppData\Roaming\npm\node_modules\node\bin\node
+ node@8.3.0
added 2 packages in 33.293s

C:\Users\Nigel
λ npm install -g puppeteer

> puppeteer@0.9.0 install C:\Users\Nigel\AppData\Roaming\npm\node_modules\puppeteer
> node install.js

C:\Users\Nigel\AppData\Roaming\npm\node_modules\puppeteer\utils\ChromiumDownloader.js:89
  downloadRevision: async function(platform, revision, progressCallback) {
                          ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Nigel\AppData\Roaming\npm\node_modules\puppeteer\install.js:17:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@0.9.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@0.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Nigel\AppData\Roaming\npm-cache\_logs\2017-08-21T10_39_20_234Z-debug.log
```

**Comment by vsemozhetbyt** [comment]
I suspect you have two Node.js: the old one (otherwise npm would not work to install new Node.js) and the v8.3.0. It seems the old one still presents in the PATH, is used for installing puppeteer and does not support async/await.
Try to run `node -v` to be sure you use v8.3.0 by default.

**Comment by NigelThorne** [comment]
You got it in one. Yep. Added new node to path and everything works fine.  Thanks.
