### ISSUE TITLE
Evaluation failed: TypeError: $ is not a function

### ISSUE THREAD

**Issue by ahmedeldeeb25-zz** [puppeteer/puppeteer#4477]
Every Thing was working fine for 2 month , but now I have this exception despite  I didn't make any changes in the code 

```
Error: Evaluation failed: TypeError: $ is not a function
    at __puppeteer_evaluation_script__:3:35
    at ExecutionContext.evaluateHandle (/home/ahmedeldeeb/git/luminairemaster/node_modules/puppeteer/lib/ExecutionContext.js:124:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/home/ahmedeldeeb/git/luminairemaster/node_modules/puppeteer/lib/helper.js:144:27)
    at ExecutionContext.evaluate (/home/ahmedeldeeb/git/luminairemaster/node_modules/puppeteer/lib/ExecutionContext.js:58:31)
    at ExecutionContext.<anonymous> (/home/ahmedeldeeb/git/luminairemaster/node_modules/puppeteer/lib/helper.js:145:23)
    at Frame.evaluate (/home/ahmedeldeeb/git/luminairemaster/node_modules/puppeteer/lib/FrameManager.js:447:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  -- ASYNC --
    at Frame.<anonymous> (/home/ahmedeldeeb/git/luminairemaster/node_modules/puppeteer/lib/helper.js:144:27)
    at Page.evaluate (/home/ahmedeldeeb/git/luminairemaster/node_modules/puppeteer/lib/Page.js:777:43)
    at Page.<anonymous> (/home/ahmedeldeeb/git/luminairemaster/node_modules/puppeteer/lib/helper.js:145:23)
    at PuppeteerCrawler.handlePageFunction (/home/ahmedeldeeb/git/luminairemaster/utils/updateWebsite.js:124:51)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)



```

**Comment by lexdorf-17** [comment]
@ahmedeldeeb25 use should try to use try and catch, in my case

i use whatsapp bot and i found the error like that, but i try to fixed like this

 

> async sendMessage(chatId, message) {
>         try {
>             await this.pupPage.evaluate((chatId, message) => {
>                 Store.SendMessage(Store.Chat.get(chatId), message);
>             }, chatId, message)
>         } catch (error) {
>             throw new Error('NOT IMPLEMENTED')
>         }
>     }

and it solved for me

**Comment by aslushnikov** [comment]
@ahmedeldeeb25 it looks like the website you automate doesn't expose the `$` function any more. It's hard to say anything specific without more details though.

**Comment by jevillC4** [comment]
> @ahmedeldeeb25 use should try to use try and catch, in my case
> 
> i use whatsapp bot and i found the error like that, but i try to fixed like this
> 
> > async sendMessage(chatId, message) {
> > try {
> > await this.pupPage.evaluate((chatId, message) => {
> > Store.SendMessage(Store.Chat.get(chatId), message);
> > }, chatId, message)
> > } catch (error) {
> > throw new Error('NOT IMPLEMENTED')
> > }
> > }
> 
> and it solved for me

This works, wrap in a try-catch.

**Comment by aminrazavi78** [comment]
with try catch, just your server don't terminate and also you have error
