### ISSUE TITLE
page.goto TimeoutError

### ISSUE THREAD

**Issue by nathagey** [puppeteer/puppeteer#4487]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: `1.17.0`
* Platform / OS version: `Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-78-generic x86_64)`
* URL: `https://test.environment.app.io` (accessible through VPN)
* Node.js version: `8.16.0`

**What steps will reproduce the problem?**

I see the expected result when I run the following from a local VM, and when I change the URL to something public. It fails when I run it from a remote machine serving https://test.environment.app.io.

```
const puppeteer = require('puppeteer');

(async() => {
  const browser = await puppeteer.launch()
  const page = await browser.newPage()
  console.log('goto start...')
  await page.goto('https://test.environment.app.io')
  console.log('this never happens')
  browser.close();
})();
```

**What is the expected result?**

```
goto start...
this never happens
```

**What happens instead?**

```
goto start...
```

Debugging output:

```
  puppeteer:protocol SEND ► {"method":"Target.setDiscoverTargets","params":{"discover":true},"id":1} +0ms
  puppeteer:protocol ◀ RECV {"method":"Target.targetCreated","params":{"targetInfo":{"targetId":"27e84178-884d-486a-9bf1-ae6b2258fb9a","type":"browser","title":"","url":"","attached":true}}} +4ms
  puppeteer:protocol ◀ RECV {"method":"Target.targetCreated","params":{"targetInfo":{"targetId":"91199247C245BF770F9DB636AEE1C45F","type":"page","title":"","url":"about:blank","attached":false,"browserContextId":"0F491EB89352A36D1DE9C93953B6BA23"}}} +1ms
  puppeteer:protocol ◀ RECV {"method":"Target.targetCreated","params":{"targetInfo":{"targetId":"befc1bcd-6d84-4b37-8466-2951e59872c8","type":"browser","title":"","url":"","attached":false}}} +1ms
  puppeteer:protocol ◀ RECV {"id":1,"result":{}} +0ms
  puppeteer:protocol ◀ RECV {"method":"Target.targetInfoChanged","params":{"targetInfo":{"targetId":"91199247C245BF770F9DB636AEE1C45F","type":"page","title":"about:blank","url":"about:blank","attached":false,"browserContextId":"0F491EB89352A36D1DE9C93953B6BA23"}}} +0ms
  puppeteer:protocol SEND ► {"method":"Target.createTarget","params":{"url":"about:blank"},"id":2} +2ms
  puppeteer:protocol ◀ RECV {"method":"Target.targetCreated","params":{"targetInfo":{"targetId":"62B1A10C7C2525B37E79D0E6BD16A8D2","type":"page","title":"","url":"","attached":false,"browserContextId":"0F491EB89352A36D1DE9C93953B6BA23"}}} +2ms
  puppeteer:protocol ◀ RECV {"id":2,"result":{"targetId":"62B1A10C7C2525B37E79D0E6BD16A8D2"}} +1ms
  puppeteer:protocol ◀ RECV {"method":"Target.targetInfoChanged","params":{"targetInfo":{"targetId":"62B1A10C7C2525B37E79D0E6BD16A8D2","type":"page","title":"about:blank","url":"about:blank","attached":false,"browserContextId":"0F491EB89352A36D1DE9C93953B6BA23"}}} +19ms
  puppeteer:protocol SEND ► {"method":"Target.attachToTarget","params":{"targetId":"62B1A10C7C2525B37E79D0E6BD16A8D2","flatten":true},"id":3} +1ms
  puppeteer:protocol ◀ RECV {"method":"Target.targetInfoChanged","params":{"targetInfo":{"targetId":"62B1A10C7C2525B37E79D0E6BD16A8D2","type":"page","title":"about:blank","url":"about:blank","attached":true,"browserContextId":"0F491EB89352A36D1DE9C93953B6BA23"}}} +1ms
  puppeteer:protocol ◀ RECV {"method":"Target.attachedToTarget","params":{"sessionId":"696FBFB7F366DC9B71B643E410B1119F","targetInfo":{"targetId":"62B1A10C7C2525B37E79D0E6BD16A8D2","type":"page","title":"about:blank","url":"about:blank","attached":true,"browserContextId":"0F491EB89352A36D1DE9C93953B6BA23"},"waitingForDebugger":false}} +0ms
  puppeteer:protocol ◀ RECV {"id":3,"result":{"sessionId":"696FBFB7F366DC9B71B643E410B1119F"}} +1ms
  puppeteer:protocol SEND ► {"sessionId":"696FBFB7F366DC9B71B643E410B1119F","method":"Page.enable","params":{},"id":4} +2ms
  puppeteer:protocol SEND ► {"sessionId":"696FBFB7F366DC9B71B643E410B1119F","method":"Page.getFrameTree","params":{},"id":5} +1ms
  puppeteer:protocol SEND ► {"sessionId":"696FBFB7F366DC9B71B643E410B1119F","method":"Target.setAutoAttach","params":{"autoAttach":true,"waitForDebuggerOnStart":false,"flatten":true},"id":6} +0ms
  puppeteer:protocol SEND ► {"sessionId":"696FBFB7F366DC9B71B643E410B1119F","method":"Performance.enable","params":{},"id":7} +1ms
  puppeteer:protocol SEND ► {"sessionId":"696FBFB7F366DC9B71B643E410B1119F","method":"Log.enable","params":{},"id":8} +0ms
  puppeteer:protocol ◀ RECV {"id":4,"result":{},"sessionId":"696FBFB7F366DC9B71B643E410B1119F"} +21ms
  puppeteer:protocol ◀ RECV {"id":5,"result":{"frameTree":{"frame":{"id":"62B1A10C7C2525B37E79D0E6BD16A8D2","loaderId":"E4E7BA6B633033B0F37E3AFBE78403BE","url":"about:blank","securityOrigin":"://","mimeType":"text/html"}}},"sessionId":"696FBFB7F366DC9B71B643E410B1119F"} +0ms
  puppeteer:protocol ◀ RECV {"id":6,"result":{},"sessionId":"696FBFB7F366DC9B71B643E410B1119F"} +0ms
  puppeteer:protocol ◀ RECV {"id":7,"result":{},"sessionId":"696FBFB7F366DC9B71B643E410B1119F"} +0ms
  puppeteer:protocol ◀ RECV {"id":8,"result":{},"sessionId":"696FBFB7F366DC9B71B643E410B1119F"} +0ms
  puppeteer:protocol SEND ► {"sessionId":"696FBFB7F366DC9B71B643E410B1119F","method":"Page.setLifecycleEventsEnabled","params":{"enabled":true},"id":9} +1ms
  puppeteer:protocol SEND ► {"sessionId":"696FBFB7F366DC9B71B643E410B1119F","method":"Runtime.enable","params":{},"id":10} +0ms
  puppeteer:protocol SEND ► {"sessionId":"696FBFB7F366DC9B71B643E410B1119F","method":"Network.enable","params":{},"id":11} +0ms
  puppeteer:protocol ◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"62B1A10C7C2525B37E79D0E6BD16A8D2","loaderId":"E4E7BA6B633033B0F37E3AFBE78403BE","name":"commit","timestamp":4305540.171712},"sessionId":"696FBFB7F366DC9B71B643E410B1119F"} +0ms
  puppeteer:protocol ◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"62B1A10C7C2525B37E79D0E6BD16A8D2","loaderId":"E4E7BA6B633033B0F37E3AFBE78403BE","name":"DOMContentLoaded","timestamp":4305540.171748},"sessionId":"696FBFB7F366DC9B71B643E410B1119F"} +1ms
  puppeteer:protocol ◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"62B1A10C7C2525B37E79D0E6BD16A8D2","loaderId":"E4E7BA6B633033B0F37E3AFBE78403BE","name":"load","timestamp":4305540.171848},"sessionId":"696FBFB7F366DC9B71B643E410B1119F"} +0ms
  puppeteer:protocol ◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"62B1A10C7C2525B37E79D0E6BD16A8D2","loaderId":"E4E7BA6B633033B0F37E3AFBE78403BE","name":"networkAlmostIdle","timestamp":4305540.172216},"sessionId":"696FBFB7F366DC9B71B643E410B1119F"} +0ms
  puppeteer:protocol ◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"62B1A10C7C2525B37E79D0E6BD16A8D2","loaderId":"E4E7BA6B633033B0F37E3AFBE78403BE","name":"networkIdle","timestamp":4305540.172216},"sessionId":"696FBFB7F366DC9B71B643E410B1119F"} +0ms
  puppeteer:protocol ◀ RECV {"id":9,"result":{},"sessionId":"696FBFB7F366DC9B71B643E410B1119F"} +0ms
  puppeteer:protocol ◀ RECV {"method":"Runtime.executionContextCreated","params":{"context":{"id":1,"origin":"://","name":"","auxData":{"isDefault":true,"type":"default","frameId":"62B1A10C7C2525B37E79D0E6BD16A8D2"}}},"sessionId":"696FBFB7F366DC9B71B643E410B1119F"} +2ms
  puppeteer:protocol ◀ RECV {"id":10,"result":{},"sessionId":"696FBFB7F366DC9B71B643E410B1119F"} +0ms
  puppeteer:protocol ◀ RECV {"id":11,"result":{},"sessionId":"696FBFB7F366DC9B71B643E410B1119F"} +0ms
  puppeteer:protocol SEND ► {"sessionId":"696FBFB7F366DC9B71B643E410B1119F","method":"Page.addScriptToEvaluateOnNewDocument","params":{"source":"//# sourceURL=__puppeteer_evaluation_script__","worldName":"__puppeteer_utility_world__"},"id":12} +1ms
  puppeteer:protocol ◀ RECV {"id":12,"result":{"identifier":"1"},"sessionId":"696FBFB7F366DC9B71B643E410B1119F"} +0ms
  puppeteer:protocol SEND ► {"sessionId":"696FBFB7F366DC9B71B643E410B1119F","method":"Page.createIsolatedWorld","params":{"frameId":"62B1A10C7C2525B37E79D0E6BD16A8D2","grantUniveralAccess":true,"worldName":"__puppeteer_utility_world__"},"id":13} +0ms
  puppeteer:protocol ◀ RECV {"method":"Runtime.executionContextCreated","params":{"context":{"id":2,"origin":"","name":"__puppeteer_utility_world__","auxData":{"isDefault":false,"type":"isolated","frameId":"62B1A10C7C2525B37E79D0E6BD16A8D2"}}},"sessionId":"696FBFB7F366DC9B71B643E410B1119F"} +3ms
  puppeteer:protocol ◀ RECV {"id":13,"result":{"executionContextId":2},"sessionId":"696FBFB7F366DC9B71B643E410B1119F"} +0ms
  puppeteer:protocol SEND ► {"sessionId":"696FBFB7F366DC9B71B643E410B1119F","method":"Emulation.setDeviceMetricsOverride","params":{"mobile":false,"width":800,"height":600,"deviceScaleFactor":1,"screenOrientation":{"angle":0,"type":"portraitPrimary"}},"id":14} +0ms
  puppeteer:protocol SEND ► {"sessionId":"696FBFB7F366DC9B71B643E410B1119F","method":"Emulation.setTouchEmulationEnabled","params":{"enabled":false},"id":15} +1ms
  puppeteer:protocol ◀ RECV {"id":14,"result":{},"sessionId":"696FBFB7F366DC9B71B643E410B1119F"} +0ms
  puppeteer:protocol ◀ RECV {"id":15,"result":{},"sessionId":"696FBFB7F366DC9B71B643E410B1119F"} +0ms
goto start...
  puppeteer:protocol SEND ► {"sessionId":"696FBFB7F366DC9B71B643E410B1119F","method":"Page.navigate","params":{"url":"https://test.environment.app.io","frameId":"62B1A10C7C2525B37E79D0E6BD16A8D2"},"id":16} +2ms
  puppeteer:protocol ◀ RECV {"method":"Network.requestWillBeSent","params":{"requestId":"91D1AE470CEDCC640F0B7FAA888C1E3D","loaderId":"91D1AE470CEDCC640F0B7FAA888C1E3D","documentURL":"https://test.environment.app.io","request":{"url":"https://test.environment.app.io","method":"GET","headers":{"Upgrade-Insecure-Requests":"1","User-Agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/76.0.3803.0 Safari/537.36","Sec-Fetch-Mode":"navigate","Sec-Fetch-User":"?1"},"mixedContentType":"none","initialPriority":"VeryHigh","referrerPolicy":"no-referrer-when-downgrade"},"timestamp":4305540.212345,"wallTime":1559103395.764454,"initiator":{"type":"other"},"type":"Document","frameId":"62B1A10C7C2525B37E79D0E6BD16A8D2","hasUserGesture":false},"sessionId":"696FBFB7F366DC9B71B643E410B1119F"} +1ms
  puppeteer:protocol ◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"62B1A10C7C2525B37E79D0E6BD16A8D2","loaderId":"E4E7BA6B633033B0F37E3AFBE78403BE","name":"networkAlmostIdle","timestamp":4305540.172216},"sessionId":"696FBFB7F366DC9B71B643E410B1119F"} +2s
  puppeteer:protocol ◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"62B1A10C7C2525B37E79D0E6BD16A8D2","loaderId":"E4E7BA6B633033B0F37E3AFBE78403BE","name":"networkIdle","timestamp":4305540.172216},"sessionId":"696FBFB7F366DC9B71B643E410B1119F"} +0ms
  (node:15690) UnhandledPromiseRejectionWarning: TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (/mnt/encrypted/opt/awareai/ui/middle-tier/node_modules/puppeteer/lib/LifecycleWatcher.js:142:21)
    at <anonymous>
  -- ASYNC --
    at Frame.<anonymous> (/mnt/encrypted/opt/awareai/ui/middle-tier/node_modules/puppeteer/lib/helper.js:110:27)
    at Page.goto (/mnt/encrypted/opt/awareai/ui/middle-tier/node_modules/puppeteer/lib/Page.js:629:49)
    at Page.<anonymous> (/mnt/encrypted/opt/awareai/ui/middle-tier/node_modules/puppeteer/lib/helper.js:111:23)
    at /mnt/encrypted/opt/awareai/ui/middle-tier/pptr.js:15:14
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:15690) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15690) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by creazy231** [comment]
same problem here

**Comment by ps-mariotacke** [comment]
Can you add the content of `https://test.environment.app.io`?

**Comment by nathagey** [comment]
```
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="google-signin-client_id" content="***********.apps.googleusercontent.com" />
    <script src="https://apis.google.com/js/platform.js" async defer="defer"></script>
    <link rel="icon" type="image/x-icon" href="/assets/img/favicon.ico">
    <link href="/static/styles.afef7b673c8207163889.bundle.css" rel="stylesheet" />
</head>
<body>
    <app-root></app-root>
    <script type="text/javascript" src="/static/inline.543bce0cb8c11b77ede5.bundle.js"></script>
    <script type="text/javascript" src="/static/polyfills.ce28f81ac2baa0097d35.bundle.js"></script>
    <script type="text/javascript" src="/static/main.45ba71e4c20d4ae0d109.bundle.js"></script>
</body>
</html>
```

**Comment by nathagey** [comment]
This is not a puppeteer bug. My page.goto URL requires 2FA. The machine running puppeteer just did not have access.
