### ISSUE TITLE
Error: Chromium revision is not downloaded. Run "npm install" or "yarn install" 

### ISSUE THREAD

**Issue by zeeshanaligold** [puppeteer/puppeteer#4514]
Hi there,
I'm using chrome-aws-lambda with puppeteer-core & getting error. 
here is the reference link https://zeit.co/blog/serverless-chrome
![Screenshot from 2019-06-03 09-45-14](https://user-images.githubusercontent.com/26404433/58794011-af4a6d80-8610-11e9-87c2-b587e3cc0202.png)

Thanks,

**Comment by nastycoder** [comment]
Just ran into this same issue.

**Comment by aslushnikov** [comment]
@zeeshanaligold @nastycoder this happens because you run `puppeteer.launch` without a custom `executablePath`. Notice how zeit blogpost passes it in:

![image](https://user-images.githubusercontent.com/746130/59003124-90430b80-87c9-11e9-9112-22b56a27d3d1.png)

**Comment by nastycoder** [comment]
So the problem wasn't that line at all. Turns out `chrome.executablePath` was `null` because `chrome.headless` is falsy. In order to make it work for local testing purposes, you have to make sure one of these `['AWS_LAMBDA_FUNCTION_NAME', 'FUNCTION_NAME', 'FUNCTION_TARGET']` environment variables are set.

**Comment by aslushnikov** [comment]
@nastycoder thanks for coming back and explaining the root cause!

**Comment by zeeshanaligold** [comment]
@nastycoder thanks. Now getting this error 
```
{ Error: Cannot find module 'iltorb'
[0]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:591:27)
[0]     at Module.require (internal/modules/cjs/loader.js:723:19)
[0]     at require (internal/modules/cjs/helpers.js:14:16)
[0]     at inflate (/media/zeeshan/Local Disk(D)/gift-voucher/server/node_modules/chrome-aws-lambda/source/index.js:200:14)
[0]     at Function.get executablePath [as executablePath] (/media/zeeshan/Local Disk(D)/gift-voucher/server/node_modules/chrome-aws-lambda/source/index.js:159:7)
[0]     at executablePath (/media/zeeshan/Local Disk(D)/gift-voucher/server/.webpack/service/webpack:/src/utils/generatePdf.js:13:36)
[0]     at generate (/media/zeeshan/Local Disk(D)/gift-voucher/server/.webpack/service/webpack:/src/controllers/pdfController.js:8:14)
[0]     at Layer.handle [as handle_request] (/media/zeeshan/Local Disk(D)/gift-voucher/server/node_modules/express/lib/router/layer.js:95:5)
[0]     at next (/media/zeeshan/Local Disk(D)/gift-voucher/server/node_modules/express/lib/router/route.js:137:13)
[0]     at Route.dispatch (/media/zeeshan/Local Disk(D)/gift-voucher/server/node_modules/express/lib/router/route.js:112:3)
[0]     at Layer.handle [as handle_request] (/media/zeeshan/Local Disk(D)/gift-voucher/server/node_modules/express/lib/router/layer.js:95:5)
[0]     at /media/zeeshan/Local Disk(D)/gift-voucher/server/node_modules/express/lib/router/index.js:281:22
[0]     at Function.process_params (/media/zeeshan/Local Disk(D)/gift-voucher/server/node_modules/express/lib/router/index.js:335:12)
[0]     at next (/media/zeeshan/Local Disk(D)/gift-voucher/server/node_modules/express/lib/router/index.js:275:10)
[0]     at Function.handle (/media/zeeshan/Local Disk(D)/gift-voucher/server/node_modules/express/lib/router/index.js:174:3) code: 'MODULE_NOT_FOUND' }
```

**Comment by zeeshanaligold** [comment]
Hi guys,
    Issue has been fixed.  It was due to because i'm using AWS_Lambda_nodejs10.x. So that iltorb need to install manually. here is the logic that chrome-aws-lambda using.

`require(process.env.AWS_EXECUTION_ENV !== 'AWS_Lambda_nodejs8.10' ? 'iltorb' : ${__dirname}/iltorb)`


Thanks,

**Comment by AlessandroAnnini** [comment]
where can I find `AWS_LAMBDA_FUNCTION_NAME` or `FUNCTION_NAME` or `FUNCTION_TARGET` values? does anyone know values for zeit now?

**Comment by zeeshanaligold** [comment]
@AlessandroAnnini This might help you

https://github.com/alixaxel/chrome-aws-lambda/wiki/HOWTO:-Local-Development
