### ISSUE TITLE
request.continue() throws net::ERR_INVALID_ARGUMENT if change the url

### ISSUE THREAD

**Issue by jiangfengming** [puppeteer/puppeteer#4575]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:  1.17.0
* Platform / OS version: mac OS
* URLs (if applicable):
* Node.js version: 12.3.1

**What steps will reproduce the problem?**

```js
const puppeteer = require('puppeteer')

puppeteer.launch().then(async browser => {
  const page = await browser.newPage()
  await page.setRequestInterception(true)

  page.on('request', req => {
    let url = req.url()
    const headers = req.headers()

    url = url.replace('example.dev', 'example.com')
    headers.host = 'example.com'

    return req.continue({ url, headers })
  })

  await page.goto('https://example.dev')
  await browser.close()
})
```

**What is the expected result?**
No error. v1.16.0 is OK. Only v1.17.0 will throw the error.

**What happens instead?**

```log
(node:1543) UnhandledPromiseRejectionWarning: Error: net::ERR_INVALID_ARGUMENT at https://example.dev
    at navigate (/Users/fenix/projects/puppeteer-prerender/node_modules/.registry.npmjs.org/puppeteer/1.17.0/node_modules/puppeteer/lib/FrameManager.js:121:37)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
  -- ASYNC --
    at Frame.<anonymous> (/Users/fenix/projects/puppeteer-prerender/node_modules/.registry.npmjs.org/puppeteer/1.17.0/node_modules/puppeteer/lib/helper.js:110:27)
    at Page.goto (/Users/fenix/projects/puppeteer-prerender/node_modules/.registry.npmjs.org/puppeteer/1.17.0/node_modules/puppeteer/lib/Page.js:629:49)
    at Page.<anonymous> (/Users/fenix/projects/puppeteer-prerender/node_modules/.registry.npmjs.org/puppeteer/1.17.0/node_modules/puppeteer/lib/helper.js:111:23)
    at /Users/fenix/projects/puppeteer-prerender/examples/puppeteer-issue.js:17:14
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
(node:1543) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1543) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by wSpring** [comment]
I also encountered the same problem.

**Comment by aslushnikov** [comment]
Looks like Chromium now [prohibits setting "host" header](https://github.com/chromium/chromium/blob/b2254b38369f4f8ce8685b7a82dee1251f6cea22/services/network/url_loader.cc#L679-L683).

So if you simply remove overwriting the "host" header - things will work. Why do you want to overwrite "host" header?

**Comment by jiangfengming** [comment]
@aslushnikov Thank you. I thought I need to set the `host` header manually.

**Comment by imShara** [comment]
@jiangfengming How do you solve it?

**Comment by aolphn** [comment]
In android webview ,I solved it.
