### ISSUE TITLE
cant run on centos

### ISSUE THREAD

**Issue by sonyalsy** [puppeteer/puppeteer#4660]
The version I used is  **prerender-spa-plugin@3.4.0**

**I have installed dependencies and update nss library using this command**
`pango.x86_64
libXcomposite.x86_64
libXcursor.x86_64
libXdamage.x86_64
libXext.x86_64
libXi.x86_64
libXtst.x86_64
cups-libs.x86_64
libXScrnSaver.x86_64
libXrandr.x86_64
GConf2.x86_64
alsa-lib.x86_64
atk.x86_64
gtk3.x86_64
ipa-gothic-fonts
xorg-x11-fonts-100dpi
xorg-x11-fonts-75dpi
xorg-x11-utils
xorg-x11-fonts-cyrillic
xorg-x11-fonts-Type1
xorg-x11-fonts-misc`
and 
`
yum update nss -y
`

`Error: Failed to launch chrome!
/data/jenkins/workspace/Dev/dev-frontend-website-pipeline/node_modules/puppeteer/.local-chromium/linux-672088/chrome-linux/chrome: error while loading shared libraries: libXcomposite.so.1: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/data/jenkins/workspace/Dev/dev-frontend-website-pipeline/node_modules/puppeteer/lib/Launcher.js:340:14)
    at Interface.helper.addEventListener (/data/jenkins/workspace/Dev/dev-frontend-website-pipeline/node_modules/puppeteer/lib/Launcher.js:329:50)
    at Interface.emit (events.js:194:15)
    at Interface.close (readline.js:379:8)
    at Socket.onend (readline.js:157:10)
    at Socket.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[Prerenderer - PuppeteerRenderer] Unable to start Puppeteer
(node:13209) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'close' of null
    at PuppeteerRenderer.destroy (/data/jenkins/workspace/Dev/dev-frontend-website-pipeline/node_modules/@prerenderer/renderer-puppeteer/es6/renderer.js:140:21)
    at Prerenderer.destroy (/data/jenkins/workspace/Dev/dev-frontend-website-pipeline/node_modules/@prerenderer/prerenderer/es6/index.js:87:20)`

**Comment by aslushnikov** [comment]
Please take a look at the discussion at #391
