### ISSUE TITLE
Navigation failed because browser disconnected in ci container

### ISSUE THREAD

**Issue by Kashio** [puppeteer/puppeteer#4679]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.18.1
* Platform / OS version: Debian
* URLs (if applicable): circleci image https://github.com/CircleCI-Public/circleci-dockerfiles/blob/master/python/images/3.7.3/node-browsers/Dockerfile
* Node.js version: 10.16.0

**What steps will reproduce the problem?**
1. Setup circleci / run docker with the provided image
2. Run tests in jest with jest-puppeteer and expect-puppeteer with the provided code

jest.config.js:
```
module.exports = {
    preset: 'jest-puppeteer',
    testMatch: [
        '**/tests/**/*.spec.js'
    ],
    reporters: ["default", "jest-junit"],
    setupFilesAfterEnv: ['./tests/screenshot.setup.js']
};
```

jest-puppeteer.config.js:
```
const testEnvironment = process.env.NODE_ENV === 'test';

let args = [];

if (testEnvironment) {
    args = ['--no-sandbox', '--disable-setuid-sandbox', '--start-maximized', '--lang=he-IL', '--font-render-hinting=medium'];
}

module.exports = {
    launch: {
        args,
        headless: testEnvironment,
    },
    browserContext: 'default'
};
```

screenshot.setup.js:
```
const path = require('path');
const mkdirp = require('mkdirp');
require('expect-puppeteer');

const screenshotsPath = path.resolve(__dirname, '../screenshots');

const cleanFileName = (fileName) => fileName.replace(/[^a-z0-9.-]+/ig, '_');

const takeScreenshot = (testName, page) => {
    mkdirp.sync(screenshotsPath);
    const filePath = path.join(
        screenshotsPath,
        cleanFileName(`${new Date().toISOString()}_${testName}.png`),
    );
    return page.screenshot({
        path: filePath
    });
};

const registerScreenshotReporter = () => {
    let screenshotPromise = Promise.resolve();
    beforeEach(() => screenshotPromise);
    afterAll(() => screenshotPromise);
    jasmine.getEnv().addReporter({
        specDone: async (result) => {
            if (result.status === 'failed') {
                screenshotPromise = screenshotPromise
                    .catch()
                    .then(() => takeScreenshot(result.fullName, page));
            }
        },
    });
};

registerScreenshotReporter();

module.exports = {
  registerScreenshotReporter
};
```

index.spec.js:
```
describe('Single Property', () => {
    beforeAll(async () => {
        await page.setViewport({width: 1366, height: 768});
        await page.goto('http://localhost:3000');
        await page.waitForNavigation({waitUntil: 'networkidle0'});
    });

    it('should be titled "Google"', async () => {
        const title = await page.title();
        console.log('PAGE TITLE: ', title);
        await expect(page.title()).resolves.toMatch('Google'); // Matching Google on purpose ..
    });
});
```

**What is the expected result?**
To fail on wrong title match

**What happens instead?**
Getting described error:
```
(node:1151) UnhandledPromiseRejectionWarning: Error: Navigation failed because browser has disconnected!
    at CDPSession.LifecycleWatcher._eventListeners.helper.addEventListener (/home/circleci/WaltyAutomation/node_modules/puppeteer/lib/LifecycleWatcher.js:46:107)
    at CDPSession.emit (events.js:198:13)
    at CDPSession._onClosed (/home/circleci/WaltyAutomation/node_modules/puppeteer/lib/Connection.js:215:10)
    at Connection._onMessage (/home/circleci/WaltyAutomation/node_modules/puppeteer/lib/Connection.js:105:17)
    at WebSocketTransport._ws.addEventListener.event (/home/circleci/WaltyAutomation/node_modules/puppeteer/lib/WebSocketTransport.js:44:24)
    at WebSocket.onMessage (/home/circleci/WaltyAutomation/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:198:13)
    at Receiver.receiverOnMessage (/home/circleci/WaltyAutomation/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:198:13)
    at Receiver.dataMessage (/home/circleci/WaltyAutomation/node_modules/ws/lib/receiver.js:422:14)
  -- ASYNC --
    at Frame.<anonymous> (/home/circleci/WaltyAutomation/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.goto (/home/circleci/WaltyAutomation/node_modules/puppeteer/lib/Page.js:629:49)
    at Page.<anonymous> (/home/circleci/WaltyAutomation/node_modules/puppeteer/lib/helper.js:112:23)
    at Object.goto (/home/circleci/WaltyAutomation/tests/flows/single-property/index.spec.js:4:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1151) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1151) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 FAIL  tests/flows/single-property/index.spec.js (10.165s)
  Single Property
    ✕ should be titled "Google" (4458ms)

  ● Single Property › should be titled "Google"

    Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:25:45)
```

**Comment by Kashio** [comment]
expect-puppeteer seems to be the issue probably some internal function not awaiting an async function.
I used normal expect and it worked fine.
Should work:
```
const title = await page.title();
expect(title).toBe('...');
```
