### ISSUE TITLE
What does net::ERR_TOO_MANY_RETRIES?

### ISSUE THREAD

**Issue by gajus** [puppeteer/puppeteer#4692]
```
Error: net::ERR_TOO_MANY_RETRIES at https://booking.[redacted].de/#/site/105/performance/DB3EF700023FWBXJYB/mode/sale/step/seating/
    at navigate (/srv/[redacted]/node_modules/puppeteer/lib/FrameManager.js:121:37)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
  -- ASYNC --
    at Frame.<anonymous> (/srv/[redacted]/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.goto (/srv/[redacted]/node_modules/puppeteer/lib/Page.js:629:49)
    at Page.<anonymous> (/srv/[redacted]/node_modules/puppeteer/lib/helper.js:112:23)
    at /srv/[redacted]/dist/countries/de/[redacted].js:154:16
    at createBrowserPage (/srv/[redacted]/dist/utilities.js:99:20)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async getForeignEvent (/srv/[redacted]/dist/countries/de/[redacted].js:153:18)
    at async Object.scrapeEvent (/srv/[redacted]/dist/countries/de/[redacted].js:241:24)
    at async scrapeEvent (/srv/node_modules/@applaudience/cinema-data-scraper/dist/scrapers.js:68:42)
    at async scrapeData (/srv/dist/routines/executeCinemaDataTask.js:89:18)
    at async runTaskBody (/srv/dist/routines/executeCinemaDataTask.js:378:29)

```

What does this error mean?

I cannot reliably replicate the issue. It appears to be intermittent. There isn't sufficient information to determine the underlying cause of the issue either.

**Comment by aslushnikov** [comment]
@gajus not an expert in network stack, but I can cite the [Chromium description](https://github.com/chromium/chromium/blob/966c0e95c915aba3b75eb432957cd421bac3ef86/net/base/net_error_list.h#L759-L763):

```
// An HTTP transaction was retried too many times due for authentication or
// invalid certificates. This may be due to a bug in the net stack that would
// otherwise infinite loop, or if the server or proxy continually requests fresh
// credentials or presents a fresh invalid certificate.
```

I can't say more than this; I'd recommend asking on chromium-dev if this doesn't shed enough light.
