### ISSUE TITLE
fail to install pupeteer

### ISSUE THREAD

**Issue by ehsan69h** [puppeteer/puppeteer#4737]
windows 10 64x
node 10.13
npm 6.4

> puppeteer@1.18.1 install G:\p\instagram bot\node_modules\puppeteer
> node install.js

ERROR: Failed to download Chromium r672088! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
Error: Download failed: server returned code 403. URL: https://storage.googleapis.com/chromium-browser-snapshots/Win_x64/672088/chrome-win.zip
    at response (G:\p\instagram bot\node_modules\puppeteer\lib\BrowserFetcher.js:232:21)
    at ClientRequest.requestCallback (G:\p\instagram bot\node_modules\puppeteer\lib\BrowserFetcher.js:297:7)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at HTTPParser.parserOnIncomingClient (_http_client.js:555:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:441:20)
    at TLSSocket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
  -- ASYNC --
    at BrowserFetcher.<anonymous> (G:\p\instagram bot\node_modules\puppeteer\lib\helper.js:111:15)
    at Object.<anonymous> (G:\p\instagram bot\node_modules\puppeteer\install.js:64:16)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
npm WARN instagram-bot@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.18.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@1.18.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by mandaputtra** [comment]
https://storage.googleapis.com/chromium-browser-snapshots/Win_x64/672088/chrome-win.zip

Try to access this if you get 403 then its network error.

**Comment by ehsan69h** [comment]
> https://storage.googleapis.com/chromium-browser-snapshots/Win_x64/672088/chrome-win.zip
> 
> Try to access this if you get 403 then its network error.
 
yes this is network error access denied! but how can i fix that?

**Comment by mandaputtra** [comment]
This issue are not related to puppeteer, you can close this issue.

403 mean your network refuse to download it (you dont had access), simply changing wifi or use VPN.
