### ISSUE TITLE
ERR_CONNECTION_REFUSED on connecting to a port again

### ISSUE THREAD

**Issue by rexagod** [puppeteer/puppeteer#4776]
Okay, so the code's actually pretty simple where this is occuring.
```js
await page.goto(`http://${envVars.HOST}:${envVars.PORT}/${envVars.SUB_PATH}`).catch(function(e) {
    console.error(e);
  });
```

What's strange is that puppeteer will connect to the live server for the first time but will throw an error,

```Error: net::ERR_CONNECTION_REFUSED at http://127.0.0.1:9996/demo/
    at navigate (/mnt/c/Users/Rexagod/cli/node_modules/puppeteer/lib/FrameManager.js:121:37)          at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  -- ASYNC --
    at Frame.<anonymous> (/mnt/c/Users/Rexagod/cli/node_modules/puppeteer/lib/helper.js:111:15)       at Page.goto (/mnt/c/Users/Rexagod/cli/node_modules/puppeteer/lib/Page.js:674:49)
    at Page.<anonymous> (/mnt/c/Users/Rexagod/cli/node_modules/puppeteer/lib/helper.js:112:23)        at invoke (/mnt/c/Users/Rexagod/cli/src/matcher-summon.js:53:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

for subsequent `goto` requests. I think it's worth mentioning that I've tried switching the host between "localhost" and "127.0.0.1" for any "mapping issues" as were seen in some similar issues, and using the `connect` api, but with no luck.

PS. I'm using the `'--no-sandbox', '--headless', '--disable-setuid-sandbox'` args to launch puppeteer.

Can anyone let me know what's up, and how can this be fixed?

Thanks!

**Comment by RacingTadpole** [comment]
In case it helps - I was getting the same error most (but not all) times I ran my puppeteer tests, and solved it by adding the `port` option to `jest-puppeteer.config.js`'s `server` object, as described in https://github.com/smooth-code/jest-puppeteer/issues/27#issuecomment-379068886. (Weirdly, an earlier solution I found by trial and error was to add `slowMo: 50` to the launch options.)
