### ISSUE TITLE
Useless question

### ISSUE THREAD

**Issue by erm100** [puppeteer/puppeteer#4795]
#4783

**Comment by erm100** [comment]
Nothing concrete.
``` 
{ Error: Protocol error (Page.setInterceptFileChooserDialog): 'Page.setInterceptFileChooserDialog' wasn't found
    at Promise (D:\socialmanagertools-igbot\node_modules\puppeteer\lib\Connection.js:185:56)
    at new Promise (<anonymous>)
    at CDPSession.send (D:\socialmanagertools-igbot\node_modules\puppeteer\lib\Connection.js:183:12)
    at Page._initialize (D:\socialmanagertools-igbot\node_modules\puppeteer\lib\Page.js:139:20)
    at Function.create (D:\socialmanagertools-igbot\node_modules\puppeteer\lib\Page.js:47:16)
    at _pagePromise._sessionFactory.then.client (D:\socialmanagertools-igbot\node_modules\puppeteer\lib\Target.js:75:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  message:
   'Protocol error (Page.setInterceptFileChooserDialog): \'Page.setInterceptFileChooserDialog\' wasn\'t found' }
```
