### ISSUE TITLE
Page.isClosed() result false , but page._client._connection is closed 

### ISSUE THREAD

**Issue by luoyjx** [puppeteer/puppeteer#4834]
I meet this error when our page timeout was exceeded ,  i will try to close this page after i check `page.isClosed()` but i think the result is false , so it will call the `page.close()`。

```
Error: Protocol error: Connection closed. Most likely the page has been closed.
    at assert (/data/node_modules/puppeteer-core/lib/helper.js:231:11)
    at Page.close (/data/node_modules/puppeteer-core/lib/Page.js:959:5)
    at Page.<anonymous> (/data/node_modules/puppeteer-core/lib/helper.js:111:23)
    at closePage (/data/lib/disposable_cdp.js:90:15)
    at Object.Bluebird.try.disposer (/data/lib/disposable_cdp.js:81:11)
    at FunctionDisposer.doDispose (/data/node_modules/bluebird/js/release/using.js:98:19)
    at FunctionDisposer.Disposer.tryDispose (/data/node_modules/bluebird/js/release/using.js:78:20)
    at iterator (/data/node_modules/bluebird/js/release/using.js:36:53)
    at dispose (/data/node_modules/bluebird/js/release/using.js:48:9)
    at /data/node_modules/bluebird/js/release/using.js:194:20
    at PassThroughHandlerContext.finallyHandler (/data/node_modules/bluebird/js/release/finally.js:56:23)
    at PassThroughHandlerContext.tryCatcher (/data/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/data/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/data/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/data/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/data/node_modules/bluebird/js/release/promise.js:695:18)
    at _drainQueueStep (/data/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/data/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/data/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/data/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
  -- ASYNC --
    at Page.<anonymous> (/data/node_modules/puppeteer-core/lib/helper.js:110:27)
    at closePage (/data/lib/disposable_cdp.js:90:15)
    at Object.Bluebird.try.disposer (/data/lib/disposable_cdp.js:81:11)
    at FunctionDisposer.doDispose (/data/node_modules/bluebird/js/release/using.js:98:19)
    at FunctionDisposer.Disposer.tryDispose (/data/node_modules/bluebird/js/release/using.js:78:20)
    at iterator (/data/node_modules/bluebird/js/release/using.js:36:53)
    at dispose (/data/node_modules/bluebird/js/release/using.js:48:9)
    at /data/node_modules/bluebird/js/release/using.js:194:20
    at PassThroughHandlerContext.finallyHandler (/data/node_modules/bluebird/js/release/finally.js:56:23)
    at PassThroughHandlerContext.tryCatcher (/data/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/data/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/data/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/data/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/data/node_modules/bluebird/js/release/promise.js:695:18)
    at _drainQueueStep (/data/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/data/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/data/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/data/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

My close page code below .

```
async function closePage (page) {
  if (
    !page ||
    (page && page.isClosed())
  ) {
    return
  }

  return page.close()
}
```

I can see there is an assertion before send close page command, but why did not `isClosed` function check the `page._client._connection` ?

https://github.com/GoogleChrome/puppeteer/blob/master/lib/Page.js#L1002

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: puppeteer-core@1.15.0
* Platform / OS version: docker / debian jessie
* URLs (if applicable):
* Node.js version: 8.9.4

**What steps will reproduce the problem?**

Cannot reproduce this currently.

**What is the expected result?**
Page.isClosed() return the correct result.

**What happens instead?**
Returned the incorrect result

**Comment by luoyjx** [comment]
Should i listen the `close` event of page instance either?

**Comment by luoyjx** [comment]
sorry, i realize that , `page.isClosed()` show the page state in chrome , but not the conneciton state, so it will not check `page._client._connection` . Before page closed , the `page._client._connection` close is unexpected, so puppeteer will throw an error  , is that right ?
