### ISSUE TITLE
Heroku spawn /app/node_modules/puppeteer/.local-chromium/linux-674921/chrome-linux/chrome EAGAIN

### ISSUE THREAD

**Issue by chrisdel101** [puppeteer/puppeteer#4895]
This is similar to another unresolved issue filed [here](https://github.com/GoogleChrome/puppeteer/issues/3749) dealing with the same issue
### Steps to reproduce
This only happens on my heroku dyno which runs Ubuntu. The same exact code works locally on mac OS so this is hard to reproduce.

To reproduce would be to clone this repo and deploy it to heroku with the [puppeteer build-pack](https://elements.heroku.com/buildpacks/jontewks/puppeteer-heroku-buildpack): https://github.com/chrisdel101/f1-web
( I'm working on getting a better way to reproduce than this. I tried making a test deployment but so far it didn't reproduce.)
**Tell us about your environment:**

* Puppeteer version: 1.19.0
* Platform / OS version: Ubuntu 14.04
* Node.js version: v10.16.3 

**What steps will reproduce the problem?**
- Deploy the app
- curl {url-for-your-app}/api/driver/lewis-hamilton
- check logs

**What is the expected result?**
That puppeteer should execute and snap an image of the html. This works as expected locally.

**What happens instead?**
```
An error occured in takeImage: TypeError: input.on is not a function
2019-09-01T18:25:27.110383+00:00 app[web.1]: at new Interface (readline.js:207:11)
2019-09-01T18:25:27.110386+00:00 app[web.1]: at Object.createInterface (readline.js:75:10)
2019-09-01T18:25:27.110388+00:00 app[web.1]: at Promise (/app/node_modules/puppeteer/lib/Launcher.js:334:25)
2019-09-01T18:25:27.110390+00:00 app[web.1]: at new Promise (<anonymous>)
2019-09-01T18:25:27.110392+00:00 app[web.1]: at waitForWSEndpoint (/app/node_modules/puppeteer/lib/Launcher.js:333:10)
2019-09-01T18:25:27.110394+00:00 app[web.1]: at Launcher.launch (/app/node_modules/puppeteer/lib/Launcher.js:177:41)
2019-09-01T18:25:27.113233+00:00 app[web.1]: GET /api/driver/lewis-hamilton - 10ms
2019-09-01T18:25:27.153445+00:00 app[web.1]: events.js:174
2019-09-01T18:25:27.153450+00:00 app[web.1]: throw er; // Unhandled 'error' event
2019-09-01T18:25:27.153452+00:00 app[web.1]: ^
2019-09-01T18:25:27.153454+00:00 app[web.1]: 
2019-09-01T18:25:27.153456+00:00 app[web.1]: Error: spawn /app/node_modules/puppeteer/.local-chromium/linux-674921/chrome-linux/chrome EAGAIN
2019-09-01T18:25:27.153458+00:00 app[web.1]: at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
2019-09-01T18:25:27.153463+00:00 app[web.1]: at onErrorNT (internal/child_process.js:415:16)
2019-09-01T18:25:27.153465+00:00 app[web.1]: at process._tickCallback (internal/process/next_tick.js:63:19)
2019-09-01T18:25:27.153468+00:00 app[web.1]: Emitted 'error' event at:
2019-09-01T18:25:27.153470+00:00 app[web.1]: at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
2019-09-01T18:25:27.153472+00:00 app[web.1]: at onErrorNT (internal/child_process.js:415:16)
2019-09-01T18:25:27.153474+00:00 app[web.1]: at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by chrisdel101** [comment]
The code used to snap an image with puppeteer was in its own file. The only solution I've been able to find so far is to move the puppeteer code into the same file that calls the route that triggers it (in Koa). Both of these work locally but not on Heroku.

Does not work. 2 separate files:
```
//func.js
exports.takeImage = async (ctx) => {
   const browser = await puppeteer.launch(
   {args: ['--no-sandbox', '--disable-setuid-sandbox']}
  );
  const page = await browser.newPage();
  await page.goto('https://example.com');
  await page.screenshot({path: 'example.png'});
  await browser.close()
  ctx.type = `image/png`
  return fs.createReadStream('./example.png')
}

//index.js
const func = require('./func.js')
router.get('/test', (ctx) => {
  const image = await func.takeImage(ctx)
  ctx.body = image
})
```

Works. 1 file:
```
router.get('/test', (ctx) => {
const browser = await puppeteer.launch(
   {args: ['--no-sandbox', '--disable-setuid-sandbox']}
  );
  const page = await browser.newPage();
  await page.goto('https://example.com');
  await page.screenshot({path: 'example.png'});
  await browser.close()
  ctx.type = `image/png`
  //   send image to body
  ctx.body = fs.createReadStream('./example.png')
})
```

If I keeping hitting the first example I will occasionally get other errors. First, 
```
2019-09-02T17:11:07.485279+00:00 app[web.1]: An error occured in takeImage: { TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
2019-09-02T17:11:07.485296+00:00 app[web.1]: at Promise.then (/app/node_modules/puppeteer/lib/LifecycleWatcher.js:142:21)
2019-09-02T17:11:07.485298+00:00 app[web.1]: -- ASYNC --
2019-09-02T17:11:07.485302+00:00 app[web.1]: at Frame.<anonymous> (/app/node_modules/puppeteer/lib/helper.js:111:15)
2019-09-02T17:11:07.485304+00:00 app[web.1]: at Page.goto (/app/node_modules/puppeteer/lib/Page.js:674:49)
2019-09-02T17:11:07.485307+00:00 app[web.1]: at Page.<anonymous> (/app/node_modules/puppeteer/lib/helper.js:112:23)
2019-09-02T17:11:07.485310+00:00 app[web.1]: at sendImage (/app/API/index.js:31:18)
2019-09-02T17:11:07.485312+00:00 app[web.1]: at process._tickCallback (internal/process/next_tick.js:68:7) name: 'TimeoutError' }
```

And Also: 
```
2019-09-02T17:12:06.600487+00:00 app[web.1]: An error occured in takeImage: Error: Failed to launch chrome!
2019-09-02T17:12:06.600496+00:00 app[web.1]: [0902/171205.799399:ERROR:platform_thread_posix.cc(129)] pthread_create: Resource temporarily unavailable (11)
2019-09-02T17:12:06.600498+00:00 app[web.1]: [0902/171205.799371:ERROR:platform_thread_posix.cc(129)] pthread_create: Resource temporarily unavailable (11)
2019-09-02T17:12:06.600500+00:00 app[web.1]: [0902/171205.804603:ERROR:platform_thread_posix.cc(129)] pthread_create: Resource temporarily unavailable (11)
2019-09-02T17:12:06.600502+00:00 app[web.1]: [0902/171205.805994:ERROR:platform_thread_posix.cc(129)] pthread_create: Resource temporarily unavailable (11)
2019-09-02T17:12:06.600505+00:00 app[web.1]: [0902/171205.804644:FATAL:backend_impl.cc(121)] Check failed: StartWithOptions(base::Thread::Options(base::MessageLoop::TYPE_IO, 0)).
2019-09-02T17:12:06.600507+00:00 app[web.1]: #0 0x559efb439a99 base::debug::CollectStackTrace()
2019-09-02T17:12:06.600509+00:00 app[web.1]: #1 0x559efb39a3e3 base::debug::StackTrace::StackTrace()
2019-09-02T17:12:06.600511+00:00 app[web.1]: #2 0x559efb3ae943 logging::LogMessage::~LogMessage()
2019-09-02T17:12:06.600513+00:00 app[web.1]: #3 0x559efb789bbb base::LazyInstance<>::Get()
2019-09-02T17:12:06.600515+00:00 app[web.1]: #4 0x559efb7828c0 disk_cache::BackendImpl::BackendImpl()
2019-09-02T17:12:06.600517+00:00 app[web.1]: #5 0x559efb7823e0 (anonymous namespace)::CacheCreator::Run()
2019-09-02T17:12:06.600519+00:00 app[web.1]: #6 0x559efb78259f (anonymous namespace)::CacheCreator::TryCreateCleanupTrackerAndRun()
2019-09-02T17:12:06.600521+00:00 app[web.1]: #7 0x559efb7821fa disk_cache::CreateCacheBackendImpl()
2019-09-02T17:12:06.600523+00:00 app[web.1]: #8 0x559efb7825f2 disk_cache::CreateCacheBackend()
2019-09-02T17:12:06.600525+00:00 app[web.1]: #9 0x559ef969dc07 gpu::ShaderDiskCache::Init()
2019-09-02T17:12:06.600527+00:00 app[web.1]: #10 0x559ef969db49 gpu::ShaderCacheFactory::Get()
2019-09-02T17:12:06.600529+00:00 app[web.1]: #11 0x559efc70acb4 viz::GpuHostImpl::EstablishGpuChannel()
2019-09-02T17:12:06.600531+00:00 app[web.1]: #12 0x559efc708896 viz::GpuClient::EstablishGpuChannel()
2019-09-02T17:12:06.600533+00:00 app[web.1]: #13 0x559ef94df7bb base::internal::Invoker<>::RunOnce()
2019-09-02T17:12:06.600535+00:00 app[web.1]: #14 0x559efb3e4b9f base::TaskAnnotator::RunTask()
2019-09-02T17:12:06.600537+00:00 app[web.1]: #15 0x559efb3f493e base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl()
2019-09-02T17:12:06.600538+00:00 app[web.1]: #16 0x559efb3f4638 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoSomeWork()
2019-09-02T17:12:06.600540+00:00 app[web.1]: #17 0x559efb44f849 base::MessagePumpLibevent::Run()
2019-09-02T17:12:06.600542+00:00 app[web.1]: #18 0x559efb3f5229 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run()
2019-09-02T17:12:06.600544+00:00 app[web.1]: #19 0x559efb3cdf57 base::RunLoop::RunWithTimeout()
2019-09-02T17:12:06.600546+00:00 app[web.1]: #20 0x559ef9952004 content::BrowserProcessSubThread::IOThreadRun()
2019-09-02T17:12:06.600548+00:00 app[web.1]: #21 0x559efb40f9ef base::Thread::ThreadMain()
2019-09-02T17:12:06.600550+00:00 app[web.1]: #22 0x559efb449b6e base::(anonymous namespace)::ThreadFunc()
2019-09-02T17:12:06.600552+00:00 app[web.1]: #23 0x7f22a48ca6db start_thread
2019-09-02T17:12:06.600554+00:00 app[web.1]: #24 0x7f229e75d88f clone
2019-09-02T17:12:06.600556+00:00 app[web.1]: Task trace:
2019-09-02T17:12:06.600558+00:00 app[web.1]: #0 0x559efc7084eb viz::GpuClient::PreEstablishGpuChannel()
2019-09-02T17:12:06.600560+00:00 app[web.1]: #1 0x559efb0076fb headless::HeadlessShell::OnStart()
2019-09-02T17:12:06.600562+00:00 app[web.1]: #2 0x559efb0076fb headless::HeadlessShell::OnStart()
2019-09-02T17:12:06.600564+00:00 app[web.1]: 
2019-09-02T17:12:06.600566+00:00 app[web.1]: Received signal 6
2019-09-02T17:12:06.600568+00:00 app[web.1]: #0 0x559efb439a99 base::debug::CollectStackTrace()
2019-09-02T17:12:06.600570+00:00 app[web.1]: #1 0x559efb39a3e3 base::debug::StackTrace::StackTrace()
2019-09-02T17:12:06.600572+00:00 app[web.1]: #2 0x559efb439621 base::debug::(anonymous namespace)::StackDumpSignalHandler()
2019-09-02T17:12:06.600574+00:00 app[web.1]: #3 0x7f22a48d5890 <unknown>
2019-09-02T17:12:06.600576+00:00 app[web.1]: #4 0x7f229e67ae97 gsignal
2019-09-02T17:12:06.600578+00:00 app[web.1]: #5 0x7f229e67c801 abort
2019-09-02T17:12:06.600579+00:00 app[web.1]: #6 0x559efb438465 base::debug::BreakDebugger()
2019-09-02T17:12:06.600581+00:00 app[web.1]: #7 0x559efb3aec27 logging::LogMessage::~LogMessage()
2019-09-02T17:12:06.600583+00:00 app[web.1]: #8 0x559efb789bbb base::LazyInstance<>::Get()
2019-09-02T17:12:06.600585+00:00 app[web.1]: #9 0x559efb7828c0 disk_cache::BackendImpl::BackendImpl()
2019-09-02T17:12:06.600587+00:00 app[web.1]: #10 0x559efb7823e0 (anonymous namespace)::CacheCreator::Run()
2019-09-02T17:12:06.600589+00:00 app[web.1]: #11 0x559efb78259f (anonymous namespace)::CacheCreator::TryCreateCleanupTrackerAndRun()
2019-09-02T17:12:06.600591+00:00 app[web.1]: #12 0x559efb7821fa disk_cache::CreateCacheBackendImpl()
2019-09-02T17:12:06.600593+00:00 app[web.1]: #13 0x559efb7825f2 disk_cache::CreateCacheBackend()
2019-09-02T17:12:06.600594+00:00 app[web.1]: #14 0x559ef969dc07 gpu::ShaderDiskCache::Init()
2019-09-02T17:12:06.600596+00:00 app[web.1]: #15 0x559ef969db49 gpu::ShaderCacheFactory::Get()
2019-09-02T17:12:06.600598+00:00 app[web.1]: #16 0x559efc70acb4 viz::GpuHostImpl::EstablishGpuChannel()
2019-09-02T17:12:06.600600+00:00 app[web.1]: #17 0x559efc708896 viz::GpuClient::EstablishGpuChannel()
2019-09-02T17:12:06.600602+00:00 app[web.1]: #18 0x559ef94df7bb base::internal::Invoker<>::RunOnce()
2019-09-02T17:12:06.600603+00:00 app[web.1]: #19 0x559efb3e4b9f base::TaskAnnotator::RunTask()
2019-09-02T17:12:06.600605+00:00 app[web.1]: #20 0x559efb3f493e base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl()
2019-09-02T17:12:06.600607+00:00 app[web.1]: #21 0x559efb3f4638 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoSomeWork()
2019-09-02T17:12:06.600609+00:00 app[web.1]: #22 0x559efb44f849 base::MessagePumpLibevent::Run()
2019-09-02T17:12:06.600611+00:00 app[web.1]: #23 0x559efb3f5229 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run()
2019-09-02T17:12:06.600613+00:00 app[web.1]: #24 0x559efb3cdf57 base::RunLoop::RunWithTimeout()
2019-09-02T17:12:06.600614+00:00 app[web.1]: #25 0x559ef9952004 content::BrowserProcessSubThread::IOThreadRun()
2019-09-02T17:12:06.600616+00:00 app[web.1]: #26 0x559efb40f9ef base::Thread::ThreadMain()
2019-09-02T17:12:06.600618+00:00 app[web.1]: #27 0x559efb449b6e base::(anonymous namespace)::ThreadFunc()
2019-09-02T17:12:06.600620+00:00 app[web.1]: #28 0x7f22a48ca6db start_thread
2019-09-02T17:12:06.600622+00:00 app[web.1]: #29 0x7f229e75d88f clone
2019-09-02T17:12:06.600624+00:00 app[web.1]: r8: 0000000000000000  r9: 00007f2292855760 r10: 0000000000000008 r11: 0000000000000246
2019-09-02T17:12:06.600632+00:00 app[web.1]: r12: 00007f2292856a20 r13: 00007f2292855a08 r14: 00007f2292856a28 r15: 00007f2292856a30
2019-09-02T17:12:06.600634+00:00 app[web.1]: di: 0000000000000002  si: 00007f2292855760  bp: 00007f22928559b0  bx: 00007f2292855a08
2019-09-02T17:12:06.600636+00:00 app[web.1]: dx: 0000000000000000  ax: 0000000000000000  cx: 00007f229e67ae97  sp: 00007f2292855760
2019-09-02T17:12:06.600638+00:00 app[web.1]: ip: 00007f229e67ae97 efl: 0000000000000246 cgf: 656c000000000033 erf: 0000000000000000
2019-09-02T17:12:06.600640+00:00 app[web.1]: trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
2019-09-02T17:12:06.600641+00:00 app[web.1]: [end of stack trace]
2019-09-02T17:12:06.600643+00:00 app[web.1]: Calling _exit(1). Core file will not be generated.
2019-09-02T17:12:06.600645+00:00 app[web.1]: 
2019-09-02T17:12:06.600647+00:00 app[web.1]: 
2019-09-02T17:12:06.600649+00:00 app[web.1]: TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
2019-09-02T17:12:06.600650+00:00 app[web.1]: 
2019-09-02T17:12:06.600652+00:00 app[web.1]: at onClose (/app/node_modules/puppeteer/lib/Launcher.js:349:14)
2019-09-02T17:12:06.600654+00:00 app[web.1]: at ChildProcess.helper.addEventListener (/app/node_modules/puppeteer/lib/Launcher.js:339:60)
2019-09-02T17:12:06.600656+00:00 app[web.1]: at ChildProcess.emit (events.js:203:15)
2019-09-02T17:12:06.600658+00:00 app[web.1]: at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
2019-09-02T17:12:06.600872+00:00 app[web.1]: image Error: Failed to launch chrome!
2019-09-02T17:12:06.600875+00:00 app[web.1]: [0902/171205.799399:ERROR:platform_thread_posix.cc(129)] pthread_create: Resource temporarily unavailable (11)
2019-09-02T17:12:06.600877+00:00 app[web.1]: [0902/171205.799371:ERROR:platform_thread_posix.cc(129)] pthread_create: Resource temporarily unavailable (11)
2019-09-02T17:12:06.600879+00:00 app[web.1]: [0902/171205.804603:ERROR:platform_thread_posix.cc(129)] pthread_create: Resource temporarily unavailable (11)
2019-09-02T17:12:06.600882+00:00 app[web.1]: [0902/171205.805994:ERROR:platform_thread_posix.cc(129)] pthread_create: Resource temporarily unavailable (11)
2019-09-02T17:12:06.600884+00:00 app[web.1]: [0902/171205.804644:FATAL:backend_impl.cc(121)] Check failed: StartWithOptions(base::Thread::Options(base::MessageLoop::TYPE_IO, 0)).
2019-09-02T17:12:06.600886+00:00 app[web.1]: #0 0x559efb439a99 base::debug::CollectStackTrace()
2019-09-02T17:12:06.600888+00:00 app[web.1]: #1 0x559efb39a3e3 base::debug::StackTrace::StackTrace()
2019-09-02T17:12:06.600890+00:00 app[web.1]: #2 0x559efb3ae943 logging::LogMessage::~LogMessage()
2019-09-02T17:12:06.600891+00:00 app[web.1]: #3 0x559efb789bbb base::LazyInstance<>::Get()
2019-09-02T17:12:06.600893+00:00 app[web.1]: #4 0x559efb7828c0 disk_cache::BackendImpl::BackendImpl()
2019-09-02T17:12:06.600895+00:00 app[web.1]: #5 0x559efb7823e0 (anonymous namespace)::CacheCreator::Run()
2019-09-02T17:12:06.600897+00:00 app[web.1]: #6 0x559efb78259f (anonymous namespace)::CacheCreator::TryCreateCleanupTrackerAndRun()
2019-09-02T17:12:06.600899+00:00 app[web.1]: #7 0x559efb7821fa disk_cache::CreateCacheBackendImpl()
2019-09-02T17:12:06.600901+00:00 app[web.1]: #8 0x559efb7825f2 disk_cache::CreateCacheBackend()
2019-09-02T17:12:06.600903+00:00 app[web.1]: #9 0x559ef969dc07 gpu::ShaderDiskCache::Init()
2019-09-02T17:12:06.600905+00:00 app[web.1]: #10 0x559ef969db49 gpu::ShaderCacheFactory::Get()
2019-09-02T17:12:06.600907+00:00 app[web.1]: #11 0x559efc70acb4 viz::GpuHostImpl::EstablishGpuChannel()
2019-09-02T17:12:06.600909+00:00 app[web.1]: #12 0x559efc708896 viz::GpuClient::EstablishGpuChannel()
2019-09-02T17:12:06.600911+00:00 app[web.1]: #13 0x559ef94df7bb base::internal::Invoker<>::RunOnce()
2019-09-02T17:12:06.600913+00:00 app[web.1]: #14 0x559efb3e4b9f base::TaskAnnotator::RunTask()
2019-09-02T17:12:06.600915+00:00 app[web.1]: #15 0x559efb3f493e base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl()
2019-09-02T17:12:06.600917+00:00 app[web.1]: #16 0x559efb3f4638 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoSomeWork()
2019-09-02T17:12:06.600919+00:00 app[web.1]: #17 0x559efb44f849 base::MessagePumpLibevent::Run()
2019-09-02T17:12:06.600921+00:00 app[web.1]: #18 0x559efb3f5229 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run()
2019-09-02T17:12:06.600923+00:00 app[web.1]: #19 0x559efb3cdf57 base::RunLoop::RunWithTimeout()
2019-09-02T17:12:06.600925+00:00 app[web.1]: #20 0x559ef9952004 content::BrowserProcessSubThread::IOThreadRun()
2019-09-02T17:12:06.600927+00:00 app[web.1]: #21 0x559efb40f9ef base::Thread::ThreadMain()
2019-09-02T17:12:06.600929+00:00 app[web.1]: #22 0x559efb449b6e base::(anonymous namespace)::ThreadFunc()
2019-09-02T17:12:06.600931+00:00 app[web.1]: #23 0x7f22a48ca6db start_thread
2019-09-02T17:12:06.600933+00:00 app[web.1]: #24 0x7f229e75d88f clone
2019-09-02T17:12:06.600935+00:00 app[web.1]: Task trace:
2019-09-02T17:12:06.600937+00:00 app[web.1]: #0 0x559efc7084eb viz::GpuClient::PreEstablishGpuChannel()
2019-09-02T17:12:06.600939+00:00 app[web.1]: #1 0x559efb0076fb headless::HeadlessShell::OnStart()
2019-09-02T17:12:06.600941+00:00 app[web.1]: #2 0x559efb0076fb headless::HeadlessShell::OnStart()
2019-09-02T17:12:06.600942+00:00 app[web.1]: 
2019-09-02T17:12:06.600944+00:00 app[web.1]: Received signal 6
2019-09-02T17:12:06.600946+00:00 app[web.1]: #0 0x559efb439a99 base::debug::CollectStackTrace()
2019-09-02T17:12:06.600948+00:00 app[web.1]: #1 0x559efb39a3e3 base::debug::StackTrace::StackTrace()
2019-09-02T17:12:06.600950+00:00 app[web.1]: #2 0x559efb439621 base::debug::(anonymous namespace)::StackDumpSignalHandler()
2019-09-02T17:12:06.600952+00:00 app[web.1]: #3 0x7f22a48d5890 <unknown>
2019-09-02T17:12:06.600954+00:00 app[web.1]: #4 0x7f229e67ae97 gsignal
2019-09-02T17:12:06.600956+00:00 app[web.1]: #5 0x7f229e67c801 abort
2019-09-02T17:12:06.600958+00:00 app[web.1]: #6 0x559efb438465 base::debug::BreakDebugger()
2019-09-02T17:12:06.600960+00:00 app[web.1]: #7 0x559efb3aec27 logging::LogMessage::~LogMessage()
2019-09-02T17:12:06.600962+00:00 app[web.1]: #8 0x559efb789bbb base::LazyInstance<>::Get()
2019-09-02T17:12:06.600964+00:00 app[web.1]: #9 0x559efb7828c0 disk_cache::BackendImpl::BackendImpl()
2019-09-02T17:12:06.600969+00:00 app[web.1]: #10 0x559efb7823e0 (anonymous namespace)::CacheCreator::Run()
2019-09-02T17:12:06.600971+00:00 app[web.1]: #11 0x559efb78259f (anonymous namespace)::CacheCreator::TryCreateCleanupTrackerAndRun()
2019-09-02T17:12:06.600973+00:00 app[web.1]: #12 0x559efb7821fa disk_cache::CreateCacheBackendImpl()
2019-09-02T17:12:06.600975+00:00 app[web.1]: #13 0x559efb7825f2 disk_cache::CreateCacheBackend()
2019-09-02T17:12:06.600977+00:00 app[web.1]: #14 0x559ef969dc07 gpu::ShaderDiskCache::Init()
2019-09-02T17:12:06.600979+00:00 app[web.1]: #15 0x559ef969db49 gpu::ShaderCacheFactory::Get()
2019-09-02T17:12:06.600981+00:00 app[web.1]: #16 0x559efc70acb4 viz::GpuHostImpl::EstablishGpuChannel()
2019-09-02T17:12:06.600983+00:00 app[web.1]: #17 0x559efc708896 viz::GpuClient::EstablishGpuChannel()
2019-09-02T17:12:06.600985+00:00 app[web.1]: #18 0x559ef94df7bb base::internal::Invoker<>::RunOnce()
2019-09-02T17:12:06.600987+00:00 app[web.1]: #19 0x559efb3e4b9f base::TaskAnnotator::RunTask()
2019-09-02T17:12:06.600989+00:00 app[web.1]: #20 0x559efb3f493e base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl()
2019-09-02T17:12:06.600991+00:00 app[web.1]: #21 0x559efb3f4638 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoSomeWork()
2019-09-02T17:12:06.600993+00:00 app[web.1]: #22 0x559efb44f849 base::MessagePumpLibevent::Run()
2019-09-02T17:12:06.600995+00:00 app[web.1]: #23 0x559efb3f5229 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run()
2019-09-02T17:12:06.600997+00:00 app[web.1]: #24 0x559efb3cdf57 base::RunLoop::RunWithTimeout()
2019-09-02T17:12:06.600999+00:00 app[web.1]: #25 0x559ef9952004 content::BrowserProcessSubThread::IOThreadRun()
2019-09-02T17:12:06.601001+00:00 app[web.1]: #26 0x559efb40f9ef base::Thread::ThreadMain()
2019-09-02T17:12:06.601002+00:00 app[web.1]: #27 0x559efb449b6e base::(anonymous namespace)::ThreadFunc()
2019-09-02T17:12:06.601004+00:00 app[web.1]: #28 0x7f22a48ca6db start_thread
2019-09-02T17:12:06.601006+00:00 app[web.1]: #29 0x7f229e75d88f clone
2019-09-02T17:12:06.601008+00:00 app[web.1]: r8: 0000000000000000  r9: 00007f2292855760 r10: 0000000000000008 r11: 0000000000000246
2019-09-02T17:12:06.601015+00:00 app[web.1]: r12: 00007f2292856a20 r13: 00007f2292855a08 r14: 00007f2292856a28 r15: 00007f2292856a30
2019-09-02T17:12:06.601017+00:00 app[web.1]: di: 0000000000000002  si: 00007f2292855760  bp: 00007f22928559b0  bx: 00007f2292855a08
2019-09-02T17:12:06.601019+00:00 app[web.1]: dx: 0000000000000000  ax: 0000000000000000  cx: 00007f229e67ae97  sp: 00007f2292855760
2019-09-02T17:12:06.601021+00:00 app[web.1]: ip: 00007f229e67ae97 efl: 0000000000000246 cgf: 656c000000000033 erf: 0000000000000000
2019-09-02T17:12:06.601023+00:00 app[web.1]: trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
2019-09-02T17:12:06.601025+00:00 app[web.1]: [end of stack trace]
2019-09-02T17:12:06.601026+00:00 app[web.1]: Calling _exit(1). Core file will not be generated.
2019-09-02T17:12:06.601028+00:00 app[web.1]: 
2019-09-02T17:12:06.601030+00:00 app[web.1]: 
2019-09-02T17:12:06.601032+00:00 app[web.1]: TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
2019-09-02T17:12:06.601034+00:00 app[web.1]: 
2019-09-02T17:12:06.601036+00:00 app[web.1]: at onClose (/app/node_modules/puppeteer/lib/Launcher.js:349:14)
2019-09-02T17:12:06.601038+00:00 app[web.1]: at ChildProcess.helper.addEventListener (/app/node_modules/puppeteer/lib/Launcher.js:339:60)
2019-09-02T17:12:06.601040+00:00 app[web.1]: at ChildProcess.emit (events.js:203:15)
2019-09-02T17:12:06.601042+00:00 app[web.1]: at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)

```
