### ISSUE TITLE
Unable to `npm install puppeteer`

### ISSUE THREAD

**Issue by ggrillone** [puppeteer/puppeteer#493]
When running `npm install puppeteer` I receive the following error:

```
@Gregs-MacBook-Pro pegasus (perf-test-prototype)*$ npm install --save-dev puppeteer

> puppeteer@0.9.0 install /Users/ME/Documents/my_project/node_modules/puppeteer
> node install.js

/Users/ME/Documents/my_project/node_modules/puppeteer/utils/ChromiumDownloader.js:89
  downloadRevision: async function(platform, revision, progressCallback) {
                          ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ME/Documents/my_project/node_modules/puppeteer/install.js:17:20)
    at Module._compile (module.js:571:32)
npm WARN react-test-renderer@15.6.1 requires a peer of react@^15.6.1 but none was installed.
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save-dev" "puppeteer"
npm ERR! node v7.2.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! puppeteer@0.9.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 

```

**Comment by ggrillone** [comment]
I am on node `v7.2.0`

**Comment by twalpole** [comment]
async/await support isn't enabled by default until Node 7.6.0

**Comment by ggrillone** [comment]
ah thanks @twalpole

**Comment by twalpole** [comment]
@ggrillone Notice the "by default" qualifier :). If you run with the harmony flag it should enable support.
