### ISSUE TITLE
Async function in evaluate method throws error

### ISSUE THREAD

**Issue by AndrejGajdos** [puppeteer/puppeteer#4938]
I am trying to check if `og:image` source exists.

* Puppeteer version: 1.19.0
* Platform / OS version: macOS Mojave 10.14.6
* URLs (if applicable): https://www.onepeloton.com/
* Node.js version: v12.1.0

_Please include code that reproduces the issue._

**app.js**

```js
const puppeteer = require("puppeteer");
const util = require('util');
const urlExists = util.promisify(require('url-exists'));

const run = async () => {
  try {
    const browser = await puppeteer.launch({ headless: true });
    const page = await browser.newPage();

    await page.goto('https://www.onepeloton.com/', { waitUntil: 'domcontentloaded' });

    const img = await page.evaluate(async () => {
      const ogImg = document.querySelector('meta[property="og:image"]');
      if (ogImg != null && ogImg.content.length > 0) {
        const isExists = await urlExists(ogImg.content);
        return isExists;
      }
    });
    console.log(img);

    await browser.close()
  } catch (e) {
    console.log(e);
  }
}

run();
```

**What is the expected result?**

A boolean value. true if url exists, false otherwise.

**What happens instead?**

```
 Error: Evaluation failed: [object Object]
    at ExecutionContext._evaluateInternal (.../node_modules/puppeteer/lib/ExecutionContext.js:122:13)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async ExecutionContext.evaluate (.../node_modules/puppeteer/lib/ExecutionContext.js:48:12)
  -- ASYNC --
    at ExecutionContext.<anonymous> (.../node_modules/puppeteer/lib/helper.js:111:15)
    at DOMWorld.evaluate (.../node_modules/puppeteer/lib/DOMWorld.js:112:20)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
  -- ASYNC --
    at Frame.<anonymous> (.../node_modules/puppeteer/lib/helper.js:111:15)
    at Page.evaluate (.../node_modules/puppeteer/lib/Page.js:827:43)
    at Page.<anonymous> (.../node_modules/puppeteer/lib/helper.js:112:23)
    at run (/Users/andrejgajdos/devel/link-preview/app.js:195:28)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

**Comment by kblok** [comment]
The code you run in the `evaluate` function runs inside the browser, `urlExists` won't be accessible from there **unless** you use [exposeFunction](https://github.com/GoogleChrome/puppeteer/blob/v1.19.0/docs/api.md#pageexposefunctionname-puppeteerfunction).

**Comment by AndrejGajdos** [comment]
Thanks, works great.

**Comment by jinusean** [comment]
I'm getting the same message when an async function fails in evaluate. 
If I get a more descriptive message if I print out the message myself by wrapping the function in try / catch. 

Is there any way to have the console print the actual error message instead of ` Error: Evaluation failed: [object Object]` ?
