### ISSUE TITLE
Puppeteer issue with docker

### ISSUE THREAD

**Issue by jainshobhit** [puppeteer/puppeteer#4945]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:
1.17.0
* Platform / OS version:
Mac OS using docker version 18.09.2
* URLs (if applicable):
* Node.js version:
10

**What steps will reproduce the problem?**
My Dockerfile is as follows
```
FROM node:10-alpine

RUN echo "http://dl-2.alpinelinux.org/alpine/edge/main" > /etc/apk/repositories
RUN echo "http://dl-2.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
RUN echo "http://dl-2.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories

ENV CHROME_BIN="/usr/bin/chromium-browser" \
    PUPPETEER_SKIP_CHROMIUM_DOWNLOAD="true"

RUN set -x \
    && apk update \
    && apk upgrade \
    && apk add --no-cache \
    udev \
    ttf-freefont \
    chromium \
    && npm install puppeteer@1.17.0

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app

WORKDIR /home/node/app

ENV PATH /home/node/app/node_modules/.bin:$PATH

COPY package*.json ./

RUN apk --no-cache --virtual build-dependencies add \
    python \
    make \
    g++ \
    && npm install \
    && apk del build-dependencies

USER node

RUN npm install

RUN mkdir -p /home/node/app/logs

COPY --chown=node:node . .

EXPOSE 4000

EXPOSE 3050

CMD [ "node", "app.js" ]

```
_Please include code that reproduces the issue._

1. 
```
const puppeteer = require("puppeteer");

fetchLedgerPdf : async function (req,res,next){

const browser = await puppeteer.launch({
                headless: true,
                executablePath: '/usr/bin/chromium-browser',
                args: ['--no-sandbox', '--headless', '--disable-gpu', '--disable-dev-shm-usage']
            });
            const page = await browser.newPage();

await page.setContent()

await page.addStyleTag()

const buffer = await page.pdf({
                // path : 'page.pdf',
                format: "A4",
                scale : 0.9,
                printBackground : true,
                displayHeaderFooter : true,
                headerTemplate: '<div id="header-template" style="width:100%;text-align:center;font-size:10px !important; color:black; padding-left:10px">Page <span class="pageNumber"></span> of <span class="totalPages"></span></div>',
                footerTemplate: '<div>...</div>',
                preferCSSPageSize : true
            });

await browser.close();
   res.end(buffer);
}
```
2.
3.

**What is the expected result?**
Process the PDF

**What happens instead?**

Throw the following error
```
{ Error: Protocol error (IO.read): Invalid parameters handle: string value expected
    at Promise (/home/node/app/node_modules/puppeteer/lib/Connection.js:183:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/home/node/app/node_modules/puppeteer/lib/Connection.js:182:12)
    at Function.readProtocolStream (/home/node/app/node_modules/puppeteer/lib/helper.js:241:37)
    at Page.pdf (/home/node/app/node_modules/puppeteer/lib/Page.js:988:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Page.<anonymous> (/home/node/app/node_modules/puppeteer/lib/helper.js:111:15)
    at fetchLedgerPdf (/home/node/app/Models/post/pdfCreation.js:316:39)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  message:
   'Protocol error (IO.read): Invalid parameters handle: string value expected' }
```

I have tried following lots of other issues facing similar problem. I have also ensured that my chromium and puppeteer version are the same as mentioned on a lot of forums. I am using `puppeteer@1.17.0`(based on release `76.0.3803.0`as obtained from https://omahaproxy.appspot.com) with the edge image of alpine that uses `chromium 76.0.3809.132-r0`. I also tried with puppeeteer@1.18.0.

Still facing this trouble. Any help would be appreciated.

**Comment by vyomsrivastava** [comment]
Well, docker has some issue with the Puppeteer or vice versa. I also tried to deploy the same setup on AWS EC2 machine but with google the never allows to sign in using a headless setup that too on a docker or EC2 instance.

**Comment by RamazanBiyik77** [comment]
Is there any update on this?
