### ISSUE TITLE
Error: Protocol error (Runtime.evaluate): Session closed. Most likely the page has been closed.

### ISSUE THREAD

**Issue by laggingreflex** [puppeteer/puppeteer#507]
Keep getting this error: 

```
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Protocol error (Runtime.evaluate): Session closed. Most likely the page has been closed.
(node:18244) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Full error  using `process.on('unhandledRejection', console.error)`

```
Error: Protocol error (Runtime.evaluate): Session closed. Most likely the page has been closed.
    at Session.send (C:\...\puppeteer\lib\Connection.js:170:29)
    at Page._onConsoleAPI (C:\...\puppeteer\lib\Page.js:225:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by ebidel** [comment]
Can you post code that repros the issue?

**Comment by aslushnikov** [comment]
Speculatively closing this. Feel free to file a new issue or to write here to reopen.

**Comment by techdiary** [comment]
`Unhandled Rejection at: Promise Promise {
  <rejected> Error: Protocol error (Runtime.evaluate): Session closed. Most likely the page has been closed.
    at CDPSession.send (/Users/aayush/Documents/projects/bjAuto/node_modules/puppeteer/lib/Connection.js:185:29)
    at ExecutionContext.evaluateHandle (/Users/aayush/Documents/projects/bjAuto/node_modules/puppeteer/lib/ExecutionContext.js:65:77)
    at _documentPromise._contextPromise.then (/Users/aayush/Documents/projects/bjAuto/node_modules/puppeteer/lib/FrameManager.js:319:38)
    at <anonymous> } reason: Error: Protocol error (Runtime.evaluate): Session closed. Most likely the page has been closed.`

Getting this error on executing code below:
`await page.goto(`${properties[name][project_partition]['uploadUrl']}`).catch( (e) => console.log(e));`

Can't share the url with you, but my workflow is like this:
-> Login into rundeck
-> wait for login page
-> go to rundeck job(`using page.goto()`)
This is where i get the above error, please help me understand it. 
I'm able to execute it manually though, thanks
