### ISSUE TITLE
Automate outlook login using puppeteer-email throws an error.

### ISSUE THREAD

**Issue by samathan** [puppeteer/puppeteer#5138]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: latest
* Platform / OS version: Mac
* URLs (if applicable):
* Node.js version:

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

const PuppeteerEmail = require('puppeteer-email');
const client = new PuppeteerEmail('outlook')
1.const visitOutlookPage = async () => {
  const username = 'xxx'
  const password = 'xxx'

const session = await client.signin({ username, password })
const emails = await session.getEmails({ query: 'from:GitHub' })
await session.close();
console.log(emails);
}
2.
3.

**What is the expected result?**
To login into outlook.

**What happens instead?**
 ✖ When I visit the outlook page # 1104/clarity/end-to-end/node_modules/cucumber/lib/support_code_library_builder/build_helpers.js:173
       TimeoutError: waiting for selector "input[type=checkbox]" failed: timeout 30000ms exceeded
           at new WaitTask (/Users/xx/appname/end-to-end/node_modules/puppeteer/lib/DOMWorld.js:561:28)
           at DOMWorld._waitForSelectorOrXPath (xx/appname//end-to-end/node_modules/puppeteer/lib/DOMWorld.js:490:22)
           at DOMWorld.waitForSelector (/xx/appname/end-to-end/node_modules/puppeteer/lib/DOMWorld.js:444:17)
           at Frame.waitForSelector (/xx/appname/end-to-end/node_modules/puppeteer/lib/FrameManager.js:628:47)
           at Frame.<anonymous> (/xx/appname/end-to-end/node_modules/puppeteer/lib/helper.js:112:23)
           at Frame.waitFor (/xx/appname/end-to-end/node_modules/puppeteer/lib/FrameManager.js:613:19)
           at Page.waitFor (/xx/appname/end-to-end/node_modules/puppeteer/lib/Page.js:1035:29)
           at module.exports (/xx/appname/end-to-end/node_modules/puppeteer-email-provider-outlook/lib/signin.js:18:14)
           at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by kblok** [comment]
Shouldn't you report this on  https://github.com/transitive-bullshit/puppeteer-email?

**Comment by IgalNeeman** [comment]
Its not work
