### ISSUE TITLE
tslib_1 is not defined when using typescript

### ISSUE THREAD

**Issue by avifatal** [puppeteer/puppeteer#5206]
Hi
The following row is raising the error bellow when using typescript:
```
const main = await this.page.$x(xpath);
```

```
(node:18116) UnhandledPromiseRejectionWarning: Error: Evaluation failed: ReferenceError: tslib_1 is not defined
    at __puppeteer_evaluation_script__:1:16
    at ExecutionContext._evaluateInternal (C:\work\projects\lob\eyez-server-net\node-server\node_modules\puppeteer\lib\ExecutionCo
ntext.js:122:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (C:\work\projects\lob\eyez-server-net\node-server\node_modules\puppeteer\lib\helper.js:111:15)
    at DOMWorld.evaluate (C:\work\projects\lob\eyez-server-net\node-server\node_modules\puppeteer\lib\DOMWorld.js:112:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (C:\work\projects\lob\eyez-server-net\node-server\node_modules\puppeteer\lib\helper.js:111:15)
    at Page.evaluate (C:\work\projects\lob\eyez-server-net\node-server\node_modules\puppeteer\lib\Page.js:863:43)
    at Page.<anonymous> (C:\work\projects\lob\eyez-server-net\node-server\node_modules\puppeteer\lib\helper.js:112:23)
    at TwitterService.<anonymous> (C:\work\projects\lob\eyez-server-net\node-server\dist\twitter\service.js:207:24)
    at Generator.next (<anonymous>)
    at C:\work\projects\lob\eyez-server-net\node-server\node_modules\tslib\tslib.js:110:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\work\projects\lob\eyez-server-net\node-server\node_modules\tslib\tslib.js:106:16)
    at TwitterService.scrollDown (C:\work\projects\lob\eyez-server-net\node-server\dist\twitter\service.js:206:24)
    at TwitterService.<anonymous> (C:\work\projects\lob\eyez-server-net\node-server\dist\twitter\service.js:111:24)
  -- ASYNC --
    at Page.<anonymous> (C:\work\projects\lob\eyez-server-net\node-server\node_modules\puppeteer\lib\helper.js:111:15)
    at TwitterService.<anonymous> (C:\work\projects\lob\eyez-server-net\node-server\dist\twitter\service.js:207:24)
    at Generator.next (<anonymous>)
    at C:\work\projects\lob\eyez-server-net\node-server\node_modules\tslib\tslib.js:110:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\work\projects\lob\eyez-server-net\node-server\node_modules\tslib\tslib.js:106:16)
    at TwitterService.scrollDown (C:\work\projects\lob\eyez-server-net\node-server\dist\twitter\service.js:206:24)
    at TwitterService.<anonymous> (C:\work\projects\lob\eyez-server-net\node-server\dist\twitter\service.js:111:24)
    at Generator.next (<anonymous>)
    at fulfilled (C:\work\projects\lob\eyez-server-net\node-server\node_modules\tslib\tslib.js:107:62)
(node:18116) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an 
async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

This is the `package.json`:

```
"dependencies": {
    "@types/puppeteer": "^2.0.0",
    "compression": "^1.7.4",
    "express": "^4.17.1",
    "helmet": "^3.21.2",
    "puppeteer": "^2.0.0",
    "tslib": "^1.10.0"
  },
  "devDependencies": {
    "@types/compression": "^1.0.1",
    "@types/express": "^4.17.2",
    "@types/helmet": "0.0.45",
    "@types/jest": "^24.0.21",
    "@types/node": "^12.12.5",
    "eslint": "^6.6.0",
    "jest": "^24.9.0",
    "typescript": "^3.6.4"
  }
```

Thanks

**Comment by kblok** [comment]
What´s the xpath you are sending?

**Comment by cloydlau** [comment]
Did you solve it bro, running into the same problem.

**Comment by klaascuvelier** [comment]
I ran into this as well. I was not able to work around it by setting my `target` to `esnext` so the native `await` is being used instead of the `tslib1.__awaiter`

**Comment by yufengbuji** [comment]
how to deal with this problem..........

**Comment by owalerys** [comment]
Setting `compilerOptions.target` to `ESNext` in my `tsconfig.json` solved this for me.
