### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Navigation failed because browser has disconnected!

### ISSUE THREAD

**Issue by mzubairsaleem** [puppeteer/puppeteer#5209]
Hi, 
I'm having this issue while using puppeteer on Raspberry Pi Version 4.
This is working fine with Chromium Version 72.x.x.x but with 72.x.x.x interception isn't working.

> (node:11358) UnhandledPromiseRejectionWarning: Error: Navigation failed because browser has disconnected!
    at CDPSession.LifecycleWatcher._eventListeners.helper.addEventListener (/opt/mcp.scanner/node_modules/puppeteer/lib/LifecycleWatcher.js:46:107)
    at CDPSession.emit (events.js:189:13)
    at CDPSession._onClosed (/opt/mcp.scanner/node_modules/puppeteer/lib/Connection.js:215:10)
    at Connection._onClose (/opt/mcp.scanner/node_modules/puppeteer/lib/Connection.js:138:15)
    at WebSocketTransport._ws.addEventListener.event (/opt/mcp.scanner/node_modules/puppeteer/lib/WebSocketTransport.js:48:22)
    at WebSocket.onClose (/opt/mcp.scanner/node_modules/ws/lib/event-target.js:124:16)
    at WebSocket.emit (events.js:189:13)
    at WebSocket.emitClose (/opt/mcp.scanner/node_modules/ws/lib/websocket.js:191:10)
    at Socket.socketOnClose (/opt/mcp.scanner/node_modules/ws/lib/websocket.js:850:15)
    at Socket.emit (events.js:189:13)
  -- ASYNC --
    at Frame.<anonymous> (/opt/mcp.scanner/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.goto (/opt/mcp.scanner/node_modules/puppeteer/lib/Page.js:675:49)
    at Page.<anonymous> (/opt/mcp.scanner/node_modules/puppeteer/lib/helper.js:112:23)
    at puppeteer.launch.then (/opt/mcp.scanner/pp.js:30:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:11358) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11358) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Code I'm using 

```
const puppeteer = require('puppeteer');
puppeteer.launch({`
    'args': [
        '--disable-web-security',
        '--allow-http-screen-capture',
        '--allow-running-insecure-content',
        '--disable-features=site-per-process',
        '--no-sandbox'
    ],
    ignoreHTTPSErrors: true,
    headless: true,
    timeout: 10000,
    executablePath: 'chromium-browser',
    // userDataDir: settings.usersData
    // slowMo: 250, // slow down by 250ms
    // devtools: true
}).then(async browser => {
    const page = await browser.newPage();
    await page.setRequestInterception(true);
    page.on('request', interceptedRequest => {
        console.log("Here");
        if (interceptedRequest.url().endsWith('.png') || interceptedRequest.url().endsWith('.jpg')) {
            console.log("Abort", interceptedRequest.url());
            interceptedRequest.abort();
        } else {
            console.log("okok");
            interceptedRequest.continue();
        }
    });
    await page.goto('https://example.com');
    await browser.close();
});
```

**Environment**
- Puppeteer version: v2.0.0
- Raspbian GNU/Linux 10 (buster)
- Chromium Version: chromium-browser_74.0.3729.157
- Node.js version: v10

So, I'm kind of stuck here any help will be appreciated.
Thank you.

**Comment by kblok** [comment]
Could you improve the code example? it's hard to read in that way.

**Comment by mzubairsaleem** [comment]
@kblok Thanks for your response,  I have formatted the Code Please check Now.

**Comment by aswinarshad** [comment]
@mzubairsaleem  any progress in your issue cause i am also having the same one.

**Comment by mzubairsaleem** [comment]
@aswinarshad Still Nothing with the latest Version, But I Was able to work with chromium 72.0.xx and this is working.
