### ISSUE TITLE
[BUG] puppeteer 2.0 `page.pdf` not work

### ISSUE THREAD

**Issue by leecade** [puppeteer/puppeteer#5237]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.0
* Platform / OS version: debian
* URLs (if applicable): 
* Node.js version: 11 or 12
* Chrome: 79.0.3945.16

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```js
const  puppeteer = require('puppeteer-core')
const browser = await puppeteer.launch({
  executablePath: 'google-chrome',
  args: ['--no-sandbox', '--disable-setuid-sandbox']
})
const page = await browser.newPage()
await page.goto('https://www.apple.com/')

// here
await page.pdf({})
```

**What is the expected result?**

`page.pdf` should works as expected

**What happens instead?**

Throw error

```
Error: Protocol error (IO.read): Invalid parameters handle: string value expected
    at /app/node_modules/puppeteer-core/lib/Connection.js:183:56
    at new Promise (<anonymous>)
    at CDPSession.send (/app/node_modules/puppeteer-core/lib/Connection.js:182:12)
    at Function.readProtocolStream (/app/node_modules/puppeteer-core/lib/helper.js:254:37)
    at Page.pdf (/app/node_modules/puppeteer-core/lib/Page.js:1024:25)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.Pdf (/app/services/pdf/index.js:39:18)
  -- ASYNC --
    at Page.<anonymous> (/app/node_modules/puppeteer-core/lib/helper.js:111:15)
    at Object.Pdf (/app/services/pdf/index.js:39:29)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  message: 'Protocol error (IO.read): Invalid parameters handle: string value expected'
}
```

**Comment by leecade** [comment]
Update: it works with chrome `80.0.3983.2`
