### ISSUE TITLE
Select substring using xpath

### ISSUE THREAD

**Issue by atlanteh** [puppeteer/puppeteer#5254]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.0.0
* Platform / OS version: windows 10
* URLs (if applicable):
* Node.js version: 10.15.1

**What steps will reproduce the problem?**
Try to use substring in xpath selector

_Please include code that reproduces the issue._

```
const browser = await puppeteer.launch({
    headless: false,
    defaultViewport: null
});
const page = await browser.newPage();
await page.goto('https://github.com/puppeteer/puppeteer')
await page.$x(`substring(//*[@class="author"]//text(), 0, 7)`)
```

**What is the expected result?**
"Puppet"

**What happens instead?**
Exception is thrown:
```
Error: Evaluation failed: TypeError: Failed to execute 'evaluate' on 'Document': The result is not a node set, and therefore cannot be converted to the desired type.
    at __puppeteer_evaluation_script__:3:37
    at ExecutionContext._evaluateInternal (**truncated**\project\node_modules\puppeteer\lib\ExecutionContext.js:122:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (**truncated**\project\node_modules\puppeteer\lib\helper.js:111:15)
    at ElementHandle.evaluateHandle (**truncated**\project\node_modules\puppeteer\lib\JSHandle.js:64:42)
    at ElementHandle.<anonymous> (**truncated**\project\node_modules\puppeteer\lib\helper.js:112:23)
    at ElementHandle.$x (**truncated**\project\node_modules\puppeteer\lib\JSHandle.js:505:36)    
    at ElementHandle.<anonymous> (**truncated**\project\node_modules\puppeteer\lib\helper.js:112:23)
    at DOMWorld.$x (**truncated**\project\node_modules\puppeteer\lib\DOMWorld.js:144:34)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (**truncated**\project\node_modules\puppeteer\lib\helper.js:111:15)     
    at Page.$x (**truncated**\project\node_modules\puppeteer\lib\Page.js:374:29)
    at Page.<anonymous> (**truncated**\project\node_modules\puppeteer\lib\helper.js:112:23)      
    at scrapeItem (**truncated**\project\index.js:120:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by kblok** [comment]
[$x](https://github.com/puppeteer/puppeteer/blob/v2.0.0/docs/api.md#pagexexpression) returns an array of `ElementHandle`.  It won't return a text.  You could use evaluate instead.

```
const result = page.evaluate(() => document.evaluate(`substring(//*[@class="author"]//text(), 0, 7)`, document).stringValue);
```

**Comment by atlanteh** [comment]
Seems a bit hacky.. I don't like to use ```evaluate``` even once.. The only solution is to use it **twice**?
I guess I'll use it if there's no other option.. but shouldn't we have such option?

**Comment by kblok** [comment]
I don't think is hacky. I think `evaluate` is one of the most useful tools in Puppeteer. What do you say you have to use it twice?

**Comment by atlanteh** [comment]
well evaluate is like the most generic way of accessing the DOM. I prefer to use the more specific API methods over evaluation of functions etc..
In your specific solution I need to run both page.evaluate & document.evaluate.
I'm not saying it's bad to use them, it's just that they are the very last resort.. and I'd prefer other methods instead..

**Comment by kblok** [comment]
`$x` uses `evaluateHandle` and `document.evaluate` to return an array of elements.

**Comment by atlanteh** [comment]
Yeah, I assumed that down the road the utility methods and the low level apis might cross path. It's just that my whole career I've been avoiding dynamic evaluation of content as it can cause bad things to happen... maybe in context of puppeteer and the way the driver works, it's ok to use it here.. I'm not sure..
