### ISSUE TITLE
Error out on npm install

### ISSUE THREAD

**Issue by thetwosents** [puppeteer/puppeteer#526]
Did the `git clone` and when running `npm i` receive this error:

```
/chromium-starter/utils/ChromiumDownloader.js:88 downloadRevision: async function(platform, revision, progressCallback) {

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)```

**Comment by thetwosents** [comment]
Was node version...my bad :(

**Comment by thestral-c** [comment]
my node version is 14.15.0 .But this error happens all the time ...

**Comment by fredbradley** [comment]
My node version is 15.6.0 - and I'm getting this. I thought a fix was released in 14.something? New bug?
