### ISSUE TITLE
NodeJs 12: UnhandledPromiseRejectionWarning.

### ISSUE THREAD

**Issue by petrpatek** [puppeteer/puppeteer#5267]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.0.0
* Platform / OS version: macOs 10.15.2
* URLs (if applicable):
* Node.js version: 12.4

**What steps will reproduce the problem?**

**Code:**

```javascript
const puppeteer = require('puppeteer');

const main = async () => {
    const functionWithPagesInvocation = async (browser) => {
        const pages = await browser.pages();
        if (pages.length > 1) return pages[0].bringToFront();
    };
    const pool = [];
    for (let i = 0; i <= 5; i++) {
        const browser = await puppeteer.launch({ headless: true });
        pool.push(browser);

        await browser.newPage();
        functionWithPagesInvocation(browser).catch(e => console.error('Should catch error', e));
    }

    await Promise.all(pool.map(browser => browser.close()));
};

main().catch(e => console.error('Should atleast catch here', e));
```

**Logs:**

```bash
Should catch error Error: WebSocket is not open: readyState 2 (CLOSING)
    at WebSocket.send (/Users/petr/apify/puppeteer-testing/node_modules/ws/lib/websocket.js:329:19)
    at WebSocketTransport.send (/Users/petr/apify/puppeteer-testing/node_modules/puppeteer/lib/WebSocketTransport.js:60:14)
    at Connection._rawSend (/Users/petr/apify/puppeteer-testing/node_modules/puppeteer/lib/Connection.js:86:21)
    at CDPSession.send (/Users/petr/apify/puppeteer-testing/node_modules/puppeteer/lib/Connection.js:181:33)
    at Page._initialize (/Users/petr/apify/puppeteer-testing/node_modules/puppeteer/lib/Page.js:137:20)
    at Function.create (/Users/petr/apify/puppeteer-testing/node_modules/puppeteer/lib/Page.js:48:16)
    at /Users/petr/apify/puppeteer-testing/node_modules/puppeteer/lib/Target.js:74:32
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
    at async BrowserContext.pages (/Users/petr/apify/puppeteer-testing/node_modules/puppeteer/lib/Browser.js:311:19)
  -- ASYNC --
    at Target.<anonymous> (/Users/petr/apify/puppeteer-testing/node_modules/puppeteer/lib/helper.js:111:15)
    at /Users/petr/apify/puppeteer-testing/node_modules/puppeteer/lib/Browser.js:314:35
    at Array.map (<anonymous>)
    at BrowserContext.pages (/Users/petr/apify/puppeteer-testing/node_modules/puppeteer/lib/Browser.js:314:14)
    at BrowserContext.<anonymous> (/Users/petr/apify/puppeteer-testing/node_modules/puppeteer/lib/helper.js:112:23)
    at /Users/petr/apify/puppeteer-testing/node_modules/puppeteer/lib/Browser.js:233:90
    at Array.map (<anonymous>)
    at Browser.pages (/Users/petr/apify/puppeteer-testing/node_modules/puppeteer/lib/Browser.js:233:67)
    at Browser.<anonymous> (/Users/petr/apify/puppeteer-testing/node_modules/puppeteer/lib/helper.js:112:23)
    at functionWithPagesInvocation (/Users/petr/apify/puppeteer-testing/main.js:5:37)
  -- ASYNC --
    at BrowserContext.<anonymous> (/Users/petr/apify/puppeteer-testing/node_modules/puppeteer/lib/helper.js:111:15)
    at /Users/petr/apify/puppeteer-testing/node_modules/puppeteer/lib/Browser.js:233:90
    at Array.map (<anonymous>)
    at Browser.pages (/Users/petr/apify/puppeteer-testing/node_modules/puppeteer/lib/Browser.js:233:67)
    at Browser.<anonymous> (/Users/petr/apify/puppeteer-testing/node_modules/puppeteer/lib/helper.js:112:23)
    at functionWithPagesInvocation (/Users/petr/apify/puppeteer-testing/main.js:5:37)
    at main (/Users/petr/apify/puppeteer-testing/main.js:14:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:29769) UnhandledPromiseRejectionWarning: Error: Protocol error (Page.enable): Target closed.
    at /Users/petr/apify/puppeteer-testing/node_modules/puppeteer/lib/Connection.js:183:56
    at new Promise (<anonymous>)
    at CDPSession.send (/Users/petr/apify/puppeteer-testing/node_modules/puppeteer/lib/Connection.js:182:12)
    at FrameManager.initialize (/Users/petr/apify/puppeteer-testing/node_modules/puppeteer/lib/FrameManager.js:60:20)
    at Page._initialize (/Users/petr/apify/puppeteer-testing/node_modules/puppeteer/lib/Page.js:136:26)
    at Function.create (/Users/petr/apify/puppeteer-testing/node_modules/puppeteer/lib/Page.js:48:16)
    at /Users/petr/apify/puppeteer-testing/node_modules/puppeteer/lib/Target.js:74:32
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
    at async BrowserContext.pages (/Users/petr/apify/puppeteer-testing/node_modules/puppeteer/lib/Browser.js:311:19)
(node:29769) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:29769) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**What is the expected result?**
I would expect the exception to be handled.

**What happens instead?**
I guess that due to the promise handling changes in node v11+ some promise inside puppeteer is rejected earlier than the error handler is attached, so the `UnhandledPromiseRejectionWarning` appears.

NOTE: It does not happen in NodeJs 10

**Comment by wpitallo** [comment]
Any updates on this? I am getting a similar issue?

**Comment by smapets** [comment]
Shouldn't you be using try catch inside the async function??

**Comment by wpitallo** [comment]
@smapets, makes no difference if there is a try catch or not. I ended up installing the latest chromium distribution (think it was 81) and and then added the path manually to .launch() and and that seems to work.

**Comment by smapets** [comment]
@wpitallo `const puppeteer = require('puppeteer');

const main = async () => {
    const functionWithPagesInvocation = async (browser) => {
        const pages = await browser.pages().catch(e=>console.error("should catch error line 5",e));
        if (pages.length > 1) return pages[0].bringToFront();
    };
    const pool = [];
    for (let i = 0; i <= 5; i++) {
        const browser = await puppeteer.launch({ headless: false }).catch(e=>console.error("should catch error line 10",e));
        pool.push(browser);

        await browser.newPage();
        await functionWithPagesInvocation(browser).catch(e => console.error('Should catch error', e));
    }

    await Promise.all(pool.map(browser => browser.close()));
};

main().catch(e => console.error('Should atleast catch here', e));`
the above worked for me... 
@petrpatek so i think it throws you an unhandledPromiseRejection because the first error comes from **inside** the functionWithPagesInvocation (see the code above).Specifically the browser.pages().That is the promise (since it follows await) which is rejected and indeed you are not handling it... Now the "outer" promise, ie the functionWithPagesInvocation (which is also converted into a promise as soon as you add async) does handle the error, but only after it has passed through the original promise. I have adde the error handlers to all your promises just to be more visible...hope it helps...

**Comment by smapets** [comment]
@petrpatek so i think it throws you an unhandledPromiseRejection because the first error comes from inside the functionWithPagesInvocation (see the code below).Specifically the browser.pages().That is the promise (since it follows await) which is rejected and indeed you are not handling it... Now the "outer" promise, ie the functionWithPagesInvocation (which is also converted into a promise as soon as you add async) does handle the error, but only after it has passed through the original promise. I have added the error handlers to all your promises just to be more visible...hope it helps...
@wpitallo 
```const puppeteer = require('puppeteer');

const main = async () => {
    const functionWithPagesInvocation = async (browser) => {
        const pages = await browser.pages().catch(e=>console.error("should catch error lin 5",e));
        if (pages.length > 1) return pages[0].bringToFront();
    };
    const pool = [];
    for (let i = 0; i <= 5; i++) {
        const browser = await puppeteer.launch({ headless: false }).catch(e=>console.error("should catch error lin 10",e));
        pool.push(browser);

        await browser.newPage();
        await functionWithPagesInvocation(browser).catch(e => console.error('Should catch error', e));
    }

    await Promise.all(pool.map(browser => browser.close()));
};

main().catch(e => console.error('Should atleast catch here', e));
```
the above works for me... just add the await before the functionWithPagesInvocation
