### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Protocol error (Performance.enable): Target closed.

### ISSUE THREAD

**Issue by wpitallo** [puppeteer/puppeteer#5290]
When running this example:

const puppeteer = require('puppeteer');

(async () => {
  console.info('start')
  const browser = await puppeteer.launch({ headless: false });
  console.info('launch')
  const page = await browser.newPage();
  console.info('newPage')
  await page.goto('https://pptr.dev');
  console.info('goto')
  // Waits until the `title` meta element is rendered
  await page.waitForSelector('title');
  
  const title = await page.title();
  console.info(`The title is: ${title}`);

  await browser.close();
})();

I get the the following exception:

(node:35300) UnhandledPromiseRejectionWarning: Error: Page crashed!
    at Page._onTargetCrashed (D:\Development\alpha\tests\testSystem\puppeteer\node_modules\puppeteer\lib\Page.js:216:24)
    at CDPSession.<anonymous> (D:\Development\alpha\tests\testSystem\puppeteer\node_modules\puppeteer\lib\Page.js:124:56)
    at CDPSession.emit (events.js:223:5)
    at CDPSession._onMessage (D:\Development\alpha\tests\testSystem\puppeteer\node_modules\puppeteer\lib\Connection.js:200:12)
    at Connection._onMessage (D:\Development\alpha\tests\testSystem\puppeteer\node_modules\puppeteer\lib\Connection.js:112:17)
    at WebSocket.<anonymous> (D:\Development\alpha\tests\testSystem\puppeteer\node_modules\puppeteer\lib\WebSocketTransport.js:44:24)
    at WebSocket.onMessage (D:\Development\alpha\tests\testSystem\puppeteer\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (events.js:223:5)
    at Receiver.receiverOnMessage (D:\Development\alpha\tests\testSystem\puppeteer\node_modules\ws\lib\websocket.js:789:20)
    at Receiver.emit (events.js:223:5)
(node:35300) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:35300) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:35300) UnhandledPromiseRejectionWarning: Error: Page crashed!
    at Page._onTargetCrashed (D:\Development\alpha\tests\testSystem\puppeteer\node_modules\puppeteer\lib\Page.js:216:24)
    at CDPSession.<anonymous> (D:\Development\alpha\tests\testSystem\puppeteer\node_modules\puppeteer\lib\Page.js:124:56)
    at CDPSession.emit (events.js:223:5)
    at CDPSession._onMessage (D:\Development\alpha\tests\testSystem\puppeteer\node_modules\puppeteer\lib\Connection.js:200:12)
    at Connection._onMessage (D:\Development\alpha\tests\testSystem\puppeteer\node_modules\puppeteer\lib\Connection.js:112:17)
    at WebSocket.<anonymous> (D:\Development\alpha\tests\testSystem\puppeteer\node_modules\puppeteer\lib\WebSocketTransport.js:44:24)
    at WebSocket.onMessage (D:\Development\alpha\tests\testSystem\puppeteer\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (events.js:223:5)
    at Receiver.receiverOnMessage (D:\Development\alpha\tests\testSystem\puppeteer\node_modules\ws\lib\websocket.js:789:20)
    at Receiver.emit (events.js:223:5)
(node:35300) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:35300) UnhandledPromiseRejectionWarning: Error: Protocol error (Performance.enable): Target closed.
    at D:\Development\alpha\tests\testSystem\puppeteer\node_modules\puppeteer\lib\Connection.js:183:56
    at new Promise (<anonymous>)
    at CDPSession.send (D:\Development\alpha\tests\testSystem\puppeteer\node_modules\puppeteer\lib\Connection.js:182:12)
    at Page._initialize (D:\Development\alpha\tests\testSystem\puppeteer\node_modules\puppeteer\lib\Page.js:138:20)
    at Function.create (D:\Development\alpha\tests\testSystem\puppeteer\node_modules\puppeteer\lib\Page.js:48:16)
    at D:\Development\alpha\tests\testSystem\puppeteer\node_modules\puppeteer\lib\Target.js:74:32
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async Browser._createPageInContext (D:\Development\alpha\tests\testSystem\puppeteer\node_modules\puppeteer\lib\Browser.js:177:18)
    at async D:\Development\alpha\tests\testSystem\puppeteer\run-tests.js:7:16
  -- ASYNC --
    at Target.<anonymous> (D:\Development\alpha\tests\testSystem\puppeteer\node_modules\puppeteer\lib\helper.js:111:15)
    at Browser._createPageInContext (D:\Development\alpha\tests\testSystem\puppeteer\node_modules\puppeteer\lib\Browser.js:177:31)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async D:\Development\alpha\tests\testSystem\puppeteer\run-tests.js:7:16
  -- ASYNC --
    at Browser.<anonymous> (D:\Development\alpha\tests\testSystem\puppeteer\node_modules\puppeteer\lib\helper.js:111:15)
    at D:\Development\alpha\tests\testSystem\puppeteer\run-tests.js:7:30
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:35300) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)

**Comment by bboydflo** [comment]
@wpitallo have you fixed your issue? I have a similar issue and still struggling with it.

**Comment by deadcoder0904** [comment]
Same

**Comment by bboydflo** [comment]
My issue was related to running puppeteer on macos and some certificate issues. Something related to codesign. There is a related issue which gives a good solution here on github. Try to search for codesign in issues ;) I hope it helps.

**Comment by deadcoder0904** [comment]
@bboydflo Thank you. I solved it via wrapping with `catch` blocks after the end of promises. Puppeteer is really weird or should I say programming 😜

**Comment by wpitallo** [comment]
Same issue, I manged to get a workaround by downloading the latest chromium and then setting the path to the new version. Not ideal tho

**Comment by matAtWork** [comment]
I have the same issue, both MacOS & Ubuntu 16.04. Puppeteer 2.1.1 - no problem with 2.0.0 (untested on Windows)

Specifically, `launch` sends a request down the dev socket, and the response causes an exception under some circumstances, so the promise for launch never resolves and the unhandled exception is reported. Although it's possible to ignore the unhandled exception, of course the app layer above "hangs" on the unresolved promise returned by `launch` for ever.

```
Error: Page crashed!

emit (events.js:292)
EventEmitter.emit (domain.js:485)
_onTargetCrashed (Page.js:213)
(anonymous) (Page.js:122)
emit (events.js:315)
EventEmitter.emit (domain.js:485)
_onMessage (Connection.js:200)
_onMessage (Connection.js:112)
(anonymous) (WebSocketTransport.js:44)
onMessage (event-target.js:120)
emit (events.js:315)
EventEmitter.emit (domain.js:485)
receiverOnMessage (websocket.js:789)
emit (events.js:315)
EventEmitter.emit (domain.js:485)
dataMessage (receiver.js:422)
getData (receiver.js:352)
startLoop (receiver.js:138)
_write (receiver.js:74)
doWrite (_stream_writable.js:392)
writeOrBuffer (_stream_writable.js:374)
Writable.write (_stream_writable.js:314)
socketOnData (websocket.js:864)
emit (events.js:315)
EventEmitter.emit (domain.js:485)
addChunk (_stream_readable.js:297)
readableAddChunk (_stream_readable.js:273)
Readable.push (_stream_readable.js:214)
onStreamRead (internal/stream_base_commons.js:186)
TCPWRAP (async)
--- ASYNC ---
init (internal/inspector_async_hook.js:25)
emitInitNative (internal/async_hooks.js:144)
Socket.connect (net.js:959)
connect (net.js:184)
netConnect (websocket.js:684)
ClientRequest (_http_client.js:308)
request (http.js:46)
get (http.js:50)
initAsClient (websocket.js:555)
WebSocket (websocket.js:70)
(anonymous) (WebSocketTransport.js:28)
create (WebSocketTransport.js:27)
setupConnection (Launcher.js:168)
processTicksAndRejections (internal/process/task_queues.js:97)
--- ASYNC ---
await in processTicksAndRejections (async)
launch (Launcher.js:245)
--- ASYNC ---
await in launch (async)
launch (Puppeteer.js:40)
createPageAsync (PagePool.ts:101)
...
...
```
