### ISSUE TITLE
Unable to `npm install` on macOS Sierra

### ISSUE THREAD

**Issue by kaushik94** [puppeteer/puppeteer#531]
According to [CONTRIBUTING.md](https://github.com/GoogleChrome/puppeteer/blob/master/CONTRIBUTING.md) I cloned the repo and ran `npm install`. It errors out with following message
```
module.js:491
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/unsupported.js:2:14)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
```
I am using node version `8.4.0`.

**Comment by aslushnikov** [comment]
What's your npm version?

**Comment by kaushik94** [comment]
@aslushnikov you are right, turns out an issue with my npm. It works now after reinstalling npm from source.
