### ISSUE TITLE
Error: Protocol error (Page.captureScreenshot): Unable to capture screenshot when taking screenshot of a large viewport

### ISSUE THREAD

**Issue by bmblb** [puppeteer/puppeteer#5341]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.0.0
* Platform / OS version: Windows 10 1903 x64
* Node.js version: 10.17

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

Here is a code snippet that sets large viewport and is trying to take screenshot of that
```
// test.js
const puppeteer = require('puppeteer');

class Server {
    async setup() {
        if (!this.browser) {
            this.browser = await puppeteer.launch();
        }
    }
    
    async export() {
        try {
            await this.setup();
    
            const me = this;
    
            const page = await this.browser.newPage();
    
            page.on('error', e => {
                throw e;
            });
    
            await page.setContent('<html><head></head><body><h1>test</h1></body></html>');
    
            await page.setViewport({
                width : 10000,
                height : 50000
            });
            await page.emulateMedia('print');
    
            await page.screenshot({
                deviceScaleFactor : 4
            });
    
            await this.browser.close();
    
            console.log('browser closed');
        }
        catch (e) {
            await this.browser.close();
            
            throw e;
        }
    }
}

const srv = new Server();

srv.export()
    .then(() => process.exit())
    .catch(e => {
        process.exit(1);
    });
```

**What is the expected result?**
Screenshot taken

**What happens instead?**
Exception thrown
```
Error: Protocol error (Page.captureScreenshot): Unable to capture screenshot
 at Promise (...server\node_modules\puppeteer\lib\Connection.js:183:56) 
 at new Promise (<anonymous>)
 at CDPSession.send (...server\node_modules\puppeteer\lib\Connection.js:182:12)
 at Page._screenshotTask (...server\node_modules\puppeteer\lib\Page.js:951:39)
 at process._tickCallback (internal/process/next_tick.js:68:7) -- ASYNC --
 at Page.<anonymous> (...server\node_modules\puppeteer\lib\helper.js:111:15)
 at Server.export (...server\src\utils\screenshot.js:34:24)
 at process._tickCallback (internal/process/next_tick.js:68:7)
```

Initially I got that exception from a puppeteer which was launched from node express request handler. It failed to take a screenshot of size 700x25000 with same exception. So I tried to figure what's going on and wrote this test script, which worked just fine with same html and same size of the viewport.
Then I tried to increase viewport to some ridiculous number and reproduced the problem.

So screenshot fails inside node express request handler on a viewport 700x25000
and fails outside of the node express but at much higher viewport size, like 10000x50000

So questions are:
1. Is there a limit to screenshot size which can be taken?
2. If so, how can I calculate that limit? 
3. Is there a safe value for viewport?
4. Can you suggest a way to take screenshots of large pages? What comes to my mind is to play with `trasnform: scale()` to fit content into some reasonable viewport, e.g. UHD

**Comment by MissiaL** [comment]
Any updates? I have the same problem
So. After my research, the working solution was to roll back to version **1.20.0**

**Comment by brumeregan** [comment]
I'm also having this problem =(

**Comment by Mattwmaster58** [comment]
My guess is that you are nearing the sending/receive limit of websocket messages. I don't know them off the top of my head, but I'm guessing it's either 100Mb or 256Mb.

**Comment by y573724537** [comment]
Any idea? I got this error too.

**Comment by y573724537** [comment]
puppeteer  version: 2.1.0
OS: centos
Node.js version: v12.15.0

**Comment by Mattwmaster58** [comment]
If anyone wants to test my theory, I'd recommend looping around, taking a screenshot, logging the screenshot's size, and increasing the viewport.

**Comment by danstarns** [comment]
Puppeteer 3.0.4
FROM node:12-slim
Using ```--window-size=2480,3508```
I tried ```--disable-dev-shm-usage``` No luck! 

FIX:
I had content that contained `<script>` tags & puppeteer reasonably refused to render them

**Comment by fchwpo** [comment]
Any update on this issue

**Comment by NikolaiSilver** [comment]
I have the same problem, any updates?

**Comment by Mathgobbo** [comment]
So many questions...
... but no answers

**Comment by snehalkulkarni20** [comment]
I am seeing similar issues. Any update on this ?

Puppeteer - latest version
Executing on Headless Chrome

`Error: Protocol error (Page.captureScreenshot): Cannot take screenshot with 0 width.
    at /mnt/tmp/local.prod/source/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:208:63
    at CDPSession.send (/mnt/tmp/local.prod/source/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:207:16)
    at Page._screenshotTask (/mnt/tmp/local.prod/source/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:1092:43)`

**Comment by StephenLover** [comment]
Hi I am experiencing the same issue, any update?

`Error: Error: Protocol error (Page.captureScreenshot): Unable to capture screenshot`

**Comment by Mattwmaster58** [comment]
[Here's where the error is raised in the Chrome source code](https://source.chromium.org/chromium/chromium/src/+/master:content/browser/devtools/protocol/page_handler.cc;l=1122?q=%22Unable%20to%20capture%20screenshot%22&ss=chromium), I think. This makes it seems like a Chrome issue.

**Comment by whoisjuan** [comment]
Seeing this error in long viewports as well.

**Comment by Ennazk** [comment]
Same here. Can't take a screenshot of a large viewport.

**Comment by caramdache** [comment]
Same here.

**Comment by ArtTkachenko** [comment]
Same here. 
Centos 7,
Puppeteer 8.0.0
Issue on production setup (2 cores, 7 gb RAM, not Docker container), locally and in Docker container will take bigger screenshots than on production. 

Run puppeteer with puppeteer-cluster.
Puppeteer launch config:

`{
    dumpio: true,
    args: [
        '--no-sandbox',
        '--disable-web-security',
        '--disable-gpu',
        '--disable-setuid-sandbox',
        '--disable-dev-shm-usage',
        '--full-memory-crash-report',
        '--enable-crash-reporter',
        '--crash-dumps-dir=/tmp/chrome',
        '--unlimited-storage',
        '--ignore-certificate-errors'
    ],
    defaultViewport: {
        width: 1920,
        height: 1080,
        deviceScaleFactor: 2
    }
}`

Errors:

**Protocol error (Page.captureScreenshot): Unable to capture screenshot)**

From dumpio got next messages:

ERROR:browser_child_process_host_impl.cc(747)] Terminating child process for bad message: Received bad user message: Validation failed for viz.mojom.CopyOutputResultSender.0  [VALIDATION_ERROR_DESERIALIZATION_FAILED]
WARNING:gpu_process_host.cc(1296)] The GPU process has crashed 1 time(s)
Dec 02 03:25:44 app-charts-renderer-1 node[3164]

**Comment by ArtTkachenko** [comment]
@bmblb Did you solve (somehow) this issue?

**Comment by guilhermebentomarques** [comment]
same here

**Comment by Gvozdik-Darya** [comment]
проблема досих пор актуальна

**Comment by Gvozdik-Darya** [comment]
the problem is still relevant

**Comment by ArtTkachenko** [comment]
Confirm, problem still actual.

**Comment by roysG** [comment]
Still hapenning

**Comment by skinfans** [comment]
The problem is actual

**Comment by Zebraslive** [comment]
wtf. just randomly started happening. i was using my script literally minutes before and now i can't use it at all. no idea what's changed.

**Comment by ArtTkachenko** [comment]
Hi everyone! Seems to be i found problem, as i understand for browser rendering important free space in temp directory for shared memory (on centos it's /temp or /dev/shm dir).
In puppeteer launch options add  [**dumpio:true**](https://pptr.dev/#?product=Puppeteer&version=v13.7.0&show=api-puppeteerlaunchoptions) -option, and if in time when puppeteer open page/render you've got error, something like this:

**[WARNING:discardable_shared_memory_manager.cc(197)] Less than 64MB of free space in temporary directory for shared memory files: 29**

or 
**ERROR:file_io.cc(140)] write: No space left on device (28)**

It's mean that you should increase tmp directory size.
To check how much memory you`ve got
type in terminal command "**df -h**" and take a look to tmp dirs available size.

![image](https://user-images.githubusercontent.com/79413084/166903403-aa247b4e-3648-4d5d-8d4a-f64868633e15.png)

Hope it will help you. Cheers.

**Comment by AmanSin001** [comment]
> Hi everyone! Seems to be i found problem, as i understand for browser rendering important free space in temp directory for shared memory (on centos it's /temp or /dev/shm dir). In puppeteer launch options add [**dumpio:true**](https://pptr.dev/#?product=Puppeteer&version=v13.7.0&show=api-puppeteerlaunchoptions) -option, and if in time when puppeteer open page/render you've got error, something like this:
> 
> **[WARNING:discardable_shared_memory_manager.cc(197)] Less than 64MB of free space in temporary directory for shared memory files: 29**
> 
> or **ERROR:file_io.cc(140)] write: No space left on device (28)**
> 
> It's mean that you should increase tmp directory size. To check how much memory you`ve got type in terminal command "**df -h**" and take a look to tmp dirs available size.
> 
> ![image](https://user-images.githubusercontent.com/79413084/166903403-aa247b4e-3648-4d5d-8d4a-f64868633e15.png)
> 
> Hope it will help you. Cheers.

This is working properly

**Comment by alexlonginc** [comment]
This doesn't address the underlying issue but I was getting this error and found that when I removed the `fullPage: true` parameter from the `screenshot` call the error went away and I was able to take screenshots without issue.

**Comment by ki412412** [comment]
I tried the same method as @alexlonginc mentioned and the error no longer occurred.

**Comment by OrKoN** [comment]
I believe there could be a limit on the browser side about how big a screenshot can be. We will need to investigate.

**Comment by Frontesque** [comment]
> This doesn't address the underlying issue but I was getting this error and found that when I removed the `fullPage: true` parameter from the `screenshot` call the error went away and I was able to take screenshots without issue.

thank you so much!!

**Comment by ki412412** [comment]
This issue is reported on the chrome dev community as well and it is still open.
https://bugs.chromium.org/p/chromium/issues/detail?id=770769&desc=2

**Comment by shubham-scaletech** [comment]
> Hi everyone! Seems to be i found problem, as i understand for browser rendering important free space in temp directory for shared memory (on centos it's /temp or /dev/shm dir). In puppeteer launch options add [**dumpio:true**](https://pptr.dev/#?product=Puppeteer&version=v13.7.0&show=api-puppeteerlaunchoptions) -option, and if in time when puppeteer open page/render you've got error, something like this:
> 
> **[WARNING:discardable_shared_memory_manager.cc(197)] Less than 64MB of free space in temporary directory for shared memory files: 29**
> 
> or **ERROR:file_io.cc(140)] write: No space left on device (28)**
> 
> It's mean that you should increase tmp directory size. To check how much memory you`ve got type in terminal command "**df -h**" and take a look to tmp dirs available size.
> 
> ![image](https://user-images.githubusercontent.com/79413084/166903403-aa247b4e-3648-4d5d-8d4a-f64868633e15.png)
> 
> Hope it will help you. Cheers.

I was running pupeteer on lambda function and i got same error. for me this worked. i increased ephemeral storage of lambda.

**Comment by tedyyu** [comment]
Still happens to "puppeteer": "^22.6.0" (npm) in 2024.

Removing fullPage:true will get a truncated screenshot, not as intended :-)

After wasting one day, I observed that it's related to the hardware. The same web page can be captured with fullPage screenshot on powerful machines but failed on another Azure B1s VM (1 vcpu, 1 GB memory). The same for Playwright. Therefore I can conclude it's a chromium issue.

**Comment by daveroberts** [comment]
> The same web page can be captured with fullPage screenshot on powerful machines

@tedyyu : To be clear, do you mean powerful machines running in Azure, or not in the cloud?

**Comment by tedyyu** [comment]
> > The same web page can be captured with fullPage screenshot on powerful machines
> 
> @tedyyu : To be clear, do you mean powerful machines running in Azure, or not in the cloud?

Hi, 
It doesn't matter at all where the power machine is. 
In my example, my ec2 VM (actually after I check, it's a t2.micro: 1vcpu, 1GiB running Ubuntu 20.04), which is not that powerful, works well, and my powerful M2 mac is good too.
Failed azure VM is Ubuntu 22.04, I have avoid to use it for taking screenshot of a long mobile page.

**Comment by epDHowwD** [comment]
No new info here, just summary with some details of what was already said.

### Summary

I found in `render.js` (for me in `/usr/local/lib/node_modules/svgexport/`) one can change `launch` of puppeteer to add extra options:

``` js
  var browser = await puppeteer.launch({
    headless: true,
    dumpio: true,
    args: ['--no-sandbox', '--font-render-hinting=none', '--force-gpu-mem-available-mb=4096']
  });
```

Adding `dumpio: true,` helped me to see my particular problem when rendering (for me) x4 which was that the image was only partially rendered in this scale:

```
[0511/144557.523227:ERROR:tile_manager.cc(793)] WARNING: tile memory limits exceeded, some content may not draw
```

Adding `'--force-gpu-mem-available-mb=4096'` helped me to fix this. (This came from [here](https://github.com/puppeteer/puppeteer/issues/5530#issuecomment-605047166)).

Beginning with x7 I get a crash of the graphic driver:
```
[0511/150628.898206:ERROR:validation_errors.cc(76)] Invalid message: VALIDATION_ERROR_DESERIALIZATION_FAILED (viz.mojom.CopyOutputResultSender.0 )
[0511/150628.899182:ERROR:browser_child_process_host_impl.cc(726)] Terminating child process for bad message: Received bad user message: Validation failed for viz.mojom.CopyOutputResultSender.0  [VALIDATION_ERROR_DESERIALIZATION_FAILED (viz.mojom.CopyOutputResultSender.0 )]
[0511/150629.356837:WARNING:gpu_process_host.cc(1217)] The GPU process has crashed 1 time(s)
[0511/150629.716893:WARNING:gpu_process_host.cc(980)] Reinitialized the GPU process after a crash. The reported initialization time was 290 ms
[0511/150800.959810:ERROR:validation_errors.cc(76)] Invalid message: VALIDATION_ERROR_DESERIALIZATION_FAILED (viz.mojom.CopyOutputResultSender.0 )
[0511/150800.959883:ERROR:browser_child_process_host_impl.cc(726)] Terminating child process for bad message: Received bad user message: Validation failed for viz.mojom.CopyOutputResultSender.0  [VALIDATION_ERROR_DESERIALIZATION_FAILED (viz.mojom.CopyOutputResultSender.0 )]
[0511/150801.238527:WARNING:gpu_process_host.cc(1217)] The GPU process has crashed 2 time(s)
[0511/150801.587723:WARNING:gpu_process_host.cc(980)] Reinitialized the GPU process after a crash. The reported initialization time was 278 ms
Error: Protocol error (Page.captureScreenshot): Unable to capture screenshot
```
... just as [said earlier](https://github.com/puppeteer/puppeteer/issues/5341#issuecomment-984696563).

**Comment by PremExtensi** [comment]
In my case I managed to fix the issue with a wait function.

I've been testing all suggested settings like

` args: ['--no-sandbox', '--font-render-hinting=none', '--force-gpu-mem-available-mb=4096', '--disable-gpu']`

but that didn't help - results were random. 

That code always work without errors.
```

...
    await wait(100);
    await page.screenshot({
        fullPage: true,
        optimizeForSpeed: true,
        path: destDir + await getNextImgCnt() + expect.getState().currentTestName +"--"+ filename + ".png"
    });
    await wait(100);
...

export async function wait(timeout) {
    await new Promise((r) => setTimeout(r, timeout));
}

```

**Comment by BrunnoBSB** [comment]
Boa noite! no meu caso segue o violão da historia.

 Take Screenshot       fullPage=${true}    
 
 Resolução pra mim.
 
 Take Screenshot       #fullPage=${true}    
 
 comentado o parametro da FULLPAGE.

**Comment by pr0pz** [comment]
Ok guys, I managed to fix my issue. For me it was related to the headless mode.
After v22, puppeteer is using the new chrome headless mode and I needed to change to the old headless mode aka chrome-headless-shell.

Launch p with the headless arg:
```js
const browser = await puppeteer.launch( { headless: 'shell' } );
```

Documentation:
https://pptr.dev/guides/headless-modes
https://developer.chrome.com/blog/chrome-headless-shell
