### ISSUE TITLE
UnknownMethodError Page.setInterceptFileChooserDialog

### ISSUE THREAD

**Issue by mikhasd** [puppeteer/puppeteer#5357]
### Steps to reproduce

Just tried puppeteer for the first time, with Firefox and got this error...

**Tell us about your environment:**

* Puppeteer version: 2.1.0
* Platform / OS version: Windows 10
* Node.js version: v12.9.1
* Firefox Version: 72.0.2 (64-bits)

**What steps will reproduce the problem?**

```javascript
process.env.DEBUG = "puppeteer:protocol";

const puppeteer = require('puppeteer');

(async function main(){
  
  const browser = await puppeteer.launch({
    product: "firefox",
    executablePath: "C:\\Program Files\\Mozilla Firefox\\firefox.exe"
  });

  try {
    await browser.newPage();
  } catch (err) {
    console.error('Error while opening page', err);
  }

  await browser.close();
})()
```

**What happens instead?**

Got an error.

```
C:\dev\node-v12.9.1-win-x64\node.exe --inspect-brk=30808 test.js 
Debugger listening on ws://127.0.0.1:30808/29af9084-6348-471f-a963-af4272a75801

For help, see: https://nodejs.org/en/docs/inspector

Debugger attached.

2020-01-28T22:29:43.970Z puppeteer:protocol SEND ► {"method":"Target.setDiscoverTargets","params":{"discover":true},"id":1}
2020-01-28T22:29:43.976Z puppeteer:protocol ◀ RECV {"method":"Target.targetCreated","params":{"targetInfo":{"browserContextId":null,"targetId":10,"type":"page","url":"about:blank"}}}
2020-01-28T22:29:43.978Z puppeteer:protocol ◀ RECV {"method":"Target.targetCreated","params":{"targetInfo":{"targetId":"8b3bcb2a-7238-437a-bbdf-8bf45efb96a3","type":"browser"}}}
2020-01-28T22:29:43.979Z puppeteer:protocol ◀ RECV {"id":1}
2020-01-28T22:29:43.980Z puppeteer:protocol SEND ► {"method":"Target.createTarget","params":{"url":"about:blank"},"id":2}
2020-01-28T22:29:43.989Z puppeteer:protocol ◀ RECV {"method":"Target.targetCreated","params":{"targetInfo":{"browserContextId":null,"targetId":12,"type":"page","url":"about:blank"}}}
2020-01-28T22:29:44.007Z puppeteer:protocol ◀ RECV {"id":2,"result":{"targetId":12}}
2020-01-28T22:29:44.011Z puppeteer:protocol SEND ► {"method":"Target.attachToTarget","params":{"targetId":12,"flatten":true},"id":3}
2020-01-28T22:29:44.026Z puppeteer:protocol ◀ RECV {"method":"Target.attachedToTarget","params":{"targetInfo":{"type":"page"},"sessionId":1}}
2020-01-28T22:29:44.027Z puppeteer:protocol ◀ RECV {"id":3,"result":{"sessionId":1}}
2020-01-28T22:29:44.029Z puppeteer:protocol SEND ► {"sessionId":1,"method":"Page.enable","params":{},"id":4}
2020-01-28T22:29:44.029Z puppeteer:protocol SEND ► {"sessionId":1,"method":"Page.getFrameTree","params":{},"id":5}
2020-01-28T22:29:44.030Z puppeteer:protocol SEND ► {"sessionId":1,"method":"Target.setAutoAttach","params":{"autoAttach":true,"waitForDebuggerOnStart":false,"flatten":true},"id":6}
2020-01-28T22:29:44.031Z puppeteer:protocol SEND ► {"sessionId":1,"method":"Performance.enable","params":{},"id":7}
2020-01-28T22:29:44.031Z puppeteer:protocol SEND ► {"sessionId":1,"method":"Log.enable","params":{},"id":8}
2020-01-28T22:29:44.032Z puppeteer:protocol SEND ► {"sessionId":1,"method":"Page.setInterceptFileChooserDialog","params":{"enabled":true},"id":9}
2020-01-28T22:29:44.033Z puppeteer:protocol ◀ RECV {"sessionId":1,"id":6}
2020-01-28T22:29:44.036Z puppeteer:protocol ◀ RECV {"sessionId":1,"id":4}
2020-01-28T22:29:44.036Z puppeteer:protocol ◀ RECV {"sessionId":1,"id":5,"result":{"frameTree":{"frame":{"id":25,"url":"about:blank","loaderId":null,"securityOrigin":null,"mimeType":null},"childFrames":[]}}}
2020-01-28T22:29:44.038Z puppeteer:protocol SEND ► {"sessionId":1,"method":"Page.setLifecycleEventsEnabled","params":{"enabled":true},"id":10}
2020-01-28T22:29:44.038Z puppeteer:protocol SEND ► {"sessionId":1,"method":"Runtime.enable","params":{},"id":11}
2020-01-28T22:29:44.039Z puppeteer:protocol SEND ► {"sessionId":1,"method":"Network.enable","params":{},"id":12}
2020-01-28T22:29:44.040Z puppeteer:protocol ◀ RECV {"sessionId":1,"id":7}
2020-01-28T22:29:44.045Z puppeteer:protocol ◀ RECV {"sessionId":1,"id":12}
2020-01-28T22:29:44.046Z puppeteer:protocol ◀ RECV {"sessionId":1,"id":8}
2020-01-28T22:29:44.046Z puppeteer:protocol ◀ RECV {"id":9,"sessionId":1,"error":{"message":"Page.setInterceptFileChooserDialog","data":"RemoteAgentError@chrome://remote/content/Error.jsm:25:5\nUnknownMethodError@chrome://remote/content/Error.jsm:108:7\nexecute@chrome://remote/content/domains/Domains.jsm:96:13\nreceiveMessage@chrome://remote/content/sessions/ContentProcessSession.jsm:69:45\n"}}
2020-01-28T22:29:44.046Z puppeteer:protocol ◀ RECV {"sessionId":1,"id":10}

null: Error while opening page
null: Error: Protocol error (Page.setInterceptFileChooserDialog): Page.setInterceptFileChooserDialog RemoteAgentError@chrome://remote/content/Error.jsm:25:5
```

**Comment by mathiasbynens** [comment]
It looks like you're using Firefox 72. The experimental support for Firefox works best with Firefox Nightly (currently 74).

cc @mjzffr who's the expert here

**Comment by mayank** [comment]
@mathiasbynens getting this error with chrome also.

```
{ Error: Protocol error (Page.setInterceptFileChooserDialog): Cannot enable file chooser interception because other protocol client already intercepts it
    at Promise (/var/app/current/node_modules/puppeteer-core/lib/Connection.js:183:56)
    at new WrappedPromise (/var/app/current/node_modules/async-listener/es6-wrapped-promise.js:13:18)
    at CDPSession.send (/var/app/current/node_modules/puppeteer-core/lib/Connection.js:182:12)
    at Page._initialize (/var/app/current/node_modules/puppeteer-core/lib/Page.js:138:20)
    at Function.create (/var/app/current/node_modules/puppeteer-core/lib/Page.js:47:16)
    at _pagePromise._sessionFactory.then.client (/var/app/current/node_modules/puppeteer-core/lib/Target.js:74:32)
    at propagateAslWrapper (/var/app/current/node_modules/async-listener/index.js:504:23)
    at /var/app/current/node_modules/async-listener/index.js:541:70
    at /var/app/current/node_modules/async-listener/glue.js:188:31
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
    at process.fallback (/var/app/current/node_modules/async-listener/index.js:565:15)
  -- ASYNC --
    at Target.<anonymous> (/var/app/current/node_modules/puppeteer-core/lib/helper.js:111:15)
    at Browser._createPageInContext (/var/app/current/node_modules/puppeteer-core/lib/Browser.js:177:31)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
    at process.fallback (/var/app/current/node_modules/async-listener/index.js:565:15)
  -- ASYNC --
    at Browser.<anonymous> (/var/app/current/node_modules/puppeteer-core/lib/helper.js:111:15)
    at HTML2PDF.render (/var/app/current/node_modules/@roadzen/rusty-mould/src/services/html-pdf.js:51:38)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
    at process.fallback (/var/app/current/node_modules/async-listener/index.js:565:15)
  message: 'Protocol error (Page.setInterceptFileChooserDialog): Cannot enable file chooser interception because other protocol client already intercepts it' }
```

**Comment by mathiasbynens** [comment]
@mayank Which version of Puppeteer are you using? I cannot reproduce the Chrome issue with your above script:

```
process.env.DEBUG = "puppeteer:protocol";

const puppeteer = require('puppeteer');

(async function main(){
  
  const browser = await puppeteer.launch();

  try {
    await browser.newPage();
  } catch (err) {
    console.error('Error while opening page', err);
  }

  await browser.close();
})()
```

**Comment by mikhasd** [comment]
> It looks like you're using Firefox 72. The experimental support for Firefox works best with Firefox Nightly (currently 74).
> 
> cc @mjzffr who's the expert here

I haven't found any indication of what FF version should be used. But that should be the root cause.

**Comment by peterdanis** [comment]
I've got the same error while connecting Puppeteer to Electron 5.x.x and 6.x.x. 
![image](https://user-images.githubusercontent.com/26599181/73434970-05121980-4348-11ea-9e49-9729ce07b18e.png)

**Comment by Metroxe** [comment]
Having the same issue with Chrome. It happens as soon as I call newPage

```typescript
const browser = await puppeteer.launch({
	headless: true,
	args: ['--disable-dev-shm-usage', '--no-sandbox', '--disable-gpu', '--disable-setuid-sandbox'],
	executablePath: process.env.CHROME_BIN || null,
});
await browser.newPage();
```

```
Error: Protocol error (Page.setInterceptFileChooserDialog): 'Page.setInterceptFileChooserDialog' wasn't found
asset-generation-service_1  |     at Promise (/usr/src/asset-generation-service/node_modules/puppeteer/lib/Connection.js:183:56)
asset-generation-service_1  |     at new Promise (<anonymous>)
asset-generation-service_1  |     at CDPSession.send (/usr/src/asset-generation-service/node_modules/puppeteer/lib/Connection.js:182:12)
asset-generation-service_1  |     at Page._initialize (/usr/src/asset-generation-service/node_modules/puppeteer/lib/Page.js:138:20)
asset-generation-service_1  |     at Function.create (/usr/src/asset-generation-service/node_modules/puppeteer/lib/Page.js:47:16)
asset-generation-service_1  |     at _pagePromise._sessionFactory.then.client (/usr/src/asset-generation-service/node_modules/puppeteer/lib/Target.js:74:32)
asset-generation-service_1  |     at process._tickCallback (internal/process/next_tick.js:68:7)
asset-generation-service_1  |   -- ASYNC --
asset-generation-service_1  |     at Target.<anonymous> (/usr/src/asset-generation-service/node_modules/puppeteer/lib/helper.js:111:15)
asset-generation-service_1  |     at Browser._createPageInContext (/usr/src/asset-generation-service/node_modules/puppeteer/lib/Browser.js:177:31)
asset-generation-service_1  |     at process._tickCallback (internal/process/next_tick.js:68:7)
asset-generation-service_1  |   -- ASYNC --
asset-generation-service_1  |     at Browser.<anonymous> (/usr/src/asset-generation-service/node_modules/puppeteer/lib/helper.js:111:15)
asset-generation-service_1  |     at Object.generatePDF [as default] (/usr/src/asset-generation-service/src/utils/GeneratePDF.ts:24:16)
asset-generation-service_1  |     at process._tickCallback (internal/process/next_tick.js:68:7)
```

I'm running in Docker with quite a few other dependencies
```Dockerfile
FROM node:10.16.3-alpine

# Chromium dependencies
RUN apk add --no-cache \
      chromium \
      nss \
      freetype \
      freetype-dev \
      harfbuzz \
      ca-certificates \
      ttf-freefont \
      nodejs \
      yarn

RUN addgroup -S pptruser && adduser -S -g pptruser pptruser \
    && mkdir -p /home/pptruser/Downloads /app \
    && chown -R pptruser:pptruser /home/pptruser \
    && chown -R pptruser:pptruser /app

ENV CHROME_BIN="/usr/bin/chromium-browser" \
	PUPPETEER_SKIP_CHROMIUM_DOWNLOAD="true"

# Canvas dependencies
RUN apk add --no-cache \
	sudo \
	curl \
	build-base \
	g++ \
	libpng \
	libpng-dev \
	jpeg-dev \
	pango-dev \
	cairo-dev \
	giflib-dev \
	python

#  add glibc and install canvas
RUN apk --no-cache add ca-certificates wget  && \
	wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub && \
	wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.29-r0/glibc-2.29-r0.apk && \
	apk add glibc-2.29-r0.apk && \
	npm install canvas@2.5.0

## installation
WORKDIR /usr/src/asset-generation-service
COPY ./asset-generation-service/package*.json ./
RUN npm install
RUN npm rebuild canvas --build-from-source
COPY ./asset-generation-service ./
RUN npm run build

EXPOSE 8080

CMD ["npm", "run", "start"]
```

**Comment by mjzffr** [comment]
> > It looks like you're using Firefox 72. The experimental support for Firefox works best with Firefox Nightly (currently 74).
> > cc @mjzffr who's the expert here
> 
> I haven't found any indication of what FF version should be used. But that should be the root cause.

Yes, that error should go away if you use Firefox Nightly (74).
