### ISSUE TITLE
Changes between v2.0.0 and v2.1.0 break integration with Browserless

### ISSUE THREAD

**Issue by gajus** [puppeteer/puppeteer#5359]
x-posting https://github.com/browserless/chrome/issues/548

**Comment by joelgriffith** [comment]
I'm not sure where it happened, possibly the new binary, but some of our "headful" tests aren't happy with the new bin. Wondering if there's been some Xvfb things as well

**Comment by joelgriffith** [comment]
Seems entirely to do with headful operation. The given script below (with all needed dependencies + Xvfb installed) errors out.

```js
const puppeteer = require('puppeteer');

async function run() {
  let browser = null;

  try {
    browser = await puppeteer.launch({ headless: false });
    const page = await browser.newPage();

    await page.goto('https://example.com');
    await page.screenshot({ path: './temp.png' });
  } catch (error) {
    console.log(error);
  } finally {
    browser && browser.close();
  }
}

run();

```

Output:

```sh
$ node index.js
{ Error: Protocol error (Page.captureScreenshot): Target closed.
    at Promise (/home/blessuser/chrome/node_modules/puppeteer/lib/Connection.js:183:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/home/blessuser/chrome/node_modules/puppeteer/lib/Connection.js:182:12)
    at Page._screenshotTask (/home/blessuser/chrome/node_modules/puppeteer/lib/Page.js:946:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  -- ASYNC --
    at Page.<anonymous> (/home/blessuser/chrome/node_modules/puppeteer/lib/helper.js:111:15)
    at run (/home/blessuser/chrome/index.js:13:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  message: 'Protocol error (Page.captureScreenshot): Target closed.' }
```

Digging deeper, the chrome binary itself outputs the following in headful:

```
$ ./chrome about:blank
[2494:2494:0130/222238.743265:ERROR:edid_parser.cc(102)] Too short EDID data: manufacturer id
[2494:2524:0130/222238.827646:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[2494:2524:0130/222238.861042:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[2494:2524:0130/222238.861273:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[2521:2521:0130/222238.886840:ERROR:angle_platform_impl.cc(40)] initialize(601): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
[2521:2521:0130/222238.887061:ERROR:gl_surface_egl.cc(690)] EGL Driver message (Critical) eglInitialize: glXQueryExtensionsString returned NULL
[2521:2521:0130/222238.887125:ERROR:gl_surface_egl.cc(1150)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[2521:2521:0130/222238.887298:ERROR:angle_platform_impl.cc(40)] initialize(601): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
[2521:2521:0130/222238.887370:ERROR:gl_surface_egl.cc(690)] EGL Driver message (Critical) eglInitialize: glXQueryExtensionsString returned NULL
[2521:2521:0130/222238.887414:ERROR:gl_surface_egl.cc(1150)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[2521:2521:0130/222238.887456:ERROR:gl_initializer_x11.cc(156)] GLSurfaceEGL::InitializeOneOff failed.
[2521:2521:0130/222238.894732:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[2494:2578:0130/222239.097364:ERROR:object_proxy.cc(632)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[2494:2578:0130/222239.098213:ERROR:object_proxy.cc(632)] Failed to call method: org.freedesktop.UPower.GetDisplayDevice: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[2494:2578:0130/222239.099481:ERROR:object_proxy.cc(632)] Failed to call method: org.freedesktop.UPower.EnumerateDevices: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[2539:2594:0130/222239.159450:FATAL:x11_util.cc(1312)] Unsupported visual with rgb mask 0x0, 0x0, 0x0.  Please report this to https://crbug.com/1025266
#0 0x564ff5ca2219 base::debug::CollectStackTrace()
#1 0x564ff5c06363 base::debug::StackTrace::StackTrace()
#2 0x564ff5c18195 logging::LogMessage::~LogMessage()
#3 0x564ff6644f05 ui::ColorTypeForVisual()
#4 0x564ff70a7892 ui::XShmImagePoolBase::Resize()
#5 0x564ff70a6a2d ui::X11SoftwareBitmapPresenter::Resize()
#6 0x564ff7017192 viz::DirectRenderer::DrawFrame()
#7 0x564ff7012530 viz::Display::DrawAndSwap()
#8 0x564ff7022730 viz::DisplayScheduler::DrawAndSwap()
#9 0x564ff702191d viz::DisplayScheduler::OnBeginFrameDeadline()
#10 0x564ff3ea47c3 base::internal::CancelableCallbackImpl<>::ForwardOnce<>()
#11 0x564ff5c4ed3b base::TaskAnnotator::RunTask()
#12 0x564ff5c5f8be base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl()
#13 0x564ff5c5f651 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoSomeWork()
#14 0x564ff5c1bffa base::MessagePumpDefault::Run()
#15 0x564ff5c60149 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run()
#16 0x564ff5c37a22 base::RunLoop::Run()
#17 0x564ff5c74077 base::Thread::ThreadMain()
#18 0x564ff5cb35be base::(anonymous namespace)::ThreadFunc()
#19 0x7f2aae7c06db start_thread
#20 0x7f2aa885a88f clone
Task trace:
#0 0x564ff70236bc viz::DisplayScheduler::ScheduleBeginFrameDeadline()
#1 0x564ff5ddc486 mojo::SimpleWatcher::Context::Notify()
IPC message handler context: 0x6B244812

Received signal 6
```

Now, on puppeter@2.0.0 (`r706915`), this outputs the following (and holds onto the process):

```sh
$ ./chrome about:blank
[2727:2756:0130/222529.669010:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[2727:2756:0130/222529.704822:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[2727:2756:0130/222529.705033:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[2753:2753:0130/222529.727453:ERROR:angle_platform_impl.cc(47)] initialize(593): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
[2753:2753:0130/222529.727689:ERROR:gl_surface_egl.cc(668)] EGL Driver message (Critical) eglInitialize: glXQueryExtensionsString returned NULL
[2753:2753:0130/222529.727759:ERROR:gl_surface_egl.cc(1115)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[2753:2753:0130/222529.728062:ERROR:angle_platform_impl.cc(47)] initialize(593): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
[2753:2753:0130/222529.728964:ERROR:gl_surface_egl.cc(668)] EGL Driver message (Critical) eglInitialize: glXQueryExtensionsString returned NULL
[2753:2753:0130/222529.729024:ERROR:gl_surface_egl.cc(1115)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[2753:2753:0130/222529.729067:ERROR:gl_initializer_x11.cc(156)] GLSurfaceEGL::InitializeOneOff failed.
[2753:2753:0130/222529.734604:ERROR:viz_main_impl.cc(180)] Exiting GPU process due to errors during initialization
[2727:2805:0130/222529.931734:ERROR:object_proxy.cc(632)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[2727:2805:0130/222529.932272:ERROR:object_proxy.cc(632)] Failed to call method: org.freedesktop.UPower.GetDisplayDevice: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[2727:2805:0130/222529.934456:ERROR:object_proxy.cc(632)] Failed to call method: org.freedesktop.UPower.EnumerateDevices: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
```

I've tried updating several package, but it appears even _those_ cause further issues, so I have to pin them [here](https://github.com/browserless/chrome/blob/master/base/Dockerfile#L69). At this point I think users can use pptr@2.1.0, but doing so in on Ubuntu 18.x.x doesn't seem to jive.

**Comment by joelgriffith** [comment]
Seems that rev `737027` doesn't have this problem

**Comment by mattzeunert** [comment]
I think this is the [related Chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1048386).
