### ISSUE TITLE
puppeteer-firefox win64 zip file isn't available for Windows users

### ISSUE THREAD

**Issue by rodoabad** [puppeteer/puppeteer#5371]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: NA
* Platform / OS version: Windows
* URLs (if applicable): NA
* Node.js version: NA

**What steps will reproduce the problem?**

`npm i puppeteer-firefox`
_Please include code that reproduces the issue._

```
ERROR: Failed to download Firefox rv0.0.1!
Error: Download failed: server returned code 404. URL: https://github.com/puppeteer/juggler/releases/download/v0.0.1/firefox-win64.zip
    ```

**What is the expected result?**

No errors.

**What happens instead?**

404 on `firefox-win64.zip`

**Comment by cheshrkat** [comment]
I suspect I'm hitting the same issue. To help investigation:

Puppeteer version 2.1.0
Platform: Windows 10 build 1909
Node version: 12.14.1

Attempting to install puppeteer-firefox in elevated Powershell. Expected installation to work; actual result is this error:

```
PS F:\dev\src\puppeteer> npm i puppeteer-firefox

> puppeteer-firefox@0.5.1 install F:\dev\src\puppeteer\node_modules\puppeteer-firefox
> node install.js

ERROR: Failed to download Firefox rv0.0.1!
Error: Download failed: server returned code 404. URL: https://github.com/puppeteer/juggler/releases/download/v0.0.1/firefox-win64.zip
    at F:\dev\src\puppeteer\node_modules\puppeteer-firefox\lib\BrowserFetcher.js:264:21
    at ClientRequest.requestCallback (F:\dev\src\puppeteer\node_modules\puppeteer-firefox\lib\BrowserFetcher.js:320:7)
    at Object.onceWrapper (events.js:313:26)
    at ClientRequest.emit (events.js:223:5)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:583:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:17)
    at TLSSocket.socketOnData (_http_client.js:456:22)
    at TLSSocket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
  -- ASYNC --
    at BrowserFetcher.<anonymous> (F:\dev\src\puppeteer\node_modules\puppeteer-firefox\lib\helper.js:32:15)
    at Object.<anonymous> (F:\dev\src\puppeteer\node_modules\puppeteer-firefox\install.js:47:16)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
```

**Comment by Allcharles** [comment]
I suspect this is the same issue as: https://github.com/puppeteer/puppeteer/issues/5310. Kind of pain that it still hasn't been fixed or addressed. I've set the following in my package.json to get around the issue:
`"puppeteer-firefox": "0.5.0"`

**Comment by shanesreal** [comment]
> >I suspect this is the same issue as: #5310. Kind of pain that it still hasn't been fixed or addressed. I've set the following in my package.json to get around the issue:
`"puppeteer-firefox": "0.5.0"`

`npm i puppeteer-firefox@0.5.0` worked for me, this will do fine until devs fix updated version.
