### ISSUE TITLE
Bug: Cannot type emoji using Puppeteer 2.1 and Firefox Nightly

### ISSUE THREAD

**Issue by zaydek** [puppeteer/puppeteer#5392]
Hi there, I’m building an editor based on contenteditable and testing around the Puppeteer ecosystem. I’m on a Mac (14.6) and running my tests in Node/Jest using Puppeteer 2.1 and Firefox Nightly (74.0a1 (2020-02-05) (64-bit)).

In puppeteer-firefox, it looks like input events **do not** have the property `inputType` -- I imagine this is a side effect of puppeteer-firefox shipping an older binary. I saw that 2.1 was released very recently based on a local copy of Firefox Nightly, so I tried Puppeteer with Firefox again.

When I ran my tests (passing in Chrome), I get the following when running against Firefox:

```
 FAIL  src/components/Editor/__tests/puppeteer.test.js (21.496s)
  ✓ cannot delete contenteditable (292ms)
  ✕ can type and delete emojis (1 of 3) (48ms)
  ✕ can type and delete emojis (2 of 3) (39ms)
  ✕ can type and delete emojis (3 of 3) (40ms)
  ✕ can type and delete characters (256ms)
  ✕ can type and delete words (236ms)
  ✕ can type and delete (forwards) characters (224ms)
  ✕ can type and delete (forwards) words (269ms)
  ✓ can type and delete 100x paragraphs (4314ms)
  ✓ can type and delete (forwards) 100x paragraphs (5468ms)
  ✓ can undo and redo (2353ms)
  ✕ can undo and overwrite redo (771ms)

  ● can type and delete emojis (1 of 3)

    Protocol error (Input.insertText): Input.insertText RemoteAgentError@chrome://remote/content/Error.jsm:25:5
    UnknownMethodError@chrome://remote/content/Error.jsm:108:7
    execute@chrome://remote/content/domains/DomainCache.jsm:96:13
    receiveMessage@chrome://remote/content/sessions/ContentProcessSession.jsm:69:45
    MessageListener.receiveMessage*ContentProcessSession@chrome://remote/content/sessions/ContentProcessSession.jsm:27:25
    @chrome://remote/content/sessions/frame-script.js:12:1

      35 | // Types character data.
      36 | export async function type(p, data) {
    > 37 | 	await p.keyboard.type(data, { delay: DELAY })
         | 	                 ^
      38 | }
      39 |
      40 | // Presses a key (e.g. keydown).

      at node_modules/puppeteer/lib/Connection.js:183:56
      at CDPSession.send (node_modules/puppeteer/lib/Connection.js:182:12)
      at Keyboard.sendCharacter (node_modules/puppeteer/lib/Input.js:151:24)
      at Keyboard.<anonymous> (node_modules/puppeteer/lib/helper.js:112:23)
      at Keyboard.type (node_modules/puppeteer/lib/Input.js:166:20)
      at Keyboard.type (node_modules/puppeteer/lib/helper.js:112:23)
      at Object.type (src/components/Editor/__tests/ppt.js:37:19)
      at Object.<anonymous> (src/components/Editor/__tests/puppeteer.test.js:44:12)

...
```

Essentially, every test that has `page.keyboard.type("...")` with emoji as the character data crashes Firefox Nightly, making it somewhat impossible to test Firefox Nightly as is (I could do tricks like copy and paste but that sort of defeats the purpose of testing the editor).

I hope this helps -- thanks.

**Comment by mjzffr** [comment]
@codex-zaydek Thanks for the report. Could you provide a minimal test case / code snippet that demonstrates the issue?

**Comment by zaydek** [comment]
Thanks @mjzffr -- sorry I didn’t include it the first time around. I’ll add this to my todo list!

**Comment by zaydek** [comment]
I don’t have time to get into this now but I forgot to mention the error is in the OP:

```
    Protocol error (Input.insertText): Input.insertText RemoteAgentError@chrome://remote/content/Error.jsm:25:5
    UnknownMethodError@chrome://remote/content/Error.jsm:108:7
    execute@chrome://remote/content/domains/DomainCache.jsm:96:13
    receiveMessage@chrome://remote/content/sessions/ContentProcessSession.jsm:69:45
    MessageListener.receiveMessage*ContentProcessSession@chrome://remote/content/sessions/ContentProcessSession.jsm:27:25
    @chrome://remote/content/sessions/frame-script.js:12:1

      35 | // Types character data.
      36 | export async function type(p, data) {
    > 37 | 	await p.keyboard.type(data, { delay: DELAY })
         | 	                 ^
      38 | }
      39 |
      40 | // Presses a key (e.g. keydown).

      at node_modules/puppeteer/lib/Connection.js:183:56
      at CDPSession.send (node_modules/puppeteer/lib/Connection.js:182:12)
      at Keyboard.sendCharacter (node_modules/puppeteer/lib/Input.js:151:24)
      at Keyboard.<anonymous> (node_modules/puppeteer/lib/helper.js:112:23)
      at Keyboard.type (node_modules/puppeteer/lib/Input.js:166:20)
      at Keyboard.type (node_modules/puppeteer/lib/helper.js:112:23)
      at Object.type (src/components/Editor/__tests/ppt.js:37:19)
      at Object.<anonymous> (src/components/Editor/__tests/puppeteer.test.js:44:12)
```

The test cases was just typing `😀😃😄😁😆😅🤣😂🙂🙃😉😊😇` into a `contenteditable` node. I hope that helps. Feel free to close this if you don’t feel like this is enough information. Error only occurred in response to Firefox Nightly, version stated above.
