### ISSUE TITLE
page.emulateTimezone(timezoneId) 

### ISSUE THREAD

**Issue by zhenghanzheng** [puppeteer/puppeteer#5421]
"puppeteer-core": "^2.1.1"

page.emulateTimezone  no this function？  why？

**Comment by zhenghanzheng** [comment]
code：
puppeteer.launch({
        args:false?['--proxy-server=socks5://'+message.proxy.ip+':'+message.proxy.port]:['--disable-infobars','--enable-automation', '--start-maximized'],
        executablePath: 'D:/chromewin/chrome.exe',
        ignoreHTTPSErrors: true,
        defaultViewport: { width:1600, height:1200 },
        headless: false,
        devtools: false
    }).then(async browser => {
        const page = await browser.newPage();
        await page.emulateTimezone('Asia/Oral');
        await page.goto('https://whatismytimezone.com');
        await page.screenshot({path: 'screenshot.png'});
    });


log：

(node:8820) UnhandledPromiseRejectionWarning: Error: Protocol error (Emulation.setTimezoneOverride): 'Emulation.setTimezoneOverride' wasn't found
    at Promise (D:\code\diandog\diandogbrowser\node_modules\puppeteer-core\lib\Connection.js:183:56)
    at new Promise (<anonymous>)
    at CDPSession.send (D:\code\diandog\diandogbrowser\node_modules\puppeteer-core\lib\Connection.js:182:12)
    at Page.emulateTimezone (D:\code\diandog\diandogbrowser\node_modules\puppeteer-core\lib\Page.js:829:26)
    at Page.<anonymous> (D:\code\diandog\diandogbrowser\node_modules\puppeteer-core\lib\helper.js:112:23)
    at D:\code\diandog\diandogbrowser\src\index.js:54:24
    at Generator.next (<anonymous>)
    at step (D:\code\diandog\diandogbrowser\src\index.js:5:191)
    at D:\code\diandog\diandogbrowser\src\index.js:5:361
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:8820) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8820) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Santosh-13** [comment]
I am also facing this issue.
Does anyone have the fix for this.

**Comment by mathiasbynens** [comment]
You’re using an old Chrome binary. Timezone emulation is available in Chrome 79+.
