### ISSUE TITLE
Some tests with Firefox cause a crash of the test runner and an abort of the test run

### ISSUE THREAD

**Issue by whimboo** [puppeteer/puppeteer#5466]
### Steps to reproduce
Run all the Puppeteer unit tests with Firefox, and make sure that `should allow accepting prompts` in dialog.spec.js is enabled. When all the unit tests are run, it fails with this crash message:

```
## CRASHED ##
Message:
  UNHANDLED PROMISE REJECTION
Stack:
  Error: expect.toBe failed:  == yes.
      at applyMatcher (/Users/henrik/code/puppeteer/utils/testrunner/Matchers.js:48:15)
      at Page.<anonymous> (/Users/henrik/code/puppeteer/test/dialog.spec.js:35:39)
      at Page.emit (events.js:196:13)
      at Page._onDialog (/Users/henrik/code/puppeteer/lib/Page.js:641:10)
      at CDPSession.<anonymous> (/Users/henrik/code/puppeteer/lib/Page.js:120:61)
      at CDPSession.emit (events.js:196:13)
      at CDPSession._onMessage (/Users/henrik/code/puppeteer/lib/Connection.js:200:12)
      at Connection._onMessage (/Users/henrik/code/puppeteer/lib/Connection.js:112:17)
      at WebSocket.<anonymous> (/Users/henrik/code/puppeteer/lib/WebSocketTransport.js:44:24)
      at WebSocket.onMessage (/Users/henrik/code/puppeteer/node_modules/ws/lib/event-target.js:120:16)
WORKERS STATE
  0: [TERMINATED] Firefox Browser Page Page.Events.Dialog should allow accepting prompts (dialog.spec.js:32:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

When I run this test alone I only get a test failure with the navigation timeout. But no crash.

**Tell us about your environment:**

* Puppeteer version: 2.0.0-post
* Platform / OS version: MacOS 10.15
* URLs (if applicable):
* Node.js version: 10.19.0

**What steps will reproduce the problem?**
1. Run npm install
2. Edit dialog.spec.js and enable `should allow accepting prompts` for Firefox
3. Run PUPPETEER_EXECUTABLE_PATH=firefox npm run funit

**What is the expected result?**
After the failure logged the unit test run should continue.

**What happens instead?**
Due to the crash failure the whole test run is immediately aborted.

**Comment by whimboo** [comment]
@mathiasbynens it would help us a lot if we could get this solved. It would allow us to always run all the Puppeteer unit tests without having to mark those problematic ones as `it_fails_ffox`. Thanks a lot.

**Comment by whimboo** [comment]
The problem actually seem to be related to `page.on()`, and when the error is thrown in its callback function. When I modify the test and save all the values first, and do the comparisons outside of it all works fine:

```
      let type, defaultValue, message;
      page.on('dialog', dialog => {
        type = dialog.type();
        defaultValue = dialog.defaultValue();
        message = dialog.message();
        dialog.accept('answer!');
      });
      const result = await page.evaluate(() => prompt('question?', 'yes.'));
      expect(type).toBe('prompt');
      expect(defaultValue).toBe('yes.');
      expect(message).toBe('question?');
```

**Comment by whimboo** [comment]
Hi @jackfranklin. Do you have a suggestion for to make it easier for to run tests as long as this problems exists? Thanks a lot.

**Comment by whimboo** [comment]
@mjzffr synced our in-tree copy of Puppeteer from 2.1 to 3.1 (see https://bugzilla.mozilla.org/show_bug.cgi?id=1632710). Now we no longer have the problem with harness crashes.

The dashboard also visualizes that:
https://puppeteer.github.io/ispuppeteerfirefoxready/

So nothing else is needed here. It works great now.
