### ISSUE TITLE
Error: Cannot find module 'puppeteer'

### ISSUE THREAD

**Issue by lovefamilychildrenhappiness** [puppeteer/puppeteer#5472]
I have pupetter installed globally on ubuntu:

$ npm list -g --depth 0
/usr/local/lib
└── puppeteer@2.1.1

Yet when I run a script that requires puppeteer, I get this error:

Error: Cannot find module 'puppeteer'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ubuntu/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/mysite/lib/js/myscript.js:15:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

Why would I get this error if puppeteer is indeed installed globally?

**Comment by Exception-star** [comment]
how to dealwith this problem？
