### ISSUE TITLE
Failed to put Xlib into threaded mode

### ISSUE THREAD

**Issue by Kikobeats** [puppeteer/puppeteer#5476]
Hello,

I searched around puppeteer repo and StackOverflow and I didn't find relevant information about this problem, so I decided to open a new issue as an entry point for trying to address it for anyone interested.

The error is happening after a while; I'm not sure why and didn't find yet a way to reproduce it.

### Stack Trace

```
[0304/162513.739328:ERROR:browser_main_loop.cc(611)] Failed to put Xlib into threaded mode.
Inconsistency detected by ld.so: ../elf/dl-tls.c: 481: _dl_allocate_tls_init: Assertion `listp->slotinfo[cnt].gen <= GL(dl_tls_generation)' failed!
TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md
  at onClose (/usr/src/app/node_modules/puppeteer/lib/Launcher.js:750:14)
  at Interface.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/Launcher.js:739:50)
  at Interface.emit (events.js:323:22)
  at Interface.EventEmitter.emit (domain.js:482:12)
  at Interface.close (readline.js:409:8)
  at Socket.onend (readline.js:187:10)
  at Socket.emit (events.js:323:22)
  at Socket.EventEmitter.emit (domain.js:482:12)
  at endReadableNT (_stream_readable.js:1204:12)
  at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

### Flags

```js
const args = [
  '--disable-cloud-import',
  '--disable-gesture-typing',
  '--disable-infobars',
  '--disable-notifications',
  '--disable-offer-store-unmasked-wallet-cards',
  '--disable-offer-upload-credit-cards',
  '--disable-print-preview',
  '--disable-speech-api',
  '--disable-tab-for-desktop-share',
  '--disable-translate',
  '--disable-voice-input',
  '--disable-wake-on-wifi',
  '--enable-async-dns',
  '--enable-simple-cache-backend',
  '--enable-tcp-fast-open',
  '--enable-webgl',
  '--hide-scrollbars',
  '--ignore-gpu-blacklist',
  '--mute-audio',
  '--no-default-browser-check',
  '--no-pings',
  '--no-zygote',
  '--prerender-from-omnibox=disabled',
  '--use-gl=swiftshader',
  '--no-sandbox',
  '--disable-web-security',
  '--font-render-hinting=none',
  '--enable-font-antialiasing',
  '--single-process',
  '--memory-pressure-off'
]
```

### Environment

* Puppeteer version: v2.1.1
* Platform / OS version: x86_64 / Ubuntu 18.04.4 LTS
* URLs (if applicable):
* Node.js version: v12.16.1
* CPU: Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz

**Comment by dom54** [comment]
We are often experiencing this too - it seems to me the simplest fix is to retry....

**Comment by Georgegriff** [comment]
> We are often experiencing this too - it seems to me the simplest fix is to retry....

Do you have an example of your retry logic?

**Comment by dom54** [comment]
Before:
```
  async launch() {
        this.browser = await puppeteer.launch({
            headless: this.parameters.browser.headless,
            args: [
                "--no-sandbox",
                "--disable-dev-shm-usage",
                "--lang=en-GB"
            ],
            defaultViewport: {
                width: 1200,
                height: 900
            }
        });
```

After:

```
 this.browser = getBrowser();

private async getBrowser(attempt = 1) {
        try {
            return await puppeteer.launch({
                headless: this.parameters.browser.headless,
                args: [
                    "--no-sandbox",
                    "--disable-dev-shm-usage",
                    "--lang=en-GB"
                ],
                defaultViewport: {
                    width: 1200,
                    height: 900
                }
            });
        } catch (e) {
            if (attempt <= 5) {
                await (new Promise(resolve => setTimeout(resolve, 500)));
                return this.getBrowser(attempt + 1);
            }
            throw new Error(e);
        }
    }
```

**Comment by Georgegriff** [comment]
Thank you i wasnt sure it was something that errors out in a promise based format or events, this makes things easier tha its not events, thank you i'll give it a go

**Comment by alpeshgit** [comment]
For me setting the DISPLAY env param did the work, as I was running it on a remote server.

> export DISPLAY=:1.0;

You may have to explicitly set it each time.

**Comment by Kikobeats** [comment]
but it's still a legit issue!

**Comment by OrKoN** [comment]
it looks like a potentially issue in Chromium or perhaps a misconfiguration in the environment (for example, like @alpeshgit mentions the display env var). Please file a bug to crbug.com if it's the former as we cannot fix it in Puppeteer.
