### ISSUE TITLE
Chromium crashes on external ressources in footer

### ISSUE THREAD

**Issue by BetaConnector** [puppeteer/puppeteer#5485]
Hello - I am using nesk/puphpeteer as php-lib and spatie/browsershot to create PDF-Files on a lumen instance - everything within a docker instance.

I am including an external ressource into my footer:
`<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
`
The following command is generated:
`node '/var/www/html/lumen/vendor/spatie/browsershot/src/../bin/browser.js' '{"url":"file:\/\/\/tmp\/1702248694-0041875001583697336\/index.html","action":"pdf","options":{"args":["--disable-dev-shm-usage","--no-sandbox"],"viewport":{"width":800,"height":600},"displayHeaderFooter":true,"delay":50,"waitUntil":"networkidle0","executablePath":"\/usr\/bin\/chromium-browser","format":"A4","footerTemplate":"<link rel=\"stylesheet\" href=\"https:\/\/maxcdn.bootstrapcdn.com\/bootstrap\/4.0.0\/css\/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW\/dAiS6JXm\" crossorigin=\"anonymous\">","margin":{"top":"30mm","right":"30mm","bottom":"0mm","left":"30mm"},"printBackground":true}}'`

If I run the command within the docker container, I am getting the following result:
`(node:1007) UnhandledPromiseRejectionWarning: Error: Page crashed!
    at Page._onTargetCrashed (/var/www/html/node_modules/puppeteer/lib/Page.js:213:24)
    at CDPSession.<anonymous> (/var/www/html/node_modules/puppeteer/lib/Page.js:122:56)
    at CDPSession.emit (events.js:223:5)
    at CDPSession._onMessage (/var/www/html/node_modules/puppeteer/lib/Connection.js:200:12)
    at Connection._onMessage (/var/www/html/node_modules/puppeteer/lib/Connection.js:112:17)
    at WebSocket.<anonymous> (/var/www/html/node_modules/puppeteer/lib/WebSocketTransport.js:44:24)
    at WebSocket.onMessage (/var/www/html/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:223:5)
    at Receiver.receiverOnMessage (/var/www/html/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:223:5)
(node:1007) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1007) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

If I just place some html-code into the footer the pdf gets generated without any problem.

The provlem also occurs with external fonts :(

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.1.1
* Platform / OS version: alpine:3.11
* Node.js version: v12.15.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.place external ressources into footer
2.save pdf

**What is the expected result?**
The external ressource are beeding able to used

**What happens instead?**
Exception as described above.

Hope you guys got a hint for me - I am running out fo ideas :(

**Comment by stevenspiel** [comment]
Perhaps related, but I have the same issue when I try to use base64-encoded font faces in my css in the header/footer.

```
(node:26748) UnhandledPromiseRejectionWarning: Error: Page crashed!
at Page._onTargetCrashed (/Users/stevenspiel/mobile/example/node_modules/puppeteer/lib/Page.js:213:24)
at CDPSession.<anonymous> (/Users/stevenspiel/mobile/example/node_modules/puppeteer/lib/Page.js:122:56)
  at CDPSession.emit (events.js:315:20)
  at CDPSession._onMessage (/Users/stevenspiel/mobile/example/node_modules/puppeteer/lib/Connection.js:200:12)
  at Connection._onMessage (/Users/stevenspiel/mobile/example/node_modules/puppeteer/lib/Connection.js:112:17)
  at WebSocket.<anonymous> (/Users/stevenspiel/mobile/example/node_modules/puppeteer/lib/WebSocketTransport.js:44:24)
    at WebSocket.onMessage (/Users/stevenspiel/mobile/example/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (/Users/stevenspiel/mobile/example/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:315:20)
    at emitUnhandledRejectionWarning (internal/process/promises.js:149:15)
    at processPromiseRejections (internal/process/promises.js:211:11)
    at processTicksAndRejections (internal/process/task_queues.js:98:32)
    (node:26748) Error: Page crashed!
    at Page._onTargetCrashed (/Users/stevenspiel/mobile/example/node_modules/puppeteer/lib/Page.js:213:24)
    at CDPSession.<anonymous> (/Users/stevenspiel/mobile/example/node_modules/puppeteer/lib/Page.js:122:56)
      at CDPSession.emit (events.js:315:20)
      at CDPSession._onMessage (/Users/stevenspiel/mobile/example/node_modules/puppeteer/lib/Connection.js:200:12)
      at Connection._onMessage (/Users/stevenspiel/mobile/example/node_modules/puppeteer/lib/Connection.js:112:17)
      at WebSocket.<anonymous> (/Users/stevenspiel/mobile/example/node_modules/puppeteer/lib/WebSocketTransport.js:44:24)
        at WebSocket.onMessage (/Users/stevenspiel/mobile/example/node_modules/ws/lib/event-target.js:120:16)
        at WebSocket.emit (events.js:315:20)
        at Receiver.receiverOnMessage (/Users/stevenspiel/mobile/example/node_modules/ws/lib/websocket.js:789:20)
        at Receiver.emit (events.js:315:20)
        (node:26748) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
        at emitDeprecationWarning (internal/process/promises.js:161:11)
        at processPromiseRejections (internal/process/promises.js:213:13)
        at processTicksAndRejections (internal/process/task_queues.js:98:32)
```

A related thread here, too: https://www.bountysource.com/issues/53960255-footertemplate-and-headertemplate-don-t-use-body-styles

**Comment by moneal** [comment]
Anyway to open this back up without creating a new issue every 30 days?
