### ISSUE TITLE
Page.goto is giving an issue

### ISSUE THREAD

**Issue by Santosh-13** [puppeteer/puppeteer#5498]
Error: net::ERR_EMPTY_RESPONSE at 
    at navigate (/node_modules/puppeteer/lib/FrameManager.js:121:37)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
  -- ASYNC --
    at Frame.<anonymous> (/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.goto (/node_modules/puppeteer/lib/Page.js:674:49)
    at Page.<anonymous> (/node_modules/puppeteer/lib/helper.js:112:23)
    at Puppeteer.launchChrome ()
    at processTicksAndRejections (internal/process/task_queues.js:85:5)

**Comment by Santosh-Gmail** [comment]
Alpine image: node:12.9-alpine
Puppeteer version: 1.19.0

Code:
const chrome = await puppeteer.launch( {
    executablePath: '/usr/bin/chromium-browser',
    args: ["--no-sandbox", "--disable-dev-shm-usage", '--headless', '--disable-gpu'],
} );
const page = (await chrome.pages())[0];
await page.setUserAgent("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36");
page.evaluateOnNewDocument( () => window.isPuppeteer = true );
await page.goto( this.url, { waitUntil: "domcontentloaded" } );

What might be the issue?

**Comment by hanselfmu** [comment]
Could you give me the URL -- in your case, `this.url` -- please?

**Comment by Santosh-Bogi** [comment]
This works properly with non docker environment. 
this.url is [Localhost](https://127.0.0.1:4000/something)

**Comment by Santosh-13** [comment]
this.url is something in localhost. Like 127.0.0.1:4000

**Comment by Santosh-13** [comment]
`this.url` is in localhost
