### ISSUE TITLE
Browser Notification & overridePermission issue.

### ISSUE THREAD

**Issue by bbrtan** [puppeteer/puppeteer#5514]
Appreciate if someone could help out. kinda new to puppeteer and i've got a blocker 

the below  is the snippet of code which i use within an iframe. Using _before_ and _after_ for browser launch & close.  Hours spend to try to get over this blocker and resort to post an issue here. 

<img width="763" alt="notification" src="https://user-images.githubusercontent.com/26596330/76773568-a4e31400-67dd-11ea-9358-a468d75bb8e0.png">

**Tell us about your environment:**

* Puppeteer version: 2.1.1
* Platform / OS version:  RHEL 8.1
* URLs (if applicable):
* Node.js version: 17.19
* Browser : Chrome 80.3987.137 or Chromium equivalent in 2.1.1

### Steps to reproduce

const puppeteer = require('puppeteer')
const config = require('../lib/config')
const homePage  =  require('../pages/HomePage')
const homePageObjects = require('../pageObjects/homePageObjects')
const loginPage  =  require('../pages/LoginPage')
const helper = require('../lib/helper')

describe('Home Menu Tests',() => {
    let browser
    let page
    
    before(async function(){
        browser = await puppeteer.launch({
            headless:config.isHeadless,
            slowMo:config.slowMo,
            devtools:config.isDevtools,
            timeout:config.launchTimeout,
            ignoreDefaultArgs: ['--disable-notifications'],
            executablePath:'/usr/bin/google-chrome-stable',
            
            
            
        })
        
        page = await browser.newPage()
        
        page.setDefaultNavigationTimeout(0);
        await page.setDefaultTimeout(config.waitingTimeout)
        await page.setViewport({
            width:config.viewRepotWidth,
            height:config.viewRepotHeight,
 
         
       
        
        
        })
    

        const context = browser.defaultBrowserContext();
        context.overridePermissions('http://P42:7778/ords/odtest/f?p=110:101::::::',['notifications']);  // just a tester for overridePermission
        await helper.loadUrl(page,config.baseUrl); //takes a url from config.
        await loginPage.Login(page,'AB0001','00000');
        
         

    })

    after(async function() {
        await homePage.Logout(page)
        await browser.close()
        
    })

    it('Verify Home Menu - Notification Control ',async()=>{
        await page.waitFor(3000);
        await helper.hover(page,homePageObjects.homeMenu) 
        await helper.clickX(page,"//a[@id='WJ7000']");
        await page.waitFor(3000);
        await page.waitForSelector('iframe');
        await page.waitForSelector('#P1_IFRAME');
        const elementHandle = await page.$('div#P1_LAUNCHER iframe')
        const frame = await elementHandle.contentFrame();
        await page.waitFor(4000);
        await frame.waitForSelector ("div#P2_SELECTION_CONTAINER")
        await frame.waitForSelector ("select#P2_MSG_TYPE")
        await frame.waitForSelector ("#P2_MSG_TYPE")
        await frame.select ('#P2_MSG_TYPE',"GEN")
        await page.waitFor(3000);
        await frame.waitForXPath ("//*[@class ='cke_wysiwyg_frame cke_reset']")
        await frame.waitForXPath ("//*[@class ='cke_wysiwyg_frame cke_reset']")
        await page.keyboard.press('Tab', {delay: 100});
        await page.keyboard.press("Tab");
        await page.keyboard.press("Tab");
        await page.keyboard.type('test')
        await page.waitFor(3000);
        await frame.type('input#P2_START_DATE', '01-Jan-2020 03:35 PM', {delay: 200})
        await frame.type('input#P2_END_DATE', '01-Jan-2027 03:35 PM', {delay: 200})
        await frame.select ('#P2_VISIBLE_OPT',"P")
        await page.waitFor(3000);
        //await frame.click ('button#P2_BTN_SAVE > span')
        //await page.waitFor(2000);
        //await page.keyboard.press ('Tab');    // not able to Tab OK on the notification 
        //await page.waitFor(40000);
        //await page.keyboard.press(String.fromCharCode(13)); 
        //await page.keyboard.press('Tab');
        //await page.keyboard.press('Enter');
        ///###///await frame.helper.clickX ("//button[@aria-labelledby='a_Collapsible2_P2_SAVED_NOTIFICATION_heading']")
        //await frame.waitForXPath("//a[contains(.,'Enabled')]")
        //await frame.clickX ("//img[@src='/test18st_image/tile-rename-sml.png']")
        //await frame.click ('button#P2_BTN_DELETE > span')
        //await delay(3000);
    })

    it('Verify Job Role ',async()=>{
    
        await page.reload({ waitUntil: ["networkidle0", "domcontentloaded"] });
        await helper.clickX(page,homePageObjects.personJobs) 
        await page.select ('#P0_PERSON_JOBS','Manager (AB880-05')
        await page.reload({ waitUntil: ["networkidle0", "domcontentloaded"] });

              
        
    })

     
})    

**What is the expected result?**
To be able to either click on the notification ( accept ) or disable it.

**What happens instead?**

The 3 issue here is the notification that appears after entry is saved.i have tried several methods. i would like to just use keyboard.press however going deeper i find that overridePermission isnt working as well. 

1.  await page.keyboard.press("Enter");     does not work 

or 

2.  context.overridePermissions('http://P42:7778/ords/odtest/f?p=110:101::::::',['notifications']);   

which throwing error : somehow granting is denied?  related to [#3279](https://github.com/puppeteer/puppeteer/issues/3279)

3. and .catch block issue  how do i manage it in a "before" statement. 

node:5223) UnhandledPromiseRejectionWarning: Error: Protocol error (Browser.grantPermissions): Permissions can't be granted in current context.
    at Promise (/home/aspats3/ess/node_modules/puppeteer/lib/Connection.js:74:56)
    at new Promise (<anonymous>)
    at Connection.send (/home/aspats3/ess/node_modules/puppeteer/lib/Connection.js:73:12)
    at BrowserContext.overridePermissions (/home/aspats3/ess/node_modules/puppeteer/lib/Browser.js:356:28)
    at BrowserContext.<anonymous> (/home/aspats3/ess/node_modules/puppeteer/lib/helper.js:112:23)
    at Context.<anonymous> (/home/aspats3/ess/tests/2_homeMenu.test.js:42:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:5223) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5223) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

is there something i can do to fix this or get over the notification popup?

**Comment by bbrtan** [comment]
workaround with dialog dismiss
