### ISSUE TITLE
How to install puppeteer?

### ISSUE THREAD

**Issue by Exception-star** [puppeteer/puppeteer#5524]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 
* Platform / OS version:  Linux version 3.10.0-1062.9.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) ) #1 SMP Fri Dec 6 15:49:49 UTC 2019
* Node.js version:  v11.14.0

**What steps will reproduce the problem?**
 npm install puppeteer-core
![image](https://user-images.githubusercontent.com/53971568/77163997-44f4b200-6aea-11ea-9eae-aa1ab0bd3e5d.png)

![image](https://user-images.githubusercontent.com/53971568/77164037-5e95f980-6aea-11ea-962e-8d9de493c5b1.png)

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/anaconda3/bin/node',
1 verbose cli   '/usr/local/anaconda3/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'puppeteer-core' ]
2 info using npm@6.7.0
3 info using node@v11.14.0
4 verbose npm-session abb4e2041d16bd0e
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for puppeteer-core@latest request to https://registry.npm.taobao.org/puppeteer-core failed, reason: connect ETIMEDOUT 172.22.178.101:80
8 timing stage:rollbackFailedOptional Completed in 0ms
9 timing stage:runTopLevelLifecycles Completed in 451828ms
10 verbose type system
11 verbose stack FetchError: request to https://registry.npm.taobao.org/puppeteer-core failed, reason: connect ETIMEDOUT 172.22.178.101:80
11 verbose stack     at ClientRequest.req.on.err (/usr/local/anaconda3/lib/node_modules/npm/node_modules/node-fetch-npm/src/index.js:68:14)
11 verbose stack     at ClientRequest.emit (events.js:193:13)
11 verbose stack     at onerror (/usr/local/anaconda3/lib/node_modules/npm/node_modules/agent-base/index.js:100:9)
11 verbose stack     at callbackError (/usr/local/anaconda3/lib/node_modules/npm/node_modules/agent-base/index.js:122:5)
11 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:86:5)
12 verbose cwd /home/ads-creative-image-algorithm/wangweizhen5/move_images/fe-video
13 verbose Linux 3.10.0-1062.9.1.el7.x86_64
14 verbose argv "/usr/local/anaconda3/bin/node" "/usr/local/anaconda3/bin/npm" "install" "-g" "puppeteer-core"
15 verbose node v11.14.0
16 verbose npm  v6.7.0
17 error code ETIMEDOUT
18 error errno ETIMEDOUT
19 error network request to https://registry.npm.taobao.org/puppeteer-core failed, reason: connect ETIMEDOUT 172.22.178.101:80
20 error network This is a problem related to network connectivity.
20 error network In most cases you are behind a proxy or have bad network settings.
20 error network
20 error network If you are behind a proxy, please make sure that the
20 error network 'proxy' config is set properly.  See: 'npm help config'
21 verbose exit [ 1, true ]
```

**Comment by occultskyrong** [comment]
先装下这个再试试，https://github.com/gucong3000/mirror-config-china
