### ISSUE TITLE
Passing a large (>100mb) argument to a function ran using page.evaluate causes a crash

### ISSUE THREAD

**Issue by Woolfe** [puppeteer/puppeteer#5598]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.1.1 (Also found the same error in 2.0.0)
* Platform / OS version: MacOS Catalina 10.15
* URLs (if applicable):
* Node.js version: v11.10.1

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Load a large JSON file into memory in your node application (>100mb)
2. Pass it to a function using page.evaluate, like so:
```
 const result = await page.evaluate(
    myFunction,
    myLargeJSON
  )
```
**What is the expected result?**
 No crash. I've tried --unlimited-storage and --force-gpu-mem-available-mb. It works with a ~95mb JSON file, and seems to crash roughly around the 100mb limit so I'm guessing there's some sort of cap but I cannot find an appropriate flag to increase this limit. I have checked the available memory in Node and on my machine, both are not close to running out, so I'm pretty sure it's a puppeteer thing.

**What happens instead?**

A crash, with an error looking something like this:

> UnhandledPromiseRejectionWarning: Error: Protocol error (Runt.
    at Promise (/Users/jwoolfe/Documents/GitHub/woolfe/roket-scraper/node_modules/puppeteer/lib/Conne)
    at new Promise (<anonymous>)
    at CDPSession.send (/Users/jwoolfe/Documents/GitHub/woolfe/roket-scraper/node_modules/puppeteer/l)
    at ExecutionContext._evaluateInternal (/Users/jwoolfe/Documents/GitHub/woolfe/roket-scraper/node_)
    at ExecutionContext.evaluate (/Users/jwoolfe/Documents/GitHub/woolfe/roket-scraper/node_modules/p)
    at ExecutionContext.<anonymous> (/Users/jwoolfe/Documents/GitHub/woolfe/roket-scraper/node_module)
    at DOMWorld.evaluate (/Users/jwoolfe/Documents/GitHub/woolfe/roket-scraper/node_modules/puppeteer)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
  -- ASYNC --
    at Frame.<anonymous> (/Users/jwoolfe/Documents/GitHub/woolfe/roket-scraper/node_modules/puppeteer)
    at Page.evaluate (/Users/jwoolfe/Documents/GitHub/woolfe/roket-scraper/node_modules/puppeteer/lib)
    at Page.<anonymous> (/Users/jwoolfe/Documents/GitHub/woolfe/roket-scraper/node_modules/puppeteer/)
    at /Users/jwoolfe/Documents/GitHub/woolfe/roket-scraper/puppet.js:141:70
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:89310) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated eit)
(node:89310) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future.

**Comment by Freundschaft** [comment]
did you manage to find a workaround for this? facing the same issue here.

**Comment by opssemnik** [comment]
> did you manage to find a workaround for this? facing the same issue here.

You can breakdown your string into 1024 * 1024 * 50 length substrings
Evaluate each substring into a variable inside the browser, then do an evaluate to concatenate all substrings into the original string, and decode it into whatever object you want (json, blob, etc)

**Comment by bekorn** [comment]
I had the same issue, Puppeteer was crashing a free-tier EC2 instance when I tried to pass ~20MB of data to `evaluate()`.

The workaround I found is to save the arguments to a file, pass the file path to the browser, and then fetch it. Works quite fast compared to what Puppeteer does. Which I believe is some sort of serialization and deserialization.

**Comment by sarvang008** [comment]
I am also facing the same issue any other resolutions other than breaking the data?
