### ISSUE TITLE
Puppeteer error :uploadFile is not a function

### ISSUE THREAD

**Issue by tara0077** [puppeteer/puppeteer#5599]
const input = await select('input[name="file"]')
await input.uploadFile(workspace+'/sfdc/data/Work-relay/src/processes/application assessment/Orchestrator.wri')
await takeScreenshot(page,enableLogs,jobName,"Start_WR_Processes_Forms")
console.log('Select Work relay -> Click Process -> selecting file1... Done');
await page.waitFor(7000);

I am getting below error while running the above code in Salesforce Lightening
Select Work relay -> Click Process ->save folder ... Done
Select Work relay -> Click Process ->import ... Done
Puppeteer Catch Error:  TypeError: input.uploadFile is not a function
    at /unicrm/jenkins/workspace/DevTools/SandboxPostRefreshTest/runtimeResources/PostStep/WorkRelay_Processes_Forms.js:163:7
    at processTicksAndRejections (internal/process/task_queues.js:85:5)]
Possible solutions: iterator(), every(), grep(), rtnError(java.lang.Object), getAt(java.lang.String), each(groovy.lang.Closure)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:58)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:54)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)

**Comment by tara0077** [comment]
Anyone has come across this same error?

**Comment by paullewis** [comment]
Hi, it will depend on what `select` does, since `uploadFile` is available on `JSHandle`, so you'd want to make sure select is using `evaluateHandle`. Going to close as `uploadFile` is definitely available, but do feel free to ping on this issue if it's not resolved.
