### ISSUE TITLE
Bug: page.type in Puppeteer with Firefox stops at/can't type certain characters (Input.insertText not implemented)

### ISSUE THREAD

**Issue by AlexanderFreud** [puppeteer/puppeteer#5629]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:		2.1.1
* Platform / OS version:	Microsoft Windows 10 Education (Version	10.0.17134 Build 17134)
* URLs (if applicable):	doesn't seem to be specific to URL
* Node.js version:		v12.16.1
* Firefox Nightly version:	77.0a1 (2020-04-11) (64-Bit)

**What steps will reproduce the problem?**
Running Puppeteer with Firefox and using page.type with certain characters, for example German Umlauts. In general it seems like characters with utf8 hex code greater than 007E resp. 007F are not working.

Minimal code example that has the problem:
```javascript
const puppeteer = require('puppeteer');

const options = {
  executablePath: 'C:\\Program Files\\Firefox Nightly\\firefox.exe',
  headless:false, 
  slowMo:10,
  defaultViewport: null,
  product:'firefox',
  args: [
  "-wait-for-browser",
  ],
};

puppeteer.launch(options).then(async browser => {
  const page = await browser.newPage();
  await page.goto('https://www.web.de');
  await page.waitFor(3000);
  let myString = 'Tokyo street \u007E \u00A1 ä \uc3a4 👹';
  await page.type("#freemailLoginUsername", myString);
  await page.waitFor(999999);
})
```

**What is the expected result?**
The characters get typed by page.type.

**What happens instead?**
The typing is stopped at the first character that causes a problem and in the console the following message is printed:

```
(node:45516) UnhandledPromiseRejectionWarning: Error: Protocol error (Input.insertText): Input.insertText RemoteAgentError@chrome://remote/content/Error.jsm:25:5
UnknownMethodError@chrome://remote/content/Error.jsm:108:7
execute@chrome://remote/content/domains/DomainCache.jsm:96:13
receiveMessage@chrome://remote/content/sessions/ContentProcessSession.jsm:69:45
MessageListener.receiveMessage*ContentProcessSession@chrome://remote/content/sessions/ContentProcessSession.jsm:27:25
@chrome://remote/content/sessions/frame-script.js:12:1

    at C:\Users\Veri\node_modules\puppeteer\lib\Connection.js:183:56
    at new Promise (<anonymous>)
    at CDPSession.send (C:\Users\Veri\node_modules\puppeteer\lib\Connection.js:182:12)
    at Keyboard.sendCharacter (C:\Users\Veri\node_modules\puppeteer\lib\Input.js:151:24)
    at Keyboard.<anonymous> (C:\Users\Veri\node_modules\puppeteer\lib\helper.js:112:23)
    at Keyboard.type (C:\Users\Veri\node_modules\puppeteer\lib\Input.js:166:20)
    at async ElementHandle.type (C:\Users\Veri\node_modules\puppeteer\lib\JSHandle.js:363:5)
    at async DOMWorld.type (C:\Users\Veri\node_modules\puppeteer\lib\DOMWorld.js:422:5)
    at async C:\Users\Veri\Documents\Webdesign\KleinanzeigenAuto\Scripts\testCharacterFirefox.js:19:3
  -- ASYNC --
    at Keyboard.<anonymous> (C:\Users\Veri\node_modules\puppeteer\lib\helper.js:111:15)
    at ElementHandle.type (C:\Users\Veri\node_modules\puppeteer\lib\JSHandle.js:363:31)
    at async DOMWorld.type (C:\Users\Veri\node_modules\puppeteer\lib\DOMWorld.js:422:5)
    at async C:\Users\Veri\Documents\Webdesign\KleinanzeigenAuto\Scripts\testCharacterFirefox.js:19:3
  -- ASYNC --
    at ElementHandle.<anonymous> (C:\Users\Veri\node_modules\puppeteer\lib\helper.js:111:15)
    at DOMWorld.type (C:\Users\Veri\node_modules\puppeteer\lib\DOMWorld.js:422:18)
    at async C:\Users\Veri\Documents\Webdesign\KleinanzeigenAuto\Scripts\testCharacterFirefox.js:19:3
  -- ASYNC --
    at Frame.<anonymous> (C:\Users\Veri\node_modules\puppeteer\lib\helper.js:111:15)
    at Page.type (C:\Users\Veri\node_modules\puppeteer\lib\Page.js:1103:29)
    at C:\Users\Veri\Documents\Webdesign\KleinanzeigenAuto\Scripts\testCharacterFirefox.js:19:14
(node:45516) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:45516) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

With Chromium everything works as expected, as these issues with it have already been fixed (for example issue #1096)

**Comment by AlexanderFreud** [comment]
Sorry for the formatting issue... first time posting code, trying to edit it for better readability!

**Comment by mjzffr** [comment]
Hey, thanks for the detailed report. Indeed, Firefox doesn't implement Input.insertText yet, but you can track progress on that here https://bugzilla.mozilla.org/show_bug.cgi?id=1595177

If you'd like to tell the team about how your project using Puppeteer, it might help us prioritize upcoming work on Firefox support. You can reach out at https://wiki.mozilla.org/Remote

**Comment by AlexanderFreud** [comment]
Hi, thanks for your response and the bugzilla link, I wasn't aware that a disscussion about this was already started :)
Thanks for the suggestion, but I guess the project is not that significant...
For now I switched to using the deprecated puppeteer-firefox (https://github.com/puppeteer/puppeteer/tree/master/experimental/puppeteer-firefox) where the typing works :)
For others reading this: on Windows one has to use version 0.5.0 instead of the last one (0.5.1), so in the command line npm i puppeteer-firefox@0.5.0 works

**Comment by hienvuong2810** [comment]
I solved this problem. You should click this element before typing.
```
await page.type("#input", "hello")
``` 
Should
```
await page.click("#input")
await page.type("#input", "hello")
```
