### ISSUE TITLE
Error: Protocol error (Runtime.callFunctionOn): Target closed. when uploadFile exceeds certain size.

### ISSUE THREAD

**Issue by W1nU** [puppeteer/puppeteer#5636]
# Environment
* Puppeteer version: ^2.1.1
* Platform / OS version: MacOS 10.14.6
* Node.js version: 10.19.0

# What steps will reproduce the problem?
I should to upload my apk, ipa build file for applying security solutions. 
Apk is uploaded well and well applied. but, ipa is not uploaded well.

When testing by changing the extension of the APK file to IPA, it was confirmed that it works without any problems. (Not means apply solutions. Just upload)
So, i think it is occured by file size.

* IPA file size: 132MB
* APK file size: 40.5MB

If anyone knows about the related issues, please help.

# FILE UPLOAD CODE
```
const FileUpload = async () => {
    const FILE_INPUT = await Page.$('#file-choosen');
    await FILE_INPUT.uploadFile(BuildFile);

    await Page.evaluate(() => {
      window.selectedFileName = 'tickle.apk';
      window.selectFile(1);

      document.querySelector('#string_enc').parentElement.click();
      document.querySelector('#xml_modify').parentElement.click();
    });

    await Page.click('#btn-composer-file');

    console.log('안드로이드 보호 시작');
  };
```

# What is the expected result?
Smooooth upload.

# What happens instead?
`
(node:4326) UnhandledPromiseRejectionWarning: Error: Protocol error (Runtime.callFunctionOn): Target closed.
    at Promise (/Users/seungwoojung/workspace/tickle-ios/Liapp/node_modules/puppeteer/lib/Connection.js:183:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/Users/seungwoojung/workspace/tickle-ios/Liapp/node_modules/puppeteer/lib/Connection.js:182:12)
    at ExecutionContext._evaluateInternal (/Users/seungwoojung/workspace/tickle-ios/Liapp/node_modules/puppeteer/lib/ExecutionContext.js:107:44)
    at ExecutionContext.evaluateHandle (/Users/seungwoojung/workspace/tickle-ios/Liapp/node_modules/puppeteer/lib/ExecutionContext.js:57:17)
    at ExecutionContext.<anonymous> (/Users/seungwoojung/workspace/tickle-ios/Liapp/node_modules/puppeteer/lib/helper.js:112:23)
    at ElementHandle.evaluateHandle (/Users/seungwoojung/workspace/tickle-ios/Liapp/node_modules/puppeteer/lib/JSHandle.js:63:42)
    at ElementHandle.<anonymous> (/Users/seungwoojung/workspace/tickle-ios/Liapp/node_modules/puppeteer/lib/helper.js:112:23)
    at ElementHandle.uploadFile (/Users/seungwoojung/workspace/tickle-ios/Liapp/node_modules/puppeteer/lib/JSHandle.js:335:16)
  -- ASYNC --
    at ElementHandle.<anonymous> (/Users/seungwoojung/workspace/tickle-ios/Liapp/node_modules/puppeteer/lib/helper.js:111:15)
    at IOSUpload (/Users/seungwoojung/workspace/tickle-ios/Liapp/index.js:64:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:4326) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4326) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by paullewis** [comment]
This is likely due to an issue with the file uploader, which we fixed in 532ae573d29063ffd081ed9ee340d71b25320dec. I'll assume fixed and will close, but please reopen if it's not resolved.
