### ISSUE TITLE
node test.js and npm i error

### ISSUE THREAD

**Issue by Hxmic** [puppeteer/puppeteer#5687]
![image](https://user-images.githubusercontent.com/23522154/79726949-2e768c00-831e-11ea-99ec-bb9e6cc101eb.png)

![image](https://user-images.githubusercontent.com/23522154/79726986-3fbf9880-831e-11ea-9ef6-0ada7cdd833d.png)

throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'original', 'function');

TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function

how  to  resolve it

**Comment by jiangyanghe** [comment]
我也遇到相同的问题

**Comment by jiangyanghe** [comment]
I had try V2,  but throw error  **"TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function"** too, my node version is 8.10.0

**Comment by Hxmic** [comment]
怎么解决呀。有些东西装不上吗？

**Comment by Hxmic** [comment]
![image](https://user-images.githubusercontent.com/23522154/79739651-0e9c9380-8331-11ea-8bfc-33df5e61f5ce.png)  找到一个这个是这个引起的吗？

https://blog.pushstack.com/export-html-to-pdf-in-node.html

**Comment by Hxmic** [comment]
![image](https://user-images.githubusercontent.com/23522154/79739689-1d834600-8331-11ea-961f-2b8e29205742.png)

**Comment by jiangyanghe** [comment]
你可以了吗？微信 18516586568

**Comment by jiangyanghe** [comment]
我试了v2版本 么有遇到这个问题，并且可以完美使用

**Comment by Hxmic** [comment]
真的吗？ 我也想知道方案

**Comment by lalmat** [comment]
You certainly have an old NodeJS version. You should have node v.10 or more installed.

**Comment by condinoaljoseph** [comment]
I have the same issue with this.

**Comment by xiaoqiao112** [comment]
> 我试了v2版本 么有遇到这个问题，并且可以完美使用

你好，这个你是怎么处理的，v2版本是哪个的版本？使用时报如下错：
Uncaught TypeError: The "original" argument must be of type Function

**Comment by brianpham93** [comment]
Having same issue when run command
` mocha './test/**/*.js' --recursive --timeout 99999      
`
Node 10.4.1, `zsh` shell works well
Node 10.14.1, `fish` shell encounters this error

```
TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
    at promisify (internal/util.js:209:11)
    at Object.<anonymous> (/Users/quocthang_pham/KrisPay/non-biz/node_modules/extract-zip/index.js:11:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/quocthang_pham/KrisPay/non-biz/node_modules/puppeteer/lib/BrowserFetcher.js:25:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/quocthang_pham/KrisPay/non-biz/node_modules/puppeteer/lib/api.js:24:21)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/quocthang_pham/KrisPay/non-biz/node_modules/puppeteer/index.js:18:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
```

**Comment by andrewdcato** [comment]
I'm getting the same issue with Node 12.13.1, but *only* when running in the VS Code debugger...when I run my app directly via `npm start` command or `node app.js`, the app runs successfully: 

```
internal/util.js:209
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'original', 'function');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
    at promisify (internal/util.js:209:11)
    at Object.<anonymous> (/Users/andrewcato/surety/financeservice/node_modules/extract-zip/index.js:11:18)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/andrewcato/surety/financeservice/node_modules/puppeteer/lib/BrowserFetcher.js:26:20)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
```
