### ISSUE TITLE
Version 3 Breaks The Library By Causing An Error Related To The libgbm.so.1

### ISSUE THREAD

**Issue by muratgozel** [puppeteer/puppeteer#5701]
**Environment:**

* Puppeteer version: 3.0.0
* Platform / OS version: Ubuntu 18.04
* Node.js version: 12.14

**Steps to reproduce the problem:**

1. Install puppeteer dependencies for Ubuntu: 
```sh
sudo DEBIAN_FRONTEND=noninteractive apt install -yq gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget
```
2. Install puppeteer:
```sh
npm install -g puppeteer
```
3. Create a symlink inside some project:
```
cd /home/someuser/projects/someproject
npm link puppeteer
```
4. Run ssr script:
```
node ssr/script/path/ssr $dir $locale $url
```

SSR script can be found here: https://gist.github.com/muratgozel/cbd643bee13c2b5cd7de89db56b3fdf2
Just uses basic methods of the library. 😛

**What is the expected result?**
Generate HTML files as in version 2.

**What happens instead?**
Throws an exception that says **libgbm.so.1: cannot open shared object file: No such file or directory** 👇
```txt
(node:3291) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
/usr/lib/node_modules/puppeteer/.local-chromium/linux-737027/chrome-linux/chrome: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/usr/lib/node_modules/puppeteer/lib/Launcher.js:615:20)
    at Interface.<anonymous> (/usr/lib/node_modules/puppeteer/lib/Launcher.js:605:56)
    at Interface.emit (events.js:215:7)
    at Interface.close (readline.js:403:8)
    at Socket.onend (readline.js:180:10)
    at Socket.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:3291) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

**How I survived:**
Reverted to version 2. 🐬

**Comment by jackfranklin** [comment]
Hi @muratgozel does the fix explained in https://github.com/puppeteer/puppeteer/pull/5693/files help?

**Comment by muratgozel** [comment]
@jackfranklin Yes! I can confirm that pr resolves this issue.

I've tested as follows:
```sh
# installed the dependency as mentioned in pr
sudo apt install libgbm1

# re-install puppeteer
cd /home/someuser/projects/someproject
npm uninstall puppeteer -g
npm install puppeteer -g
npm link puppeteer

# test
node ssr/script/path/ssr $dir $locale $url
```

Thank you and the community 👏👏

**Comment by jackfranklin** [comment]
Great!
