### ISSUE TITLE
Navigation failed because browser has disconnected! | Raspberry Pi 3+

### ISSUE THREAD

**Issue by dommilosz** [puppeteer/puppeteer#5790]
Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 
* Platform / OS version: Raspberry Pi 3+
* URLs (if applicable):
* Node.js version: 12.15.0

**What steps will reproduce the problem?**

On windows it works normal.

```js
const puppeter = require('puppeteer')
puppeeteer = null;

    let cookies = []
    let error = false
    try{browser = await puppeter.launch({args: ['--no-sandbox']})}
    catch{
        try{
        browser = await puppeter.launch({ executablePath: 'chromium-browser' })}catch{
            puppeeteer = require('puppeteer-core');
            browser = await puppeeteer.launch({executablePath: '/usr/bin/chromium-browser',args: ['--no-sandbox']});
        }
    }
    
    page = await browser.newPage();
    await page.goto(url) <<< Here
```
```
(node:12549) UnhandledPromiseRejectionWarning: Error: Navigation failed because browser has disconnected!
    at CDPSession.LifecycleWatcher._eventListeners.helper.addEventListener (/home/pi/Downloads/main/node_modules/puppeteer-core/lib/FrameManager.js:1181:107)
    at CDPSession.emit (events.js:189:13)
    at CDPSession._onClosed (/home/pi/Downloads/main/node_modules/puppeteer-core/lib/Connection.js:231:10)
    at Connection._onClose (/home/pi/Downloads/main/node_modules/puppeteer-core/lib/Connection.js:121:15)
    at WebSocketTransport._ws.addEventListener.event (/home/pi/Downloads/main/node_modules/puppeteer-core/lib/WebSocketTransport.js:45:22)
    at WebSocket.onClose (/home/pi/Downloads/main/node_modules/ws/lib/event-target.js:124:16)
    at WebSocket.emit (events.js:189:13)
    at WebSocket.emitClose (/home/pi/Downloads/main/node_modules/ws/lib/websocket.js:191:10)
    at Socket.socketOnClose (/home/pi/Downloads/main/node_modules/ws/lib/websocket.js:850:15)
    at Socket.emit (events.js:189:13)
  -- ASYNC --
    at Frame.<anonymous> (/home/pi/Downloads/main/node_modules/puppeteer-core/lib/helper.js:144:27)
    at Page.goto (/home/pi/Downloads/main/node_modules/puppeteer-core/lib/Page.js:624:49)
    at Page.<anonymous> (/home/pi/Downloads/main/node_modules/puppeteer-core/lib/helper.js:145:23)
    at Object.login (/home/pi/Downloads/main/main.js:28:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:12549) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12549) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**What is the expected result?**

Puppeteer loads page

**Comment by NorthBlue333** [comment]
Hi.
I ran into the same issue and for now I am unable to resolve this.
I'm running it with docker though.

**Comment by dommilosz** [comment]
I did this and it works somehow on my rpi
```js
const puppeter = require("puppeteer");
browser = null;
launchbrowser = async function (visible) {
    headless = !visible
    try {
        browser = await puppeter.launch({
            args: ["--no-sandbox"],
            headless: headless
        });
    } catch (ex) {
        try {
            console.log(ex);
            browser = await puppeter.launch({
                executablePath: "chromium-browser",
                headless: headless
            });
        } catch {
            browser = await puppeter.launch({
                args: [
                    "--disable-web-security",
                    "--allow-http-screen-capture",
                    "--allow-running-insecure-content",
                    "--disable-features=site-per-process",
                    "--no-sandbox"
                ],
                headless: headless,
                executablePath: "/usr/bin/chromium-browser",
                devtools: devtools
            });
        }
    }
};
```

**Comment by NorthBlue333** [comment]
I didn't expected you to answer this fast !
Well this didn't solve the issue while running it through docker, but it surely works without docker. Thanks a lot !

**Comment by rojvv** [comment]
Same issue, my url is something like file:///.......
