### ISSUE TITLE
Ubuntu 18.04 - TimeoutError: waiting for selector failed: timeout 30000ms exceeded

### ISSUE THREAD

**Issue by fatihturgut** [puppeteer/puppeteer#5801]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 3.0.2
* Platform / OS version: Chrome / Ubuntu 18.04
* URLs (if applicable):
* Node.js version: v14.1.0

**What steps will reproduce the problem?**

Following code block **(A)**,
Works on macOS Mojave 10.14.6;
Works properly on ubuntu 18.04
```javascript
const puppeteer = require('puppeteer');
async function main() {
  const browser = await puppeteer.launch({
    headless: true
  });

  const page = await browser.newPage();
  await page.goto('https://example.com');

  await page.content();
  await page.screenshot({path: 'screenshot.png'});

  await browser.close();
}

main();
```

Following code block **(B)**,
Works on macOS Mojave 10.14.6;
But throws error due to **page.waitForSelector function on ubuntu 18.04**  
```javascript
const puppeteer = require('puppeteer');
async function main() {
  const browser = await puppeteer.launch({
    headless: true,
  });
  const page = await browser.newPage();
  await page.goto('https://twitter.com/i/trends');
  await page.content();
  console.log("pageUrl", page.url());
  await page.waitForSelector("[data-testid=trend]");
  const trendElements = await page.$$("[data-testid=trend]");
  console.log("trendElementsLength", trendElements && trendElements.length);
  await browser.close();
}

main();
```

1. Launched an instance (ubuntu 18.04) on aws ec2 service
2. Created a file test-pup/index.js, and added script **B** mentioned above
3. Installed npm package (only puppeteer)
4. Run the script with `node index`

**What is the expected result?**

Should not throw error on ubuntu 18.04 like on macOS Mojave 10.14.6.

Should logs console something like
```
trendElementsLength 7
```

**What happens instead?**

**Throws error on ubuntu 18.04, but not on macOS Mojave 10.14.6**
**UnhandledPromiseRejectionWarning: TimeoutError: waiting for selector**
```
(node:5483) UnhandledPromiseRejectionWarning: TimeoutError: waiting for selector "[data-testid=trend]" failed: timeout 30000ms exceeded
    at new WaitTask (/home/ec2-user/test-pup/node_modules/puppeteer/lib/DOMWorld.js:549:28)
    at DOMWorld._waitForSelectorOrXPath (/home/ec2-user/test-pup/node_modules/puppeteer/lib/DOMWorld.js:478:22)
    at DOMWorld.waitForSelector (/home/ec2-user/test-pup/node_modules/puppeteer/lib/DOMWorld.js:432:17)
    at Frame.waitForSelector (/home/ec2-user/test-pup/node_modules/puppeteer/lib/FrameManager.js:627:47)
    at Frame.<anonymous> (/home/ec2-user/test-pup/node_modules/puppeteer/lib/helper.js:112:23)
    at Page.waitForSelector (/home/ec2-user/test-pup/node_modules/puppeteer/lib/Page.js:1122:29)
    at main (/home/ec2-user/test-pup/index.js:20:20)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5483) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5483) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by fatihturgut** [comment]
I solved this problem, "[data-testid=trend]" items never appear on document.
I assume twitter blocks it, and shows "something went wrong" message.
