### ISSUE TITLE
Initiate a request from within a page

### ISSUE THREAD

**Issue by barnash** [puppeteer/puppeteer#592]
Is there an easy way to initiate a new request form within a page?

My use case is logging in and than running some API calls from the client to the server, without browsing all the pages.

I'd like something like `page.request('/path/to/call', 'POST', '{"param1": "value1"})`

I think I can use `evaluate` and use the a native xml http request, convert it to a promise and send it back, but it's a lot of work.

Anyone has an idea?

**Comment by aslushnikov** [comment]
@barnash you can use [fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API):

```js
await page.evaluate(async () => {
  const response = await fetch('https://example.com');
  const text = await response.text();
  return text;
});
```

**Comment by bipsBro** [comment]
I got following error when executing fetch using async/await like @aslushnikov 
 mention

Evaluation failed: ReferenceError: _Promise is not defined

      at __puppeteer_evaluation_script__:4:5
      at ExecutionContext._evaluateInternal (node_modules/puppeteer/lib/ExecutionContext.js:122:13)
        -- ASYNC --
      at ExecutionContext.<anonymous> (node_modules/puppeteer/lib/helper.js:111:15)
      at DOMWorld.evaluate (node_modules/puppeteer/lib/DOMWorld.js:112:20)
        -- ASYNC --
      at Frame.<anonymous> (node_modules/puppeteer/lib/helper.js:111:15)
      at Page.evaluate (node_modules/puppeteer/lib/Page.js:782:43)
      at Page.<anonymous> (node_modules/puppeteer/lib/helper.js:112:23)
      at evaluate (tests/page.js:569:40)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:271:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:97:21)
      at asyncGeneratorStep (node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:5:24)
      at _next (node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:27:9)
      at node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:34:7
        -- ASYNC --
      at Page.<anonymous> (node_modules/puppeteer/lib/helper.js:111:15)
      at evaluate (tests/page.js:569:40)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:271:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:97:21)
      at asyncGeneratorStep (node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:5:24)
      at _next (node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:27:9)
      at node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:34:7
      at new F (node_modules/core-js/library/modules/_export.js:36:28)

**Comment by leonardorifeli** [comment]
I got same error @bipsBro.

Did you fix that?

```
Error: Evaluation failed: [object Object]
    at ExecutionContext._evaluateInternal (.../node_modules/puppeteer/lib/ExecutionContext.js:122:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (.../node_modules/puppeteer/lib/helper.js:111:15)
    at DOMWorld.evaluate (.../node_modules/puppeteer/lib/DOMWorld.js:112:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
  -- ASYNC --
    at Frame.<anonymous> (.../node_modules/puppeteer/lib/helper.js:111:15)
    at Page.evaluate (.../node_modules/puppeteer/lib/Page.js:782:43)
    at Page.<anonymous> (.../node_modules/puppeteer/lib/helper.js:112:23)
    at myMethod (./index.js:90:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
```

**Comment by bipsBro** [comment]
@leonardorifeli I solved this problem by using `then` method instead of using async await. 

I am using it as a helper function to handle request inside browser here is the sample code that i used.
   
    requestFn = async (
     url,
     method = 'GET',
     options = { body: undefined, headers: undefined },
    ) => {
    return await this.page.evaluate(
      datas => {
        return fetch(datas.url, {
          method: datas.method,
          body: datas.options.body,
          headers: datas.options.headers,
        })
          .then(response => response.json().then(r => r))
          .catch(err => {
            console.log(err);
          });
      },
      { url, method, options },
     );
    };

**Comment by zbigniewstefaniuk** [comment]
well I assume that you want to POST some data to webhook or other server to trigger with gathered data so to do this you can install axios to your puppeteer package.json and then use it like this 

```
const dataToSend = await page.evaluate(() => {
// your code here and then return this data 
  return text;
});

// here use axios or fetch outside of evaluate(() => {}) scope
try {
    const {status, statusText} = await axios.post(url,{dataToSend});
    status === 200 && console.log('notification sended');
  } catch (err) {
    console.error(err);
  }
```
just use axios or fetch outside of .evaluate function block because in evaluate block, code in it will execute on browser instead of your puppeteer server/cron
