### ISSUE TITLE
Issues with puppeteer loading shared libraries

### ISSUE THREAD

**Issue by georgeka98** [puppeteer/puppeteer#5931]
Hi,

Im running puppeteer on aUbuntu 19.10 x64 server and I am getting the following problem:

```
0|index    |     at process._tickCallback (internal/process/next_tick.js:63:19)
0|index    | Error: Failed to launch the browser process!
0|index    | /var/www/dommain/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome: error while loading shared libraries: libxcb-dri3.so.0: cannot open shared object file: No such file or directory
0|index    | 
0|index    | 
0|index    | TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md
0|index    | 
0|index    |     at onClose (/var/www/covid19livespread.com/node_modules/puppeteer/lib/launcher/BrowserRunner.js:159:20)
0|index    |     at Interface.helper_1.helper.addEventListener (/var/www/domain/node_modules/puppeteer/lib/launcher/BrowserRunner.js:149:65)
0|index    |     at Interface.emit (events.js:194:15)
0|index    |     at Interface.close (readline.js:379:8)
0|index    |     at Socket.onend (readline.js:157:10)
0|index    |     at Socket.emit (events.js:194:15)
0|index    |     at endReadableNT (_stream_readable.js:1103:12)
0|index    |     at process._tickCallback (internal/process/next_tick.js:63:19)
```

There are problems with loading shared libraries on my server with puppeteer. On my local machine, puppeteer worked perfectly fine.

Are there any issues with puppeteer 3.1.0? How do I fix this issue?

**Comment by georgeka98** [comment]
Fixed now.

**Comment by 007lva** [comment]
Hello, I have the same problem, can you tell me how did you fix it please? Thanks!

**Comment by anjina** [comment]
> Fixed now.

how do you fix it ?

**Comment by mapinxue** [comment]
how do you fix it?
