### ISSUE TITLE
browser.close() still tries to kill the process when the close is successful

### ISSUE THREAD

**Issue by char101** [puppeteer/puppeteer#5933]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 3.1.0
* Platform / OS version: Windows 10
* URLs (if applicable):
* Node.js version: 14.2.0

**What steps will reproduce the problem?**

```javascript
browser.close()
```
**What is the expected result?**
No error message

**What happens instead?**

```
ERROR: The process "67920" not found.
```
^ This is the output from running `taskill` on non-existent process on Windows.

**Explanation of the problem**

https://github.com/puppeteer/puppeteer/blob/master/src/launcher/BrowserRunner.ts#L129 sends `Browser.close` command and on error it tries to kill the process. But in this case the error itself is not really an error

```
Error: Protocol error (Browser.close): Target closed.
    at \node_modules\puppeteer\lib\Connection.js:53:63
    at new Promise (<anonymous>)
    at Connection.send (\node_modules\puppeteer\lib\Connection.js:52:16)
    at BrowserRunner.close (\node_modules\puppeteer\lib\launcher\BrowserRunner.js:100:29)
    at Browser.close (\node_modules\puppeteer\lib\Browser.js:177:35)
    at Browser.<anonymous> (\node_modules\puppeteer\lib\helper.js:95:27)
```

So it then tried to kill a non-existent process.

**Comment by blacktipit-x** [comment]
I am seeing a potentially related issue in browser.close() as well.   

Out of a few hundred runs I'm seeing about 6% error rate (windows server 2016/vmware fusion/puppeteer 3.1/node 14.1/14.2).  While in browser.close(), a 'page crashed' error is randomly emitted with a call trace like:

(node:6296) Error: Page crashed!
at Page._onTargetCrashed (..\node_modules\puppeteer\lib\Page.js:200:28)
at CDPSession. (..\node_modules\puppeteer\lib\Page.js:120:57)
at CDPSession.emit (events.js:315:20)
at CDPSession._onMessage (..\node_modules\puppeteer\lib\Connection.js:166:18)
at Connection._onMessage (..\node_modules\puppeteer\lib\Connection.js:83:25)
at WebSocket. (..\node_modules\puppeteer\lib\WebSocketTransport.js:25:32)
at WebSocket.onMessage (..\node_modules\ws\lib\event-target.js:125:16)
at WebSocket.emit (events.js:315:20)
at Receiver.receiverOnMessage (..\node_modules\ws\lib\websocket.js:800:20)
at Receiver.emit (events.js:315:20)

The node error stream sometimes shows:
ERROR: The process with PID XXXX (child process of PID YYYY) could not be terminated.
Reason: There is no running instance of the task.

Still trying to isolate this issue but fast running out of time.  Unable to repro on bare-metal/win10pro so far.

-- 
Edit 1: Occurs on node 14.3.
Edit 2: Occurs on node 12.17 LTS & pptr 3.2.  
Edit 3: Also confirmed on 12.17 LTS + 3.0.2. 
- Both issues (page crash & process ID) may appear independently of each other.
- Current mitigation: add a page.on('error', ...) listener - no apparent leaks.
