### ISSUE TITLE
Puppeteer NOT working with Firefox (nightly) when {product: 'firefox'}

### ISSUE THREAD

**Issue by mpalavrov** [puppeteer/puppeteer#5958]
## Steps to reproduce

1. Download [Firefox Nightly](https://www.mozilla.org/en-US/firefox/channel/desktop/)
2. Run the below edited example to use `product: 'firefox'`
```
/**
 * @name Duck Duck Go search
 */

const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
	  headless: false,
	  product: 'firefox',
	  //executablePath: 'C:/Program Files (x86)/Google/Chrome/Application/chrome.exe'
	  //executablePath: 'C:/Program Files/Mozilla Firefox/firefox.exe'
	  executablePath: 'C:/Program Files/Firefox Developer Edition/firefox.exe',
	  dumpio: true

	  });
  const page = await browser.newPage()
  await page.goto('https://duckduckgo.com/')  
  await page.type('#search_form_input_homepage', 'Puppeteer')
  const searchValue = await page.$eval('#search_form_input_homepage', el => el.value)
  console.log(searchValue)
  await browser.close()
})()
```

**Tell us about your environment:**

* Puppeteer version: 3.2.0
* Platform / OS version: Windows 10
* URLs (if applicable):
* Node.js version: v13.8.0
* NPM version: 6.14.2

**What steps will reproduce the problem?**
_Described above_

**What is the expected result?**
Puppeteer to work as expected, the same way (or near) as it works with chrome/chromium

**What happens instead?**
It crash with:

```
C:\Users\Milen\Desktop\Puppeteer-Test_Firefox>node test.js
(node:12256) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (C:\Users\Milen\Desktop\Puppeteer-Test_Firefox\node_modules\puppeteer\lib\Launcher.js:750:14)
    at ChildProcess.<anonymous> (C:\Users\Milen\Desktop\Puppeteer-Test_Firefox\node_modules\puppeteer\lib\Launcher.js:740:61)
    at ChildProcess.emit (events.js:333:22)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
(node:12256) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:12256) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Error: EBUSY: resource busy or locked, unlink 'C:\Users\Milen\AppData\Local\Temp\puppeteer_dev_firefox_profile-BFNrfA\cookies.sqlite'] {
  errno: -4082,
  code: 'EBUSY',
  syscall: 'unlink',
  path: 'C:\\Users\\Milen\\AppData\\Local\\Temp\\puppeteer_dev_firefox_profile-BFNrfA\\cookies.sqlite'
}
```

and the Firefox Nightly is left open:
![изображение](https://user-images.githubusercontent.com/33352511/83493214-1c5f4000-a4bd-11ea-80cf-4ad0f42a10f6.png)
About was additionali clicked in order to see the version.

Can you please someone review it and advise what might be the issue.

Thank you,

Milen Palavrov

**Comment by chenfan-fchen** [comment]
if you want to sue Firefox Nightly, why not change the why to  import **puppeteer-firefox** 
```const pptrFirefox = require('puppeteer-firefox');```

**Comment by mpalavrov** [comment]
Hello @chenfan-fchen. I am not using puppeteer-firefox mostly because of the below:
```
:\Users\XXXXXXXXXX\Desktop\puppeteer-cluster test>npm install --save puppeteer-firefox
npm WARN deprecated puppeteer-firefox@0.5.1: Firefox support is gradually transitioning to the puppeteer package. As of puppeteer v2.1.0 you can interact with Firefox Nightly. The puppeteer-firefox package will remain available until the transition is complete, but it is no longer actively maintained. For more information visit https://wiki.mozilla.org/Remote

> puppeteer-firefox@0.5.1 install C:\Users\XXXXXXXXXX\Desktop\puppeteer-cluster test\node_modules\puppeteer-firefox
> node install.js

ERROR: Failed to download Firefox rv0.0.1!
Error: Download failed: server returned code 404. URL: https://github.com/puppeteer/juggler/releases/download/v0.0.1/firefox-win64.zip
    at C:\Users\XXXXXXXXXXXX\Desktop\puppeteer-cluster test\node_modules\puppeteer-firefox\lib\BrowserFetcher.js:264:21
    at ClientRequest.requestCallback (C:\Users\XXXXXXXXXXXX\Desktop\puppeteer-cluster test\node_modules\puppeteer-firefox\lib\BrowserFetcher.js:320:7)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:610:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
    at TLSSocket.socketOnData (_http_client.js:479:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)
  -- ASYNC --
    at BrowserFetcher.<anonymous> (C:\Users\XXXXXXXXXXXX\Desktop\puppeteer-cluster test\node_modules\puppeteer-firefox\lib\helper.js:32:15)
    at Object.<anonymous> (C:\Users\XXXXXXXXXXXX\Desktop\puppeteer-cluster test\node_modules\puppeteer-firefox\install.js:47:16)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\XXXXXXXXXXXX\Desktop\puppeteer-cluster test\package.json'
npm WARN puppeteer-cluster test No description
npm WARN puppeteer-cluster test No repository field.
npm WARN puppeteer-cluster test No README data
npm WARN puppeteer-cluster test No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer-firefox@0.5.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer-firefox@0.5.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\XXXXXXXXXXXX\AppData\Roaming\npm-cache\_logs\2020-06-05T12_01_39_478Z-debug.log

C:\Users\XXXXXXXXXXXX\Desktop\puppeteer-cluster test>
```

Can someone review and advise how to fix this?

**Comment by wdatagit** [comment]
Hi, have you tried replacing
  executablePath: 'C:/Program Files/Firefox Developer Edition/firefox.exe'
with 
  executablePath: 'C://Program Files//Firefox Developer Edition//firefox.exe'

**Comment by mpalavrov** [comment]
In addition I have added
`dumpio :true` for the puppeteer.launch, and the below errors appeared:

```
C:\Users\Milen\Desktop\Puppeteer-Test_Firefox>node test.js
(node:2216) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (C:\Users\Milen\Desktop\Puppeteer-Test_Firefox\node_modules\puppeteer-core\lib\Launcher.js:750:14)
    at ChildProcess.<anonymous> (C:\Users\Milen\Desktop\Puppeteer-Test_Firefox\node_modules\puppeteer-core\lib\Launcher.js:740:61)
    at ChildProcess.emit (events.js:333:22)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
(node:2216) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2216) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[GFX1-]: shader[2020-06-13T11:56:26Z ERROR webrender_bindings::program_cache] shader-cache: Failed to create file: The system cannot find the path specified. (os error 3)
-cache: Failed to create file: The system cannot find the path specified. (os error 3)
[GFX1-]: shader-cache: Failed to create file: The system cannot find the path specified. (os error 3)
[GFX1-]: shader-cache: Failed to create file: The system cannot find the path specified. (os error 3)
[2020-06-13T11:56:27Z ERROR webrender_bindings::program_cache] shader-cache: Failed to create file: The system cannot find the path specified. (os error 3)
[2020-06-13T11:56:27Z ERROR webrender_bindings::program_cache] shader-cache: Failed to create file: The system cannot find the path specified. (os error 3)
JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
[GFX1-]: shade[2020-06-13T11:56:27Z ERROR webrender_bindings::program_cache] shader-cache: Failed to create file: The system cannot find the path specified. (os error 3)
r-cache: Failed to create file: The system cannot find the path specified. (os error 3)
[GFX1-]: shader-cach[2020-06-13T11:56:28Z ERROR webrender_bindings::program_cache] shader-cache: Failed to create file: The system cannot find the path specified. (os error 3)
[2020-06-13T11:56:28Z ERROR webrender_bindings::program_cache] shader-cache: Failed to create file: The system cannot find the path specified. (os error 3)
[2020-06-13T11:56:28Z ERROR webrender_bindings::program_cache] shader-cache: Failed to create file: The system cannot find the path specified. (os error 3)
[2020-06-13T11:56:28Z ERROR webrender_bindings::program_cache] shader-cache: Failed to create file: The system cannot find the path specified. (os error 3)
[2020-06-13T11:56:28Z ERROR webrender_bindings::program_cache] shader-cache: Failed to create file: The system cannot find the path specified. (os error 3)
[2020-06-13T11:56:28Z ERROR webrender_bindings::program_cache] shader-cache: Failed to create file: The system cannot find the path specified. (os error 3)
[2020-06-13T11:56:28Z ERROR webrender_bindings::program_cache] shader-cache: Failed to create file: The system cannot find the path specified. (os error 3)
[2020-06-13T11:56:28Z ERROR webrender_bindings::program_cache] shader-cache: Failed to create file: The system cannot find the path specified. (os error 3)
[2020-06-13T11:56:28Z ERROR webrender_bindings::program_cache] shader-cache: Failed to create file: The system cannot find the path specified. (os error 3)
e: Failed to create file: The system cannot find the path specified. (os error 3)
[GFX1-]: shader-cache: Failed to create file: The system cannot find the path specified. (os error 3)
[GFX1-]: shader-cache: Failed to create file: The system cannot find the path specified. (os error 3)
[GFX1-]: shader-cache: Failed to create file: The system cannot find the path specified. (os error 3)
[GFX1-]: shader-cache: Failed to create file: The system cannot find the path specified. (os error 3)
[GFX1-]: shader-cache: Failed to create file: The system cannot find the path specified. (os error 3)
[GFX1-]: shader-cache: Failed to create file: The system cannot find the path specified. (os error 3)
[GFX1-]: shader-cache: Failed to create file: The system cannot find the path specified. (os error 3)
[GFX1-]: shader-cache: Failed to create file: The system cannot find the path specified. (os error 3)
[GFX1-]: shade[2020-06-13T11:56:28Z ERROR webrender_bindings::program_cache] shader-cache: Failed to create file: The system cannot find the path specified. (os error 3)
r-cache: Failed to create file: The system cannot find the path specified. (os error 3)
[GFX1-]: shader-cache: Failed to create file: The system cannot find the path specified. (os error 3)
[2020-06-13T11:56:28Z ERROR webrender_bindings::program_cache] shader-cache: Failed to create file: The system cannot find the path specified. (os error 3)
[Error: EBUSY: resource busy or locked, unlink 'C:\Users\Milen\AppData\Local\Temp\puppeteer_dev_firefox_profile-TIeMxM\cookies.sqlite'] {
  errno: -4082,
  code: 'EBUSY',
  syscall: 'unlink',
  path: 'C:\\Users\\Milen\\AppData\\Local\\Temp\\puppeteer_dev_firefox_profile-TIeMxM\\cookies.sqlite'
}
[GFX1-]: shader-cache: Failed to write startup whitelist: The s[2020-06-13T11:56:31Z ERROR webrender_bindings::program_cache] shader-cache: Failed to write startup whitelist: The system cannot find the path specified. (os error 3)
ystem cannot find the path specified. (os error 3)

```



I hope someone has some additional information over the matter.

Thank you guys.

Best,
Milen

**Comment by mpalavrov** [comment]
Just for whoever is having this issue. The fix for my troubles are...:

```
/**
 * @name Duck Duck Go search
 */

const puppeteer = require('puppeteer-core');

(async () => {
  const browser = await puppeteer.launch({
	  headless: true,
	  product: 'firefox',
	  args: [
	  '-wait-for-browser'
	  ],
	  executablePath: 'C:/Program Files/Firefox Nightly/firefox.exe',
		userDataDir: 'C:/Users/Milen/Desktop/Puppeteer-Test_Firefox/Profile_FirefoxNightly',
	  });

  const page = await browser.newPage()
  	
  //await page.goto('https://duckduckgo.com/')  
      await page.setViewport({ width: 1920, height: 1080 });
   await page.screenshot({path: 'example.png'});
  await browser.close()
})()
```

There were 2 issues with my code:

1. I was using **Firefox Developers** 🔴 instead of **Firefox Nightly** 🟢 , which seems to be an issue.
2. I have added 
```
	  args: [
	  '-wait-for-browser'
	  ],
```
Which seems to be needed when using Firefox.

Cheers guys, I hope it helps someone.

Closing.

**Comment by mjzffr** [comment]
Thanks for sharing your solution :)
