### ISSUE TITLE
Page crashed when scroll

### ISSUE THREAD

**Issue by sanchobouillant** [puppeteer/puppeteer#5975]
Hi !

package.json

```
    "puppeteer": "^3.3.0",
    "puppeteer-extra": "^3.1.9",
    "puppeteer-extra-plugin-stealth": "^2.4.9"
```

Node.js version: 14

I try different ways to scroll but every time I get a "page crashed"

Code to reproduce the error:

```
export default async (page) => {
    await page.evaluate(async () => {
        await new Promise((resolve, reject) => {
            let totalHeight = 0;
            const distance = 100;
            const timer = setInterval(() => {
                const scrollHeight = document.body.scrollHeight;
                window.scrollBy(0, distance);
                totalHeight += distance;

                if (totalHeight >= scrollHeight) {
                    clearInterval(timer);
                    resolve();
                }
            }, 100);
        });
    });
}
```

Error:
```

(node:14252) UnhandledPromiseRejectionWarning: Error: Page crashed!
    at Page._onTargetCrashed (/var/application/node_modules/puppeteer/lib/Page.js:209:28)
    at CDPSession.<anonymous> (/var/application/node_modules/puppeteer/lib/Page.js:129:57)
    at CDPSession.emit (events.js:315:20)
    at CDPSession._onMessage (/var/application/node_modules/puppeteer/lib/Connection.js:166:18)
    at Connection._onMessage (/var/application/node_modules/puppeteer/lib/Connection.js:83:25)
    at WebSocket.<anonymous> (/var/application/node_modules/puppeteer/lib/WebSocketTransport.js:25:32)
    at WebSocket.onMessage (/var/application/node_modules/ws/lib/event-target.js:125:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (/var/application/node_modules/ws/lib/websocket.js:800:20)
    at Receiver.emit (events.js:315:20)
    at emitUnhandledRejectionWarning (internal/process/promises.js:149:15)
    at processPromiseRejections (internal/process/promises.js:211:11)
    at processTicksAndRejections (internal/process/task_queues.js:98:32)
(node:14252) Error: Page crashed!
    at Page._onTargetCrashed (/var/application/node_modules/puppeteer/lib/Page.js:209:28)
    at CDPSession.<anonymous> (/var/application/node_modules/puppeteer/lib/Page.js:129:57)
    at CDPSession.emit (events.js:315:20)
    at CDPSession._onMessage (/var/application/node_modules/puppeteer/lib/Connection.js:166:18)
    at Connection._onMessage (/var/application/node_modules/puppeteer/lib/Connection.js:83:25)
    at WebSocket.<anonymous> (/var/application/node_modules/puppeteer/lib/WebSocketTransport.js:25:32)
    at WebSocket.onMessage (/var/application/node_modules/ws/lib/event-target.js:125:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (/var/application/node_modules/ws/lib/websocket.js:800:20)
    at Receiver.emit (events.js:315:20)
(node:14252) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:161:11)
    at processPromiseRejections (internal/process/promises.js:213:13)
    at processTicksAndRejections (internal/process/task_queues.js:98:32)
```

Is there any other way to scroll the page without evaluate?

**Comment by paramveer1999** [comment]
async function autoScroll(page) {
    await page.evaluate(async () => {
      await new Promise((resolve, reject) => {
        var totalHeight = 0;
        var distance = 1000;
        var timer = setInterval(() => {
          var scrollHeight = document.body.scrollHeight;
          window.scrollBy(0, distance);
          totalHeight += distance;
  
          if (totalHeight >= scrollHeight) {
            clearInterval(timer);
            resolve();
          }
        }, 1000);
      });
    });
  }
try this

**Comment by sanchobouillant** [comment]
Same error. Every time I use scroll I have a "crash"

Edit: I change the viewport width and height and now it work ... 

width: 1900 - height 1080 -> failed
width: 1280 - height 800 -> OK
