### ISSUE TITLE
Puppeteer 3.3.0 crashes Firefox Nightly 79 when using UTF8 in ElementHandler.type

### ISSUE THREAD

**Issue by dsheiko** [puppeteer/puppeteer#5991]
Consider the following script
```js
const puppeteer = require( "puppeteer" );

async function main() {
  try {
    const browser = await puppeteer.launch({
      "product": "firefox",
      "headless": false,
      "devtools": false,
      "slowMo": 30,
      "ignoreHTTPSErrors": true,
      "executablePath": "/etc/firefox-nightly/firefox"
    });
    const page = await browser.newPage();
    await page.goto( "http://todomvc.com/examples/react/#/" );
    const elh = await page.$( "input.new-todo" );
    await elh.type( "ưxx111" );
   
    await browser.close();
  } catch ( e ) {
    console.error( e );
  }

}
main();
```
If I use in `await elh.type( "abc" );` any ASCII everything works perfect, but with ` "ưxx111"`
it crashes Firefox with fatal error:

```
chrome://remote/content/sessions/frame-script.js:12:1

    at Promise (/tmp/node_modules/puppeteer/lib/Connection.js:152:63)
    at new Promise (<anonymous>)
    at CDPSession.send (/tmp/node_modules/puppeteer/lib/Connection.js:151:16)
    at Keyboard.sendCharacter (/tmp/node_modules/puppeteer/lib/Input.js:105:28)
    at Keyboard.<anonymous> (/tmp/node_modules/puppeteer/lib/helper.js:95:27)
    at Keyboard.type (/tmp/node_modules/puppeteer/lib/Input.js:119:28)
    at Keyboard.<anonymous> (/tmp/node_modules/puppeteer/lib/helper.js:95:27)
    at ElementHandle.type (/tmp/node_modules/puppeteer/lib/JSHandle.js:307:35)
  -- ASYNC --
    at ElementHandle.<anonymous> (/tmp/node_modules/puppeteer/lib/helper.js:94:19)
    at main (/tmp/test.js:16:15)
  message:
   'Protocol error (Input.insertText): Input.insertText RemoteAgentError@chrome://remote/content/Error.jsm:25:5\n
UnknownMethodError@chrome://remote/content/Error.jsm:108:7\n
execute@chrome://remote/content/domains/DomainCache.jsm:96:13\n
receiveMessage@chrome://remote/content/sessions/ContentProcessSession.jsm:86:45\n
MessageListener.receiveMessage*ContentProcessSession@chrome://remote/content/sessions/ContentProcessSession.jsm:33:25\n
@chrome://remote/content/sessions/frame-script.js:12:1\n' }
```

**Comment by mjzffr** [comment]
When you see UnknownMethodError, it means the protocol implementation in Firefox doesn't support that method yet, in this case `Input.insertText`

The bug tracking this work on the Firefox side is: https://bugzilla.mozilla.org/show_bug.cgi?id=1595177

**Comment by mjzffr** [comment]
That is, Puppeteer's ElementHandle.type depends on Input.insertText at the protocol level, in some cases.

**Comment by victorgseo** [comment]
A quick solution is to add into "/puppeteer/lib/cjs/puppeteer/common/USKeyboardLayout.js" the chars you'll use.

For example, for "ê", append the line to main object:

`ê: { keyCode: 234, key: 'ê', code: 'KeyÊ' },`

Run this function to generate and paste into the USKeyboardLayout.js:

function charcodes(char) {

    return `${char}: { keyCode: ${char.charCodeAt(0)}, key: '${char}', code: 'Key${char.toUpperCase()}' },`

}

for(let each of 'êÊáéíúó'){
	console.log(charcodes(each))
}

Hope it helps :)
