### ISSUE TITLE
puppeteer Headless: true issue.

### ISSUE THREAD

**Issue by lmk07** [puppeteer/puppeteer#6050]
Hi guys,
I'm trying to automate the "https://appstoreconnect.apple.com/" webpage. i inspect that login form is "iframe" content. when im execute the code with headless as false, credentials are properly entering automatically and logging in. but if i made headless as true, it wait for some time and following error is happening.

"Loaded: https://appstoreconnect.apple.com/login
(node:5260) UnhandledPromiseRejectionWarning: Error: waitForFunction failed: frame got detached.
    at DOMWorld._detach (C:\Work\iOS_Automate\node_modules\puppeteer\lib\DOMWorld.js:63:32)
    at Frame._detach (C:\Work\iOS_Automate\node_modules\puppeteer\lib\FrameManager.js:428:30)
    at FrameManager._removeFramesRecursively (C:\Work\iOS_Automate\node_modules\puppeteer\lib\FrameManager.js:269:15)      
    at FrameManager._onFrameDetached (C:\Work\iOS_Automate\node_modules\puppeteer\lib\FrameManager.js:217:18)
    at CDPSession.<anonymous> (C:\Work\iOS_Automate\node_modules\puppeteer\lib\FrameManager.js:40:63)
    at CDPSession.emit (events.js:210:5)
    at CDPSession.EventEmitter.emit (domain.js:475:20)
    at CDPSession._onMessage (C:\Work\iOS_Automate\node_modules\puppeteer\lib\Connection.js:166:18)
    at Connection._onMessage (C:\Work\iOS_Automate\node_modules\puppeteer\lib\Connection.js:83:25)
    at WebSocket.<anonymous> (C:\Work\iOS_Automate\node_modules\puppeteer\lib\WebSocketTransport.js:25:32)
    at WebSocket.onMessage (C:\Work\iOS_Automate\node_modules\ws\lib\event-target.js:125:16)
    at WebSocket.emit (events.js:210:5)
    at WebSocket.EventEmitter.emit (domain.js:475:20)
    at Receiver.receiverOnMessage (C:\Work\iOS_Automate\node_modules\ws\lib\websocket.js:800:20)
    at Receiver.emit (events.js:210:5)
    at Receiver.EventEmitter.emit (domain.js:475:20)
  -- ASYNC --
    at Frame.<anonymous> (C:\Work\iOS_Automate\node_modules\puppeteer\lib\helper.js:94:19)
    at credentials (C:\Work\iOS_Automate\index.js:128:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async C:\Work\iOS_Automate\index.js:101:4
of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5260) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code."

My code:
                const browser = await puppeteer.launch({headless:false,args: ['--no-sandbox', '--disable-setuid-sandbox']});

                const pwd = '#password_text_field' 
		await page.waitForSelector("iframe");
		const elementHandle = await page.$('div#idms-auth-container iframe',{ waitUntil: 'networkidle2' });
		const frame = await elementHandle.contentFrame();
		await frame.waitForSelector(email);
		const username = await frame.$(email);
		await username.type(<username>);
		await page.waitFor(1000);
		await frame.waitForSelector(usernameclick);
		const signinclicks = await frame.$(usernameclick);
		await signinclicks.click();
		  await frame.waitForSelector(pwd);
		const password = await frame.$(pwd);
		await password.type(<password>);    
		await page.waitFor(3000);
		await signinclicks.click();
		await page.waitForNavigation();

**Comment by niveinii** [comment]
Got the same issue

**Comment by lukejagodzinski** [comment]
I have the same issue. It's pretty annoying that Puppeteer behaves differently with `headless` set to `true` and `false`. Everything works properly if I set it to `false`

**Comment by SCHREl** [comment]
If someone still has the same problem, I managed to solve it by using https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-stealth to launch puppeteer
