### ISSUE TITLE
Getting UnhandledPromiseRejectionWarning: Error: Passed function is not well-serializable!  Error

### ISSUE THREAD

**Issue by lmk07** [puppeteer/puppeteer#6089]
Hi guys,

im using puppeteer with nodejs, following code is working fine, when i run in "windows" but getting error in "linux" and it says passed function is not serialized.

 ```
var temp = parseInt(today);
			await page.$$eval(".week div",(elements,userDate)=> elements.map(item=>{
			  if(item.textContent == userDate){            
				item.click()
			  }
		  }),temp) 
```
```
Error is : 

    (node:21636) UnhandledPromiseRejectionWarning: Error: Passed function is not well-serializable!
    at ExecutionContext._evaluateInternal (/snapshot/puppeteer/node_modules/puppeteer/lib/ExecutionContext.js:80:23)
    at ExecutionContext.evaluate (/snapshot/puppeteer/node_modules/puppeteer/lib/ExecutionContext.js:33:27)
    at ExecutionContext.<anonymous> (/snapshot/puppeteer/node_modules/puppeteer/lib/helper.js:117:27)
    at DOMWorld.evaluate (/snapshot/puppeteer/node_modules/puppeteer/lib/DOMWorld.js:108:24)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
  -- ASYNC --
    at Frame.<anonymous> (/snapshot/puppeteer/node_modules/puppeteer/lib/helper.js:116:19)
    at Page.evaluate (/snapshot/puppeteer/node_modules/puppeteer/lib/Page.js:680:14)
    at Page.<anonymous> (/snapshot/puppeteer/node_modules/puppeteer/lib/helper.js:117:27)
    at selectFromDate (/snapshot/puppeteer/index.js)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /snapshot/puppeteer/index.js
(node:21636) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:21636) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 
Thanks in advance...

**Comment by Tianj0o** [comment]
Hi, I also met this problem. Have you solved it?
