### ISSUE TITLE
Error while closing the browser

### ISSUE THREAD

**Issue by pooja372** [puppeteer/puppeteer#6105]
Getting bellow error while closing browser 

{ Error: ENOENT: no such file or directory, uv_cwd
    at setopts (/app/node_modules/glob/common.js:93:21)
    at new Glob (/app/node_modules/glob/glob.js:135:3)
    at Function.glob.hasMagic (/app/node_modules/glob/glob.js:101:11)
    at rimraf (/app/node_modules/rimraf/rimraf.js:106:36)
    at Promise (internal/util.js:276:30)
    at new Promise (<anonymous>)
    at rimraf (internal/util.js:275:12)
    at ChildProcess.proc.once (/app/node_modules/puppeteer/lib/launcher/BrowserRunner.js:69:21)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12) errno: -2, code: 'ENOENT', syscall: 'uv_cwd' }

**Comment by christian-bromann** [comment]
@pooja372 can you provide a reproducible example? And do you experience this with the latest version of Puppeteer?
