### ISSUE TITLE
Puppeteer breaks when trying to use 'firebase deploy'

### ISSUE THREAD

**Issue by jeff-0002** [puppeteer/puppeteer#6112]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 4.0.0
* Platform / OS version: Windows
* URLs (if applicable):
* Node.js version: 8

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. This is all my Puppeteer code 
```
const url = req.body.url;
  const browser = await puppet.launch();
  const page = await browser.newPage();
  await page.goto(url, { waitUntil: 'networkidle2' });

  let data = await page.evaluate(() => {
    let title = document.querySelector('h1.headline.heading-content').textContent;

    let ingredients = [];
    document.querySelectorAll('.ingredients-item-name').forEach(i => {
      ingredients.push(i.textContent);
    });

    let instructions = [];
    document.querySelectorAll('div.section-body > div.paragraph > p').forEach(i => {
      instructions.push(i.textContent);
    });

    const image = document.querySelector('div.image-container >  div').attributes[1].textContent;
    return {
      title,
      ingredients,
      instructions,
      image
    };
  });
  await browser.close();
```

**What is the expected result?**
App deploys Successfully and everything works fine.

**What happens instead?**
deployment fails on functions and gives this error code
```
Build failed: npm_install had stderr output:
/workspace/node_modules/puppeteer/install.js:178
            } catch {
                    ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)

    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
        app
```

**Comment by sohcah** [comment]
Getting the same issue here

**Comment by dattran92** [comment]
Same issue here.

puppeteer version 4.0.1
OS: Ubuntu 16.04 LTS

**Comment by polisen** [comment]
Same here:

puppeteer 4.0.0
OS: macOS Mojave


```
exports.receiveSearch = functions.https.onRequest(async (req, res) => {
    if (req.method !== 'POST') throw new Error('POST is the only supported action.');
    let itemStatus = req.body.itemStatus || 'Ended';
    let categoryId = req.body.categoryId || '302612';
    let sortBy = req.body.SortBy || 'AddedOn';
    let searchurl = `https://www.url.com/pci-e-c3_${categoryId}?itemStatus=${itemStatus}&sortBy=${sortBy}`;
    let msEpoch = new Date(Date.now())
    let date = msEpoch.toUTCString()
    // Push the new essage into Cloud Firestore using the Firebase Admin SDK.
    const writeResult = await db.collection(searches).doc(categoryId).collection("article_hrefs").doc("1").set({
        searchurl: searchurl,
        created: date,
        categoryId: categoryId,
        itemStatus: itemStatus
    });
    res.json({ result: `CategoryId: ${categoryId} added.` });
});
```

**Comment by mayurrawte** [comment]
Updating node version to 10 fixed for me.

"engines": {
    "node": "10"
  },

**Comment by jackfranklin** [comment]
We require Node 10 since Puppeteer 3, so please ensure you're on a recent enough version.
