### ISSUE TITLE
Floating errors: Session closed and Puppeteer sent "disconnect" event

### ISSUE THREAD

**Issue by falkenbach** [puppeteer/puppeteer#6114]
Running Puppeteers with https://github.com/apify/apify-js Apify.PuppeteerPool for a single linkedin page at several dedicated DigitalOcean droplets, in other words each server running single instance of Apify.PuppeteerPool with 1 page opened. No actions made after login, just page.evaluate and page.on('response') to track live changes.

Randomly there is errors without any clear reason (same code on same server worked without issues before and will work without issues after retry):

```
Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
    at CDPSession.send (/var/scraper/node_modules/apify/node_modules/puppeteer/lib/Connection.js:180:29)
    at ExecutionContext._evaluateInternal (/var/scraper/node_modules/apify/node_modules/puppeteer/lib/ExecutionContext.js:107:44)
    at ExecutionContext.evaluate (/var/scraper/node_modules/apify/node_modules/puppeteer/lib/ExecutionContext.js:48:23)
    at ExecutionContext.<anonymous> (/var/scraper/node_modules/apify/node_modules/puppeteer/lib/helper.js:112:23)
    at DOMWorld.evaluate (/var/scraper/node_modules/apify/node_modules/puppeteer/lib/DOMWorld.js:112:20)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async DOMWorld.content (/var/scraper/node_modules/apify/node_modules/puppeteer/lib/DOMWorld.js:185:12)
  -- ASYNC --
    at Frame.<anonymous> (/var/scraper/node_modules/apify/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.content (/var/scraper/node_modules/apify/node_modules/puppeteer/lib/Page.js:658:49)
    at Page.<anonymous> (/var/scraper/node_modules/apify/node_modules/puppeteer/lib/helper.js:112:23)
    at ScrapeLogger (/var/scraper/src/scrape-logger.js:23:39)
    at /var/scraper/src/main.js:347:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

```
[2020-06-23T13:28:51.196Z]: ERROR: PuppeteerPool: Browser launch failed {"id":0}
  Error: spawn ENOMEM
    at ChildProcess.spawn (internal/child_process.js:405:11)
    at Object.spawn (child_process.js:548:9)
    at Launcher.launch (/var/scraper/node_modules/apify/node_modules/puppeteer/lib/Launcher.js:132:40)
    at async Object.launchPuppeteer (/var/scraper/node_modules/apify/build/puppeteer.js:296:15)
    at async PuppeteerPool.launchPuppeteerFunction (/var/scraper/node_modules/apify/build/puppeteer_pool.js:265:23)
```

```
[2020-06-25T05:51:00.654Z]: ERROR: PuppeteerPool: Puppeteer sent "disconnect" event. Maybe it crashed??? {"id":0}
```

So its floating errors and its at puppeteer level, apify sdk just a wrapper for it.

Ideally we would like to avoid such errors at all and understand why it happens.

 - OS: Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-106-generic x86_64)
 - Node.js v13.11.0
 - apify-cli/0.5.3 linux-x64 node-v13.11.0
- puppeteer@2.0.0

**Comment by jrandolf-google** [comment]
We no longer support Node < 14, please try this again with the latest version of Puppeteer and Node >= 14. If the issue still occurs, please reopen this issue and update the description :)
