### ISSUE TITLE
 Protocol error (Page.printToPDF): PrintToPDF is not implemented

### ISSUE THREAD

**Issue by cornelius-dol** [puppeteer/puppeteer#6220]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 5.1.0
* Platform / OS version: Windows 10 Pro, 19041.329
* URLs (if applicable): http://think.dolhub.com/
* Node.js version: 14.5.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Create the simplest possible script to convert a URL to a PDF file, following one of the many examples.
2. Run script.

**What is the expected result?**

That a PDF file is produced.

**What happens instead?**

With the internal Chromium build:

````
(async function() {
"use strict";

const puppeteer         = require("puppeteer");

try {
    const browser = await puppeteer.launch({
                        dumpio: true,
                        headless: true,
                        });
    const page    = await browser.newPage();
    await page.goto('http://think.dolhub.com');
    await page.pdf({path: 'html-page.pdf', format: 'A4'});
    await browser.close();
    }
catch(err) {
    console.log("Failed to convert URL to PDF ("+err.name+" - "+err.message+")");
    console.log(err);
    }
})();
````

In headful mode, only a single tab is shown, it has the "tab crashed" icon, and the script hangs until CTRL-C with output as follows.

````
[0714/165333.534:ERROR:sandbox_policy_base.cc(360)] Failed to add sandbox rule. error = 2, subsystem = 0, semantics = 1, pattern = 'c:\[...]\script\node_modules\puppeteer\.local-chromium\win64-768783\chrome-win\*.pdb'
[0714/165333.535:WARNING:gpu_process_host.cc(1228)] The GPU process has crashed 1 time(s)
[0714/165333.536:ERROR:sandbox_policy_base.cc(360)] Failed to add sandbox rule. error = 2, subsystem = 0, semantics = 1, pattern = 'c:\[...]\script\node_modules\puppeteer\.local-chromium\win64-768783\chrome-win\*.pdb'
[0714/165333.536:WARNING:gpu_process_host.cc(1228)] The GPU process has crashed 2 time(s)

DevTools listening on ws://127.0.0.1:63124/devtools/browser/abbb8aaf-8125-4457-9270-85d3db028a3c
[0714/165333.537:ERROR:sandbox_policy_base.cc(360)] Failed to add sandbox rule. error = 2, subsystem = 0, semantics = 1, pattern = 'c:\[...]\script\node_modules\puppeteer\.local-chromium\win64-768783\chrome-win\*.pdb'
[0714/165333.539:WARNING:gpu_process_host.cc(1228)] The GPU process has crashed 3 time(s)
[0714/165333.540:ERROR:sandbox_policy_base.cc(360)] Failed to add sandbox rule. error = 2, subsystem = 0, semantics = 1, pattern = 'c:\[...]\script\node_modules\puppeteer\.local-chromium\win64-768783\chrome-win\*.pdb'
[0714/165333.540:WARNING:gpu_process_host.cc(1228)] The GPU process has crashed 4 time(s)
[0714/165333.542:ERROR:sandbox_policy_base.cc(360)] Failed to add sandbox rule. error = 2, subsystem = 0, semantics = 1, pattern = 'c:\[...]\script\node_modules\puppeteer\.local-chromium\win64-768783\chrome-win\*.pdb'
[0714/165333.543:ERROR:sandbox_policy_base.cc(360)] Failed to add sandbox rule. error = 2, subsystem = 0, semantics = 1, pattern = 'c:\[...]\script\node_modules\puppeteer\.local-chromium\win64-768783\chrome-win\*.pdb'
[0714/165333.543:WARNING:gpu_process_host.cc(1228)] The GPU process has crashed 5 time(s)
[0714/165333.544:ERROR:sandbox_policy_base.cc(360)] Failed to add sandbox rule. error = 2, subsystem = 0, semantics = 1, pattern = 'c:\[...]\script\node_modules\puppeteer\.local-chromium\win64-768783\chrome-win\*.pdb'
[0714/165333.544:WARNING:gpu_process_host.cc(1228)] The GPU process has crashed 6 time(s)
[0714/165333.544:ERROR:browser_gpu_channel_host_factory.cc(153)] Failed to launch GPU process.
[0714/165333.548:ERROR:sandbox_policy_base.cc(360)] Failed to add sandbox rule. error = 2, subsystem = 0, semantics = 1, pattern = 'c:\[...]\script\node_modules\puppeteer\.local-chromium\win64-768783\chrome-win\*.pdb'
````

In headless mode it hangs until timeout with output as follows.

````
[0714/165729.933:ERROR:sandbox_policy_base.cc(360)] Failed to add sandbox rule. error = 2, subsystem = 0, semantics = 1, pattern = 'c:\[...]\script\node_modules\puppeteer\.local-chromium\win64-768783\chrome-win\*.pdb'
[0714/165729.934:ERROR:sandbox_policy_base.cc(360)] Failed to add sandbox rule. error = 2, subsystem = 0, semantics = 1, pattern = 'c:\[...]\script\node_modules\puppeteer\.local-chromium\win64-768783\chrome-win\*.pdb'
[0714/165729.935:ERROR:sandbox_policy_base.cc(360)] Failed to add sandbox rule. error = 2, subsystem = 0, semantics = 1, pattern = 'c:\[...]\script\node_modules\puppeteer\.local-chromium\win64-768783\chrome-win\*.pdb'
[0714/165729.936:ERROR:sandbox_policy_base.cc(360)] Failed to add sandbox rule. error = 2, subsystem = 0, semantics = 1, pattern = 'c:\[...]\script\node_modules\puppeteer\.local-chromium\win64-768783\chrome-win\*.pdb'
[0714/165729.937:ERROR:sandbox_policy_base.cc(360)] Failed to add sandbox rule. error = 2, subsystem = 0, semantics = 1, pattern = 'c:\[...]\script\node_modules\puppeteer\.local-chromium\win64-768783\chrome-win\*.pdb'
[0714/165729.938:ERROR:sandbox_policy_base.cc(360)] Failed to add sandbox rule. error = 2, subsystem = 0, semantics = 1, pattern = 'c:\[...]\script\node_modules\puppeteer\.local-chromium\win64-768783\chrome-win\*.pdb'
[1736:5636:0714/165729.938:ERROR:browser_gpu_channel_host_factory.cc(153)] Failed to launch GPU process.

DevTools listening on ws://127.0.0.1:63140/devtools/browser/0cc16706-aa94-43c5-92e2-60b7dd1dd56f
[0714/165729.983:ERROR:sandbox_policy_base.cc(360)] Failed to add sandbox rule. error = 2, subsystem = 0, semantics = 1, pattern = 'c:\[...]\script\node_modules\puppeteer\.local-chromium\win64-768783\chrome-win\*.pdb'
[0714/165729.984:ERROR:sandbox_policy_base.cc(360)] Failed to add sandbox rule. error = 2, subsystem = 0, semantics = 1, pattern = 'c:\[...]\script\node_modules\puppeteer\.local-chromium\win64-768783\chrome-win\*.pdb'
[1736:5636:0714/165730.016:ERROR:browser_gpu_channel_host_factory.cc(153)] Failed to launch GPU process.
[0714/165731.086:ERROR:sandbox_policy_base.cc(360)] Failed to add sandbox rule. error = 2, subsystem = 0, semantics = 1, pattern = 'c:\[...]\script\node_modules\puppeteer\.local-chromium\win64-768783\chrome-win\*.pdb'
[0714/165731.087:ERROR:sandbox_policy_base.cc(360)] Failed to add sandbox rule. error = 2, subsystem = 0, semantics = 1, pattern = 'c:\[...]\script\node_modules\puppeteer\.local-chromium\win64-768783\chrome-win\*.pdb'
[0714/165731.089:ERROR:sandbox_policy_base.cc(360)] Failed to add sandbox rule. error = 2, subsystem = 0, semantics = 1, pattern = 'c:\[...]\script\node_modules\puppeteer\.local-chromium\win64-768783\chrome-win\*.pdb'
Failed to convert URL to PDF (TimeoutError - waiting for target failed: timeout 30000ms exceeded)
TimeoutError: waiting for target failed: timeout 30000ms exceeded
    at Object.waitWithTimeout (c:\[...]\script\node_modules\puppeteer\lib\cjs\common\helper.js:156:26)
    at Browser.waitForTarget (c:\[...]\script\node_modules\puppeteer\lib\cjs\common\Browser.js:269:42)
    at ChromeLauncher.launch (c:\[...]\script\node_modules\puppeteer\lib\cjs\node\Launcher.js:107:27)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async c:\[...]\script\h2p.js:20:21
````

With Google Chrome 84:

````
(async function() {
"use strict";

const puppeteer         = require("puppeteer-core");

try {
    const browser = await puppeteer.launch({
                        dumpio: true,
                        executablePath: "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe",
                        headless: true,
                        });
    const page    = await browser.newPage();
    await page.goto('http://think.dolhub.com');
    await page.pdf({path: 'html-page.pdf', format: 'A4'});
    await browser.close();
    }
catch(err) {
    console.log("Failed to convert URL to PDF ("+err.name+" - "+err.message+")");
    console.log(err);
    }
})();
````

In headful mode, the page loads in a new tab, but the script throws the below error and then waits until the GUI window is manually closed, with output as follows.

````
DevTools listening on ws://127.0.0.1:62904/devtools/browser/2337949f-9243-42ed-99b6-fc407fef90a5
Failed to convert URL to PDF (Error - Protocol error (Page.printToPDF): PrintToPDF is not implemented)
Error: Protocol error (Page.printToPDF): PrintToPDF is not implemented
    at c:\[...]\script\node_modules\puppeteer-core\lib\cjs\common\Connection.js:208:63
    at new Promise (<anonymous>)
    at CDPSession.send (c:\[...]\script\node_modules\puppeteer-core\lib\cjs\common\Connection.js:207:16)
    at Page.pdf (c:\[...]\script\node_modules\puppeteer-core\lib\cjs\common\Page.js:1124:43)
    at c:\[...]\script\h2p.js:27:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
````

In headless mode, it hangs until CTRL-C, with output as follows.

````
[0714/164810.991:ERROR:sandbox_policy_base.cc(360)] Failed to add sandbox rule. error = 2, subsystem = 0, semantics = 0, pattern = 'C:\Users\[...]\AppData\Local\Temp\puppeteer_dev_chrome_profile-xhlbFv\Default\chrome_debug.log'
[0714/164810.991:WARNING:gpu_process_host.cc(1233)] The GPU process has crashed 1 time(s)
[0714/164810.992:ERROR:sandbox_policy_base.cc(360)] Failed to add sandbox rule. error = 2, subsystem = 0, semantics = 0, pattern = 'C:\Users\[...]\AppData\Local\Temp\puppeteer_dev_chrome_profile-xhlbFv\Default\chrome_debug.log'
[0714/164810.993:WARNING:gpu_process_host.cc(1233)] The GPU process has crashed 2 time(s)

DevTools listening on ws://127.0.0.1:63089/devtools/browser/ea38bb0f-756b-462b-a48f-29897b33d7da
[0714/164810.994:ERROR:sandbox_policy_base.cc(360)] Failed to add sandbox rule. error = 2, subsystem = 0, semantics = 0, pattern = 'C:\Users\[...]\AppData\Local\Temp\puppeteer_dev_chrome_profile-xhlbFv\Default\chrome_debug.log'
[0714/164810.994:WARNING:gpu_process_host.cc(1233)] The GPU process has crashed 3 time(s)
[0714/164810.995:ERROR:sandbox_policy_base.cc(360)] Failed to add sandbox rule. error = 2, subsystem = 0, semantics = 0, pattern = 'C:\Users\[...]\AppData\Local\Temp\puppeteer_dev_chrome_profile-xhlbFv\Default\chrome_debug.log'
[0714/164810.995:WARNING:gpu_process_host.cc(1233)] The GPU process has crashed 4 time(s)
[0714/164810.997:ERROR:sandbox_policy_base.cc(360)] Failed to add sandbox rule. error = 2, subsystem = 0, semantics = 0, pattern = 'C:\Users\[...]\AppData\Local\Temp\puppeteer_dev_chrome_profile-xhlbFv\Default\chrome_debug.log'
[0714/164810.998:ERROR:sandbox_policy_base.cc(360)] Failed to add sandbox rule. error = 2, subsystem = 0, semantics = 0, pattern = 'C:\Users\[...]\AppData\Local\Temp\puppeteer_dev_chrome_profile-xhlbFv\Default\chrome_debug.log'
[0714/164810.998:WARNING:gpu_process_host.cc(1233)] The GPU process has crashed 5 time(s)
[0714/164810.999:ERROR:sandbox_policy_base.cc(360)] Failed to add sandbox rule. error = 2, subsystem = 0, semantics = 0, pattern = 'C:\Users\[...]\AppData\Local\Temp\puppeteer_dev_chrome_profile-xhlbFv\Default\chrome_debug.log'
[0714/164810.999:WARNING:gpu_process_host.cc(1233)] The GPU process has crashed 6 time(s)
[0714/164810.999:ERROR:browser_gpu_channel_host_factory.cc(153)] Failed to launch GPU process.
[0714/164811.003:ERROR:sandbox_policy_base.cc(360)] Failed to add sandbox rule. error = 2, subsystem = 0, semantics = 0, pattern = 'C:\Users\[...]\AppData\Local\Temp\puppeteer_dev_chrome_profile-xhlbFv\Default\chrome_debug.log'
````

**Comment by christian-bromann** [comment]
There's a note in the docs:

> NOTE Generating a pdf is currently only supported in Chrome headless.

https://pptr.dev/#?product=Puppeteer&version=v5.1.0&show=api-pagepdfoptions

Duplicate of #5059, #1829, #576 

I was able to generate the PDF in headless mode just fine.

**Comment by cornelius-dol** [comment]
@christian-bromann

If you read my report, you'll see that I detailed failure of *both* headless and headful mode, the latter in a desperate attempt to get some insight into why headless mode just hangs.

Can you provide the script, verbatim, that worked for you in Windows 10.

**Comment by christian-bromann** [comment]
> Can you provide the script, verbatim, that worked for you in Windows 10.

Sure, here you go:

```js
const puppeteer = require("puppeteer");

(async function() {
  try {
    const browser = await puppeteer.launch({
      dumpio: true,
      headless: false,
    });
    const page = await browser.newPage();
    await page.goto('http://think.dolhub.com');
    await page.pdf({path: 'html-page.pdf', format: 'A4'});
    await browser.close();
  } catch(err) {
    console.log("Failed to convert URL to PDF ("+err.name+" - "+err.message+")");
    console.log(err);
  }
})();
```

**Comment by hiagodotme** [comment]
Did anyone get a solution to this problem?

**Comment by zackzhang88** [comment]
you could try to move "await browser.close();" to finally part.
