### ISSUE TITLE
page.setExtraHTTPHeaders throws Protocol Error

### ISSUE THREAD

**Issue by NoahCardoza** [puppeteer/puppeteer#6221]
### Steps to reproduce

```js
const P = require('puppeteer');

(async () => {
  const browser = await P.launch({
    product: 'firefox',
    headless: false
  })
  const page = await browser.newPage()
  await page.setExtraHTTPHeaders({
    'X-Testing': '123'
  })
  await page.goto('https://httpbin.org/get')
})().catch(console.error)
```

**Tell us about your environment:**

* Puppeteer version: 3.3.0
* Platform / OS version: MacOS
* URLs (if applicable): https://httpbin.org/get
* Node.js version: v14.2.0

**What is the expected result?**

Headers to be set.

**What happens instead?**

```text
Error: Protocol error (Network.setExtraHTTPHeaders): Network.setExtraHTTPHeaders RemoteAgentError@chrome://remote/content/Error.jsm:25:5
UnknownMethodError@chrome://remote/content/Error.jsm:108:7
execute@chrome://remote/content/domains/DomainCache.jsm:96:13
receiveMessage@chrome://remote/content/sessions/ContentProcessSession.jsm:86:45

    at /Users/USERNAME/projects/CloudProxy/node_modules/puppeteer/lib/Connection.js:152:63
    at new Promise (<anonymous>)
    at CDPSession.send (/Users/USERNAME/projects/CloudProxy/node_modules/puppeteer/lib/Connection.js:151:16)
    at NetworkManager.setExtraHTTPHeaders (/Users/USERNAME/projects/CloudProxy/node_modules/puppeteer/lib/NetworkManager.js:66:28)
    at Page.setExtraHTTPHeaders (/Users/USERNAME/projects/CloudProxy/node_modules/puppeteer/lib/Page.js:354:52)
    at Page.<anonymous> (/Users/USERNAME/projects/CloudProxy/node_modules/puppeteer/lib/helper.js:95:27)
    at /Users/USERNAME/projects/CloudProxy/test.js:11:14
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by mjzffr** [comment]
Thanks for filing. The underlying protocol method is not implemented in Firefox yet. https://bugzilla.mozilla.org/show_bug.cgi?id=1549462

**Comment by NoahCardoza** [comment]
Yeah, I found a graphic somewhere that brought me to that conclusion so I have switched to Chrome for now.

Thanks for all the great work so far!
