### ISSUE TITLE
xpath string(.)

### ISSUE THREAD

**Issue by laosandegudai** [puppeteer/puppeteer#6249]
"puppeteer": "2.1.1"
I want get all text from Element,I use xpath as `string(.)`,I met some exception.

`const title=await titleEle[0].$x('string(.)')`

`Error: Evaluation failed: TypeError: Failed to execute 'evaluate' on 'Document': The result is not a node set, and therefore cannot be converted to the desired type.
    at __puppeteer_evaluation_script__:3:37
    at ExecutionContext._evaluateInternal (e:\Develop\Codes\Program\spider\puppeteer-spider\egg\node_modules\puppeteer\lib\ExecutionContext.js:122:13)
    at async ElementHandle.evaluateHandle (e:\Develop\Codes\Program\spider\puppeteer-spider\egg\node_modules\puppeteer\lib\JSHandle.js:63:12)
    at async ElementHandle.$x (e:\Develop\Codes\Program\spider\puppeteer-spider\egg\node_modules\puppeteer\lib\JSHandle.js:532:25)
    at async e:\Develop\Codes\Program\spider\puppeteer-spider\egg\infoq.js:42:21
  -- ASYNC --
    at ExecutionContext.<anonymous> (e:\Develop\Codes\Program\spider\puppeteer-spider\egg\node_modules\puppeteer\lib\helper.js:111:15)
    at ElementHandle.evaluateHandle (e:\Develop\Codes\Program\spider\puppeteer-spider\egg\node_modules\puppeteer\lib\JSHandle.js:63:42)
    at ElementHandle.<anonymous> (e:\Develop\Codes\Program\spider\puppeteer-spider\egg\node_modules\puppeteer\lib\helper.js:112:23)
    at ElementHandle.$x (e:\Develop\Codes\Program\spider\puppeteer-spider\egg\node_modules\puppeteer\lib\JSHandle.js:532:36)
    at ElementHandle.<anonymous> (e:\Develop\Codes\Program\spider\puppeteer-spider\egg\node_modules\puppeteer\lib\helper.js:112:23)
    at e:\Develop\Codes\Program\spider\puppeteer-spider\egg\infoq.js:42:39 {stack: 'Error: Evaluation failed: TypeError: Failed t…am\spider\puppeteer-spider\egg\infoq.js:42:39', message: 'Evaluation failed: TypeError: Failed to exec…
    at __puppeteer_evaluation_script__:3:37'}`

I know this is a special return value, but it is the correct xpath.

**Comment by vsemozhetbyt** [comment]
If you need text nodes of an Element, you need `const title=await titleEle[0].$x('./text()')`, but I am not sure if a text node is a valid puppeteer Element handler.

**Comment by laosandegudai** [comment]
> If you need text nodes of an Element, you need `const title=await titleEle[0].$x('./text()')`, but I am not sure if a text node is a valid puppeteer Element handler.

yes,i also do it.
`_remoteObject:{type: 'undefined'}`

but no exception.

I wanted to find a good way to get all the text, and I came up with xpath, but I found that only the convenience works for now.
Thank you.

**Comment by vsemozhetbyt** [comment]
If `.innerText` or `.textContent` in browser context do not suffice, you can try to collect text nodes in the browser context with xPath (`document.evaluate()`) and transfer them as texts.

**Comment by laosandegudai** [comment]
Yes, text nodes can be used, but they are not as fast as srting(.).
thank you.
