### ISSUE TITLE
TypeError: Cannot read property '_productName' of undefined

### ISSUE THREAD

**Issue by srcnalt** [puppeteer/puppeteer#6266]
I am trying to use `puppeteer-core` and `chrome-aws-lambda` to render a website server side, it is a `React & Next.js` project. The point of start was this project, were it works fine on [this non-Next.js example](https://github.com/vercel/og-image).

Either I deploy to Vercel or run locally I get `TypeError: Cannot read property '_productName' of undefined` error.

### Steps to reproduce

**Tell us about your environment:**

**Puppeteer version:**
- puppeteer-core: 2.1.1
- chrome-aws-lambda: 2.1.1

**Platform / OS version:**
- Win10, 64

**URLs (if applicable):**
- https://github.com/srcnalt/web-render

**Node.js version:
- node -v: v12.13.1
- npm -v: 6.12.1

**What steps will reproduce the problem?**
1. Clone the repo from `https://github.com/srcnalt/web-render`
2. run `npm i`
3. observe the error message: 
```
TypeError: Cannot read property '_productName' of undefined
    at launch (...\web-render\node_modules\puppeteer-core\lib\Puppeteer.js:38:15)
    at Post (...\web-render\.next\server\static\development\pages\api\web-render.js:274:86)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async module.exports../pages/api/web-render.js.__webpack_exports__.default (...\web-render\.next\server\static\development\pages\api\web-render.js:230:7)        
    at async apiResolver (...\web-render\node_modules\next\dist\next-server\server\api-utils.js:6:1)
    at async DevServer.handleApiRequest (...\web-render\node_modules\next\dist\next-server\server\next-server.js:43:397)
    at async Object.fn (...\web-render\node_modules\next\dist\next-server\server\next-server.js:35:764)
    at async Router.execute (...\web-render\node_modules\next\dist\next-server\server\router.js:28:28)
    at async DevServer.run (...\web-render\node_modules\next\dist\next-server\server\next-server.js:44:494)
    at async DevServer.handleRequest (...\web-render\node_modules\next\dist\next-server\server\next-server.js:13:133)
```
---

## **Update:**
Upgrading to [`puppeteer-core 3.1.0` and `chrome-aws-lambda 3.1.1`](https://github.com/alixaxel/chrome-aws-lambda#versioning) yields `TypeError: Cannot read property '_launcher' of undefined`

**Comment by srcnalt** [comment]
Using puppeteer from chrome-aws-lambda, instead of importing puppeteer solved the issue.

**Comment by tsathis** [comment]
@srcnalt I'm also getting the exact problem, Happy to see you have resolved it. Can you please explain what is meant by 
> Using puppeteer from chrome-aws-lambda

**Comment by pbteja1998** [comment]
I faced the same problem. This is what worked for me.

**Before:**
```js
import { launch } from 'puppeteer-core'

const browser = await launch(options)
```

**After:**
```js
import { puppeteer } from 'chrome-aws-lambda'

const browser = await puppeteer.launch(options)
```
