### ISSUE TITLE
console.log is weirdly-formatted and too verbose after upgrading puppeteer from 2.0.0 to 5.2.1

### ISSUE THREAD

**Issue by RonMichaeli** [puppeteer/puppeteer#6280]
I'm running tests locally using puppeteer and the tests are doing a lot of `console.log` for debugging purposes.
Today I've upgraded `puppeteer` to `5.2.1` and noticed to `console.log` output now looks different - it seems to include the stack trace of the logged line along with blank lines - which makes the output extremely long and barely readable.

Current output format:
```
17:54:33 PASS src/tests/archiveProgram.test.ts (16.865 s)
17:54:33   ● Console
17:54:33 
17:54:33     console.log
17:54:33       Launching Puppeteer...
17:54:33 
17:54:33       at Object.initSession (src/TestRunner.ts:38:17)
17:54:33 
17:54:33     console.log
17:54:33       Puppeteer is running on local environment
17:54:33 
17:54:33       at getBrowser (src/TestRunner.ts:68:17)
17:54:33 
17:54:33     console.log
17:54:33       Puppeteer launched successfully
17:54:33 
17:54:33       at Object.initSession (src/TestRunner.ts:40:17)
17:54:33 
17:54:33     console.log
17:54:33       Opening browser...
17:54:33 
17:54:33       at Object.initSession (src/TestRunner.ts:42:17)
17:54:33 
17:54:33     console.log
17:54:33       Browser opened successfully
17:54:33 
17:54:33       at Object.initSession (src/TestRunner.ts:44:17)
17:54:33 
17:54:33     console.log
17:54:33       Logging in to Studio...
17:54:33 
17:54:33       at Object.exports.loginAndNavigateToAccountPage (src/common/actions/hubUIActions.ts:244:13)
17:54:33 
17:54:33     console.log
17:54:33       Looking for introduction dialog
17:54:33 
17:54:33       at handleIntroductionNewStudioNavigationDialog (src/common/actions/hubUIActions.ts:139:13)
17:54:33 
17:54:33     console.log
17:54:33       Logged in successfully
17:54:33 
17:54:33       at Object.exports.loginAndNavigateToAccountPage (src/common/actions/hubUIActions.ts:246:13)
17:54:33 
17:54:33     console.log
17:54:33       Navigating to account ID 0010b00002R0wc3AAB...
17:54:33 
17:54:33       at Object.exports.loginAndNavigateToAccountPage (src/common/actions/hubUIActions.ts:248:13)
17:54:33 
17:54:33     console.log
17:54:33       Navigation completed
17:54:33 
17:54:33       at Object.exports.loginAndNavigateToAccountPage (src/common/actions/hubUIActions.ts:251:13)
17:54:33 
17:54:33     console.log
17:54:33       Creating new program "Archive program E2E Test 27-7-2020-14-54-28-774"...
17:54:33 
17:54:33       at Object.<anonymous> (src/tests/archiveProgram.test.ts:30:21)
17:54:33 
17:54:33     console.log
17:54:33       Navigating to "All Programs"...
17:54:33 
17:54:33       at Object.exports.createNewProgram (src/common/actions/hubUIActions.ts:151:13)
17:54:33 
17:54:33     console.log
17:54:33       Opening New Program dialog...
17:54:33 
17:54:33       at Object.exports.createNewProgram (src/common/actions/hubUIActions.ts:160:13)
17:54:33 
17:54:33     console.log
17:54:33       Setting program name...
17:54:33 
17:54:33       at Object.exports.createNewProgram (src/common/actions/hubUIActions.ts:165:13)
17:54:33 
17:54:33     console.log
17:54:33       Setting program type...
17:54:33 
17:54:33       at Object.exports.createNewProgram (src/common/actions/hubUIActions.ts:169:13)
17:54:33           at runMicrotasks (<anonymous>)
17:54:33 
17:54:33     console.log
17:54:33       Saving program...
17:54:33 
17:54:33       at Object.exports.createNewProgram (src/common/actions/hubUIActions.ts:173:13)
17:54:33           at runMicrotasks (<anonymous>)
17:54:33 
17:54:33     console.log
17:54:33       Program created successfully
17:54:33 
17:54:33       at Object.<anonymous> (src/tests/archiveProgram.test.ts:32:21)
17:54:33           at runMicrotasks (<anonymous>)
17:54:33 
17:54:33     console.log
17:54:33       Verifying that we are under All but Archived filter...
17:54:33 
17:54:33       at Object.<anonymous> (src/tests/archiveProgram.test.ts:53:27)
17:54:33           at runMicrotasks (<anonymous>)
17:54:33 
17:54:33     console.log
17:54:33       clicking program's context menu and selecting Archive...
17:54:33 
17:54:33       at Object.<anonymous> (src/tests/archiveProgram.test.ts:56:27)
17:54:33           at runMicrotasks (<anonymous>)
17:54:33 
17:54:33     console.log
17:54:33       clicking confirmation to Archive program...
17:54:33 
17:54:33       at Object.<anonymous> (src/tests/archiveProgram.test.ts:62:27)
17:54:33           at runMicrotasks (<anonymous>)
17:54:33 
17:54:33     console.log
17:54:33       expecting the program that have been archive to disappear from view...
17:54:33 
17:54:33       at Object.<anonymous> (src/tests/archiveProgram.test.ts:66:27)
17:54:33           at runMicrotasks (<anonymous>)
17:54:33 
17:54:33     console.log
17:54:33       setting drawer filter to archived
17:54:33 
17:54:33       at Object.exports.selectMainProgramsDrawerFilter (src/common/actions/hubUIActions.ts:194:19)
17:54:33           at runMicrotasks (<anonymous>)
17:54:33 
17:54:33     console.log
17:54:33       Verifying that we are under archived filter...
17:54:33 
17:54:33       at Object.exports.selectMainProgramsDrawerFilter (src/common/actions/hubUIActions.ts:198:19)
17:54:33           at runMicrotasks (<anonymous>)
17:54:33 
17:54:33     console.log
17:54:33       expecting the program that have been archive to appear in drawer...
17:54:33 
17:54:33       at Object.<anonymous> (src/tests/archiveProgram.test.ts:70:27)
17:54:33           at runMicrotasks (<anonymous>)
17:54:33 
17:54:33     console.log
17:54:33       clicking program's context menu and selecting Unarchive...
17:54:33 
17:54:33       at Object.<anonymous> (src/tests/archiveProgram.test.ts:73:27)
17:54:33           at runMicrotasks (<anonymous>)
17:54:33 
17:54:33     console.log
17:54:33       expecting the program that have been archive to disappear from view...
17:54:33 
17:54:33       at Object.<anonymous> (src/tests/archiveProgram.test.ts:77:27)
17:54:33           at runMicrotasks (<anonymous>)
17:54:33 
17:54:33     console.log
17:54:33       setting drawer filter to notArchived
17:54:33 
17:54:33       at Object.exports.selectMainProgramsDrawerFilter (src/common/actions/hubUIActions.ts:194:19)
17:54:33           at runMicrotasks (<anonymous>)
17:54:33 
17:54:33     console.log
17:54:33       Verifying that we are under notArchived filter...
17:54:33 
17:54:33       at Object.exports.selectMainProgramsDrawerFilter (src/common/actions/hubUIActions.ts:198:19)
17:54:33           at runMicrotasks (<anonymous>)
17:54:33 
17:54:33     console.log
17:54:33       expecting the program that have been unarchive to appear in drawer...
17:54:33 
17:54:33       at Object.<anonymous> (src/tests/archiveProgram.test.ts:81:27)
17:54:33           at runMicrotasks (<anonymous>)
17:54:33 
17:54:33     console.log
17:54:33       Test took 4.413138531 seconds
17:54:33 
17:54:33       at Object.stopTestTiming (src/TestRunner.ts:101:17)
17:54:33           at runMicrotasks (<anonymous>)
17:54:33 
17:54:33     console.log
17:54:33       Closing browser...
17:54:33 
17:54:33       at Object.terminateSession (src/TestRunner.ts:135:17)
17:54:33           at runMicrotasks (<anonymous>)
17:54:33 
17:54:33     console.log
17:54:33       Browser closed successfully
17:54:33 
17:54:33       at Object.terminateSession (src/TestRunner.ts:137:17)
17:54:33 
```

Previous output format:
```
15:55:31 PASS src/tests/archiveProgram.test.ts (16.69s)
15:55:31   ● Console
15:55:31 
15:55:31     console.log src/TestRunner.ts:38
15:55:31       Launching Puppeteer...
15:55:31     console.log src/TestRunner.ts:68
15:55:31       Puppeteer is running on local environment
15:55:31     console.log src/TestRunner.ts:40
15:55:31       Puppeteer launched successfully
15:55:31     console.log src/TestRunner.ts:42
15:55:31       Opening browser...
15:55:31     console.log src/TestRunner.ts:44
15:55:31       Browser opened successfully
15:55:31     console.log src/common/actions/hubUIActions.ts:239
15:55:31       Logging in to Studio...
15:55:31     console.log src/common/actions/hubUIActions.ts:134
15:55:31       Looking for introduction dialog
15:55:31     console.log src/common/actions/hubUIActions.ts:241
15:55:31       Logged in successfully
15:55:31     console.log src/common/actions/hubUIActions.ts:243
15:55:31       Navigating to account ID 0010b00002R0wc3AAB...
15:55:31     console.log src/common/actions/hubUIActions.ts:246
15:55:31       Navigation completed
15:55:31     console.log src/tests/archiveProgram.test.ts:29
15:55:31       Creating new program "Archive program E2E Test 27-7-2020-12-55-27-46"...
15:55:31     console.log src/common/actions/hubUIActions.ts:146
15:55:31       Navigating to "All Programs"...
15:55:31     console.log src/common/actions/hubUIActions.ts:155
15:55:31       Opening New Program dialog...
15:55:31     console.log src/common/actions/hubUIActions.ts:160
15:55:31       Setting program name...
15:55:31     console.log src/common/actions/hubUIActions.ts:164
15:55:31       Setting program type...
15:55:31     console.log src/common/actions/hubUIActions.ts:168
15:55:31       Saving program...
15:55:31     console.log src/tests/archiveProgram.test.ts:31
15:55:31       Program created successfully
15:55:31     console.log src/tests/archiveProgram.test.ts:52
15:55:31       Verifying that we are under All but Archived filter...
15:55:31     console.log src/tests/archiveProgram.test.ts:55
15:55:31       clicking program's context menu and selecting Archive...
15:55:31     console.log src/tests/archiveProgram.test.ts:61
15:55:31       clicking confirmation to Archive program...
15:55:31     console.log src/tests/archiveProgram.test.ts:65
15:55:31       expecting the program that have been archive to disappear from view...
15:55:31     console.log src/common/actions/hubUIActions.ts:189
15:55:31       setting drawer filter to archived
15:55:31     console.log src/common/actions/hubUIActions.ts:193
15:55:31       Verifying that we are under archived filter...
15:55:31     console.log src/tests/archiveProgram.test.ts:69
15:55:31       expecting the program that have been archive to appear in drawer...
15:55:31     console.log src/tests/archiveProgram.test.ts:72
15:55:31       clicking program's context menu and selecting Unarchive...
15:55:31     console.log src/tests/archiveProgram.test.ts:76
15:55:31       expecting the program that have been archive to disappear from view...
15:55:31     console.log src/common/actions/hubUIActions.ts:189
15:55:31       setting drawer filter to notArchived
15:55:31     console.log src/common/actions/hubUIActions.ts:193
15:55:31       Verifying that we are under notArchived filter...
15:55:31     console.log src/tests/archiveProgram.test.ts:80
15:55:31       expecting the program that have been unarchive to appear in drawer...
15:55:31     console.log src/TestRunner.ts:101
15:55:31       Test took 4.628601666000001 seconds
15:55:31     console.log src/TestRunner.ts:135
15:55:31       Closing browser...
15:55:31     console.log src/TestRunner.ts:137
15:55:31       Browser closed successfully
15:55:31 
```

* Puppeteer version: 5.2.1
* Platform / OS version: Windows 10
* Node.js version: 10.15.3

`package.json`:
```
{
  "dependencies": {
    "@sundaysky/smartvideo-hub-s3": "^1.4.8",
    "@types/jest": "26.0.7",
    "@types/puppeteer": "^3.0.1",
    "@typescript-eslint/eslint-plugin": "3.7.0",
    "@typescript-eslint/parser": "3.7.0",
    "aws-sdk": "2.720.0",
    "faker": "4.1.0",
    "jest": "26.1.0",
    "jest-image-snapshot": "4.1.0",
    "puppeteer": "5.2.1",
    "tmp": "0.2.1",
    "ts-jest": "26.1.3",
    "typescript": "3.9.7"
  },
  "devDependencies": {
    "eslint": "7.5.0",
    "eslint-plugin-jest": "23.18.2"
  },
  "jest": {
    "preset": "ts-jest"
  }
}
```

How can I restore the previous `console.log` output format?

Thanks!

**Comment by vinothdevelop** [comment]
Are you using jest? Jest will have that stack trace.

**Comment by RonMichaeli** [comment]
Yep, I downgraded Jest back to `24.8.0` and the format is back to "normal".
Thanks!
Closing this one.
