### ISSUE TITLE
waitForFileChooser

### ISSUE THREAD

**Issue by nosers** [puppeteer/puppeteer#6419]
I followed the examples of 'puppeteer' and 'issue', but there was a problem and I couldn't find a solution.

**Tell us about your environment:**
* Puppeteer version: Puppeteer@5.3.0 / Chrome@85.0.4183.102
* Platform / OS version: Windows / 10 Enterprise
* URLs (if applicable): None
* Node.js version: 12.18.3

**What steps will reproduce the problem?**
```
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({
        product: "chrome",
        executablePath: "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe",
        ignoreDefaultArgs: ['--disable-extensions'],
        headless: false,
    });

    const page = await browser.newPage();
    await page.goto('about:blank');
    await page.setContent('<input type="file">');

    await page.waitForFileChooser()
        .then(value => {
            console.log(value);
        })
        .catch(reason => {
            console.log(reason);
        });
})();
```
**What is the expected result?**

`return variable Promise<FileChooser>`

**What happens instead?**
```
Error: Protocol error (Page.setInterceptFileChooserDialog): 'Page.setInterceptFileChooserDialog' wasn't found
    at c:\Users\MT01045\node_modules\puppeteer\lib\Connection.js:183:56
    at new Promise (<anonymous>)
    at CDPSession.send (c:\Users\MT01045\node_modules\puppeteer\lib\Connection.js:182:12)
    at Page.waitForFileChooser (c:\Users\MT01045\node_modules\puppeteer\lib\Page.js:163:26)
    at Page.<anonymous> (c:\Users\MT01045\node_modules\puppeteer\lib\helper.js:112:23)
    at c:\Users\MT01045\git\webmail\test.js:15:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {message: 'Protocol error (Page.setInterceptFileChooser….setInterceptFileChooserDialog' wasn't found', stack: 'Error: Protocol error (Page.setInterceptFileC…ctions (internal/process/task_queues.js:97:5)'}
```

**Comment by nosers** [comment]
Chrome reinstallation and module reinstallation have resolved this issue.
