### ISSUE TITLE
Error when generating a larger jpeg file

### ISSUE THREAD

**Issue by qubiack** [puppeteer/puppeteer#6428]
When the file is bigger than 1757x2835px puppeteer throws an error as below, for example for file 1984x2835

```
PP2          | 1. Launch browser
PP2          | 2. Browser is launched
PP2          | 3. Page is created
PP2          | 1984 2835
PP2          | 4. Viewport settings are applied
PP2          | GET /api/stars/d3-celestial/svg?uuid=b29a5862-086b-403d-ad12-1bdee3668d37 200 50.069 ms - 298038
PP2          | 5. Go to page is done
PP2          | 6. #d3map is appear on page
PP2          | generator data manipulation error { Error: Protocol error (Page.captureScreenshot): Internal error
PP2          |     at Promise (/home/api/node_modules/puppeteer/lib/cjs/common/Connection.js:181:63)
PP2          |     at new Promise (<anonymous>)
PP2          |     at CDPSession.send (/home/api/node_modules/puppeteer/lib/cjs/common/Connection.js:180:16)
PP2          |     at Page._screenshotTask (/home/api/node_modules/puppeteer/lib/cjs/common/Page.js:966:43)
PP2          |     at process._tickCallback (internal/process/next_tick.js:68:7)
PP2          |   -- ASYNC --
PP2          |     at Page.<anonymous> (/home/api/node_modules/puppeteer/lib/cjs/common/helper.js:109:19)
PP2          |     at Function.<anonymous> (/home/api/src/app/services/_renderer/rendererPuppeteer.service.ts:77:37)
PP2          |     at step (/home/api/build/app/services/_renderer/rendererPuppeteer.service.js:33:23)
PP2          |     at Object.next (/home/api/build/app/services/_renderer/rendererPuppeteer.service.js:14:53)
PP2          |     at fulfilled (/home/api/build/app/services/_renderer/rendererPuppeteer.service.js:5:58)
PP2          |   message: 'Protocol error (Page.captureScreenshot): Internal error' }
PP2          | 8. Browser is closd properly
```

My configuration:
Docker 19.03.8
Docker-compose start a process like this:
```
  api:
    build:
      context: ${API_SOURCE}
      dockerfile: ${COMPOSE_PATH}/PP2/Dockerfile
      args:
        - API_ENVIRONMENT=${API_ENVIRONMENT}
    container_name: PP2
    restart: always
    networks:
      some_network:
        ipv4_address: 173.18.0.20
    ports:
      - "3200:3200"
    volumes:
      - type: bind
        source: ${CACHE_SRC}
        target: /cache
      - type: bind
        source: ${PS_SRC}
        target: /ps
      - type: bind
        source: ${API_SQLITE}
        target: /home/api/db.sqlite3
```
Inside a container I use: Ubuntu:20.04
Node.js 10

And my ts script that run this puppeter with logs:
```
        /**
         * 1. Create Puppeteer browser
         * 2. Check if application is active
         * 3. Break if any errors occurs
         */
        try {
            console.log('1. Launch browser');
            browser = await puppeteer.launch({
                headless: true,
                args: [
                    '--no-sandbox',
                    '--disable-dev-shm-usage',
                    '--disable-web-security',
                ]
            });
            console.log('2. Browser is launched');
        } catch (e) {
            try {
                console.log(ProgramErrorEnum.GENERATOR_ERROR_INITIALIZE, e);
                await browser.close();
            } catch (e) {
                console.log(ProgramErrorEnum.GENERATOR_ERROR_INITIALIZE + 'browser.exit() ', e);
            }
            throw ProgramErrorEnum.GENERATOR_ERROR_INITIALIZE;
        }

        /**
         * 1. Open new page in Puppeteer
         * 2. Set page properties to Viewport
         * 3. Open url from config in PhantomJS
         */
        try {
            page = await browser.newPage();
            console.log('3. Page is created');
            console.log(config.format.width, config.format.height);
            await page.setViewport({
                width: config.format.width,
                height: config.format.height,
                deviceScaleFactor: 1,
            });
            console.log('4. Viewport settings are applied');
            await page.goto(process.env.RENDERER + config.uri, {});
            console.log('5. Go to page is done');
            await page.waitForSelector('#d3map');
            await page.waitFor(2000);
            console.log('6. #d3map is appear on page');
        } catch (e) {
            try {
                console.log(ProgramErrorEnum.GENERATOR_ERROR, e);
                await browser.close();
            } catch (e) {
                console.log(ProgramErrorEnum.GENERATOR_ERROR + 'browser.exit()', e);
            }
            throw ProgramErrorEnum.GENERATOR_ERROR;
        }

        /**
         * 1. Get base64 code from page (as print screen)
         * 2. Close PhantomJS page
         * 3. Convert Base64 to Buffer - Buffer is Node.JS proper format to store binary images
         */
        try {
            if (config.fileType === ImgFormatEnum.JPEG || config.fileType === ImgFormatEnum.PNG) {
                render = await page.screenshot({
                    encoding: "binary",
                    omitBackground: config.fileType === ImgFormatEnum.PNG,
                    type: config.fileType,
                    width: Math.ceil(config.format.width) + 'px',
                    height: Math.ceil(config.format.height) + 'px',
                    quality: 100,
                    margin: {
                        top: 0,
                        right: 0,
                        bottom: 0,
                        left: 0,
                    }
                })
                console.log('7. screenshot is done');
            } else if (config.fileType === ImgFormatEnum.PDF || config.fileType === ImgFormatEnum.PDF_TO_JPEG) {
                const pdfOptions: PDFOptions = {
                    width: Math.round(config.format.width * 96 / 72) + 'px',
                    height: Math.round(config.format.height * 96 / 72) + 'px',
                    pageRanges: '1',
                    margin: {
                        top: 0,
                        right: 0,
                        bottom: 0,
                        left: 0,
                    },
                    printBackground: true
                }

                // console.log('7.0. ready to apply emulated media type - PRINT');
                // await page.emulateMediaType('print');
                console.log('7.1. emulated media type - applied');
                render = await page.pdf(pdfOptions);
                console.log('7.2. PDF screenshot is done');
            }
        } catch (e) {
            try {
                console.log(ProgramErrorEnum.GENERATOR_ERROR_DATA_MANIPULATION, e);
                await browser.close();
            } catch (e) {
                console.log(ProgramErrorEnum.GENERATOR_ERROR_DATA_MANIPULATION + ' browser.exit() ', e);
            }
            throw ProgramErrorEnum.GENERATOR_ERROR_DATA_MANIPULATION;
        } finally {
            // Close PhantomJS process
            await browser.close();
            console.log('8. Browser is closd properly');
        }
```

And my docker info:
```
Client:
 Debug Mode: false

Server:
 Containers: 6
  Running: 6
  Paused: 0
  Stopped: 0
 Images: 166
 Server Version: 19.03.9
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-99-generic
 Operating System: Ubuntu 18.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.852GiB
 Name: DEV
 ID: YC6C:CVNY:G4OD:FMZN:SQ5T:BAG5:63R7:DP2P:ONAN:MGVR:JWAM:UJAW
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by ASGdev** [comment]
Could you ensure you are using the latest version Chromium packaged with the latest puppeteer package (npm update) ? I have just updated it maybe 30 minutes ago, and I am now able to take larger screenshots than before (last one was width=1349px and height=136305px).
Platform: Windows 10 64bits
Node : v12.16.3
Puppeteer : 5.3.0
