### ISSUE TITLE
Linux uses puppeter to open browser and report error

### ISSUE THREAD

**Issue by fubojuan** [puppeteer/puppeteer#6494]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:5.3.1
* Platform / OS version:Linux version 4.18.20-1.el7
* Node.js version:10.15.1

**What steps will reproduce the problem?**
excute follow code

_Please include code that reproduces the issue._

```
 console.log('open browser');
    const browser = await puppeteer.launch({
        headless:true,
        //executablePath:'/opt/web/ajk_qa_mpservice/node_modules/puppeteer/.local-chromium/linux-800071/chrome-linux/chrome',
        args:[
            '--no-sandbox',
            '--disable-setuid-sandbox'
        ]
    });
    console.log("open browser success")
    const page = await browser.newPage();
    await page.setDefaultNavigationTimeout(0);
    await page.goto('https://example.com');
    console.log("open example")
    await page.screenshot({path: 'example.png'});
```

**What is the expected result?**
```
open browser and goto https://example.com,take a screenshot and save it.
```

**What happens instead?**
```
https://servicewechat.com/wxa/ci/getonlineschema Error: connect ETIMEDOUT 182.254.79.100:443
get online schema fail Error: connect ETIMEDOUT 182.254.79.100:443
(node:2992) UnhandledPromiseRejectionWarning: Error: net::ERR_CONNECTION_TIMED_OUT at https://example.com
    at navigate (/opt/web/ajk_qa_mpservice/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:115:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:2992) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2992) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ghost** [comment]
Have the same issue. Any suggestions?
