### ISSUE TITLE
Recursively open new pages => Error: Protocol error (Target.createTarget): Target closed.

### ISSUE THREAD

**Issue by CaptainFemur** [puppeteer/puppeteer#6632]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: ^5.5.0
* Platform / OS version: Windows 10
* Node.js version: v13.14.0

**What steps will reproduce the problem?**

Here is my code :

```
const getAllUrl = async (browser, urlList, urlListCrawled) => {
    if(urlList.length > 0){
        const page = await browser.newPage();
        const url = urlList.shift();
        if(urlListCrawled.includes(url)){
            getAllUrl(browser, urlList, urlListCrawled);
        }
        await page.goto(url);
        await page.waitForSelector('body');
        const allHrefs = await page.evaluate(() =>
            [...document.querySelectorAll('a[href*="specificurl"]')].map(link => link.href)
        );

        urlListCrawled.push(url);
        urlList = [...urlList,...allHrefs];

        //await page.close();
        getAllUrl(browser, urlList, urlListCrawled);
    } else {
        return urlListCrawled;
    }
}

const scrap = async () => {
    const browser = await puppeteer.launch({ headless: false });
    let urlListCrawled = [];
    let urlList = ["mywebsiteurl"];
    const result = await getAllUrl(browser, urlList, urlListCrawled);
    browser.close();
    return result;
}

scrap()
  .then(value => {
        console.log('The end');
        console.log(value);
  })
  .catch(e => console.log(`error: ${e}`))


```

**What is the expected result?**

I want to make a function that crawl my website to check all URLs, this is why I made it recursive, because I retrieved new URLs on the fly. So, I want Puppeteer to check all urls in "urlList" until it's empty, and then return the list of urls crawled. 

**What happens instead?**

My script stop and the error below show up in my console. My function getAllUrl is called one time, retrieve some urls, and then, when it's called another time with the new list, it stop at "const page = browser.newPage()" and then, it get out of getAllUrl to "browser.close()", and in the console log I have "The end" and "Undefined" insted of my list of urls crawled. I tried to put "await page.close();" after calling another time my function but it's not working.

```
(node:22592) UnhandledPromiseRejectionWarning: Error: Protocol error (Target.createTarget): Target closed.
    at C:\Tools\crawler\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:71:63
    at new Promise (<anonymous>)
    at Connection.send (C:\Tools\crawler\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:70:16)
    at Browser._createPageInContext (C:\Tools\crawler\node_modules\puppeteer\lib\cjs\puppeteer\common\Browser.js:221:53)
    at BrowserContext.newPage (C:\Tools\crawler\node_modules\puppeteer\lib\cjs\puppeteer\common\Browser.js:500:30)
    at Browser.newPage (C:\Tools\crawler\node_modules\puppeteer\lib\cjs\puppeteer\common\Browser.js:214:37)
    at getAllUrl (C:\Tools\crawler\app\cssCrawler.js:22:38)
    at getAllUrl (C:\Tools\crawler\app\cssCrawler.js:59:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async scrap (C:\Tools\crawler\app\cssCrawler.js:95:20)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:22592) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promi
se which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli
_unhandled_rejections_mode). (rejection id: 1)
(node:22592) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-ze
ro exit code.
```

Ps : Sorry if my English is not perfect, I'm French.

**Comment by vsemozhetbyt** [comment]
Inside `getAllUrl()`, try to replace
```
getAllUrl(browser, urlList, urlListCrawled);
```
with
```
return getAllUrl(browser, urlList, urlListCrawled);
```
— otherwise all recursive calls except the last return a Promise that resolves in `undefined`.

**Comment by CaptainFemur** [comment]
Damn, you are right.

It works perfectly now, thanks you !
