### ISSUE TITLE
Error when uploading a file in Firefox (DOM.setFileInputFiles not implemented)

### ISSUE THREAD

**Issue by 787681277** [puppeteer/puppeteer#6688]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:5.5.0
* Platform / OS version:macOS High Sierra 10.13.6
* URLs (if applicable):
* Node.js version:v12.16.1

**What steps will reproduce the problem?**
simulate users to upload a file in firefox browser

err Error: Protocol error (DOM.setFileInputFiles): DOM.setFileInputFiles RemoteAgentError@chrome://remote/content/Error.jsm:25:5
UnknownMethodError@chrome://remote/content/Error.jsm:108:7
execute@chrome://remote/content/domains/DomainCache.jsm:96:13
receiveMessage@chrome://remote/content/sessions/ContentProcessSession.jsm:86:45

    at /Users/llu159/Documents/GitHub/AutomationTestingFramework/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:208:63
    at new Promise (<anonymous>)
    at CDPSession.send (/Users/llu159/Documents/GitHub/AutomationTestingFramework/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:207:16)
    at ElementHandle.uploadFile (/Users/llu159/Documents/GitHub/AutomationTestingFramework/node_modules/puppeteer/lib/cjs/puppeteer/common/JSHandle.js:475:32)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async TestEngineCore.runningTest [as _runningTest] (/Users/llu159/Documents/GitHub/AutomationTestingFramework/engine/TestEngineCore.js:283:11)
    at async TestEngineCore.checkBeforeTest [as _checkBeforeTest] (/Users/llu159/Documents/GitHub/AutomationTestingFramework/engine/TestEngineCore.js:490:5)
    at async TestEngineCore.traverseTestComponents [as _traverseTestComponents] (/Users/llu159/Documents/GitHub/AutomationTestingFramework/engine/TestEngineCore.js:559:5)
    at async TestEngineCore._init (/Users/llu159/Documents/GitHub/AutomationTestingFramework/engine/TestEngineCore.js:627:9) {
  message: 'Protocol error (DOM.setFileInputFiles): DOM.setFileInputFiles RemoteAgentError@chrome://remote/content/Error.jsm:25:5\n' +
    'UnknownMethodError@chrome://remote/content/Error.jsm:108:7\n' +
    'execute@chrome://remote/content/domains/DomainCache.jsm:96:13\n' +
    'receiveMessage@chrome://remote/content/sessions/ContentProcessSession.jsm:86:45\n'

_Please include code that reproduces the issue._

1.        let inputUpload = await page.$(":focus>input");
        if (inputUpload)
        {
          // console.log("inputUpload is : ",inputUpload)
          await inputUpload.uploadFile('/Users/llu159/Desktop/talentlink.png');
          await page.waitFor(3000);
          await this._CaptureScreenshot(page,type,action);
          break;
        }
        else return;
2.

3.

**What is the expected result?**
It should work like that in chromium browser

**What happens instead?**
The does not occur in chromium browser

**Comment by whimboo** [comment]
The API for [DOM.setFileInputFiles](https://bugzilla.mozilla.org/show_bug.cgi?id=1553847) hasn't been implemented yet in Firefox.

**Comment by whimboo** [comment]
Closing the issue given that it is very unlikely that we will implement this API. Our focus is on WebDriver BiDi and to get this running properly.
