### ISSUE TITLE
Error: Failed to launch the browser process! in cpanel

### ISSUE THREAD

**Issue by Ilmans** [puppeteer/puppeteer#6755]
(node:3305601) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
/domain/11/lib/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory

i got this error and i try to find how to fix that, i found many tips for fix it, but i dont know how to fix it in the cpanel.
could you help me

**Comment by andretunes** [comment]
Hello!
If you're using Ubuntu 18.04 you need to install the dependency `libatk-bridge2.0-0`. Can you tell me what Operating System are you using?

**Comment by nodecentral** [comment]
Hi,

I have the same on my pi, is the fix above the same ?

````

pi@raspberrypi:~/Pictures $ pageres google.com
Error: Failed to launch the browser process!
/usr/local/lib/node_modules/pageres-cli/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome: 1: /usr/local/lib/node_modules/pageres-cli/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome: Syntax error: "(" unexpected


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/usr/local/lib/node_modules/pageres-cli/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at Interface.<anonymous> (/usr/local/lib/node_modules/pageres-cli/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)
    at Interface.emit (node:events:391:22)
    at Interface.close (node:readline:451:8)
    at Socket.onend (node:readline:224:10)
    at Socket.emit (node:events:391:22)
    at endReadableNT (node:internal/streams/readable:1307:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)

**Comment by andretunes** [comment]
Hello,

Can you try this install below?
`sudo apt-get install gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget`

**Comment by nodecentral** [comment]
Thanks 

Done,  but running the original command again, I still get this error.

````
pi@raspberrypi:~/Pictures $ pageres google.com
Error: Failed to launch the browser process!
/usr/local/lib/node_modules/pageres-cli/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome: 1: /usr/local/lib/node_modules/pageres-cli/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome: Syntax error: "(" unexpected


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/usr/local/lib/node_modules/pageres-cli/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at Interface.<anonymous> (/usr/local/lib/node_modules/pageres-cli/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)
    at Interface.emit (node:events:391:22)
    at Interface.close (node:readline:451:8)
    at Socket.onend (node:readline:224:10)
    at Socket.emit (node:events:391:22)
    at endReadableNT (node:internal/streams/readable:1307:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)

**Comment by andretunes** [comment]
Can you try installing the Chromium Browser?
`sudo apt-get install chromium-browser`

**Comment by nodecentral** [comment]
Hi, thanks again

I tried that too, ( see below) 

````
pi@raspberrypi:~ $ sudo apt-get install chromium-browserReading package lists... Done
Building dependency tree       
Reading state information... Done
chromium-browser is already the newest version (72.0.3626.121-0+rpt4).
0 upgraded, 0 newly installed, 0 to remove and 112 not upgraded.
pi@raspberrypi:~ 
````
but sadly still the same error..
````
pi@raspberrypi:~ $ pageres www.google.com
Error: Failed to launch the browser process!
/usr/local/lib/node_modules/pageres-cli/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome: 1: /usr/local/lib/node_modules/pageres-cli/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome: Syntax error: "(" unexpected


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/usr/local/lib/node_modules/pageres-cli/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at Interface.<anonymous> (/usr/local/lib/node_modules/pageres-cli/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)
    at Interface.emit (node:events:391:22)
    at Interface.close (node:readline:451:8)
    at Socket.onend (node:readline:224:10)
    at Socket.emit (node:events:391:22)
    at endReadableNT (node:internal/streams/readable:1307:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
pi@raspberrypi:~ $

**Comment by andretunes** [comment]
Well... Can you try go to the file `/usr/local/lib/node_modules/pageres-cli/node_modules/pageres/cli.js` edit the line and do this:
1. Where is `incrementalName: !options.overwrite`, put:
```js
incrementalName: !options.overwrite,
executablePath: '/usr/bin/chromium-browser',
args: ['--no-sandbox', '--disable-setuid-sandbox']
```

And try again.

**Comment by nodecentral** [comment]
Hi

I don’t seem to have that file in that location, see below..

````
pi@raspberrypi:/usr/local/lib/node_modules/pageres-cli/node_modules/pageres $ ls
dist  license  package.json  readme.md

````
In ‘dist’ I have the following..
````
pi@raspberrypi:/usr/local/lib/node_modules/pageres-cli/node_modules/pageres $ cd dist

pi@raspberrypi:/usr/local/lib/node_modules/pageres-cli/node_modules/pageres/dist $ ls
index.d.ts  index.js

pi@raspberrypi:/usr/local/lib/node_modules/pageres-cli/node_modules/pageres/dist $

**Comment by andretunes** [comment]
I'm sorry my fault, the file is: `/usr/local/lib/node_modules/pageres-cli/cli.js`

**Comment by nodecentral** [comment]
Thanks

Just to be sure, it’s this section to change.

````
async function generate(args, options) {
��������const pageres = new Pageres({
����������������incrementalName: !options.overwrite
��������}).dest(process.cwd());

**Comment by andretunes** [comment]
Yes!

**Comment by nodecentral** [comment]
Thanks - still an error but a different one this time ..

````
pi@raspberrypi:~/Pictures $ pageres google.com
/usr/local/lib/node_modules/pageres-cli/cli.js:72
                executablePath: '/usr/bin/chromium-browser',
                ^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at wrapSafe (node:internal/modules/cjs/loader:1024:16)
    at Module._compile (node:internal/modules/cjs/loader:1072:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47

**Comment by andretunes** [comment]
Do you have Discord or any other way to talk better?

**Comment by nodecentral** [comment]
The full section, that was updated is below, if it helps?

````
async function generate(args, options) {
��������const pageres = new Pageres({
��������������� incrementalName: !options.overwrite
��������������� executablePath: '/usr/bin/chromium-browser',
��������������� args: ['--no-sandbox', '--disable-setuid-sandbox']
��������}).dest(process.cwd());

��������for (const argument of args) {
��������������� pageres.src(argument.url, argument.sizes, argument.options);
��������}

��������await pageres.run();
��������pageres.successMessage();
}
````

I’ve had a look and ‘/usr/bin/chromium-browser’ seems to be there..

````
pi@raspberrypi:/ $ sudo find -name chromium*
./etc/chromium-browser
./usr/bin/chromium-browser
./usr/lib/chromium-browser
./usr/lib/chromium-browser/chromium-browser
./usr/lib/chromium-browser/chromium-browser-v7
./usr/share/chromium-browser
./usr/share/man/man1/chromium-browser.1.gz
./usr/share/gnome-control-center/default-apps/chromium-browser.xml
./usr/share/lintian/overrides/chromium-codecs-ffmpeg-extra
./usr/share/lintian/overrides/chromium-browser
./usr/share/pixmaps/chromium-browser.png
./usr/share/icons/hicolor/22x22/apps/chromium-browser.png
./usr/share/icons/hicolor/128x128/apps/chromium-browser.png
./usr/share/icons/hicolor/48x48/apps/chromium-browser.png
./usr/share/icons/hicolor/256x256/apps/chromium-browser.png
./usr/share/icons/hicolor/24x24/apps/chromium-browser.png
./usr/share/icons/hicolor/64x64/apps/chromium-browser.png
./usr/share/doc/chromium-browser-l10n
./usr/share/doc/chromium-codecs-ffmpeg-extra
./usr/share/doc/chromium-browser
./usr/share/applications/chromium-browser.desktop
./usr/share/apport/package-hooks/chromium-browser.py
./usr/local/lib/node_modules/pageres-cli/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/resources/inspector/third_party/chromium
./usr/local/lib/node_modules/pageres-cli/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/resources/inspector/third_party/chromium/chromium-tsconfig.json
./var/lib/dpkg/info/chromium-browser.prerm
./var/lib/dpkg/info/chromium-browser.postinst
./var/lib/dpkg/info/chromium-browser.md5sums
./var/lib/dpkg/info/chromium-browser.list
./var/lib/dpkg/info/chromium-codecs-ffmpeg-extra.list
./var/lib/dpkg/info/chromium-browser-l10n.md5sums
./var/lib/dpkg/info/chromium-codecs-ffmpeg-extra.md5sums
./var/lib/dpkg/info/chromium-browser-l10n.list
./var/lib/dpkg/info/chromium-browser.conffiles

**Comment by andretunes** [comment]
You forgot the comma and I missed one thingh., please use the code below:
```js
async function generate(args, options) {
	const pageres = new Pageres({
		incrementalName: !options.overwrite,
		launchOptions: {
			executablePath: '/usr/bin/chromium-browser',
			args: ['--no-sandbox', '--disable-setuid-sandbox']
		}
	}).dest(process.cwd());

	for (const argument of args) {
		pageres.src(argument.url, argument.sizes, argument.options);
	}

	await pageres.run();
	pageres.successMessage();
}
```

**Comment by nodecentral** [comment]
Many thanks, but sadly another error..

````
pi@raspberrypi:/ $ pageres www.google.com
Error: Protocol error (Emulation.setEmulatedMedia): Invalid parameters media: string value expected
    at /usr/local/lib/node_modules/pageres-cli/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:208:63
    at new Promise (<anonymous>)
    at CDPSession.send (/usr/local/lib/node_modules/pageres-cli/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:207:16)
    at Page.emulateMediaFeatures (/usr/local/lib/node_modules/pageres-cli/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:873:32)
    at captureWebsite (/usr/local/lib/node_modules/pageres-cli/node_modules/capture-website/index.js:228:13)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async Pageres.create (/usr/local/lib/node_modules/pageres-cli/node_modules/pageres/dist/index.js:176:28)
    at async /usr/local/lib/node_modules/pageres-cli/node_modules/pageres/dist/index.js:84:33
    at async Promise.all (index 0)
    at async Pageres.run (/usr/local/lib/node_modules/pageres-cli/node_modules/pageres/dist/index.js:70:9)

**Comment by andretunes** [comment]
Hello!

As I seen in the documentation of `pageres-cli` module, can you try having scheme? Like: `https://www.google.com`

**Comment by nodecentral** [comment]
Sorry I should have said, I tired a few and got the same message..

````
pi@raspberrypi:/ $ pageres http://google.com 1366x768
Error: Protocol error (Emulation.setEmulatedMedia): Invalid parameters media: string value expected
    at /usr/local/lib/node_modules/pageres-cli/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:208:63
    at new Promise (<anonymous>)
    at CDPSession.send (/usr/local/lib/node_modules/pageres-cli/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:207:16)
    at Page.emulateMediaFeatures (/usr/local/lib/node_modules/pageres-cli/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:873:32)
    at captureWebsite (/usr/local/lib/node_modules/pageres-cli/node_modules/capture-website/index.js:228:13)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async Pageres.create (/usr/local/lib/node_modules/pageres-cli/node_modules/pageres/dist/index.js:176:28)
    at async /usr/local/lib/node_modules/pageres-cli/node_modules/pageres/dist/index.js:84:33
    at async Promise.all (index 0)
    at async Pageres.run (/usr/local/lib/node_modules/pageres-cli/node_modules/pageres/dist/index.js:70:9)
pi@raspberrypi:/ $ pageres https://www.google.com
Error: Protocol error (Emulation.setEmulatedMedia): Invalid parameters media: string value expected
    at /usr/local/lib/node_modules/pageres-cli/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:208:63
    at new Promise (<anonymous>)
    at CDPSession.send (/usr/local/lib/node_modules/pageres-cli/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:207:16)
    at Page.emulateMediaFeatures (/usr/local/lib/node_modules/pageres-cli/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:873:32)
    at captureWebsite (/usr/local/lib/node_modules/pageres-cli/node_modules/capture-website/index.js:228:13)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async Pageres.create (/usr/local/lib/node_modules/pageres-cli/node_modules/pageres/dist/index.js:176:28)
    at async /usr/local/lib/node_modules/pageres-cli/node_modules/pageres/dist/index.js:84:33
    at async Promise.all (index 0)
    at async Pageres.run (/usr/local/lib/node_modules/pageres-cli/node_modules/pageres/dist/index.js:70:9)
pi@raspberrypi:/ $

**Comment by andretunes** [comment]
Go to the file: `/usr/local/lib/node_modules/pageres-cli/node_modules/capture-website/index.js`, on line 230 change this:
```js
value: options.darkMode ? 'dark' : 'light'
```

To this for example if you wanna light theme:
```js
value: 'light'
```

**Comment by nodecentral** [comment]
Thanks so much for your help/attention, changes were made to the following as requested, but sadly still the same error.

````
await page.emulateMediaFeatures([{
��������������� name: 'prefers-color-scheme',
����������������value: options.darkMode ? 'dark' : 'light'
��������}]);
````
Now this...
````
await page.emulateMediaFeatures([{
name: 'prefers-color-scheme',
value: 'light'
}]);
````
Trying the command again, I get the error.
````
pi@raspberrypi:/ $ pageres https://www.google.com

Error: Protocol error (Emulation.setEmulatedMedia): Invalid parameters media: string value expected
    at /usr/local/lib/node_modules/pageres-cli/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:208:63
    at new Promise (<anonymous>)
    at CDPSession.send (/usr/local/lib/node_modules/pageres-cli/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:207:16)
    at Page.emulateMediaFeatures (/usr/local/lib/node_modules/pageres-cli/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:873:32)
    at captureWebsite (/usr/local/lib/node_modules/pageres-cli/node_modules/capture-website/index.js:228:13)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async Pageres.create (/usr/local/lib/node_modules/pageres-cli/node_modules/pageres/dist/index.js:176:28)
    at async /usr/local/lib/node_modules/pageres-cli/node_modules/pageres/dist/index.js:84:33
    at async Promise.all (index 0)
    at async Pageres.run (/usr/local/lib/node_modules/pageres-cli/node_modules/pageres/dist/index.js:70:9)
pi@raspberrypi:/ $

**Comment by andretunes** [comment]
I'm sorry but I don't know what to do more, please open a Issue in the `pageres` module.

Kind regards

**Comment by nodecentral** [comment]
No problem, and thanks so much for your help.

Do I need to reverse any of the changes we’ve made - or are they all good to stay now  ?

**Comment by andretunes** [comment]
It's okay to stay that.

**Comment by nodecentral** [comment]
Hi, 

I’m back again, i’ve been sent me back to you - https://github.com/sindresorhus/pageres/issues/407 :-(

**Comment by joshike-code** [comment]
I'm having similar issue running puppeteer on cpanel. Works fine locally on windows but not on cpanel

**Comment by jamshedgopang55** [comment]
> I'm having similar issue running puppeteer on cpanel. Works fine locally on windows but not on cpanel

The error that you have encountered seems to be resolved on my local Windows environment, but it persists on the cPanel server. If you have successfully resolved this issue, kindly share the steps you took to rectify it. I am facing the same problem on cPanel, and your assistance in resolving it would be greatly appreciated. Thank you.
