### ISSUE TITLE
page.goto freeze with net::ERR_INVALID_AUTH_CREDENTIALS

### ISSUE THREAD

**Issue by kvrvgixzis** [puppeteer/puppeteer#6785]
## Problem
Im connecting to [multilogin](https://docs.multilogin.com/l/ru) browser and going to same page.
code freezing on `await page.goto()` although the page is open

## code example:
```javascript
const run = async (ws) => {
  try {
    const browser = await puppeteer.connect({
      browserWSEndpoint: ws,
      defaultViewport: null,
      ignoreHTTPSErrors: true,
    });

    const url = 'https://www.tiktok.com/upload/?lang=ru-RU';
    const [page] = await browser.pages();

    await page.goto(url);
    console.log('page loaded');
    await browser.close()
  } catch (err) {
    console.log('err: ', err);
  }
};
```

## answer
```
Browser ws endpoint: ws://127.0.0.1:26508/devtools/browser/a35bef71-0b13-43c7-b45f-c329fd6ee894
err:  Error: net::ERR_INVALID_AUTH_CREDENTIALS at https://www.tiktok.com/upload/?lang=ru-RU
    at navigate (/home/nkt/git/tik-tok-videos-uploading/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:115:23)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async FrameManager.navigateFrame (/home/nkt/git/tik-tok-videos-uploading/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:90:21)
    at async Frame.goto (/home/nkt/git/tik-tok-videos-uploading/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:417:16)
    at async Page.goto (/home/nkt/git/tik-tok-videos-uploading/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:825:16)
    at async run (/home/nkt/git/tik-tok-videos-uploading/src/index.js:52:5)

```

**Comment by tyurin-ilya** [comment]
multilogin ws does not support HTTP proxy. Use SOCKS

**Comment by KnightSlayer** [comment]
@kvrvgixzis hi! did you find any solution or explanation? I face same issue

**Comment by kvrvgixzis** [comment]
> @kvrvgixzis hi! did you find any solution or explanation? I face same issue

hi!

multilogin support answer:

Проблема с аутентификацией прокси происходит при использовании https прокси и puppeteer. Разработчики уже работают над решением проблемы. На данный момент быстрым решением было бы использование socks5, либо аутентификация через Puppeteer, используя следующий код:

```js
const browser =await puppeteer.connect({browserWSEndpoint: ws, defaultViewport:null});
const page = await browser.newPage();
await page.authenticate({'username':'PROXY_USERNAME','password':'PROXY_PASSWORD'});
await page.goto('https://google.com/');
```

it worked for me.

you can watch public repo in my profile
