### ISSUE TITLE
Adding ' in selectors with attributes filtering seems to break everything.

### ISSUE THREAD

**Issue by oom-** [puppeteer/puppeteer#6789]
### Steps to reproduce
1. Create a selector looking like this: `form div input[placeholder="Nom d'utilisateur"]`
2. Try to `page.waitForSelector` or `page.click` with this selector

**Tell us about your environment:**

* Puppeteer version: ^5.5.0
* Platform / OS version: w10 64bit 
* URLs (if applicable): /
* Node.js version: v12.16.1

**What steps will reproduce the problem?**

```js
page.waitForSelector(`form div input[placeholder="Nom d'utilisateur"]`);
```

**What is the expected result?**
Nothing special, just that it get the selector well.

**What happens instead?**
```
(node:11268) UnhandledPromiseRejectionWarning: Error: Protocol error (Target.attachToTarget): No target with given id found
    at f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:71:63
    at new Promise (<anonymous>)
    at Connection.send (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:70:16)
    at Connection.createSession (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:141:42)
    at Target._sessionFactory (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Browser.js:157:91)
    at Target.worker (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Target.js:85:40)
    at Plugin._onTargetCreated (f:\Documents\Projects\bot\node_modules\puppeteer-extra-plugin\dist\index.cjs.js:498:41)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
 <node_internals>/internal/process/warning.js
(node:11268) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
 <node_internals>/internal/process/warning.js
(node:11268) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 <node_internals>/internal/process/warning.js
(node:11268) UnhandledPromiseRejectionWarning: Error: Protocol error (Target.attachToTarget): No target with given id found
    at f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:71:63
    at new Promise (<anonymous>)
    at Connection.send (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:70:16)
    at Connection.createSession (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:141:42)
    at Target._sessionFactory (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Browser.js:157:91)
    at Target.worker (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Target.js:85:40)
    at Plugin._onTargetCreated (f:\Documents\Projects\bot\node_modules\puppeteer-extra-plugin\dist\index.cjs.js:498:41)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
 <node_internals>/internal/process/warning.js
(node:11268) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
 <node_internals>/internal/process/warning.js
(node:11268) UnhandledPromiseRejectionWarning: Error: Protocol error (Target.attachToTarget): No target with given id found
    at f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:71:63
    at new Promise (<anonymous>)
    at Connection.send (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:70:16)
    at Connection.createSession (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:141:42)
    at Target._sessionFactory (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Browser.js:157:91)
    at Target.worker (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Target.js:85:40)
    at Plugin._onTargetCreated (f:\Documents\Projects\bot\node_modules\puppeteer-extra-plugin\dist\index.cjs.js:498:41)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
 <node_internals>/internal/process/warning.js
(node:11268) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
 <node_internals>/internal/process/warning.js
(node:11268) UnhandledPromiseRejectionWarning: Error: Protocol error (Target.attachToTarget): No target with given id found
    at f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:71:63
    at new Promise (<anonymous>)
    at Connection.send (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:70:16)
    at Connection.createSession (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:141:42)
    at Target._sessionFactory (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Browser.js:157:91)
    at Target.worker (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Target.js:85:40)
    at Plugin._onTargetCreated (f:\Documents\Projects\bot\node_modules\puppeteer-extra-plugin\dist\index.cjs.js:498:41)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
 <node_internals>/internal/process/warning.js
(node:11268) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
 <node_internals>/internal/process/warning.js
(node:11268) UnhandledPromiseRejectionWarning: Error: Protocol error (Target.attachToTarget): No target with given id found
    at f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:71:63
    at new Promise (<anonymous>)
    at Connection.send (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:70:16)
    at Connection.createSession (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:141:42)
    at Target._sessionFactory (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Browser.js:157:91)
    at Target.worker (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Target.js:85:40)
    at Plugin._onTargetCreated (f:\Documents\Projects\bot\node_modules\puppeteer-extra-plugin\dist\index.cjs.js:498:41)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
 <node_internals>/internal/process/warning.js
(node:11268) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
 <node_internals>/internal/process/warning.js
(node:11268) UnhandledPromiseRejectionWarning: Error: Protocol error (Target.attachToTarget): No target with given id found
    at f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:71:63
    at new Promise (<anonymous>)
    at Connection.send (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:70:16)
    at Connection.createSession (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:141:42)
    at Target._sessionFactory (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Browser.js:157:91)
    at Target.worker (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Target.js:85:40)
    at Plugin._onTargetCreated (f:\Documents\Projects\bot\node_modules\puppeteer-extra-plugin\dist\index.cjs.js:498:41)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
 <node_internals>/internal/process/warning.js
(node:11268) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
 <node_internals>/internal/process/warning.js
(node:11268) UnhandledPromiseRejectionWarning: Error: Protocol error (Target.attachToTarget): No target with given id found
    at f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:71:63
    at new Promise (<anonymous>)
    at Connection.send (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:70:16)
    at Connection.createSession (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:141:42)
    at Target._sessionFactory (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Browser.js:157:91)
    at Target.worker (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Target.js:85:40)
    at Plugin._onTargetCreated (f:\Documents\Projects\bot\node_modules\puppeteer-extra-plugin\dist\index.cjs.js:498:41)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
 <node_internals>/internal/process/warning.js
(node:11268) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
 <node_internals>/internal/process/warning.js
(node:11268) UnhandledPromiseRejectionWarning: Error: Protocol error (Target.attachToTarget): No target with given id found
    at f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:71:63
    at new Promise (<anonymous>)
    at Connection.send (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:70:16)
    at Connection.createSession (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:141:42)
    at Target._sessionFactory (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Browser.js:157:91)
    at Target.worker (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Target.js:85:40)
    at Plugin._onTargetCreated (f:\Documents\Projects\bot\node_modules\puppeteer-extra-plugin\dist\index.cjs.js:498:41)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
 <node_internals>/internal/process/warning.js
(node:11268) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
 <node_internals>/internal/process/warning.js
(node:11268) UnhandledPromiseRejectionWarning: Error: Protocol error (Target.attachToTarget): No target with given id found
    at f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:71:63
    at new Promise (<anonymous>)
    at Connection.send (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:70:16)
    at Connection.createSession (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:141:42)
    at Target._sessionFactory (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Browser.js:157:91)
    at Target.worker (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Target.js:85:40)
    at Plugin._onTargetCreated (f:\Documents\Projects\bot\node_modules\puppeteer-extra-plugin\dist\index.cjs.js:498:41)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
 <node_internals>/internal/process/warning.js
(node:11268) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)
 <node_internals>/internal/process/warning.js
(node:11268) UnhandledPromiseRejectionWarning: Error: Protocol error (Target.attachToTarget): No target with given id found
    at f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:71:63
    at new Promise (<anonymous>)
    at Connection.send (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:70:16)
    at Connection.createSession (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:141:42)
    at Target._sessionFactory (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Browser.js:157:91)
    at Target.worker (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Target.js:85:40)
    at Plugin._onTargetCreated (f:\Documents\Projects\bot\node_modules\puppeteer-extra-plugin\dist\index.cjs.js:498:41)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
 <node_internals>/internal/process/warning.js
(node:11268) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 10)
 <node_internals>/internal/process/warning.js
(node:11268) UnhandledPromiseRejectionWarning: Error: Protocol error (Target.attachToTarget): No target with given id found
    at f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:71:63
    at new Promise (<anonymous>)
    at Connection.send (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:70:16)
    at Connection.createSession (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:141:42)
    at Target._sessionFactory (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Browser.js:157:91)
    at Target.worker (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Target.js:85:40)
    at Plugin._onTargetCreated (f:\Documents\Projects\bot\node_modules\puppeteer-extra-plugin\dist\index.cjs.js:498:41)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
 <node_internals>/internal/process/warning.js
(node:11268) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 11)
 <node_internals>/internal/process/warning.js
(node:11268) UnhandledPromiseRejectionWarning: Error: Protocol error (Target.attachToTarget): No target with given id found
    at f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:71:63
    at new Promise (<anonymous>)
    at Connection.send (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:70:16)
    at Connection.createSession (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:141:42)
    at Target._sessionFactory (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Browser.js:157:91)
    at Target.worker (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Target.js:85:40)
    at Plugin._onTargetCreated (f:\Documents\Projects\bot\node_modules\puppeteer-extra-plugin\dist\index.cjs.js:498:41)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
 <node_internals>/internal/process/warning.js
(node:11268) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 12)
 <node_internals>/internal/process/warning.js
(node:11268) UnhandledPromiseRejectionWarning: Error: Protocol error (Target.attachToTarget): No target with given id found
    at f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:71:63
    at new Promise (<anonymous>)
    at Connection.send (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:70:16)
    at Connection.createSession (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:141:42)
    at Target._sessionFactory (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Browser.js:157:91)
    at Target.worker (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Target.js:85:40)
    at Plugin._onTargetCreated (f:\Documents\Projects\bot\node_modules\puppeteer-extra-plugin\dist\index.cjs.js:498:41)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
 <node_internals>/internal/process/warning.js
(node:11268) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 13)
 <node_internals>/internal/process/warning.js
(node:11268) UnhandledPromiseRejectionWarning: Error: Protocol error (Target.attachToTarget): No target with given id found
    at f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:71:63
    at new Promise (<anonymous>)
    at Connection.send (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:70:16)
    at Connection.createSession (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:141:42)
    at Target._sessionFactory (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Browser.js:157:91)
    at Target.worker (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Target.js:85:40)
    at Plugin._onTargetCreated (f:\Documents\Projects\bot\node_modules\puppeteer-extra-plugin\dist\index.cjs.js:498:41)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
 <node_internals>/internal/process/warning.js
(node:11268) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 14)
 <node_internals>/internal/process/warning.js
(node:11268) UnhandledPromiseRejectionWarning: Error: Protocol error (Target.attachToTarget): No target with given id found
    at f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:71:63
    at new Promise (<anonymous>)
    at Connection.send (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:70:16)
    at Connection.createSession (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:141:42)
    at Target._sessionFactory (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Browser.js:157:91)
    at Target.worker (f:\Documents\Projects\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Target.js:85:40)
    at Plugin._onTargetCreated (f:\Documents\Projects\bot\node_modules\puppeteer-extra-plugin\dist\index.cjs.js:498:41)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
 <node_internals>/internal/process/warning.js
(node:11268) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 15)
 <node_internals>/internal/process/warning.js
 ```

**Comment by oom-** [comment]
Ok in the end it wasn't linked with this "'" I mean not directly. The main cause was because I forgot a ";" after the line `puppeteer.use(StealthPlugin())`.
Javascript is sometimes acting really weird.

Excuse me for this issue, I just close it right now.
