### ISSUE TITLE
Location of downloaded chromium

### ISSUE THREAD

**Issue by sjfricke** [puppeteer/puppeteer#679]
Is there a way to show the file path of where it is downloading Chromium when running `npm i puppeteer` as I can't seem to ever find where it actually is downloading it

**Comment by ebidel** [comment]
The path will change based on the platform that you install puppeteer on. [install.js](https://github.com/GoogleChrome/puppeteer/blob/master/install.js) has methods for finding that path. Something like this should work:

```js
const Downloader = require('puppeteer/utils/ChromiumDownloader');
const {chromium_revision} = require('puppeteer/package.json').puppeteer;
const info = Downloader.revisionInfo(Downloader.currentPlatform(), chromium_revision);
console.log(info);
```

```info.executablePath``` will give you the binary's path. Useful when launching chrome: `puppeter.launch({executablePath: info.executablePath})`.

**Comment by CoreyCole** [comment]
Sorry to hijack this thread, but I've been looking all over for why my `ChromiumDownloader` module cannot be found.

I've added the lines to the top of my `karma.conf.js`
```javascript
const Downloader = require('puppeteer/utils/ChromiumDownloader');
const {chromium_revision} = require('puppeteer/package.json').puppeteer;
const info = Downloader.revisionInfo(Downloader.currentPlatform(), chromium_revision);
console.log(info);

process.env.CHROME_BIN = info.executablePath();
```

And I get error:
```
05 06 2018 18:02:17.510:ERROR [config]: Invalid config file!
  Error: Cannot find module 'puppeteer/utils/ChromiumDownloader'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/corey/Halloo/src/state/client/src/karma.conf.js:4:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.parseConfig (/Users/corey/Halloo/src/state/client/node_modules/karma/lib/config.js:363:22)
    at new Server (/Users/corey/Halloo/src/state/client/node_modules/karma/lib/server.js:56:20)
    at Observable.rxjs_1.Observable.obs [as _subscribe] (/node_modules/@angular-devkit/build-angular/src/karma/packages/angular_devkit/build_angular/src/karma/index.ts:92:29)
    at Observable.subscribe (/node_modules/rxjs/src/internal/Observable.ts:197:63)
```

Here is my devDependencies in package.json- I have puppeteer and karma-chrome-launcher
```json
"devDependencies": {
    "@angular-devkit/build-angular": "~0.6.5",
    "@angular/cli": "~6.0.7",
    "@angular/compiler-cli": "^6.0.3",
    "@angular/language-service": "^6.0.3",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "^2.2.0",
    "karma-coverage-istanbul-reporter": "~1.4.2",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-phantomjs-launcher": "^1.0.4",
    "protractor": "~5.3.0",
    "puppeteer": "^1.4.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "~2.7.2"
}
```

**Comment by KaKi87** [comment]
Hello, how can I do the same thing today ? The `utils` directory no longer exists. Thanks

**Comment by mathiasbynens** [comment]
@KaKi87 https://github.com/puppeteer/puppeteer/blob/master/src/BrowserFetcher.ts

**Comment by prvnsmpth** [comment]
@KaKi87 Puppeteer has an API for getting the path to the executable: https://github.com/GoogleChrome/puppeteer/blob/v1.1.1/docs/api.md#puppeteerexecutablepath

**Comment by humkins** [comment]
run in the directory where `node_modules` is located

```sh
node -e "console.log(require('puppeteer').executablePath())"
```

Example output on Linux:
```
/app/node_modules/puppeteer/.local-chromium/linux-686378/chrome-linux/chrome
```

**Comment by estatistics** [comment]
downloaded location in debian linux for chrome is `/home/user/.cache/puppeteer/chrome/linux-117.0.5938.92/chrome-linux64/` and it is not detected at all. I will recommend puppeeteer to tell the EXPECTED full dir in order to be able to rename it for that.
