### ISSUE TITLE
when installing puppeteer  it says catch a '{' ;

### ISSUE THREAD

**Issue by mapinxue** [puppeteer/puppeteer#6887]
there is the code on the centos .
```npm install puppeteer
> puppeteer@7.1.0 install /root/node/node_modules/puppeteer
> node install.js
(node:16825) UnhandledPromiseRejectionWarning: /root/node/node_modules/puppeteer/lib/cjs/puppeteer/node/install.js:139
                    catch {
                          ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)
    at Module._compile (module.js:624:28)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at download (/root/node/node_modules/puppeteer/install.js:35:7)
(node:16825) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16825) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
npm WARN ws@7.4.3 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.4.3 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
```

**Comment by vsemozhetbyt** [comment]
You may have an old Node.js version that does not support optional catch binding. Try to upgrade the Node.js and then install the puppeteer. 

See https://node.green/#ES2019-misc-optional-catch-binding

**Comment by mapinxue** [comment]
> You may have an old Node.js version that does not support optional catch binding. Try to upgrade the Node.js and then install the puppeteer.
> 
> See https://node.green/#ES2019-misc-optional-catch-binding

you are right!thank you.
