### ISSUE TITLE
Error: Unsupported platform: freebsd

### ISSUE THREAD

**Issue by yurivict** [puppeteer/puppeteer#7016]
I am getting this error while running build for ```concourse``` (https://github.com/concourse/concourse):
```
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/5] ⠐ elm
[-/5] ⠐ waiting...
[3/5] ⠐ elm-format
[4/5] ⠐ elmi-to-json
error /usr/ports/misc/concourse/work/concourse-7.1.0/node_modules/puppeteer: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /usr/ports/misc/concourse/work/concourse-7.1.0/node_modules/puppeteer
Output:
/usr/ports/misc/concourse/work/concourse-7.1.0/node_modules/puppeteer/lib/helper.js:279
    throw new Error(message);
    ^

Error: Unsupported platform: freebsd
    at assert (/usr/ports/misc/concourse/work/concourse-7.1.0/node_modules/puppeteer/lib/helper.js:279:11)
    at new BrowserFetcher (/usr/ports/misc/concourse/work/concourse-7.1.0/node_modules/puppeteer/lib/BrowserFetcher.js:96:7)
    at module.exports.createBrowserFetcher (/usr/ports/misc/concourse/work/concourse-7.1.0/node_modules/puppeteer/lib/Puppeteer.js:82:12)
    at Object.<anonymous> (/usr/ports/misc/concourse/work/concourse-7.1.0/node_modules/puppeteer/install.js:39:34)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
```

Browsers work in exactly the same way in FreeBSD as in Linux.

**Comment by raybellis** [comment]
setting `PUPPETEER_SKIP_DOWNLOAD` at least allows v23.5.1 of this module to `npm install` under FreeBSD.  Whether it subsequently works as expected is unknown.
