### ISSUE TITLE
Puppeteer Did Not Install All Necessary Components

### ISSUE THREAD

**Issue by PostAlmostAnything** [puppeteer/puppeteer#7033]
I am trying to setup a Puppeteer app on a CENTOS 7.9 server for the first time. The app works fine in IIS, so I know the app is not the problem. I installed Node.js the typical way using cPanel and then used npm i puppeteer to install the module. 

When I try to run the app Puppeteer will not run properly and instead I get a message like this in my server error log:

App 15726 output:     at Interface.helper_js_1.helper.addEventListener (/home/username/public_html/example.com/app/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)
App 15726 output:     at onClose (/home/username/public_html/example.com/app/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
App 15726 output: /home/username/public_html/example.com/app/node_modules/puppeteer/.local-chromium/linux-856583/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory

I have seen similar error in which people claim to have solved the problem by typing:

sudo apt-get install gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget

When I do that I get sudo: apt-get: command not found

Is there another way to install those missing components? It would be easier for me if I could use npm since I just used it and am not familiar with sudo.

**Comment by PostAlmostAnything** [comment]
I managed to install the components but it still will not run. My error log still says:
App 23654 output:     at Interface.helper_js_1.helper.addEventListener (/home/username/public_html/example.com/app/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)
App 23654 output:     at onClose (/home/username/public_html/example.com/app/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
