### ISSUE TITLE
Getting an error in Node js I can't figure out.....

### ISSUE THREAD

**Issue by cowboysdude** [puppeteer/puppeteer#7041]
Whoops! There was an uncaught exception...
node_modules\puppeteer\lib\cjs\puppeteer\node\Puppeteer.js:66
        const { projectRoot, preferredRevision, productName, ...commonSettings } = settings;

I'm running node v12.16.2 and Puppeteer 8.......

Any input would be highly appreciated :)

**Comment by chonbon** [comment]
I am getting the same error,
App threw an error during load
B:\Code\FortuneBot\node_modules\puppeteer\lib\cjs\puppeteer\node\Puppeteer.js:66
        const { projectRoot, preferredRevision, productName, ...commonSettings } = settings;
                                                                                              ^^^
SyntaxError: Unexpected token ...
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (B:\Code\FortuneBot\node_modules\puppeteer\lib\cjs\puppeteer\initialize-node.js:22:24)
    at Module._compile (module.js:556:32)

Running Node v12.19.0 and puppeteer 9.1.1
