### ISSUE TITLE
FileChooser.accept doesn't work on file dialogs not associated with an input element

### ISSUE THREAD

**Issue by tlecoz** [puppeteer/puppeteer#7234]
Here is my code 

[nodeJs]
```
const puppeteer = require('puppeteer');

class App {

    private static ROOT_PATH:string = "D:/WWW/test_puppeteer_file_access/"
    private static CLIENT_PATH:string = "http://127.0.0.1/edsa-LocalHost_D/test_puppeteer_file_access/src/index.html";
    private page:any;

    constructor(){
        this.init();
    }

    async init(){
        let browserConfig = {
            executablePath: 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe',
            headless:false,
            devtools:true,
            args:["--enable-blink-features=WebCodecs",
                  "--enable-experimental-web-platform-features",
                  "--file-handling-api",
                  "--enable-features=MediaFoundationAsyncH264Encoding"
                ]
        }
        
        let pageViewport = {
            width:800,
            height:450,
            deviceScaleFactor:1
        }

        const browser = await puppeteer.launch(browserConfig); 
        
        this.page = await browser.newPage();
        this.page.setViewport(pageViewport)
        await this.page.goto(App.CLIENT_PATH);


        let futureFileChooser = await this.page.waitForFileChooser();
        await this.page.click('#fileSelectionBtn') 
        let fileChooser = await futureFileChooser;

        console.log("fileChooser = ",fileChooser)
        await fileChooser.accept(['/myfile.mp4']); 
    }
}
new App();
```
[/nodeJs]

[WebPage]
```
<html>
    <body>
        <script>
            let btn = document.createElement("div");
            btn.id = "fileSelectionBtn"
            btn.style.width = btn.style.height = "100px";
            btn.style.backgroundColor = "#cccccc";
            document.body.appendChild(btn);

            async function saveFile() {
                const options = {
                    types: [{
                    description: 'video file',
                    accept: {'video/mp4': ['.mp4']},
                    }],
                };
                const newHandle = await window.showSaveFilePicker(options);
                console.log("fileHandle => ",newHandle);
            }
            btn.onclick = ()=>{ saveFile(); } 
        </script>
    </body>
</html>
```
[/WebPage]

I tryed different file paths : 

```
 await fileChooser.accept(['/myfile.mp4'])
 await fileChooser.accept(['./myfile.mp4'])
 await fileChooser.accept(['D:/WWW/test_puppeteer_file_access/myfile.mp4'])
 await fileChooser.accept(['D:\\WWW\\test_puppeteer_file_access\\myfile.mp4'])
 await fileChooser.accept(['http://127.0.0.1/edsa-LocalHost_D/test_puppeteer_file_access/myfile.mp4']);
 await fileChooser.accept(['http:\\\\127.0.0.1\\edsa-LocalHost_D\\test_puppeteer_file_access\\myfile.mp4']);
```

I also tryed another way to proceed (the one given here : https://pptr.dev/#?product=Puppeteer&version=v9.1.1&show=api-class-filechooser ) 

```
const [fileChooser] = await Promise.all([
      page.waitForFileChooser(),
      page.click('#btn'), // some button that triggers file selection
    ]);
  await fileChooser.accept(['/tmp/myfile.pdf']);
```

(the way I proceed in my code is described here : https://pub.dev/documentation/puppeteer/latest/puppeteer/FileChooser-class.html )

But it doesn't work in any case.... 
The fileChooser appears but never close, so no file is selected... 

Actually, the problem come from "waitForFileChooser" ; the promise never resolve

Please help, I want to open a file that doesn't exist yet (to save it) in a folder contained in my puppeteer project.
I do not know what to do...  

I'm using Windows 10 and Puppeteer v9.1.1

**Comment by tlecoz** [comment]
Please help !

**Comment by kaibadash** [comment]
I found this in [API document](https://github.com/puppeteer/puppeteer/blob/main/docs/api.md).

> File choosers let you react to the page requesting for file(s) to be loaded by the web app. (This file chooser does not cover the “Save file” dialog.)

FileChooser doesn't seem to support Native File System API...

**Comment by azarai** [comment]
@tlecoz did you find a workaround?

And to the maintainers: Are there any plans on supporting showSaveFilePicker with an auto-accept behavior like for regular downloads?

I generate audio files in a browser app and use the same code for cli exporter using puppeteer. Used "new Blob" before and it works up to certain file sizes but am now switching to the new native file access as that's a huge performance increase over "Blong-handling.

**Comment by justotherel** [comment]
We've encountered the [same issue](https://github.com/puppeteer/puppeteer/issues/8615) on puppeteer v13.3.2 after upgrading from 4.0.0. WaitForFileChooser() never resolves but file chooser opens up and is not torn down after the execution ended.

From what we observe, it seems that file chooser is not being intercepted, as it would not appear on the screen otherwise. It opens but not reported by the browser over CDP. What we've found searching through related issues suggests that this might be caused by some race condition, but I'm not certain on that.

**Comment by OrKoN** [comment]
I believe that should have been solved by crbug.com/1332511 Could someone re-try in the most recent version? Please re-open a new issue with all details if it still happens.

**Comment by kaibadash** [comment]
@OrKoN Thank you for your response. I tried again. But I got `TimeoutError: Waiting for FileChooser failed: 30000ms exceeded.` :( .

## Sample site

https://kaibadash.github.io/puppeteer_native_file_system_api_sample/

## Source code

puppetter script: 

https://github.com/kaibadash/puppeteer_native_file_system_api_sample

```bash
cd puppeteer
yarn
yarn start
```

## version

- puppeteer-core@^17.1.3
- puppeteer@^17.1.3
- Chromium: 106.0.5249.0（Developer Build)

**Comment by azarai** [comment]
Tried @kaibadash example with 17.1.3 and also 19.2.2 but I get a different error:

`ProtocolError: Protocol error (DOM.resolveNode): Either nodeId or backendNodeId must be specified.
    at /Users/azarai/Downloads/puppeteer_native_file_system_api_sample-main/puppeteer/node_modules/puppeteer-core/src/common/Connection.ts:400:16
    at new Promise (<anonymous>)
    at CDPSessionImpl.send (/Users/azarai/Downloads/puppeteer_native_file_system_api_sample-main/puppeteer/node_modules/puppeteer-core/src/common/Connection.ts:396:12)
    at IsolatedWorld.adoptBackendNode (/Users/azarai/Downloads/puppeteer_native_file_system_api_sample-main/puppeteer/node_modules/puppeteer-core/src/common/IsolatedWorld.ts:598:41)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async CDPPage._CDPPage_onFileChooser (/Users/azarai/Downloads/puppeteer_native_file_system_api_sample-main/puppeteer/node_modules/puppeteer-core/src/common/Page.ts:324:21)`

**Comment by Guilherme-j10** [comment]
Up

**Comment by ForbiddenEra** [comment]
> Tried @kaibadash example with 17.1.3 and also 19.2.2 but I get a different error:
> 
> `ProtocolError: Protocol error (DOM.resolveNode): Either nodeId or backendNodeId must be specified. at /Users/azarai/Downloads/puppeteer_native_file_system_api_sample-main/puppeteer/node_modules/puppeteer-core/src/common/Connection.ts:400:16 at new Promise (<anonymous>) at CDPSessionImpl.send (/Users/azarai/Downloads/puppeteer_native_file_system_api_sample-main/puppeteer/node_modules/puppeteer-core/src/common/Connection.ts:396:12) at IsolatedWorld.adoptBackendNode (/Users/azarai/Downloads/puppeteer_native_file_system_api_sample-main/puppeteer/node_modules/puppeteer-core/src/common/IsolatedWorld.ts:598:41) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async CDPPage._CDPPage_onFileChooser (/Users/azarai/Downloads/puppeteer_native_file_system_api_sample-main/puppeteer/node_modules/puppeteer-core/src/common/Page.ts:324:21)`

I'm seeing this on v21.3.8, tried in both 'new' headless and non-headless.

```
 Unhandled Rejection: ProtocolError: Protocol error (DOM.resolveNode): Either nodeId or backendNodeId must be specified.
    at <instance_members_initializer> (/ppt/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:42:14)
    at new Callback (/ppt/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:46:16)
    at CallbackRegistry.create (/ppt/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:86:26)
    at Connection._rawSend (/ppt/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:208:26)
    at CdpCDPSession.send (/ppt/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/CDPSession.js:61:33)
    at IsolatedWorld.adoptBackendNode (/ppt/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/IsolatedWorld.js:211:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async #onFileChooser (/ppt/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Page.js:331:60)
```

Is Puppeteer file chooser just completely broken, or what?

**Comment by ForbiddenEra** [comment]
Looking at the code at the top of the trace, I see a comment:

> // This is guaranteed to be an HTMLInputElement handle by the event.

What if the input element is hidden and a 'pretty' button triggers it, like, almost everything does these days?

I _was_ able to get a handle for the input element directly and tried to use `.uploadFile()` on it, seemingly worked although it the app didn't want to accept it.

(To clarify 'app', I'm trying to upload files to ChatGPT-4V since it's not available via API yet)

**Comment by murmeel** [comment]
_Electron has 2 processes: The main process and the renderer process._

_What went wrong was that Puppeteer was only able to communicate with the renderer process. Since the file dialog was_ _launched from Electron's API, which comes from the main process, Puppeteer was unable to detect nor interact with it, thus_ _the timeout._

_You have to launch the file dialog from the renderer process (i.e. using vanilla html) for Puppeteer to detect the File Choooser._

Taken from [this SO question's answer](https://stackoverflow.com/questions/76717354/puppeteers-waitforfilechooser-doesnt-detect-filechooser-launched-electron).

Not sure if this is relevant, but have had issues myself with waiting for the file chooser just timing out and looking for answers.
Haven't tested the SO question's answer yet though.

**Comment by ForbiddenEra** [comment]
> @ForbiddenEra please open a new issue with a reproducible example

Sorry, but can you explain what the purpose for doing that would be when it's the same issue and this one is still open? I don't see the logic in having multiple issue threads for the same issue and that's literally the exact opposite of the norm.

**Comment by OrKoN** [comment]
@ForbiddenEra because this issue is about a timeout with the reproduction described in https://github.com/puppeteer/puppeteer/issues/7234#issuecomment-1245601566   `Unhandled Rejection: ProtocolError: Protocol error (DOM.resolveNode): Either nodeId or backendNodeId must be specified.` looks like a different bug.

**Comment by ForbiddenEra** [comment]
> @ForbiddenEra because this issue is about a timeout with the reproduction described in [#7234 (comment)](https://github.com/puppeteer/puppeteer/issues/7234#issuecomment-1245601566) `Unhandled Rejection: ProtocolError: Protocol error (DOM.resolveNode): Either nodeId or backendNodeId must be specified.` looks like a different bug.

Perhaps some are getting different error messages, @azarai posted the same error as myself and wasn't asked to open a new thread, but the reproduction steps, actual result and expected result are no different.

**Comment by OrKoN** [comment]
@ForbiddenEra sometimes messages are missed or no time to respond. I think from your message it was not clear that you used the same reproducible example, that's why I asked for a fresh repro. And indeed on the latest versions the bug looks different, so filing a new issue would be the way to go. The browser sends a `Page.fileChooserOpened` event but it does not send which element the dialog is associated with.

**Comment by OrKoN** [comment]
Yeah, it looks like newer file/directory dialog APIs are not really supported by CDP. The FileChooser only really supports the input[type=file] cases.

**Comment by ForbiddenEra** [comment]
> @ForbiddenEra sometimes messages are missed or no time to respond. I think from your message it was not clear that you used the same reproducible example, that's why I asked for a fresh repro. And indeed on the latest versions the bug looks different, so filing a new issue would be the way to go. The browser sends a `Page.fileChooserOpened` event but it does not send which element the dialog is associated with.

To be fair, from a user perspective, performing the same action and having it not work seems like basically the same issue. I shouldn't have to know or care about any internals such as you mentioned in order to know how to classify bug reports. It's highly discouraged to open duplicate issues in projects, especially larger projects that have thousands of issues - thus I searched, found an issue that matched mine and added a reply instead of creating a new issue without searching, as many do and are scolded for it.

And, in fact, if anything, it _was_ my knowledge about Puppeteer/Chromium that made me consider that, while the error messages might not be identical, that the issue is likely one and the same and any variation is due to the constant flux between the two projects.

I do appreciate that it seems you're looking into it still, however. To be honest though, this issue affected a side project I was messing around with - wrapper for ChatGPT4v since it wasn't available via API yet - being that it was a side project AND no longer really applicable and I don't for see myself using that functionality anytime soon, I really can't justify the time to create a new issue, unfortunately.

If you want to with my information, feel free; hopefully my addition benefits the community in some way and hopefully those who need it will be able to use this feature sometime, though as you seem to have pointed out, it's blocked upstream anyhow.

Best of luck, cheers!

**Comment by pierreminiggio** [comment]
>`Unhandled Rejection: ProtocolError: Protocol error (DOM.resolveNode): Either nodeId or backendNodeId must be specified.` 

Is there any update on this ?
I'm getting the same error too in the latest version of Puppeteer while waiting for a file chooser.

**Comment by bleehome** [comment]
`
<div class="click_me_to_upload"><input type="file"/></div> //works fine
`

`
<div class="click_me_to_upload"></div> // failed
<input type="file"/>
`

`
  async #onFileChooser(
    event: Protocol.Page.FileChooserOpenedEvent
  ): Promise<void> {
    if (!this.#fileChooserDeferreds.size) {
      return;
    }

    const frame = this.#frameManager.frame(event.frameId);
    assert(frame, 'This should never happen.');

    // This is guaranteed to be an HTMLInputElement handle by the event.
    using handle = (await frame.worlds[MAIN_WORLD].adoptBackendNode(
      event.backendNodeId
    )) as ElementHandle<HTMLInputElement>;

    const fileChooser = new FileChooser(handle.move(), event);
    for (const promise of this.#fileChooserDeferreds) {
      promise.resolve(fileChooser);
    }
    this.#fileChooserDeferreds.clear();
  }

`

**Comment by finngladstone** [comment]
@ForbiddenEra did you ever manage to find a workaround for this? I believe my use case is the exact same (hitting GPT via the web ui) 

Kind regards
