### ISSUE TITLE
error while loading shared libraries: libnss3.so

### ISSUE THREAD

**Issue by strowk** [puppeteer/puppeteer#7316]
I am using this tool aws-azure-login and it runs puppeteer. Tool is installed with snap. Trying to run it gives this error: 

```
Error: Failed to launch the browser process!
/snap/aws-azure-login/6/node_modules/puppeteer/.local-chromium/linux-856583/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/snap/aws-azure-login/6/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at Interface.<anonymous> (/snap/aws-azure-login/6/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)
    at Interface.emit (events.js:327:22)
    at Interface.EventEmitter.emit (domain.js:467:12)
    at Interface.close (readline.js:424:8)
    at Socket.onend (readline.js:202:10)
    at Socket.emit (events.js:327:22)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

```

I installed all the tools listed in troubleshooting and specifically checked that I have libnss3:

```
sudo apt install libnss3                                             
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libnss3 is already the newest version (2:3.49.1-1ubuntu1.5).
```

What could be the problem here?

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 8.0.0
* Platform / OS version: Ubuntu 20.04
* Node.js version: v12.19.0

**What steps will reproduce the problem?**

1. install aws-azure-login from snap
2. configure and run it
3. it runs puppeteer and fails

**What is the expected result?**

Tool works.

**What happens instead?**

I see error from puppeteer about libnss3

**Comment by ChenYCL** [comment]
centos8.0 same

**Comment by thinkloading** [comment]
解决了吗？centos7的docker里面的环境，一样的报错

**Comment by Pqoh** [comment]
Any solution?

**Comment by jrandolf-google** [comment]
We no longer support Node 12, please try this again with the latest version of Puppeteer and Node 14+.
