### ISSUE TITLE
Puppeteer stopped working with latest Chrome (V 92.0.4512.0)

### ISSUE THREAD

**Issue by raptoria** [puppeteer/puppeteer#7332]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: V 92.0.4512.0
* Platform / OS version: Mac OS 10.15.7
* URLs (if applicable):
* Node.js version: v16.0.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Run the code below with headless set to true

code:
```
import 'expect-puppeteer';
import { Page } from 'puppeteer';

let page: Page;
describe('Chariot UI', () => {
	beforeAll(async () => {
		page = await browser.newPage();
		await page.goto('http://localhost:3000', {
			waitUntil: 'domcontentloaded'
		});
		await page.waitForNavigation({ waitUntil: 'networkidle0' });
		await page.click('a[href="/training-management"]');
	});

	it('should be titled "Chariot UI"', async () => {
		await expect(page.title()).resolves.toMatch('Chariot UI');
	});

	it('should contain create links, a search input, etc', async () => {
		const createButtons = await page.$x('//a[contains(., "Create")]');
		expect(createButtons.length).toBe(2);

		const searchInput = await page.$x(
			'//input[contains(@placeholder, "Filter By Name")]'
		);
		expect(searchInput.length).toBe(1);
	});
	//TODO: click on the create buttons, fill out forms and expect stuff to happen
	afterAll(async () => {
		await page.close();
	});
});

```

**What is the expected result?**
Puppeteer tests should pass when headless is set to true AND when headless is set to false. This was working before Chrome V.92 was released.

**What happens instead?**
Tests fail differently depending on whether headless is set to true or false.

with headless set to true:

```
lerna info Executing command in 1 package: "npm run test:automated"
@strive/chariot-web: > @strive/chariot-web@0.0.17 test:automated
@strive/chariot-web: > jest --config ../../jest.config.js --rootDir . --selectProjects automated
@strive/chariot-web: Running one project: automated
@strive/chariot-web: DevTools listening on ws://127.0.0.1:63217/devtools/browser/d72570ef-7fde-43ec-9dcb-d18bee8a4d2f
@strive/chariot-web: [0615/121518.574210:WARNING:address_sorter_posix.cc(388)] FromSockAddr failed on netmask
@strive/chariot-web: TimeoutError: waiting for target failed: timeout 30000ms exceeded
@strive/chariot-web:     at Object.waitWithTimeout (/Users/clacey/projects/chariot-ui/node_modules/puppeteer/lib/cjs/puppeteer/common/helper.js:224:26)
@strive/chariot-web:     at Browser.waitForTarget (/Users/clacey/projects/chariot-ui/node_modules/puppeteer/lib/cjs/puppeteer/common/Browser.js:296:45)
@strive/chariot-web:     at ChromeLauncher.launch (/Users/clacey/projects/chariot-ui/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:105:31)
@strive/chariot-web:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
@strive/chariot-web:     at async setup (/Users/clacey/projects/chariot-ui/node_modules/jest-environment-puppeteer/lib/global.js:26:15)
@strive/chariot-web:     at async /Users/clacey/projects/chariot-ui/node_modules/@jest/core/build/runGlobalHook.js:82:11
@strive/chariot-web:     at async waitForPromiseWithCleanup (/Users/clacey/projects/chariot-ui/node_modules/@jest/transform/build/ScriptTransformer.js:207:5)
@strive/chariot-web:     at async /Users/clacey/projects/chariot-ui/node_modules/@jest/core/build/runGlobalHook.js:72:9
@strive/chariot-web:     at async pEachSeries (/Users/clacey/projects/chariot-ui/node_modules/p-each-series/index.js:8:23)
@strive/chariot-web:     at async _default (/Users/clacey/projects/chariot-ui/node_modules/@jest/core/build/runGlobalHook.js:58:5)
```
when headless set to false:

```
@strive/chariot-web: FAIL automated src/modules/training/__automated__/training.test.ts (14.082 s)
@strive/chariot-web:   Chariot UI
@strive/chariot-web:     ✕ should be titled "Chariot UI" (504 ms)
@strive/chariot-web:     ✕ should contain create links, a search input, etc (2008 ms)
@strive/chariot-web:   ● Chariot UI › should be titled "Chariot UI"
@strive/chariot-web:     Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.
@strive/chariot-web:       at mapper (../../node_modules/jest-jasmine2/build/queueRunner.js:27:45)
@strive/chariot-web:   ● Chariot UI › should contain create links, a search input, etc
@strive/chariot-web:     Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.
@strive/chariot-web:       at mapper (../../node_modules/jest-jasmine2/build/queueRunner.js:27:45)
@strive/chariot-web:   ● Chariot UI › should contain create links, a search input, etc
@strive/chariot-web:     expect(received).toBe(expected) // Object.is equality
@strive/chariot-web:     Expected: 2
@strive/chariot-web:     Received: 0
@strive/chariot-web:       21 | 	it('should contain create links, a search input, etc', async () => {
@strive/chariot-web:       22 | 		const createButtons = await page.$x('//a[contains(., "Create")]');
@strive/chariot-web:     > 23 | 		expect(createButtons.length).toBe(2);
@strive/chariot-web:          | 		                             ^
@strive/chariot-web:       24 |
@strive/chariot-web:       25 | 		const searchInput = await page.$x(
@strive/chariot-web:       26 | 			'//input[contains(@placeholder, "Filter By Name")]'
@strive/chariot-web:       at Object.<anonymous> (src/modules/training/__automated__/training.test.ts:23:32)
@strive/chariot-web: Test Suites: 1 failed, 1 total
@strive/chariot-web: Tests:       2 failed, 2 total
@strive/chariot-web: Snapshots:   0 total
@strive/chariot-web: Time:        14.667 s
@strive/chariot-web: Ran all test suites.
```

**Comment by chaoticsparks** [comment]
Had the same issue with running chrome win64-1056772 running puppeteer from cmder under the admin on Windows
Cmder started not from admin rights worked without the issue above
