### ISSUE TITLE
"npm i puppeteer" is not working

### ISSUE THREAD

**Issue by stzahi** [puppeteer/puppeteer#7383]
Trying to add the package 
`npm i puppeteer`
get the following result:

> npm ERR! code 1
> npm ERR! path /home/sza/Desktop/Projects/puppeteer/node_modules/puppeteer
> npm ERR! command failed
> npm ERR! command sh -c node install.js
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/sza/.npm/_logs/2021-06-27T08_39_42_768Z-debug.log

content of log file:

> 0 verbose cli [
> 0 verbose cli   '/snap/node/4812/bin/node',
> 0 verbose cli   '/usr/local/bin/npm',
> 0 verbose cli   'install',
> 0 verbose cli   'puppeteer'
> 0 verbose cli ]
> 1 info using npm@7.5.2
> 2 info using node@v14.17.1
> 3 timing config:load:defaults Completed in 2ms
> 4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 2ms
> 5 timing config:load:builtin Completed in 2ms
> 6 timing config:load:cli Completed in 1ms
> 7 timing config:load:env Completed in 1ms
> 8 timing config:load:file:/home/sza/Desktop/Projects/puppeteer/.npmrc Completed in 0ms
> 9 timing config:load:project Completed in 0ms
> 10 timing config:load:file:/home/sza/.npmrc Completed in 0ms
> 11 timing config:load:user Completed in 0ms
> 12 timing config:load:file:/etc/npmrc Completed in 1ms
> 13 timing config:load:global Completed in 1ms
> 14 timing config:load:cafile Completed in 0ms
> 15 timing config:load:validate Completed in 0ms
> 16 timing config:load:setUserAgent Completed in 1ms
> 17 timing config:load:setEnvs Completed in 0ms
> 18 timing config:load Completed in 8ms
> 19 verbose npm-session 50a2e8f60b136674
> 20 timing npm:load Completed in 15ms
> 21 timing arborist:ctor Completed in 1ms
> 22 timing arborist:ctor Completed in 0ms
> 23 timing idealTree:init Completed in 10ms
> 24 timing idealTree:userRequests Completed in 2ms
> 25 silly idealTree buildDeps
> 26 silly fetch manifest puppeteer@*
> 27 http fetch GET 304 https://registry.npmjs.org/puppeteer 192ms (from cache)
> 28 silly placeDep ROOT puppeteer@10.0.0 OK for: ssr@1.0.0 want: *
> 29 silly fetch manifest debug@4.3.1
> 30 silly fetch manifest devtools-protocol@0.0.883894
> 31 silly fetch manifest extract-zip@2.0.1
> 32 silly fetch manifest https-proxy-agent@5.0.0
> 33 silly fetch manifest node-fetch@2.6.1
> 34 silly fetch manifest pkg-dir@4.2.0
> 35 silly fetch manifest progress@2.0.1
> 36 silly fetch manifest proxy-from-env@1.1.0
> 37 silly fetch manifest rimraf@3.0.2
> 38 silly fetch manifest tar-fs@2.0.0
> 39 silly fetch manifest unbzip2-stream@1.3.3
> 40 silly fetch manifest ws@7.4.6
> 41 http fetch GET 304 https://registry.npmjs.org/debug 91ms (from cache)
> 42 http fetch GET 304 https://registry.npmjs.org/extract-zip 176ms (from cache)
> 43 http fetch GET 304 https://registry.npmjs.org/proxy-from-env 171ms (from cache)
> 44 http fetch GET 304 https://registry.npmjs.org/https-proxy-agent 177ms (from cache)
> 45 http fetch GET 304 https://registry.npmjs.org/rimraf 171ms (from cache)
> 46 http fetch GET 304 https://registry.npmjs.org/node-fetch 177ms (from cache)
> 47 http fetch GET 304 https://registry.npmjs.org/devtools-protocol 182ms (from cache)
> 48 http fetch GET 304 https://registry.npmjs.org/pkg-dir 184ms (from cache)
> 49 http fetch GET 304 https://registry.npmjs.org/progress 183ms (from cache)
> 50 http fetch GET 304 https://registry.npmjs.org/unbzip2-stream 178ms (from cache)
> 51 http fetch GET 304 https://registry.npmjs.org/ws 179ms (from cache)
> 52 http fetch GET 304 https://registry.npmjs.org/tar-fs 239ms (from cache)
> 53 timing idealTree:#root Completed in 456ms
> 54 silly fetch manifest bufferutil@^4.0.1
> 55 http fetch GET 304 https://registry.npmjs.org/bufferutil 72ms (from cache)
> 56 silly fetch manifest utf-8-validate@^5.0.2
> 57 http fetch GET 304 https://registry.npmjs.org/utf-8-validate 84ms (from cache)
> 58 silly placeDep ROOT debug@4.3.1 OK for: puppeteer@10.0.0 want: 4.3.1
> 59 silly placeDep ROOT devtools-protocol@0.0.883894 OK for: puppeteer@10.0.0 want: 0.0.883894
> 60 silly placeDep ROOT extract-zip@2.0.1 OK for: puppeteer@10.0.0 want: 2.0.1
> 61 silly placeDep ROOT https-proxy-agent@5.0.0 OK for: puppeteer@10.0.0 want: 5.0.0
> 62 silly placeDep ROOT node-fetch@2.6.1 OK for: puppeteer@10.0.0 want: 2.6.1
> 63 silly placeDep ROOT pkg-dir@4.2.0 OK for: puppeteer@10.0.0 want: 4.2.0
> 64 silly placeDep ROOT progress@2.0.1 OK for: puppeteer@10.0.0 want: 2.0.1
> 65 silly placeDep ROOT proxy-from-env@1.1.0 OK for: puppeteer@10.0.0 want: 1.1.0
> 66 silly placeDep ROOT rimraf@3.0.2 OK for: puppeteer@10.0.0 want: 3.0.2
> 67 silly placeDep ROOT tar-fs@2.0.0 OK for: puppeteer@10.0.0 want: 2.0.0
> 68 silly placeDep ROOT unbzip2-stream@1.3.3 OK for: puppeteer@10.0.0 want: 1.3.3
> 69 silly placeDep ROOT ws@7.4.6 OK for: puppeteer@10.0.0 want: 7.4.6
> 70 silly fetch manifest ms@2.1.2
> 71 silly fetch manifest @types/yauzl@^2.9.1
> 72 silly fetch manifest get-stream@^5.1.0
> 73 silly fetch manifest yauzl@^2.10.0
> 74 silly fetch manifest agent-base@6
> 75 silly fetch manifest find-up@^4.0.0
> 76 silly fetch manifest glob@^7.1.3
> 77 silly fetch manifest chownr@^1.1.1
> 78 silly fetch manifest mkdirp@^0.5.1
> 79 silly fetch manifest pump@^3.0.0
> 80 silly fetch manifest tar-stream@^2.0.0
> 81 silly fetch manifest buffer@^5.2.1
> 82 silly fetch manifest through@^2.3.8
> 83 http fetch GET 304 https://registry.npmjs.org/yauzl 97ms (from cache)
> 84 http fetch GET 304 https://registry.npmjs.org/ms 117ms (from cache)
> 85 http fetch GET 304 https://registry.npmjs.org/mkdirp 112ms (from cache)
> 86 http fetch GET 304 https://registry.npmjs.org/pump 112ms (from cache)
> 87 http fetch GET 304 https://registry.npmjs.org/tar-stream 112ms (from cache)
> 88 http fetch GET 304 https://registry.npmjs.org/agent-base 120ms (from cache)
> 89 http fetch GET 304 https://registry.npmjs.org/get-stream 125ms (from cache)
> 90 http fetch GET 304 https://registry.npmjs.org/glob 123ms (from cache)
> 91 http fetch GET 304 https://registry.npmjs.org/@types%2fyauzl 129ms (from cache)
> 92 http fetch GET 304 https://registry.npmjs.org/buffer 119ms (from cache)
> 93 http fetch GET 304 https://registry.npmjs.org/find-up 127ms (from cache)
> 94 http fetch GET 304 https://registry.npmjs.org/chownr 126ms (from cache)
> 95 http fetch GET 304 https://registry.npmjs.org/through 122ms (from cache)
> 96 timing idealTree:node_modules/puppeteer Completed in 316ms
> 97 silly placeDep ROOT ms@2.1.2 OK for: debug@4.3.1 want: 2.1.2
> 98 timing idealTree:node_modules/debug Completed in 2ms
> 99 timing idealTree:node_modules/devtools-protocol Completed in 0ms
> 100 silly placeDep ROOT @types/yauzl@2.9.1 OK for: extract-zip@2.0.1 want: ^2.9.1
> 101 silly placeDep ROOT get-stream@5.2.0 OK for: extract-zip@2.0.1 want: ^5.1.0
> 102 silly placeDep ROOT yauzl@2.10.0 OK for: extract-zip@2.0.1 want: ^2.10.0
> 103 silly fetch manifest @types/node@*
> 104 silly fetch manifest fd-slicer@~1.1.0
> 105 silly fetch manifest buffer-crc32@~0.2.3
> 106 http fetch GET 304 https://registry.npmjs.org/buffer-crc32 63ms (from cache)
> 107 http fetch GET 304 https://registry.npmjs.org/fd-slicer 77ms (from cache)
> 108 http fetch GET 304 https://registry.npmjs.org/@types%2fnode 83ms (from cache)
> 109 timing idealTree:node_modules/extract-zip Completed in 91ms
> 110 silly placeDep ROOT @types/node@15.12.5 OK for: @types/yauzl@2.9.1 want: *
> 111 timing idealTree:node_modules/@types/yauzl Completed in 1ms
> 112 timing idealTree:node_modules/@types/node Completed in 0ms
> 113 silly placeDep ROOT pump@3.0.0 OK for: get-stream@5.2.0 want: ^3.0.0
> 114 silly fetch manifest end-of-stream@^1.1.0
> 115 silly fetch manifest once@^1.3.1
> 116 http fetch GET 304 https://registry.npmjs.org/end-of-stream 58ms (from cache)
> 117 http fetch GET 304 https://registry.npmjs.org/once 77ms (from cache)
> 118 timing idealTree:node_modules/get-stream Completed in 81ms
> 119 silly placeDep ROOT agent-base@6.0.2 OK for: https-proxy-agent@5.0.0 want: 6
> 120 timing idealTree:node_modules/https-proxy-agent Completed in 5ms
> 121 timing idealTree:node_modules/agent-base Completed in 0ms
> 122 timing idealTree:node_modules/ms Completed in 0ms
> 123 timing idealTree:node_modules/node-fetch Completed in 0ms
> 124 silly placeDep ROOT find-up@4.1.0 OK for: pkg-dir@4.2.0 want: ^4.0.0
> 125 silly fetch manifest locate-path@^5.0.0
> 126 silly fetch manifest path-exists@^4.0.0
> 127 http fetch GET 304 https://registry.npmjs.org/path-exists 70ms (from cache)
> 128 http fetch GET 304 https://registry.npmjs.org/locate-path 73ms (from cache)
> 129 timing idealTree:node_modules/pkg-dir Completed in 74ms
> 130 silly placeDep ROOT locate-path@5.0.0 OK for: find-up@4.1.0 want: ^5.0.0
> 131 silly placeDep ROOT path-exists@4.0.0 OK for: find-up@4.1.0 want: ^4.0.0
> 132 silly fetch manifest p-locate@^4.1.0
> 133 http fetch GET 304 https://registry.npmjs.org/p-locate 62ms (from cache)
> 134 timing idealTree:node_modules/find-up Completed in 63ms
> 135 silly placeDep ROOT p-locate@4.1.0 OK for: locate-path@5.0.0 want: ^4.1.0
> 136 silly fetch manifest p-limit@^2.2.0
> 137 http fetch GET 304 https://registry.npmjs.org/p-limit 73ms (from cache)
> 138 timing idealTree:node_modules/locate-path Completed in 77ms
> 139 silly placeDep ROOT p-limit@2.3.0 OK for: p-locate@4.1.0 want: ^2.2.0
> 140 silly fetch manifest p-try@^2.0.0
> 141 http fetch GET 304 https://registry.npmjs.org/p-try 60ms (from cache)
> 142 timing idealTree:node_modules/p-locate Completed in 63ms
> 143 silly placeDep ROOT p-try@2.2.0 OK for: p-limit@2.3.0 want: ^2.0.0
> 144 timing idealTree:node_modules/p-limit Completed in 1ms
> 145 timing idealTree:node_modules/p-try Completed in 0ms
> 146 timing idealTree:node_modules/path-exists Completed in 0ms
> 147 timing idealTree:node_modules/progress Completed in 0ms
> 148 timing idealTree:node_modules/proxy-from-env Completed in 0ms
> 149 silly placeDep ROOT end-of-stream@1.4.4 OK for: pump@3.0.0 want: ^1.1.0
> 150 silly placeDep ROOT once@1.4.0 OK for: pump@3.0.0 want: ^1.3.1
> 151 silly fetch manifest wrappy@1
> 152 http fetch GET 304 https://registry.npmjs.org/wrappy 50ms (from cache)
> 153 timing idealTree:node_modules/pump Completed in 56ms
> 154 timing idealTree:node_modules/end-of-stream Completed in 0ms
> 155 silly placeDep ROOT wrappy@1.0.2 OK for: once@1.4.0 want: 1
> 156 timing idealTree:node_modules/once Completed in 1ms
> 157 silly placeDep ROOT glob@7.1.7 OK for: rimraf@3.0.2 want: ^7.1.3
> 158 silly fetch manifest fs.realpath@^1.0.0
> 159 silly fetch manifest inflight@^1.0.4
> 160 silly fetch manifest inherits@2
> 161 silly fetch manifest minimatch@^3.0.4
> 162 silly fetch manifest path-is-absolute@^1.0.0
> 163 http fetch GET 304 https://registry.npmjs.org/inflight 91ms (from cache)
> 164 http fetch GET 304 https://registry.npmjs.org/minimatch 91ms (from cache)
> 165 http fetch GET 304 https://registry.npmjs.org/path-is-absolute 90ms (from cache)
> 166 http fetch GET 304 https://registry.npmjs.org/fs.realpath 99ms (from cache)
> 167 http fetch GET 304 https://registry.npmjs.org/inherits 97ms (from cache)
> 168 timing idealTree:node_modules/rimraf Completed in 102ms
> 169 silly placeDep ROOT fs.realpath@1.0.0 OK for: glob@7.1.7 want: ^1.0.0
> 170 silly placeDep ROOT inflight@1.0.6 OK for: glob@7.1.7 want: ^1.0.4
> 171 silly placeDep ROOT inherits@2.0.4 OK for: glob@7.1.7 want: 2
> 172 silly placeDep ROOT minimatch@3.0.4 OK for: glob@7.1.7 want: ^3.0.4
> 173 silly placeDep ROOT path-is-absolute@1.0.1 OK for: glob@7.1.7 want: ^1.0.0
> 174 silly fetch manifest brace-expansion@^1.1.7
> 175 http fetch GET 304 https://registry.npmjs.org/brace-expansion 59ms (from cache)
> 176 timing idealTree:node_modules/glob Completed in 64ms
> 177 timing idealTree:node_modules/fs.realpath Completed in 0ms
> 178 timing idealTree:node_modules/inflight Completed in 0ms
> 179 timing idealTree:node_modules/inherits Completed in 0ms
> 180 silly placeDep ROOT brace-expansion@1.1.11 OK for: minimatch@3.0.4 want: ^1.1.7
> 181 silly fetch manifest balanced-match@^1.0.0
> 182 silly fetch manifest concat-map@0.0.1
> 183 http fetch GET 304 https://registry.npmjs.org/concat-map 69ms (from cache)
> 184 http fetch GET 304 https://registry.npmjs.org/balanced-match 73ms (from cache)
> 185 timing idealTree:node_modules/minimatch Completed in 75ms
> 186 silly placeDep ROOT balanced-match@1.0.2 OK for: brace-expansion@1.1.11 want: ^1.0.0
> 187 silly placeDep ROOT concat-map@0.0.1 OK for: brace-expansion@1.1.11 want: 0.0.1
> 188 timing idealTree:node_modules/brace-expansion Completed in 1ms
> 189 timing idealTree:node_modules/balanced-match Completed in 0ms
> 190 timing idealTree:node_modules/concat-map Completed in 0ms
> 191 timing idealTree:node_modules/path-is-absolute Completed in 0ms
> 192 silly placeDep ROOT chownr@1.1.4 OK for: tar-fs@2.0.0 want: ^1.1.1
> 193 silly placeDep ROOT mkdirp@0.5.5 OK for: tar-fs@2.0.0 want: ^0.5.1
> 194 silly placeDep ROOT tar-stream@2.2.0 OK for: tar-fs@2.0.0 want: ^2.0.0
> 195 silly fetch manifest minimist@^1.2.5
> 196 silly fetch manifest bl@^4.0.3
> 197 silly fetch manifest fs-constants@^1.0.0
> 198 silly fetch manifest readable-stream@^3.1.1
> 199 http fetch GET 304 https://registry.npmjs.org/minimist 66ms (from cache)
> 200 http fetch GET 304 https://registry.npmjs.org/bl 68ms (from cache)
> 201 http fetch GET 304 https://registry.npmjs.org/readable-stream 70ms (from cache)
> 202 http fetch GET 304 https://registry.npmjs.org/fs-constants 71ms (from cache)
> 203 timing idealTree:node_modules/tar-fs Completed in 74ms
> 204 timing idealTree:node_modules/chownr Completed in 0ms
> 205 silly placeDep ROOT minimist@1.2.5 OK for: mkdirp@0.5.5 want: ^1.2.5
> 206 timing idealTree:node_modules/mkdirp Completed in 1ms
> 207 timing idealTree:node_modules/minimist Completed in 0ms
> 208 silly placeDep ROOT bl@4.1.0 OK for: tar-stream@2.2.0 want: ^4.0.3
> 209 silly placeDep ROOT fs-constants@1.0.0 OK for: tar-stream@2.2.0 want: ^1.0.0
> 210 silly placeDep ROOT readable-stream@3.6.0 OK for: tar-stream@2.2.0 want: ^3.1.1
> 211 silly fetch manifest buffer@^5.5.0
> 212 silly fetch manifest string_decoder@^1.1.1
> 213 silly fetch manifest util-deprecate@^1.0.1
> 214 http fetch GET 304 https://registry.npmjs.org/util-deprecate 87ms (from cache)
> 215 http fetch GET 304 https://registry.npmjs.org/string_decoder 92ms (from cache)
> 216 timing idealTree:node_modules/tar-stream Completed in 95ms
> 217 silly placeDep ROOT buffer@5.7.1 OK for: bl@4.1.0 want: ^5.5.0
> 218 silly fetch manifest base64-js@^1.3.1
> 219 silly fetch manifest ieee754@^1.1.13
> 220 http fetch GET 304 https://registry.npmjs.org/ieee754 64ms (from cache)
> 221 http fetch GET 304 https://registry.npmjs.org/base64-js 84ms (from cache)
> 222 timing idealTree:node_modules/bl Completed in 85ms
> 223 silly placeDep ROOT base64-js@1.5.1 OK for: buffer@5.7.1 want: ^1.3.1
> 224 silly placeDep ROOT ieee754@1.2.1 OK for: buffer@5.7.1 want: ^1.1.13
> 225 timing idealTree:node_modules/buffer Completed in 2ms
> 226 timing idealTree:node_modules/base64-js Completed in 0ms
> 227 timing idealTree:node_modules/fs-constants Completed in 0ms
> 228 timing idealTree:node_modules/ieee754 Completed in 0ms
> 229 silly placeDep ROOT string_decoder@1.3.0 OK for: readable-stream@3.6.0 want: ^1.1.1
> 230 silly placeDep ROOT util-deprecate@1.0.2 OK for: readable-stream@3.6.0 want: ^1.0.1
> 231 silly fetch manifest safe-buffer@~5.2.0
> 232 http fetch GET 304 https://registry.npmjs.org/safe-buffer 98ms (from cache)
> 233 timing idealTree:node_modules/readable-stream Completed in 99ms
> 234 silly placeDep ROOT safe-buffer@5.2.1 OK for: string_decoder@1.3.0 want: ~5.2.0
> 235 timing idealTree:node_modules/string_decoder Completed in 2ms
> 236 timing idealTree:node_modules/safe-buffer Completed in 0ms
> 237 silly placeDep ROOT through@2.3.8 OK for: unbzip2-stream@1.3.3 want: ^2.3.8
> 238 timing idealTree:node_modules/unbzip2-stream Completed in 1ms
> 239 timing idealTree:node_modules/through Completed in 0ms
> 240 timing idealTree:node_modules/util-deprecate Completed in 0ms
> 241 timing idealTree:node_modules/wrappy Completed in 1ms
> 242 timing idealTree:node_modules/ws Completed in 0ms
> 243 silly placeDep ROOT buffer-crc32@0.2.13 OK for: yauzl@2.10.0 want: ~0.2.3
> 244 silly placeDep ROOT fd-slicer@1.1.0 OK for: yauzl@2.10.0 want: ~1.1.0
> 245 silly fetch manifest pend@~1.2.0
> 246 http fetch GET 304 https://registry.npmjs.org/pend 60ms (from cache)
> 247 timing idealTree:node_modules/yauzl Completed in 65ms
> 248 timing idealTree:node_modules/buffer-crc32 Completed in 0ms
> 249 silly placeDep ROOT pend@1.2.0 OK for: fd-slicer@1.1.0 want: ~1.2.0
> 250 timing idealTree:node_modules/fd-slicer Completed in 2ms
> 251 timing idealTree:node_modules/pend Completed in 0ms
> 252 timing idealTree:buildDeps Completed in 1962ms
> 253 timing idealTree:fixDepFlags Completed in 2ms
> 254 timing idealTree Completed in 1978ms
> 255 timing reify:loadTrees Completed in 1979ms
> 256 timing reify:diffTrees Completed in 1ms
> 257 silly reify moves {}
> 258 timing reify:retireShallow Completed in 0ms
> 259 timing reify:createSparse Completed in 7ms
> 260 timing reify:loadBundles Completed in 0ms
> 261 timing reifyNode:node_modules/buffer-crc32 Completed in 191ms
> 262 timing reifyNode:node_modules/chownr Completed in 191ms
> 263 timing reifyNode:node_modules/path-is-absolute Completed in 190ms
> 264 timing reifyNode:node_modules/brace-expansion Completed in 191ms
> 265 timing reifyNode:node_modules/inflight Completed in 190ms
> 266 timing reifyNode:node_modules/wrappy Completed in 190ms
> 267 timing reifyNode:node_modules/once Completed in 191ms
> 268 timing reifyNode:node_modules/end-of-stream Completed in 191ms
> 269 timing reifyNode:node_modules/@types/yauzl Completed in 191ms
> 270 timing reifyNode:node_modules/ms Completed in 191ms
> 271 timing reifyNode:node_modules/pend Completed in 194ms
> 272 timing reifyNode:node_modules/ieee754 Completed in 193ms
> 273 timing reifyNode:node_modules/fs-constants Completed in 193ms
> 274 timing reifyNode:node_modules/inherits Completed in 193ms
> 275 timing reifyNode:node_modules/p-try Completed in 193ms
> 276 timing reifyNode:node_modules/p-limit Completed in 193ms
> 277 timing reifyNode:node_modules/locate-path Completed in 193ms
> 278 timing reifyNode:node_modules/p-locate Completed in 193ms
> 279 timing reifyNode:node_modules/pkg-dir Completed in 193ms
> 280 timing reifyNode:node_modules/path-exists Completed in 194ms
> 281 timing reifyNode:node_modules/find-up Completed in 194ms
> 282 timing reifyNode:node_modules/util-deprecate Completed in 195ms
> 283 timing reifyNode:node_modules/string_decoder Completed in 195ms
> 284 timing reifyNode:node_modules/base64-js Completed in 195ms
> 285 timing reifyNode:node_modules/balanced-match Completed in 195ms
> 286 timing reifyNode:node_modules/minimatch Completed in 194ms
> 287 timing reifyNode:node_modules/fs.realpath Completed in 194ms
> 288 timing reifyNode:node_modules/extract-zip Completed in 194ms
> 289 timing reifyNode:node_modules/mkdirp Completed in 196ms
> 290 timing reifyNode:node_modules/get-stream Completed in 196ms
> 291 timing reifyNode:node_modules/pump Completed in 196ms
> 292 timing reifyNode:node_modules/safe-buffer Completed in 198ms
> 293 timing reifyNode:node_modules/yauzl Completed in 197ms
> 294 timing reifyNode:node_modules/rimraf Completed in 196ms
> 295 timing reifyNode:node_modules/concat-map Completed in 199ms
> 296 timing reifyNode:node_modules/progress Completed in 197ms
> 297 timing reifyNode:node_modules/debug Completed in 197ms
> 298 timing reifyNode:node_modules/tar-stream Completed in 200ms
> 299 timing reifyNode:node_modules/proxy-from-env Completed in 198ms
> 300 timing reifyNode:node_modules/fd-slicer Completed in 201ms
> 301 timing reifyNode:node_modules/glob Completed in 200ms
> 302 timing reifyNode:node_modules/buffer Completed in 201ms
> 303 timing reifyNode:node_modules/through Completed in 202ms
> 304 timing reifyNode:node_modules/https-proxy-agent Completed in 201ms
> 305 timing reifyNode:node_modules/bl Completed in 203ms
> 306 timing reifyNode:node_modules/agent-base Completed in 202ms
> 307 timing reifyNode:node_modules/unbzip2-stream Completed in 202ms
> 308 timing reifyNode:node_modules/node-fetch Completed in 203ms
> 309 timing reifyNode:node_modules/minimist Completed in 206ms
> 310 timing reifyNode:node_modules/ws Completed in 205ms
> 311 timing reifyNode:node_modules/readable-stream Completed in 209ms
> 312 timing reifyNode:node_modules/tar-fs Completed in 211ms
> 313 timing reifyNode:node_modules/@types/node Completed in 222ms
> 314 timing reifyNode:node_modules/devtools-protocol Completed in 232ms
> 315 timing reifyNode:node_modules/puppeteer Completed in 274ms
> 316 timing reify:unpack Completed in 277ms
> 317 timing reify:unretire Completed in 1ms
> 318 timing build:queue Completed in 3ms
> 319 timing build:link:node_modules/extract-zip Completed in 3ms
> 320 timing build:link:node_modules/mkdirp Completed in 2ms
> 321 timing build:link:node_modules/rimraf Completed in 2ms
> 322 timing build:link Completed in 3ms
> 323 info run puppeteer@10.0.0 install node_modules/puppeteer node install.js
> 324 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 1052ms
> 325 timing auditReport:getReport Completed in 1054ms
> 326 timing metavuln:packument:puppeteer Completed in 1ms
> 327 timing metavuln:cache:get:security-advisory:puppeteer:WaoW7jlSokCk6tQo2mzkvuU1o0wv7FMBme7gyxNoXEuaaKn3tFlSNBqrUDpB6G7PwDbHrIv7Aj6PR3l4Yg0beQ== Completed in 6ms
> 328 timing metavuln:load:security-advisory:puppeteer:824 Completed in 15ms
> 329 timing metavuln:calculate:security-advisory:puppeteer:824 Completed in 21ms
> 330 timing auditReport:init Completed in 22ms
> 331 timing reify:audit Completed in 1077ms
> 332 info run puppeteer@10.0.0 install { code: 1, signal: null }
> 333 timing reify:rollback:createSparse Completed in 66ms
> 334 timing reify:rollback:retireShallow Completed in 0ms
> 335 timing command:install Completed in 36311ms
> 336 verbose stack Error: command failed
> 336 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
> 336 verbose stack     at ChildProcess.emit (events.js:375:28)
> 336 verbose stack     at maybeClose (internal/child_process.js:1055:16)
> 336 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
> 337 verbose pkgid puppeteer@10.0.0
> 338 verbose cwd /home/sza/Desktop/Projects/puppeteer
> 339 verbose Linux 5.8.0-59-generic
> 340 verbose argv "/snap/node/4812/bin/node" "/usr/local/bin/npm" "install" "puppeteer"
> 341 verbose node v14.17.1
> 342 verbose npm  v7.5.2
> 343 error code 1
> 344 error path /home/sza/Desktop/Projects/puppeteer/node_modules/puppeteer
> 345 error command failed
> 346 error command sh -c node install.js
> 347 verbose exit 1
> 
> 
>

**Comment by stzahi** [comment]
Seems like it was a local Nodejs problem on my machine.
