### ISSUE TITLE
request.respond() for big json-file fails with 'browser disconnected" error

### ISSUE THREAD

**Issue by halittiryaki** [puppeteer/puppeteer#7417]
when returning a response for an intercepted requested, which is bigger than 100mb, I get the following error:

`helper_js_1.helper.addEventListener(frameManager._client, Connection_js_1.CDPSessionEmittedEvents.Disconnected, () => this._terminate(new Error('Navigation failed because browser has disconnected!'))),`

all other respond() work fine. only if a given file is big, I am facing the issue. the `respond()` looks like:
`
return request.respond({
	status: 200,
	headers: {
		"content-length": fs.statSync(getFilePath(request.url())).size
	},
	contentType: getMime(request.url()),
	body: fs.readFileSync(getFilePath(request.url()), 'utf-8')
});
`

stacktrace:
`
Error: Navigation failed because browser has disconnected!
    at /usr/src/demo/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:51:147
    at /usr/src/demo/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:62
    at Array.map (<anonymous>)
    at Object.emit (/usr/src/demo/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:43)
    at CDPSession.emit (/usr/src/demo/node_modules/puppeteer/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
    at CDPSession._onClosed (/usr/src/demo/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:256:14)
    at Connection._onClose (/usr/src/demo/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:138:21)
    at WebSocket.<anonymous> (/usr/src/demo/node_modules/puppeteer/lib/cjs/puppeteer/node/NodeWebSocketTransport.js:17:30)
    at WebSocket.onClose (/usr/src/demo/node_modules/ws/lib/event-target.js:136:16)
`

already tried various options. currently:
`
const browser = await puppeteer.launch({headless: true, args:[
			"--disable-dev-shm-usage", "--shm-size=3gb", '--disable-features=IsolateOrigins,site-per-process', '--disable-web-security',"--no-sandbox","--disable-setuid-sandbox","--no-zygote",
			"--unlimited-storage",
			'--deterministic-fetch',
		]});
`

the process gets killed before any of those events for the big-file are triggered:
`
page.on('requestfailed', request => console.info(`Failed request: ${request.url()}`));
page.on('response', response => console.info(`Response: ${response.url()}`))
`

my env:

* Puppeteer version: 20
* Platform / OS version: ubuntu 20
* URLs (if applicable):
* Node.js version: v14.17.0

**Comment by halittiryaki** [comment]
ok, now I know the reason:
switched to pipe mode but still running to a limit:
`
[0710/225637.498642:ERROR:http_connection.cc(37)] Too large read data is pending: capacity=104857600, max_buffer_size=104857600, read=104857600
[0710/225637.498686:ERROR:devtools_pipe_handler.cc(282)] Connection closed, not enough capacity
`

any way to increase the cap?

**Comment by halittiryaki** [comment]
though the question how to increase connection cap is interesting, I ve implemented a dirty fix to progress. if someone else faces the same problem, I transfer the  big json file in chunks by js invokes:

`
let body = "{}"; 
if (request.url().endsWith("big.json")) { 
  await (new Promise((resolve, reject) => {
    fs.createReadStream(getFilePath(request.url()), { highWaterMark: 1 * 1024, encoding: 'utf8' })
	.on('data', async (chunk) => {
		await page.evaluate((data) => {
			appendJson(data);
		}, chunk);
	})
	.on('end', async () => {
		await page.evaluate(() => finJson());
		resolve();
	});
}));
} else {
	body = fs.readFileSync(getFilePath(request.url()), 'utf-8');
}

`
