### ISSUE TITLE
Issue with debugging puppeteer and stacktrace

### ISSUE THREAD

**Issue by extempl** [puppeteer/puppeteer#7429]
This is the common report about approach of composing and minifying puppeteer within npm package. 
The main issue is that you do not put TS sources within the npm package, but putting `.map` which does links to the `src/…ts` files which really breaks ability in debugging and understanding the logic, as stacktrace looks like this
```
    at new WaitTask (/Users/extempl/Projects/puppeteer/jest/node_modules/puppeteer/src/common/DOMWorld.ts:777:28)
    at DOMWorld.waitForXPath (/Users/extempl/Projects/puppeteer/jest/node_modules/puppeteer/src/common/DOMWorld.ts:674:22)
    at Frame.waitForXPath (/Users/extempl/Projects/puppeteer/jest/node_modules/puppeteer/src/common/FrameManager.ts:1193:47)
    at Page.waitForXPath (/Users/extempl/Projects/puppeteer/jest/node_modules/puppeteer/src/common/Page.ts:2116:29)
```
But there is no `src` directory, and only `lib` with compiled js files, so it is really a, hm, _hard_ to find the right position and debug the behavior - I have to go to sources on github with according version on search for alike place in the result js (which is really not that easy, as there are a bunch of copies for some reason, and not clear which one is used). Also the `go into the method` action breaks on the step where IDE does not know where to look, as it looks for `src…ts` file.
Possible solutions: 
- Remove `map` file, so IDEs will show (clickable) position in js files
- Add src files - usually this is fine, as any builders omitting src files and includes only imported files.

**Comment by extempl** [comment]
Two years already, and not a slightest attention to the issue.

**Comment by extempl** [comment]
Up.

**Comment by Lightning00Blade** [comment]
Closing as completed in #10415.
