### ISSUE TITLE
Ubuntu 20.04: UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!

### ISSUE THREAD

**Issue by devinyasas** [puppeteer/puppeteer#7479]
First of all I know this issue has been reported many times. I tried every possible solution and did not work for me
I ran this in Windows without an issue. But I recently switched to Linux and getting this error ,

```
 at onClose (/opt/lampp/htdocs/node-scrapers/node_modules/puppeteer-core/lib/Launcher.js:750:14)
    at Interface.helper.addEventListener (/opt/lampp/htdocs/node-scrapers/node_modules/puppeteer-core/lib/Launcher.js:739:50)
    at Interface.emit (events.js:187:15)
    at Interface.EventEmitter.emit (domain.js:442:20)
    at Interface.close (readline.js:379:8)
    at Socket.onend (readline.js:157:10)
    at Socket.emit (events.js:187:15)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
I tried `executablePath: '/usr/bin/chromium-browser'` ,`args: ["--no-sandbox"]`, `ignoreDefaultArgs: ['--disable-extensions']` , and reinstalling node_modules.
but nothing worked for me. 
And here's the complete code,

```
const puppeteer = require('puppeteer-extra');
const StealthPlugin = require('puppeteer-extra-plugin-stealth');
puppeteer.use(StealthPlugin());
let browsers = {
    browser: undefined,
    browserNoProxy: undefined,
    pageProxy: undefined,
    pageNoProxy: undefined
};


(async () => {
    browsers.browserNoProxy = await puppeteer.launch({
        args: ['--start-maximized'],
        headless: false,
        executablePath: process.env.CHROMIUM_PATH || "./node_modules/puppeteer/.local-chromium/win64-706915/chrome-win/chrome.exe"
    });
    if (process.env.USE_PROXY === "true") {
        console.log('using proxy')
        browsers.browser = await puppeteer.launch({
            args: ['--proxy-server=127.0.0.1:24000', '--start-maximized'],
            headless: false,
            executablePath: process.env.CHROMIUM_PATH || "./node_modules/puppeteer/.local-chromium/win64-706915/chrome-win/chrome.exe"
        });
    } else {
        browsers.browser = browsers.browserNoProxy
    }
    browsers.pageProxy = await browsers.browser.newPage();
    browsers.pageNoProxy = await browsers.browserNoProxy.newPage()
    await browsers.pageProxy.goto("https://www.google.com");
    await browsers.pageNoProxy.goto("https://www.google.com");
})();

module.exports = browsers;
```

**Comment by michaelknoch** [comment]
did you figure it out? I'm running into the same issue @devinyasas
