### ISSUE TITLE
Page Crashed error

### ISSUE THREAD

**Issue by kevalrathod** [puppeteer/puppeteer#7486]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:2.1.x
* Platform / OS version: Linux
* Node.js version: Latest

**What steps will reproduce the problem?**

```
  let browser = await puppeteer.launch({headless: true, args: ["--no-sandbox=true","--disable-setuid-sandbox","--disable- 
  dev-shm-usage","--disable-gpu","--js-flags=--expose-gc"]});

  browser.on('targetchanged', async target => {
    const page = await target.page();
    page.setDefaultNavigationTimeout(0);
    if(config.settings.emulatedFormFactor == 'mobile'){
      await page.emulate(iPhone);
    } else {
      await page.setViewport({
        width: 1280,
        height: 800
      });
    }
  });

  try {
    const report = await lighthouse(url, {
        port: (new URL(browser.wsEndpoint())).port,
        output: 'json',
        logLevel: flags.logLevel,
      }, config);
    return report.lhr;
  } catch (e) {
    console.error(e);
  } finally {
    await browser.close();
  }

MY DOCKER:
FROM node:14.15.0-buster-slim

RUN apt-get update \
    && apt-get install -y wget gnupg libjemalloc2  \
      xvfb gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 \
      libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 \
      libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 \
      libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 \
      libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget && \
    rm -rf /var/lib/apt/lists/*

# uses jemalloc memory allocator
ENV LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.2
```

**What is the expected result?**
In some cases, it gives a page crashed error. While someone wants to generate reports and insert too many requests and the puppeteer gives the below error.

**What happens instead?**
Error: Page crashed!
    at Page._onTargetCrashed (/website-analyzer/node_modules/puppeteer/lib/Page.js:213:24)
    at CDPSession.<anonymous> (/website-analyzer/node_modules/puppeteer/lib/Page.js:122:56)
    at CDPSession.emit (events.js:315:20)
    at CDPSession._onMessage (/website-analyzer/node_modules/puppeteer/lib/Connection.js:200:12)
    at Connection._onMessage (/website-analyzer/node_modules/puppeteer/lib/Connection.js:112:17)
    at WebSocket.<anonymous> (/website-analyzer/node_modules/puppeteer/lib/WebSocketTransport.js:44:24)
    at WebSocket.onMessage (/website-analyzer/node_modules/puppeteer/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (/website-analyzer/node_modules/puppeteer/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (/website-analyzer/node_modules/puppeteer/node_modules/ws/lib/receiver.js:422:14)
    at Receiver.getData (/website-analyzer/node_modules/puppeteer/node_modules/ws/lib/receiver.js:352:17)
    at Receiver.startLoop (/website-analyzer/node_modules/puppeteer/node_modules/ws/lib/receiver.js:138:22)
    at Receiver._write (/website-analyzer/node_modules/puppeteer/node_modules/ws/lib/receiver.js:74:10)

**Comment by ivanvandessel-wk** [comment]
waiting for a css selector like one here:  "[data-test-id='shell-document-tab-nav-item'][aria-selected='true']" 

After upgrading to 22.11.0 from 22.10 of puppeteer
I receive this failure:

Puppeteer page error Error: Page crashed!
    at #onTargetCrashed (/usr/local/lib/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Page.js:399:50)
    at /usr/local/lib/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/third_party/mitt/mitt.js:62:7
    at Array.map (<anonymous>)
    at Object.emit (/usr/local/lib/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/third_party/mitt/mitt.js:61:20)
    at CdpCDPSession.emit (/usr/local/lib/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:83:23)
    at CdpCDPSession._onMessage (/usr/local/lib/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/CDPSession.js:82:18)
    at Connection.onMessage (/usr/local/lib/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:142:25)
    at WebSocket.<anonymous> (/usr/local/lib/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/node/NodeWebSocketTransport.js:44:32)
    at callListener (/usr/local/lib/node_modules/puppeteer/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onMessage (/usr/local/lib/node_modules/puppeteer/node_modules/ws/lib/event-target.js:209:9)
