### ISSUE TITLE
Using Amazon EC2 but can't install amazon-linux-extras

### ISSUE THREAD

**Issue by matsyui** [puppeteer/puppeteer#7504]
It runs fine when I host it to my PC, but it doesn't run on VPS/Cloud Hosting like Amazone EC2 and also to Heroku
**Error Log:**
```log
/home/container/node_modules/node-html-to-image/node_modules/puppeteer-cluster/dist/Cluster.js:120
                    throw new Error(`Unable to launch browser, error message: ${err.message}`);
                          ^

Error: Unable to launch browser, error message: Failed to launch the browser process!
/home/container/node_modules/node-html-to-image/node_modules/puppeteer/.local-chromium/linux-737027/chrome-linux/chrome: error while loading shared libraries: libXcomposite.so.1: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at Cluster.<anonymous> (/home/container/node_modules/node-html-to-image/node_modules/puppeteer-cluster/dist/Cluster.js:120:27)
    at Generator.throw (<anonymous>)
    at rejected (/home/container/node_modules/node-html-to-image/node_modules/puppeteer-cluster/dist/Cluster.js:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
  ```
    
If you think that I didn't try the [Troubleshooting ](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md), Well I also posted at [StackOverflow with another problem](https://stackoverflow.com/questions/68828553/error-sudo-amazon-linux-extras-command-not-found).

Here's my code for the js file that uses this package:
```js
		//Get chart image
		const coinchart = fs.readFileSync('./commands/token/chart/image.jpg');
		const base64Image = new Buffer.from(coinchart).toString('base64');
		const dataURI = 'data:image/jpeg;base64,' + base64Image
		
		nodeHtmlToImage({
		  output: './commands/token/chart/image.jpg',
		  html: "<html><body height='1080px' width='1920px'><script src='https://widgets.coingecko.com/coingecko-coin-price-chart-widget.js'></script><coingecko-coin-price-chart-widget  coin-id='XXXXX' currency='XXXX' height='100%' locale='en' background-color='#fdf0c0' width='100%'></coingecko-coin-price-chart-widget></body></html>",
		  content: { imageSource: dataURI }
		})
```

**Comment by matsyui** [comment]
Update: 

I've already installed all of this:
![image](https://user-images.githubusercontent.com/62344860/129940237-f715ff4c-5ff0-4e0c-8ced-f4fa611a88d4.png)
![image](https://user-images.githubusercontent.com/62344860/129940390-76c79b45-efd0-4f14-b024-c842d14f9b20.png)
![image](https://user-images.githubusercontent.com/62344860/129940509-0ebec76c-a4d6-405c-8a59-ec44ef6074a3.png)

Still giving me this error:
```log
(node:3563) UnhandledPromiseRejectionWarning: Error: Unable to launch browser, error message: Failed to launch the browser process!
/home/container/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at Cluster.<anonymous> (/home/container/node_modules/puppeteer-cluster/dist/Cluster.js:120:27)
    at Generator.throw (<anonymous>)
    at rejected (/home/container/node_modules/puppeteer-cluster/dist/Cluster.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3563) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3563) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
