### ISSUE TITLE
Error: Navigation failed because browser has disconnected!

### ISSUE THREAD

**Issue by ade566** [puppeteer/puppeteer#7531]
### Error: Navigation failed because browser has disconnected!
```
(node:147241) UnhandledPromiseRejectionWarning: Error: Navigation failed because browser has disconnected!
    at /home/api-umkm/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:51:147
    at /home/api-umkm/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:62
    at Array.map (<anonymous>)
    at Object.emit (/home/api-umkm/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:43)
    at CDPSession.emit (/home/api-umkm/node_modules/puppeteer/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
    at CDPSession._onClosed (/home/api-umkm/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:256:14)
    at Connection._onClose (/home/api-umkm/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:138:21)
    at WebSocket.<anonymous> (/home/api-umkm/node_modules/puppeteer/lib/cjs/puppeteer/node/NodeWebSocketTransport.js:17:30)
    at WebSocket.onClose (/home/api-umkm/node_modules/ws/lib/event-target.js:136:16)
    at WebSocket.emit (events.js:400:28)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:147241) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:147241) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

how i fix this sir?

**Comment by Heritsam** [comment]
could you please put the source and how do we reproduce the error?

**Comment by ade566** [comment]
```
const { Client, MessageMedia } = require('whatsapp-web.js');
const express = require('express');
const socketIO = require('socket.io');
const qrcode = require('qrcode');
const http = require('http');
const fs = require('fs');
const axios = require('axios');
const port = process.env.PORT || 3000;

const app = express();
const server = http.createServer(app);
const io = socketIO(server);

app.use(express.json());
app.use(express.urlencoded({
  extended: true
}));

app.get('/', (req, res) => {
  res.sendFile('multi.html', {
    root: __dirname
  });
});

const sessions = [];

const createSession = function (id, description) {
  console.log('Creating session: ' + id);
  const SESSION_FILE_PATH = `./whatsapp-session-${id}.json`;
  let sessionCfg;
  if (fs.existsSync(SESSION_FILE_PATH)) {
    sessionCfg = require(SESSION_FILE_PATH);
  }

  const client = new Client({
    restartOnAuthFail: true,
    puppeteer: {
      headless: true,
      args: [
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-dev-shm-usage',
        '--disable-accelerated-2d-canvas',
        '--no-first-run',
        '--no-zygote',
        '--single-process', // <- this one doesn't works in Windows
        '--disable-gpu'
      ],
    },
    session: sessionCfg
  });

  client.initialize();

  client.on('qr', (qr) => {
    console.log('QR RECEIVED', qr);
    qrcode.toDataURL(qr, (err, url) => {
      io.emit('qr', { id: id, src: url });
      io.emit('message', { id: id, text: 'QR Code received, scan please!' });
    });
  });

  client.on('ready', () => {
    io.emit('ready', { id: id });
    io.emit('message', { id: id, text: 'Whatsapp is ready!' });
  });

  client.on('authenticated', (session) => {
    io.emit('authenticated', { id: id });
    io.emit('message', { id: id, text: 'Whatsapp is authenticated!' });
    sessionCfg = session;
    fs.writeFile(SESSION_FILE_PATH, JSON.stringify(session), function (err) {
      if (err) {
        console.error(err);
      }
    });
  });

  client.on('auth_failure', function (session) {
    io.emit('message', { id: id, text: 'Auth failure, restarting...' });
  });

  client.on('disconnected', (reason) => {
    io.emit('message', { id: id, text: 'Whatsapp is disconnected!' });
    client.destroy();
    client.initialize();
  });

  // Tambahkan client ke sessions
  sessions.push({
    id: id,
    description: description,
    client: client
  });
}

// init();

// Socket IO
io.on('connection', function (socket) {
  // init(socket);

  socket.on('create-session', function (data) {
    console.log('Create session: ' + data.id);
    createSession(data.id, data.description);
  });
});

// Send message
app.post('/send-message', (req, res) => {
  const sender = req.body.sender;
  const number = req.body.number + '@c.us';
  const message = req.body.message;

  const client = sessions.find(sess => sess.id == sender).client;

  client.sendMessage(number, message).then(response => {
    res.status(200).json({
      status: true,
      response: response
    });
  }).catch(err => {
    res.status(500).json({
      status: false,
      response: err
    });
  });
});

server.listen(port, function () {
  console.log('App running on *: ' + port);
});

```

**Comment by jschfflr** [comment]
@ade566 
Thanks for taking the time to report this issue!
Could you maybe find a smaller reproduction for this issue?

**Comment by iamkhalidbashir** [comment]
Same error for me

**Comment by 1Map** [comment]
I get this same error when I have a https in my html:

**WORKS 100%:**

```
<html>
    <head>
        <link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet">
    </head>
    
    <body>
        <div class="container">
            <h1>Hello world</h1>
        </div>
    </body>
</html>
```

**DOES NOT WORK AND GIVES ERROR:**

```
<html>
    <head>
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet">
    </head>
    
    <body>
        <div class="container">
            <h1>Hello world</h1>
        </div>
    </body>
</html>
```

Error produced:

```
Report "test_bootstrap" render failed.

Navigation failed because browser has disconnected!
Error: Navigation failed because browser has disconnected!
    at /home/schalk/onemapjsreport/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:51:147
    at /home/schalk/onemapjsreport/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:62
    at Array.map (<anonymous>)
    at Object.emit (/home/schalk/onemapjsreport/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:43)
    at CDPSession.emit (/home/schalk/onemapjsreport/node_modules/puppeteer/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
    at CDPSession._onClosed (/home/schalk/onemapjsreport/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:271:14)
    at Connection._onClose (/home/schalk/onemapjsreport/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:144:21)
    at WebSocket.<anonymous> (/home/schalk/onemapjsreport/node_modules/puppeteer/lib/cjs/puppeteer/node/NodeWebSocketTransport.js:17:30)
    at WebSocket.onClose (/home/schalk/onemapjsreport/node_modules/ws/lib/event-target.js:210:18)
    at WebSocket.emit (node:events:390:28)
```

**Comment by Aex12** [comment]
I'm getting the same error on Fedora 35 (Using latest mesa from git, if that matters), just by launching puppeeter. If I run it on headless=true, I get this error:
```
DevTools listening on ws://127.0.0.1:41859/devtools/browser/1c7007fa-1a87-409d-b0fc-4ce9bb7141ad
[0311/111559.751342:WARNING:vaapi_wrapper.cc(589)] VAAPI video acceleration not available for swiftshader
[0311/111559.751470:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is swiftshader
[0311/111559.762718:ERROR:command_buffer_proxy_impl.cc(125)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
Received signal 11 SEGV_MAPERR 00000000101e
#0 0x557f3bb0bf49 base::debug::CollectStackTrace()
#1 0x557f3ba75933 base::debug::StackTrace::StackTrace()
#2 0x557f3bb0ba21 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#3 0x7f0176e4a750 (/usr/lib64/libc.so.6+0x4274f)
#4 0x557f3bb27e82 base::internal::PartitionGetSizeEstimate()
#5 0x7f015df46505 <unknown>
#6 0x7f015df46eb1 <unknown>
#7 0x7f0176f01752 gaih_inet.constprop.0
#8 0x7f0176f02639 __GI_getaddrinfo
#9 0x557f385c7605 net::AddrInfoGetter::getaddrinfo()
#10 0x557f385c7171 net::AddressInfo::Get()
#11 0x557f385f5846 net::SystemHostResolverCall()
#12 0x557f385ed32d net::HostResolverManager::ProcTask::DoLookup()
#13 0x557f385ed76b base::internal::Invoker<>::RunOnce()
#14 0x557f3baceb13 base::TaskAnnotator::RunTask()
#15 0x557f3bae5947 base::internal::TaskTracker::RunContinueOnShutdown()
#16 0x557f3bae5485 base::internal::TaskTracker::RunTask()
#17 0x557f3bb1c44e base::internal::TaskTrackerPosix::RunTask()
#18 0x557f3bae5118 base::internal::TaskTracker::RunAndPopNextTask()
#19 0x557f3baf0cba base::internal::WorkerThread::RunWorker()
#20 0x557f3baf099d base::internal::WorkerThread::RunPooledWorker()
#21 0x557f3bb1cc9c base::(anonymous namespace)::ThreadFunc()
#22 0x7f0176e95b1a start_thread
#23 0x7f0176f1a650 __clone3
  r8: 0000000000000000  r9: 0000000000000000 r10: 00007ffd2c097080 r11: 00007ffd2c097090
 r12: 00007f01641155c0 r13: 0000000000000000 r14: 000020720031f640 r15: 00007f01641154e0
  di: 0000557f40f4f7f8  si: 0000000000000000  bp: 00007f0164115490  bx: 00007f01641155c8
  dx: 0000000000000000  ax: 0000000000001000  cx: 0000000000000000  sp: 00007f0164115490
  ip: 0000557f3bb27e82 efl: 0000000000010206 cgf: 002b000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 000000001e493a01 cr2: 000000000000101e
[end of stack trace]
Error: Navigation failed because browser has disconnected!
    at /home/aex12/stuff/proyectos/own/test-cheerio-scrap/node_modules/.pnpm/puppeteer@10.4.0/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:51:147
    at /home/aex12/stuff/proyectos/own/test-cheerio-scrap/node_modules/.pnpm/puppeteer@10.4.0/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:62
    at Array.map (<anonymous>)
    at Object.emit (/home/aex12/stuff/proyectos/own/test-cheerio-scrap/node_modules/.pnpm/puppeteer@10.4.0/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:43)
    at CDPSession.emit (/home/aex12/stuff/proyectos/own/test-cheerio-scrap/node_modules/.pnpm/puppeteer@10.4.0/node_modules/puppeteer/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
    at CDPSession._onClosed (/home/aex12/stuff/proyectos/own/test-cheerio-scrap/node_modules/.pnpm/puppeteer@10.4.0/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:256:14)
    at Connection._onClose (/home/aex12/stuff/proyectos/own/test-cheerio-scrap/node_modules/.pnpm/puppeteer@10.4.0/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:138:21)
    at WebSocket.<anonymous> (/home/aex12/stuff/proyectos/own/test-cheerio-scrap/node_modules/.pnpm/puppeteer@10.4.0/node_modules/puppeteer/lib/cjs/puppeteer/node/NodeWebSocketTransport.js:17:30)
    at WebSocket.onClose (/home/aex12/stuff/proyectos/own/test-cheerio-scrap/node_modules/.pnpm/ws@7.4.6/node_modules/ws/lib/event-target.js:136:16)
    at WebSocket.emit (node:events:390:28)
```
If I run it with headless=false, I get this error:
```
DevTools listening on ws://127.0.0.1:44395/devtools/browser/edd4b390-12a9-4cb1-a227-9bbc94582ce5
[0311/112014.484774:ERROR:elf_dynamic_array_reader.h(61)] tag not found
[0311/112014.484818:ERROR:elf_dynamic_array_reader.h(61)] tag not found
Received signal 11 SEGV_MAPERR 00000000101e
#0 0x55c634ca6f49 base::debug::CollectStackTrace()
#1 0x55c634c10933 base::debug::StackTrace::StackTrace()
#2 0x55c634ca6a21 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#3 0x7f72eea17750 (/usr/lib64/libc.so.6+0x4274f)
#4 0x55c634cc2e82 base::internal::PartitionGetSizeEstimate()
#5 0x7f72ccffb505 <unknown>
#6 0x7f72ccffbeb1 <unknown>
#7 0x7f72eeace752 gaih_inet.constprop.0
#8 0x7f72eeacf639 __GI_getaddrinfo
#9 0x55c631762605 net::AddrInfoGetter::getaddrinfo()
#10 0x55c631762171 net::AddressInfo::Get()
#11 0x55c631790846 net::SystemHostResolverCall()
#12 0x55c63178832d net::HostResolverManager::ProcTask::DoLookup()
#13 0x55c63178876b base::internal::Invoker<>::RunOnce()
#14 0x55c634c69b13 ErrorEvent {
  target: WebSocket {
    _events: [Object: null prototype] { open: [Function], error: [Function] },
    _eventsCount: 2,
    _maxListeners: undefined,
    _binaryType: 'nodebuffer',
    _closeCode: 1006,
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: '',
    _closeTimer: null,
    _extensions: {},
    _protocol: '',
    _readyState: 3,
    _receiver: null,
    _sender: null,
    _socket: null,
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    _url: 'ws://127.0.0.1:44395/devtools/browser/edd4b390-12a9-4cb1-a227-9bbc94582ce5',
    _req: null,
    [Symbol(kCapture)]: false
  },
  type: 'error',
  message: 'socket hang up',
  error: Error: socket hang up
      at connResetException (node:internal/errors:691:14)
      at Socket.socketOnEnd (node:_http_client:471:23)
      at Socket.emit (node:events:402:35)
      at endReadableNT (node:internal/streams/readable:1343:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21) {
    code: 'ECONNRESET'
  }
}
[13257:13257:0100/000000.529655:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
[0311/112014.906319:ERROR:nacl_helper_linux.cc(307)] NaCl helper process running without a sandbox!
Most likely you need to configure your SUID sandbox correctly
```

These are the options I'm using to launch it:
```
      browser = await puppeteer.launch({                                                                                                                                                                                                                     
          args: ['--no-sandbox', '--disable-setuid-sandbox'],                                                                                                                                                                                                
          headless: false,                                                                                                                                                                                                                                   
          timeout: 10000,                                                                                                                                                                                                                                    
          dumpio: true,                                                                                                                                                                                                                                      
      });                                                                                                                                                                                                                                                    
```

**Comment by kalintro** [comment]
@1Map Did you manage to find a workaround for this? I have the same issue regarding https in my html suddenly

**Comment by KKMaster-code** [comment]
@kalintro, did you find any solution for this issue?
