### ISSUE TITLE
[Bug]: Argument should belong to the same JavaScript world as target object

### ISSUE THREAD

**Issue by putuoka** [puppeteer/puppeteer#7544]
### Bug description

Steps to reproduce the problem:

1. I don't know how to produce error because sometimes it appears sometimes it doesn't and it works very well. I think it's related to puppeteer or chrome because the error log doesn't include my script.
2. here's my script

await page.screenshot({ path: `${logFolderImg}blockgoogle.png` });
        console.log("ada bloking google popup agreement");
        await Promise.all([
          page.waitForNavigation(), // The promise resolves after navigation has finished
          page.click('form div[data-is-touch-wrapper="true"]>button'), // Clicking the link will indirectly cause a navigation
        ]);
this line clicking google cookie agreement. this page https://i.imgur.com/7MHa9OY.png

### Puppeteer version

10.2.0

### Node.js version

v14.15.3

### npm version

6.14.9

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
(node:9968) UnhandledPromiseRejectionWarning: Error: Protocol error (Runtime.callFunctionOn): Argument should belong to the same JavaScript
world as target object
    at E:\test\cloudflare\twitterpuppeteer\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:217:63
    at new Promise (<anonymous>)
    at CDPSession.send (E:\test\cloudflare\twitterpuppeteer\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:216:16)
    at next (E:\test\cloudflare\twitterpuppeteer\node_modules\puppeteer-extra-plugin-stealth\evasions\sourceurl\index.js:32:41)
    at CDPSession.send (E:\test\cloudflare\twitterpuppeteer\node_modules\puppeteer-extra-plugin-stealth\evasions\sourceurl\index.js:65:16)
    at ExecutionContext._evaluateInternal (E:\test\cloudflare\twitterpuppeteer\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:204:50)
    at ExecutionContext.evaluateHandle (E:\test\cloudflare\twitterpuppeteer\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:155:21)
    at ElementHandle.evaluateHandle (E:\test\cloudflare\twitterpuppeteer\node_modules\puppeteer\lib\cjs\puppeteer\common\JSHandle.js:120:46)    at Object.internalHandler.queryOne (E:\test\cloudflare\twitterpuppeteer\node_modules\puppeteer\lib\cjs\puppeteer\common\QueryHandler.js:24:44)
    at ElementHandle.$ (E:\test\cloudflare\twitterpuppeteer\node_modules\puppeteer\lib\cjs\puppeteer\common\JSHandle.js:675:29)
```

**Comment by jschfflr** [comment]
@putuoka Thanks for taking the time to report this issue! 
Can you run the script with `DEBUG=puppeteer:*` and paste the log messages here? Thanks!
