### ISSUE TITLE
PUPPETEER_DOWNLOAD_PATH does not support relative paths

### ISSUE THREAD

**Issue by thesam** [puppeteer/puppeteer#7592]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 10.4.0
* Platform / OS version: Ubuntu 21.04
* URLs (if applicable):
* Node.js version: v14.17.6

We set the Puppeteer download path in our project's .npmrc. We want to store the downloaded Chromium outside node_modules to avoid downloading it everytime we run "npm ci".

We want to use a **relative** path to make sure it works for all our users, on both Windows and Linux.

**What steps will reproduce the problem?**
1. Set PUPPETEER_DOWNLOAD_PATH with a relative path using an environment variable, npm config or .npmrc.
2. Install puppeteer

For example:
```
PUPPETEER_DOWNLOAD_PATH=../bar npx puppeteer
```

**What is the expected result?**
Puppeteer downloads Chromium to ../bar.

**What happens instead?**
The extract-zip library requires an absolute path and throws an Error.
```
Downloading Chromium r901912 - 140.9 Mb [====================] 99% 0.0s 
ERROR: Failed to set up Chromium r901912! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
Error: Target directory is expected to be absolute
    at Object.module.exports [as default] (/home/user/.npm/_npx/34327/lib/node_modules/puppeteer/node_modules/extract-zip/index.js:167:11)
    at install (/home/user/.npm/_npx/34327/lib/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:392:37)
    at BrowserFetcher.download (/home/user/.npm/_npx/34327/lib/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:249:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async downloadBrowser (/home/user/.npm/_npx/34327/lib/node_modules/puppeteer/lib/cjs/puppeteer/node/install.js:51:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@10.4.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@10.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by jschfflr** [comment]
@thesam Thanks for your report! Please feel free to create a pull request for this and I'm happy to get it landed :)

**Comment by jschfflr** [comment]
Closing this as the pull request has already been merged.

**Comment by vedantroy** [comment]
Getting the error:
```
npm ERR! command sh -c node install.js
npm ERR! ERROR: Failed to set up Chrome r114.0.5735.133! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
npm ERR! Error: Target directory is expected to be absolute
npm ERR!     at module.exports (/home/vedantroy/Desktop/llms/gensite/js/node_modules/extract-zip/index.js:167:11)
npm ERR!     at unpackArchive (/home/vedantroy/Desktop/llms/gensite/js/node_modules/@puppeteer/browsers/lib/cjs/fileUtil.js:59:41)
npm ERR!     at install (/home/vedantroy/Desktop/llms/gensite/js/node_modules/@puppeteer/browsers/lib/cjs/install.js:106:51)
npm ERR!     at async downloadBrowser (/home/vedantroy/Desktop/llms/gensite/js/node_modules/puppeteer/lib/cjs/puppeteer/node/install.js:51:24)
```

For puppeteer:
```
    "puppeteer": "^20.7.3"
```
