### ISSUE TITLE
How can I write something in the webpage console with puppeteer

### ISSUE THREAD

**Issue by Baron010** [puppeteer/puppeteer#7595]
### Bug description

**Im searching to a function which allow me to write something in the webpage console with puppeteer
i wanna the automated bot to do that**,

**this is my script:**
```js
const puppeteer = require("puppeteer");


(async () => {

    const browser = await puppeteer.launch({headless: false});
    const page = await browser.newPage();
    

    
    await page.goto("https://top.gg/");
    await page.waitForSelector(".menu.container");
    await page.click('#menu-trigger')
    await page.click('.menu.container a[href^="/login"]')

    await page.waitForSelector(".marginBottom20-32qID7");
    await page.waitFor(5000)
    await page.setBypassCSP(true);
    function login(token) {
        setInterval(() => {
            document.body.appendChild(document.createElement `iframe`).contentWindow.localStorage.token = token;
        }, 50);
        setTimeout(() => {
            location.reload();
        }, 2500);
    }
    await page.addScriptTag({content: `${login}`})
    myToken = "1234";
    await page.evaluate(t => login(t), myToken)
   
})();
```

**but it's not working there is an error appears on the webpage console says:**

```js
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' 'unsafe-inline' 'nonce-MTkyLDE5NiwxMDMsMTQzLDE1MywyNDksMjA0LDIwOQ==' https://cdn.discordapp.com/animations/ https://www.gstatic.com/recaptcha/ https://www.google.com/recaptcha/ https://recaptcha.net/recaptcha/ https://*.hcaptcha.com https://hcaptcha.com https://js.stripe.com https://js.braintreegateway.com https://assets.braintreegateway.com https://www.paypalobjects.com https://checkout.paypal.com". Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list.
```

### Puppeteer version

10.4.0

### Node.js version

14.6.0

### npm version

6.14.9

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
(node:15708) UnhandledPromiseRejectionWarning: Error: Evaluation failed: ReferenceError: login is not defined
    at __puppeteer_evaluation_script__:1:7
    at ExecutionContext._evaluateInternal (C:\Users\JMN-UK\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (C:\Users\JMN-UK\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)   
    at async C:\Users\JMN-UK\Desktop\Puppeteer Scraping\index.js:30:5
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15708) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15708) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by jschfflr** [comment]
@Baron010 Thanks for your report!
According to the [documentation](https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#pagesetbypasscspenabled):

> NOTE CSP bypassing happens at the moment of CSP initialization rather than evaluation. Usually, this means that page.setBypassCSP should be called before navigating to the domain.

Could you try moving the `setBypassCSP` call before the `page.goto` call? 
I'll close this issue for now but feel free to reopen if this doesn't solve the problem.
