### ISSUE TITLE
[Bug]: Error: Protocol error (Network.getResponseBody): No resource with given identifier found

### ISSUE THREAD

**Issue by kaykyr** [puppeteer/puppeteer#7607]
### Bug description

Hello! The response is related to a JSON response. I am creating this event listener to read response body.

I tried to use response.text() and response.json() none works. The error is the same:
Error: Protocol error (Network.getResponseBody): No resource with given identifier found

page.on('response', async (response) => {
	let resJson = await response.json()
	console.log(resJson)
})

Maybe a bug of 10.4.0 version?

### Puppeteer version

10.4.0

### Node.js version

15.7.0

### npm version

7.4.3

### What operating system are you seeing the problem on?

macOS

**Comment by jschfflr** [comment]
@kaykyr Thanks for taking the time to report this issue!
Could you share a full script to reproduce the problem? Thanks!

**Comment by kaykyr** [comment]
> @kaykyr Thanks for taking the time to report this issue! Could you share a full script to reproduce the problem? Thanks!

Hi! No problem! I'll send the script today! Thank you!

**Comment by kaykyr** [comment]
> @kaykyr Thanks for taking the time to report this issue! Could you share a full script to reproduce the problem? Thanks!

```js
import puppeteer from 'puppeteer'

async function test() {
    const browser = await puppeteer.launch({
        headless: false,
        devtools: true,
        ignoreHTTPSErrors: true,
        args: ['--no-sandbox'],
    })

    const instance = (await browser.pages())[0]
    const instanceDevice = puppeteer.devices['iPhone 6']

    await instance.emulate(instanceDevice)

    await instance.goto('https://www.instagram.com', {
        waitUntil: ['domcontentloaded', 'networkidle2'],
        timeout: 0,
    })

    instance.on('response', async (response) => {
        const url = response.url()
        const data = await response.json()

        console.log(url)
        console.log(data)
    })
}

test()
```

So, the error is:

```txt
❯ yarn dev
yarn run v1.22.10
warning package.json: No license field
$ sucrase-node ./bot.js
https://www.instagram.com/logging/falco
{ status: 'ok' }
https://www.instagram.com/ajax/bz
{ status: 'ok' }
/Users/kaykyramos/Desktop/pptr/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:217
            this._callbacks.set(id, { resolve, reject, error: new Error(), method });
                                                              ^

Error: Protocol error (Network.getResponseBody): No resource with given identifier found
    at /Users/kaykyramos/Desktop/pptr/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:217:63
    at new Promise (<anonymous>)
    at CDPSession.send (/Users/kaykyramos/Desktop/pptr/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:216:16)
    at /Users/kaykyramos/Desktop/pptr/node_modules/puppeteer/lib/cjs/puppeteer/common/HTTPResponse.js:99:53
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async HTTPResponse.text (/Users/kaykyramos/Desktop/pptr/node_modules/puppeteer/lib/cjs/puppeteer/common/HTTPResponse.js:111:25)
    at async HTTPResponse.json (/Users/kaykyramos/Desktop/pptr/node_modules/puppeteer/lib/cjs/puppeteer/common/HTTPResponse.js:124:25)
    at async /Users/kaykyramos/Desktop/pptr/bot.js:23:22
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jschfflr** [comment]
I think this has been fixed by the pull request. I'll cut a new release next week - could you verify it works?
Closing this in the meantime but feel free to reopen!
