### ISSUE TITLE
[Bug]: page.goto() - simple download example fails

### ISSUE THREAD

**Issue by darklightcode** [puppeteer/puppeteer#7626]
### Bug description

Steps to reproduce the problem:

```
const puppeteer = require('puppeteer');
const fs = require('fs');

(async () => {
    const browser = await puppeteer.launch({headless: true});
    const page = await browser.newPage();
    var response = await page.goto('https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/fonts/glyphicons-halflings-regular.eot');
    //var buffer = await response.buffer();
    //fs.writeFileSync("pom.xml", buffer);
    await browser.close();
})();
```

### Puppeteer version

10.4.0

### Node.js version

16.9.1

### npm version

7.21.1

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
Error: net::ERR_ABORTED at https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/fonts/glyphicons-halflings-regular.eot
    at navigate (D:\simple-pup\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:116:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async FrameManager.navigateFrame (D:\simple-pup\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:91:21)
    at async Frame.goto (D:\simple-pup\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:417:16)
    at async Page.goto (D:\simple-pup\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:1156:16)
    at async D:\simple-pup\sample.js:19:20
```

**Comment by jschfflr** [comment]
@darklightcode Thanks for taking the time to report this issue! This is the result of how Chromium handles downloads like this internally and unfortunately, there's nothing on the Puppeteer side we can do to work around this. Please open a feature request on https://crbug.com to get `Network.loadingFailed` to include if it has been converted into a download instead.
