### ISSUE TITLE
[Bug]: Puppeteer tries to `getAttribute` for just a simple screenshot of a webpage. And fails.

### ISSUE THREAD

**Issue by marvindanig** [puppeteer/puppeteer#7629]
### Bug description

Steps to reproduce the problem:

1. I have a running container for puppeteer that takes screenshot of a website on a mobile sized viewport per the following code:

```JS
const puppeteer = require('puppeteer')
const url = require('url')

module.exports = (website) => new Promise((resolve, reject) => {
  (async () => {
    const browser = await puppeteer.launch({
      headless: true,
      args: [
        "--disable-gpu",
        "--disable-dev-shm-usage",
        "--disable-setuid-sandbox",
        "--no-sandbox",
      ]
    })

    const page = await browser.newPage()

    await page.setUserAgent('Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1')
    await page.setViewport({
      width: 375,
      height: 812,
      deviceScaleFactor: 1
    })

    page.on('error', err => {
      reject(new Error(`In-page error: ${err}`));
    });

    page.on('pageerror', pageerr => {
      reject(new Error(`Pageerror occurred: ${pageerr}`));
    })

    try {
      console.log(website)
      await page.goto(website, { 'waitUntil': 'networkidle2', timeout: 10000 })
      await page.screenshot({ path: `./public/screenshots/${url.parse(website)?.hostname}.png` })
      await browser.close()
      resolve(website)
    } catch (e) {
      console.log('An expection on page.evaluate ', e)
      reject
    }
  })()
})

```

2. Taking a screenshot shouldn't require Puppeteer to look up into the DOM for an element and yet here we are:

```node
Test URL: https://app.dotplan.io/users/log_in
[💻] (node:68670) UnhandledPromiseRejectionWarning: Error: Pageerror occurred: Error: TypeError: Cannot read properties of null (reading 'getAttribute')
[💻]     at https://app.dotplan.io/js/app-a90da2866ba43f2c148c1574971e8c4f.js?vsn=d:1:227438
[💻]     at https://app.dotplan.io/js/app-a90da2866ba43f2c148c1574971e8c4f.js?vsn=d:1:227875
[💻]     at https://app.dotplan.io/js/app-a90da2866ba43f2c148c1574971e8c4f.js?vsn=d:1:227879
[💻]     at /Users/marvindanig/Projects/red.goose/red.goose.web/helpers/screenshot.js:31:14
[💻]     at /Users/marvindanig/Projects/red.goose/red.goose.web/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:62
[💻]     at Array.map (<anonymous>)
[💻]     at Object.emit (/Users/marvindanig/Projects/red.goose/red.goose.web/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:43)
[💻]     at Page.emit (/Users/marvindanig/Projects/red.goose/red.goose.web/node_modules/puppeteer/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
[💻]     at Page._handleException (/Users/marvindanig/Projects/red.goose/red.goose.web/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:949:14)
[💻]     at /Users/marvindanig/Projects/red.goose/red.goose.web/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:161:66
[💻]     at /Users/marvindanig/Projects/red.goose/red.goose.web/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:62
[💻]     at Array.map (<anonymous>)
[💻]     at Object.emit (/Users/marvindanig/Projects/red.goose/red.goose.web/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:43)
[💻] (Use `node --trace-warnings ...` to show where the warning was created)
[💻] (node:68670) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[💻] (node:68670) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

How do I prevent headless Puppeteer to simply screenshot the page peacefully and not go after attributes of anything on the HTML within the page? 

### Puppeteer version

"puppeteer": "^10.4.0"

### Node.js version

FROM node:16.10.0

### npm version

7.24.0

### What operating system are you seeing the problem on?

macOS

### Relevant log output

```shell
Test URL: https://app.dotplan.io/users/log_in
[💻] (node:68670) UnhandledPromiseRejectionWarning: Error: Pageerror occurred: Error: TypeError: Cannot read properties of null (reading 'getAttribute')
[💻]     at https://app.dotplan.io/js/app-a90da2866ba43f2c148c1574971e8c4f.js?vsn=d:1:227438
[💻]     at https://app.dotplan.io/js/app-a90da2866ba43f2c148c1574971e8c4f.js?vsn=d:1:227875
[💻]     at https://app.dotplan.io/js/app-a90da2866ba43f2c148c1574971e8c4f.js?vsn=d:1:227879
[💻]     at /Users/marvindanig/Projects/red.goose/red.goose.web/helpers/screenshot.js:31:14
[💻]     at /Users/marvindanig/Projects/red.goose/red.goose.web/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:62
[💻]     at Array.map (<anonymous>)
[💻]     at Object.emit (/Users/marvindanig/Projects/red.goose/red.goose.web/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:43)
[💻]     at Page.emit (/Users/marvindanig/Projects/red.goose/red.goose.web/node_modules/puppeteer/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
[💻]     at Page._handleException (/Users/marvindanig/Projects/red.goose/red.goose.web/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:949:14)
[💻]     at /Users/marvindanig/Projects/red.goose/red.goose.web/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:161:66
[💻]     at /Users/marvindanig/Projects/red.goose/red.goose.web/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:62
[💻]     at Array.map (<anonymous>)
[💻]     at Object.emit (/Users/marvindanig/Projects/red.goose/red.goose.web/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:43)
[💻] (Use `node --trace-warnings ...` to show where the warning was created)
[💻] (node:68670) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[💻] (node:68670) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by jschfflr** [comment]
@marvindanig Thanks for taking the time to report this issue! Puppeteer is not calling `getAttribute` - that's something that happens on the page itself. To verify, please go to `https://app.dotplan.io/users/log_in` and check the console in DevTools there. Closing this as it is unrelated to Puppeteer.

**Comment by marvindanig** [comment]
Thank you for looking into this @jschfflr. I will notify the issue to the site owner of Dotplan.

**Comment by jschfflr** [comment]
Sure, happy to help!
