### ISSUE TITLE
[Bug]: network error visiting apple story page

### ISSUE THREAD

**Issue by bryanzhou** [puppeteer/puppeteer#7676]
### Bug description

Steps to reproduce the problem:

1.  page.goto("https://apps.apple.com/cn/story/id1584592202")

### Puppeteer version

1.20.0

### Node.js version

v14.17.0

### npm version

6.14.13

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
Error: net::ERR_ABORTED at https://apps.apple.com/cn/story/id1584592202
    at navigate (/data0/puppeteer/xiaohongshu_nodejs/node_modules/puppeteer/lib/FrameManager.js:120:37)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async FrameManager.navigateFrame (/data0/puppeteer/xiaohongshu_nodejs/node_modules/puppeteer/lib/FrameManager.js:94:17)
    at async Frame.goto (/data0/puppeteer/xiaohongshu_nodejs/node_modules/puppeteer/lib/FrameManager.js:406:12)
    at async Page.goto (/data0/puppeteer/xiaohongshu_nodejs/node_modules/puppeteer/lib/Page.js:674:12)
    at async Object.get (/data0/puppeteer/xiaohongshu_nodejs/common_proxy_clawer.js:228:27)
    at async doProxyJob (/data0/puppeteer/xiaohongshu_nodejs/common_proxy_server.js:143:26)
```

**Comment by bryanzhou** [comment]
I found this code caused the problem
```
await page.emulate(mobileDevices['iPhone X'])
```
