### ISSUE TITLE
[Bug]: await page.waitFor(element, {visible: true}) or page.click(element) not working with mobile emulation if input is not in viewport

### ISSUE THREAD

**Issue by PythonCoderAS** [puppeteer/puppeteer#7680]
### Bug description

Steps to reproduce the problem:

1. Open a form using the bundled Chromium (90.1 I think)
2. Click an element that causes another element **below** the current viewport
3. Try to wait for/click the element

### Puppeteer version

10.2.0

### Node.js version

16.11.0

### npm version

8.0.0

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
Oct 12 20:17:01 ubuntuserver node[88953]: TimeoutError: waiting for selector `#q1no` failed: timeout 30000ms exceeded
Oct 12 20:17:01 ubuntuserver node[88953]:     at new WaitTask (/home/<user>/HealthScreeningBot/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:509:34)
Oct 12 20:17:01 ubuntuserver node[88953]:     at DOMWorld.waitForSelectorInPage (/home/<user>/HealthScreeningBot/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:420:>
Oct 12 20:17:01 ubuntuserver node[88953]:     at Object.internalHandler.waitFor (/home/<user>/HealthScreeningBot/node_modules/puppeteer/lib/cjs/puppeteer/common/QueryHandler.js:>
Oct 12 20:17:01 ubuntuserver node[88953]:     at DOMWorld.waitForSelector (/home/<user>/HealthScreeningBot/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:313:29)
Oct 12 20:17:01 ubuntuserver node[88953]:     at Frame.waitForSelector (/home/<user>/HealthScreeningBot/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:841:51)
Oct 12 20:17:01 ubuntuserver node[88953]:     at Page.waitForSelector (/home/<user>/HealthScreeningBot/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2252:33)
Oct 12 20:17:01 ubuntuserver node[88953]:     at /home/<user>/HealthScreeningBot/produce_screenshot.js:99:47
Oct 12 20:17:01 ubuntuserver node[88953]:     at step (/home/<user>/HealthScreeningBot/produce_screenshot.js:33:23)
Oct 12 20:17:01 ubuntuserver node[88953]:     at Object.next (/home/<user>/HealthScreeningBot/produce_screenshot.js:14:53)
Oct 12 20:17:01 ubuntuserver node[88953]:     at fulfilled (/home/<user>/HealthScreeningBot/produce_screenshot.js:5:58)
```

**Comment by PythonCoderAS** [comment]
The interesting part is that if I run the same code on an rpi with chromium v88, everything works as expected.

**Comment by jludc** [comment]
i have the same problem (linux)
do you have resolved this question?
