### ISSUE TITLE
[Bug]: 10.4.0 closes all browser instances when .close() is called on one

### ISSUE THREAD

**Issue by edqallen** [puppeteer/puppeteer#7686]
### Bug description

Steps to reproduce the problem:

1. Create an application that opens a browser and begins fetching pages.
2. Create another application that opens a browser, fetches a page, then closes the browser and exits.
3. Run both apps simultaneously.  When the second app exits, the first will crash with the error "Error: Navigation failed because browser has disconnected!"

This behavior was tested and confirmed with puppeteer 10.0.0 and 10.4.0 running on Windows 10 in WSL2.

### Puppeteer version

10.4.0

### Node.js version

14.17.0

### npm version

irrelevant

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
Error: Navigation failed because browser has disconnected!
    at /home/edqallen/projects/webcrawler/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:51:147
    at /home/edqallen/projects/webcrawler/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:62
    at Array.map (<anonymous>)
    at Object.emit (/home/edqallen/projects/webcrawler/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:43)
    at CDPSession.emit (/home/edqallen/projects/webcrawler/node_modules/puppeteer/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
    at CDPSession._onClosed (/home/edqallen/projects/webcrawler/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:256:14)
    at Connection._onMessage (/home/edqallen/projects/webcrawler/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:99:25)
    at WebSocket.<anonymous> (/home/edqallen/projects/webcrawler/node_modules/puppeteer/lib/cjs/puppeteer/node/NodeWebSocketTransport.js:13:32)
    at WebSocket.onMessage (/home/edqallen/projects/webcrawler/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js:376:20)
```

**Comment by edqallen** [comment]
Ignore this, error was my own.  Sorry!
