### ISSUE TITLE
[Bug]: Following redirects only when headless = false

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#7756]
### Bug description

Steps to reproduce the problem:

The following code throws an exception:

```
const puppeteer = require('puppeteer');

(async () => {

  const browser = await puppeteer.launch({headless : true});
  const page = await browser.newPage();
  response = await page.goto('http://www.islandpacket.com/');
  await page.screenshot({ path: 'example.png' });
  await browser.close();
})();

```
It works fine if headless is set to False.

### Puppeteer version

11.0.0

### Node.js version

8.16.2

### npm version

6.4.1

### What operating system are you seeing the problem on?

macOS

### Relevant log output

```shell
$node test-follow-redirects.js 
(node:26056) UnhandledPromiseRejectionWarning: TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (/Users/buster/node_modules/puppeteer/lib/LifecycleWatcher.js:143:21)
    at <anonymous>
  -- ASYNC --
    at Frame.<anonymous> (/Users/buster/node_modules/puppeteer/lib/helper.js:108:27)
    at Page.goto (/Users/buster/node_modules/puppeteer/lib/Page.js:662:49)
    at Page.<anonymous> (/Users/buster/node_modules/puppeteer/lib/helper.js:109:23)
    at /Users/buster/test-follow-redirects.js:8:25
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:26056) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:26056) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Aliaksandr-K-JazzTeam** [comment]
Try to change opening page to:
```
const url = 'http://www.islandpacket.com/';
await page.goto(url, {waitUntil: 'load'});
```

**Comment by ghost** [comment]
Tried that but still doesn't work. There seems to be some logic problem when headless is set True.

**Comment by Aliaksandr-K-JazzTeam** [comment]
Try to update your Node.js to at least 14 or 16

**Comment by ghost** [comment]
Thank you, that definitely helped.
