### ISSUE TITLE
[Bug]: Error: net::ERR_CONNECTION_REFUSED 

### ISSUE THREAD

**Issue by t1a2l** [puppeteer/puppeteer#7759]
### Bug description

Hey i am facing an issue while trying to connect to localhost or127.0.0.1 when trying to run tests with mocha and puppetter. ( iam using vs code on windows 10, no issues with linux virtual machine).

before(async () => { /* before hook for mocha testing */
      page = await browser.newPage();
      await page.waitForTimeout(5000);
      await page.goto(`https://127.0.0.1:${config.port}/app.html`);
      await page.setViewport( { width: 1920, height: 1080} );
  });

### Puppeteer version

11

### Node.js version

12.14.1

### npm version

8.1.3

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
Error: net::ERR_CONNECTION_REFUSED at https://127.0.0.1:3030/app.html
      at navigate (node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:155:23)
      at runNextTicks (internal/process/task_queues.js:59:5)
      at listOnTimeout (internal/timers.js:501:9)
      at processTimers (internal/timers.js:475:7)
      at async FrameManager.navigateFrame (node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:130:21)
      at async Frame.goto (node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:500:16)
      at async Page.goto (node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:1167:16)
      at async Context.<anonymous> (test\frontend\test\index.test.js:68:7)
```

**Comment by Kujo-Jotaro-AAAAA** [comment]
fixed?

**Comment by t1a2l** [comment]
As part of the puppeteer tests, i added a server for client tests: (not the solution but what i used before and caused the error)
```
const server_opt = {
      cwd: './',
      env: process.env,
};
server_process = await spawn('npm', ['run',  "test-server"], server_opt);
```
The fix was to add to the server_opt the "port" property and the server port number. for me it was "port: 3010" but your port maybe different.

**Comment by Rah1x** [comment]
im also getting this error

**Comment by ngohuytrieu** [comment]
Has anyone found a solution for this?
I have the node js app runs with docker

1. Localhost runs just fine
2. But on Gitlab CI, this error occurred
