### ISSUE TITLE
cron, xvfb and puppeteer : raises SyntaxError: Invalid regular expression 

### ISSUE THREAD

**Issue by yarekc** [puppeteer/puppeteer#7760]
When I run my node command in ssh

`xvfb-run -a node /var/www/html/jardinsgmc/fb.js`

everything runs fine

When I run it from cron 
`0 * * * * xvfb-run -a node /var/www/html/jardinsgmc/fb.js`

I got this strange error

```
/var/www/html/jardinsgmc/node_modules/puppeteer/lib/cjs/puppeteer/common/AriaQueryHandler.js:30
const attributeRegexp = /\[\s*(?<attribute>\w+)\s*=\s*"(?<value>\\.|[^"\\]*)"\s*\]/g;
                        ^

SyntaxError: Invalid regular expression: /\[\s*(?<attribute>\w+)\s*=\s*"(?<value>\\.|[^"\\]*)"\s*\]/: Invalid group
    at Object.<anonymous> (/var/www/html/jardinsgmc/node_modules/puppeteer/lib/cjs/puppeteer/common/AriaQueryHandler.js:30:25)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/html/jardinsgmc/node_modules/puppeteer/lib/cjs/puppeteer/common/QueryHandler.js:19:31)
    at Module._compile (module.js:653:30)
```

In fact that error is raised as soon as I got 

`const puppeteer = require('puppeteer');`

in my script

Any idea ?

**Comment by mathiasbynens** [comment]
Which version of Node.js are you using? `node -v`

**Comment by yarekc** [comment]
It was an issue with node path.
If I run node with full path, then it works fine.

Probably because I updated node using the npm n .

**Comment by kristianstroka** [comment]
Well we noticed this same issue with using node cron with expressjs (so we are not using nodejs from shell), do you have an ideas what can cause this kind of errors?

**Comment by ghost** [comment]
> It was an issue with node path. If I run node with full path, then it works fine.
> 
> Probably because I updated node using the npm n .

I am getting the same error. can you show me how to fix it? details please

**Comment by yarekc** [comment]
Put the whole path to node like

/user/bin/node script.js

instead of 

node script.js

**Comment by kristianstroka** [comment]
well but we are running puppeteer in nodejs expressjs server

**Comment by johnou** [comment]
@mathiasbynens we are running into the same issue on node version: 8.17.0.

```
06 03 2022 12:06:47.243:ERROR [config]: Invalid config file!
  SyntaxError: Invalid regular expression: /\[\s*(?<attribute>\w+)\s*=\s*(?<quote>"|')(?<value>\\.|.*?(?=\k<quote>))\k<quote>\s*\]/: Invalid group
    at Object.<anonymous> (/srv/node_modules/puppeteer/lib/cjs/puppeteer/common/AriaQueryHandler.js:30:25)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (/srv/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/srv/node_modules/puppeteer/lib/cjs/puppeteer/common/QueryHandler.js:19:31)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (/srv/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/srv/node_modules/puppeteer/lib/cjs/puppeteer/common/Puppeteer.js:21:27)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (/srv/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/srv/node_modules/puppeteer/lib/cjs/puppeteer/node/Puppeteer.js:22:24)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (/srv/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/srv/node_modules/puppeteer/lib/cjs/puppeteer/initialize-node.js:19:24)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (/srv/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/srv/node_modules/puppeteer/lib/cjs/puppeteer/node.js:18:30)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (/srv/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/srv/node_modules/puppeteer/cjs-entry.js:28:25)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (/srv/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/srv/karma.conf.js:7:17)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (/srv/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.parseConfig (/srv/node_modules/karma/lib/config.js:284:22)
    at new Server (/srv/node_modules/karma/lib/server.js:57:20)
    at Gulp.<anonymous> (/srv/tasks/test.js:15:16)
    at module.exports (/srv/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/srv/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/srv/node_modules/orchestrator/index.js:214:10)
    at /srv/node_modules/orchestrator/index.js:279:18
    at finish (/srv/node_modules/orchestrator/lib/runTask.js:21:8)
    at /srv/node_modules/orchestrator/lib/runTask.js:43:4
    at <anonymous>:null:null
```

**Comment by johnou** [comment]
guess it might be related to coffee-script, I'm still investigating.

**Comment by johnou** [comment]
https://github.com/puppeteer/puppeteer/issues/7887

**Comment by johnou** [comment]
works if I modify the regex declaration to the following..

```
const attributeRegexp = new RegExp('\[\s*(?<attribute>\w+)\s*=\s*(?<quote>"|\')(?<value>\\.|.*?(?=\k<quote>))\k<quote>\s*\]', 'g');
```
