### ISSUE TITLE
[Bug]: Missing async stack trace on for Protocol Error: Target Closed

### ISSUE THREAD

**Issue by youvalb** [puppeteer/puppeteer#7786]
### Bug description

When the browser is terminated (either explicitly or after a crash, or being externally killed),  and we call `page.evaluate()` the resulting stack trace doesn't show the asynchronous call stack.

This is in contrast to other errors, like "TimeoutError: waiting for selector" when calling `page.waitForSelector()` with a selector for a non-existing element( as described in #979)

The script below demonstrates the disparate behavior in the two situations (the output is included as "log output"):
```javascript
const puppeteer = require('puppeteer');

async function puppeteerTargetClosedError(browser, page) {
    browser.close();
    return page.evaluate(()=>Date.now()).then( now => {console.log(now);})
}

async function puppeteerMissingElementError(page) {
    await page.waitForSelector('a[href="does/not/exist"]', { timeout: 50 });
}

(async () => {
    let browser = await puppeteer.launch({ headless: false });
    let page = await browser.newPage();

    console.log("Testing Puppeteer timeout /missing element error:  stack trace shows full async calling chain, as expected\n");
    try {
        await puppeteerMissingElementError(page);
    }
    catch (e) {
        console.error(e);
    }

    console.log("\n\nTesting a puppeteer closed browser error :  stack trace doesn't show async calling chain\n");  

    try {
        await puppeteerTargetClosedError(browser, page);
    }
    catch (e) {
        console.error(e);
    }
})();
```

### Puppeteer version

11.0.0

### Node.js version

v16.12.0

### npm version

8.1.0

### What operating system are you seeing the problem on?

macOS

### Relevant log output

```
Testing Puppeteer timeout /missing element error:  stack trace shows full async calling chain, as expected

TimeoutError: waiting for selector `a[href="does/not/exist"]` failed: timeout 50ms exceeded
    at new WaitTask (/private/tmp/test/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:517:34)
    at DOMWorld.waitForSelectorInPage (/private/tmp/test/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:428:26)
    at Object.internalHandler.waitFor (/private/tmp/test/node_modules/puppeteer/lib/cjs/puppeteer/common/QueryHandler.js:31:77)
    at DOMWorld.waitForSelector (/private/tmp/test/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:321:29)
    at Frame.waitForSelector (/private/tmp/test/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:924:51)
    at Page.waitForSelector (/private/tmp/test/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2359:33)
    at puppeteerMissingElementError (/private/tmp/test/errors.js:9:16)
    at /private/tmp/test/errors.js:18:15
    at processTicksAndRejections (node:internal/process/task_queues:96:5)


Testing a puppeteer closed browser error :  stack trace doens't show async calling chain

ProtocolError: Protocol error (Runtime.callFunctionOn): Target closed.
    at /private/tmp/test/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:226:24
    at new Promise (<anonymous>)
    at CDPSession.send (/private/tmp/test/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:222:16)
    at ExecutionContext._evaluateInternal (/private/tmp/test/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:204:50)
    at ExecutionContext.evaluate (/private/tmp/test/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:27)
    at DOMWorld.evaluate (/private/tmp/test/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:95:24) {
  originalMessage: undefined
}
```

**Comment by udalyi-qs** [comment]
@youvalb 

```
async function puppeteerTargetClosedError(browser, page) {
    const executionContext = await page.mainFrame().executionContext();

    browser.close();
    return executionContext.evaluate(()=>Date.now()).then( now => {console.log(now);});
}
```

**Comment by youvalb** [comment]
@udalyi-qs 

I can't really use your solution, because in the real world scenario the browser is killed externally after it's getting stuck.  The problem is that I don't know what in my code leads to the browser getting stuck in the first place (this is why I was hoping to get a full stack trace).

Would you consider this behavior a bug in Puppeteer?  If so, would fixing it require a major change, or is it rather simple?

**Comment by udalyi-qs** [comment]
@youvalb 
There is a quick solution. You can use Bluebird, which is a fully featured promise library. It will give you the full stack trace.

`global.Promise = require('bluebird');`

If you use babel, you might want to use transform-async-to-bluebird instead.
