### ISSUE TITLE
[Bug]: Protocol error (Target.createTarget): Failed to open a new tab, in launching with '--guest'

### ISSUE THREAD

**Issue by YusukeIwaki** [puppeteer/puppeteer#7807]
### Bug description

Steps to reproduce the problem:

Here is a minimum example for reproducing this issue:

```js
const puppeteer = require('puppeteer-core')

puppeteer.launch({ channel: 'chrome', headless: false, args: ['--guest'] }).then(async (browser) => {
    const page = await browser.newPage()
})
```

then get an error:

```
ProtocolError: Protocol error (Target.createTarget): Failed to open a new tab
    at /Users/yusuke-iwaki/Desktop/pup-js/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:75:24
    at new Promise (<anonymous>)
    at Connection.send (/Users/yusuke-iwaki/Desktop/pup-js/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:71:16)
    at Browser._createPageInContext (/Users/yusuke-iwaki/Desktop/pup-js/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Browser.js:261:53)
    at BrowserContext.newPage (/Users/yusuke-iwaki/Desktop/pup-js/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Browser.js:520:30)
    at Browser.newPage (/Users/yusuke-iwaki/Desktop/pup-js/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Browser.js:254:37)
    at /Users/yusuke-iwaki/Desktop/pup-js/main.js:4:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  originalMessage: 'Failed to open a new tab'
}
```

### Puppeteer version

12.0.0

### Node.js version

16.10.0

### npm version

7.24.0

### What operating system are you seeing the problem on?

macOS

**Comment by Kle0s** [comment]
I have also noticed this bug lately. From what I saw, it only happens when puppeteer's browser is initiates with `headless: false`

**Comment by BrayanLope5** [comment]
I have the same issue when setting headless: false.

**Comment by StasToken** [comment]
I confirm that the problem persists to this day, and it appears by accident, the browser worked fine and then every time this problem started to appear at startup

**Comment by tejohnso** [comment]
Same error using `headless: "new"`

**Comment by aminaodzak** [comment]
Any workaround for this?

I'm using playwright/typescript, and have chrome extension that needs to be launched in persistent context, therefore headless needs to be set to false.

**Comment by mercuryyy** [comment]
I am having the same issue any solution on this?

**Comment by tbrockman** [comment]
Also encountering this error.

**Comment by HadyMash** [comment]
Same issue here

**Comment by OrKoN** [comment]
Still happens, the issue needs to be filed upstream as it looks like some CDP methods do not work with the guest mode.

**Comment by kawanet** [comment]
Same

- Chromium 128.0.6613.84
- puppeteer-core: 22.5.0 & 23.1.1 
- node v20.17.0

It causes the error with `--guest` mode. It works when `--guest` option removed however.

**Comment by jjaic-neogov** [comment]
hi @kawanet 
any luck with solution? 
I am facing same issue.
Only thing if I remove --guest it timeouts

**Comment by daliuchen** [comment]
I added --disable-dev-shm-usage, removed --guest and headless mode, and now it doesn't throw errors
