### ISSUE TITLE
[Bug]: Installation fails when using `yarn --modules-folder=not_node_modules`

### ISSUE THREAD

**Issue by evanpurkhiser** [puppeteer/puppeteer#7820]
### Bug description

Steps to reproduce the problem:

```
$ mkdir puppeteer-failure-case
$ cd puppeteer-failure-case
$ yarn init --yes
$ yarn add puppeteer
$ rm -rf node_modules
$ yarn install --modules-folder=test

yarn install v1.22.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
error /Users/evan/Coding/puppeteer-failure-case/test/puppeteer: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: /Users/evan/Coding/puppeteer-failure-case/test/puppeteer
Output:
node:internal/modules/cjs/loader:927
  const err = new Error(message);
              ^

Error: Cannot find module 'progress'
Require stack:
- /Users/evan/Coding/puppeteer-failure-case/test/puppeteer/lib/cjs/puppeteer/node/install.js
- /Users/evan/Coding/puppeteer-failure-case/test/puppeteer/install.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:927:15)
    at Function.Module._load (node:internal/modules/cjs/loader:772:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/Users/evan/Coding/puppeteer-failure-case/test/puppeteer/lib/cjs/puppeteer/node/install.js:24:36)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/evan/Coding/puppeteer-failure-case/test/puppeteer/lib/cjs/puppeteer/node/install.js',
    '/Users/evan/Coding/puppeteer-failure-case/test/puppeteer/install.js'
  ]
}
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

### Puppeteer version

12.0.1

### Node.js version

16.5.0

### npm version

yarn  1.22.4

### What operating system are you seeing the problem on?

Linux, macOS

**Comment by djones8520** [comment]
I'm having nearly the exact same error message when trying to install puppeteer.  There are just a few slight differences in the numbers on the end of the lines and mine is Module._load instead of Function.Module._load (and a few other like that).  I've tried adding via yarn add and also manually adding to package.json (puppeteer v14.1.0) and I get the same error for both.

```
yarn install v1.22.18
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error /path-to-project/public/assets/vendor/puppeteer: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: /path-to-project/public/assets/vendor/puppeteer
Output:
node:internal/modules/cjs/loader:939
  const err = new Error(message);
              ^

Error: Cannot find module 'progress'
Require stack:
- /path-to-project/public/assets/vendor/puppeteer/lib/cjs/puppeteer/node/install.js
- /path-to-project/public/assets/vendor/puppeteer/install.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:939:15)
    at Module._load (node:internal/modules/cjs/loader:780:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/path-to-project/public/assets/vendor/puppeteer/lib/cjs/puppeteer/node/install.js:23:36)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/path-to-project/public/assets/vendor/puppeteer/lib/cjs/puppeteer/node/install.js',
    '/path-to-project/public/assets/vendor/puppeteer/install.js'
  ]
}
```

**Commands**
yarn add puppeteer or yarn install (after adding puppeteer to package.json)

Node version: 18.1.0
Yarn version: 1.22.18

**OS**
I'm having this happen on mac using a laravel homestead environment and also on our stage server that is running ubuntu 20.
