### ISSUE TITLE
[Bug]: --proxy-server argument not working 

### ISSUE THREAD

**Issue by C4T4** [puppeteer/puppeteer#7837]
### Bug description

the proxy is working but inside puppeteer I get a ERR_EMPTY_RESPONSE error.
still the "--proxy-server" option available? (can't find the argument in the documentation)

I tried different node and puppeteer versions on a ubuntu server, same result

```const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
      args: [
          '--proxy-server=amsterdam.nl.socks.nordhold.net:1080'
      ]
  });
  const page = await browser.newPage();
  await page.authenticate({ username: "xxxx", password:"yyyy" });
  await page.goto('https://pptr.dev/');
  await page.screenshot({ path: 'visit.png' });

  await browser.close();
})();
```

### Puppeteer version

11.0.0

### Node.js version

17.2.0

### npm version

8.1.4

### What operating system are you seeing the problem on?

macOS

### Relevant log output

```shell
node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:155
                    ? new Error(`${response.errorText} at ${url}`)
                      ^

Error: net::ERR_EMPTY_RESPONSE at https://pptr.dev/
    at navigate (/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:155:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async FrameManager.navigateFrame (/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:130:21)
    at async Frame.goto (/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:500:16)
    at async Page.goto (/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1167:16)
    at async test.js:11:3
```

**Comment by yangguangwuwu** [comment]
Is this bug fixed ？

**Comment by dr0i** [comment]
@yangguangwuwu I can confirm that it's working now using the  `--proxy-server` args.
