### ISSUE TITLE
[Bug]:  Failed to launch the browser process! 

### ISSUE THREAD

**Issue by BUPTlhuanyu** [puppeteer/puppeteer#7874]
### Bug description

```
    const browser = await puppeteer.launch({
        // executablePath: path.resolve('/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'),
        args: [
            '--no-sandbox',
            '--disable-setuid-sandbox',
            '--disable-dev-shm-usage',
            '--disable-accelerated-2d-canvas', 
            '--disable-gpu' 
        ],
        headless: true,
        devtools: false
    });
```

### Puppeteer version

8.0.0

### Node.js version

v12.13.0

### npm version

6.12.0

### What operating system are you seeing the problem on?

macOS

### Relevant log output

```shell
Error: Failed to launch the browser process!
/home/work/xxx/node_modules/puppeteer/.local-chromium/linux-856583/chrome-linux/chrome: symbol lookup error: /usr/lib64/libgdk_pixbuf-2.0.so.0: undefined symbol: g_bytes_unref


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/work/xxx/node_modules/puppeteer/src/node/BrowserRunner.ts:222:9)
    at Interface.<anonymous> (/home/work/xxx/node_modules/puppeteer/src/node/BrowserRunner.ts:208:50)
    at Interface.emit (events.js:215:7)
    at Interface.EventEmitter.emit (domain.js:476:20)
    at Interface.close (readline.js:403:8)
    at Socket.onend (readline.js:180:10)
    at Socket.emit (events.js:215:7)
    at Socket.EventEmitter.emit (domain.js:476:20)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Done in 5.00s.
```

**Comment by BUPTlhuanyu** [comment]
centos 6.10

**Comment by PythonCoderAS** [comment]
https://github.com/electron-userland/electron-prebuilt/issues/182 is related.

**Comment by jrandolf-google** [comment]
We no longer support Node 12, please try this again with the latest version of Puppeteer and Node 14+.
