### ISSUE TITLE
[Bug]: aria selection not working on docker build

### ISSUE THREAD

**Issue by sbland** [puppeteer/puppeteer#7903]
### Bug description

I'm using the following selection that works fine when running Puppeteer inside WSL. 
`await page.waitForSelector("aria/Project Info");`

When running the puppeteer inside a docker container I get a `waiting for selector` error.

dockerfile:
```dockerfile

FROM node:12.2.0-alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

RUN apk update && apk add --no-cache nmap && \
    echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories && \
    echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories && \
    apk update && \
    apk add --no-cache \
    chromium \
    harfbuzz \
    "freetype>2.8" \
    ttf-freefont \
    nss

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true

CMD ["npm", "build"]

```

run.js
```js
const browser = await puppeteer.launch({
  executablePath: "/usr/bin/chromium-browser",
  headless: true,
  args: ["--disable-dev-shm-usage", "--no-sandbox", "--disable-gpu"],
});

```

### Puppeteer version

13.0.1

### Node.js version

12.2.0

### npm version

6.9.0

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
TimeoutError: waiting for selector `Project Info` failed: timeout 30000ms exceeded
    at new WaitTask (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:526:34)
    at DOMWorld.waitForSelectorInPage (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:430:26)
    at Object.waitFor (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/AriaQueryHandler.js:62:21)
    at DOMWorld.waitForSelector (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:321:29)
    at Frame.waitForSelector (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:924:51)
    at Page.waitForSelector (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2359:33)
    at genRevisionHomeDocs (/app/src/puppeteer_paths/pages/revisionHome.js:51:14)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async errorWrap (/app/src/puppeteer_paths/error_handling.js:15:5)
    at async /app/src/build-docs.js:74:3 {
  name: 'TimeoutError'
}
```

**Comment by thispsj** [comment]
@sbland exactly !

I just tried to select a radio button using `aria-label` but it failed on GitHub Codespaces (which are in turn Docker containers !). It works fine on my PC.

I also got a `TimeoutError`.

I'm running node `v14.17.6`,npm `v8.3.1` & puppeteer `v13.2.0`

**Update** : I just realized that the webpage has removed aria labels in their radio buttons.
