### ISSUE TITLE
[Bug]:  headful puppeteer randomly crashed with simple code

### ISSUE THREAD

**Issue by SkwalExe** [puppeteer/puppeteer#7993]
### Bug description

# code 
```js
const puppeteer = require('puppeteer');

(async() => {
    const browser = await puppeteer.launch({
        headless: false,
        defaultViewport: null,
    });

    const page = await browser.newPage();

    await page.goto('https://10fastfingers.com/login');
})();
```

# expected behavior
puppeteer should run normaly
# actual behavior
puppeteer crashes after a random amount of time (~10-60 seconds)

Im using arch and the problem is the same on my other pc  

### Puppeteer version

latest

### Node.js version

latest

### npm version

latest

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
/home/skwal/Documents/temp/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:230
                error: new Errors_js_1.ProtocolError(),
                       ^

ProtocolError: Protocol error (Page.createIsolatedWorld): No frame for given id found
    at /home/skwal/Documents/temp/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:230:24
    at new Promise (<anonymous>)
    at CDPSession.send (/home/skwal/Documents/temp/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:226:16)
    at /home/skwal/Documents/temp/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:291:37
    at Array.map (<anonymous>)
    at FrameManager._ensureIsolatedWorld (/home/skwal/Documents/temp/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:291:14)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 1)
    at async FrameManager.initialize (/home/skwal/Documents/temp/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:102:13) {
  originalMessage: 'No frame for given id found'
}

Node.js v17.3.0
```

**Comment by andrevlima** [comment]
Same happening here in many pages

**Comment by andrevlima** [comment]
Hi,
Same happening here in many pages
Here is another example, this is a public site, where the error happens randomly. 
I have tried to rollback to old puppeteer version but I have got not much more success than this.
```js
const puppeteer = require('puppeteer');

(async() => {
    const browser = await puppeteer.launch({
        headless: false,
        defaultViewport: null,
    });

    const page = await browser.newPage();
        
    await page.goto('https://fdownloader.net/pt', {});
    await page.setViewport({
        width: 1920,
        height: 1080,
        deviceScaleFactor: 1,
    });
    await delay(1000);
    console.log("Downloader page open, inserting URL...");
    await page.type('input[name="q"]', facebookVideoUrl, { delay: 0 });
    await page.click('form button[type="button"]');
    console.log("URL submitted for download. Loading download URL...");
    await page.waitForSelector('a[title*="(SD)"]');
    const linkEl = await page.$('a[title*="(SD)"]');
    const downloadLink = await page.evaluate(linkEl => linkEl.getAttribute('href'), linkEl);
    console.log("Generated link: ", downloadLink);
    await page.close();
})();

**Comment by SkwalExe** [comment]
I noticed that this issue doesn't happen  when running headless puppeteer

**Comment by gionot** [comment]
Hi ,
I have the some problem. Anyone expert can help ? Expleain or address di matter ?
many thanks

**Comment by ucarbehlul** [comment]
Similar issue is happening for me:
```
/home/behlul/xyz/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:230
                error: new Errors_js_1.ProtocolError(),
                       ^

ProtocolError: Protocol error (Network.setUserAgentOverride): Target closed.
    at /home/behlul/xyz/node_modules/puppeteer/src/common/Connection.ts:304:16
    at new Promise (<anonymous>)
...
  originalMessage: ''
```

and this causes node to stop execution.

**Comment by OrKoN** [comment]
I am unable to reproduce in v16.0.0. Please give the latest version a try as we reworked the target handing a bit. The original error is very likely to have been caused by out-of-process iframes that were attaching/detaching fast while Puppeteer was trying to send commands to them.  out-of-process iframes are disabled by default in headless and one can disable them in headful too and thats explains the difference.
