### ISSUE TITLE
Error when adding Content-Type Header on POST request using puppeteer

### ISSUE THREAD

**Issue by farhan260** [puppeteer/puppeteer#8004]
### Bug description

I am trying to send a POST request using puppteer and it looks like it is failing with Content-Type header.

```
page.once('request', request => {

    	if (request.method() == "POST") {
	        request.continue({ method: process.argv[2], postData: process.argv[3] }); //, headers: array
	        console.log(request.headers());
    	}
    	else{
    		request.continue({ method: process.argv[2], postData: process.argv[3]});
    		console.log(request.headers());	
        }
    	page.setRequestInterception(false);
    });

    await page.setExtraHTTPHeaders({
  'upgrade-insecure-requests': '1',
  'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.0 Safari/537.36',
  accept: '*/*',
  connection: 'close',
  'accept-encoding': 'gzip, deflate',
  dnt: '1',
  'accept-language': 'en-US,en;q=0.5',
  'x-same-domain': '1',
  'content-type': 'application/x-www-form-urlencoded;charset=utf-8'
});
    
response = await page.goto(String(process.argv[5]));
```

### Puppeteer version

Latest version

### Node.js version

v17.4.0

### npm version

8.4.1

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
{
  'upgrade-insecure-requests': '1',
  'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.0 Safari/537.36',
  accept: '*/*',
  connection: 'close',
  'accept-encoding': 'gzip, deflate',
  dnt: '1',
  'accept-language': 'en-US,en;q=0.5',
  'x-same-domain': '1',
  'content-type': 'application/x-www-form-urlencoded;charset=utf-8'
}
url: https://redacted/_/test/test/test?hl=en, errText: net::ERR_ABORTED, method: GET
/home/kali/Desktop/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:156
                    ? new Error(`${response.errorText} at ${url}`)
                      ^

Error: net::ERR_ABORTED at https://redacted:443/_/test/test/test?hl=en
    at navigate (/home/kali/Desktop/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:156:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async FrameManager.navigateFrame (/home/kali/Desktop/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:130:21)
    at async Frame.goto (/home/kali/Desktop/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:502:16)
    at async Page.goto (/home/kali/Desktop/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1167:16)
    at async /home/kali/Desktop/puppeteer/puppeteer.js:77:16

Node.js v17.4.0
```

**Comment by farhan260** [comment]
I have tried to test it without Content-Type header and it works.
