### ISSUE TITLE
[Bug]: page.setRequestInterception immediate crash under FireFox

### ISSUE THREAD

**Issue by coconutbird** [puppeteer/puppeteer#8057]
### Bug description

Steps to reproduce the problem:

1. create a page
2. call `await page.setRequestInterception(true);`
3. profit?

I noticed this while trying the firefox driver, I'd use the Chrome driver but FireFox passes right through cloudflare.

### Puppeteer version

13.4.0

### Node.js version

16.13.1

### npm version

8.1.2

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
C:\Users\Jon\Documents\GitHub\coconutbird\test-recaptcha-server\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:230
                error: new Errors_js_1.ProtocolError(),
                       ^

ProtocolError: Protocol error (Fetch.enable): Fetch.enable RemoteAgentError@chrome://remote/content/cdp/Error.jsm:29:5
UnknownMethodError@chrome://remote/content/cdp/Error.jsm:112:7
execute@chrome://remote/content/cdp/domains/DomainCache.jsm:98:13
receiveMessage@chrome://remote/content/cdp/sessions/ContentProcessSession.jsm:84:45

    at C:\Users\Jon\Documents\GitHub\coconutbird\test-recaptcha-server\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:230:24
    at new Promise (<anonymous>)
    at CDPSession.send (C:\Users\Jon\Documents\GitHub\coconutbird\test-recaptcha-server\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:226:16)
    at NetworkManager._updateProtocolRequestInterception (C:\Users\Jon\Documents\GitHub\coconutbird\test-recaptcha-server\node_modules\puppeteer\lib\cjs\puppeteer\common\NetworkManager.js:143:30)
    at NetworkManager.setRequestInterception (C:\Users\Jon\Documents\GitHub\coconutbird\test-recaptcha-server\node_modules\puppeteer\lib\cjs\puppeteer\common\NetworkManager.js:133:20)
    at Page.setRequestInterception (C:\Users\Jon\Documents\GitHub\coconutbird\test-recaptcha-server\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:407:52)
    at setupTab (C:\Users\Jon\Documents\GitHub\coconutbird\test-recaptcha-server\src\index.js:40:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async C:\Users\Jon\Documents\GitHub\coconutbird\test-recaptcha-server\src\index.js:147:24 {
  originalMessage: 'Fetch.enable'
}
error Command failed with exit code 1.
```

**Comment by NithinSGowda** [comment]
I'm facing the exact same issue,
Puppeteer version 18.0.0
Firefox version 105.0
