### ISSUE TITLE
[Bug]: Failed to launch the browser process!

### ISSUE THREAD

**Issue by Kisloteny** [puppeteer/puppeteer#8086]
### Bug description

Guys, hello everyone! I'm trying to run a script with a parser in Chromium on the ubuntu 20 server, but for some reason the script does not work, neither in headless mode, nor without it. Log attached, tell me what's the problem?
Already tried to solve the problem with args: ['--disable-gpu', '--disable-setuid-sandbox', '--no-sandbox', '--no-zygote' ] and executablePath

### Puppeteer version

13.4.1

### Node.js version

16.13.2

### npm version

8.1.2

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
Error: Failed to launch the browser process!


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/www/server/project/node_modules/puppeteer-extra/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:237:20)
    at Interface.<anonymous> (/www/server/project/node_modules/puppeteer-extra/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:227:68)
    at Interface.emit (node:events:402:35)
    at Interface.close (node:readline:586:8)
    at Socket.onend (node:readline:277:10)
    at Socket.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
/www/server/project/script_3.js:166
            await browser.close()
            ^

ReferenceError: browser is not defined
    at /www/server/project/script_3.js:166:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by scar0x00** [comment]
Hi!

@EnisBerk found a workaround to this problem:
https://github.com/puppeteer/puppeteer/issues/4991#issuecomment-548614255

**Comment by Kisloteny** [comment]
That doesn't work for me, and I don't know why

**Comment by Kisloteny** [comment]
I don’t know, maybe this is due to the fact that I have the chromium repository in a different folder. The full path is: /snap/chromium/1912/usr/lib/chromium-browser

**Comment by Kisloteny** [comment]
When I try to put executablePath: into the startup code, it starts giving me an error: spawn usr/lib/chromium-browser EACCES

**Comment by Black2vs2** [comment]
Can you share the code?
