### ISSUE TITLE
[Bug]: setPageContent appears to be flaky in utils/doclint/cli.js

### ISSUE THREAD

**Issue by OrKoN** [puppeteer/puppeteer#8112]
### Bug description

Steps to reproduce the problem:

1. Run utils/doclint/cli.js

### Puppeteer version

13.5.0

### Node.js version

16.13.2

### npm version

8.1.2

### What operating system are you seeing the problem on?

macOS

### Relevant log output

```shell
> node utils/doclint/cli.js

/Users/alexrudenko/src/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:107
        return new Promise((fulfill) => (this._maximumTimer = setTimeout(fulfill, this._timeout))).then(() => new Errors_js_1.TimeoutError(errorMessage));
                                                                                                              ^

TimeoutError: Navigation timeout of 30000 ms exceeded
    at /Users/alexrudenko/src/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:107:111
    at async DOMWorld.setContent (/Users/alexrudenko/src/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:152:23)
    at async Page.setContent (/Users/alexrudenko/src/puppeteer/lib/cjs/puppeteer/common/Page.js:1108:9)
    at async Function.create (/Users/alexrudenko/src/puppeteer/utils/doclint/check_public_api/MDBuilder.js:37:5)
    at async module.exports (/Users/alexrudenko/src/puppeteer/utils/doclint/check_public_api/MDBuilder.js:396:21)
    at async lint (/Users/alexrudenko/src/puppeteer/utils/doclint/check_public_api/index.js:47:20)
    at async run (/Users/alexrudenko/src/puppeteer/utils/doclint/cli.js:96:21)
```

**Comment by OrKoN** [comment]
cc @johanbay @mathiasbynens @jrandolf

**Comment by OrKoN** [comment]
Unable to reproduce anymore.
