### ISSUE TITLE
[Bug]: setCookies function not allowing semicolons in value field of the cookie

### ISSUE THREAD

**Issue by JamesDepret** [puppeteer/puppeteer#8130]
### Bug description

Steps to reproduce the problem:

1. Setup a basic project and goto page
2. Add the setCookies function with a cookie that contains a semicolon in the value field ex.
```await page.setCookie({name: 'Cookie', value: 'cookie;test', domain: 'https://www.example.com'});```

Minimal reproducible example:
```JS
const puppeteer = require('puppeteer');
const loginPage = 'https://stackoverflow.com/';

async function login() {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.setCookie({name: 'Cookie', value: 'cookie=test;test=cookie' , domain: 'stackoverflow.com'}); 
    await page.goto(loginPage);
}

login();
```

### Puppeteer version

13.5.0

### Node.js version

16.13.1

### npm version

8.3.2

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
error: new Errors_js_1.ProtocolError(),
       ^

ProtocolError: Protocol error (Network.setCookies): Invalid cookie fields
    at C:\Users\james\OneDrive\Bureaublad\connector\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:230:24
    at new Promise (<anonymous>)
    at CDPSession.send (C:\Users\james\OneDrive\Bureaublad\connector\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:226:16)
    at Page.setCookie (C:\Users\james\OneDrive\Bureaublad\connector\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:772:32)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async loginRequest (C:\Users\james\OneDrive\Bureaublad\connector\connector.js:46:5) {
  originalMessage: 'Invalid cookie fields'
}
```

**Comment by jribbens** [comment]
This is not a bug. Cookie values cannot contain semicolons so the setCookie function is correct to reject it.
