### ISSUE TITLE
[Bug]: $$eval() crashes when passed a function as extra parameter

### ISSUE THREAD

**Issue by RupertBarrow** [puppeteer/puppeteer#8157]
### Bug description

Steps to reproduce the problem:

1. Here is the failing code : 
```
  public async getStringValue_FormatterList(element: ElementHandle, selector: String, formatter: Function): Promise<string[]> {    
    console.log('formatter: ', formatter)
    try {
      return await element.$$eval(selector, (elements: ElementHandle[], func: Function) => {
        console.log('func = ',func)
        return elements.map(func)
      }, formatter)
    } catch (err) {
      console.log('### ERROR : ', err)
      return []
    }
```

Pass the following parameters : 
- element = the current page
- selector = to select a list of items in the page
- formatter = eg ```(el) => el.getAttribute('href')```

### Puppeteer version

13.5.1

### Node.js version

16.13.0

### npm version

8.1.0

### What operating system are you seeing the problem on?

macOS

### Relevant log output

```shell
formatter:  [Function: hrefFormatter]
### ERROR :  Error: Evaluation failed: TypeError: undefined is not a function
    at Array.map (<anonymous>)
    at __puppeteer_evaluation_script__:3:33
    at ExecutionContext._evaluateInternal (/Users/.../node_modules/puppeteer/src/common/ExecutionContext.ts:273:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/Users/.../node_modules/puppeteer/src/common/ExecutionContext.ts:140:12)
    at async JSHandle.evaluate (/Users/.../node_modules/puppeteer/src/common/JSHandle.ts:168:12)
    at async ElementHandle.$$eval (/Users/.../node_modules/puppeteer/src/common/JSHandle.ts:1088:20)
    at async DOMWorld.$$eval (/Users/.../node_modules/puppeteer/src/common/DOMWorld.ts:224:19)
```

**Comment by RupertBarrow** [comment]
What extra input do you need ?
