### ISSUE TITLE
[Bug]: Protocol error (Page.printToPDF) - When headless=false

### ISSUE THREAD

**Issue by JavaScriptDude** [puppeteer/puppeteer#8158]
### Bug description

Steps to reproduce the problem:

1. Get fully updated Ubuntu 20.04.4 LTS (kernel: 5.13.0-37-generic)
2. Follow latest instructions for Puppeteer to install
3. Run simple PDF generating example with headless=false

```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({headless: false});
  const page = await browser.newPage();
  await page.goto('https://example.com');
  await page.pdf({ path: 'example.pdf' });

  await browser.close();
})();
```
Fails at `page.pdf(...)` with `ProtocolError: Protocol error (Page.printToPDF): Printing is not available`.

### Puppeteer version

13.5.1

### Node.js version

17.0.1

### npm version

17.0.1

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
/dpool/vcmain/dev/js/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:230
                error: new Errors_js_1.ProtocolError(),
                       ^

ProtocolError: Protocol error (Page.printToPDF): Printing is not available
    at /dpool/vcmain/dev/js/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:230:24
    at new Promise (<anonymous>)
    at CDPSession.send (/dpool/vcmain/dev/js/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:226:16)
    at Page.createPDFStream (/dpool/vcmain/dev/js/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2074:50)
    at Page.pdf (/dpool/vcmain/dev/js/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2103:37)
    at /dpool/vcmain/dev/js/puppeteer/pdf_test/example.js:7:14
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  originalMessage: 'Printing is not available'
}
```

**Comment by JavaScriptDude** [comment]
I tried un-installing and re-installing `puppeteer`, Tried clearing `~/.config/chromium/` and `~/.cache/chromium/` with no luck.

**Comment by JavaScriptDude** [comment]
I suspect this is something on my system specifically and related to `chromium` but I cannot figure out what the issue is and was hoping if someone on this project may be able to give me some troubleshooting hints.

**Comment by JavaScriptDude** [comment]
This issue is clearly related to Chromium and has existed for some time. I have raised a [ticket](https://bugs.chromium.org/p/chromedriver/issues/detail?id=4070) with Chromium.org.

The resolution for the time being is to run with `headless: true`.
