### ISSUE TITLE
[Bug]: TimeoutError: waiting for selector in headless mode

### ISSUE THREAD

**Issue by coaperator** [puppeteer/puppeteer#8166]
### Bug description

Steps to reproduce the problem:

```
;(async () => {
  const link =
    'https://www.dns-shop.ru/catalog/17a899cd16404e77/processory/?f[mn]=i1wt&p='

  let flag = true
  let res = []
  let counter = 1

  try {
    let browser = await puppeteer.launch({
      // headless: true,
      slowMo: 100,
      devtools: true,
    })
    let page = await browser.newPage()

    await page.setViewport({
      width: 1200,
      height: 1900,
    })

    while (flag) {
      await page.goto(`${link}${counter}`)
      await page.waitForSelector('a.pagination-widget__page-link_next')
      console.log(counter)

      let html = await page.evaluate(
        async () => {
          let pages = []

          try {
            let divs = document.querySelectorAll('div.catalog-product')

            divs.forEach((div) => {
              let a = div.querySelector('a.ui-link')

              let obj = {
                title: a !== null ? a.innerText : 'NO_PRICE',
                link: a.href,
                price:
                  div.querySelector('div.product-buy__price') !== null
                    ? div.querySelector('div.product-buy__price').innerText
                    : 'NO_PRICE',
              }

              pages.push(obj)
            })
          } catch (e) {
            console.log(e)
          }

          return pages
        },
        { waitUntil: 'a.pagination-widget__page-link_next' }
      )

      await res.push(html)

      for (let i in res) {
        if (res[i].length === 0) flag = false
      }

      counter++
    }

    await browser.close()

    res = res.flat()

    console.log(res);
  } catch (e) {
    console.log(e)
  }
})()
```
1. run this
If you set headless: false, then the script works, if you set headless: true, an error appears

### Puppeteer version

13.5.1

### Node.js version

12.22.7

### npm version

6.14.15

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
PS D:\WebProjects\test\bot-parser> node app
TimeoutError: waiting for selector `a.pagination-widget__page-link_next` failed: timeout 30000ms exceeded
    at new WaitTask (D:\WebProjects\test\bot-parser\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:528:34)
    at DOMWorld.waitForSelectorInPage (D:\WebProjects\test\bot-parser\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:432:26)
    at Object.internalHandler.waitFor (D:\WebProjects\test\bot-parser\node_modules\puppeteer\lib\cjs\puppeteer\common\QueryHandler.js:31:77)
    at DOMWorld.waitForSelector (D:\WebProjects\test\bot-parser\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:323:29)
    at Frame.waitForSelector (D:\WebProjects\test\bot-parser\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:942:51)
    at Page.waitForSelector (D:\WebProjects\test\bot-parser\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:2359:33)
    at D:\WebProjects\test\bot-parser\app.js:31:18
    at runNextTicks (internal/process/task_queues.js:62:5)
    at listOnTimeout (internal/timers.js:523:9)
    at processTimers (internal/timers.js:497:7)
```

**Comment by gen4sp** [comment]
same on mac

**Comment by trkyshorty** [comment]
i have the same problem (Mac)

Update:

It is solved when the user agent is defined.

Example:

`await page.setUserAgent('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36')`

**Comment by xgqfrms** [comment]
```js
navigator.userAgent
// 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36'

```

https://ourcodeworld.com/articles/read/1106/how-to-solve-puppeteer-timeouterror-navigation-timeout-of-30000-ms-exceeded

**Comment by srijan009** [comment]
we gotta specify the user agent if headless is set to true (Default its true)
`await page.setUserAgent('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36')`
