### ISSUE TITLE
Downloading puppeteer firefox not working

### ISSUE THREAD

**Issue by Ibexlol** [puppeteer/puppeteer#8215]
### Bug description

How do i fix this? i run PUPPETEER_PRODUCT=firefox npm install it doesn't work for me

### Puppeteer version

v13.5.2

### Node.js version

v17.0.1

### npm version

8.1.0

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
node_modules\images-scraper\node_modules\puppeteer\lib\cjs\puppeteer\node\Launcher.js:79
                throw new Error(missingText);
                      ^

Error: Could not find browser revision 818858. Run "PUPPETEER_PRODUCT=firefox npm install" or "PUPPETEER_PRODUCT=firefox yarn install" to download a supported Firefox browser binary.
    at ChromeLauncher.launch (C:\Users\Administrator\Desktop\Simba\discordbotz\node_modules\images-scraper\node_modules\puppeteer\lib\cjs\puppeteer\node\Launcher.js:79:23)  
    at async GoogleScraper.scrape (C:\Users\Administrator\Desktop\Simba\discordbotz\node_modules\images-scraper\src\google\scraper.js:53:21)
    at async Object.execute (C:\Users\Administrator\Desktop\Simba\discordbotz\commands\image.js:17:31)

PUPPETEER_PRODUCT=firefox : The term 'PUPPETEER_PRODUCT=firefox' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling 
of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ PUPPETEER_PRODUCT=firefox npm install
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (PUPPETEER_PRODUCT=firefox:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by jrandolf-google** [comment]
Please check the documentation carefully.

**Comment by fregante** [comment]
This does not work, Firefox is just not installed:

```sh
$ npm ls puppeteer

webext-dynamic-content-scripts@8.1.1
├─┬ jest-puppeteer@6.1.0
│ └── puppeteer@14.4.0 deduped
└── puppeteer@14.4.0
```

```sh
$ PUPPETEER_PRODUCT=firefox npm install puppeteer -D

up to date, audited 872 packages in 2s

212 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

```sh
$ PUPPETEER_PRODUCT=firefox npm run jest

Error: Jest: Got error running globalSetup - ./node_modules/jest-environment-puppeteer/setup.js,
reason: Could not find expected browser (firefox) locally. Run `PUPPETEER_PRODUCT=firefox npm install` to download a supported Firefox browser binary.
```

For it to work, you have to remove Puppeteer first _and then_ reinstall it. The documentation is incomplete and/or Puppeteer should offer a better way to do this.

Running on:

- node 16.14.2
- npm 8.5.0
- macOS 11.6.7

**Comment by fullstackdeveloper111** [comment]
exactly
