### ISSUE TITLE
[Bug]: Error: Failed to launch the browser process! Command '/usr/bin/chromium-browser' requires the chromium snap to be installed. Please install it with:  snap install chromium

### ISSUE THREAD

**Issue by prakashkandh** [puppeteer/puppeteer#8232]
### Bug description

Steps to reproduce the problem:

1. …
[/workspace/pdf/chrome-aws-lambda:prod.mbmfy20.apps]  # node index.js
Error: Failed to launch the browser process!
Command '/usr/bin/chromium-browser' requires the chromium snap to be installed.
Please install it with:

snap install chromium

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/workspace/pdf/chrome-aws-lambda/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241:20)
    at Interface.<anonymous> (/workspace/pdf/chrome-aws-lambda/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:231:68)
    at Interface.emit (events.js:201:15)
    at Interface.close (readline.js:401:8)
    at Socket.onend (readline.js:178:10)
    at Socket.emit (events.js:201:15)
    at endReadableNT (_stream_readable.js:1130:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:17)

### Puppeteer version

latest

### Node.js version

12

### npm version

6.9.0

### What operating system are you seeing the problem on?

macOS

### Relevant log output

```shell
Error: Failed to launch the browser process!

Command '/usr/bin/chromium-browser' requires the chromium snap to be installed.
Please install it with:

snap install chromium



TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/workspace/pdf/chrome-aws-lambda/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241:20)
    at Interface.<anonymous> (/workspace/pdf/chrome-aws-lambda/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:231:68)
    at Interface.emit (events.js:201:15)
    at Interface.close (readline.js:401:8)
    at Socket.onend (readline.js:178:10)
    at Socket.emit (events.js:201:15)
    at endReadableNT (_stream_readable.js:1130:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:17)
```

**Comment by chathuranga** [comment]
This issue is visible for me on Ubuntu 20.04.4 LTS

**Comment by Mahmoud-Skafi** [comment]
@prakashkandh  any update??

**Comment by rpsene** [comment]
This issue is visible for me on Ubuntu 22.04 LTS

**Comment by rabbygit** [comment]
any update?

**Comment by rajcracker** [comment]
I also facing the same issue in ubuntu 22.04 LTS   

Failed to launch the browser process!\n\nCommand '\/usr\/bin\/chromium-browser' requires the chromium snap to be installed.\nPlease install it with:\n\nsnap install chromium
