### ISSUE TITLE
[Bug]: Error: Protocol error (Target.setAutoAttach): Target closed

### ISSUE THREAD

**Issue by frontHu** [puppeteer/puppeteer#8245]
### Bug description

`
puppeteer.launch({}).then(browser => {
  return browser.pages().then(async (pages) => {
     const page = pages[0]
     ....
     ....
  })
})
`

### Puppeteer version

10.2.0

### Node.js version

14.16.0

### npm version

6.14.11

### What operating system are you seeing the problem on?

macOS

### Relevant log output

```shell
(node:49324) UnhandledPromiseRejectionWarning: Error: Protocol error (Target.setAutoAttach): Target closed.
    at /Users/WoodyHu/Workspace/web_frontend/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:217:63
    at new Promise (<anonymous>)
    at CDPSession.send (/Users/WoodyHu/Workspace/web_frontend/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:216:16)
    at Page._initialize (/Users/WoodyHu/Workspace/web_frontend/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:184:26)
    at Function.create (/Users/WoodyHu/Workspace/web_frontend/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:176:20)
    at /Users/WoodyHu/Workspace/web_frontend/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Target.js:72:88
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:49324) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:49324) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by frontHu** [comment]
m1 chips

**Comment by Kujo-Jotaro-AAAAA** [comment]
+ 1. M1 chips

**Comment by marcelinhov2** [comment]
Also having this problem at AWS Lambda.

**Comment by marcelinhov2** [comment]
I'm guessing it's related to the nodejs version and not with the mac chipset.

**Comment by OrKoN** [comment]
Please try it out with the latest version and re-open if it still happens.
