### ISSUE TITLE
[Bug]: "performance.measureUserAgentSpecificMemory is not available" in headless mode?

### ISSUE THREAD

**Issue by cmdcolin** [puppeteer/puppeteer#8258]
### Bug description

Steps to reproduce the problem:

1. download https://github.com/cmdcolin/express_cross_origin_isolated, used to test cross-origin isolation
2. run node index.js in express_cross_origin_isolated folder to startup server on port 4000
3. run a puppeteer script on public/index.html
4. try running await page.evaluate(() => self.crossOriginIsolated), works and produces true
5. try running await page.evaluate(() => performance.measureUserAgentSpecificMemory()), produces error (see log below)

note: if I use headless:false in the launch params, then it actually does produce a value, but unfortunately the headless:false mode completely grinds my entire system (ubuntu 22.04) to a halt so if this was available in headless mode it would be great

### Puppeteer version

13.6.0

### Node.js version

16.14.2

### npm version

8.5.0

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
/home/cdiesh/src/jb2profile/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: DOMException: Failed to execute 'measureUserAgentSpecificMemory' on 'Performance': performance.measureUserAgentSpecificMemory is not available.
    at __puppeteer_evaluation_script__:2:17
    at ExecutionContext._evaluateInternal (/home/cdiesh/src/jb2profile/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/home/cdiesh/src/jb2profile/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)

```
```

**Comment by cmdcolin** [comment]
note: if this is not a bug or a known limitation, welcome to close. my ultimate aim is to get memory usage stats on a page using webworkers

**Comment by cmdcolin** [comment]
a linked issue above (https://github.com/krausest/js-framework-benchmark/issues/1050) suggests using the flag `--headless=chrome`
