### ISSUE TITLE
[Bug]: Passing a page object to another function in another file does not work

### ISSUE THREAD

**Issue by jlanssie** [puppeteer/puppeteer#8266]
### Bug description

I have a main.js file in which intends to perform several tests, located in other .js files.
The main.js files call the function in the other file and passes the page object into that function. 
But that does not seem to work.

main.js

```
'use strict';
const {puppeteer, URL, fs, variables} = require('./modules.js');
const {login, cookies, test} = require('./scenarios/scenarios.js');
(async() => {
  const browser = await puppeteer.launch({
    headless: false, 
    defaultViewport: null,
  });
  let page = await browser.newPage();
  try {
    test.test(page)
  } catch (err) {
    console.log(err)
  }
  await browser.close();
})();
```

.scenarios/test.js 

```
'use strict';
const {puppeteer, URL, fs, variables} = require('../modules.js');
async function test(page) {
    await page.goto(https://www.example.com, {waitUntil: 'load', timeout: 0});
}
module.exports.test = test
```

### Puppeteer version

Chrome/101.0.4950.0

### Node.js version

17.9.0

### npm version

8.5.5

### What operating system are you seeing the problem on?

macOS

### Relevant log output

```shell
error: new Errors_js_1.ProtocolError(),
                       ^

ProtocolError: Protocol error (Runtime.callFunctionOn): Target closed.
    at /mypath/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:230:24
    at new Promise (<anonymous>)
    at CDPSession.send (/mypath/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:226:16)
    at ExecutionContext._evaluateInternal (/mypath/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:204:50)
    at ExecutionContext.evaluate (/mypath/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:27)
    at DOMWorld.evaluate (/mypath/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:97:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  originalMessage: ''
}
```

**Comment by jlanssie** [comment]
In found a solution. If I change the line in the try block to...

`const test =  await test.test(page)
`

... it works.
