### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by SajadTroy** [puppeteer/puppeteer#8406]
### Bug description

Steps to reproduce the problem:

1. …

### Puppeteer version

1.7.0

### Node.js version

16.15.0

### npm version

1.0.0

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
~/whbot $ npm start

> whbot@1.0.0 start
> node index.js

/data/data/com.termux/files/home/whbot/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26
        throw new Error(message);
              ^

Error: Unsupported platform: android
    at assert (/data/data/com.termux/files/home/whbot/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26:15)
    at BrowserFetcher.setPlatform (/data/data/com.termux/files/home/whbot/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:184:36)
    at new BrowserFetcher (/data/data/com.termux/files/home/whbot/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:168:14)
    at resolveExecutablePath (/data/data/com.termux/files/home/whbot/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:622:28)
    at ChromeLauncher.launch (/data/data/com.termux/files/home/whbot/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:103:53)
    at async Client.initialize (/data/data/com.termux/files/home/whbot/node_modules/whatsapp-web.js/src/Client.js:95:23)
~/whbot $
```

**Comment by jrandolf-google** [comment]
Android is not supported.

**Comment by SajadTroy** [comment]
Ok

**Comment by Mark-Erena** [comment]
😭
