### ISSUE TITLE
Error: Protocol error (Network.enable): Target closed.

### ISSUE THREAD

**Issue by wj-1993** [puppeteer/puppeteer#843]
my code
```
(async() => {

  const browser = await puppeteer.launch({
          args: ['--no-sandbox','--disable-setuid-sandbox'],
          ignoreHTTPSErrors: true
        });
const page = await browser.newPage();
await page.goto('http://www.google.com');
await page.screenshot({path: 'example.png'});

browser.close();
})();
```

Error
```
(node:27335) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Protocol error (Network.enable): Target closed.
(node:27335) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
internal/process.js:188
      throw util._errnoException(err, 'kill');
      ^

Error: kill ESRCH
    at Object._errnoException (util.js:1026:11)
    at process.kill (internal/process.js:188:18)
    at process.killChrome (/home/node/node_modules/puppeteer/lib/Launcher.js:122:19)
    at emitOne (events.js:115:13)
    at process.emit (events.js:210:7)
```

node 8.5.0
CentOS Linux release 7.3.1611 (Core)

**Comment by vsemozhetbyt** [comment]
Does `await browser.close();` help (with the last puppeteer version)?

**Comment by aslushnikov** [comment]
Given the puppeteer 0.11, the following should mitigate all the races:

```js
await page.close();
await browser.close();
```

Feel free to yell here if it doesn't help
