### ISSUE TITLE
[Bug]: Can't run on Replit

### ISSUE THREAD

**Issue by lzhoang2601** [puppeteer/puppeteer#8475]
### Bug description

![image](https://user-images.githubusercontent.com/50077198/172040191-d94e7d57-d4f7-4a04-b6bc-6c741584a890.png)
Code:   let browser = await require('puppeteer').launch({ args: ['--no-sandbox', '--disable-setuid-sandbox'] })
            let page = await browser.newPage()
with nodejs

### Puppeteer version

14.2.1

### Node.js version

v12.22.10

### npm version

6.14.16

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
(node:1525) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
/home/runner/ocbuilder/node_modules/puppeteer/.local-chromium/linux-1002410/chrome-linux/chrome: error while loading shared libraries: libgobject-2.0.so.0: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/runner/ocbuilder/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:247:20)
    at Interface.<anonymous> (/home/runner/ocbuilder/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:240:68)
    at Interface.emit (events.js:326:22)
    at Interface.close (readline.js:416:8)
    at Socket.onend (readline.js:194:10)
    at Socket.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:1525) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1525) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by simonhammes** [comment]
Related (or possibly a duplicate): https://github.com/puppeteer/puppeteer/issues/7322

**Comment by jrandolf** [comment]
Duplicate: #7322
