### ISSUE TITLE
[Bug]: PuppeteerSharp.ProcessException: Failed to launch browser! ailed to create a message-only window: Not enough storage is available to process this command.

### ISSUE THREAD

**Issue by josha1971** [puppeteer/puppeteer#8561]
### Bug description

Steps to reproduce the problem:

I have our setup code like this:
```
private async Task<string> Setup()
{
    var browserFetcher = new BrowserFetcher();
    await browserFetcher.DownloadAsync( BrowserFetcher.DefaultRevision );
    return browserFetcher.GetExecutablePath( BrowserFetcher.DefaultRevision );
}

var executablePath = await Setup();

var options = new LaunchOptions
{
    Headless = true,
    ExecutablePath = executablePath
};
var browser = await Puppeteer.LaunchAsync( options );
```
**We are seeing this error on the LaunchAsync() method:** 
PuppeteerSharp.ProcessException: Failed to launch browser! [66200:57684:0623/193037.056:ERROR:message_window.cc(116)] Failed to create a message-only window: Not enough storage is available to process this command. (0x8)
[66200:57684:0623/193037.427:ERROR:message_window.cc(116)] Failed to create a message-only window: Not enough storage is available to process this command. (0x8)
[66200:57684:0623/193037.438:FATAL:window_impl.cc(149)] Check failed: atom. : The operation completed successfully. (0x0)

The full stack trace is below with the relevant log output.

We are running this inside an Azure Service Fabric cluster. The service we have is running several times a day, and each time it runs, we scrape 4 webpages. The past couple weeks, we've been getting this "Not enough storage" error, but also sometimes we get "Not enough memory" errors too. 

At this point, each time our service is running, we're getting one of these two errors.

We've confirmed several times that our Service Fabric node indeed has plenty of storage space on it. There is other services installed on the node, and everything else is running fine so we are hesitant to think it's related to RAM being low.

Any input would be extremely helpful!

### Puppeteer version

7.0.0

### Node.js version

n/a

### npm version

n/a

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
**Here is the full stack:** 
Caught JobHandler Exception: PuppeteerSharp.ProcessException: Failed to launch browser! [66200:57684:0623/193037.056:ERROR:message_window.cc(116)] Failed to create a message-only window: Not enough storage is available to process this command. (0x8)
[66200:57684:0623/193037.427:ERROR:message_window.cc(116)] Failed to create a message-only window: Not enough storage is available to process this command. (0x8)
[66200:57684:0623/193037.438:FATAL:window_impl.cc(149)] Check failed: atom. : The operation completed successfully. (0x0)
Backtrace:
GetMainTargetServices [0x00007FFDEE1AC262+1161602]
GetMainTargetServices [0x00007FFDEE120892+589746]
GetMainTargetServices [0x00007FFDEE131027+657223]
GetMainTargetServices [0x00007FFDEE131E7C+660892]
GetMainTargetServices [0x00007FFDEE132170+661648]
GetHandleVerifier [0x00007FFDEF01E2E2+1213106]
GetHandleVerifier [0x00007FFDEF01E928+1214712]
GetHandleVerifier [0x00007FFDEF01E640+1213968]
GetHandleVerifier [0x00007FFDEF197B38+2759432]
GetHandleVerifier [0x00007FFDEF1978CD+2758813]
GetMainTargetServices [0x00007FFDEE4DA7C6+4497126]
ovly_debug_event [0x00007FFDEC763A79+23401145]
ovly_debug_event [0x00007FFDEC7641AA+23402986]
ovly_debug_event [0x00007FFDEC281851+18280593]
ovly_debug_event [0x00007FFDEC284AC1+18293505]
ovly_debug_event [0x00007FFDEC28098B+18276811]
ovly_debug_event [0x00007FFDECE95B8F+30946255]
ovly_debug_event [0x00007FFDECE96DB5+30950901]
ovly_debug_event [0x00007FFDECE968DB+30949659]
ovly_debug_event [0x00007FFDECE953EF+30944303]
ovly_debug_event [0x00007FFDECE957C5+30945285]
ChromeMain [0x00007FFDEB111294+500]
GetPakFileHashes [0x00007FF6ED0926ED+5869]
GetPakFileHashes [0x00007FF6ED091A8D+2701]
GetHandleVerifier [0x00007FF6ED1F57A2+949714]
BaseThreadInitThunk [0x00007FFF0C8484D4+20]
RtlUserThreadStart [0x00007FFF0F27E8B1+33]
Crash keys:
"io_scheduler_async_stack" = "0x7FFDEC0E6E4D 0x0"
"variations" = "8d569531-27a0c3c6,69d4ebd5-3f4a17df,da493d3c-3f4a17df,"
"num-experiments" = "3"
"switch-27" = "about:blank"
"switch-26" = "--user-data-dir=D:\temp\folder\where\chrome\is\chrome.exe"
"switch-25" = "--remote-debugging-port=0"
"switch-24" = "--enable-blink-features=IdleDetection"
"switch-23" = "--use-mock-keychain"
"switch-22" = "--password-store=basic"
"switch-21" = "--enable-automation"
"switch-20" = "--no-first-run"
"switch-19" = "--metrics-recording-only"
"switch-18" = "--force-color-profile=srgb"
"switch-17" = "--disable-sync"
"switch-16" = "--disable-renderer-backgrounding"
"switch-15" = "--disable-prompt-on-repost"
"switch-14" = "--disable-popup-blocking"
"switch-13" = "--disable-ipc-flooding-protection"
"switch-12" = "--disable-hang-monitor"
"switch-11" = "--disable-features=Translate"
"switch-10" = "--disable-extensions"
"switch-9" = "--disable-dev-shm-usage"
"switch-8" = "--disable-default-apps"
"switch-7" = "--disable-component-extensions-with-background-pages"
"switch-6" = "--disable-client-side-phishing-detection"
"switch-5" = "--disable-breakpad"
"switch-4" = "--disable-backgrounding-occluded-windows"
"switch-3" = "--disable-background-timer-throttling"
"switch-2" = "--enable-features=NetworkService,NetworkServiceInProcess"
"switch-1" = "--disable-background-networking"
"num-switches" = "27"

at PuppeteerSharp.States.ChromiumStartingState.StartCoreAsync(LauncherBase p) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\States\ChromiumStartingState.cs:line 98
at PuppeteerSharp.States.ChromiumStartingState.StartCoreAsync(LauncherBase p) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\States\ChromiumStartingState.cs:line 98
at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Launcher.cs:line 93
at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Launcher.cs:line 93
at ....:line 67 _**(line 67 is the LaunchAsync() call defined above)**_
```

**Comment by OrKoN** [comment]
Hey, did you mean to file this bug to the puppeteer-sharp repository? https://github.com/hardkoded/puppeteer-sharp

I think there is not much we can do on the Puppeteer side: the error is thrown by Chromium and it looks like either there is no enough memory or disk space. I could not find the error message in the Chromium codebase so it looks like it's a Windows-specific error returned by some system calls. I'd suggest trying to run on a system with a plenty of disk storage and plenty of RAM as I am not sure which kind of storage the error refers too. Alternatively, you could file an issue to crbug.com so that Chromium team could see if there is a Windows-specific issue here.

/cc @kblok
