### ISSUE TITLE
End gracefully waitForFunction

### ISSUE THREAD

**Issue by giacomocerquone** [puppeteer/puppeteer#859]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.11.0
* Platform / OS version: Win 10 1607

**What steps will reproduce the problem?**

Doing `await page.waitForFunction('condition', {timeout: 1000});` after 1 second my script crashes with an error, but I'd like to handle it in order to do more in my code.

I tried this, but doesn't work:
```javascript
try {
  await page.waitForFunction('condition', {timeout: 1000});
} catch (err) {
  console.log(err);
}
```

**Comment by vsemozhetbyt** [comment]
I cannot reproduce with this code and puppeteer v0.12.0-alpha:
```js
'use strict';

const puppeteer = require('puppeteer');

puppeteer.launch().then(async browser => {
  const page = await browser.newPage();
  try {
    await page.waitForFunction('document.querySelector("div")', {timeout: 1000});
  } catch (err) {
    console.log(err);
  }
  console.log('I am here.');

  await browser.close();
});
```
```console
Error: waiting failed: timeout 1000ms exceeded
    at Timeout.WaitTask._timeoutTimer.setTimeout (puppeteer\lib\FrameManager.js:468:58)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
I am here.
```

**Comment by aslushnikov** [comment]
@giacomocerquone what kind of error do you get?

**Comment by aslushnikov** [comment]
Closing this due to inactivity.
