### ISSUE TITLE
[Bug]: My Docker Puppeteer is not working.

### ISSUE THREAD

**Issue by Jeffr-K** [puppeteer/puppeteer#8641]
### Bug description

I don't understand why my puppeteer on docker is not working..

Here is my Environment: [Stack over flow: my question](https://stackoverflow.com/questions/72892398/my-puppeteer-not-working-on-docker-container)

In result, my dockerfile or environment is not setup correctly. 

how do I re-setup for working puppeteer on docker??

### Puppeteer version

15.3.1

### Node.js version

18.4.0

### npm version

8.12.1

### What operating system are you seeing the problem on?

macOS

### Relevant log output

```shell
node-test | ProtocolError: Protocol error (Target.createTarget): Target closed.
node-test |     at /usr/src/app/node_modules/puppeteer/src/common/Connection.ts:119:16
node-test |     at new Promise (<anonymous>)
node-test |     at Connection.send (/usr/src/app/node_modules/puppeteer/src/common/Connection.ts:115:12)
node-test |     at Browser._createPageInContext (/usr/src/app/node_modules/puppeteer/src/common/Browser.ts:525:47)
node-test |     at BrowserContext.newPage (/usr/src/app/node_modules/puppeteer/src/common/Browser.ts:886:26)
node-test |     at Browser.newPage (/usr/src/app/node_modules/puppeteer/src/common/Browser.ts:518:33)
node-test |     at crawler (/usr/src/app/src/crawler/crawler.ts:16:30)
node-test |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
node-test |     at async CrawlerController (/usr/src/app/src/crawler/crawler.controller.ts:10:5) {
node-test |   originalMessage: ''
node-test | }
```

**Comment by OrKoN** [comment]
We are currently working on the official Docker image for Puppeteer. In the meantime, please consult the troubleshooting guide to see if Docker is set-up correctly: https://pptr.dev/troubleshooting#running-puppeteer-in-docker

Also, note that M1 CPUs are not supported by Puppeteer yet as GitHub actions don't support them.

**Comment by Jeffr-K** [comment]
@OrKoN Thank you for advise for me.

Yes. I figured out another error messages.

```
node-test | [0707/075106.082855:ERROR:stack_trace_posix.cc(707)] Failed to parse the contents of /proc/self/maps
node-test | [0707/075106.661227:ERROR:stack_trace_posix.cc(707)] Failed to parse the contents of /proc/self/maps
node-test | [0707/075106.662826:ERROR:stack_trace_posix.cc(707)] Failed to parse the contents of /proc/self/maps
node-test | [0707/075106.689034:FATAL:zygote_main_linux.cc(162)] Check failed: sandbox::ThreadHelpers::IsSingleThreaded(). 
node-test | #0 0x00400744cdc9 <unknown>
node-test | #1 0x0040073c0a43 <unknown>
node-test | #2 0x0040073bdb90 <unknown>
node-test | #3 0x0040073be78e <unknown>
node-test | #4 0x004006f2e6c6 <unknown>
node-test | #5 0x004006f2922e <unknown>
node-test | #6 0x004006f29f39 <unknown>
node-test | #7 0x004006f2acbc <unknown>
node-test | #8 0x004006f27e8e <unknown>
node-test | #9 0x004006f2884e <unknown>
node-test | #10 0x004006f8299a <unknown>
node-test | #11 0x004006f82853 <unknown>
node-test | #12 0x004006f814a5 <unknown>
node-test | #13 0x0040037481e3 <unknown>
node-test | #14 0x0040104e509b <unknown>
node-test | #15 0x00400374802a <unknown>
node-test | 
node-test | qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
node-test | [0707/075106.690282:FATAL:zygote_main_linux.cc(162)] Check failed: sandbox::ThreadHelpers::IsSingleThreaded(). 
node-test | #0 0x00400744cdc9 <unknown>
node-test | #1 0x0040073c0a43 <unknown>
node-test | #2 0x0040073bdb90 <unknown>
node-test | #3 0x0040073be78e <unknown>
node-test | #4 0x004006f2e6c6 <unknown>
node-test | #5 0x004006f2922e <unknown>
node-test | #6 0x004006f29f39 <unknown>
node-test | #7 0x004006f2acbc <unknown>
node-test | #8 0x004006f27e8e <unknown>
node-test | #9 0x004006f2884e <unknown>
node-test | #10 0x004006f8299a <unknown>
node-test | #11 0x004006f82853 <unknown>
node-test | #12 0x004006f814a5 <unknown>
node-test | #13 0x0040037481e3 <unknown>
node-test | #14 0x0040104e509b <unknown>
node-test | #15 0x00400374802a <unknown>
node-test | 
node-test | qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
node-test | [0707/075107.774313:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
node-test | [0707/075107.776487:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
node-test | [0707/075107.783271:ERROR:file_path_watcher_inotify.cc(329)] inotify_init() failed: Function not implemented (38)
node-test | 
node-test | DevTools listening on ws://127.0.0.1:36711/devtools/browser/71400440-43fe-48ae-af3a-474f1f66d8fa
node-test | [0707/075107.929655:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
node-test | [0707/075107.942542:ERROR:gpu_process_host.cc(960)] GPU process launch failed: error_code=1002
node-test | [0707/075107.943661:WARNING:gpu_process_host.cc(1268)] The GPU process has crashed 1 time(s)
node-test | [0707/075108.253078:ERROR:gpu_process_host.cc(960)] GPU process launch failed: error_code=1002
node-test | [0707/075108.253269:WARNING:gpu_process_host.cc(1268)] The GPU process has crashed 2 time(s)
node-test | [0707/075108.299292:INFO:render_frame_host_impl.cc(11595)] RenderFrameHostImpl::MaybeGenerateCrashReport url = , status = 5, exit_code = 1002
node-test | [0707/075108.312024:ERROR:gpu_process_host.cc(960)] GPU process launch failed: error_code=1002
node-test | [0707/075108.312177:WARNING:gpu_process_host.cc(1268)] The GPU process has crashed 3 time(s)
node-test | [0707/075108.335037:ERROR:gpu_process_host.cc(960)] GPU process launch failed: error_code=1002
node-test | [0707/075108.335234:WARNING:gpu_process_host.cc(1268)] The GPU process has crashed 4 time(s)
node-test | [0707/075108.344576:ERROR:gpu_process_host.cc(960)] GPU process launch failed: error_code=1002
node-test | [0707/075108.344669:WARNING:gpu_process_host.cc(1268)] The GPU process has crashed 5 time(s)
node-test | [0707/075108.349927:ERROR:gpu_process_host.cc(960)] GPU process launch failed: error_code=1002
node-test | [0707/075108.349996:WARNING:gpu_process_host.cc(1268)] The GPU process has crashed 6 time(s)
node-test | [0707/075108.350065:FATAL:gpu_data_manager_impl_private.cc(451)] GPU process isn't usable. Goodbye.
node-test | #0 0x00400744cdc9 <unknown>
node-test | #1 0x0040073c0a43 <unknown>
node-test | #2 0x0040073bdb90 <unknown>
node-test | #3 0x004004ed3b67 <unknown>
node-test | #4 0x004004ed13ee <unknown>
node-test | #5 0x004004ecff53 <unknown>
node-test | #6 0x004004eda95e <unknown>
node-test | #7 0x004004edbb14 <unknown>
node-test | #8 0x004004d3a5c1 <unknown>
node-test | #9 0x004004d97c55 <unknown>
node-test | #10 0x004004d97e75 <unknown>
node-test | #11 0x0040074093d0 <unknown>
node-test | #12 0x00400741cfdc <unknown>
node-test | #13 0x00400741cb8d <unknown>
node-test | #14 0x00400741d552 <unknown>
node-test | #15 0x0040073c753b <unknown>
node-test | #16 0x00400f080fee <unknown>
node-test | #17 0x00400f081288 <unknown>
node-test | #18 0x00400f08131c <unknown>
node-test | #19 0x0040073c7367 <unknown>
node-test | #20 0x00400741d7d6 <unknown>
node-test | #21 0x0040073e6b0d <unknown>
node-test | #22 0x004004d52e1d <unknown>
node-test | #23 0x004004d54662 <unknown>
node-test | #24 0x00400ccecabe <unknown>
node-test | #25 0x004006f29bb2 <unknown>
node-test | #26 0x004006f2b14a <unknown>
node-test | #27 0x004006f2ace0 <unknown>
node-test | #28 0x004006f27e8e <unknown>
node-test | #29 0x004006f2884e <unknown>
node-test | #30 0x004006f8299a <unknown>
node-test | #31 0x004006f826a5 <unknown>
node-test | #32 0x0040037481e3 <unknown>
node-test | #33 0x0040104e509b <unknown>
node-test | #34 0x00400374802a <unknown>
node-test | Task trace:
node-test | #0 0x004004d97b0c <unknown>
node-test | #1 0x004004d97509 <unknown>
node-test | #2 0x004007784cf6 <unknown>
node-test | #3 0x004007784cf6 <unknown>
node-test | #4 0x004007784cf6 <unknown>
node-test | Task trace buffer limit hit, update PendingTask::kTaskBacktraceLength to increase.
node-test | 
node-test | qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
node-test | ProtocolError: Protocol error (Target.createTarget): Target closed.
node-test |     at /node_modules/puppeteer/src/common/Connection.ts:119:16
node-test |     at new Promise (<anonymous>)
node-test |     at Connection.send (/node_modules/puppeteer/src/common/Connection.ts:115:12)
node-test |     at Browser._createPageInContext (/node_modules/puppeteer/src/common/Browser.ts:525:47)
node-test |     at BrowserContext.newPage (/node_modules/puppeteer/src/common/Browser.ts:886:26)
node-test |     at Browser.newPage (/node_modules/puppeteer/src/common/Browser.ts:518:33)
node-test |     at crawler (/src/crawler/crawler.ts:17:30)
node-test |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
node-test |     at async CrawlerController (/src/crawler/crawler.controller.ts:10:5) {
node-test |   originalMessage: ''
node-test | }
mongo    | {"t":{"$date":"2022-07-07T07:51:42.672+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"Checkpointer","msg":"WiredTiger message","attr":{"message":"[1657180302:672686][1:0xffffa1a7ed00], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 3, snapshot max: 3 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write 
```

```
const browser = await puppeteer.launch({
    dumpio: true,
    headless: true,
    "args": [
      '--disable-setuid-sandbox', '--no-sandbox',
      '--disable-gpu']
  })
```

```
FROM node:14-slim

RUN apt-get update \
    && apt-get install -y wget gnupg \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

RUN npm init -y &&  \
    npm i puppeteer \
    # Add user so we don't need --no-sandbox.
    # same layer as npm install to keep re-chowned files from using up several hundred MBs more space
    && groupadd -r pptruser && useradd -r -g pptruser -G audio,video pptruser \
    && mkdir -p /home/pptruser/Downloads \
    && chown -R pptruser:pptruser /home/pptruser \
    && chown -R pptruser:pptruser /node_modules \
    && chown -R pptruser:pptruser /package.json \
    && chown -R pptruser:pptruser /package-lock.json

USER pptruser

COPY package*.json ./

RUN npm install

COPY . .

#RUN #sudo npm run build

EXPOSE 8010

CMD ["npm", "run", "start:dev"]

```

I'm tracing the error, but it's not easy to debug. How can I find any clues that might solve this problem?? Thank you for your hard working!
