### ISSUE TITLE
[Bug]: puppeteer@15.3.2 cannot take screenshot when set viewport as null 

### ISSUE THREAD

**Issue by suym796** [puppeteer/puppeteer#8673]
### Bug description

Steps to reproduce the problem:

1. Launch the browser by ```await puppeteer.launch({ defaultViewport: null })```
2. Get the elementHandle by ```await page.$(selector)```
3. Run ```await elementHandle.screenshot()```
4. Throw an error, which point to the null viewport 

But when I use puppeteer@13.7.0, it works.

### Puppeteer version

15.3.2

### Node.js version

16.15.1

### npm version

8.11.0

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
{}
       Error
           at assert (file:///d:/workdir/Projects/Cloud%20E2E/cloud-e2e-testing-template/node_modules/puppeteer/lib/esm/puppeteer/common/assert.js:25:15)
           at ElementHandle.screenshot (file:///d:/workdir/Projects/Cloud%20E2E/cloud-e2e-testing-template/node_modules/puppeteer/lib/esm/puppeteer/common/ElementHandle.js:562:9)
           at runMicrotasks (<anonymous>)
           at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by pecampelo** [comment]
I don't know what you are aiming at with using viewport defined as null, could you explain a bit further? Seems a bit odd to want a screenshot of a null-defined viewport, since the screenshot takes into account the viewport size.
