### ISSUE TITLE
Puppeteer & Docker Microservice: Upgrade from Node 12 to Node 16

### ISSUE THREAD

**Issue by barry-thierno** [puppeteer/puppeteer#8711]
### Bug description

I have a cluster application that has **Puppeteer** on it. Here is the original configuration:

Container: `node:12-alpine`

In Node microservice: `Puppeteer "^13.5.1", from package.json` 

I've done a migration to **Node 16** from my container `(node:16-alpine)`. 
Since this migration, our container crashes often (1 time on average per hour) with error

```
31m2022-07-28T06:51:26.744Z [error]:  ProtocolError: Protocol error (Target.createTarget): Target closed. -- traceId=f99faabaceb68869←[39m
    [31m2022-07-28T06:51:26.786Z [error]:  ProtocolError: Protocol error (Target.createTarget): Target closed. -- stack=ProtocolError: Protocol error (Target.createTarget): Target closed.←[39m
    [31m    at /opt/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:75:24←[39m
    [31m    at new Promise (<anonymous>)←[39m
    [31m    at Connection.send (/opt/app/node_modules/puppeteer/lib/cjs/puppete... traceId=f99faabaceb68869←[39m
    [32m2022-07-28T06:51:26.834Z [info]:   [Reply]: POST /basics 500 81 - 247ms -- logKind=legoReply method=POST url=/basics status=500 contentLength=81 duration=247 pendingAnswers=0 storeId=605 requestKind=BASIC countryCode=FR clientApp=CubeInStore localesCount=1 destination=gcp requestsNbr=8 signageNbr=8 signageTypes=A5,A7,PE paperFormats=A5,A7,PE paper_A5=1 paper_A7=6 paper_PE=1 signage_A5=1 signage_A7=6 signage_PE=1 traceId=f99faabaceb68869←[39m
    [31m2022-07-28T06:51:26.855Z [error]:  uncaughtException: Protocol error (Target.createTarget): Target closed.←[39m
    [31mProtocolError: Protocol error (Target.createTarget): Target closed.←[39m
    [31m    at /opt/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:75:24←[39m
    [31m    at new Promise (<anonymous>)←[39m
    [31m    at Connection.send (/opt/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:71:16)←[39m
    [31m    at Browser._createPageInContext (/opt/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Browser.js:274:53)←[39m
    [31m    at BrowserContext.newPage (/opt/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Browser.js:553:30)←[39m
    [31m    at Browser.newPage (/opt/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Browser.js:267:37)←[39m
    [31m    at puppeteerOpenPage (/opt/app/services/browser.js:134:20)←[39m
    [31m    at /opt/app/utils/functionTimers.js:73:33←[39m
    [31m    at acquire.maxPending (/opt/app/services/browser.js:140:40)←[39m
    [31m    at /opt/app/utils/concurrency/lock.js:148:24 -- error=ProtocolError: Protocol error (Target.createTarget): Target closed. stack=ProtocolError: Protocol error (Target.createTarget): Target closed.←[39m
    [31m    at /opt/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:75:24←[39m
    [31m    at new Promise (<anonymous>)←[39m
    [31m    at Connection.send (/opt/app/node_modules/puppeteer/lib/cjs/puppete..
```

### Puppeteer version

13.5.1

### Node.js version

v16.16.0 through node:16-alpine

### npm version

8.11.0

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
[31m2022-07-28T06:51:26.744Z [error]:  ProtocolError: Protocol error (Target.createTarget): Target closed. -- traceId=f99faabaceb68869←[39m
    [31m2022-07-28T06:51:26.786Z [error]:  ProtocolError: Protocol error (Target.createTarget): Target closed. -- stack=ProtocolError: Protocol error (Target.createTarget): Target closed.←[39m
    [31m    at /opt/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:75:24←[39m
    [31m    at new Promise (<anonymous>)←[39m
    [31m    at Connection.send (/opt/app/node_modules/puppeteer/lib/cjs/puppete... traceId=f99faabaceb68869←[39m
    [32m2022-07-28T06:51:26.834Z [info]:   [Reply]: POST /basics 500 81 - 247ms -- logKind=legoReply method=POST url=/basics status=500 contentLength=81 duration=247 pendingAnswers=0 storeId=605 requestKind=BASIC countryCode=FR clientApp=CubeInStore localesCount=1 destination=gcp requestsNbr=8 signageNbr=8 signageTypes=A5,A7,PE paperFormats=A5,A7,PE paper_A5=1 paper_A7=6 paper_PE=1 signage_A5=1 signage_A7=6 signage_PE=1 traceId=f99faabaceb68869←[39m
    [31m2022-07-28T06:51:26.855Z [error]:  uncaughtException: Protocol error (Target.createTarget): Target closed.←[39m
    [31mProtocolError: Protocol error (Target.createTarget): Target closed.←[39m
    [31m    at /opt/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:75:24←[39m
    [31m    at new Promise (<anonymous>)←[39m
    [31m    at Connection.send (/opt/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:71:16)←[39m
    [31m    at Browser._createPageInContext (/opt/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Browser.js:274:53)←[39m
    [31m    at BrowserContext.newPage (/opt/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Browser.js:553:30)←[39m
    [31m    at Browser.newPage (/opt/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Browser.js:267:37)←[39m
    [31m    at puppeteerOpenPage (/opt/app/services/browser.js:134:20)←[39m
    [31m    at /opt/app/utils/functionTimers.js:73:33←[39m
    [31m    at acquire.maxPending (/opt/app/services/browser.js:140:40)←[39m
    [31m    at /opt/app/utils/concurrency/lock.js:148:24 -- error=ProtocolError: Protocol error (Target.createTarget): Target closed. stack=ProtocolError: Protocol error (Target.createTarget): Target closed.←[39m
    [31m    at /opt/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:75:24←[39m
    [31m    at new Promise (<anonymous>)←[39m
    [31m    at Connection.send (/opt/app/node_modules/puppeteer/lib/cjs/puppete..
```

**Comment by OrKoN** [comment]
Have you followed the troubleshooting guide for running in Docker? https://pptr.dev/troubleshooting#running-on-alpine

**Comment by barry-thierno** [comment]
Hello 

> Have you followed the troubleshooting guide for running in Docker? https://pptr.dev/troubleshooting#running-on-alpine

Yes. I just check and I noticed that there are some dependencies (Debian) that we are missing. 
Could this explain the reboot of our container ?

**Comment by OrKoN** [comment]
@barry-thierno I think the reboot of the contains is completely up to your set up: e.g., perhaps it's running out of memory or disk space, or perhaps the main process crashes for some reason. Sudden errors about the target being closed during the creation usually indicate some resource-related problem.
