### ISSUE TITLE
[Bug]: Puppeteer not launching Chrome, missing libgbm

### ISSUE THREAD

**Issue by markhowellsmead** [puppeteer/puppeteer#8746]
### Bug description

Attempting to start a browser instance crashes the Docker process with the message “_error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory_”. `libgbm` is installed during the Docker process and is available.

### Puppeteer version

16.0.0

### Node.js version

16.16.0

### npm version

6.14.4

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
pdf-machine_1  | /usr/src/pdf-machine/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:289
pdf-machine_1  |             reject(new Error([
pdf-machine_1  |                    ^
pdf-machine_1  | 
pdf-machine_1  | Error: Failed to launch the browser process!
pdf-machine_1  | /usr/src/pdf-machine/node_modules/puppeteer/.local-chromium/linux-1011831/chrome-linux/chrome: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory
pdf-machine_1  | 
pdf-machine_1  | 
pdf-machine_1  | TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
pdf-machine_1  | 
pdf-machine_1  |     at onClose (/usr/src/pdf-machine/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:289:20)
pdf-machine_1  |     at Interface.<anonymous> (/usr/src/pdf-machine/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:277:24)
pdf-machine_1  |     at Interface.emit (node:events:539:35)
pdf-machine_1  |     at Interface.close (node:readline:586:8)
pdf-machine_1  |     at Socket.onend (node:readline:277:10)
pdf-machine_1  |     at Socket.emit (node:events:539:35)
pdf-machine_1  |     at endReadableNT (node:internal/streams/readable:1345:12)
pdf-machine_1  |     at processTicksAndRejections (node:internal/process/task_queues:83:21)
docker_pdf-machine_1 exited with code 1
```

**Comment by markhowellsmead** [comment]
(Suggested fixes from the previous Github issues haven't made any differences.)

**Comment by markhowellsmead** [comment]
See also https://github.com/puppeteer/puppeteer/issues/5704 https://github.com/puppeteer/puppeteer/issues/5891

**Comment by OrKoN** [comment]
Do you use the official docker image?

**Comment by markhowellsmead** [comment]
Yes. We've done some more extensive testing and it appears that the container was somehow corrupted. Setting up a new container with the same code appears to work with no issues.
