### ISSUE TITLE
[Bug]: Invalid parameters Failed to deserialize params.url

### ISSUE THREAD

**Issue by likaiweb** [puppeteer/puppeteer#8815]
### Bug description

Steps to reproduce the problem:

Error: Protocol error (Page.navigate): Invalid parameters Failed to deserialize params.url - BINDINGS: mandatory field missing at position 49
2022-08-19 15:34:25        at /data/node/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:208:63
2022-08-19 15:34:25        at new Promise (<anonymous>)
2022-08-19 15:34:25        at CDPSession.send (/data/node/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:207:16)
2022-08-19 15:34:25        at navigate (/data/node/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:108:47)
2022-08-19 15:34:25        at FrameManager.navigateFrame (/data/node/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:91:13)
2022-08-19 15:34:25        at Frame.goto (/data/node/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:416:41)
2022-08-19 15:34:25        at Page.goto (/data/node/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:789:53)

**but, my url is a string!**

### Puppeteer version

8.0.0

### Node.js version

16.15.1

### npm version

8.11.0

### What operating system are you seeing the problem on?

Linux

**Comment by OrKoN** [comment]
Please provide an executable script to reproduce the issue.

**Comment by likaiweb** [comment]
try {
      browser = await puppeteer.launch({
        // executablePath: '/usr/bin/chromium',
        // executablePath: '/chrome-linux/chrome',
        headless: true,
        args: [ '--no-sandbox' ],
        ignoreDefaultArgs: [ '--disable-extensions' ],
        // args: [ '--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage', '--single-process' ],
      })
      console.log('brower创建完成')
      const page = await browser.newPage()

      page.once('load', () => console.log('Page loaded!'))
      page.on('error', err => console.log(err))
      // options.isMobile
      //   ? await page.setUserAgent(options.userAgent)
      //   : await page.setCookie(options.cookie)

      await page.goto(options.url)

      return browser
    } catch (error) {
      console.log(error)
    }

and brower creat success。

**Comment by OrKoN** [comment]
where is `options.url` defined?

**Comment by doneber** [comment]
For some reason that I don't understand yet, the problem was the variable name (yes, it doesn't make sens) passed to the method (`page.goto(...)`)
This don't work:
```js
await page.goto(project.homepage)
```
but this yes:
```js
await page.goto(project.homepage_url)
```
