### ISSUE TITLE
[Bug]: Using an external function inside `page.evaluate` doesn't work

### ISSUE THREAD

**Issue by babakfp** [puppeteer/puppeteer#8853]
### Bug description

I just want to have a few function inside another file (DOM functions) and use them inside Puppeteer.

File `src/helpers/product/index.js`:

```javascript
export const get_card_data = ( card_node ) =>
{
	const title = card_node.querySelector('.css-n55ojx')?.textContent

	return {
		title,
	}
}
```

File `src/test.js`:

```javascript
import puppeteer from 'puppeteer'
import { launch_method_args } from './helpers/puppeteer.js'
import { get_card_data } from './helpers/product/index.js'

const browser = await puppeteer.launch(launch_method_args)
const page = await browser.newPage()
await page.setCacheEnabled(false)
await page.goto('https://store.epicgames.com/en-US/browse?sortBy=releaseDate&sortDir=DESC&tag=August%20Event%20Sale&category=Game&count=40&start=0', { waitUntil: 'load' })

await page.exposeFunction('get_card_data', get_card_data)

await page.evaluate(async () => {
	const data = await get_card_data(
		document.querySelector('.css-lrwy1y')
	)
	await console.log(data)
})

// await browser.close()
```

### Puppeteer version

16.2.0

### Node.js version

16.16.0

### npm version

8.15.0

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
PS C:\Users\babak\Desktop\EpicGames\epicgames-webscraper> node src/test
file:///C:/Users/babak/Desktop/EpicGames/epicgames-webscraper/node_modules/.pnpm/puppeteer@16.2.0/node_modules/puppeteer/lib/esm/puppeteer/common/ExecutionContext.js:267   
        throw new Error('Evaluation failed: ' + getExceptionMessage(exceptionDetails));
              ^

Error: Evaluation failed: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'HTMLLIElement'
    |     property '__reactFiber$d67mbk6punn' -> object with constructor 'Ai'
    --- property 'stateNode' closes the circle
    at JSON.stringify (<anonymous>)
    at win.<computed> (pptr://__puppeteer_evaluation_script__:19:26)
    at pptr://__puppeteer_evaluation_script__:2:21
    at ExecutionContext._ExecutionContext_evaluate (file:///C:/Users/babak/Desktop/EpicGames/epicgames-webscraper/node_modules/.pnpm/puppeteer@16.2.0/node_modules/puppeteer/lib/esm/puppeteer/common/ExecutionContext.js:267:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (file:///C:/Users/babak/Desktop/EpicGames/epicgames-webscraper/node_modules/.pnpm/puppeteer@16.2.0/node_modules/puppeteer/lib/esm/puppeteer/common/ExecutionContext.js:115:16)
    at async file:///C:/Users/babak/Desktop/EpicGames/epicgames-webscraper/src/test.js:12:1
PS C:\Users\babak\Desktop\EpicGames\epicgames-webscraper>
```

**Comment by OrKoN** [comment]
That is not expected to work because Puppeteer needs serializable functions: the functions are stringified and evaluated in the page context. You'd need to bundle all of the code inside the evaluated function, either manually or using tools like rollup or use the `exposeFunction` mechanism: https://pptr.dev/next/api/puppeteer.page.exposefunction.

**Comment by babakfp** [comment]
Hi
I'm talking about using DOM functions and etc. DOM stuff doesn't work with `page.exposeFunction()`.

`a-file.js`:

```javascript
export const hello_world = () => 'Hello, World!'
```

`app.js`:

```javascript
import puppeteer from 'puppeteer'
import { launch_method_args } from './helpers/puppeteer.js'
import { hello_world } from './a-file.js'

const browser = await puppeteer.launch(launch_method_args)
const page = await browser.newPage()
await page.goto('https://store.epicgames.com/en-US/browse?sortBy=releaseDate&sortDir=DESC&tag=August%20Event%20Sale&category=Game&count=40&start=0', { waitUntil: 'load' })

await page.exposeFunction('hello_world', hello_world)

await page.evaluate(async () => {
  const data = await window.hello_world()
  console.log(data)
})
```

This👆 works. But this doesn't work:

`a-file.js`:

```javascript
export const get_card_data = ( card_node ) => {
  const title = card_node.querySelector('.css-n55ojx')?.textContent
  return { title }
}
```

`app.js`:

```javascript
import puppeteer from 'puppeteer'
import { launch_method_args } from './helpers/puppeteer.js'
import { hello_world, get_card_data } from './a-file.js'

const browser = await puppeteer.launch(launch_method_args)
const page = await browser.newPage()
await page.goto('https://store.epicgames.com/en-US/browse?sortBy=releaseDate&sortDir=DESC&tag=August%20Event%20Sale&category=Game&count=40&start=0', { waitUntil: 'load' })

await page.exposeFunction('hello_world', hello_world)
await page.exposeFunction('get_card_data', get_card_data)

await page.evaluate(async () => {
  // const data = await window.hello_world()
  const data = await window.get_card_data( document.querySelector('.css-lrwy1y') )
  console.log(data)
})

// await browser.close()
```

@OrKoN

**Comment by drewbaker** [comment]
I want this exact thing, a bunch of helper functions for sorting through the DOM... @babakfp curious how you solved this? 

I can't imagine that the answer is just a bunch of repeated code inside `.evaluate()` everytime?!
