### ISSUE TITLE
[Bug]: Timezone override is already in effect

### ISSUE THREAD

**Issue by firmart** [puppeteer/puppeteer#8854]
### Bug description

Steps to reproduce the problem:

1. Call `page.emulateTimezone(timeZone)` twice in a browser session.

See also: https://github.com/alixaxel/chrome-aws-lambda/issues/137

### Puppeteer version

14.4.1

### Node.js version

17.5.0

### npm version

8.4.1

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:268
                error: new Errors_js_1.ProtocolError(),
                       ^

ProtocolError: Protocol error (Emulation.setTimezoneOverride): Timezone override is already in effect
    at /node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:268:24
    at new Promise (<anonymous>)
    at CDPSession.send (/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:264:16)
    at next (/node_modules/puppeteer-extra-plugin-stealth/evasions/sourceurl/index.js:34:41)
    at CDPSession.send (/node_modules/puppeteer-extra-plugin-stealth/evasions/sourceurl/index.js:67:18)
    at Page.emulateTimezone (/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1586:67)
    ...
}
```

**Comment by jrandolf** [comment]
Could you verify if this occurs with different time zones? If it only occurs due to a duplicate call, I wouldn't necessarily call this a bug.

**Comment by Lightning00Blade** [comment]
This does not seem to be an issue on the latest Puppeteer version.
