### ISSUE TITLE
[Bug]: define a function in page.evaluate throw an error

### ISSUE THREAD

**Issue by a1528zhang** [puppeteer/puppeteer#8859]
### Bug description

Steps to reproduce the problem:
code here:

tsconfig.json
```
{
    "compilerOptions": {
        "rootDirs": ["src", "test"],
        "outDir": "dist",
        "target": "esnext",
        "esModuleInterop": true,
        "moduleResolution": "Node",
        "module": "CommonJS",
        "lib": ["dom", "esnext"],
        "strictNullChecks": true,
        "resolveJsonModule": true,
        "skipLibCheck": true,
        "pretty": true,
    },
    "include": ["*", "src"]
}
```

processor.test.ts
```
import puppeteer from "puppeteer"

let browser: puppeteer.Browser;
let browserIsOpen = false;
const options = {
    headless: false,
    args: [
      '--no-sandbox',
      '--disable-gpu',
      '--disable-dev-shm-usage',
      '--disable-setuid-sandbox',
      '--shm-size=1gb',
      '--auto-open-devtools-for-tabs',
    ],
    dumpio: !!process.env.DEBUG,
}

export const launchPuppeteer = async () => {
    try {
        browser = await puppeteer.launch(options);
        console.log('launch success');
        
        browserIsOpen = true;
        browser.on('disconnected', () => {
            browserIsOpen = false;
        });
    } catch (e) {
        throw e
    }
}

const test = async ()=> {
    await launchPuppeteer();
    const page = await browser.newPage();
    await page.evaluate(async () => {
        const fc = () => {   //  throw   Error: Evaluation failed: ReferenceError: n is not defined
            console.log("test");
        }
    });
}

test();
```

and run it with `tsx ./processor.test.ts`

MacOS Catalina  10.15.7
typescript: 4.8.2
tsx: 3.8.2

I can not define any funciton in page.evaluate(), include async and sync function 

### Puppeteer version

16.2.0

### Node.js version

v16.10.0

### npm version

7.24.0

### What operating system are you seeing the problem on?

macOS

### Relevant log output

```shell
/xxx/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:271
        throw new Error('Evaluation failed: ' + (0, util_js_1.getExceptionMessage)(exceptionDetails));
              ^

Error: Evaluation failed: ReferenceError: n is not defined
    at pptr://__puppeteer_evaluation_script__:1:20
    at x._ExecutionContext_evaluate (/xxx/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:271:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at x.evaluate (/xxx/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:118:16)
    at null.test (/xxx/test/projector/processor.test.ts:41:5)
```

**Comment by OrKoN** [comment]
It looks like your TypeScript configuration incorrectly compiles the JavaScript code:

```
async()=>{const o=n(()=>{console.log("test")},"fc")}
```

is the resulting JavaScript. As the evaluation happens in another process (on the page within the browser), the code should not reference any outside functions.
