### ISSUE TITLE
[Bug]: Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.

### ISSUE THREAD

**Issue by justoverclockl** [puppeteer/puppeteer#8928]
### Bug description

Steps to reproduce the problem:

1. Run puppeteer
2. wait for some minutes
3. see the error in the logs

```
0|app      |     at ExecutionContext.evaluate (/home/xxx/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:27)
0|app      |     at DOMWorld.evaluate (/home/marco/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:97:24)
0|app      |     at runMicrotasks (<anonymous>)
0|app      |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|app      | Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
0|app      |     at CDPSession.send (/home/marco/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:218:35)
0|app      |     at ExecutionContext._evaluateInternal (/home/marco/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:204:50)
0|app      |     at ExecutionContext.evaluate (/home/marco/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:27)
0|app      |     at DOMWorld.evaluate (/home/marco/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:97:24)


```

### Puppeteer version

@latest

### Node.js version

16

### npm version

@latest

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
0|app      |     at ExecutionContext.evaluate (/home/xxx/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:27)
0|app      |     at DOMWorld.evaluate (/home/marco/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:97:24)
0|app      |     at runMicrotasks (<anonymous>)
0|app      |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|app      | Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
0|app      |     at CDPSession.send (/home/marco/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:218:35)
0|app      |     at ExecutionContext._evaluateInternal (/home/marco/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:204:50)
0|app      |     at ExecutionContext.evaluate (/home/marco/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:27)
0|app      |     at DOMWorld.evaluate (/home/marco/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:97:24)
```

**Comment by OrKoN** [comment]
@justoverclockl please provide the exact version numbers you are using and a script to reproduce

**Comment by justoverclockl** [comment]
i'm using "whatsapp-web.js": "^1.17.1"

**Comment by OrKoN** [comment]
That package is using Puppeteer `^13.0.0` which is not the latest. I suggest you open the issue with the package developer first.

**Comment by changzhiwin** [comment]
@justoverclockl  any solution?  why this issue closed?
I have same problem with latest `"puppeteer": "^19.1.1"`.

**Comment by OrKoN** [comment]
@changzhiwin please open a new issue with all details and a repro script.
