### ISSUE TITLE
Browser dies silently

### ISSUE THREAD

**Issue by Khady** [puppeteer/puppeteer#893]
I'm trying to access a page in a loop, but at some points it seems that the browser is silently dying and I'm not aware of it until the next operation using the browser.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: ec760ab5e345cc18e3199e937ecddc6cac3bd703
* Platform / OS version: debian stretch
* URLs (if applicable): https://www.cbsnews.com/news/missouri-disabled-woman-gypsy-blancharde-pleads-not-guilty-in-mothers-murder/

**What steps will reproduce the problem?**

```javascript
'use strict';

const puppeteer = require('puppeteer');
const longjohn = require("longjohn");
longjohn.async_trace_limit = -1;

const URL = "http://www.cbsnews.com/news/missouri-disabled-woman-gypsy-blancharde-pleads-not-guilty-in-mothers-murder/";

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

(async() => {
  process.on("uncaughtException", (e) => {
    console.error("Unhandled exeption:", e);
    cont = false;
  });
  process.on("unhandledRejection", (reason, p) => {
    console.error("Unhandled Rejection at: Promise", p, "reason:", reason);
    // application specific logging, throwing an error, or other logic here
    cont = false;
  });
  const args = [
    "--disable-gpu",
    "--disable-setuid-sandbox",
    "--force-device-scale-factor",
    "--ignore-certificate-errors",
    "--no-sandbox",
  ];
  const options = {
    args,
    headless: false,
    ignoreHTTPSErrors: true,
  };
  let cont = true;
  let n = 0
  const browser = await puppeteer.launch(options);
  while (cont) {
    console.log(n);
    n++
    const page = await browser.newPage();
    await page.setRequestInterceptionEnabled(true);
    page.on("request", (request) => {
      if (request.resourceType === "Image") {
        request.abort();
      } else {
        request.continue();
      }
    });
    await page.goto(URL, { timeout: 30000, waitUntil: "load" });
    await page.waitFor(1000);
    const html = await page.content();
    await page.close();
    await sleep(2000);
  }
  await browser.close();
})();
```

Just launch this code and it should crash pretty quickly.

**What is the expected result?**

The program should loop forever

**What happens instead?**

```
$ nodejs ./bin/test_server/minimal.js
0
1
Unhandled Rejection at: Promise Promise {
  <rejected> Error: not opened
    at WebSocket.send (/home/team/prod/bin/test_server/node_modules/ws/lib/WebSocket.js:355:18)
    at Connection.send (/home/team/prod/bin/test_server/node_modules/puppeteer/lib/Connection.js:72:14)
    at Browser.newPage (/home/team/prod/bin/test_server/node_modules/puppeteer/lib/Browser.js:46:47)
    at __dirname (/home/team/prod/bin/test_server/minimal.js:41:32)
    at <anonymous>
---------------------------------------------
    at __dirname (/home/team/prod/bin/test_server/minimal.js:18:11)
    at Object.<anonymous> (/home/team/prod/bin/test_server/minimal.js:57:3)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16) } reason: Error: not opened
    at WebSocket.send (/home/team/prod/bin/test_server/node_modules/ws/lib/WebSocket.js:355:18)
    at Connection.send (/home/team/prod/bin/test_server/node_modules/puppeteer/lib/Connection.js:72:14)
    at Browser.newPage (/home/team/prod/bin/test_server/node_modules/puppeteer/lib/Browser.js:46:47)
    at __dirname (/home/team/prod/bin/test_server/minimal.js:41:32)
    at <anonymous>
---------------------------------------------
    at __dirname (/home/team/prod/bin/test_server/minimal.js:18:11)
    at Object.<anonymous> (/home/team/prod/bin/test_server/minimal.js:57:3)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
Unhandled exeption: { Error: kill ESRCH
    at Object._errnoException (util.js:1041:11)
    at process.kill (internal/process.js:184:18)
    at process.killChrome (/home/team/prod/bin/test_server/node_modules/puppeteer/lib/Launcher.js:124:19)
    at emitOne (events.js:115:13)
    at process.emit (events.js:210:7)
    at process.emit (/home/team/prod/bin/test_server/node_modules/source-map-support/source-map-support.js:431:21)
---------------------------------------------
    at Function.addEventListener (/home/team/prod/bin/test_server/node_modules/puppeteer/lib/helper.js:189:13)
    at Function.launch (/home/team/prod/bin/test_server/node_modules/puppeteer/lib/Launcher.js:100:32)
    at Function.launch (/home/team/prod/bin/test_server/node_modules/puppeteer/lib/Puppeteer.js:25:21)
    at __dirname (/home/team/prod/bin/test_server/minimal.js:37:35)
    at Object.<anonymous> (/home/team/prod/bin/test_server/minimal.js:57:3)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12) code: 'ESRCH', errno: 'ESRCH', syscall: 'kill' }
```

**Comment by Khady** [comment]
Actually, it seems that I need to run this code in xvfb to make it crash faster. No idea why.

**Comment by Khady** [comment]
`xvfb-run -a --server-args="-screen 0 1920x2000x24" bash -c "export DEBUG=* && nodejs bin/test_server/browser_dies.js 2> puppeteer.log"`

[browser_dies.js](https://github.com/GoogleChrome/puppeteer/files/1340231/browser_dies.js.txt)

I ran the program like this to get the puppeteer logs: 
[puppeteer.log](https://github.com/GoogleChrome/puppeteer/files/1340224/browser_dies.log)

**Comment by aslushnikov** [comment]
Puppeteer should provide `browser.closed`  and `page.closed` events so that it's possible to build reliable scripts - filed #952 to track this.

The crashes themselves are bugs, please report to chromium: [crbug.com/new](http://crbug.com/new)
