### ISSUE TITLE
Page closes itself silently

### ISSUE THREAD

**Issue by Khady** [puppeteer/puppeteer#894]
Sometimes when I try to navigate to a url, the `goto` is successful but then the page seems to be closed and when I try to get the content of the page, I face an exception.

I face the error mostly when I run puppeteer in xvfb.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: aslushnikov/puppeteer#04311aa6cdc18ee0ab696532e805f857a880b8c3 but I can reproduce with master too
* Platform / OS version: debian stretch
* URLs (if applicable): http://www.cbsnews.com/news/missouri-disabled-woman-gypsy-blancharde-pleads-not-guilty-in-mothers-murder/

**What steps will reproduce the problem?**

I don't manage to find a good code to reproduce this issue. Basically I have a code very similar to this running, and sometimes I have the error pasted bellow. Much easier to reproduce when the code is launched in xvfb.

```
'use strict';

const puppeteer = require('puppeteer');
const longjohn = require("longjohn");
longjohn.async_trace_limit = -1;

const URL = "http://www.cbsnews.com/news/missouri-disabled-woman-gypsy-blancharde-pleads-not-guilty-in-mothers-murder/";

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

(async() => {
  process.on("uncaughtException", (e) => {
    console.error("Unhandled exeption:", e);
    cont = false;
  });
  process.on("unhandledRejection", (reason, p) => {
    console.error("Unhandled Rejection at: Promise", p, "reason:", reason);
    // application specific logging, throwing an error, or other logic here
    cont = false;
  });
  const args = [
    "--disable-gpu",
    "--disable-setuid-sandbox",
    "--force-device-scale-factor",
    "--ignore-certificate-errors",
    "--no-sandbox",
  ];
// same behavior with headless false
  const options = {
    args,
    headless: true,
    ignoreHTTPSErrors: true,
  };
  let cont = true;
  let n = 0
  const browser = await puppeteer.launch(options);
  while (cont) {
    console.log(n);
    n++
    const page = await browser.newPage();
    await page.setRequestInterceptionEnabled(true);
    page.on("request", (request) => {
      if (request.resourceType === "Image") {
        request.abort();
      } else {
        request.continue();
      }
    });
    await page.goto(URL, { timeout: 30000, waitUntil: "load" });
    await page.waitFor(1000);
    const html = await page.content();
    await page.close();
    await sleep(2000);
  }
  await browser.close();
})();
```

**What is the expected result?**

The page should not be closed until `page.close` is called.

**What happens instead?**

When I try to use the page, I get this error:

```
Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
    at Session.send (/home/louis/Code/test/v2/test_server/node_modules/puppeteer/lib/Connection.js:167:29)
    at Frame._rawEvaluate (/home/louis/Code/test/v2/test_server/node_modules/puppeteer/lib/FrameManager.js:256:75)
    at Frame.evaluate (/home/louis/Code/test/v2/test_server/node_modules/puppeteer/lib/FrameManager.js:186:37)
    at Page.evaluate (/home/louis/Code/test/v2/test_server/node_modules/puppeteer/lib/Page.js:502:43)
    at Page.content (/home/louis/Code/test/v2/test_server/node_modules/puppeteer/lib/Page.js:345:23)
...
```

If I display the log of puppeteer, I get this:

[puppeteer.log](https://github.com/GoogleChrome/puppeteer/files/1339646/e.log)

The stacktrace pasted above is displayed just after the line `Thu, 28 Sep 2017 05:58:06 GMT puppeteer:frame frame.evaluate("() => {let retVal = …")` and before the latest call to `page.close()`

**Comment by aslushnikov** [comment]
Hi @Khady,

This is likely due to the renderer crashing. If you launch browser with the `dumpio: true`, you should see chromium stacktrace when this happens. Could you please check if this is the case?

**Comment by Khady** [comment]
Thanks for the answer. I'm pretty busy currently, but I will try to do this during the week.

**Comment by aslushnikov** [comment]
In general case, we should report page crashes with the `page.closed` event. Filed #952 to track this.

**Comment by aaronshaf** [comment]
I get the same problem when I have:

```
    await page.setRequestInterceptionEnabled(true);
    page.on("request", (request) => {
      if (request.resourceType === "Image") {
        request.abort();
      } else {
        request.continue();
      }
    });
```

**Comment by aaronshaf** [comment]
```
Received signal 11 SEGV_MAPERR 000000000008
 [0x00010f93aabc]
 [0x00010f93a9b1]
 [0x7fffa8206b3a]
 [0x000000000000]
 [0x00010e4ca6ec]
 [0x0001102bf6a2]
 [0x0001102bf1c9]
 [0x00010e6728ed]
 [0x00010e67091e]
 [0x00010e66a210]
 [0x00010e6698e0]
 [0x00010e6671f3]
 [0x00010e666b61]
 [0x00010e66c8ca]
 [0x00010e67b6bd]
 [0x00010e673e89]
 [0x00010dea2f85]
 [0x000110408bff]
 [0x0001103ecce3]
 [0x0001103ed361]
 [0x00010e42bc35]
 [0x0001103fdb4d]
 [0x00010f93b2bc]
 [0x00010f961024]
 [0x00010f961529]
 [0x00010f962691]
 [0x00010f985e3a]
 [0x00010e47da68]
 [0x00010e47dbf6]
 [0x00010f9b805b]
 [0x00010f9b26a7]
 [0x7fffa821093b]
 [0x7fffa8210887]
 [0x7fffa821008d]
[end of stack trace]
Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
    at Session.send (/Users/me/github/project/node_modules/puppeteer/lib/Connection.js:167:29)
    at ExecutionContext.evaluateHandle (/Users/me/github/project/node_modules/puppeteer/lib/ExecutionContext.js:58:75)
    at ExecutionContext.evaluate (/Users/me/github/project/node_modules/puppeteer/lib/ExecutionContext.js:37:31)
    at Frame.evaluate (/Users/me/github/project/node_modules/puppeteer/lib/FrameManager.js:211:26)
    at Page.evaluate (/Users/me/github/project/node_modules/puppeteer/lib/Page.js:582:43)
    at Page.content (/Users/me/github/project/node_modules/puppeteer/lib/Page.js:424:23)
    at main (/Users/me/github/project/scripts/prerender-pages.js:112:34)
```

**Comment by aslushnikov** [comment]
@aaronshaf what's your environment? Do you use docker? Can you share your script/url so that we can repro it locally? Also, can you please file a new issue answering above questions so that we have more information to work with.

**Comment by Khady** [comment]
With a recent version of puppeteer and dumpio, I now have this:

```
$ xvfb-run -a --server-args="-screen 0 1920x2000x24" nodejs bug.js
[9406:9406:1108/050313.727424:ERROR:display.cc(52)] Failed to parse the default device scale factor:

DevTools listening on ws://127.0.0.1:18295/devtools/browser/1f72703a-f073-4e32-852c-ff50d0b63942
=================================================================================================>  0
[9406:9506:1108/050316.208274:ERROR:object_proxy.cc(575)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[9406:9506:1108/050316.208429:ERROR:object_proxy.cc(575)] Failed to call method: org.freedesktop.UPower.GetDisplayDevice: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[9406:9506:1108/050316.208580:ERROR:object_proxy.cc(575)] Failed to call method: org.freedesktop.UPower.EnumerateDevices: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
=================================================================================================>  1
[9406:9506:1108/050319.652230:ERROR:object_proxy.cc(575)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[9406:9506:1108/050319.652415:ERROR:object_proxy.cc(575)] Failed to call method: org.freedesktop.UPower.GetDisplayDevice: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[9406:9506:1108/050319.652557:ERROR:object_proxy.cc(575)] Failed to call method: org.freedesktop.UPower.EnumerateDevices: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
Received signal 11 SEGV_MAPERR 000000000008
#0 0x55e9d228dd07 base::debug::StackTrace::StackTrace()
#1 0x55e9d228d86f base::debug::(anonymous namespace)::StackDumpSignalHandler()
#2 0x7f4ec65120c0 <unknown>
#3 0x55e9d1145069 content::protocol::NetworkHandler::CreateRequestFromURLRequest()
#4 0x55e9d11278de content::DevToolsURLInterceptorRequestJob::Start()
#5 0x55e9d2b0c72b net::URLRequest::StartJob()
#6 0x55e9d2b0c281 net::URLRequest::Start()
#7 0x55e9d129761a content::ResourceLoader::StartRequestInternal()
#8 0x55e9d129566d content::ResourceLoader::StartRequest()
#9 0x55e9d128fe44 content::ResourceDispatcherHostImpl::BeginRequestInternal()
#10 0x55e9d128f46c content::ResourceDispatcherHostImpl::ContinuePendingBeginRequest()
#11 0x55e9d128cd15 content::ResourceDispatcherHostImpl::BeginRequest()
#12 0x55e9d128c6fa content::ResourceDispatcherHostImpl::OnRequestResourceInternal()
#13 0x55e9d1292547 content::ResourceDispatcherHostImpl::OnRequestResourceWithMojo()
#14 0x55e9d129edba content::URLLoaderFactoryImpl::CreateLoaderAndStart()
#15 0x55e9d129881e content::ResourceMessageFilter::CreateLoaderAndStart()
#16 0x55e9d0bdddbf content::mojom::URLLoaderFactoryStubDispatch::Accept()
#17 0x55e9d2c240c9 IPC::(anonymous namespace)::ChannelAssociatedGroupController::Accept()
#18 0x55e9d2c09fe5 mojo::Connector::ReadSingleMessage()
#19 0x55e9d2c0a6e2 mojo::Connector::ReadAllAvailableMessages()
#20 0x55e9d10a2990 net::(anonymous namespace)::CallInt64ToInt()
#21 0x55e9d2c19f44 mojo::SimpleWatcher::OnHandleReady()
#22 0x55e9d228ec47 base::debug::TaskAnnotator::RunTask()
#23 0x55e9d22a8444 base::MessageLoop::RunTask()
#24 0x55e9d22a8907 base::MessageLoop::DoWork()
#25 0x55e9d22ab4b9 base::MessagePumpLibevent::Run()
#26 0x55e9d22c8c15 base::RunLoop::Run()
#27 0x55e9d10e6cf6 content::BrowserThreadImpl::IOThreadRun()
#28 0x55e9d10e6ef1 content::BrowserThreadImpl::Run()
#29 0x55e9d22f355a base::Thread::ThreadMain()
#30 0x55e9d22ee7c3 base::(anonymous namespace)::ThreadFunc()
#31 0x7f4ec6508494 start_thread
#32 0x7f4ec0239aff clone
  r8: 0000000000000008  r9: 000014fd42fd74b0 r10: 0000000000000003 r11: cce27f464577cad5
 r12: 000014fd4131cd48 r13: 000014fd4351c6da r14: 000014fd4131cd40 r15: 000014fd428d9000
  di: 000014fd42f68060  si: 000055e9ce6e95d6  bp: 000014fd425e79c8  bx: 00007f4eab9f3ba1
  dx: 0000000000000000  ax: 0000000000000000  cx: 00000000000005d6  sp: 00007f4eab9f3b60
  ip: 000055e9d1145069 efl: 0000000000010246 cgf: 002b000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000008
[end of stack trace]
Calling _exit(1). Core file will not be generated.
[1108/050320.738418:ERROR:nacl_helper_linux.cc(310)] NaCl helper process running without a sandbox!
Most likely you need to configure your SUID sandbox correctly
=================================================================================================>  2
Unhandled Rejection at: Promise Promise {
  <rejected> Error: not opened
    at WebSocket.send (/home/team/prod/bin/test_project/node_modules/ws/lib/WebSocket.js:355:18)
    at Connection.send (/home/team/prod/bin/test_project/node_modules/puppeteer/lib/Connection.js:72:14)
    at Browser.newPage (/home/team/prod/bin/test_project/node_modules/puppeteer/lib/Browser.js:95:47)
    at __dirname (/home/team/prod/bin/test_project/bug.js:43:29)
    at <anonymous>
---------------------------------------------
    at __dirname (/home/team/prod/bin/test_project/bug.js:18:13)
    at Object.<anonymous> (/home/team/prod/bin/test_project/bug.js:59:3)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16) } reason: Error: not opened
    at WebSocket.send (/home/team/prod/bin/test_project/node_modules/ws/lib/WebSocket.js:355:18)
    at Connection.send (/home/team/prod/bin/test_project/node_modules/puppeteer/lib/Connection.js:72:14)
    at Browser.newPage (/home/team/prod/bin/test_project/node_modules/puppeteer/lib/Browser.js:95:47)
    at __dirname (/home/team/prod/bin/test_project/bug.js:43:29)
    at <anonymous>
---------------------------------------------
    at __dirname (/home/team/prod/bin/test_project/bug.js:18:13)
    at Object.<anonymous> (/home/team/prod/bin/test_project/bug.js:59:3)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
```

**Comment by Khady** [comment]
The log looks more like #893

**Comment by aslushnikov** [comment]
@Khady that's a nice stacktrace, thank you. Filed upstream as https://crbug.com/782545

+cc network gurus @caseq and @allada.

**Comment by Khady** [comment]
And another trace, with another url. Puppeteer version d1f044e18ff6eeb80468e4f30dbd99618dc13f96

```
$ URL=https://www.thetimes.co.uk/article/free-schools-plan-under-threat-from-budget-raid-gz7fg2tn0 nodejs bug.js
[1108/053256.928394:ERROR:display.cc(52)] Failed to parse the default device scale factor:

DevTools listening on ws://127.0.0.1:18747/devtools/browser/2826d659-97c2-430c-8cc6-a0a95ba548d3
=================================================================================================>  0
[1108/053258.302923:INFO:CONSOLE(0)] "The SSL certificate used to load resources from https://www.thetimes.co.uk will be distrusted in the future. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.", source: about:blank (0)
[1108/053258.307354:INFO:CONSOLE(0)] "The SSL certificate used to load resources from https://www.thetimes.co.uk will be distrusted in the future. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.", source: https://www.thetimes.co.uk/article/free-schools-plan-under-threat-from-budget-raid-gz7fg2tn0 (0)
[1108/053258.381009:INFO:CONSOLE(0)] "The SSL certificate used to load resources from https://c.amazon-adsystem.com will be distrusted in the future. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.", source: https://www.thetimes.co.uk/article/free-schools-plan-under-threat-from-budget-raid-gz7fg2tn0 (0)
[1108/053258.456984:INFO:CONSOLE(0)] "The SSL certificate used to load resources from https://feeds.thetimes.co.uk will be distrusted in the future. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.", source: https://www.thetimes.co.uk/article/free-schools-plan-under-threat-from-budget-raid-gz7fg2tn0 (0)
[1108/053258.457225:INFO:CONSOLE(0)] "The SSL certificate used to load resources from https://s.go-mpulse.net will be distrusted in the future. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.", source: https://www.thetimes.co.uk/article/free-schools-plan-under-threat-from-budget-raid-gz7fg2tn0 (0)
[1108/053258.514802:INFO:CONSOLE(0)] "The SSL certificate used to load resources from https://static.criteo.net will be distrusted in the future. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.", source: https://www.thetimes.co.uk/article/free-schools-plan-under-threat-from-budget-raid-gz7fg2tn0 (0)
[1108/053258.517730:INFO:CONSOLE(0)] "The SSL certificate used to load resources from https://ads.pubmatic.com will be distrusted in the future. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.", source: https://www.thetimes.co.uk/article/free-schools-plan-under-threat-from-budget-raid-gz7fg2tn0 (0)
[1108/053258.521774:INFO:CONSOLE(0)] "The SSL certificate used to load resources from https://secure.adnxs.com will be distrusted in the future. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.", source: https://www.thetimes.co.uk/article/free-schools-plan-under-threat-from-budget-raid-gz7fg2tn0 (0)
[1108/053258.624856:INFO:CONSOLE(0)] "The SSL certificate used to load resources from https://aax.amazon-adsystem.com will be distrusted in the future. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.", source: https://www.thetimes.co.uk/article/free-schools-plan-under-threat-from-budget-raid-gz7fg2tn0 (0)
[1108/053258.625171:INFO:CONSOLE(0)] "The SSL certificate used to load resources from https://as-sec.casalemedia.com will be distrusted in the future. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.", source: https://www.thetimes.co.uk/article/free-schools-plan-under-threat-from-budget-raid-gz7fg2tn0 (0)
[1108/053258.652502:ERROR:object_proxy.cc(575)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[1108/053258.652526:WARNING:property.cc(150)] DaemonVersion: GetAndBlock: failed.
[1108/053258.652630:ERROR:object_proxy.cc(575)] Failed to call method: org.freedesktop.UPower.GetDisplayDevice: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[1108/053258.652782:ERROR:object_proxy.cc(575)] Failed to call method: org.freedesktop.UPower.EnumerateDevices: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[1108/053258.682736:INFO:CONSOLE(0)] "The SSL certificate used to load resources from https://bidder.criteo.com will be distrusted in the future. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.", source: https://www.thetimes.co.uk/article/free-schools-plan-under-threat-from-budget-raid-gz7fg2tn0 (0)
[1108/053258.696496:INFO:CONSOLE(0)] "The SSL certificate used to load resources from https://c.go-mpulse.net will be distrusted in the future. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.", source: https://www.thetimes.co.uk/article/free-schools-plan-under-threat-from-budget-raid-gz7fg2tn0 (0)
[1108/053258.701164:INFO:CONSOLE(0)] "The SSL certificate used to load resources from https://secure.adnxs.com will be distrusted in the future. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.", source: https://acdn.adnxs.com/ib/static/usersync/v3/async_usersync.html (0)
[1108/053258.799571:INFO:CONSOLE(51)] "MQ:medium", source: https://www.thetimes.co.uk/d/js/app-0bed16f075.js (51)
Received signal 11 SEGV_MAPERR 000000000008
#0 0x563d2afedd07 base::debug::StackTrace::StackTrace()
#1 0x563d2afed86f base::debug::(anonymous namespace)::StackDumpSignalHandler()
#2 0x7f0638fe60c0 <unknown>
#3 0x563d29ea5069 content::protocol::NetworkHandler::CreateRequestFromURLRequest()
#4 0x563d29e878de content::DevToolsURLInterceptorRequestJob::Start()
#5 0x563d2b86c72b net::URLRequest::StartJob()
#6 0x563d2b86c281 net::URLRequest::Start()
#7 0x563d29ff761a content::ResourceLoader::StartRequestInternal()
#8 0x563d29ff566d content::ResourceLoader::StartRequest()
#9 0x563d29fefe44 content::ResourceDispatcherHostImpl::BeginRequestInternal()
#10 0x563d29fef46c content::ResourceDispatcherHostImpl::ContinuePendingBeginRequest()
#11 0x563d29fecd15 content::ResourceDispatcherHostImpl::BeginRequest()
#12 0x563d29fec6fa content::ResourceDispatcherHostImpl::OnRequestResourceInternal()
#13 0x563d29ff2547 content::ResourceDispatcherHostImpl::OnRequestResourceWithMojo()
#14 0x563d29ffedba content::URLLoaderFactoryImpl::CreateLoaderAndStart()
#15 0x563d29ff881e content::ResourceMessageFilter::CreateLoaderAndStart()
#16 0x563d2993ddbf content::mojom::URLLoaderFactoryStubDispatch::Accept()
#17 0x563d2b9840c9 IPC::(anonymous namespace)::ChannelAssociatedGroupController::Accept()
#18 0x563d2b969fe5 mojo::Connector::ReadSingleMessage()
#19 0x563d2b96a6e2 mojo::Connector::ReadAllAvailableMessages()
#20 0x563d29e02990 net::(anonymous namespace)::CallInt64ToInt()
#21 0x563d2b979f44 mojo::SimpleWatcher::OnHandleReady()
#22 0x563d2afeec47 base::debug::TaskAnnotator::RunTask()
#23 0x563d2b008444 base::MessageLoop::RunTask()
#24 0x563d2b008907 base::MessageLoop::DoWork()
#25 0x563d2b00b4b9 base::MessagePumpLibevent::Run()
#26 0x563d2b028c15 base::RunLoop::Run()
#27 0x563d29e46cf6 content::BrowserThreadImpl::IOThreadRun()
#28 0x563d29e46ef1 content::BrowserThreadImpl::Run()
#29 0x563d2b05355a base::Thread::ThreadMain()
#30 0x563d2b04e7c3 base::(anonymous namespace)::ThreadFunc()
#31 0x7f0638fdc494 start_thread
#32 0x7f0632d0daff clone
  r8: 0000000000000008  r9: 000005cb40a523c0 r10: 0000000000000003 r11: cce27f464577cad5
 r12: 000005cb40bad5a8 r13: 000005cb40ea4dfa r14: 000005cb40bad5a0 r15: 000005cb40ce0800
  di: 000005cb40bb9000  si: 0000563d274495d6  bp: 000005cb40b17248  bx: 00007f06229c4ba1
  dx: 0000000000000000  ax: 0000000000000000  cx: 00000000000005d6  sp: 00007f06229c4b60
  ip: 0000563d29ea5069 efl: 0000000000010246 cgf: 002b000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000008
[end of stack trace]
Calling _exit(1). Core file will not be generated.
Unhandled Rejection at: Promise Promise {
  <rejected> Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
    at Session.send (/home/team/prod/bin/test_project/node_modules/puppeteer/lib/Connection.js:167:29)
    at ExecutionContext.evaluateHandle (/home/team/prod/bin/test_project/node_modules/puppeteer/lib/ExecutionContext.js:58:75)
    at ExecutionContext.evaluate (/home/team/prod/bin/test_project/node_modules/puppeteer/lib/ExecutionContext.js:37:31)
    at Frame.evaluate (/home/team/prod/bin/test_project/node_modules/puppeteer/lib/FrameManager.js:228:26)
    at Page.evaluate (/home/team/prod/bin/test_project/node_modules/puppeteer/lib/Page.js:592:43)
    at Page.content (/home/team/prod/bin/test_project/node_modules/puppeteer/lib/Page.js:428:23)
    at __dirname (/home/team/prod/bin/test_project/bug.js:54:26)
    at <anonymous>
---------------------------------------------
    at __dirname (/home/team/prod/bin/test_project/bug.js:18:13)
    at Object.<anonymous> (/home/team/prod/bin/test_project/bug.js:59:3)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16) } reason: Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
    at Session.send (/home/team/prod/bin/test_project/node_modules/puppeteer/lib/Connection.js:167:29)
    at ExecutionContext.evaluateHandle (/home/team/prod/bin/test_project/node_modules/puppeteer/lib/ExecutionContext.js:58:75)
    at ExecutionContext.evaluate (/home/team/prod/bin/test_project/node_modules/puppeteer/lib/ExecutionContext.js:37:31)
    at Frame.evaluate (/home/team/prod/bin/test_project/node_modules/puppeteer/lib/FrameManager.js:228:26)
    at Page.evaluate (/home/team/prod/bin/test_project/node_modules/puppeteer/lib/Page.js:592:43)
    at Page.content (/home/team/prod/bin/test_project/node_modules/puppeteer/lib/Page.js:428:23)
    at __dirname (/home/team/prod/bin/test_project/bug.js:54:26)
    at <anonymous>
---------------------------------------------
    at __dirname (/home/team/prod/bin/test_project/bug.js:18:13)
    at Object.<anonymous> (/home/team/prod/bin/test_project/bug.js:59:3)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
```

```javascript
'use strict';

const puppeteer = require('puppeteer');
const longjohn = require("longjohn");
longjohn.async_trace_limit = -1;

const URL = process.env.URL || "http://www.cbsnews.com/news/missouri-disabled-woman-gypsy-blancharde-pleads-not-guilty-in-mothers-murder/";

function sleep(ms) {
    return new Promise((resolve) => setTimeout(resolve, ms));
}

(async() => {
    process.on("uncaughtException", (e) => {
	console.error("Unhandled exeption:", e);
	process.exit(6);
    });
    process.on("unhandledRejection", (reason, p) => {
	console.error("Unhandled Rejection at: Promise", p, "reason:", reason);
	// application specific logging, throwing an error, or other logic here
	// cont = false;
    });
    const args = [
	"--disable-gpu",
	"--disable-setuid-sandbox",
	"--force-device-scale-factor",
	"--ignore-certificate-errors",
	"--no-sandbox",
    ];
    // same behavior with headless false
    const options = {
	args,
	headless: true,
	ignoreHTTPSErrors: true,
	dumpio: true,
    };
    let cont = true;
    let n = 0
    const browser = await puppeteer.launch(options);
    while (cont && n <= 5) {
	console.log("=================================================================================================> ", n);
	n++
	const page = await browser.newPage();
	await page.setRequestInterception(true);
	page.on("request", (request) => {
	    if (request.resourceType === "image") {
		request.abort();
	    } else {
		request.continue();
	    }
	});
	await page.goto(URL, { timeout: 30000, waitUntil: "load" });
	await page.waitFor(1000);
	const html = await page.content();
	await page.close();
	await sleep(2000);
    }
    await browser.close();
})();```

**Comment by Khady** [comment]
http://hamptoninn3.hilton.com/en/hotels/texas/hampton-inn-and-suites-north-houston-spring-HOUSXHX/index.html
http://hamptoninn3.hilton.com/en/hotels/pennsylvania/hampton-inn-and-suites-valley-forge-oaks-PHLVYHX/index.html
http://www.ikea.com/us/en/catalog/products/00177249/
https://www.accuweather.com/en/us/bristol-vt/05443/weather-forecast/336184
https://www.thesun.co.uk/news/2669006/hillary-clinton-catches-husband-bill-checking-out-melania-trump-during-presidential-inauguration-ceremony/

Same error on those urls. I hope this can help

**Comment by aslushnikov** [comment]
@Khady awesome, I can repro on OS X on tip-of-tree (https://github.com/GoogleChrome/puppeteer/commit/7d18275fb981e01cec4a4fbac61a9c66e46947bc) with
```
URL=https://www.thetimes.co.uk/article/free-schools-plan-under-threat-from-budget-raid-gz7fg2tn0 node bug.js
```

**Comment by allada** [comment]
I'm going to take a bet the problem is here:

https://cs.chromium.org/chromium/src/content/browser/devtools/protocol/network_handler.cc?type=cs&sq=package:chromium&l=1114

since the documentation here:

https://cs.chromium.org/chromium/src/net/base/upload_element_reader.h?type=cs&sq=package:chromium&l=28

says that it may not exist, but we are not null-checking it.

**Comment by aslushnikov** [comment]
@allada nice, that was exactly the issue

@Khady: @caseq fixed the issue in [r515281](https://chromium-review.googlesource.com/c/chromium/src/+/759298), we'll bring it in with the next chromium roll.
