### ISSUE TITLE
[Bug]: `Frame.waitForSelector` is flaky for cross-process navigation

### ISSUE THREAD

**Issue by jrandolf-google** [puppeteer/puppeteer#8959]
1) waittask specs
1246       Frame.waitForSelector
1247         should survive cross-process navigation:
1248     done() called multiple times in test <waittask specs Frame.waitForSelector should survive cross-process navigation> of file /home/runner/work/puppeteer/puppeteer/test/build/waittask.spec.js; in addition, done() received error: Error: NS_BINDING_ABORTED at http://127.0.0.1:44173/grid.html
1249    at navigate (/home/runner/work/puppeteer/puppeteer/src/common/Frame.ts:336:13)
1250    at runMicrotasks (<anonymous>)
1251    at processTicksAndRejections (node:internal/process/task_queues:96:5)
1252    at Frame.goto (/home/runner/work/puppeteer/puppeteer/src/common/Frame.ts:300:17)
1253    at Page.goto (/home/runner/work/puppeteer/puppeteer/src/common/Page.ts:1954:12)
1254    at Context.<anonymous> (/home/runner/work/puppeteer/puppeteer/test/src/waittask.spec.ts:477:7)
1255  Error: done() called multiple times in test <waittask specs Frame.waitForSelector should survive cross-process navigation> of file /home/runner/work/puppeteer/puppeteer/test/build/waittask.spec.js; in addition, done() received error: Error: NS_BINDING_ABORTED at http://127.0.0.1:44173/grid.html
1256      at navigate (src/common/Frame.ts:336:13)
1257      at runMicrotasks (<anonymous>)
1258      at processTicksAndRejections (node:internal/process/task_queues:96:5)
1259      at Frame.goto (src/common/Frame.ts:300:17)
1260      at Page.goto (src/common/Page.ts:1954:12)
1261      at Context.<anonymous> (test/src/waittask.spec.ts:477:7)
1262      at runMicrotasks (<anonymous>)
1263      at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by OrKoN** [comment]
Also, the waitForFunction is flaky:

```
should survive navigations:
     done() called multiple times in test <waittask specs Frame.waitForFunction should survive navigations> of file /home/runner/work/puppeteer/puppeteer/test/build/waittask.spec.js; in addition, done() received error: Error: JSHandles can be evaluated only in the context they were created!
    at ExecutionContext.convertArgument (/home/runner/work/puppeteer/puppeteer/src/common/ExecutionContext.ts:328:17)
    at Array.map (<anonymous>)
    at ExecutionContext._ExecutionContext_evaluate (/home/runner/work/puppeteer/puppeteer/src/common/ExecutionContext.ts:277:43)
    at ExecutionContext.evaluateHandle (/home/runner/work/puppeteer/puppeteer/src/common/ExecutionContext.ts:196:26)
    at IsolatedWorld.evaluateHandle (/home/runner/work/puppeteer/puppeteer/src/common/IsolatedWorld.ts:213:20)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at WaitTask.rerun (/home/runner/work/puppeteer/puppeteer/src/common/WaitTask.ts:94:26)
    at async Promise.all (index 0)
    at TaskManager.rerunAll (/home/runner/work/puppeteer/puppeteer/src/common/WaitTask.ts:235:5) {
  uncaught: true
}
```

**Comment by jrandolf** [comment]
No longer relevant.
