### ISSUE TITLE
[Bug]: spawn Unkown system error -86 on Apple Silicon / M1

### ISSUE THREAD

**Issue by Jiangultimo** [puppeteer/puppeteer#8960]
### Bug description

Steps to reproduce the problem:

1. install puppeteer latest version
2. generate a pdf for the page built with nextjs

```javascript
const generatePDF = async (
  url: string,
  options: PuppeteerLaunchOptions = defaultPuppeteerLaunchOptions,
  pdfOptions: PDFOptions = defaultPDFOptions
): Promise<Buffer> => {
  const browser = await puppeteer.launch(options)
  const page: Page = await browser.newPage()

  await page.setDefaultNavigationTimeout(0)
  await page.goto(url, {
    waitUntil: 'networkidle2'
  })
  await page.addStyleTag({
    content: `
    #tools{
      display: none;
    }
    `
  })
  const pdfBuffer = await page.pdf(pdfOptions)
  await browser.close()
  return pdfBuffer
}
````

OS: macOS 12.6 21G115 arm64
CPU: Apple M1 Max

I have tried installing puppeteer with `PUPPETEER_EXPERIMENTAL_CHROMIUM_MAC_ARM=true`
but i got this:
```bash
Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (1036745).
    at ChromeLauncher.launch (file:///Users/hing/spark/generate-resume/node_modules/puppeteer/lib/esm/puppeteer/node/ChromeLauncher.js:64:23)
    at async generatePDF (webpack-internal:///(api)/./utils/pdf.ts:24:21)
    at async exportPDF (webpack-internal:///(api)/./pages/api/pdf.ts:19:33)
    at async Object.apiResolver (/Users/hing/spark/generate-resume/node_modules/next/dist/server/api-utils/node.js:184:9)
    at async DevServer.runApi (/Users/hing/spark/generate-resume/node_modules/next/dist/server/next-server.js:403:9)
    at async Object.fn (/Users/hing/spark/generate-resume/node_modules/next/dist/server/base-server.js:493:37)
    at async Router.execute (/Users/hing/spark/generate-resume/node_modules/next/dist/server/router.js:222:36)
    at async DevServer.run (/Users/hing/spark/generate-resume/node_modules/next/dist/server/base-server.js:612:29)
    at async DevServer.run (/Users/hing/spark/generate-resume/node_modules/next/dist/server/dev/next-dev-server.js:569:20)
    at async DevServer.handleRequest (/Users/hing/spark/generate-resume/node_modules/next/dist/server/base-server.js:311:20)
```
then I went into `node_modules/puppeteer`, ran `npm install` :
```bash
> puppeteer@17.1.3 install
> node install.js

Downloading Chromium r1036745 - 120.5 Mb [====================] 100% 0.0s
Chromium (1036745) downloaded to /Users/hing/spark/generate-resume/node_modules/puppeteer/.local-chromium/mac-1036745
```
run the project get the same error

### Puppeteer version

v17.1.3

### Node.js version

v16.16.0

### npm version

8.17.0

### What operating system are you seeing the problem on?

macOS

### Relevant log output

```shell
Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at Module.spawn (node:child_process:700:9)
    at BrowserRunner.start (file:///Users/hing/spark/generate-resume/node_modules/puppeteer/lib/esm/puppeteer/node/BrowserRunner.js:91:34)
    at ChromeLauncher.launch (file:///Users/hing/spark/generate-resume/node_modules/puppeteer/lib/esm/puppeteer/node/ChromeLauncher.js:70:16)
    at async generatePDF (webpack-internal:///(api)/./utils/pdf.ts:24:21)
    at async exportPDF (webpack-internal:///(api)/./pages/api/pdf.ts:19:33)
    at async Object.apiResolver (/Users/hing/spark/generate-resume/node_modules/next/dist/server/api-utils/node.js:184:9)
    at async DevServer.runApi (/Users/hing/spark/generate-resume/node_modules/next/dist/server/next-server.js:403:9)
    at async Object.fn (/Users/hing/spark/generate-resume/node_modules/next/dist/server/base-server.js:493:37)
    at async Router.execute (/Users/hing/spark/generate-resume/node_modules/next/dist/server/router.js:222:36) {
  errno: -86,
  code: 'Unknown system error -86',
  syscall: 'spawn'
}
```

**Comment by OrKoN** [comment]
Github Actions [still does not support M1](https://github.com/actions/runner-images/issues/2187) so the support is experimental as we don't have test coverage. Make sure that you run `npm install` with `PUPPETEER_EXPERIMENTAL_CHROMIUM_MAC_ARM` and sometimes you might want to re-install Puppeteer if it previously was installed with the x86 binary to make sure the ARM binary is downloaded.

**Comment by EtaJx** [comment]
The problem has disappeared since I updated the OS. The issue is also caused by an updated OS. The xcode command line tools need to agree to a new license.

**Comment by hoaminhit** [comment]
Please install Rosetta then try again
https://support.apple.com/HT211861
