### ISSUE TITLE
[Bug]: page.$eval  not working when defined in other files

### ISSUE THREAD

**Issue by Ykeng** [puppeteer/puppeteer#8968]
### Bug description

i am using `page.$eva()` to get DOM  content.  But  if the function  defined  in `utils.js` file,  the code seem to not working .

**utils.js**
```
const getContent = async function(page, selector) {
  return await page.$eval(selector, function(element) {
    return element.textContent || ''
  })
}

module.exports = {
  getContent
}
```

App.test.js
```
const puppeteer = require("puppeteer");

const { getContent } = require("./utils.js");

// same to getContent function
const getContent1 = async function (page, selector) {
  return await page.$eval(selector, function (element) {
    return element.textContent || "";
  });
};

describe("Example", () => {
  let page;
  let browser;
  beforeAll(async () => {
    browser = await puppeteer.launch({ headless: false });
    page = await browser.newPage();
    await page.goto("http://172.16.7.48/#/login", {
      waitUntil: ["networkidle2"],
    });
  }, 60 * 1000);

  afterAll(async () => {
    await browser.close();
  });

  it("visit page", async () => {
    // getContent1 defined in this file
    let content = await getContent1(page, "footer");
    console.info(content);
    await expect(content).toMatch("2020");
    // getContent defined in utils.js file
    content = await getContent(page, "footer");
    console.info(content);
    await expect(content).toMatch("2020");
  });
});

```

### Puppeteer version

17.1.3

### Node.js version

v16.14.2

### npm version

8.5.0

### What operating system are you seeing the problem on?

macOS

### Relevant log output

```shell
Evaluation failed: ReferenceError: cov_228wabbjqy is not defined

      at pptr:/__puppeteer_evaluation_script__:3:5
      at ExecutionContext._ExecutionContext_evaluate (node_modules/puppeteer/src/common/ExecutionContext.ts:293:13)
      at ExecutionContext.evaluate (node_modules/puppeteer/src/common/ExecutionContext.ts:136:12)
      at ElementHandle.evaluate (node_modules/puppeteer/src/common/JSHandle.ts:133:12)
      at ElementHandle.$eval (node_modules/puppeteer/src/common/ElementHandle.ts:181:20)
```

**Comment by OrKoN** [comment]
It looks like you are running with coverage reporting (judging by `cov_228wabbjqy`) You need to make sure your coverage tool does not instrument functions that are evaluated inside the page:

```
return await page.$eval(selector, function (element) { // this function is serialized toString by Puppeteer and evaluated in the target page instead of NodeJS. 
    return element.textContent || "";
});
```

**Comment by Ykeng** [comment]
thanks for your  help. disabled  `jest` coverage option and all things work.
