### ISSUE TITLE
[Bug]: when I request a pdf file, there is an error

### ISSUE THREAD

**Issue by libofei2004** [puppeteer/puppeteer#9006]
### Bug description

Steps to reproduce the problem:
when I use await page.goto(url, { timeout:25000, waitUntil: 'networkidle0'}) to request a pdf file, the pdf had been downloaded  successfully, but it report an error:

Error: net::ERR_ABORTED at http://gjaqyj.cnjournals.com/gjaqyj/ch/reader/create_pdf.aspx?file_no=20220106&year_id=2022&quarter_id=1&falg=1
    at navigate (C:\workspace\digger\electron-egg-master\node_modules\puppeteer\lib\cjs\puppeteer\common\Frame.js:225:23)
    at runMicrotasks (<anonymous>)
    at runNextTicks (internal/process/task_queues.js:58:5)
    at listOnTimeout (internal/timers.js:523:9)
    at processTimers (internal/timers.js:497:7)
    at async Frame.goto (C:\workspace\digger\electron-egg-master\node_modules\puppeteer\lib\cjs\puppeteer\common\Frame.js:195:21)

The error is not affect normal function, but I would like to know the reason.

### Puppeteer version

17.1.3

### Node.js version

16.13.0

### npm version

8.1.0

### What operating system are you seeing the problem on?

Windows

**Comment by jrandolf** [comment]
Could you provide an MVP?

**Comment by jrandolf** [comment]
Looks like https://github.com/puppeteer/puppeteer/issues/9005

**Comment by libofei2004** [comment]
@jrandolf what is MVP？I see https://github.com/puppeteer/puppeteer/issues/9005 , but I can‘t find the answer, I can download files successfully by goto(), but also report an error.
