### ISSUE TITLE
[Bug]: Error: spawn Unknown system error -8

### ISSUE THREAD

**Issue by Glecun** [puppeteer/puppeteer#9011]
### Bug description

Hi ! :wave: 

Steps to reproduce the problem:

- Run a docker with image `arm32v7/node:16-alpine`
- Go in `docker exec -it [container-name] sh`
- `npm install` (with puppeteer 13.5.1)
- Run a simple script :arrow_down: 
```
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({ args: ['--no-sandbox'] });
    await browser.close();
})();
```
Thanks in advance :pray: 

### Puppeteer version

13.5.1

### Node.js version

v16.17.0

### npm version

8.15.0

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
/ # env DEBUG="puppeteer:*" node script.js
  puppeteer:fetcher {
  puppeteer:fetcher   revision: '970485',
  puppeteer:fetcher   executablePath: '/node_modules/puppeteer/.local-chromium/linux-970485/chrome-linux/chrome',
  puppeteer:fetcher   folderPath: '/node_modules/puppeteer/.local-chromium/linux-970485',
  puppeteer:fetcher   local: true,
  puppeteer:fetcher   url: 'https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/970485/chrome-linux.zip',
  puppeteer:fetcher   product: 'chrome'
  puppeteer:fetcher } +0ms
  puppeteer:launcher Calling /node_modules/puppeteer/.local-chromium/linux-970485/chrome-linux/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=Translate --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --enable-blink-features=IdleDetection --export-tagged-pdf --headless --hide-scrollbars --mute-audio about:blank --no-sandbox --remote-debugging-port=0 --user-data-dir=/tmp/puppeteer_dev_chrome_profile-GmPaLg +0ms
node:internal/errors:477
    ErrorCaptureStackTrace(err);
    ^

Error: spawn Unknown system error -8
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at Object.spawn (node:child_process:713:9)
    at BrowserRunner.start (/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:91:34)
    at ChromeLauncher.launch (/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:109:16)
    at async /script.js:4:21 {
  errno: -8,
  code: 'Unknown system error -8',
  syscall: 'spawn'
}
```

**Comment by jrandolf** [comment]
Currently, Puppeteer is only guaranteed to support the Docker image it provides. See https://github.com/puppeteer/puppeteer/tree/main/docker for more information.
