### ISSUE TITLE
[Bug]: Unexpected QueryHandler error thrown when utilising page.$eval function

### ISSUE THREAD

**Issue by pecampelo** [puppeteer/puppeteer#9017]
### Bug description

Steps to reproduce the problem:

1. Launch a Puppeteer instance inside a docker container.

2. Make use of the `page.$` function inside a `try/catch` block, with an await prior to it and trying to find a selector with its `xpath` prefix. e.g.: 

`const elementHandle = await page.$('xpath/' + '//a[text() = "Example"]')`

3. The function will return `Promise<ElementHandle>`.

4. Make use of the `$eval` function to click such elementHandle.
e.g.: 

`await page.$eval(elementHandle, (el) => el.click({ delay: 5 }))`

5. It will throw an error in the catch block:

`TypeError: selector.startsWith is not a function`.

It is related to the queryHandler for the selector:

```
function getQueryHandlerAndSelector(selector) {
    for (const handlerMap of [QUERY_HANDLERS, INTERNAL_QUERY_HANDLERS]) {
        for (const [name, { handler: queryHandler, transformSelector },] of handlerMap) {
            for (const separator of CUSTOM_QUERY_SEPARATORS) {
                const prefix = `${name}${separator}`;
                if (selector.startsWith(prefix)) {
                    selector = selector.slice(prefix.length);
                    if (transformSelector) {
                        selector = transformSelector(selector);
                    }
                    return { updatedSelector: selector, queryHandler };
                }
            }
        }
    }
    return { updatedSelector: selector, queryHandler: defaultHandler };
}
```

To be honest, I have recently started using the xpath prefix, and did not have many occurrences of this error, only in some divs. Maybe this is not a matter of not finding a selector or not, but I believe it is most likely a matter of the adaptation of the evaluate method when using a selector gotten through the xpath prefix. Maybe I am wrong.

If anyone has any ideas on what the description could be,  I would be willing to open a PR to fix such error throwing.

### Puppeteer version

17.0.0

### Node.js version

16.16.0

### npm version

8.19.2

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
TypeError: selector.startsWith is not a function
at getQueryHandlerAndSelector (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/QueryHandler.js:237:30)
at ElementHandle.$ (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ElementHandle.js:102:100)
at ElementHandle.$eval (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ElementHandle.js:145:42)
at IsolatedWorld.$eval (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/IsolatedWorld.js:200:2
```

**Comment by pecampelo** [comment]
Just realized I made a mistake by trying to `$eval` an elementHandle, which should instead be a string.

Closing this due to lack of need for better error handling.
