### ISSUE TITLE
`page.goto()` does not follow redirects

### ISSUE THREAD

**Issue by niftylettuce** [puppeteer/puppeteer#902]
This method does not resolve redirects per `301` nor `302` status codes.

It simply throws an error:

```sh
Error: Failed to navigate: http://localhost:3000/some-redirect-url
      at Page.goto (node_modules/puppeteer/lib/Page.js:390:13)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

**Comment by niftylettuce** [comment]
Perhaps use <https://github.com/cezary/resolve-redirect>?

**Comment by paulirish** [comment]
I would not expect a problem here.

You can try `page.goto('http://gmail.com')` with headless:false to verify that it does handle the series of redirects just fine.

**Comment by aslushnikov** [comment]
@niftylettuce redirects should work, we have a bunch of tests to cover this.

Please share a snippet if it doesn't work for you. Meanwhile speculatively closing this due to inactivity.

**Comment by ali-habibzadeh** [comment]
Is there a way of making `.goto ` not follow redirects and stop after the first 3xx response?

**Comment by aslushnikov** [comment]
@ali-habibzadeh no, not yet. feel free to file an issue for this

**Comment by ali-habibzadeh** [comment]
I have already [https://github.com/GoogleChrome/puppeteer/issues/1132](url)

**Comment by GuilloOme** [comment]
you mean: #1132 :wink:

**Comment by kauecastro** [comment]
Have already you solved this problem ?
