### ISSUE TITLE
[Bug]: Cannot find module 'puppeteer-core/internal/common/DeviceDescriptors.js'

### ISSUE THREAD

**Issue by elephantux** [puppeteer/puppeteer#9126]
### Bug description

Steps to reproduce the problem:
Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-110-generic x86_64)

1. npm i puppeteer --save
2. create script from source https://github.com/checkly/puppeteer-examples/blob/master/1.%20basics/screenshots.js
3. node test.js

### Puppeteer version

19.0.0

### Node.js version

v10.19.0

### npm version

6.14.4

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
Error: Cannot find module 'puppeteer-core/internal/common/DeviceDescriptors.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/var/www/tariffer/node_modules/puppeteer/lib/cjs/puppeteer/puppeteer.js:33:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```
```

**Comment by OrKoN** [comment]
@elephantux we don't support Node 10, could you try with Node 14 at least.

**Comment by elephantux** [comment]
This helped, but now the script crashes on this error:
```
Error: Failed to launch the browser process!
[1018/083524.552398:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
```

**Comment by OrKoN** [comment]
@elephantux do you run it as root?

**Comment by elephantux** [comment]
> @elephantux do you run it as root?

I think so. I run php unit test via ssh and logged in as root

**Comment by OrKoN** [comment]
Then you should do like the message says: 1) either run as a non-root 2) or add --no-sandbox for the launch args. I recommend running as a non-root user.
