### ISSUE TITLE
 Failed start Browser ! Error: spawn Unknown system error -86

### ISSUE THREAD

**Issue by AnonymFromInternet** [puppeteer/puppeteer#9142]
### Bug description

Hello everyone!
I have a problem. I am trying to run tests from terminal and get this error:

Init Browser ...
    Launch browser ...
    Failed start Browser ! Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at Object.spawn (node:child_process:700:9)
    at BrowserRunner.start (...bdd-api/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:91:34)
    at ChromeLauncher.launch (...bdd-api/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:109:16)
    at async BrowserLauncher.launchBrowser (...bdd-api/step_definition/BrowserLauncher.js:80:24)
    at async BrowserLauncher.initBrowser (...bdd-api/step_definition/BrowserLauncher.js:124:9)
    at async Command.openApp (...bdd-api/step_definition/steps/serviceSteps.js:153:9) {
  errno: -86,
  code: 'Unknown system error -86',
  syscall: 'spawn',

Can anyone please tell me how could I solve it?

Thank You!

### Puppeteer version

13.5.0

### Node.js version

16.15.0

### npm version

8.5.5

### What operating system are you seeing the problem on?

macOS

### Relevant log output

```shell
Init Browser ...
    Launch browser ...
    Failed start Browser ! Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at Object.spawn (node:child_process:700:9)
    at BrowserRunner.start (...bdd-api/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:91:34)
    at ChromeLauncher.launch (...bdd-api/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:109:16)
    at async BrowserLauncher.launchBrowser (...bdd-api/step_definition/BrowserLauncher.js:80:24)
    at async BrowserLauncher.initBrowser (...bdd-api/step_definition/BrowserLauncher.js:124:9)
    at async Command.openApp (...bdd-api/step_definition/steps/serviceSteps.js:153:9) {
  errno: -86,
  code: 'Unknown system error -86',
  syscall: 'spawn',
```

**Comment by trystan2k** [comment]
Hi,

I am having this same error, but with an old version of Puppeteer (3.3.0).

After some initial investigation, I am wondering if this is related to the Chrome version (109) ?

I started to see this error this morning in our pipeline, while yesterday evening it was working fine. Nothing has changed since last night in our code base (no change in package.json, no change in package-lock.json, neither in any source code). 

Does it make sense to blame Chrome version ? If it is confirmed to be the culprit, how could we fix this ?

**Comment by AnonymFromInternet** [comment]
Solution:
<img width="645" alt="Screenshot 2022-10-21 at 15 53 44" src="https://user-images.githubusercontent.com/84092079/197212463-b6b5f4e5-6215-4409-86f8-a7d87b39d805.png">

**Comment by trystan2k** [comment]
In my case, it is running in a Docker with Linux. 

The solution I found, so far, is to fix an old revision of Chromium (5 days ago) setting `node_chromium_revision=1059524` in my .npmrc file

**Comment by jrandolf** [comment]
Could you upgrade puppeteer to the latest version and try again?

**Comment by OrKoN** [comment]
-86 usually means the mismatch between the binary architecture and your system cpu architecture. `PUPPETEER_EXPERIMENTAL_CHROMIUM_MAC_ARM` is a solution for Macs for Linux we currently don't have ARM builds at all.

**Comment by vadimrostok** [comment]
Solved it by installing rosetta on m2 mac.
`softwareupdate --install-rosetta`
