### ISSUE TITLE
[Bug]: Crash on code launch when using "userDataDir" option

### ISSUE THREAD

**Issue by parotech123** [puppeteer/puppeteer#9146]
### Bug description

When trying to launch a chrome instances by referencing the chrome.exe location, the userDataDir and setting the profile in args  with the following code

```
const browser = await puppeteer.launch({
		headless: false,
		executablePath: 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
		userDataDir: "C:\\Users\\parol\\AppData\\Local\\Google\\Chrome\\User Data",
		args: [
			`--profile-directory="Profile 1"`,		
		]
	})
```

i get this message

```
C:\Projects\WebSeer\node_modules\puppeteer-core\lib\cjs\puppeteer\node\BrowserRunner.js:299
            reject(new Error([
                   ^

Error: Failed to launch the browser process!


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (C:\Projects\WebSeer\node_modules\puppeteer-core\lib\cjs\puppeteer\node\BrowserRunner.js:299:20)
    at ChildProcess.<anonymous> (C:\Projects\WebSeer\node_modules\puppeteer-core\lib\cjs\puppeteer\node\BrowserRunner.js:290:24)
    at ChildProcess.emit (node:events:402:35)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
    at Process.callbackTrampoline (node:internal/async_hooks:130:17)
```

as soon i remove the userDataDir option, the script works and i can see the browser opening.

i get the same result with the following code
```
const browser = await puppeteer.launch({
		headless: false,
		executablePath: 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
		// userDataDir: "C:\\Users\\parol\\AppData\\Local\\Google\\Chrome\\User Data",
		args: [
			`--user-data-dir=C:\\Users\\parol\\AppData\\Local\\Google\\Chrome\\User Data`,
			`--profile-directory="Profile 1"`,
		]
	})
```

what am i doing wrong? thanks for the help

### Puppeteer version

18.2.1 and above

### Node.js version

16.13.2

### npm version

8.1.2

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
C:\Projects\WebSeer\node_modules\puppeteer-core\lib\cjs\puppeteer\node\BrowserRunner.js:299
            reject(new Error([
                   ^

Error: Failed to launch the browser process!


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (C:\Projects\WebSeer\node_modules\puppeteer-core\lib\cjs\puppeteer\node\BrowserRunner.js:299:20)
    at ChildProcess.<anonymous> (C:\Projects\WebSeer\node_modules\puppeteer-core\lib\cjs\puppeteer\node\BrowserRunner.js:290:24)
```

**Comment by jrandolf** [comment]
Could it be the space in `User Data`?

**Comment by aladynjr** [comment]
same issue, no solution found
