### ISSUE TITLE
[Bug]: Unknown system error -86

### ISSUE THREAD

**Issue by hoaminhit** [puppeteer/puppeteer#9193]
### Bug description

Steps to reproduce the problem:

1. …
const puppeteer = require('puppeteer');
await puppeteer.launch();

==> throw:

 Error: spawn Unknown system error -86
[0]     at ChildProcess.spawn (node:internal/child_process:413:11)
[0]     at Object.spawn (node:child_process:743:9)
[0]     at BrowserRunner.start (/Users/my-acc/Workspace/Prj/my-prj/node/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:121:34)
[0]     at ChromeLauncher.launch (/Users/my-acc/Workspace/Prj/my-prj/node/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:74:16)
[0]     at async run (/Users/my-acc/Workspace/Prj/my-prj/routes/my-rt/index.js:19:18) {
[0]   errno: -86,
[0]   code: 'Unknown system error -86',
[0]   syscall: 'spawn'
[0] }

### Puppeteer version

19.2.0

### Node.js version

v18.12.0

### npm version

8.19.2

### What operating system are you seeing the problem on?

macOS

**Comment by hoaminhit** [comment]
Thanks team, I found solution my mac arm need need to install Rosetta.
https://support.apple.com/HT211861
Worked!

**Comment by portalpap** [comment]
I'm on windows And I can't figure out how to solve this,

**Comment by sondrealf** [comment]
Thx this fixed it for me

**Comment by noscripter** [comment]
Detailed steps to install Rosetta in Mac(with Apple Chip):

## 1.command to check whether rosetta is installed:

```
/usr/bin/pgrep -q oahd && echo "Running" || echo "Not running"
```

## 2.install rosetta 2:

```
softwareupdate --install-rosetta
```
