### ISSUE TITLE
[Bug]: Cannot build puppetter-core using @vercel/ncc since version 18.2.0 

### ISSUE THREAD

**Issue by goldalworming** [puppeteer/puppeteer#9216]
### Bug description

Steps to reproduce the problem:

1. npm install puppeteer-core@18.2.0
2. create any puppeteer-core script
3. ncc build -m example.js -o dist

It works fine @18.1.0 and error show since 18.2.0

since 18.2.0 shown this error
Error: Cannot find package directory
    at getPackageDirectory (D:\code\node\puppeteer-new\dist\index.js:3:424814)
    at Object.3666 (D:\code\node\puppeteer-new\dist\index.js:3:425761)
    at __nccwpck_require__ (D:\code\node\puppeteer-new\dist\index.js:3:688282)
    at D:\code\node\puppeteer-new\dist\index.js:3:688525
    at D:\code\node\puppeteer-new\dist\index.js:3:688929
    at Object.<anonymous> (D:\code\node\puppeteer-new\dist\index.js:3:688968)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)

### Puppeteer version

18.2.0

### Node.js version

12.22.9

### npm version

6.14.15

### What operating system are you seeing the problem on?

Windows

**Comment by OrKoN** [comment]
Node 12 is not supported anymore. Please try using Node 14+ and latest NPM. Also, if you are running Puppeteer in a different environment, make sure to have the installation folder configured https://pptr.dev/guides/configuration#examples

**Comment by goldalworming** [comment]
I tried update to node 18.12.1 and use latest puppeteer and it works.
Thank You
