### ISSUE TITLE
ubuntu shows some errors.  release V19.0.0

### ISSUE THREAD

**Issue by xcbaojian** [puppeteer/puppeteer#9218]
### Bug description

after update to V19.0.0，ubuntu shows some errors when running.
This seems to be a problem with the chrome path. 
The error that is eventually reported after relying on the installation is difficult to solve.
Note that this is the case with Ubuntu.

### Puppeteer version

19.0.0

### Node.js version

16.7.1

### npm version

8.15.0

### What operating system are you seeing the problem on?

Linux

### Configuration file

```JavaScript
const puppeteer = require('puppeteer');
const moment = require('moment');
console.log(moment().format("YYYY-MM-DD HH:mm:ss"));  

(async () => {
  // const browser = await puppeteer.launch({ args: ['--no-sandbox', '--disable-setuid-sandbox'] })

const pathToExtension = '/root/.cache/puppeteer/chrome/linux-1056772/chrome-linux/chrome';
const browser = await puppeteer.launch({
   headless: true,
   timeout: 0, 
   devtools: true, 
   executablePath: pathToExtension,
   args:['--disable-infobars','--no-sandbox','--disable-setuid-sandbox']
   });
  const page = await browser.newPage();
  await page.goto('https://www.google.com');
  await page.screenshot({path: 'example110401.png'});

  await browser.close();
})();
```

### Relevant log output

```Shell
[00:16:30] /root/workspace/pupperteer_WcJ8/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:299
[00:16:30]             reject(new Error([
[00:16:30]                    ^
[00:16:30] 
[00:16:30] Error: Failed to launch the browser process!
[00:16:30] /root/.cache/puppeteer/chrome/linux-1056772/chrome-linux/chrome: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /root/.cache/puppeteer/chrome/linux-1056772/chrome-linux/chrome)
[00:16:30] /root/.cache/puppeteer/chrome/linux-1056772/chrome-linux/chrome: /usr/lib/x86_64-linux-gnu/libxkbcommon.so.0: no version information available (required by /root/.cache/puppeteer/chrome/linux-1056772/chrome-linux/chrome)
[00:16:30] /root/.cache/puppeteer/chrome/linux-1056772/chrome-linux/chrome: symbol lookup error: /root/.cache/puppeteer/chrome/linux-1056772/chrome-linux/chrome: undefined symbol: gbm_bo_get_modifier
[00:16:30] 
[00:16:30] 
[00:16:30] TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
[00:16:30] 
[00:16:30]     at onClose (/root/workspace/pupperteer_WcJ8/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:299:20)
```

**Comment by jrandolf** [comment]
Please check our guide on troubleshooting on https://pptr.dev. You are missing some libraries.

**Comment by xcbaojian** [comment]
hi
i install the libraries.the problem still.

`sudo apt install -y gconf-service libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget libappindicator3-1`

**Comment by xcbaojian** [comment]
![image](https://user-images.githubusercontent.com/96899734/200306919-85c46830-27f8-46f5-9235-30d91bcce8f3.png)

**Comment by iamsid** [comment]
Troubleshooted this for a couple of hours before finding this.
Seeing same issue with v19. Using v18.2.1 works fine. No dependency or package change.
Probably my configuration is failing because of this change: https://github.com/puppeteer/puppeteer/pull/9095
Although, I have no idea on how to configure it.

**Comment by sinanargun** [comment]
@iamsid this exact version worked for my case as well.

I put the below commands into Dockerfile:
`- apt-get update
          - >-
            apt-get install -yq gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3
            libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4
            libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1
            libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates
            fonts-liberation libnss3 lsb-release xdg-utils wget`
            
In package.json:
"puppeteer": "18.2.1 "

While launching the browser:
const browser = await puppeteer.launch({ args: ['--no-sandbox'] });

I am not sure exactly what is broken in the latest version, still investigating.

**Comment by chaosreigned** [comment]
i have the same issue in V19.2.2

`Error: Failed to launch the browser process!
/opt/bytefaas/.cache/puppeteer/chrome/linux-1056772/chrome-linux/chrome: symbol lookup error: /opt/bytefaas/.cache/puppeteer/chrome/linux-1056772/chrome-linux/chrome: undefined symbol: gbm_bo_get_modifier


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/opt/bytefaas/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:299:20)
    at Interface.<anonymous> (/opt/bytefaas/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:287:24)
    at Interface.emit (events.js:412:35)
    at Interface.close (readline.js:451:8)
    at Socket.onend (readline.js:224:10)
    at Socket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  from: 'launchDef'
}`

**Comment by MichaelBelousov** [comment]
FWIW: this is due to chromium 108 requiring a higher libglm1 version (greater than v17.1), source: https://www.forum.puppylinux.com/viewtopic.php?t=7542

**Comment by iamsid** [comment]
I was able to get the latest versions running on my server. I read somewhere (don't have the reference link) that after the package version is updated, the server needs to be restarted to ensure Chrome installation path is correctly set.
I did not understand it exactly, but v19+ puppeteer did start working after I deployed my app and restarted my remote server.

**Comment by luopeihai** [comment]
Lower the puppeteer version to less than or equal to v17.1
Reason: After puppeteer version > v17.1, the chromium version used is greater than 108, and this version of chromium calls a higher version of the image software libglm1
https://medium.com/@ggluopeihai/best-practices-for-scraping-html-to-generate-pdf-with-puppeteer-0f6e13c84f0f
