### ISSUE TITLE
[Bug]: A system error occurred: uv_os_homedir returned ENOENT (no such file or directory)

### ISSUE THREAD

**Issue by PHLAK** [puppeteer/puppeteer#9230]
### Bug description

We updated to puppeteer v19.0.0 shortly after release and modified our system to change the puppeteer cache directory to a non-standard location (i.e. `/var/cache/puppeteer`). This has been working fine. However after upgrading to v19.1.0 (and beyond, currently v19.2.2) puppeteer is not working with the following error.

```
The command "PATH=$PATH:/usr/local/bin:/opt/homebrew/bin NODE_PATH=`npm root -g` node '/var/www/html/vendor/spatie/browsershot/src/../bin/browser.js' '{"url":"file:\/\/\/tmp\/220035-0767462001667925278\/index.html","action":"pdf","options":{"args":["--no-sandbox"],"viewport":{"width":800,"height":600},"format":"letter","margin":{"top":"10mm","right":"10mm","bottom":"10mm","left":"10mm"},"waitUntil":"networkidle0","displayHeaderFooter":false,"printBackground":true}}'" failed.

Exit Code: 1(General error)

...

SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_homedir returned ENOENT (no such file or directory)
```

**NOTE:** Full error output below.

### Additional Details

We are running puppeteer through [`spatie/browsershot`](https://github.com/spatie/browsershot). These errors are occurring on our local systems in our development **Docker** container. Here's the relevant bits from our `docker-compose.yaml` file.

```yaml
version: '3.9'

services:
  app:
    ...
    
    environment:
      PDF_DISABLE_SANDBOXING: 'true'
      PUPPETEER_CACHE_DIR: /var/cache/puppeteer
   
    volumes:
      - ${PUPPETEER_CACHE_DIR:-$HOME/.cache/puppeteer}:/var/cache/puppeteer
```

It seems like [`uv_os_homedir`](http://iks.cs.ovgu.de/~elkner/tmp/ph/misc.html#c.uv_os_homedir) is part of the libuv library and according to the docs it's using the `HOME` environment variable which _is_ defined withing our Docker container.

```
(Docker Container) $ env | grep HOME
HOME=/tmp
```

### Puppeteer version

19.2.2

### Node.js version

18.4.0

### npm version

8.19.2

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```Shell
The command "PATH=$PATH:/usr/local/bin:/opt/homebrew/bin NODE_PATH=`npm root -g` node '/var/www/html/vendor/spatie/browsershot/src/../bin/browser.js' '{"url":"file:\/\/\/tmp\/220035-0767462001667925278\/index.html","action":"pdf","options":{"args":["--no-sandbox"],"viewport":{"width":800,"height":600},"format":"letter","margin":{"top":"10mm","right":"10mm","bottom":"10mm","left":"10mm"},"waitUntil":"networkidle0","displayHeaderFooter":false,"printBackground":true}}'" failed.

Exit Code: 1(General error)

Working directory: /var/www/html/public

Output:
================


Error Output:
================
node:internal/errors:477
    ErrorCaptureStackTrace(err);
    ^

SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_homedir returned ENOENT (no such file or directory)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/clean-stack/index.js:6:61)
    at Module._compile (node:internal/modules/cjs/loader:1112:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/aggregate-error/index.js:3:20)
    at Module._compile (node:internal/modules/cjs/loader:1112:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10) {
  code: 'ERR_SYSTEM_ERROR',
  info: {
    errno: -2,
    code: 'ENOENT',
    message: 'no such file or directory',
    syscall: 'uv_os_homedir'
  },
  errno: [Getter/Setter],
  syscall: [Getter/Setter]
}

Node.js v18.4.0
node:internal/errors:477
    ErrorCaptureStackTrace(err);
    ^

SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_homedir returned ENOENT (no such file or directory)
    at normalizeOptions (/var/www/html/node_modules/cosmiconfig/dist/index.js:69:26)
    at cosmiconfigSync (/var/www/html/node_modules/cosmiconfig/dist/index.js:38:29)
    at getConfiguration (/var/www/html/node_modules/puppeteer/lib/cjs/puppeteer/getConfiguration.js:24:54)
    at Object.<anonymous> (/var/www/html/node_modules/puppeteer/lib/cjs/puppeteer/puppeteer.js:44:66)
    at Module._compile (node:internal/modules/cjs/loader:1112:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18) {
  code: 'ERR_SYSTEM_ERROR',
  info: {
    errno: -2,
    code: 'ENOENT',
    message: 'no such file or directory',
    syscall: 'uv_os_homedir'
  },
  errno: [Getter/Setter],
  syscall: [Getter/Setter]
}

Node.js v18.4.0
```

**Comment by jrandolf** [comment]
Being defined in this case is not enough. It also needs to exist. Have you made sure the home directory exists?

**Comment by PHLAK** [comment]
@jrandolf Yes, the directory (`/tmp`) exists.

**Comment by PHLAK** [comment]
@jrandolf Actually, your comment gave me an idea and I was able to solve this by creating a user within my docker container with a "normal" home folder and setting `HOME` to that folder (i.e. `/home/username`).

Anyway, not sure if this is a Docker-specific issue but sorry to bother you.

**Comment by jrandolf** [comment]
Home directory is obtained through several means of I recall. In any case, you can manage this explicitly by using a configuration file.
