### ISSUE TITLE
[Bug]: Navigation timeout crashes the script

### ISSUE THREAD

**Issue by RainNHard** [puppeteer/puppeteer#9317]
### Bug description

When I get an error for a timeout in navigation, my script crashes, try catch does not help.

### Puppeteer version

19.3.0

### Node.js version

18.12.1

### npm version

9.1.2

### What operating system are you seeing the problem on?

Windows

### Configuration file

```JavaScript
import puppeteer from 'puppeteer-extra';
import StealthPlugin from 'puppeteer-extra-plugin-stealth';
puppeteer.use(StealthPlugin())
import { executablePath } from 'puppeteer';

import os, { type } from 'os';
import path from 'path';
import { fileURLToPath } from 'url';
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function launch() {
    try {
        var browser = await puppeteer.launch({
            headless: false, args: [
                '--window-size=1400,900',
                '--mute-audio',
                '--disable-gpu',
                '--no-sandbox'
            ],
            defaultViewport: {
                width: 1400,
                height: 900
            },
            ignoreHTTPSErrors: true,
            userDataDir: __dirname + '\\browser\\Profile',
            executablePath: executablePath(),
            timeout: 30000
        });
    } catch (error) {
        console.log(error);
    }
    let page = await browser.newPage();

    await page.setUserAgent("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36");

    try {
        page.goto('https://www.namesilo.com/', { timeout: 1000 });
    } catch (error) {
        console.log('just got an error');
    }
    
    while(true) {

    }
}
```

### Relevant log output

```Shell
C:\Users\admin\source\FSauto\node_modules\puppeteer-core\lib\cjs\puppeteer\common\LifecycleWatcher.js:174
    return new Errors_js_1.TimeoutError(errorMessage);
           ^
TimeoutError: Navigation timeout of 1000 ms exceeded
    at LifecycleWatcher._LifecycleWatcher_createTimeoutPromise (C:\Users\admin\source\FSauto\node_modules\puppeteer-core\lib\cjs\puppeteer\common\LifecycleWatcher.js:174:12)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:533:9)
    at process.processTimers (node:internal/timers:507:7)
    at async Frame.goto (C:\Users\admin\source\FSauto\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Frame.js:206:21)
    at async CDPPage.goto (C:\Users\admin\source\FSauto\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Page.js:1053:16)

Node.js v18.12.1
PS C:\Users\admin\source\FSauto>
```

**Comment by OrKoN** [comment]
The code you provided has two issues: 1) missing await before the goto which prevents try/catch from working 2) infinite loop that blocks the js event loop making everything to timeout. Once those issues are fixed,`page.goto('https://www.namesilo.com/')` works without timing out.

**Comment by Hodor228** [comment]
> The code you provided has two issues: 1) missing await before the goto which prevents try/catch from working 2) infinite loop that blocks the js event loop making everything to timeout. Once those issues are fixed,`page.goto('https://www.namesilo.com/')` works without timing out.

Thanks you sir. This was mine mistake
