### ISSUE TITLE
Support run puppeteer inside docker

### ISSUE THREAD

**Issue by ricardowiseverge** [puppeteer/puppeteer#9333]
### Bug description

Hello,

I'm trying to run puppeteer inside a chromium instance on a Docker Container without success (I've provided the log outp).

The docker commands:
`docker build --platform=linux/amd64 . -t  e2e-alpine`
`docker run -p 3000:3000 --platform linux/amd64 -it e2e-alpine`

It builds and it runs. When I trigger the endpoint that calls the chrome launcher (code of the launcher below) it shows the error I've shared as well.

Any suggestion?

**CODE**
```
  const browser = await launch({
    headless: true,
    args: [
      "--window-size=1920,1080",
      "--window-position=1921,0",
      "--disable-gpu",
      "--disable-dev-shm-usage",
      "--disable-setuid-sandbox",
      "--no-sandbox",
    ],
    executablePath: "/usr/bin/chromium-browser",
  });
```

**Package.json**
```
{
  "name": "test-e2e",
  "version": "1.0.0",
  "description": "",
  "main": "teste2e.js",
  "type": "module",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node src/index.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "body-parser": "^1.20.1",
    "dotenv": "^16.0.3",
    "express": "^4.18.2",
    "puppeteer-stream": "^2.1.1",
    "puppeteer":"19.3.0"
  }
}
```

**DOCKERFILE**
```
FROM alpine

RUN apk add --no-cache \
    chromium \
    nss \
    freetype \
    harfbuzz \
    ca-certificates \
    ttf-freefont \
    nodejs \
    yarn

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
    PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

RUN apk add npm
RUN yarn config set PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true
RUN yarn config set ignore-scripts true

ENV DEBIAN_FRONTEND noninteractive
WORKDIR /app
COPY package.json /app
COPY . /app
RUN yarn install
CMD ["yarn", "start"]
```

### Puppeteer version

19.3.0

### Node.js version

LTS

### npm version

LTS

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```Shell
/app/node_modules/puppeteer-stream/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:299
            reject(new Error([
                   ^

Error: Failed to launch the browser process!
qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
[1127/174844.482648:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Function not implemented (38)
Assertion failed: p_rcu_reader->depth != 0 (/qemu/include/qemu/rcu.h: rcu_read_unlock: 101)

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/app/node_modules/puppeteer-stream/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:299:20)
    at ChildProcess.<anonymous> (/app/node_modules/puppeteer-stream/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:290:24)
    at ChildProcess.emit (node:events:525:35)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

**Comment by jrandolf** [comment]
Please see our guides on Docker: https://pptr.dev/guides/docker/

**Comment by oleghalin** [comment]
It still not covers running in docker. I pulled docker image into my Dockerfile and face absolutely same error while running on CI

**Comment by yadue** [comment]
@oleghalin Please see my comment, maybe it will suit you https://github.com/puppeteer/puppeteer/issues/7746#issuecomment-1333677725
