### ISSUE TITLE
[Bug]: UncaughtException: Failed to launch the browser process

### ISSUE THREAD

**Issue by carmanlcr** [puppeteer/puppeteer#9361]
### Bug description

**What did I do?**

I have a docker project running with the node:19.1.0-alpine3.16 image.

I installed alpine chromium from its latest version (https://pkgs.alpinelinux.org/package/edge/community/x86_64/chromium) 

My docker runs on AWS ECS in a container with 8 vCPU and 16GB of memory, it has around 100 requests per second and 360000 requests per hour. 

I followed instructions from Troubleshooting(https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md) by creating the puppeteer.config.cjs file, and adding arguments to the launch configuration ('--no-sandbox', 
            '--disable-setuid-sandbox', 
            '--disable-extensions',
            '--aggressive-cache-discard',
            --disable-cache',
            '--disable-application-cache', '--disable-application-cache',
            '--disable-offline-load-stale-cache',
            --disable-gpu-shader-disk-cache',
            --media-cache-size=0',
            --disk-cache-size=0')

I have increased the size of my server since by concurrency (max CPU or Max Memory) I can avoid launching the browser, but I have found the error with CPU < 70% and memory < 50% both cases in use.

**What did you expect to happen?**

I expected my applications to be 100% resolved without puppeteer errors (There are controlled errors within the application).

**What actually happened?**

My server processes about 70% of the requests, the other 30% approximately (this calculation is not exact, it is measured manually with expected results) are errors of this type (UncaughtException: Failed to launch the browser process). 

### Puppeteer version

19.2.2

### Node.js version

19.1.0

### npm version

8.19.3

### What operating system are you seeing the problem on?

Linux

### Configuration file

```JavaScript
const {join} = require('path');

module.exports = {
  cacheDirectory: join(__dirname, '.cache', 'puppeteer'),
};
```

### Relevant log output

```Shell
{
   "exception":true,
   "level":"error",
   "message":"uncaughtException: Failed to launch the browser process! spawn /usr/bin/chromium-browser EAGAIN\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md\n\nError: Failed to launch the browser process! spawn /usr/bin/chromium-browser EAGAIN\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md\n\n at onClose (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:299:20)\n at ChildProcess.<anonymous> (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:293:24)\n at ChildProcess.emit (node:events:513:28)\n at ChildProcess.emit (node:domain:489:12)\n at ChildProcess._handle.onexit (node:internal/child_process:291:12)\n at onErrorNT (node:internal/child_process:483:16)\n at process.processTicksAndRejections (node:internal/process/task_queues:82:21)",
   "os":{
      "loadavg":[
         0,
         0.12,
         0.18
      ],
      "uptime":12939.19
   },
   "process":{
      "argv":[
         "/usr/local/bin/node",
         "/app/bin/www"
      ],
      "cwd":"/app",
      "execPath":"/usr/local/bin/node",
      "gid":0,
      "memoryUsage":{
         "arrayBuffers":63234,
         "external":1009804,
         "heapTotal":113537024,
         "heapUsed":109618632,
         "rss":170270720
      },
      "pid":18,
      "uid":0,
      "version":"v19.2.0"
   },
   "stack":"Error: Failed to launch the browser process! spawn /usr/bin/chromium-browser EAGAIN\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md\n\n at onClose (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:299:20)\n at ChildProcess.<anonymous> (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:293:24)\n at ChildProcess.emit (node:events:513:28)\n at ChildProcess.emit (node:domain:489:12)\n at ChildProcess._handle.onexit (node:internal/child_process:291:12)\n at onErrorNT (node:internal/child_process:483:16)\n at process.processTicksAndRejections (node:internal/process/task_queues:82:21)",
   "trace":[
      {
         "column":20,
         "file":"/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js",
         "function":"onClose",
         "line":299,
         "method":null,
         "native":false
      },
      {
         "column":24,
         "file":"/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js",
         "function":null,
         "line":293,
         "method":null,
         "native":false
      },
      {
         "column":28,
         "file":"node:events",
         "function":"ChildProcess.emit",
         "line":513,
         "method":"emit",
         "native":false
      },
      {
         "column":12,
         "file":"node:domain",
         "function":"ChildProcess.emit",
         "line":489,
         "method":"emit",
         "native":false
      },
      {
         "column":12,
         "file":"node:internal/child_process",
         "function":"ChildProcess._handle.onexit",
         "line":291,
         "method":"onexit",
         "native":false
      },
      {
         "column":16,
         "file":"node:internal/child_process",
         "function":"onErrorNT",
         "line":483,
         "method":null,
         "native":false
      },
      {
         "column":21,
         "file":"node:internal/process/task_queues",
         "function":"process.processTicksAndRejections",
         "line":82,
         "method":"processTicksAndRejections",
         "native":false
      }
   ]
}
```

**Comment by Lightning00Blade** [comment]
Hello as you can also see this is system issue rather a Puppeteer, so I will be closing this one as its out of scope. The process fails because system will not allow the chrome to be executed. There could be a policy that is stopping this from happening, or some other AWS ECS specific thing.
