### ISSUE TITLE
[Bug]: Failed to launch the browser process!

### ISSUE THREAD

**Issue by PoolloverNathan** [puppeteer/puppeteer#9409]
### Bug description

Steps to reproduce the problem:

1. Install puppeteer
2. Add it to tests and try to run
3. `Failed to launch the browser process!`

```
$ uname -a
Linux e704baadf6e7 5.15.0-1025-gcp #32~20.04.2-Ubuntu SMP Tue Nov 29 08:31:04 UTC 2022 x86_64 GNU/Linux
```

### Puppeteer version

19.4.0

### Node.js version

v16.7.0 (cannot modify)

### npm version

7.20.3 (cannot modify)

### What operating system are you seeing the problem on?

Linux

### Configuration file

No configuration file. Plain `puppeteer.launch()`.

### Relevant log output

```Shell
$ npx jest db-creds
-- snip --
  ● 'db.json'.creds › 3177539[1]

    Failed to launch the browser process!


    TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

      at onClose (node_modules/puppeteer-core/src/node/BrowserRunner.ts:328:9)
      at ChildProcess.<anonymous> (node_modules/puppeteer-core/src/node/BrowserRunner.ts:317:16)

  ● 'db.json'.creds › 3177539[1]

    TypeError: Cannot read property 'close' of undefined

      72 |   }
      73 |   afterEach(async () => {
    > 74 |     await page.close()
         |                ^
      75 |     page = null
      76 |   })
      77 |   afterAll(async () => {

      at Object.close (db-creds.test.js:74:16)
-- snip --

$ uname -a
Linux e704baadf6e7 5.15.0-1025-gcp #32~20.04.2-Ubuntu SMP Tue Nov 29 08:31:04 UTC 2022 x86_64 GNU/Linux
```

**Comment by OrKoN** [comment]
@PoolloverNathan can you launch the browser on this system without puppeteer?

**Comment by PoolloverNathan** [comment]
...I'm an idiot.
