### ISSUE TITLE
[Bug]:  net::ERR_ABORTED when request responds with 204 status

### ISSUE THREAD

**Issue by dan-scott-dev** [puppeteer/puppeteer#9458]
### Bug description

Steps to reproduce the problem:

For ease, test with a server you control. Otherwise test with a URL that you know will respond with 204 status.

Go to a URL on that server.

`await args.page.goto('http://localhost:8090/test');`

On the server at localhost:8090 make /test responds with 204 status.

### Puppeteer version

19.2.2

### Node.js version

16.16.0

### npm version

8.15.0

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```Shell
ERROR [ExceptionsHandler] net::ERR_ABORTED at http://localhost:8090/test
Error: net::ERR_ABORTED at http://localhost:8090/test
    at navigate (/projects/x/node_modules/puppeteer-core/src/common/Frame.ts:346:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Frame.goto (/projects/x/node_modules/puppeteer-core/src/common/Frame.ts:310:17)
    at CDPPage.goto (/projects/x/node_modules/puppeteer-core/src/common/Page.ts:1523:12)
 at myFunc (/projects/x/src/script.ts:251:27)
```

**Comment by jrandolf** [comment]
Could you provide a minimal, complete and verifiable example in a separate repository?

**Comment by dan-scott-dev** [comment]
> await args.page.goto('http://localhost:8090/test');

https://github.com/dan-scott-dev/puppeteer-9458

**Comment by dan-scott-dev** [comment]
Sure, here you are - https://github.com/dan-scott-dev/puppeteer-9458

**Comment by Rafael-Martins** [comment]
@OrKoN maybe we can add this error to the checking implemented in #9523, since it seems that is how chromium handles it as well. What do you think?

**Comment by OrKoN** [comment]
@Rafael-Martins I am not sure, we need to see what exactly happens here. Does the navigation still happens? if not, then we should report an error and fix it upstream.

**Comment by Rafael-Martins** [comment]
Oh, yeah, totally makes sense, I will do some testings if I have some time!

**Comment by armancarr-tm** [comment]
Hi, I have exactly the same scenario! Any news about this?
