### ISSUE TITLE
[Bug]: puppeteer doesn't fit well with Android devices

### ISSUE THREAD

**Issue by huajiqaq** [puppeteer/puppeteer#9460]
### Bug description

Steps to reproduce the problem:

When os.platform() returns Android, there is an error that prevents it from being installed 

### Puppeteer version

v19.4.1

### Node.js version

v18.12.1

### npm version

8.19.2

### What operating system are you seeing the problem on?

Linux

### Configuration file

```JavaScript

```

### Relevant log output

```Shell
All fragments that determine the device according to os.platform()
```

**Comment by jrandolf** [comment]
Could you provide a sample script?

**Comment by SunPodder** [comment]
@jrandolf what do you mean by sample script? We are trying to install it through `npm`/`yarn`.

Here is the error
```
$ yarn add puppeteer
yarn add v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error /data/data/com.termux/files/home/discord-chess/node_modules/puppeteer: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: /data/data/com.termux/files/home/discord-chess/node_modules/puppeteer
Output:
/data/data/com.termux/files/home/discord-chess/node_modules/puppeteer-core/lib/cjs/puppeteer/util/assert.js:28
        throw new Error(message);
              ^

Error: Unsupported platform: android
    at assert (/data/data/com.termux/files/home/discord-chess/node_modules/puppeteer-core/lib/cjs/puppeteer/util/assert.js:28:15)
    at new BrowserFetcher (/data/data/com.termux/files/home/discord-chess/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserFetcher.js:215:44)
    at downloadBrowser (/data/data/com.termux/files/home/discord-chess/node_modules/puppeteer/lib/cjs/puppeteer/node/install.js:49:28)
    at Object.<anonymous> (/data/data/com.termux/files/home/discord-chess/node_modules/puppeteer/install.js:40:1)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by jrandolf** [comment]
Chrome installation needs to be done through Android's installer (this would be a security problem if Termux could suddenly install any application, right?). Even if Chrome is installed, I would assume you cannot render both the Node process and Chrome simultaneously due to processor throttling.

If you are trying to test websites for Android devices, there is [emulation](https://pptr.dev/api/puppeteer.page.emulate/) meant for just that.

**Comment by SunPodder** [comment]
@jrandolf you mean installing chrome apk? Though we can install that through termux, I don't think that's necessary. We have firefox inside termux which is sufficient I guess. And we can run node process and chrome simultaneously in termux. I mentioned in #9457 that I'm already running gecko web driver with python-selenium.

If still there's a issue running puppeteer on android, please mention them

**Comment by jrandolf** [comment]
If you can run both node and Chrome, then you should be able to run puppeteer if you skip downloading the binary. The error above is due to the fact that we do not support Android installations of Chrome through Puppeteer, so if you have access to the binary through Termux, just [configure](https://pptr.dev/guides/configuration) Puppeteer to use an [`executionPath`](https://pptr.dev/api/puppeteer.configuration.executablepath) set to the Chrome binary.
