### ISSUE TITLE
[Bug] view/webpack tools don't work with export maps

### ISSUE THREAD

**Issue by StrugglingAndroid** [puppeteer/puppeteer#9467]
puppeteer-core/internal/node/PuppeteerNode.js in ./node_modules/puppeteer/lib/cjs/puppeteer/puppeteer.js
puppeteer-cone/internal/puppeteer-core.js in ./node modules/puppeteer/lib/cijs/puppeteer/puppeteer.js

![3}(LZZV{DWK{9YM BSJ{N92](https://user-images.githubusercontent.com/20653456/210730734-1cd3fe4a-8626-4fb9-9784-a73a8851549d.png)

**Comment by OrKoN** [comment]
Which node + npm version version are you using? try using using at least node 14 and the latest NPM version.

**Comment by AfterFinal** [comment]
> Which node + npm version version are you using? try using using at least node 14 and the latest NPM version.

![image](https://user-images.githubusercontent.com/20653456/211764978-a866e86a-0c12-48eb-8fff-d84a9710c6de.png)

**Comment by OrKoN** [comment]
Can you share a repo demonstrating the complete TS setup you are using and the code you try to compile?

**Comment by AfterFinal** [comment]
[puppeteer-demo.zip](https://github.com/puppeteer/puppeteer/files/10390624/puppeteer-demo.zip)
it's the code file.  electron + vue

**Comment by AfterFinal** [comment]
> Can you share a repo demonstrating the complete TS setup you are using and the code you try to compile?

![image](https://user-images.githubusercontent.com/20653456/211766938-4bdbb443-3451-47db-a183-2d02f0866bdd.png)

**Comment by OrKoN** [comment]
I am not able to compile it because of different errors:

```
 ERROR  Failed to compile with 2 errors                                                                                                                                                                                                                                                                                                                                                                                          10:24:40 AM

 error  in ./node_modules/electron/index.js

Module not found: Error: Can't resolve 'fs' in '/Users/alexrudenko/Downloads/puppeteer-demo/node_modules/electron'

 error  in ./node_modules/electron/index.js

Module not found: Error: Can't resolve 'path' in '/Users/alexrudenko/Downloads/puppeteer-demo/node_modules/electron'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
	- install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "path": false }

 ERROR  Error: Build failed with errors.
Error: Build failed with errors.
    at /Users/alexrudenko/Downloads/puppeteer-demo/node_modules/@vue/cli-service/lib/commands/build/index.js:207:23
    at /Users/alexrudenko/Downloads/puppeteer-demo/node_modules/webpack/lib/webpack.js:148:8
    at /Users/alexrudenko/Downloads/puppeteer-demo/node_modules/webpack/lib/HookWebpackError.js:68:3
    at Hook.eval [as callAsync] (eval at create (/Users/alexrudenko/Downloads/puppeteer-demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/alexrudenko/Downloads/puppeteer-demo/node_modules/tapable/lib/Hook.js:18:14)
    at Cache.shutdown (/Users/alexrudenko/Downloads/puppeteer-demo/node_modules/webpack/lib/Cache.js:150:23)
    at /Users/alexrudenko/Downloads/puppeteer-demo/node_modules/webpack/lib/Compiler.js:1225:15
    at Hook.eval [as callAsync] (eval at create (/Users/alexrudenko/Downloads/puppeteer-demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/alexrudenko/Downloads/puppeteer-demo/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.close (/Users/alexrudenko/Downloads/puppeteer-demo/node_modules/webpack/lib/Compiler.js:1218:23)
    at /Users/alexrudenko/Downloads/puppeteer-demo/node_modules/webpack/lib/webpack.js:147:16
    at finalCallback (/Users/alexrudenko/Downloads/puppeteer-demo/node_modules/webpack/lib/Compiler.js:441:32)
    at /Users/alexrudenko/Downloads/puppeteer-demo/node_modules/webpack/lib/Compiler.js:458:13
    at Hook.eval [as callAsync] (eval at create (/Users/alexrudenko/Downloads/puppeteer-demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/alexrudenko/Downloads/puppeteer-demo/node_modules/tapable/lib/Hook.js:18:14)
    at onCompiled (/Users/alexrudenko/Downloads/puppeteer-demo/node_modules/webpack/lib/Compiler.js:456:21)
    at /Users/alexrudenko/Downloads/puppeteer-demo/node_modules/webpack/lib/Compiler.js:1196:17
    at Hook.eval [as callAsync] (eval at create (/Users/alexrudenko/Downloads/puppeteer-demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/alexrudenko/Downloads/puppeteer-demo/node_modules/tapable/lib/Hook.js:18:14)
    at /Users/alexrudenko/Downloads/puppeteer-demo/node_modules/webpack/lib/Compiler.js:1192:33
    at finalCallback (/Users/alexrudenko/Downloads/puppeteer-demo/node_modules/webpack/lib/Compilation.js:2787:11)
    at /Users/alexrudenko/Downloads/puppeteer-demo/node_modules/webpack/lib/Compilation.js:3092:11
    at Hook.eval [as callAsync] (eval at create (/Users/alexrudenko/Downloads/puppeteer-demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/alexrudenko/Downloads/puppeteer-demo/node_modules/tapable/lib/Hook.js:18:14)
    at /Users/alexrudenko/Downloads/puppeteer-demo/node_modules/webpack/lib/Compilation.js:3085:38
    at eval (eval at create (/Users/alexrudenko/Downloads/puppeteer-demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at eval (eval at create (/Users/alexrudenko/Downloads/puppeteer-demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
````

Can you share your package-lock.json?

**Comment by AfterFinal** [comment]
[yarn.zip](https://github.com/puppeteer/puppeteer/files/10390781/yarn.zip)


>

**Comment by AfterFinal** [comment]
> [yarn.zip](https://github.com/puppeteer/puppeteer/files/10390781/yarn.zip)
> 
> >
no package-lock.json.  only a file named 'yarn.lock'

**Comment by AfterFinal** [comment]
yarn
yarn electron:serve

**Comment by AfterFinal** [comment]
It's an electron project

**Comment by AfterFinal** [comment]
> 

I'm sorry but I'm in a hurry to catch a bus, Probably can not reply in time。I'll reply as soon as I reach home

**Comment by OrKoN** [comment]
Able to confirm the issue but I am not sure we will fix it on our side. It looks like webpack/vue tooling does not support export maps in the same way as npm/yarn https://github.com/puppeteer/puppeteer/blob/main/packages/puppeteer-core/package.json#L14 cc @jrandolf

**Comment by AfterFinal** [comment]
Any way, thanks a lot. Please let me know if the bug fixed.

**Comment by AfterFinal** [comment]
> Able to confirm the issue but I am not sure we will fix it on our side. It looks like webpack/vue tooling does not support export maps in the same way as npm/yarn https://github.com/puppeteer/puppeteer/blob/main/packages/puppeteer-core/package.json#L14 cc @jrandolf

Besides, puppeteer-core is ok. Is there any difference between puppeteer and puppeteer-core  that cause the problem？

**Comment by OrKoN** [comment]
puppeteer imports those internal classes that are not found by webpack from puppeteer-core.

**Comment by jrandolf** [comment]
This is an issue with [`vue-cli-plugin-electron-builder`](https://github.com/nklayman/vue-cli-plugin-electron-builder). They use an outdated version of webpack, so we suggest filing a bug with them.

**Comment by AfterFinal** [comment]
Thanks a lot

**Comment by AfterFinal** [comment]
@OrKoN I found that puppeteer@18.1.0 and lower versions is ok. Can you check for more details about this issue ?

**Comment by AfterFinal** [comment]
Besides,  the page weibo.com got intto circular redirection and only white page shown when puppeteer>18.10

**Comment by OrKoN** [comment]
@AfterFinal back in 18.1.0 we didn't use export maps. weibo.com seems to work fine for me:

```
import puppeteer from 'puppeteer';

const browser = await puppeteer.launch({
    headless: false,
});
const page = await browser.newPage();
await page.goto('https://weibo.com');
await page.screenshot({path: 'weibo.png'});

await browser.close();
```

If you believe there is a bug, please open a repro with a minimal reproducible example.

**Comment by AfterFinal** [comment]
OK, thanks!
