### ISSUE TITLE
[Bug]: Puppeteer raises protocol error when evaluating a promise that throws in Firefox

### ISSUE THREAD

**Issue by pyoor** [puppeteer/puppeteer#9478]
### Bug description

Puppeteer raises a protocol error when an evaluate statement throws from within a promise, thereby hiding the true cause of the error.

```javascript
const puppeteer = require("puppeteer");

(async () => {
  const browser = await puppeteer.launch({
    "product": "firefox"
  })

  const page = await browser.newPage()
  try {
    await page.evaluate("(async() => {await new Promise((resolve) => {throw new Error('foo')}) })()")
  } catch (e) {
    console.log(e)
  }
})()
```

### Puppeteer version

19.5.0

### Node.js version

v16.17.1

### npm version

8.15.0

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```Shell
ProtocolError: Protocol error (Runtime.evaluate): Debugger: expected Debugger.Object, got Proxy _returnError@chrome://remote/content/cdp/domains/content/runtime/ExecutionContext.sys.mjs:179:22
evaluate@chrome://remote/content/cdp/domains/content/runtime/ExecutionContext.sys.mjs:159:23

    at /home/pyoor/tools/domino-web-tests/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:230:24
    at new Promise (<anonymous>)
    at CDPSession.send (/home/pyoor/tools/domino-web-tests/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:226:16)
    at ExecutionContext._evaluateInternal (/home/pyoor/tools/domino-web-tests/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:166:18)
    at ExecutionContext.evaluate (/home/pyoor/tools/domino-web-tests/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:27)
    at DOMWorld.evaluate (/home/pyoor/tools/domino-web-tests/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:95:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  originalMessage: 'Debugger: expected Debugger.Object, got Proxy'
```

**Comment by whimboo** [comment]
This is covered by https://bugzilla.mozilla.org/show_bug.cgi?id=1702860 but unlikely to get fixed unless someone provides a patch for.

**Comment by CanadaHonk** [comment]
FYI: I submitted a patch a few weeks ago which should fix this - https://phabricator.services.mozilla.com/D167496
