### ISSUE TITLE
[Bug]: Error: spawn UNKNOWN

### ISSUE THREAD

**Issue by xuakson** [puppeteer/puppeteer#9566]
### Bug expectation

I run this command to compile my node js to exe file using pkg library
command: `pkg -t node14-win-arm64 index.js`` I got an error
Here is the error

    throw errnoException(err, 'spawn');
    ^

Error: spawn UNKNOWN
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:757:9)
    at fabricate (C:\Users\MAN\AppData\Roaming\npm\node_modules\pkg\lib-es5\fabricator.js:55:51)
    at fabricateTwice (C:\Users\MAN\AppData\Roaming\npm\node_modules\pkg\lib-es5\fabricator.js:120:5)
    at MultiStream._queue (C:\Users\MAN\AppData\Roaming\npm\node_modules\pkg\lib-es5\producer.js:266:68)
    at MultiStream._next (C:\Users\MAN\AppData\Roaming\npm\node_modules\pkg\node_modules\multistream\index.js:86:12)
    at Meter.onEnd (C:\Users\MAN\AppData\Roaming\npm\node_modules\pkg\node_modules\multistream\index.js:129:12)
    at Object.onceWrapper (node:events:627:28)
    at Meter.emit (node:events:513:28)
    at endReadableNT (node:internal/streams/readable:1359:12) {
  errno: -4094,
  code: 'UNKNOWN',
  syscall: 'spawn'
}

However when i run it like this 
`pkg -t node14-win-arm64 index.js`i dont get error , everything run nicely

only that it fails to run other other windows pc. 

Using the latest version, 
Node.js v18.13.0

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
(async () => {
          
            const browser = await puppeteer.launch();
            const page = await browser.newPage();
              await page.setContent('file.html', { waitUntil: 'domcontentloaded' });
              await page.emulateMediaType('screen');
              const pdf = await page.pdf({
                path: `./output.pdf`,
                margin: { top: '100px', right: '50px', bottom: '100px', left: '50px' },
                printBackground: true,
                format: 'letter',
                landscape: false
              }).then(() => {
               console.log("DONE")
              
              });
             
              
            
            await browser.close();
            resolve(emailLength);
          })();
```

### Error string

node:internal/child_process:413    throw errnoException(err, 'spawn'); Error: spawn UNKNOWN

### Puppeteer version

19.6.0

### Node version

Node.js v18.13.0

### Package manager

npm

### Package manager version

Nothing

### Operating system

Windows

**Comment by OrKoN** [comment]
It looks like a problem with the pkg tool. Note that we don't have arm64 binaries so that might be also the reason why it fails.

**Comment by xuakson** [comment]
> It looks like a problem with the pkg tool. Note that we don't have arm64 binaries so that might be also the reason why it fails.

Yh i guesss, anyway thanks for your concern,  i have stick to what i'm using ..
