### ISSUE TITLE
[Bug]: Error while closing the browser

### ISSUE THREAD

**Issue by bhushanlaware** [puppeteer/puppeteer#9654]
On `await browser.close();` the below error is thrown this happens when I execute a batch of tasks which opens the browser, take a screenshot and close the browser. 

```
Error: ENOENT: no such file or directory, uv_cwd
    at process.wrappedCwd (node:internal/bootstrap/switches/does_own_process_state:126:28)
    at process.cwd (/Users/bhushan/Documents/Hakcerrank/ironapck-preview-matcher/node_modules/graceful-fs/polyfills.js:10:19)
    at setopts (/Users/bhushan/Documents/Hakcerrank/ironapck-preview-matcher/node_modules/glob/common.js:89:21)
    at new Glob (/Users/bhushan/Documents/Hakcerrank/ironapck-preview-matcher/node_modules/glob/glob.js:132:3)
    at Function.glob.hasMagic (/Users/bhushan/Documents/Hakcerrank/ironapck-preview-matcher/node_modules/glob/glob.js:98:11)
    at rimraf (/Users/bhushan/Documents/Hakcerrank/ironapck-preview-matcher/node_modules/rimraf/rimraf.js:70:36)
    at /Users/bhushan/Documents/Hakcerrank/ironapck-preview-matcher/node_modules/puppeteer/lib/helper.js:169:22
    at new Promise (<anonymous>)
    at promisified (/Users/bhushan/Documents/Hakcerrank/ironapck-preview-matcher/node_modules/puppeteer/lib/helper.js:161:14)
    at ChildProcess.<anonymous> (/Users/bhushan/Documents/Hakcerrank/ironapck-preview-matcher/node_modules/puppeteer/lib/Launcher.js:156:11) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'uv_cwd'
}
```

On tracing it backwards using error stack I found the below code which is responsible for throwing this error:

```
    const waitForChromeToClose = new Promise((fulfill, reject) => {
      chromeProcess.once('exit', () => {
        chromeClosed = true;
        // Cleanup as processes exit.
        if (temporaryUserDataDir) {
          removeFolderAsync(temporaryUserDataDir)
              .then(() => fulfill())
              .catch(err => console.error(err));
        } else {
          fulfill();
        }
      });
    });
  ```
  
. Instead of checking just checking `temporaryUserDataDir` it should check if the path exists and then only it should call 
` removeFolderAsync(temporaryUserDataDir)` 

```TypeScript
// below code can't reproduce the bug but it gives the idea of what the batch process looks like. 
(async () => {
  const puppeteer = require("puppeteer");
  for (let i = 0; i < 5; i++) {
    try {
      process.chdir(react_proj);
      const testProcess = exec("yarn test");
      attachLogs(testProcess);
      await waitTillFinish(testProcess);
      const browser = await puppeteer.launch();
      const page = await browser.newPage();
      await page.goto("https://www.google.com/");
      await page.screenshot({ path: "google.png" });
      await browser.close();
    } catch (error) {
      console.log("error", error);
    }
  }
})();
```

### Error string

Error: ENOENT: no such file or directory, uv_cwd

### Puppeteer version

1.1.1

### Node version

16.14.2

### Package manager

npm

### Package manager version

8.5.0

### Operating system

macOS

**Comment by OrKoN** [comment]
Please try using the latest version and I wonder why the directory is not there, the temporaryUserDataDir flag indicates that puppeteer has created the folder for this launched instance so it must exist. Are you deleting the folder in some other way?

**Comment by OrKoN** [comment]
Unable to reproduce. Please provide more info it reproduces with the latest version. Thanks.
