### ISSUE TITLE
[Bug]: I'm trying to write a demo of puppteer but can't start Chromium

### ISSUE THREAD

**Issue by xiaosimon** [puppeteer/puppeteer#9740]
### Bug expectation

I'm trying to write a demo of puppeteer but can't start Chromium.It shows

```
Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at Object.spawn (node:child_process:757:9)
    at BrowserRunner.start (/Users/liusiyuan/Desktop/pdf/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:120:34)
    at ChromeLauncher.launch (/Users/liusiyuan/Desktop/pdf/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:97:16)
    at async /Users/liusiyuan/Desktop/pdf/index.js:4:19 {
  errno: -86,
  code: 'Unknown system error -86',
  syscall: 'spawn'
}
```

here are my codes

```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://example.com');
  await page.screenshot({ path: 'example.png' });

  await browser.close();
})();
```
I'm sure I'v install Chromium because I run `node node_modules/puppeteer/install.js` 
ps: Envirement  Mac mini m2 node.js v18.14.2

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://example.com');
  await page.screenshot({ path: 'example.png' });

  await browser.close();
})();
```

### Error string

Error: spawn Unknown system error -86

### Puppeteer version

19.7.2

### Node version

18.14.2

### Package manager

npm

### Package manager version

9.5.0

### Operating system

macOS

**Comment by Raju03-git** [comment]
I also got the same error. It's working fine for me in my local environment, but I encountered an issue when I deployed the code on a Linux-based App Service. 

Note : Also Chromium is installed in the env
Chromium is already in C:\home\site\wwwroot\node_modules\puppeteer\.local-chromium\win32-982053; skipping download.

Error: spawn UNKNOWN
2024-04-28T18:16:08.988 [Information] at ChildProcess.spawn (node:internal/child_process:413:11)
2024-04-28T18:16:08.988 [Information] at Object.spawn (node:child_process:700:9)
2024-04-28T18:16:08.988 [Information] at BrowserRunner.start (C:\home\site\wwwroot\node_modules\puppeteer\lib\cjs\puppeteer\node\BrowserRunner.js:95:34)
2024-04-28T18:16:08.988 [Information] at ChromeLauncher.launch (C:\home\site\wwwroot\node_modules\puppeteer\lib\cjs\puppeteer\node\Launcher.js:113:16)


Please assist me in resolving this Issue?
