### ISSUE TITLE
[Feature]: Let us download chrome from a mirror and configure it for pupetter

### ISSUE THREAD

**Issue by MohammadMiras** [puppeteer/puppeteer#9792]
### Feature description

Hello

I'm from Iran. I want to use Pupetter. But because of sanctions against my country, the `npm i puppeteer` encounters this error:

```
user@CompanyPc:/Temp/Pup$ npm i puppeteer
npm ERR! code 1
npm ERR! path /Temp/Pup/node_modules/puppeteer
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! ERROR: Failed to set up Chromium r1095492! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
npm ERR! Error: Download failed: server returned code 403. URL: https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/1095492/chrome-linux.zip
npm ERR!     at /Temp/Pup/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserFetcher.js:447:27
npm ERR!     at ClientRequest.requestCallback (/Temp/Pup/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserFetcher.js:565:13)
npm ERR!     at Object.onceWrapper (node:events:628:26)
npm ERR!     at ClientRequest.emit (node:events:513:28)
npm ERR!     at HTTPParser.parserOnIncomingClient (node:_http_client:701:27)
npm ERR!     at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
npm ERR!     at TLSSocket.socketOnData (node:_http_client:542:22)
npm ERR!     at TLSSocket.emit (node:events:513:28)
npm ERR!     at addChunk (node:internal/streams/readable:324:12)
npm ERR!     at readableAddChunk (node:internal/streams/readable:297:9)
```

As you can see, it's because Google API domain restricts access for us.

Please provide a mirror for the chrome, or give us the option to separately download chrome and configure it for pupetter.

**Comment by OrKoN** [comment]
Hi, thanks for the request and sorry for the trouble but Puppeteer won't provide mirrors for the browser download. You can get the browser binaries through other means and configure it to use the binary using the executable path and skip download env variables: https://pptr.dev/api/puppeteer.configuration
